### ISSUE TITLE
Backup & Restore

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#1]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:43 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/7_

----

# Stories
* As operator I want to restore a broken cluster, so that I can ensure business continuity.

# Motivation
We must ensure that if disaster strikes (human error or hardware failure alike), we can recreate the entire cluster.

# Acceptance Criteria
- [ ] Delete the etcd volumes, then recreate them from a backup
- [ ] Delete the entire cluster, then recreate it from a backup

:information_source: Migrated from Jira issue [KUBE-17](https://jtrack.removed/browse/KUBE-17)

**Comment by vlerenc** [comment]
Moved to https://github.com/gardener/etcd-backup-restore/issues/1.
