### ISSUE TITLE
Community Gardener Setup

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener#101]
# Story
- As a community developer I want to develop and contribute to project Gardener
- As a community user or operations person I want to deploy and operate my own Gardener

# Motivation
The Gardener source code has been moved to public github already but due the the lack of documentation and procedures it is very hard to set up a Gardener for development or deployment. This is however critical for getting traction in the open source community and getting contributors which help to bring project Gardener forward.

# Acceptance Criteria
- [ ] It is straightforward to install Gardener from which is it possible to install shoot clusters (with only the minimum required manual steps and configurations.
- [ ] There is documentation that explains the set up as well as the key technical background. An initial "how to contribute" section would be very helpful.
- [ ] The Gardener Dashboard shall be installed and be connected to a public IDP (e.g. Github IDP)
- [ ] There is a stable release tag for the Gardener components

# Implementation Proposal

Set up an AWS sees cluster with Kubify and install a Gardner instance in that cluster. There shall be no need to set up a Garden and a separate seed cluster. The Kubify cluster can then be configured as the seed cluster. The Dashboard should be configured with a public IDP (Github).

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] An operations person new to Gardner shall be able to deploy the described set-up without help from the Gardener team
- [ ] A new developer shall be able to make a small change to the gardener and run it without help from the Gardener team
- [ ] User documentation: Have you informed the documentation developers about user-relevant changes?

**Comment by vlerenc** [comment]
The implementation proposal carries parts of the acceptance criteria. The DoD as well and at the same time is not meeting the formal DoD requirements (DoD is no free text, but together with team and program management agreed upon items that must be checked for a story to be closed if we are to avoid additional process overhead).

**Comment by vlerenc** [comment]
@marwinski Can this ticket be closed now? Or moved to the now existing external landscape-setup repo?

**Comment by rfranzke** [comment]
Covered with https://github.com/gardener/landscape-setup, I guess.
