### ISSUE TITLE
[operator]: Adapt gardener/dashboard related code

### ISSUE THREAD

**Issue by petersutter** [gardener/gardener#10116]
**How to categorize this issue?**

/area security
/kind enhancement

**What would you like to be added**:
There were some improvements made in the latest gardener/dashboard releases that should be incorporated in the operator: 
- [ ] `experimentalUseWatchCacheForListShoots` setting can be removed (https://github.com/gardener/dashboard/pull/1822)
- [ ] dashboard supports `previousSessionSecret`, enabling seamless session rotation (https://github.com/gardener/dashboard/pull/1856)
- [x] secrets are mounted as files instead of env vars https://github.com/gardener/gardener/pull/10100
- [ ] `oidc.clientSecret` is now optional (https://github.com/gardener/dashboard/pull/1835)
- [ ] Lease object is now created during runtime if it does not exist, the corresponding code in the operator can be removed (https://github.com/gardener/dashboard/pull/1823)
- [ ] remove `get` `secret` permission for the gardener dashboard. This permission is now obsolete with the ability to display OIDC observability urls (https://github.com/gardener/dashboard/blob/3d692fb2ac6d36af93c5c8bef3aadc42b23d51b1/charts/gardener-dashboard/values.yaml#L236-L239 and https://github.com/gardener/dashboard/pull/1899)

**Why is this needed**:
To adapt to latest (non-breaking) changes introduced with gardener/dashboard [1.75.0](https://github.com/gardener/dashboard/releases/tag/1.75.0) and [1.76.0](https://github.com/gardener/dashboard/releases/tag/1.76.0)

**Comment by rfranzke** [comment]
@petersutter Will you take care of this?

**Comment by petersutter** [comment]
@grolu wanted to take care
