### ISSUE TITLE
Make VPA more configurable to improve utilisation of VPA-dependent workload

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#10141]
**What would you like to be added**:
https://github.com/gardener/gardener/pull/9279 made VPA's `--target-cpu-percentile` configurable. Now, let's please also add:
- `--recommendation-lower-bound-cpu-percentile`
- `--recommendation-upper-bound-cpu-percentile`
- `--target-memory-percentile` <-- most important
- `--recommendation-lower-bound-memory-percentile`
- `--recommendation-upper-bound-memory-percentile`

**Why is this needed**:
This is needed to improve utilisation of VPA-dependent workload.

**Comment by ialidzhikov** [comment]
FYI, the PR that introduced these flags in the upstream VPA is not yet released: https://github.com/kubernetes/autoscaler/pull/6660.
https://github.com/gardener/gardener/pull/10221 has to stay in draft mode until the new VPA release is cut and we adopt it. 🙈

**Comment by ialidzhikov** [comment]
VPA v1.2.0 has been adopted with https://github.com/gardener/gardener/pull/10275.
