### ISSUE TITLE
no matches for kind "Seed" in version "garden.sapcloud.io/v1beta1"

### ISSUE THREAD

**Issue by srinisbook** [gardener/gardener#1020]
I was deployed Gardener in gcp using landscape.

https://github.com/gardener/garden-setup

everything was successful but when creating seed cluster, im getting below error.

kubectl apply -f seed.yaml 
secret/seed-gcp unchanged
error: unable to recognize "seed.yaml": no matches for kind "Seed" in version "garden.sapcloud.io/v1beta1"

Also, in the dashboard, I'm getting error "Failed to fetch the clusters". 

Could you please help on this ?

**Comment by rfranzke** [comment]
Probably, the Gardener API server is not running properly. Please raise an issue in gardener/garden-setup.
