### ISSUE TITLE
New Alerts on ETCD DB Size (warning if predictive too large soon and error if too large)

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#1026]
**What would you like to be added**:
We have seen end users that by accident (bug) were flooding ETCD. A failure is consequently not the fault of Gardener.

**Why is this needed**:
We'd like to warn the end users about their approaching doom and to silence alerts on our end if ETCD is simply beyond our limits that we can manage today.

**Current limit**
We may want to question the performance colleagues (@nikhilsap and colleagues), but the limit may be around 500-1000 MB at present without proper vertical pod autoscaling for ETCD (cc @PadmaB @amshuman-kr @swapnilgm @shreyas-s-rao).

**Comment by swapnilgm** [comment]
@PadmaB Will you please include this in your work around alerts for backup failure?

**Comment by vlerenc** [comment]
I think the warning/alerting part is covered already by @wyb1 , right @dkistner?

**Comment by dkistner** [comment]
Yes it is possible to distinguish between user and operator related alerts, but we did not have any backup/restore alerts yet integrated.

**Comment by rfranzke** [comment]
What's the status here?

**Comment by swapnilgm** [comment]
It was supposed to be added in backup alerts PR. But not added yet.  @shreyas-s-rao Please add this alert as well.
/assign @shreyas-s-rao
