### ISSUE TITLE
Link to configuration of SMTP alerting is broken

### ISSUE THREAD

**Issue by freegroup** [gardener/gardener#1027]
The page [Cluster Alert Configuration](https://github.com/gardener/gardener/blob/master/docs/usage/shoots.md#configure-a-shoot-cluster-alert-receiver) describes how to setup an SMTP alert for the shoot.

Unfortunately, the link to the configmap example is broken.

<img width="919" alt="Bildschirmfoto 2019-05-22 um 10 45 13" src="https://user-images.githubusercontent.com/1155039/58160427-bff8fc00-7c7e-11e9-9d77-134d54dc9274.png">

Question: why is this page not part of the official [Gardener Documentation](https://gardener.cloud/blog/)? A good place could be the [Admin section](https://gardener.cloud/using-gardener/administrator/). I think it is a good idea
to aggregate the documentation in the gardener page.

**Comment by freegroup** [comment]
I moved the page to the Gardener Landing Page 

 - [Rendered Version](https://gardener.cloud/050-tutorials/content/howto/create-delete-shoot/) for the enduser
 - [Markdown Version](https://github.com/gardener/documentation/blob/master/website/documentation/050-tutorials/content/howto/create-delete-shoot/_index.md) to edit/update the content


I think it is a good idea to delete the page https://github.com/gardener/gardener/blob/master/docs/usage/shoots.md#configure-a-shoot-cluster-alert-receiver and maintain the one in the gardener documentation.

**Comment by ialidzhikov** [comment]
Why the same content is duplicated in gardener/documentation repo? Can't we just reference from gardener/documentation the docs/usage/shoots.md file in gardener/gardener?

**Comment by freegroup** [comment]
I can link any "md" file. But unfortunately the files are moved or delete without notice and
the documentation is broken.

Question: why this "md" exists? We can maintain just the file in the documentation repo.
or?

**Comment by ialidzhikov** [comment]
> Question: why this "md" exists? We can maintain just the file in the documentation repo.
or?

Yep, operations/end user docs can be/should be moved and maintained in g/documentation. After gardener/documentation#51 is resolved, we can remove the `docs/usage/shoots.md` file.
