### ISSUE TITLE
Calico version 3.7.2 breaks networking on Azure

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener#1032]
**What happened**:

Pull request https://github.com/gardener/gardener/pull/1018 breaks networking on Azure.

**What you expected to happen**:

Pods on different nodes can communicate with each other. They cannot however with this pull request.

**How to reproduce it (as minimally and precisely as possible)**:

Azure (seed) cluster when updated from the old calico version. It may be required to add new nodes after the update to calico 3.7.2 to trigger this issue (not enough details known so far).

**Anything else we need to know?**:

The problem is that "something" messes with the route tabes on Azure. They look ok at first sight but when looking deeper they forward the wrong CIDR ranges to the wrong node ip. We did observe this with Calico 3.7.2 but not with v3.4.0 (the CIDRs matched the nodes where the pods were actually running on).

IMPORTANT: Downstream Azure clusters must not be updated with this version.

**Environment**:

- Calico version 3.7.2

**Comment by dkistner** [comment]
Up to Calico 3.4.0 it use the cidr ranges on the node object which is controlled by the cloud controller manager. CCM uses this range to propagate the routing table. We verified Calico 3.7.2 uses different ranges. Also seen on Azure and AWS.
Since the node cidr is used to propagate the route table on Azure this breaks networking.
On AWS the CCM does not use the information in the route table.

**Comment by timuthy** [comment]
Calico IPAM (https://github.com/gardener/gardener/pull/1018/files#diff-9db9994a19aaf3eff63107a3e00c85d6R33) does not work on Azure.

Unfortunately, the [recommended](https://docs.projectcalico.org/v3.7/reference/public-cloud/azure) Azure IPAM plugin does also not work in combination with the Calico plugin.
If we want switch from `host-local` IPAM on Azure we're also required to switch to Azure CNI which has not been tested yet from our side and implies bigger code changes.

For the moment we can either stick with `host-local` solely for Azure or for all infrastructures.
