### ISSUE TITLE
Dependecy inconsistency caused by `replace`

### ISSUE THREAD

**Issue by HappyHacker123** [gardener/gardener#10490]
**How to categorize this issue?**

/area robustness
/kind technical-debt

**Why is this needed**:
Currently `gardener` depends on `github.com/gardener/etcd-druid v0.22.5` but does not follow to use the `replace` directive declared in its go.mod as below. `etcd-druid` uses replace directive to pin `google.golang.org/grpc` to version `v1.29.0`.
```
replace google.golang.org/grpc => google.golang.org/grpc v1.29.0
```

According to [Go Modules wikis](https://go.dev/doc/modules/gomod-ref#replace-notes), `replace` directives in modules other than the main module are ignored when building the main module. It means such replace usage in go.mod cannot be inherited by downstream projects automatically.  Consequently, `gardener's` version of `google.golang.org/grpc` is v1.62.1, different from the pinned version `etcd-druid` needed.

**What would you like to be added**:
Add the same replace directive to `gardener` go.mod to make it consistent with `gardener/etcd-druid`'s need.

```
replace google.golang.org/grpc => google.golang.org/grpc v1.29.0
```

**Comment by HappyHacker123** [comment]
Could you please take a look at this issue @Kostov6 @rfranzke  :)? Many thanks

**Comment by plkokanov** [comment]
@HappyHacker123 we only use the `etcd-druid` api definitions from the `gardener/etcd-druid` package - so grpc version used by `gardener/etcd-druid` should not matter at all when building gardener. 

On the other hand, some packages that are used by `gardener/gardener` actually seem to depend on the newer grpc version.  Adding the replace directive results in the following error:
```
go: github.com/gardener/gardener/pkg/nodeagent/controller/healthcheck imports
        github.com/containerd/containerd imports
        google.golang.org/grpc/credentials/insecure: module google.golang.org/grpc@latest found (v1.66.1, replaced by google.golang.org/grpc@v1.29.0), but does not contain package google.golang.org/grpc/credentials/insecure
```

Please also check this issue on `etcd-druid` side for separating the api packages due to the current circular dependency (`gardener` importing `etcd-druid` and `etcd-druid` importing `gardener`): https://github.com/gardener/etcd-druid/issues/508

**Comment by plkokanov** [comment]
Btw @shreyas-s-rao do you have any eta on https://github.com/gardener/etcd-druid/issues/508? I see that it is currently blocked.

@HappyHacker123 can we close this issue for now?

**Comment by shreyas-s-rao** [comment]
From etcd-druid side, with v0.23.0 release we have already moved everything from `pkg` to `internal`, so only the API package is to be used by gardener. This already breaks the cyclic dependency between the two, meaning gardener's grpc version should no longer be affected by druid's grpc version. Druid is updated to v0.23.0 in #10526 , which is currently in progress.

**Comment by marc1404** [comment]
As `gardener/gardener` is using `etc-druid` version `v0.24.1` which doesn't include the `replace` directive anymore this issue can be closed as resolved. ([ref](https://github.com/gardener/gardener/blob/516df3477c2373e1c786bcea62cbd28415661a0b/go.mod#L16))

/close
