### ISSUE TITLE
Admin Password Reset

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#105]
# Story
- As user I want to reset the password, so that I can change it if it leaked.

# Motivation
Users sometimes/accidentally leak their admin password.

# Acceptance Criteria
First we must answer the question whether we like to just reset it or also set it, i.e.
- [ ] User can request admin password regeneration through the shoot cluster resource

or
- [ ] User can set the admin password through the shoot cluster resource

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual test tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests or added manual test tickets?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the operations guide about ops-relevant changes?
- [ ] User documentation: Have you informed the documentation developers about user-relevant changes?

**Comment by rfranzke** [comment]
What do you think about using an annotation as trigger to do that? The user puts e.g. `garden.sapcloud.io/operation=reset-password` on the Shoot, and the Gardener does the same and removes the annotation after that.

**Comment by vlerenc** [comment]
Yes, that sounds reasonable. Much like with initializers/finalizers. They trigger an action/operation and remove themselves afterwards. This allows for some loose coupling as well.

Let's spin this idea further, would it also help with hibernation/wake-up? That's the other story that jumps to mind that is similar in nature?

**Comment by rfranzke** [comment]
Hm, regarding hibernation/wake-up I guess it's actually safer to have a dedicated field in the `Shoot` resource. Otherwise it would be hard to identify whether the Shoot is currently hibernated or not.

**Comment by vlerenc** [comment]
OK, sounds reasonable. I guess I was coming from the angle: controller sees annotation, stores/parks current max/mins in another annotation, sets them all to zero. Wake-up is similar.

However, that's not a smart idea as Gardener already needs to "understand" hibernation (it also hibernates the non-essential control plane), so already carries specific code for that. Also, this way we don't have to consider changes to the worker pools while in hibernation.

Yes, the spec field sounds much better, thank you!

**Comment by grolu** [comment]
Stakeholders started asking for this feature. What also should be part of this, is reset of CA / Certificates as kubeconfig would continue to work even if password has been reseted.
Moreover, this is not only required in case of accidentally leaking credentials. Stakeholders also pointed out that this feature is important to them, as they want tor reset cluster credentials when users with access leave their team. This is a critical feature for them if they want to go live.

**Comment by muvaf** [comment]
We need this as well. The use case is more or less similar with @grolu 's comments.
