### ISSUE TITLE
Could not create route for hollow node in kubemark

### ISSUE THREAD

**Issue by nikhilsap** [gardener/gardener#1050]
**What happened**:
I have implemented kubemark in gardner, using kubemark's pre-existing cluster configuration.
As a part of framework, the hollod-pods got deployed in the cluster and registered as nodes also.
But when i do `kubectl describe node hollow-node`,i can see this error.

`Warning FailedToCreateRoute 9s route_controller Could not create route f26a850b-81ee-11e9-a072-b2f06bc2a29d 100.96.99.0/24 for node hollow-node-4kc9s after 486.555595ms: instance not found`

This node is not able to schedule any pods in it.

**What you expected to happen**:
The hollow-node should able to schedule the pods.

**How to reproduce it (as minimally and precisely as possible)**:
Use kubemark for pre-existing cluster and pass proper configuration in cloud-provider-config file.
**Anything else we need to know?**:
I have already raised [the issue](https://github.com/kubernetes/kubernetes/issues/78483) in the k8s community. 
but i feel. this warning might be related PodCIDR range and NodeCIDR range defined for the gardener. As kubemark, creates the pod and registers that pod as hollow-node in the cluster. 
cloud controller manager log 
`0530 04:50:17.109263       1 route_controller.go:199] Could not create route 68583bf4-8296-11e9-a072-b2f06bc2a29d 100.96.137.0/24 for node hollow-node-6msrn: instance not found
E0530 04:50:19.078058       1 gce_instances.go:482] Failed to retrieve instances: [hollow-node-bvf9s hollow-node-zpsx9 hollow-node-6msrn hollow-node-rkmr2]`

**Environment**:

- Gardener version:
0.21.0
- Kubernetes version (use `kubectl version`):
` Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
GCP
- Others:

**Comment by nikhilsap** [comment]
We have tweaked the cloud controller flag `--configure-cloud-routes="false"` and stopped the reconciliation in the cluster.
We are now able to deploy the hollow-pods and those pods are registered as hollow-nodes in the cluster and able to schedule normal pods in the hollow-nodes. 

![image](https://user-images.githubusercontent.com/41104107/58700539-effe7880-83bd-11e9-99cb-2589d76ba023.png)


Thanks @amshuman-kr for the help and you can share the futuristics idea to use kubemark on gardner as we discussed.

**Comment by rfranzke** [comment]
@nikhilsap what do you suggest? Should anything be improved on Gardener side or can this ticket be closed?

**Comment by nikhilsap** [comment]
For now Closing this as nothing need to change in Gardener side.
