### ISSUE TITLE
Gardener dashboard does not show the right cluster status

### ISSUE THREAD

**Issue by IliyanVidenov** [gardener/gardener#1051]
Adding an annotation "shoot.garden.sapcloud.io/ignore: true" changed the status of the shoot to "Reconciliation Deactivated" but the reconciliation didn't stop on Canary landscape.

**Comment by ialidzhikov** [comment]
Thanks for reporting.
An issue about that already exists in gardener/dashboard repo - gardener/dashboard#386. You could subscribe for it.

I think we can close this one as duplicate.

**Comment by IliyanVidenov** [comment]
Okay, thanks for the fast response. I'm closing it.
