### ISSUE TITLE
Adding an annotation "shoot.garden.sapcloud.io/ignore: true" didn't stop reconciliation on Canary landscape.

### ISSUE THREAD

**Issue by IliyanVidenov** [gardener/gardener#1052]
**What happened**: The Shoot reconciled again.

**What you expected to happen**: The shoot should stop its reconciliation

**How to reproduce it (as minimally and precisely as possible)**: Add "shoot.garden.sapcloud.io/ignore: true" to your cluster and it will reconcile again

**Anything else we need to know?**:
I am part of the Continuum team. Our Shoots should not reconcile, or better, they should start reconciling only in the maintenance window. We are afraid of small outages that could happen.

**Account**: garden-ias

**Shoot**: ias5

**Environment**: Canary

- Gardener version: 1.31.2
- Kubernetes version (use `kubectl version`): 1.12.9
- Cloud provider or hardware configuration: AWS
- Others:

**Comment by ialidzhikov** [comment]
Thanks for reporting.

As described in #1035

> Also `controllers.shoot.respectSyncPeriodOverwrite` property of Gardener controller manager needs to be `true`, otherwise the ignore annotation won't be respected.

and you hit this case.

The issue for reconciling only in maintenance time window is #251.

**Comment by IliyanVidenov** [comment]
As I understand, this is not possible on Canary for now. I don't know much about Gardener implementation but what about moving this property to the project controller? That way the number of clusters which are out of sync would be reduced and it won't be necessary to stop overriding the sync period on a whole landscape.

**Comment by rfranzke** [comment]
Hi @IliyanVidenov, this feature was originally only meant for development purposes (and is still). We cannot allow this to be used on productive landscapes. If clusters are not reconciled for various weeks we cannot ensure anymore that we can update them with newer Gardener versions. For example, take the recent etcd volume migration: The migration code has been introduced with the last version and will be removed in a new version soon. If a cluster would not be reconciled during that time the whole migration for this cluster would be skipped, and the new Gardener version does not have the migration code anymore. In such situations these clusters get out-of-sync and cannot be brought into the desired state automatically/without manual intervention. While this is OK for dev. clusters it is definitely not for production clusters. The only real solution would be to implement #251, sorry.

**Comment by IliyanVidenov** [comment]
Hi @rfranzke, basically we need the feature described in #251. Unfortunately, as I understand the task is blocked for now but we need #251 working (or something similar to it) in August.
