### ISSUE TITLE
Drop GRM `TokenInvalidator` controller when we drop support for shoots with version <= 1.26

### ISSUE THREAD

**Issue by Kostov6** [gardener/gardener#10589]
**How to categorize this issue?**

/area quality
/kind cleanup

**What would you like to be added**:
As in 1.27 `LegacyServiceAccountTokenNoAutoGeneration` becomes `LockToDefault: true` [ref](https://github.com/kubernetes/kubernetes/blob/v1.27.0/pkg/features/kube_features.go#L1053C2-L1053C43), after https://github.com/gardener/gardener/issues/10339 we can drop related code to the `TokenInvalidator` controller

**Why is this needed**:
Drop unneeded code

**Comment by ialidzhikov** [comment]
@rfranzke, can you also confirm that it is safe to drop the TokenInvalidator controller and webhook from GRM after https://github.com/gardener/gardener/issues/10339? Thanks in advance!

**Comment by rfranzke** [comment]
@Kostov6 @ialidzhikov Yes, after we drop support for Kubernetes < 1.27, it should be safe to also drop the TokenInvalidator completely. Thanks for keeping track of this! 🙇🏻

**Comment by shafeeqes** [comment]
I can do it as a part of https://github.com/gardener/gardener/issues/10339.
/assign

**Comment by shafeeqes** [comment]
Added it as a task in https://github.com/gardener/gardener/issues/10339.
Let's close this one.
/close
