### ISSUE TITLE
Rolling Update MaxInFlight (per worker pool)

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#106]
# Story
- As user I want to define/cap the number of machines that are under parallel update/in parallel drain, so that I can tweak it to my applications/workload.

# Motivation
When we create N new machines, we drain N old machines in parallel. Kubernetes does a great job in respecting the pod disruption budgets, but we will only wait at most 5 minutes for the machine to be drained before terminating it forcefully. If a pod requires a lot of time to pull its image or startup, this could lead to downtimes/violated pod disruption budgets.

Example: ReplicaSet of 3, PDB of 1, pod anti-affinity on the hostname, average startup time of 3 minutes. The user can at most have 2 machines in flight. If he has more in flight, all pods could be on those machines and since only 1 pod could be drained within the 5 minutes, 2 pods would be gone at once when the machine controller manager terminates all not fully drained machines.

# Acceptance Criteria
- [ ] User can set the maximum number of machines that are under parallel update/in parallel drain (per worker pool)

# Implementation Proposal
The maxInFlight value should be rendered into the machine deployment `.spec.startegy. rollingUpdate` section. I am wondering though @hardikdr and @prashanth26 whether this really maps to `maxSurge`? Can we discuss the meanings please in this ticket and decide how to ensure that the user can directly influence the number of machines that are "in parallel flight" at any given point in time?

# Resources
- See https://github.com/gardener/machine-controller-manager/issues/52#issuecomment-370729530 (this and the following comments)
- See https://github.com/gardener/machine-controller-manager/blob/master/kubernetes/machine-deployment.yaml#L17

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual test tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests or added manual test tickets?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the operations guide about ops-relevant changes?
- [ ] User documentation: Have you informed the documentation developers about user-relevant changes?

**Comment by rfranzke** [comment]
@hardikdr and @prashanth26 can you please comment here?
Would it be correct from your point of view to let the `.spec.strategy.rollingUpdate.maxSurge` be configurable per worker pool in the shoot? Currently, we [hard-code it to `1`](https://github.com/gardener/gardener/blob/master/charts/seed-machines/charts/machines/values.yaml#L6).
What are thoughts on `.spec.strategy.maxUnavailable` (currently ["hard-coded" to `0`](https://github.com/gardener/gardener/blob/master/charts/seed-machines/charts/machines/values.yaml#L7))?

**Comment by prashanth26** [comment]
I think that it would be better if users could configure this on the dashboard as an advanced configuration (something that is hidden by default, as users already kind of are confused with the concept of multiple worker pools) . We could default this to marSurge=1 and maxUnavailable=0 and keep it only as an advanced option.

**Comment by rfranzke** [comment]
Agreed, this we will anyway do. I was more asking about whether it is correct to only expose `maxSurge`. Do we also have to expose `maxUnavailable`?

**Comment by prashanth26** [comment]
I think exposing both would be better as it would offer more flexibility to the customers. I think some one who understands marSurge would also understand maxUnavailable (or at-least read upon it).
