### ISSUE TITLE
Be able to specify extended resources in worker pools

### ISSUE THREAD

**Issue by dhague** [gardener/gardener#10652]
**How to categorize this issue?**
/area auto-scaling
/kind enhancement

**What would you like to be added**:
In standard Kubernetes, [Extended resources](https://kubernetes.io/docs/tasks/administer-cluster/extended-resource-node/) can be assigned to a Node once it exists. If a pod requests such extended resources then the cluster autoscaler will add a node if required, but **only if there are existing nodes with such resources** already in the cluster. 
By allowing such extended resources to be defined in a `WorkerPool`, these can be added to the `nodeTemplate.capacity` to inform the cluster autoscaler of the resources even if the pool size is zero.

**Why is this needed**:
This will add the ability for worker pools to scale from zero based on requests for extended resources.

**Comment by LucaBernstein** [comment]
/assign @ashwani2k
Could you please check with the MCM autoscaling team how feasible this approach is?

**Comment by voelzmo** [comment]
This seems to be the same requirement as captured in https://github.com/gardener/autoscaler/issues/132.
The MCM colleagues are aware of this and currently working on the modifications necessary for the AWS extension https://github.com/gardener/gardener-extension-provider-aws/issues/1009

ping @elankath FYI

**Comment by elankath** [comment]
@dhague  @voelzmo  yes, this is planned for Q4.

**Comment by dhague** [comment]
Awesome, thanks!
