### ISSUE TITLE
`Gardenlet` can be created with a missing `ingress` field in `GardenletConfiguration`

### ISSUE THREAD

**Issue by Kostov6** [gardener/gardener#10679]
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
It is possible to create a `Gardenlet` resource with a missing `ingress` field that leads to failure of the `gardenlet` pod

**What you expected to happen**:
Not be able to create `Gardenlet` that results in failure

**How to reproduce it (as minimally and precisely as possible)**:
In the local setup
1.  `make kind-operator-up operator-up`
2. Delete the `ingress` field from the following file https://github.com/gardener/gardener/blob/d4250c11cb5eabf85f48fce830174345de2543f0/example/gardener-local/gardenlet/operator/gardenlet.yaml#L37-L40
3. `make operator-seed-up`

The following happens
```
$ k get gardenlet -A
NAMESPACE   NAME    OCI REPOSITORY                                                               RECONCILED   AGE
garden      local   localhost:5001/local-skaffold_gardenlet_chart:v1.106.0-dev-bbbc6b75e-dirty   <unknown>    4s

$ k -n garden get pod
...
gardenlet-5df5bdb8b-spckh                                   0/1     CrashLoopBackOff   5 (80s ago)    4m26s
gardenlet-6cff988785-kp8cd                                  0/1     CrashLoopBackOff   5 (110s ago)   4m56s
gardenlet-6cff988785-vv4zm                                  0/1     CrashLoopBackOff   5 (111s ago)   4m56s
...

$ k -n garden logs gardenlet-5df5bdb8b-spckh
...
panic: could not register seed "local": Seed.core.gardener.cloud "local" is invalid: spec.ingress: Required value: cannot be empty

goroutine 1 [running]:
main.main()
	github.com/gardener/gardener/cmd/gardenlet/main.go:20 +0x58
```

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by acumino** [comment]
Fixed in https://github.com/gardener/gardener/pull/10655
/close
