### ISSUE TITLE
Move Seed controller to the API server

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#107]
[APIService](https://github.com/kubernetes/kube-aggregator/tree/5cfc5c4c8c903e1886b9a54678d0837d9cdd9e2f/pkg/controllers/status) as part of `kube-aggregator` has the controller which reconciles its `status` in the `aggregator-apiserver`. Following the same pattern, [seed-controller](https://github.com/gardener/gardener/tree/8446cd54eef1514992757f944850fdc34aa42c83/pkg/controller/seed), should be moved to the `gardener-apisever`. 

This will allow to create `Shoot` resources even without a running `gardener-controller-manager`.

**Comment by rfranzke** [comment]
It is possible to create Shoots also without running the gardener-controller-manager by specifying a value in the Shoot's `.spec.cloud.seed` field. Only when it's not specified the "SeedManager" admission controller in the gardener-apiserver will try to find a Seed and only considering those whose status indicates availability.

The seed controller does not only update the status but also bootstrap the Seeds. If we want to put the 'status' updating part into the gardener-apiserver we have to split the controller. I don't want to do that right now. Maybe we can revisit the topic in a few months when we have more capacity for minor improvements like this.
Hence, let's not do that and close the ticket therefore.
