### ISSUE TITLE
Cert Manager Extension cannot be cleaned up when shoot deletes

### ISSUE THREAD

**Issue by adracus** [gardener/gardener#1070]
**What happened**:
Cleaning up the extensions for a deleting Shoot with Cert Manager errors with
```
Flow "Shoot cluster deletion" encountered task errors: [task "Waiting until extension resources have been deleted" failed: 1 error occurred:
	* Failed waiting for extension delete: Error deleting Extension resource: Error getting Gardener secret from namespace <shoot ns>: Secret "gardener" not found

 task "Waiting until Shoot namespace in Seed has been deleted" failed: retry failed with context deadline exceeded, last error: namespace "<shoot ns>" is not yet cleaned up]
```

**What you expected to happen**:
The Shoot should be properly deleted.

**How to reproduce it (as minimally and precisely as possible)**:
Create a Shoot with Cert Manager enabled. Delete it again. This only happens for some of the clusters.

**Anything else we need to know?**:
I anticipate this happens due to a race condition where `Waiting until extension resources have been deleted` and `Waiting until Shoot namespace in Seed has been deleted` in the Shoot deletion flow. The namespace shouldn't be deleted if the extension still is reconciling.

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timuthy** [comment]
Fixed in #1071
