### ISSUE TITLE
Support Service Account Token Volume Projection

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener#1073]
**What would you like to be added**:
Allow the user to configure the following flags on the `kube-apiserver`
```shell
--service-account-issuer
--service-account-signing-key-file
--service-account-api-audiences
````
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection

For clusters older than `1.12` the `ServiceAccountTokenVolumeProjection` feature gate needs to be activated .

**Comment by adracus** [comment]
@afritzler in the shoot API, under `.spec.kubernetes.kubeAPIServer.runtimeConfig`, we already support entering arbitrary values for the runtime configuration of the Shoot's Kube-APIserver - is that enough?

**Comment by rfranzke** [comment]
This only configures the `--runtime-config` flag.

**Comment by adracus** [comment]
Ah, sorry, my bad - then I'll just introduce it.
