### ISSUE TITLE
Cleanup Provider Type Predicate

### ISSUE THREAD

**Issue by LucaBernstein** [gardener/gardener#10745]
**How to categorize this issue?**

/area usability
/kind cleanup

**What would you like to do**:
In the extension webhooks, we introduced `ObjectSelectors` that target/filter objects having labels, e.g. the provider type label. Additionally, we still have `Predicates` that we also use to target the provider type.

To resolve this duplicate check, we could remove the `Predicate` to check for the provider type in favor of the `ObjectSelector` checking the provider type label.

Example usage: https://github.com/gardener/gardener-extension-provider-azure/blob/e73fff32b2d917b269056488e29bf4eeb37513fc/pkg/admission/mutator/webhook.go#L34

/cc @timuthy 

**Why is this needed**:
Cleanup the duplicate check for an object's provider type.

**Comment by shafeeqes** [comment]
Yeah, I guess we can get rid of the predicate now that all extensions are adapted. Thanks for cleaning this up.

**Comment by LucaBernstein** [comment]
* [ ] provider-azure: https://github.com/gardener/gardener-extension-provider-azure/pull/998
* [ ] provider-aws
* [ ] provider-gcp
* [ ] provider-openstack
* [ ] provider-alicloud
* [ ] provider-ironcore
