### ISSUE TITLE
clusterAutoscaler: Add support for `statusTaints` option mapping to `--status-taints` flag

### ISSUE THREAD

**Issue by dhague** [gardener/gardener#10844]
**How to categorize this issue?**
/area auto-scaling
/kind enhancement

**What would you like to be added**:
In a shoot's `spec.kubernetes.clusterAutoscaler` map a `statusTaints` option should be added, functioning very similarly to the `ignoreTaints` option.

**Why is this needed**:
The `--ignore-taints` flag mentioned in https://github.com/gardener/gardener/issues/5166 [is now deprecated](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#ignore-taints) in favour of `--startup-taints` and its semantics have changed accordingly, such that any nodes with such a taint are considered unready by the cluster autoscaler (CA). This can cause the CA to stop working entirely if there are too many nodes with such taints.
Access to the new flag `--status-taints` is needed in order to restore the original functionality where the CA ignores the taint, but it does not affect the CA's view of node readiness.
At the same time, it is probably a good idea to deprecate `ignoreTaints` and support `startupTaints`.

**Comment by shafeeqes** [comment]
cc @rishabh-11 @unmarshall @aaronfern
