### ISSUE TITLE
Shoot stuck in deletion in a edge case

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1089]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Shoot and ensure that the creation passes successfully.
2. HIbernate the Shoot and ensure that all CP components are scaled down to 0.
3. Un-hibernate the shoot and trigger the deletion in the same time.
4. Ensure that the deletion stucks in `Initializing connection to Shoot` waiting kube-apiserver to be responsible but it is scaled down to 0.

**Anything else we need to know?**:

**Environment**:

- Gardener version: 0.23.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
cc @timuthy 
i guess we can easily resolve this when you introduce the new field in the shoot status that indicates whether the shoot is really hibernated or not (while the `.spec.hibernation.enabled` just defines the desired state from the user)

**Comment by timuthy** [comment]
@rfranzke absolutely! I'll take care of this. Thanks for reporting @ialidzhikov.
