### ISSUE TITLE
GCP prerequisite: Role "service account actor" deprecated

### ISSUE THREAD

**Issue by burreo** [gardener/gardener#109]
According to the documentation Service account needs to have the role

> Ensure that the service account has at least the roles below.
Service Account Admin
**Service Account Actor**
Compute Admin

I got to know that the role „Service Account Actor” doen't exist and is deprecated according to https://cloud.google.com/iam/docs/service-accounts 
and the role „Service Account User“ should be used.

**Comment by rfranzke** [comment]
Thanks, that's already fixed in the [latest version of the Gardener dashboard](https://github.com/gardener/dashboard/blob/a178b9bc0690f0e6008b09f1e9e75c79c178056b/frontend/src/dialogs/SecretDialogGcpHelp.vue#L33-L39).
