### ISSUE TITLE
Clean up of Shoot resources with finalizers

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1100]
Currently the Shoot deletion could be be blocked at `Cleaning kubernetes resources
` step if there is a controller and various objects have finalizers of this controller. The deletion flow can delete the controller pods and the objects with the finalizer can hang.

I managed to reproduce with rancher chart installation:
1. Create a Shoot.
2. Follow the steps at https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/ and install the rancher chart.
3. Create several ns and ensure that they have the `controller.cattle.io/namespace-auth` finalizer.
4. Trigger shoot deletion and ensure that the namespaces created in 2. can hang in Terminating

**Comment by rfranzke** [comment]
@adracus I understood that this is desired for the moment, right? We only forcefully delete the CRDs or APIServices, correct?
Should we forcefully remove finalizers from all resources after `5m`? What speaks against this?

**Comment by adracus** [comment]
Yes, that's right. What speaks against this: Until now, by doing this and manually investigating for each 'stuck' Shoot, we 'protected' our customers from deleting unwanted resources by pinging them if some of them had an issue. However, since we anyways also finalize `CRD`s and `APIService`s, I'd also be up to finalizing the remaining resources.

**Comment by rfranzke** [comment]
> However, since we anyways also finalize CRDs and APIServices, I'd also be up to finalizing the remaining resources.

Yes, I guess that's the point. We already do this for CRDs and APIServices, so, with the same argument/reasoning we can do it for everything else as well, I think.
