### ISSUE TITLE
Support configuring `skip-nodes-with-local-storage` via `shoot`

### ISSUE THREAD

**Issue by JorTurFer** [gardener/gardener#11042]
**How to categorize this issue?**

/area auto-scaling
/kind enhancement

**What would you like to be added**:
Currently, the cluster autoscaler behaviour can be customized [via shoot spec](https://github.com/gardener/gardener/blob/master/docs/api-reference/core.md#core.gardener.cloud/v1beta1.ClusterAutoscaler) and it's nice, but not all the fields can be configured using the mechanism.  
In our use case, we'd need to set `skip-nodes-with-local-storage=true` and checking gardener autoscaler, [it supports it](https://github.com/gardener/autoscaler/blob/45e190f4bd7890e0029bef8eb9affa0946f135d5/cluster-autoscaler/FAQ.md?plain=1#L826). The current problem is that the [shoot spec doesn't expose that specific flag](https://github.com/gardener/gardener/blob/d898b88b5b7c0c089b8b7b3a94d996c4afb46eee/pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go#L428-L486)

**Why is this needed**:
There are multiple admission webhooks that injects an **emptyDir** volume using the node storage (e.g: Linkerd), and this is treated as a local volume. **emptyDir** is an ephemeral storage indeed, but the cluster autoscaler [only treats it as ephemeral if it's in memory](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node):
![Image](https://github.com/user-attachments/assets/40177017-c0f1-47d7-8021-84ba3e2ff7c1)
As user, I'd like to have the control over the cluster autoscaler behaviour to configure it. I know that we can just mark everything as safe to evict, but it's complex with 3rd party softwares because they don't always offer that extension point

I've checked the current scenario and I think that adding the flag is quite easy (please correct me if you don't think it so), so I'm willing to draft a PR with the changes if you think that this is worth

**Comment by JorTurFer** [comment]
Well, this issue doesn't apply because the value that we need is 'false' indeed (sorry for the noise :( ). I can close it or just support the feature if you think that it's worth to continue with the PR

**Comment by timebertt** [comment]
I suggest closing this issue and the PR if there is no concrete ask for the feature. If the need arises, we can revisit them.
If you agree, feel free to close both the issue and PR :)
