### ISSUE TITLE
Allow to set the Node CIDR Mask Size in Shoot Spec

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener#1107]
**What would you like to be added**:
Currently the default CIDR mask size for a singe node is set to 24 which results in 255 allocatable Pod IPs per node.
```
--node-cidr-mask-size int32     Default: 24
```
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
It would be great if you could set this number in the Shoot spec.

**Why is this needed**:
In case you are creating large node machines, it might be desirable to specify (increase) the maximal number of Pod IPs per node.

**Comment by KesavanKing** [comment]
I changed the default value and it works for me. Able to allocate more pods per node.
