### ISSUE TITLE
the service should be able to keep deleted cluster for some time.

### ISSUE THREAD

**Issue by yagrxu** [gardener/gardener#112]
e.g. AWS will keep the information as "terminated" instances for some time(billing reason) ?
But I could not find the deleted one in our page anymore.

**Comment by vlerenc** [comment]
And why would you need to? What's your motivation? What do you want to read up afterwards?

**Comment by vlerenc** [comment]
Ping...

**Comment by vlerenc** [comment]
Ping... (ticket will be closed next, if no answer is provided)
