### ISSUE TITLE
Extract network policy tests to gardener/gardener-extensions

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1137]
**What would you like to be added**:
We should move all [network policy tests that are provider-specific](https://github.com/gardener/gardener/tree/master/test/integration/seeds/networkpolicies) to their dedicated repositories. Currently, we develop all extensions in https://github.com/gardener/gardener-extensions, hence, let's move them there.

**Why is this needed**:
We are progressing with extensibility and want to maintain everything provider-related outside of Gardener core.

**Comment by ialidzhikov** [comment]
Once this is resolved we can use `gofmt -s` - used in k/kubernetes and suggested by goreportcard.
Ref https://golang.org/cmd/gofmt/#hdr-The_simplify_command .
