### ISSUE TITLE
Schedule Critical Shoot Cluster `kube-system` Pods with High Priority

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#1150]
**What would you like to be added**:
We schedule critical shoot cluster `kube-system` pods with extensive tolerations, but not yet with high priority, so our pods may starve.

**Why is this needed**:
Proposal by @cbarbian-sap: How about scheduling them with higher priority?

**Comment by cbarbian-sap** [comment]
That would at least allow gardener pods to evict other workloads if necessary. What about doing both (i.e. scheduling gardener pods in kube-system with priorityclass system-cluster-critical/system-node-critical + offering an optional section in the shoot yaml to specify tolerations/affinities/nodeselectors for the gardener workloads) ?

**Comment by shafeeqes** [comment]
Found that all `kube-system` pods in the Shoot cluster are already scheduled with system-cluster-critical/system-node-critical `PriorityClass`.

**Comment by rfranzke** [comment]
Thanks for taking time to check this @shafeeqes, then it seems fine to
/close
this issue.
