### ISSUE TITLE
Allow to Defer Reconcilation/Maintenance to Next Maintenance Time Window/24h

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#1151]
# Story
- As shoot cluster owner I want to defer the next reconciliation/maintenance to the next maintenance time window or by at most a day/24h, so that I can avoid planned or unplanned cluster outages.

# Motivation
At present we run only zonal clusters and we know that during maintenance of either the seed or the shoot the control plane may become unavailable for a minute or so. Most use cases will cope nicely with that, but there are others that won't (e.g. FaaS or CI/CD use cases). Now imagine, that if a stakeholder runs multiple shoot clusters in HA spread across multiple seed clusters (to avoid seed cluster update issues due to missing anti-affinity) and one cluster fails (maybe because of a bug in the software running on said stakeholder cluster), then the respective stakeholder SRE/ops team would like to prevent also the other (HA) cluster from failing (then maybe because of a reconciliation/maintenance issue) and therefore defer the reconciliation/maintenance until the first/initial problem is resolved. This example also illustrates, why disjunct maintenance time windows are not helping the stakeholder: The first cluster goes down because of a problem unrelated to Gardener. So even if we would know of the logical connection between the two, we can’t really know of their actual health in regards to the software they run. We on the other hand want to know, that clusters get eventually all reconciled (forcefully without manual intervention) in a reasonable time. If that time is now 2 days instead of 1 day, I guess we could live with it (cc @rfranzke @adracus).

# Acceptance Criteria
- [ ] Shoot cluster maintenance can be temporarily avoided/deferred (e.g. by means of an annotation, specifying a timestamp that may not lie more than 48h after the last reconciliation)
- [ ] Shoot cluster gets eventually reconciled, no matter the annotation or updates to it (within at most 48h)

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit tests are provided: Have you written automated unit tests?
- [ ] Integration tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added/changed public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the operations guide about ops-relevant changes?
- [ ] User documentation: Have you updated the READMEs/docs/how-tos about user-relevant changes?

**Comment by rfranzke** [comment]
Implemented, but not on a per-shoot basis, but globally in the controller-manager configuration.
