### ISSUE TITLE
Documentation issue on page "https://gardener.cloud/about/"

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1156]
The about page is not properly displayed. See the screenshot below.

![Screenshot 2019-06-27 at 17 11 50](https://user-images.githubusercontent.com/9372594/60273599-2832a180-98ff-11e9-8a88-6aeef11bb293.png)

/cc @freegroup 

---
Page: https://gardener.cloud/about/
don't remove the link to the page. It's required for the processor

**Comment by vasu1124** [comment]
@OlegLoewen

**Comment by OlegLoewen** [comment]
Will look at this with @freegroup together
