### ISSUE TITLE
Gardener reconcile/readiness shoot status doesn't reflect the working VPN

### ISSUE THREAD

**Issue by kayrus** [gardener/gardener#1167]
**What happened**:

If the shoot cluster VPN is not reachable and the `vpn-seed` container inside the `kube-apiserver` pod produces error logs:

```
[Wed Jul  3 14:59:19 UTC 2019]: trying to identify the endpoint (load balancer name of vpn-shoot service) myself...
[Wed Jul  3 14:59:19 UTC 2019]: found endpoints: [ 10.0.0.99 ]
[Wed Jul  3 14:59:19 UTC 2019]: checking whether port 4314 is open on 10.0.0.99 ...
[Wed Jul  3 14:59:22 UTC 2019]: error: port 4314 on 10.0.0.99 is not open, can not use it
[Wed Jul  3 14:59:22 UTC 2019]: No tunnel endpoint found
```

This error is not reflected in the overall shoot cluster status:

```
$ kubectl -n garden-cluster get shoot
NAME         CLOUDPROFILE   VERSION   SEED           DOMAIN                                 OPERATION   PROGRESS   APISERVER   CONTROL   NODES   SYSTEM   AGE
wir5xvwkm5   region1        1.15.0    seed-region1   wir5xvwkm5.rtr-prblm.shoot.my.domain   Succeeded   100        True        True      True    True     3h47m
```

And when user want to use `kubectl logs` or `kubectl exec`, this operation will timeout and user won't be able to understand why.

**What you expected to happen**:

I expect to see PROGRESS: 99%, SYSTEM: false, OPERATION: Creating. In addition the gardener dashboard should display the VPN connection issue with logs inside the status modal window.

**Environment**:

- Gardener version: 0.26.1
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration: openstack
- Others: dashboard 1.33.0

**Comment by rfranzke** [comment]
@adracus WDYT about enhancing the `SystemComponents` condition to make it only `True` if the VPN works?

**Comment by adracus** [comment]
The `SystemComponents` condition only reflects what the various system component `Deployment`s, `StatefulSet`s and `DaemonSet`s report back - I think that this means that probably our health checks for the VPN are not good enough so its `Deployment` does not report that it's not working. We'll have to improve that I guess.

**Comment by rfranzke** [comment]
Hm, not sure whether that's the correct way. The vpn-shoot deployment itself is fine (it functions as OpenVPN server and is ready and ready to accept incoming connections). It's just that the vpn-seed cannot (yet?) connect to it. I don't think we should include this information in the `Deployment` status of the vpn-shoot.

**Comment by adracus** [comment]
I mean I'm just looking at the health-checking code: This code does not have any client to do real checks in the cluster and that's by design - it should see 'declaratively' whether there's an issue or not. In the case of the VPN, I'd probably then rather recommend to have an operator that takes care of setting up the 'network bridge' between Seed and Shoot and that this one is the one thing that can write proper health information into the status of its resource that is then reflected back in the health check.

Actually, now that I think of it, we also don't reflect the state of all extensions in the Shoot, so that also may be a problem with our health checks...

**Comment by rfranzke** [comment]
Hm, I didn't get the motivation for such an "operator". Why should we do this? The VPN is a core component in the Gardener architecture. IMHO there is nothing bad in compiling the health checking logic in the regular care controller. Did I miss something?

> This code does not have any client to do real checks in the cluster

I don't get this as well - we have the shoot client when checking the system components. The only thing we need to do is trying to open a port-forward connection (this code exists already as part of the shoot reconciliation flow, we can directly re-use it).

> we also don't reflect the state of all extensions in the Shoot, so that also may be a problem with our health checks

Which extensions are you talking about? The addons are part of the health check, right? The newly introduced OS/provider/... extensions are running in the seed and their health should probably be part of the `ControllerInstallation` status, but that's a different topic anyways.
