### ISSUE TITLE
Number of pods limited to 110 per node by default

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener#117]
During network and cluster scalability tests it was noted that there is a 110 pod limit on nodes by default. This might be too low for certain use cases. 

There is a detailed discussion here: https://github.com/kubernetes/kubernetes/issues/23349

I would propose to make this configurable through the shoot manifest to up to 254 nodes (the pod network is a class C network) as part of the node configuration.

The limit can be set using the --max-pods option on the kubelet.

**Comment by mvladev** [comment]
The Kubernetes SLAs only support 100 pods / node: https://kubernetes.io/docs/admin/cluster-large/ 
There are lots of factors that can limit performance - docker version, noisy neighbors, kubelet overhead ...

> At v1.10, Kubernetes supports clusters with up to 5000 nodes. More specifically, we support configurations that meet all of the following criteria:
>
>    No more than 5000 nodes
>    No more than 150000 total pods
>    No more than 300000 total containers
>    No more than 100 pods per node

**Comment by rfranzke** [comment]
Let's either close this or refine the description. We won't change that limit without that we've tried that out and got more experience with very large clusters (that might require > 110 pods per nodes). As @mvladev pointed out, the fact that K8S doesn't support that officially is a strong indicator not to do it.
