### ISSUE TITLE
Unable to Deploy Gardener on local Kubernetes

### ISSUE THREAD

**Issue by george-xiao-sap** [gardener/gardener#1174]
**What happened**:
when I follow the instruction of “Deploying the Gardener into a Kubernetes cluster”，
I execute command “helm install charts/gardener --debug --namespace garden --name gardener --wait ” in the path of gardener which is the master branch I download at 2019-7-5.

I get the following error:

[debug] Created tunnel using local port: '36441'

[debug] SERVER: "127.0.0.1:36441"

[debug] Original chart version: ""
[debug] CHART PATH: /work/goworkspace/src/github.com/gardener/gardener/charts/gardener

Error: render error in "gardener/charts/runtime/templates/deployment-scheduler.yaml": template: gardener/charts/runtime/templates/deployment-scheduler.yaml:2:15: executing "gardener/charts/runtime/templates/deployment-scheduler.yaml" at <include "deploymentversion" .>: error calling include: template: no template "deploymentversion" associated with template "gotpl"

**What you expected to happen**:
I expected success.

**How to reproduce it (as minimally and precisely as possible)**:
when I execute the command every time, I always get the error.

**Anything else we need to know?**:
I want to install gardener cluster to my own Kubernetes.
**Environment**:

- Gardener version: master  at 2019-7-5
- Kubernetes version (use `kubectl version`): v1.15.0
- Cloud provider or hardware configuration: virtual box vm on my pc
- Others:
<img width="759" alt="error" src="https://user-images.githubusercontent.com/52069941/60711166-db764880-9f46-11e9-8aaf-6e1cea6d1eed.png">

**Comment by rfranzke** [comment]
I cannot reproduce this. Is this a local issue with your system? The Gardener Helm chart contains symlinks, e.g. https://github.com/gardener/gardener/blob/master/charts/gardener/charts/utils-templates ?

**Comment by george-xiao-sap** [comment]
I delete my local branch, and try again. The error is not happen. 
Maybe my local branch has errors.
Many thanks.
