### ISSUE TITLE
Prevention of Garden namespace deletion when deleting Project

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener#1182]
**What would you like to be added**:
Since we are currently treating the `garden` namespace and project kind of "special" it would make sense to prevent the `garden` namespace deletion when the `garden` project has been removed. Can't we just remove the `project` but leave the namespace as is and leave it to the user to remove it.

**Why is this needed**:
Currently people are blowing up their landscape setups via accidentally deleting the garden project. I know that this "special" treatment of resource is not optimal - but it would save a lot pain for first time landscape setups.

**Comment by rfranzke** [comment]
duplicate of #879
