### ISSUE TITLE
Check for seed and shoot network overlap

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener#1190]
**What happened**:
I create a shoot by explicitly specifying a seed. The network setups of shoot and seed are exactly the same. The shoot will fail because of kube-apiserver failure.  
**What you expected to happen**:
The shoot should not be created. API validation should prevent it from creating.

**Comment by ialidzhikov** [comment]
I had no success reproducing this:
```
$ k apply -f shoot.yaml
Error from server (Forbidden): error when creating "shoot.yaml": shoots.garden.sapcloud.io "aws-local" is forbidden: [spec.cloud.aws.networks.nodes: Invalid value: "10.222.0.0/16": shoot node network intersects with seed node network
```

https://github.com/gardener/gardener/blob/3ef3b2d70f40a05a5fb1b2ea36f614351e952fd4/plugin/pkg/shoot/validator/admission.go#L343-L345

Can you outline some steps to reproduce?

**Comment by jia-jerry** [comment]
@ialidzhikov , I reported this issue by mistake. Everything is fine. Thank you for your check. I will close this issue.
