### ISSUE TITLE
gardener/pkg/client/kubernetes Clientset with fake clients in extension controller tests

### ISSUE THREAD

**Issue by shturec** [gardener/gardener#1191]
**What would you like to be added**:
Fake clients implementation for the `Interface` interface in gardener/pkg/client/kubernetes.

**Why is this needed**:
This is the all-purpose client that is most likely to be used by extension controllers. While there are already `fake` packages for the particular clients, there is no easy way to fake this interface. It is implemented by the `Clientset` struct that does not expose any fields that can be injected with fake clients. That could also be a solution, alternative to creating an implementation with fakes.
Therefore the lack of an in-tree fake clients implementation hampers the unit testing of extension controllers that have selected this interface for kubernetes and Gardeners-specific resources interactions with the api server.

**Comment by zanetworker** [comment]
@shturec did you have a look at this: https://github.com/gardener/gardener/tree/master/pkg/mock ?

**Comment by shturec** [comment]
No, thanks. I will give it a try. I see the interface I need has been added some 13 days ago. Is that already part of a release or when is that planned?
Still it feels strange why would I need a `gomock` dependency instead of simply having the relevant properties exposed and let people do their thing.

**Comment by zanetworker** [comment]
because you can only do so much with Fake clients, Mocking gives you much more leaverage over the API. Regarding the part you are referring to, it was added a long while ago, only refactored recently.

**Comment by rfranzke** [comment]
Can we close this? I think `gomock` should provide enough flexibility for the use-case?
