### ISSUE TITLE
Deploy multiple Gardener API server with node Anti-affinity

### ISSUE THREAD

**Issue by hoeltcl** [gardener/gardener#1193]
**What would you like to be added**:
Deploy multiple Gardener API servers with Node Anti-Affinity
(https://github.com/gardener/gardener/blob/master/charts/gardener/charts/runtime/templates/deployment-apiserver.yaml)
**Why is this needed**:
This is required to make Gardener API server fail safe.

**Comment by vpnachev** [comment]
The chart has already support for a parameter for the number of replicas https://github.com/gardener/gardener/blob/a1e2433c31adc95fca52705fe547190630b9312f/charts/gardener/charts/runtime/templates/deployment-apiserver.yaml#L14

So what needs to be done is to add pod [anti-affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity) to the spec of the deployment.
