### ISSUE TITLE
Deletion issue in corner case

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1194]
Shoot hibernated with older version of gardener fails to delete with `0.26.2`.
```
Flow "Shoot cluster deletion" encountered task errors: [task "Waking up control plane to ensure proper cleanup of resources" failed: deployments.apps "gardener-resource-manager" not found] Operation will be retried.
```

As a workaround creating a sample deploy with the same name (`gardener-resource-manager`) does the trick.
```
$ k run gardener-resource-manager --image=busybox -n $NAMESPACE
```

**Comment by adracus** [comment]
I think the thing we should rather do is to re-apply the expected components instead of scaling them imperatively - I'll take that one.

**Comment by rfranzke** [comment]
With #1239 we will always deploy the GRM which will help with the problem.

For the future I guess what @adracus suggested is the right way. I opened #1240 and assigned him to track the status.
