### ISSUE TITLE
Change the default storage class of a cluster

### ISSUE THREAD

**Issue by Fabian-K** [gardener/gardener#1225]
**What happened**:
I provisioned a new storage class to a cluster, removed the `storageclass.kubernetes.io/is-default-class` from the `default-class` and added it to my new storage class. After some time, gardener automatically re-adds `storageclass.kubernetes.io/is-default-class` to `default-class`. 

As a result, there are two storage classes marked as default and provisioning new PVCs without specifying a storage class fail with `persistentvolumeclaims "sample-pvc" is forbidden: Internal error occurred: 2 default StorageClasses were found`

**What you expected to happen**:
If a storage class marked as default exists, gardener should not mark the `default-class`as default.

**How to reproduce it (as minimally and precisely as possible)**:
provision a new storage class, e.g. https://github.com/rancher/local-path-provisioner
```
kubectl patch storageclass default-class -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'`
kubectl patch storageclass other-storage-class -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```
wait...

**Comment by rfranzke** [comment]
I don't think we can implement this easily. The extension controllers will create the storage classes and will pick one that is the default class. After that, these manifests are given to the resource-manager who will apply them every minute or so. The resource-manager itself is not aware of what it applies, i.e., it doesn't know about the context. However, it would need to know to fix "this issue", but that contradicts its design.
The extensions themselves could check whether there is another storage class that is marked as default, and if so, then don't mark their own as default. However, this does not work when we switch to reconciliation only in the maintenance time window (every 24h, basically).

--> I don't think we can easily solve this soon and we probably won't find time to work on it. I'll close the PR and mark it as "won't fix" for now. Also, I guess it's no too hard restriction that the default class cannot be changed.
