### ISSUE TITLE
Editing kube-apiserver of Gardener shoot created to enable Kubernetes dynamic-backend auditing 

### ISSUE THREAD

**Issue by mejuhi** [gardener/gardener#1226]
To enable dynamic audit configuration in the kubernetes cluster which requires adding "--audit-dynamic-configuration" option in kube-apiserver along with additional changes llike adding additional feature gates.

Since in normal kubernetes cluster(not using Gardner) one can edit kube-apiserver manifest file which is saved on path /etc/kubernetes/manifests/kube-apiserver.yaml directly and add all the required changes, I am not able to find anything similar when my cluster is setup using Garner. 

To enable dynamic-backend audit of kubernetes (https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#dynamic-backend) following changes are required in kube-apiserver
--audit-dynamic-configuration
--feature-gates=DynamicAuditing=true
--runtime-config=auditregistration.k8s.io/v1alpha1=true

Out of which option to add feature-gates and runtime-config is there in shoot's yaml (https://github.com/gardener/gardener/blob/0.22.0/example/90-shoot-aws.yaml) but no provision to add extra option of "audit-dynamic-configuration"

Looking into https://github.com/gardener/gardener/tree/0.22.0/charts/seed-controlplane/charts/kube-apiserver chart. In this chart's values.yaml there is option available "additionalParameters: []" to add extra option. But this option is not available in https://github.com/gardener/gardener/blob/0.22.0/example/90-shoot-aws.yaml shoots's yaml file.

**Comment by vpnachev** [comment]
So far the `DynamicAuditing` is in alpha state and this is why we do not want to invest into it. Once it graduates to beta we will take care to provide option to enable it.

**Comment by mejuhi** [comment]
Okay, Is there any way to provide  Kubernetes auditing using [webhook ](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#webhook-backend)

It requires "--audit-webhook-config-file" as one of the option.

Is Kubernetes auditing using webhook supported by Gardener v0.22.0 @shturec

**Comment by shturec** [comment]
No configurable way, as far as I know. Audit is a managed feature so in terms of api server audit backend you get what your Gardener hosting service has in store for your shoots (log file by default). And it's not configurable on per shoot basis by the shoot cluster owner. What you can influence is the audit policy. 
The plans to make this more flexible are to enable dynamic audit as soon as the feature graduates at least to beta. You might want to keep an eye on the development of the feature in the community to make sure your use case is addressed.

**Comment by rfranzke** [comment]
Thanks for the explanation and outlook, @shturec. I guess we can close this one then as "won't fix" as we already have different plans using audit sinks.
