### ISSUE TITLE
Only use secure TLS cypher suites

### ISSUE THREAD

**Issue by ThormaehlenFred** [gardener/gardener#1232]
**What would you like to be added**:
Please only use the following secure TLS cypher suites:
1. TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
2. TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
3. TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
4. TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

**Why is this needed**:
With Gardener PR [#428](https://github.com/gardener/gardener/pull/428) we removed insecure cipher suites and have written a release note for 0.13.0. 

> The list of TLS cipher suites supported by the Kubernetes control plane has been limited to TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

Scan tools recently have identified some of them as being insecure. The list 1-4 above are the remaining TLS cipher suites which are rated to be secure by the scan tool. Thus we should only use this limited list in the Gardener.

**Comment by ialidzhikov** [comment]
I guess we can reopen as the PRs were reverted.

/reopen

**Comment by ThormaehlenFred** [comment]
Hi @rfranzke and @ialidzhikov , can this issue be closed then?

**Comment by rfranzke** [comment]
Why?

**Comment by ialidzhikov** [comment]
There are still
```
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA
```

which are not removed. We tried to remove them but we faced issues on aws.

**Comment by ThormaehlenFred** [comment]
@rfranzke and @ialidzhikov What is the outcome of your discussion? Will the ciphers stay, because they are required for AWS?

**Comment by rfranzke** [comment]
There was no discussion, the last update is what @ialidzhikov wrote with https://github.com/gardener/gardener/issues/1232#issuecomment-597127897. I don't think any further actions have happened yet. So, yes, for now they'll have to stay.
