### ISSUE TITLE
Shoot apiserver intermittently not reachable from shoot work-load when the apiserver request rate is high

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/gardener#1241]
**What happened**:
When the request rate is high (>~200 req/s), the shoot apiserver becomes unreachable to the shoot work-load intermittently. This has been seen in AWS, Alicloud as well as GCP. But it is reachable from the other control-plane components in the seed.

**What you expected to happen**:
The shoot apiserver should have been accessible from shoot work-load especially because no control-plane components (in seed or shoot) restarted and the apiserver was accessible from the control-plane components in the seed right thourghout.

**How to reproduce it (as minimally and precisely as possible)**:
Create a work-load on the shoot apiserver with request rate ~200 req/s. At consistently high load, this issue begins to appear after 10-15min.

**Anything else we need to know?**:
- None of the control-plane components were restarted during this entire period.
![image](https://user-images.githubusercontent.com/32157254/61696764-8a8e8e80-ad53-11e9-974e-d06b2a4a83ff.png)
- All the control-plane components were ready as well. The only spikes in the seed control-plane are due to the hourly-curator.
![image](https://user-images.githubusercontent.com/32157254/61696868-b873d300-ad53-11e9-9caa-d4630feebc69.png)
- There is no correlation with network traffic in the apiserver pod(s).
![image](https://user-images.githubusercontent.com/32157254/61697001-025cb900-ad54-11e9-9d04-7a0829d0a30f.png)
- No correlation with network traffic in the etcd-main pod.
![image](https://user-images.githubusercontent.com/32157254/61697024-0ee11180-ad54-11e9-8358-f63751bb2050.png)
- No correlation with blackbox-exporter pod probing the apiserver from the shoot.
![image](https://user-images.githubusercontent.com/32157254/61697052-1d2f2d80-ad54-11e9-8a77-014aee9d3d21.png)
- Similarly, there was no correlation with calico-nodes or kube-proxy instances.
- The loadbalancer in AWS for the kube-apiserver service also did not show anything obviously wrong.
![image](https://user-images.githubusercontent.com/32157254/61697126-48b21800-ad54-11e9-9f37-963723091be0.png)
- A check of apiserver logs did not show anything out of the ordinary during the period apiserver was reported as unreachable.

**Environment**:
- Gardener version:
- Kubernetes version (use `kubectl version`): 1.14.4, 1.14.0

- Cloud provider or hardware configuration:
  - AWS - m5.4xlarge
  - Alicloud - ecs.sn2ne.4xlarge
  - GCP - n1-standard-2
- Others:

**Comment by zanetworker** [comment]
@amshuman-kr I have linked related PRs that solves the file-copy issue but also should improve the situation for this one. Can you re-test your use-case ?

**Comment by rfranzke** [comment]
@amshuman-kr I'm closing this issue now that we have HVPA in place. Kindly reopen if you think it makes sense.
