### ISSUE TITLE
Provision to customize kube-apiserver of Gardener shoot

### ISSUE THREAD

**Issue by mejuhi** [gardener/gardener#1244]
Kubernetes provides various options in [kube-apiserver ](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/). 

I want to add additional options to customize my shoot's  kube-apiserver rather than using shipped in kube-apiserver options of shoot which gets created using shoot's yaml (other than configurable option such as featureGates, runtimeConfig and auditConfig). 

Is there any way to customize and add options in kube-apiserver of shoot or a way to utilize "additionalParameters: []" defined over [here](https://github.com/gardener/gardener/blob/0.22.0/charts/seed-controlplane/charts/kube-apiserver/values.yaml)

**Comment by rfranzke** [comment]
We don’t allow that on purpose to keep up Gardener‘s SLOs. 
Gardener is a managed Kubernetes service and as such dictates what can be configured and what not. We won’t make such general configurability available, sorry.
