### ISSUE TITLE
TCP Load Balancing for NGINX

### ISSUE THREAD

**Issue by tiagokv** [gardener/gardener#1246]
**What would you like to be added**:

In NGINX ingress, it's possible to use a [L4 load balancing](https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/). The solution is basically passing a ConfigMap name to an NGINX controller argument `--tcp-services-configmap`, which the key is a port number to be open and the value is a concatenation of the namespace, service and its port number that should be routed to. In their chart, you can use the `tcp` argument and it will create the ConfigMap and pass the argument for you.

I see two options on the enhacement of NGINX addon on shoot API ([link](https://github.com/gardener/gardener/blob/master/pkg/apis/garden/v1beta1/types.go#L1077-L1082)):
  a. Add the same TCP parameters as to be passed to the values in the chart. This would keep compatibility and an easy implementation. The con of this is that one has to know the service and the port beforehand and the cluster is updated (e.g. a new service is created) the shoot API has to be used to be updated (is this possible?) because, as far as I know, changing the ConfigMap created by the chart would be reconciled by Gardener.
  b. Pass a ConfigMap name, with a name that would not conflict e.g. using the release name, and pass it to NGINX as a reference to check. From the shoot cluster side, one would create the same ConfigMap and edit as it wants. The con is that would required to restart after changing the ConfigMap.

Once the decision is done, I can develop myself and create the PR.

**Why is this needed**:

In our service we use Gardener's default NGINX deployment, but we also need to use TCP load balancing. Today, we have to create another load balancer just to handle the TCP connection and is not managed by NGINX.

**Comment by rfranzke** [comment]
Closing this for the reasons described in #1254. gardener/gardener-extensions#201 tracks the status of the DNS controller for shoots. gardener/gardener-extensions#237 tracks the status of the certificate service enhancements for custom domains.
