### ISSUE TITLE
Enhance Configuration ConfigMap for NGINX

### ISSUE THREAD

**Issue by tiagokv** [gardener/gardener#1247]
**What would you like to be added**:

There are specific configurations in NGINX, which are more detailed [here](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/), the can be tweaked in NGINX deployment. They all end up in this [file](https://github.com/gardener/gardener/blob/master/charts/shoot-addons/charts/nginx-ingress/templates/controller-configmap.yaml).
My proposal would be to add in the NGINX addon [part ](https://github.com/gardener/gardener/blob/master/pkg/apis/garden/v1beta1/types.go#L1077-L1082) of the shoot API a key-pair configuration that would be routed to this file. 

**Why is this needed**:

For example, in our service we have to use URLs with very long paths, which currently cause NGINX to reject with 414 error. This can be fixed by raising the buffer size with the [large-client-header-buffers](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#large-client-header-buffers) parameter.

**Comment by rfranzke** [comment]
Closing this for the reasons described in #1254. gardener/gardener-extensions#201 tracks the status of the DNS controller for shoots. gardener/gardener-extensions#237 tracks the status of the certificate service enhancements for custom domains.
