### ISSUE TITLE
Update nginx-ingress-controller image to latest version

### ISSUE THREAD

**Issue by tiagokv** [gardener/gardener#1254]
**What would you like to be added**:

1. Update the NGINX Controller to version 0.25.0 and its chart in the nginx-ingress folder.
2. Enhance in shoot API the following points:
  a. Image of a custom NGINX controller.
  b. Map the "extraEnvs" information to NGINX controller (already present a placeholder in the values.xml of the new chart).
  c. Add namespace where NGINX controller will be installed.

**Why is this needed**:

We want to enable a JSON Web Token (JWT) validation in the NGINX ingress controller to avoid erroneous tokens getting into the service itself. In the new version from the controller, there's the possibility of installing a lua package based on OpenResty, which can be done by creating new Docker image based on the default one and installing the package (example can be found in this [repository](https://github.com/ubergarm/openresty-nginx-jwt)).

In order to JWT validation to work, we need the token to validate it. This would be available in a secret that would be injected as an environment variable.

**Comment by rfranzke** [comment]
Hi @tiagokv, while we certainly want to update the nginx version, I guess we won't work on your points mentioned in 2.

We are providing the nginx-ingress-controller as a default ingress addon for convenience reasons. However, there are way too many configuration options and every end-user needs something different. Consequently, we would need to open up everything. That's a lot of effort for us having all these configuration options (+validation/defaulting) in the shoot API.

Instead, what we rather plan to do is to allow end-users to create DNS records for their shoot. Having that in place you can deploy your own ingress controller and customize it based on your needs.

I'm keeping this ticket open until we have updated nginx to `0.25.0`.

**Comment by rfranzke** [comment]
gardener/gardener-extensions#201 tracks the status of the DNS controller for shoots. gardener/gardener-extensions#237 tracks the status of the certificate service enhancements for custom domains.
