### ISSUE TITLE
Delete failed

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#129]
I created a couple of clusters for testing and deleted them. I did not use the programmatic interface and I did not fiddle around with the IaaS resources or opened the console, but I got this error (`canary`: `core`/`vlerencaw9`):

```
Delete Processing
Currently executing (CloudBotanist).DestroyInfrastructure
Last Error
Operation failed as there are dependent objects on cloud provider level
Failed to delete Shoot cluster: Errors occurred during flow execution: '(CloudBotanist).DestroyInfrastructure' returned 'Terraform execution job 'vlerencaw9.infra.tf-job' could not be completed. The following issues have been found in the logs:

-> Pod 'vlerencaw9.infra.tf-job-zpldk' reported:
* aws_vpc.vpc (destroy): 1 error(s) occurred:
* aws_vpc.vpc: DependencyViolation: The vpc 'vpc-3264fd59' has dependencies and cannot be deleted.
	status code: 400, request id: <omitted>'
```

**Comment by rfranzke** [comment]
Hm, that's the same issue which we saw occasionally in the past. The kube controller manager cannot delete load balancers or security groups from AWS (more often security groups). Generally, it deletes the load balancers first and the corresponding security groups second. However, AWS takes a while to detach the network interface from the load balancer and blocks the deletion of the security group until then.
The only thing we can do about it is deleting those resources on our own... let's discuss.

**Comment by vlerenc** [comment]
Let's wait for the smoke tests. If they fail, we should do something. The only thing we can do is to delete the security groups automatically and not wait on the controller manager to (not) do it.

**Comment by rfranzke** [comment]
FYI: I've prepared an implementation that deletes the ELB security groups. Thus, just in case we need it, we can quickly have it.
