### ISSUE TITLE
Make possible to delete shoot with wrong `.spec.dns`

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1295]
**What happened**:
User can apply shoot spec with not properly configured `.spec.dns` which may result in
```
level=error msg="could not initialize a new operation: unable to figure out which secret should be used for dns"
```

The deletion of such shoot is not possible.

**What you expected to happen**:
To be able to delete shoot with not properly configured `.spec.dns`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a shoot with the following dns section and ensure that it does not match the default domain:
```yaml
spec:
  # [...]
  dns:
    domain: foo.bar.baz.example.com
  # [...]
```

2. Ensure that the the shoot reconciliation won't be triggered.
3. Ensure that the deletion of the shoot won't be possible.

**Anything else we need to know?**:

**Environment**:

- Gardener version: 0.27.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
#1205 is similar
