### ISSUE TITLE
Disable cluster autoscaler in spec (temporarily until we have one again)

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#131]
As long as we have no cluster autoscaler supporting our machine controller, we should not mislead the users and make clear we have none.

**Comment by rfranzke** [comment]
We decided to wait and sync with @hardikdr and @prashanth26 about when the integration of cluster-autoscaler will come. If it takes too long and we still want to not confuse the users we should rather change the dashboard (cc @grolu @holgerkoser @petersutter) by only allowing to enter a fixed number of worker nodes per pool (the dashboard should write the provided to number both `autoScalerMin` and `autoScalerMax`).

**Comment by rfranzke** [comment]
Closing as cluster-autoscaler is merged (#200).
