### ISSUE TITLE
AliCloud Regression: Loadbalancers can't be deleted in shoot cluster

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener#1311]
**What happened**:
After deletion of shoot cluster, SLBs  are not deleted.
**What you expected to happen**:
External resources should be deleted successfully
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Gardener should wait for SLBs to be deleted in Shoot Deletion loop. I also found some disks leftovers, but it seems that they were left during the unstable development phase. Anyway, will keep an eye on it.
**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: AliCloud
- Others:

**Comment by jia-jerry** [comment]
It seems other cloud providers have the same issue

**Comment by timuthy** [comment]
Hi @jia-jerry,

it'd be nice if there was more context on this issue.

- Do you mean Disks / SLBs of the Shoot cluster's control plane (resource in Seed) or Disks / SLBs that are created in the Shoot?

- What reclaim policy did your PVs have?

- How were the SLBs created? Through `services` of type `LoadBalancer`?

**Comment by jia-jerry** [comment]
Hi @timuthy 
1. SLBs in shoot cluster like nginx-ingress-controller and VPN are not released. This is because the cloud controller manager and csi controllers are deleted before SLBs and PVC are deleted. 
2. Reclaim policy of PV-- persistentVolumeReclaimPolicy: Delete
3. Through services of type LoadBalancer

The deletion lifecycle is refactored. This issue doesn't happen before. And also, this issue also occurs in other hyperscalars like GCP. It is a serious issue. It will cause too many manually clean up steps.

**Comment by ialidzhikov** [comment]
I guess gardener/gardener-extensions#257 is related to this issue?

**Comment by rfranzke** [comment]
We probably have found the cause for this (cc @timuthy) and are working on a fix.
The root cause is still that services don’t have Finalizers yet...

**Comment by afritzler** [comment]
For OpenStack we implemented this hack for now https://github.com/gardener/gardener-extensions/pull/191 ... we wait for 2 minutes before we remove the cloud/kube-controller-manager.

**Comment by timuthy** [comment]
To be sure, I double checked the disk issue but couldn't reproduce it.

**Comment by jia-jerry** [comment]
> To be sure, I double checked the disk issue but couldn't reproduce it.

It can't be reproduced when the shoot is awaken.
Just now I did a test as following steps, the disk is left undeleted. I will check this issue next week if you guys overloaded.
1. Create a shoot on AliCloud.
2. Create a PVC in shoot cluster.
3. Hibernate the shoot cluster
4. Delete the shoot **without** waking up the shoot.

**Comment by rfranzke** [comment]
Do you use alicloud extension [0.9.3](https://github.com/gardener/gardener-extensions/releases/tag/0.9.3) containing [this fix](https://github.com/gardener/gardener-extensions/commit/882ac8a07ec9f5c4935a05e95711134b26fc2134)?

**Comment by jia-jerry** [comment]
> Do you use alicloud extension [0.9.3](https://github.com/gardener/gardener-extensions/releases/tag/0.9.3) containing [this fix](https://github.com/gardener/gardener-extensions/commit/882ac8a07ec9f5c4935a05e95711134b26fc2134)?

Yes. The extension is in version 0.9.3. I did the test again and found the CSI-Controller was not wakeup during deletion. This isssue only occurs for providers using CSI

**Comment by rfranzke** [comment]
Thanks, will check it.

**Comment by rfranzke** [comment]
https://github.com/gardener/gardener-extensions/commit/b971aade2373eef0de62d024ad32c95e2bd912be fixes the problem. Release 0.9.4 is in the process of being built. Sorry for the inconveniences, Jerry.

**Comment by jia-jerry** [comment]
Thank you Rafael, I should haved handled this issue anyway. At least for Alicloud plugin. :)
