### ISSUE TITLE
Please support spec with <major>.<minor> Kubernetes version

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#1324]
**What would you like to be added**:
The ability to specify only the `<major>`.`<minor>` Kubernetes version with new shoot resources and the appropriate/matching `<major>`.`<minor>`.`<patch>` version will be inserted instead by the API server.

**Why is this needed**:
To simplify cluster creation/automation, avoiding the need to read and parse the cloud profiles beforehand.

**Comment by rfranzke** [comment]
@danielfoehrKn
