### ISSUE TITLE
Resource limit handling for pods using VPA

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1335]
**What would you like to be added**:
Currently, we are using the VPA for several components, e.g. `kube-controller-manager`, `kube-scheduler`, and may more.

In its current implementation the VPA - if set to policy `Auto` - does only set the pod's resource **requests**. It doesn't touch the **limits**. According to @georgekuruvillak this is planned for a future release of VPA, however, it might still take some time.
As a consequence, even with having VPA adapting the resource requests, our statically computed limits are still the upper bound, and a cluster under pressure can not scale beyond them.

Can we improve the situation? @georgekuruvillak suggested to either remove the limits entirely from the pods using VPA or having a separate mutating webhook that adjusts the limits (e.g., based on the VPA's recommendations). Maybe there are even other options.

**Why is this needed**:
We don't want to statically compute resource limits for the various pods in our clusters because their load can differ and, thus, the limits need to be determined dynamically.

/cc @georgekuruvillak @amshuman-kr @ggaurav10 @PadmaB

**Comment by amshuman-kr** [comment]
Seems to be already covered by VPA admission plugin in [#2005](https://github.com/kubernetes/autoscaler/pull/2005). We might have to wait till 0.6.0 release or even better 0.5.2 according to [#2105](https://github.com/kubernetes/autoscaler/pull/2105).

**Comment by rfranzke** [comment]
Awesome, so nothing to do on our side other than updating to the new version, right? Great, thank you.

**Comment by amshuman-kr** [comment]
Yes. Then limits will be scaled in the same proportion as the requests are scaled.

**Comment by vlerenc** [comment]
Just to clarify @rfranzke: Is there anything that needs to be done right now (like statically increasing the limits for certain now failing components) until the new version will become available?

**Comment by rfranzke** [comment]
I don't think so, @georgekuruvillak just explained that the limits will scale proportional to requests with https://github.com/kubernetes/autoscaler/pull/2005/. It should be OK to only wait for the new release.

**Comment by amshuman-kr** [comment]
VPA 0.6.1 is [out](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.6.1) with the ["Preserve limit / request ratio, don't cap recommendations to limit"](https://github.com/kubernetes/autoscaler/commit/3fef092d2d7abc65b953e391c72e107bb8f2cd5e) change.

**Comment by amshuman-kr** [comment]
We are evaluating it as part of the performance test run with HVPA.

**Comment by rfranzke** [comment]
👍

**Comment by rfranzke** [comment]
Fixed with https://github.com/gardener/gardener/pull/1512
