### ISSUE TITLE
Current Azure shoot example is incorrect

### ISSUE THREAD

**Issue by tuxgoose** [gardener/gardener#1348]
**What happened**:
Currently the document below is recommending users to use azure as a cloud profile, https://github.com/gardener/gardener/blob/ed26a3fdf2d67487d68fc5b2783b06e14e25daca/example/90-shoot-azure.yaml#L9

However you will get an error when attempting to deploy a azure shoot cluster unless you specify, "az"
**What you expected to happen**:
➜  gardener_shoot_nursery git:(master) ✗ kubectl apply -f azure-no.yaml
should have deployed an azure shoot cluster 

Error from server (Forbidden): error when creating "azure-no.yaml": shoots.garden.sapcloud.io "ev-1067-az" is forbidden: cloudprofile.garden.sapcloud.io "azure" not found

**How to reproduce it (as minimally and precisely as possible)**:
attempt to deploy an azure shoot cluster with "azure" listed as a profile rather than az
**Anything else we need to know?**:

**Environment**:

- Gardener version: 0.27.6
- Kubernetes version (use `kubectl version`):v1.14.1
- Cloud provider or hardware configuration: azure
- Others:

**Comment by rfranzke** [comment]
Not an issue/bug, see explanation in #1259. This is the open-source project repository for gardener, and the examples are independent of any concrete installation/landscape.
