### ISSUE TITLE
During Reconcile , kubectl is not working, API is unavailable.

### ISSUE THREAD

**Issue by nikhilagrawal577** [gardener/gardener#144]
During Reconcile of cluster, Kubectl is not working.
API server is also unavailable 
As a result, we are not able to use the cluster.
Reconcile is happening again and again.
IAAS : Openstack

**Comment by rfranzke** [comment]
Thanks for reporting! We are aware and have already fixed the issue, releasing a new version today. Sorry for the inconveniences.

**Comment by rfranzke** [comment]
Closing due to [release 0.3.2](https://github.com/gardener/gardener/releases/tag/0.3.2).
