### ISSUE TITLE
Minimise disruption to workload in case of kube-apiserver loadbalancer issues

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/gardener#1447]
**What happened**:
If the `kuber-apiserver` loadbalancer is down for some time, the workload (even what is not dependent on `kube-apiserver`) in the cluster is disrupted because nodes and pods get evicted eventually.

The `nodelifecycle` controller in the `kube-controller-manager` is the active component that is taking the relevant actions. The following flags seem to be relevant.
* `--node-monitor-grace-period` controls the grace period before the node is marked as `NotReady` if `kubelet` is not able to reach the `kube-apiserver`.
* `--pod-eviction-timeout` controls the grace period after a node is marked as `NotReady` before the pods in that node are evicted.
* The pods are marked as not ready (condition `Ready` false) as soon as node is marked as `NotReady`. This is not controlled by any flag.
* So, none of the above flags help completely in keeping the node and the workload ready.
* Only switching off the `nodelifecycle` controller using the the `--controllers` flag keeps the nodes and the workload *ready*. But it might be simpler to scale down the `kube-controller-manager`.

**What you expected to happen**:
The workload (not dependent on `kube-apiserver`) should not be disrupted.

**How to reproduce it (as minimally and precisely as possible)**:
Delete `kube-apiserver` `LoadBalancer` `Service` (or replace it with a `ClusterIP` `Service`).

**Anything else we need to know?**:
A possible minimal solution could be to introduce a watchdog component to continually monitor the accessibility of `kube-apiserver` both internally from the seed cluster and externally via the loadbalancer. If it is not accessible externally but accessible internally then scale down the `kube-controller-manager` and scale it back up when external access is restored.

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by vlerenc** [comment]
We were fearing that scaling down the KCM may have undesired side effects and disabling the `nodelifecycle` controller may be better/less drastic. Do we know whether there is anything in KCM worth keep running or whether it can be shut down, if the nodes can't call back home anyways?

**Comment by amshuman-kr** [comment]
@vlerenc I tried switching off KCM for longer periods last week (~2h) while the loadbalancer was also down. I could not see any adverse affects. The existing workload was unaffected as long as the pods/nodes themselves did not have any issues. Considering that scaling down KCM is simpler compared to switching on/off individual controllers in KCM, this looks more suitable approach. WDYT?

**Comment by vlerenc** [comment]
Well then, if the anxiety wasn't justified, then it is certainly the simplest solution. I just wasn't sure whether we should check the source code to be sure or try another path (avoiding that). Not sure whether "disabling it for a week" proves the point (maybe some code paths were not touched). However, if a standard workload looks healthy, then I guess we can just do it this way. During further Gardener ring tests we will anyhow uncover more issues and if it works for us (it did for you already), then it may work for most if not all. So yes, let's go ahead with the simple solution for this "problem" and refine if necessary later. It will already improve the situation today. Thank you!
