### ISSUE TITLE
Auto Scaling is not working

### ISSUE THREAD

**Issue by nikhilagrawal577** [gardener/gardener#145]
With known fact of the number pods limited to 110 per node.We wanted also to check on the Auto Scaling aspects of Gardener.
Gardener should create up new nodes in the cluster when no of pods per node reaches the limit

**Cluster Characteristics** : 
```
- AWS ~ Node Instances of type m4.xlarge

- 10 Worker groups –  Auto Scaling aspects: Min 1 and Max 10

- Initial: 10 nodes and it can auto-scaled up to 100 nodes
```
Upto 31 nodes, auto scaling was working properly.
Beyond 31 nodes, means there were around 3300 pods, Auto scaling of nodes didn’t happen after that.

What configuration gardener is considering for auto scaling of nodes ? 
is it related to VM resources or no of pods ?

**Comment by rfranzke** [comment]
We are currently in the process of integrating the cluster autoscaler. It is not explicitly disabled or mentioned in the Gardener dashboard as it will come shortly, and we already want to enable users to configure the proper settings.
We will (re)use the [Kubernetes cluster autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) and the actual logic of how it's decided when to scale up/down is untouched (and can be read up in the mentioned repository).
Closing it therefore, ok? Once the integration is done it will be mentioned in the related release notes.
