### ISSUE TITLE
Optionally add ports to allow-to-blocked-cidrs networkpolicy

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener#1462]
**What would you like to be added**:
Add whitelisted ports to the networkpolicy `allow-to-blocked-cidrs`.
**Why is this needed**:
Currently the networkpolicy `allow-to-blocked-cidrs` will allow traffic on all ports to the given CIDRs. This will reduce the traffic to only the allowed ports.

**Comment by rfranzke** [comment]
@wyb1 what's the status here? Do we still need it?

**Comment by rfranzke** [comment]
ping @wyb1 - can you explain more about the use-case and whether it's still relevant?
