### ISSUE TITLE
Prevent `gardener` finalizer from being removed for existing shoots

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#1470]
**What would you like to be added**:
When the `gardener` finalizer is removed from a shoot, an admission plugin in the Gardener should check if the shoot still has some backing assets, e.g. networks, machines, etc.

This can be done by checking if the shoot `namespace` in the seed exists and deny the admission request if this is the case.

**Why is this needed**:
At the moment it is possible to remove the `gardener` finalizer and remove the shoot subsequently. As a result, the shoot resource is gone but all the assts related to the shoot, e.g. network, load balancers, services, workers, etc. are still in the system.

/cc @rfranzke @vpnachev

**Comment by timebertt** [comment]
Thanks for opening the issue. I'll get on it as soon as I'm back from vacation.
