### ISSUE TITLE
Cannot run integration tests

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1483]
Recently the controller-runtime version was upgraded to `v0.2.0-beta.4`. In this version the library also registers a flag `kubeconfig` which makes impossible to run our integration tests because they also define a flag with the same name which results in panic.

https://github.com/kubernetes-sigs/controller-runtime/blob/v0.2.0-beta.4/pkg/client/config/config.go#L38-L40

```bash
$ go test -mod=vendor ./test/integration/shoots/applications -kubeconfig $HOME/.kube/config -shootName "foo" -shootNamespace "bar" -ginkgo.v -ginkgo.progress
panic: /var/folders/p9/6dr9snnx6ws1dxkj4b66st6r0000gn/T/go-build615956323/b001/applications.test flag redefined: kubeconfig
[...]
```

**Comment by danielfoehrKn** [comment]
Will be fixed with [PR](https://github.com/gardener/gardener/pull/1474) changing our internal naming of the flag from to "kubecfg".

**Comment by danielfoehrKn** [comment]
I think this issue can be closed now. The PR has been merged.
