### ISSUE TITLE
Add K8s version metadata to cloudprofile

### ISSUE THREAD

**Issue by RaphaelVogel** [gardener/gardener#1495]
**What would you like to be added**:
We are currently sharpening/defining our K8s versioning policy and want to classify versions in the cloudprofiles. An additional ENUM with possible values of `preview`, `supported`, `deprecated` and `expired` should be added. This should be used by the dashboard to display those version classifications when selecting the a specific version.

**Why is this needed**:
Have a clear guidance for our stakeholders when we deprecate and/or remove K8s versions.

**Comment by ialidzhikov** [comment]
Why we point to an internal link in the public repo?

**Comment by RaphaelVogel** [comment]
removed...

**Comment by rfranzke** [comment]
Closed in favour of #1577
