### ISSUE TITLE
Gardener finalizer cannot be written directly to newly created shoot

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#1498]
**What happened**:
#1463 introduced a bug, which may cause that gardener-controller-manager cannot add the  `gardener` finalizer to a newly created shoot and still continue with the reconciliation logic.
E.g. it is possible, that the shoot controller creates other resources which require proper cleanup while the shoot itself is missing the `gardener` finalizer.

Error message:
```
time="2019-10-10T15:51:25+02:00" level=error msg="Could not add finalizer to Shoot: Operation cannot be fulfilled on shoots.core.gardener.cloud \"fake-shoot\": the object has been modified; please apply your changes to the latest version and try again" operation=reconcile shoot=garden-d067603/fake-shoot
```

**What you expected to happen**:
gardener-controller-manager should add the `gardener` finalizer directly at the start of the reconciliation logic and make sure that this operation is successful or return with an error.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
I am on it and will open a PR in the next days

**Comment by timuthy** [comment]
I'd consider this a blocker for Gardener release `0.31.x` @rfranzke
