### ISSUE TITLE
Broken Node Detection & Retirement

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#15]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:44 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/29_

----

# Story
* As operator I want broken nodes to be removed automatically, so that nothing gets scheduled there anymore, the existing workload is drained/moved, the nodes dont count into my budget (in general/financially and also into the auto-scaler).

# Motivation
Cost saving, business continuity, depending on the reason for the retirement also security.

# Acceptance Criteria
- [ ] Nodes are retired if:
  - [ ] Kubelet fails to call home
  - [ ] Kubelet indicates health issues
  - [ ] Ephemeral disk is full
- [ ] Retirement means (cordoning; actually implicit with next step), draining, and finally terminating the VM so that a new one can be recreated by the scaling group

# Implementation Proposal
See e.g. [KUBE-70](https://jtrack.removed/browse/KUBE-70).

# Definition of Done

- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://git.infra.removed/kubernetes/kube-docs/wiki/Operations%20Guide)?

:information_source: Migrated from Jira issue [KUBE-236](https://jtrack.removed/browse/KUBE-236)

**Comment by vlerenc** [comment]
Done with https://github.com/gardener/auto-node-repair. New https://github.com/gardener/node-controller-manager will replace the logic.
