### ISSUE TITLE
ValidatingWebhook for GCM breaks local setup

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener#1531]
**What happened**:
With the RBAC rules introduced in https://github.com/gardener/gardener/commit/924fb2692c04b5321774e0168ceed510954800aa the local setup doesn't work quite right anymore since you can't create any secrets in the `garden` namespace anymore. Why is this webhook + rules needed in the local setup at all?

**How to reproduce it (as minimally and precisely as possible)**:
Run `make dev-setup` and try to `kubectl apply` e.g. the domain secrets.

**Environment**:
Local setup on Minikube, kind.

**Comment by timebertt** [comment]
+1, I ran into the same problem yesterday.

A possible workaround would be to delete the `"gardener-controller-manager"` `ValidatingWebhookConfiguration`, create the domain secrets you want, rerun `make dev-setup` and then start `gardener-controller-manager` again.

**Comment by rfranzke** [comment]
I'll open a PR that makes the webhook optional, it's not needed in the local setup. The motivation was to  be as near as possible on a real setup.
