### ISSUE TITLE
Credentials are not correctly synced when shoot is in deletion

### ISSUE THREAD

**Issue by schrodit** [gardener/gardener#1542]
**What happened**:

A shoot was deleted with invalid credentials. 
The customer updated the credentials in the project but the new credentials were not synced to the seed.

**What you expected to happen**:
New Credentials are synced to the shoot namespace in the seed so that the shoot can be correctly deleted.

**How to reproduce it (as minimally and precisely as possible)**:
1. create a shoot with valid credentials
2. invalidate the credentials when the shoot was successfully reconciled
3. delete shoot
4. update credentials to valid ones

**Environment**:

- Gardener version: 0.30.5

**Comment by ialidzhikov** [comment]
+1

I also hit this several times and I had to sync manually the updated credentials from the secret in the garden cluster to the secret in the Shoot ns to allow proper deletion.

**Comment by ialidzhikov** [comment]
Btw it is not only the `cloudprovider` secret in the shoot ns, I had to sync also the machineclass secret.

**Comment by ialidzhikov** [comment]
Ok, with v0.33.4 the `cloudprovider` secret is updated but the machineclass secret is not.

**Comment by rfranzke** [comment]
This should be done by the worker controllers as part of the deletion flow.
