### ISSUE TITLE
Deadlock on Seed deletion

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#1555]
**What happened**:
When a Seed is deleted that is still used by at least one Shoot (which is not marked for deletion), a deadlock will occur, so that neither Seed nor Shoots can be deleted and require manual cleanup.

The problem is that the `metadata.generation` of the Seed object is increased on deletion (here: `vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:761`) and the `status.observedGeneration` will not be updated by gcm to match the generation. The deletion process of the Seed is blocked until all referencing Shoots and BackupBuckets are deleted. If you then try to delete the Shoot, the deletion process is also blocked, because it is waiting for the Seed to get ready (waiting for observedGeneration to equal generation).
The same problem occurs for other gardener resources, for example BackupBuckets.

**What you expected to happen**:
The deletion of a Seed which is still used by Shoots should not block the deletion of the Shoots and therefore cause a deadlock.
That means that:
- either the observedGeneration should be updated accordingly in gcm on deletion of the Seed object
- or the generation should not be increased on deletion in the first place

**How to reproduce it (as minimally and precisely as possible)**:
1. create a Seed
1. create a Shoot using that Seed
1. delete the Seed
    - this will increase the generation field
    - this will wait for Shoots and BackupBucket (and transitively BackupEntries) to get deleted
1. delete the Shoot
    - this will wait for the seed to get ready
1. result: deadlock

**Anything else we need to know?**:
According to comments in the apiserver library the generation is increased because "the object has pending finalizers but does not supporting graceful deletion" (ShootStrategy does not implement the RESTGracefulDeleteStrategy interface).

**Environment**:

- Gardener version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by zanetworker** [comment]
@tim-ebert maybe we can implement something similar to this (https://github.com/kubernetes/kubernetes/blob/cb19b56831d54d1d31249949318ef0b07bf00df9/pkg/registry/core/pod/strategy.go#L118 ) for our resources (especially the seed in this case)? 

We would need to have `spec.TerminationGracePeriodSeconds` in the seed spec, or any other spec that wishes to implement the interface...

**Comment by rfranzke** [comment]
Should we simply not wait for a seed to be "up-to-date" in case it is marked for deletion? It will never get up to date anyways because the bootstrap loop is never executed again.

**Comment by timebertt** [comment]
Yes of course, this should be a possible workaround.

**Comment by rfranzke** [comment]
Not sure if I would consider it as "workaround". It's rather the correct implementation as the seed controller will never do any bootstrapping anymore if the seed is deleted, so it doesn't make sense to wait for it.
You wanna go ahead implementing it this way?

**Comment by timebertt** [comment]
Yes, sure.
/assign
