### ISSUE TITLE
Core: kubelet services lose connections to kube-apiserver

### ISSUE THREAD

**Issue by kayrus** [gardener/gardener#1560]
**What happened**:

When kube-apiserver is restarted, some kubelet go routines seem lose connection state and then fail, which leads to reconciliation issues in gardener.

![Screenshot_20191029_132131](https://user-images.githubusercontent.com/4047483/67766591-0a14b380-fa4f-11e9-96fc-0794798c8429.png)

**What you expected to happen**:

Reconciliation should be fine even, when kube-apiserver was restarted

**How to reproduce it (as minimally and precisely as possible)**:

Looks like it is occurred only in OpenStack environment.

**Anything else we need to know?**:

There is a kubernetes upstream issue: https://github.com/kubernetes/kubernetes/issues/82405

**Environment**:

- Gardener version: 0.29.2
- Kubernetes version (use `kubectl version`): 1.15.4
- Cloud provider or hardware configuration: OpenStack
- Others:

@schrodit @afritzler @rfranzke

**Comment by rfranzke** [comment]
I don't think this is something that we can influence, can we? Also, I've never seen this anywhere in the past. The screenshot you linked indicates that the vpn-shoot pod is either not running or not reachable via its load balancer. How is a kubelet restart related here?

**Comment by kayrus** [comment]
@rfranzke it is related to the pod status. when pod status is not updated, other depending services stop working. restarting the kubelet solves the issue. @schrodit is already looking into this. The issue occurs in office landscape as well.

**Comment by kayrus** [comment]
@rfranzke @afritzler according to the latest debug results, this issue hasn't been faced by you, because your production CoreOS VMs are updated manually under the ops control. In our case we're using garden-setup and it has the autoupdate enabled by default.
Our nodes are updated and rebooted almost every 2 weeks (approximately). This leads to a connection problem between kubelet and active kube-apiserver. Once kubelet reconnects, it may face a (50% from my observation) race condition, when we see a pod status reconciliation problem. Thus all pods, depending on the failed pod, fail as well.

**Comment by kayrus** [comment]
fixed in k8s 1.15.8 (1.15.9)

**Comment by ialidzhikov** [comment]
Nice, we just hit that this morning. We restarted the kubelet on the nodes as a workaround which fixed the Deployments, StatefulSets and DaemonSets to properly update their conditions.
Good to know that this was fixed in v1.15.9.
Thank you @kayrus !
