### ISSUE TITLE
☂️- Issue for Gardener Test Cases

### ISSUE THREAD

**Issue by schrodit** [gardener/gardener#1564]
### Motivation
Since Gardener has to manage hundreds or even thousands of clusters in full automation, there is no human involved anymore once deployed. A bug in the controller manager may have catastrophic effects on a productive landscape. Consequently, we must protect ourselves against this worst case scenario with a likewise fully automated output qualification.

The goal is that we can release gardener with confidence and ensure that a gardener installation is working correctly.
This issue should track necessary test cases and their priority in order to achieve this goal and improve the overall test coverage of gardener.

### Test Cases
- [x] Test the manual scale out of a worker in a running cluster (https://github.com/gardener/gardener/pull/1510)
- [x] Test a full reconciliation (maintenance and reconcile) of a shoot cluster (https://github.com/gardener/gardener/pull/1510)
- [x] Test hibernation (https://github.com/gardener/gardener/pull/1276)
- [x] Test wake up of a hibernated shoot (https://github.com/gardener/gardener/pull/1276)
- [x] Validate that rbac is enabled for the gardener cluster (https://github.com/gardener/gardener/pull/1139)
- [x] Test a kubernetes version update
  - [x] Test Minor version update (https://github.com/gardener/gardener/pull/1203)
  - [x] Test Patch Versions update
- [x] Test autoscaler scale up and down across all cloudproviders
- [ ] Test Project creation and deletion
  - [ ] Test Permissions on projects
- [ ] Test multizone cluster

**Comment by ialidzhikov** [comment]
Not sure if it is the right issue, but I just wanted to suggest that we could also add test for  `.spec.kubeProxy.mode`. Afaik we currently do not test with `.spec.kubeProxy.mode: IPVS`, right?

**Comment by timuthy** [comment]
Have you already thought of adding test cases for the different operating systems that we support on major cloud providers? I know the test matrix easily grows here but at least the most important permutations should be covered.

**Comment by dguendisch** [comment]
> Not sure if it is the right issue, but I just wanted to suggest that we could also add test for .spec.kubeProxy.mode. Afaik we currently do not test with .spec.kubeProxy.mode: IPVS, right?

Right, we don't customize `kubeProxy:mode` yet, so we test whatever is the current default.
@ialidzhikov do you happen to have an idea on how much usage there is for `IPVS` currently?
If we'd test `IPVS` as well, would the basic shootapp test (deploying guestbook, etc) suffice or would we need a new test (of course besides creating an `IPVS` enabled cluster)?

> Have you already thought of adding test cases for the different operating systems

Yes, colleagues are running jeos+ubuntu tests (beyond our coreos tests) and we'll soon incorporate at least jeos into the regular test matrix.

**Comment by rfranzke** [comment]
Some ideas:

- [ ] Add labels, taints, annotations to worker pools and see them added
- [x] Disable privileged containers and test that privileged containers are not allowed anymore
- [ ] Configure kube-apiserver settings (OIDC, admission plugins, etc.) and see them being correctly configured
- [ ] Configure kube-controller-manager settings (HPA, feature gates, etc.) and see them being correctly configured
- [x] Configure kube-scheduler settings (feature gates, etc.) and see them being correctly configured
- [ ] Configure kubelet settings (eviction, max pods, etc.) and see them being correctly configured
- [x] Configure cluster-autoscaler settings and see them being correctly configured
- [ ] Enable/disable addons and see them correctly deployed/deleted

- [ ] Check whether `infrastructureConfig`, `controlPlaneConfig`, networking `providerConfig`, etc. are correctly transported to extension resources
- [ ] Enable generic extension and see it being deployed

- [x] Scale down the kube-apiserver component and see the health check getting red
- [ ] Scale down a control plane component and see the health check getting red
- [ ] Break a node object and see the health check getting red (provoke problems, NPD should pick up)
- [ ] Scale down a system component and see the health check getting red

- [ ] Check that `BackupEntry` object is created correctly
- [ ] Change audit policy config map and see reconciliation to get triggered

Not sure if this is already covered:

- [x] Create a hibernated shoot
- [x] Delete a hibernated shoot
- [ ] Test automated hibernation according to schedule

**Comment by grolu** [comment]
Ideas for **Dashboard**
* Have an end-to-end test for Gardener Dashboard, leverage Test Machinery Infrastructure to setup a Gardener Landscape where we can run the tests
  * Create a project
  *  Create a cluster (different providers?)
  * Start a terminal session
  * Delete a cluster
  * Delete a project
…
*  Add tests for Terminal Feature
* * Backend Code
* * Terminal Controller
* Improve Unit Test Coverage in Frontend
* * Test utility methods
* *  Add component tests for components with complex logic
* Refactoring Topics
* * Refactor backend to encapsulate more logic in services, use classes to represent kubernetes entities, e.g. class shoot could have getSeed method, also include caching inside classes

**Comment by timebertt** [comment]
As Seeds are an essential part of Gardener's architecture, we should probably add an integration for Shooting a Seed / Seed Bootstrapping.

See https://github.com/gardener/gardener/pull/2786

In that test we could also check, that important resources / components of the Seed are correctly configured, e.g.:
- [ ] monitoring/logging ingresses are configured with the correct operator credentials
- [ ] gardener-seed-admission-controller is deployed and the deletion protection webhook is working (test via deletion of extension CRD/CRs)

**Comment by rfranzke** [comment]
In a recent sync we identified the following areas where we could improve with unit and/or integration tests:

- [ ] Federated seed controller in gardenlet (https://github.com/gardener/gardener/tree/master/pkg/gardenlet/controller/federatedseed), see also https://github.com/gardener/gardener/issues/2561#issuecomment-671183370
- Improve existing tests:
  - [ ] shoot hibernation test, e.g. with a check that the shoot conditions are correctly set
  - [ ] Cluster-Autoscaler test could be extended, e.g. displaying the proper condition (`EveryNodeReady`) that the cluster is scaling up/down
  - [ ] rolling update/Kubernetes update tests (check for proper condition similar as above)
  - [ ] eliminate flakes in existing "beta"-labeled tests

**Comment by timebertt** [comment]
We could also
- [ ] add a smoke-test style integration tests, which checks if prometheus is able to scrape the most important components/metrics (cc @wyb1 @istvanballok)

**Comment by rfranzke** [comment]
We should also
- [ ] enhance our existing integration tests to try out kubeconfig rotation for a shoot (and whether the cluster is still accessible afterwards)

/cc @schrodit @dguendisch

**Comment by timebertt** [comment]
We should also add integration test cases for
- [ ] shoots with custom dns providers (including a check for the finalizer on the referenced secret)
- [ ] shoots with a configured audit policy (including a check for the finalizer on the referenced configmap)

**Comment by timebertt** [comment]
We need an integration test for
- [ ] gardenlet bootstrapping (via bootstrap token and serviceaccount) - partly addressed by https://github.com/gardener/gardener/pull/2786
- [ ] gardenlet certificate rotation

**Comment by rfranzke** [comment]
There is no development/update whatsoever on this issue for a long time, I suggest closing it for now (obviously, there is not much pull in the open topics).
