### ISSUE TITLE
Default externalTrafficPolicy Nginx ingress service 

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener#1571]
**What would you like to be added**:
By default, when I enable Nginx ingress controller for shoot cluster, *externalTrafficPolicy* is *Cluster*.  There is some drawbacks for this setting:
1. Nginx can't get correct source IP from client: https://kubernetes.io/docs/tutorials/services/source-ip/
2. Possible extra hops between nodes.

Suggest to set the default value to Local
**Why is this needed**:
Some enhancement.

**Comment by rfranzke** [comment]
I think this is cloud specific, right? cc @zanetworker @DockToFuture

**Comment by zanetworker** [comment]
This is cloud-specific yes, it should be possible however needs to be tested on each cloud provider to make sure the LB health checks are fast enough.

**Comment by rfranzke** [comment]
Let's close the PR for now. As discussed, it's probably provider-specific and can be changed with the [shoot webhook concept](https://github.com/gardener/gardener/blob/master/docs/extensions/shoot-webhooks.md).

If you want to change the default in Gardener itself please reopen with experiment results and reasoning why it can be done generally for all infrastructure providers.

**Comment by jia-jerry** [comment]
The desired behavior of externalTrafficPolicy=Local is that the cloud provider only make nodes which have pod running on as listener instances in ELB. This is should be correctly implemented by CCM. Any way, I will try to only enable it in AliCloud extensions. Otherwise, the nginx ingress controller can never get source IP.
