### ISSUE TITLE
Forbid hibernating shoots with problematic webhooks

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1575]
We should prevent `Shoot`s from getting hibernated in case they have `ValidatingWebhookConfiguration`s or `MutatingWebhookConfiguration`s with rules for `CREATE` `pods` or `nodes` and `failurePolicy=Fail`.

Otherwise, we can never wake up this shoot cluster again as new nodes cannot get created, or our system component pods cannot get created (because the validating webhook pod is not yet running).

**Comment by vpnachev** [comment]
> ... in case they have ValidatingWebhookConfigurations or MutatingWebhookConfigurations with rules for CREATE pods or nodes and failurePolicy=Fail.

If the webhook is external, e.g. `[MutatingWebhookConfigurations|ValidatingWebhookConfigurations].webhooks.clientConfig.url` is defined, Gardener should not block hibernation of the cluster.

**Comment by vlerenc** [comment]
Good point(s).

**Comment by timebertt** [comment]
@rfranzke @timuthy @zanetworker and myself discussed on how we want to implement this behaviour.

Here are our thoughts:
As direct communication from the garden cluster to the Shoot is not desired anymore (and will be removed with #1601) the correct place to actually check the webhooks is in the Shoot care controller which will eventually also be part of the Gardenlet and also runs the Shoot health checks.
Still we want to directly deny the request to the gardener apiserver which would hibernate the Shoot to give the user instant feedback. 
Therefore we will introduce a new section `constraints` in the `ShootStatus` of type `[]Condition`. The Shoot Care Controller will run the actual constraint checks and set any constraints (for example `HibernationPossible`) to status `False`. The admission plugin will pick up the constraints array to deny any changes to the Shoot if corresponding constraints are set.

/status in-progress

**Comment by schrodit** [comment]
You should also consider this issue we had with the karydia webhooks: https://github.com/karydia/karydia/issues/235
There they set the `failurePolicy` to `Ignore` but as the timeout was 30s the initial client request timeouted with an error before the failure could be ignored.
