### ISSUE TITLE
Gardenlet

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1576]
Similar to how Kubernetes has the Kubelet to manage pods on nodes we want to have a Gardenlet to manage shoots on seeds.
The idea is to run the shoot reconciliation flow (+ all other controllers communicating with the seed) inside the seed itself, allowing for better network performance and scalability. The gardener-controller-manager will remain the control loops for things that are not requiring to communicate with the seed's API servers.

The following things need to be done for an initial implementation:

* [x] Gardenlet should have its own componentconfig
* Garden-controller-manager keeps following control loops:
  * [x] `CloudProfile` controller
  * [x] `ControllerRegistration` controller
  * [x] `Plant` controller
  * [x] `Project` controller
  * [x] `Quota` controller
  * [x] `SecretBinding` controller
  * [x] `Shoot` maintenance controller
  * [x] `Shoot` hibernation controller
  * [x] `Shoot` quota controller
* Gardenlet gets following control loops:
  * [x] `BackupBucket` controller
  * [x] `BackupEntry` controller
  * [x] `ControllerInstallation` controller
  * [x] `Seed` controller
  * [x] `Shoot` controller
  * [x] `Shoot` care controller
* [x] Gardenlet sends regular heartbeat and maintains the `GardenletReady` condition on `Seed`s
* [x] Garden-controller-manager gets a new seed lifecycle controller that turns the `GardenletReady` condition to `Unknown` if the gardenlet stops sending heartbeats
* [x] Helm chart for Gardenlet
* [x] Gardenlet requests a valid client certificate for the garden cluster with a bootstrap token and the `CertificateSigningRequest` resource
* [x] Gardenlet can deploy its own Helm chart for shooted seeds
* [x] Documentation & Migration Guide

**Comment by mvladev** [comment]
Can you elaborate on 

> Gardenlet sends regular heartbeat and maintains the GardenletReady condition on Seeds

I'll strongly recommend to use the [Lease](https://github.com/kubernetes/api/blob/665c8a257c1af277521b08dd43d5c73570405ef0/coordination/v1/types.go#L23-L37) resource for storing heartbeats and update the status only when something really breaks. See the [Node Heartbeat KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/0009-node-heartbeat.md).

**Comment by rfranzke** [comment]
Thanks for pointing this out! Very interesting! In its initial version it's implemented in a way similar to what the kubelet does today, hence, reporting its ready status as condition in the `Seed` object. I suggest to incorporate it as is, as we definitely won't have these scalability problems for some time (the document talks about 2000 nodes with 10-15 pods each; I doubt that anybody will have more than 50-100 seeds at the moment).
Consequently, we can do this improvement separately (as the PR itself is already quite large as you can imagine). For the same reason the TLS certificate renewal is not yet implemented in the first version. I'll open separate issues for follow-up tasks once the PR is open.
