### ISSUE TITLE
MTU Optimization

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#159]
Marc reported issues with MTU that we should tweak to improve performance. Do you agree/can we do that?

**Comment by vlerenc** [comment]
According to a @dkusidlo this would require the Gardener to use different parameters for different infrastructures. According to @rfranzke this would have to be added or we could use the lowest possible value (which is GCP given the currently supported 4 infrastructures) for the CNI interface as well.

**Comment by marwinski** [comment]
As far as I remember from the performance tests MTUs beyond ~1400 don't really have a big impact. That said, there may be - under certain circumstances - big improvements for some scenarios. That said, increasing the MTU to something like 9000 on AWS is possible (don't know about OpenStack) but I would not recommend it without thourough testing. I doubt that it is really worth the effort.

**Comment by vlerenc** [comment]
My point was more that our default may be too large/not fit the MTU of the network below and we create too many packets (let's say, ours is 1500 and let's say the networking underlay has 1460, then every packet is broken into two, one of 1460 and one of 40 bytes - ideally they should match and having more packets than necessary on the underlay is waste). Take these numbers with a grain of salt - I don't know the exact MTUs and repackaging overhead.

Picking larger MTUs may or may not bring an advantage. I am not an expert. The packets on the underlay will be basically the same, but maybe the overlay wins from a larger MTU, right? Again, shouldn't then again the overlay MTU match/be a multiple of the underlay MTU to avoid unnecessary fragmentation? That's why 9000 is a multiple of 1500. You don't want unnecessary fragmentation and sending more packets than you need to on the underlay, because that's the more expensive operation (usually).

So this ticket is primarily about "matching" the MTUs per cloud provider, not having jumbo frames support.

**Comment by vlerenc** [comment]
What are your thoughts @mkoderer, @dkusidlo?

**Comment by marwinski** [comment]
OK, fragmentation is a big problem - caused this myself :-( But why have an "optimized" setting for all the cloud providers? What we have seen from the performance tests is that it does not really matter whether the MTU is something in between ~1360 and ~1450. So why not agree on something the works in the range of 1400 ?

**Comment by vlerenc** [comment]
Well, also in the light of the extensibility we should strive to keep infrastructure specific stuff where it belongs to, but we can of course first go with a sane default value.

**Comment by vlerenc** [comment]
We could test using `ping` to find the ideal MTU sizes (preferred). From what I can find online:

AWS: 1500, source: https://docs.aws.amazon.com/de_de/AWSEC2/latest/UserGuide/network_mtu.html
Azure: 1500 from the looks, source, no direct one: https://blogs.msdn.microsoft.com/igorpag/2017/04/06/my-personal-azure-faq-on-azure-networking-v3
GCP: 1460, source: https://cloud.google.com/vpn/docs/concepts/mtu-considerations
OpenStack: let's ask our colleagues, e.g. @gonzolino

**Comment by vlerenc** [comment]
Do we have to reserve 20 bytes for repackaging?

Anyway, locations are https://github.com/gardener/gardener/blob/master/charts/shoot-core/charts/calico/templates/config.yaml and https://github.com/gardener/gardener/blob/master/charts/shoot-core/charts/calico/templates/calico.yaml, I guess. Not sure though.

**Comment by dkusidlo** [comment]
@marwinski 
> As far as I remember from the performance tests MTUs beyond ~1400 don't really have a big impact. 

Sure, having 1400 or 1440 doesn't help a lot. Deciding on an MTU really depends on the kind of workload you have, which is something I don't know and therefor cannot decide upon.
What can be seen is a better throughput when using ~9000 byte internally. The (synthetic) performance gain we measured for Jumbo Frames was ~35%. 
External connectivity is a different thing as we have seen with the GCP issue. The internet "standard" usually is 1500. 

@vlerenc 
> The packets on the underlay will be basically the same, but maybe the overlay wins from a larger MTU, right?

Less packets with larger payload means the overhead to size ratio caused by the headers will be less and the devices have to "touch" less packets. 
Fragmentation is only caused when you send a packet larger than the devices on the underlay route support. It must not be a multiple of the underlay! 

> but we can of course first go with a sane default value

Calico provides some information for the cluster MTU there.
```
| Network MTU                 | MTU  | MTU with IP-in-IP |
|-----------------------------|------|-------------------|
| 1460 (GCE)                  | 1460 | 1440 |
| 9001 (AWS Jumbo)            | 9001 | 8981 |
| 1450 (OpenStack VXLAN)      | 1450 | 1430 |
```
Our OpenStack supports 1500, so 1480 would be our "MTU with IP-in-IP" value.
So with < 1440 you should be on the safe side. (but not the best one performancewise). Using `ping -s <byte> -M do <IP>` helps to find working values.

Btw. I think the GCP issue is on your kubify cluster, not the Calico-based shoots.

**Comment by vlerenc** [comment]
> Fragmentation is only caused when you send a packet larger than the devices on the underlay route support.

Right, IFF all switches and hosts on the way are properly configured, it won't matter, I guess.

> It must not be a multiple of the underlay!

I guess you mean "doesn't have to" and not "must not" (darf nicht).

> So with < 1440 you should be on the safe side. (but not the best one performancewise).

Well, not sure what you mean. Let's pick 1440 then, right?

> Btw. I think the GCP issue is on your kubify cluster, not the Calico-based shoots.

Yes, as discussed in the Slack channel (;-)). There is Kubify and the Shoots.

So are we done here, 1440 is the way to go and we do that now for Kubify and the shoots?

**Comment by dkusidlo** [comment]
> I guess you mean "doesn't have to" and not "must not" (darf nicht).

I intentionally used "must not" as in RFC2119 because I assumed you want your packets to get delivered ;) As the DF bit is set it would not get fragmented but dropped.

> So are we done here, 1440 is the way to go and we do that now for Kubify and the shoots?

That is addressed to @marwinski I guess?

**Comment by vlerenc** [comment]
> I intentionally used "must not" as in RFC2119 because I assumed you want your packets to get delivered ;) As the DF bit is set it would not get fragmented but dropped.

Wow, thanks for that clarification. ;-)

It seems a need a lesson in this. Jumbo frames with their 9000 bytes looked like a multiple of the usual 1500 bytes, using one for what normally required 6 packets.

> That is addressed to @marwinski I guess?

Well, yes, and to all else, so 1440 it is then?

@afritzler Can you please change that in Kubify?
@rfranzke And can you do that please for the shoots?

To both: What happens with the existing clusters (all gardens + shoots we have right now)?
