### ISSUE TITLE
Calico IPIP Optimization

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#160]
Marc reported issues with IPIP that we should tweak to improve performance (specifically using IP-in-IP only cross-subnet, not generally, see Calico documentation https://docs.projectcalico.org/v2.2/usage/configuration/ip-in-ip). Do you agree/can we do that?

**Comment by dkusidlo** [comment]
For clusters running on OpenStack the performance increases from < 1 gbps to ~ 6 gbps when switching IPinIP from `Always` to `CrossSubnet` in our test setup. (tested using kubernetes/perf-tests)

The issue then is that the port security blocks the out- and ingoing traffic and removing port security is no option. Adding OpenStack `allowed_address_pairs` to the workers VM port with the calico IPPool subnet fixes this. I'll have a look how to implement this.

**Comment by vlerenc** [comment]
Awesome news!

As for the `allowed_address_pairs` feature and its integration (if I understood it right), the networking is setup in https://github.com/gardener/gardener/blob/master/charts/seed-terraformer/charts/openstack-infra/templates/_main.tf (contact is @rfranzke) and the machines in https://github.com/gardener/machine-controller-manager/blob/master/pkg/driver/driver_openstack.go and https://github.com/gardener/machine-controller-manager/blob/master/pkg/controller/openstackmachineclass.go (contacts are @hardikdr and @prashanth26).
