### ISSUE TITLE
Expose shoot infrastucture information for end users

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener#1609]
**What would you like to be added**:
When a shoot is created, infrastructure (vpc, security grups and etc. ) is created by Gardener via Terraform. Though Gardener operators could find the output from infrastructures.extensions.gardener.cloud in seed cluster, we need to find a way to expose such information to customers. 
**Why is this needed**:
Some users need infrastructure information to do some followup stuff in an automatic way.

**Comment by rfranzke** [comment]
Kind of similar to #1749

**Comment by vpnachev** [comment]
This information has already been available in the `ShootState` resource for the respective shoot.

I think this can be extended to mutating webhook in the `provider-*` extension which will inject the information in the `shoot-core` managedresource. At the end the `shoot-info` configmap (https://github.com/gardener/gardener/pull/1690) will contain the required info. 

What do you think? This will be scenario targeting users without access to the Gardener API.
Or we can close this issue as it is resolved by `ShootState`?

**Comment by rfranzke** [comment]
I think the idea is that end-users can read it from the Gardener API, not (only) from the within the shoot cluster.

**Comment by vpnachev** [comment]
Sure. I was targeting users that do not have access to the Gardener API but only to the shoot API.

**Comment by danielfoehrKn** [comment]
closed in favor of #3873
