### ISSUE TITLE
Allow nodes with root disks of type io1 with configurable iops when creating shoots in aws

### ISSUE THREAD

**Issue by ggaurav10** [gardener/gardener#1627]
**What would you like to be added**:
Today it is not possible to create shoots with nodes that have io1 disks as root disks with configurable iops. Gardener should support that.
**Why is this needed**:
This could be useful for end-users who depend on higher throughput from a node's root disk. In our perf-runs also, we have observed that higher root disk's throughput can be helpful in the cases when large number of containers/pods need to be scheduled together in a single node.
This feature would provide end-users with certain degree of freedom in creating their clusters.

**Comment by rfranzke** [comment]
This is possible as of https://github.com/gardener/gardener-extensions/commit/ddba59f549c2ed50d49bf207242bd56adf126bf2, but only with the new `core.gardener.cloud` API group.
