### ISSUE TITLE
Incorrect state on cluster hibernation

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#1630]
**What happened**:
When Gardener hibernates Shoot clusters, it sometimes happens that the objects in the Shoot's etcd don't reflect the correct state of the cluster. 
The current logic is more or less: scale down the workers, wait for all Node objects to be deleted and then hibernate the control plane.

This can lead to the following state:
All Nodes removed, but Pods still having the state `Running` and Endpoints still containing the Pods' IPs (which is incorrect).
On wakeup the garbage collector in the `kube-controller-manager` cleans up all "orphaned" Pods and cleans the IPs from the corresponding Endpoints.
Because this runs in parallel to i.e. the ReplicaSet controller, kcm tries to create new Pods which will then go through configured admission webhooks.

Together with @schrodit I discovered the following issue:
If the Shoot has `ValidatingWebhookConfigurations` or `MutatingWebhookConfigurations` with rules for `CREATE pods` and `failurePolicy=Ignore` and `timeout=30s` (for example the default `vpa-webhook`) the Shoot might not get woken up correctly.
This is because `kube-apiserver` tries to connect to the Webhook but will timeout after the configured `30s` because the Pod's IP is not reachable. In this time, the request from `kube-controller-manager` will timeout on the client side and the request will be cancelled and therefore the Pod will not be created. The ReplicaSet controller somehow does not retry to create the Pod in this case. Therefore the Shoot cannot be woken up, if the `vpn-shoot` Deployment is affected by this issue.

**What you expected to happen**:
Shoot cluster should be hibernated with a "clean state"

**How to reproduce it (as minimally and precisely as possible)**:
(Hard to reproduce because this is somewhat of a race condition on wakeup between the garbage collector and the other Controllers. Sometimes it will work completely, sometimes a few Pods will be created and a few don't...)
1. Create a Shoot
1. `ValidatingWebhookConfigurations` or `MutatingWebhookConfigurations` with rules for `CREATE pods` and `failurePolicy=Ignore` and `timeout=30s` (i.e. vpa-webhooks)
1. Hibernate the Shoot
1. Wake it up again

**Anything else we need to know?**:
This issue might be the root cause of karydia/karydia#235
The current solution is to restart `kube-controller-manager` of the Shoot, if this issue occurs.

**Environment**:

- Gardener version: 0.31.2, extensions: 0.14.4/1.0.0
- Kubernetes version (use `kubectl version`): Shoot: 1.16.2, Seed: 1.15.5
- Cloud provider or hardware configuration: aws
- Others:

**Comment by timebertt** [comment]
I discussed with @zanetworker and @timuthy on how to check, if the cluster is in a "clean state" before hibernating the control plane.

Here are our thoughts:
- We should wait for all the Endpoints objects in the Shoot to not contain any IPs from the Shoot's PodCIDR. This would indicate that all Pod's reflect the hibernated state (not running anymore) and the Endpoints controller picked it up and removed the Pods' IPs from the Endpoint.
- EndpointSlices in k8s 1.16 should be kept in mind

**Comment by timebertt** [comment]
@schrodit and I could not reproduce this issue in a local setup.
We will analyse this further and then implement a fix for this.

/assign
/status in-progress

**Comment by timebertt** [comment]
Update:
We've been able to reproduce the issue. It seems to be related to k8s v1.16 as we can only reproduce it with v1.16

**Comment by timebertt** [comment]
Update:
We verified that this issue is related to Kubernetes version 1.16 (all patch versions).
I will now proceed with implementing the fix as described above:

> We should wait for all the Endpoints objects in the Shoot to not contain any IPs from the Shoot's PodCIDR. This would indicate that all Pod's reflect the hibernated state (not running anymore) and the Endpoints controller picked it up and removed the Pods' IPs from the Endpoint.

**Comment by vlerenc** [comment]
Thanks for catching this. Indeed, we should avoid this situation (right after getting rid of the nodes shutting down everything before it's properly updated by the various independent controllers).

**Comment by vpnachev** [comment]
IMHO, the actual RCA is shortly described here https://github.com/kubernetes/kubernetes/issues/71508#issuecomment-470126655. Basically the client request timeout before the request from the kube API to the validating/mutating webhook, thus the request is rejected despite the `Ignore` policy.

I am wondering whether the `Nodes` objects are deleted before the control plane is hibernated? If not, this might explain the faulty state of the pods and endpoints after wake-up. 

Could you try to reproduce it with webhook timeout set to 10 seconds or less?

**Comment by timebertt** [comment]
> IMHO, the actual RCA is shortly described here [kubernetes/kubernetes#71508 (comment)](https://github.com/kubernetes/kubernetes/issues/71508#issuecomment-470126655). Basically the client request timeout before the request from the kube API to the validating/mutating webhook, thus the request is rejected despite the `Ignore` policy.

Yes, indeed. That is exactly the issue we were experiencing here.

> I am wondering whether the `Nodes` objects are deleted before the control plane is hibernated? If not, this might explain the faulty state of the pods and endpoints after wake-up.

Before Gardener hibernates the control plane, it waits for all Node objects to be deleted. But at the moment it does not wait long enough before scaling down `kube-controller-manager` for it to update the Pods and Endpoints accordingly.


> Could you try to reproduce it with webhook timeout set to 10 seconds or less?

Yes, we tried this. We managed to wake up the Shoot properly when setting the problematic webhook's timeout to `10s`. In this case the call from `kube-apiserver` to the webhook then times out before the request from `kube-controller-manager` times out from the client side. Therefore Pods can be created successfully as the webhook's `FailurePolicy` is set to `Ignore`.

**Comment by schrodit** [comment]
> We should wait for all the Endpoints objects in the Shoot to not contain any IPs from the Shoot's PodCIDR. This would indicate that all Pod's reflect the hibernated state (not running anymore) and the Endpoints controller picked it up and removed the Pods' IPs from the Endpoint.

Update:
We tested the above mentioned fix which fixes the endpoint issue. But discovered another strange behavior with the pods.
The endpoints are now "cleaned" (some endpoints have `<none>` some have nothing?) but the pods are still `Running`. 
I think we should wait for a real clean state, so all pods are pending and all internal endpoints are `<none>`.

![Screen Shot 2019-11-19 at 15 55 40](https://user-images.githubusercontent.com/7979201/69217097-0ec01980-0b6e-11ea-80b2-c63652ff9f67.png)

**Comment by vpnachev** [comment]
They are in `Running` because the `kubelet` is down and there is nothing to update their status.
Actually, are the Nodes drained during the hibernation?

**Comment by schrodit** [comment]
> They are in Running because the kubelet is down and there is nothing to update their status.

Yes but the kcm will update their state to `Pending` after some time, so we just need to wait until the kcm gc starts updating the pod's status.

**Comment by timuthy** [comment]
> Actually, are the Nodes drained during the hibernation?

This should happen by MCM since the MachineDeployment is scaled down.
/cc @hardikdr @prashanth26

**Comment by prashanth26** [comment]
> > Actually, are the Nodes drained during the hibernation?
> 
> This should happen by MCM since the MachineDeployment is scaled down.
> /cc @hardikdr @prashanth26

Yes, the nodes are always drained on scale-down (in turn hibernation).
