### ISSUE TITLE
Wildcard certificates

### ISSUE THREAD

**Issue by petersutter** [gardener/gardener#1637]
**What would you like to be added**:
If a certificate can be requested because a certificate service is available, e.g. `cert-management` for shoots, gardener should request a wildcard certificate per shoot namespace on the seed. 

**Why is this needed**:
- Could be of use for `Use valid certificates for Grafana and Kibana endpoints` #1482
- Could be of use for `Browser-trusted certificates for kube-apiservers` #1413
- As #1413 is not yet implemented, the gardener dashboard currently creates an ingress for the `kube-apiserver` of a shoot and requests a browser trusted certificate for it.

So we need at least 3 certificates per shoot (`grafana`, `prometheus`, `kube-apiserver`) and potentially more in the future if we do not make use of wildcard certificates.

**Comment by petersutter** [comment]
As of gardener/dashboard#510, at least from the dashboard perspective, we no longer require this as the dashboard now uses wildcard certificates `per seed`.  

Feel free to close this issue if you see no further need from your side for wildcard certificates `per shoot namespace`.

**Comment by timuthy** [comment]
Let's continue on #1482.
