### ISSUE TITLE
CRDs deployed by Gardener-Resource-Manager block shoot clean-up

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#1639]
**What happened**:
Presumably a race condition blocks/defers the deletion of shoot clusters when CRDs are deployed by the Gardener-Resource-Manager.

Gardener deletes all cluster CRDs in the shoot deletion flow. After the deletion, it checks if the resources are gone.

It can happen that the Gardener-Resource-Manager redeploys a deleted CRD before the check is done by Gardener. As a consequence the once deleted CRD is again in the cluster and Gardener retries its clean-up procedure.

**What you expected to happen**:
The deletion flow should continue once the CRDs were deleted successfully.

/cc @DockToFuture @rfranzke 

- Gardener version: 0.31.2

**Comment by DockToFuture** [comment]
Thanks for opening up an issue for this race condition!

**Comment by ialidzhikov** [comment]
`certificates.cert.gardener.cloud` crd gets recreated because of the mr of the extension.
Whats is your fix idea here?

**Comment by timuthy** [comment]
Gardener first deletes all CRDs and then checks for them to be gone.

A quick win could be to directly check for the existence **after each CRD** was deleted. Once gone, we should be confident enough to proceed with the shoot deletion flow.

**Comment by ialidzhikov** [comment]
We do apply the clean && ensureGone pattern not only for crds but for each kubernetes api resource that we clean up during Shoot deletion. Isn't the right solution the extension controller to clean up its managed resources when the shoot is in deletion? If I know that something is being deleted, I would stop applying new things on it.
My initial proposal was to move the `Clean extensions` step before `Clean extended API groups` step but @rfranzke said that we cannot do that because of other reasons.
And do we have Shoot deletions hanging long time because of this issue as I guess I haven't notice such cases for now?

**Comment by timuthy** [comment]
> My initial proposal was to move the Clean extensions step before Clean extended API groups step

This is not possible because it would also delete controllers that have set their `finalizers` on the resource, i.e. the resource is not cleaned up properly.
Let's take the `shoot-cert-service` as an example: It deploys a `certificate controller` to the shoot control plane and puts a `Certificate CRD` into the shoot cluster. When we deleted the `shoot-cert-service` extension before the CRDs in the cluster, the `certificate controller` as well as the `Certificate CRD` would be gone at the same time --> no change for the `certificate controller` to clean-up and remove the finalizers from the `Certificate` resources.

> And do we have Shoot deletions hanging long time because of this issue as I guess I haven't notice such cases for now?

Yes, we've been experiencing this from time to time since the `shoot-cert-service` was released and enabled in our landscapes.

**Comment by timuthy** [comment]
I re-iterated over the situation and came up with the following proposal:

1. Introduce a new field in the `ManagedResource` CRD called `forceRedeploy` which defaults to `true`.
```
apiVersion: resources.gardener.cloud/v1alpha1
kind: ManagedResource
metadata:
  name: extension-shoot-cert-service
  namespace: shoot--project--foo
spec:
  class:
  forceOverwriteAnnotations: false
  forceRedeploy: true
  keepObjects: false
  secretRefs:
  - name: extension-shoot-cert-service-seed
``` 

- `forceRedeploy == true`: resources are re-applied by the controller
- `forceRedeploy == false`: resources are only applied once and deleted when `ManagedResource` is removed.

2. Add a step prior to `Cleaning extended API groups` which sets `forceRedeploy = false` for all `ManagedResources` in the shoot namespace on the seed.

As @ialidzhikov already said:
> If I know that something is being deleted, I would stop applying new things on it.

We that, we can stop it for all `ManagedResources` during shoot deletion.

What do you think @ialidzhikov, @rfranzke?

**Comment by rfranzke** [comment]
Thanks @timuthy, sounds good, although I have the feeling that the `ManagedResource` API could be better streamlined. Though, it's `v1alpha1`, hence, okay for now.
Another (quicker) approach would be to adapt our clean-up logic to only check for resources whose creation timestamp is <= the deletion timestamp of the shoot. One potential "problem" with the above suggestion is that extension controllers could theoretically set the `forceRedeploy` to `true` again.

**Comment by timuthy** [comment]
> Another (quicker) approach would be to adapt our clean-up logic to only check for resources whose creation timestamp is <= the deletion timestamp of the shoot.

Sounds also good to me, thanks for the suggestion :)
