### ISSUE TITLE
Use character not allowed in project and cluster name to split off both in namespace

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#164]
We must avoid namespace clashes, which can occur at present, e.g. when:
* someone creates project aaa and cluster bbb-ccc
* someone else creates project aaa-bbb and cluster ccc
This would result in the same namespace name and problems in creation/with the reconciler that would be confused.

We applied a bandaid in the dashboard for now, forbidding dashes for cluster names, the current split-off character in said namespaces in the seed cluster. However, we need a solution in Gardener (protecting this on a fundamental level, e.g. against programmatic access), but that cannot be banning the dashes, because the present seed names use them and we want no change that would make it impossible to create the landscapes as we have them today. Changing the landscape setup/name of a shoot cluster after creation is not possible either, so we should better come up with a different split-off character and migrate the existing namespaces, but this will take more time and careful planning.

**Comment by rfranzke** [comment]
Namespaces in Kubernetes must respect the regex `[a-z0-9]([-a-z0-9]*[a-z0-9])?`. Hence, we decided to use `shoot--<project>--<name>` in the future.

**Comment by swapnilgm** [comment]
@rfranzke Won't it create same issue,  that project/shoot name should follow regex which don't allow "--"? Won't that be again another bandaid? Are we planning to have this check may be in admission controller or validation?
Instead isn't it better to again use UID as prefix/suffix. Since we will have it (UID) available by the time we create namespace. (UID are supposed to be that way).  Something like `shoot-<project>-<name>-<uid>`.

**Comment by rfranzke** [comment]
Hm, good point. @vlerenc Thoughts?

**Comment by vlerenc** [comment]
Well, `--` will indeed be forbidden, but it can be forbidden in the Gardener directly. `-` can't be forbidden, because its already used by our seed clusters and we can't migrate that easily as of now without the ability to move control planes.

So the plan is to:
- [x] forbid `--` in the Gardener for cluster names
- [x] keep the existing namespaces, but create them with new pattern for new clusters
- [x] forbid `--` in the dashboard for project and cluster names (and no longer `-` for cluster names) --> gardener/dashboard#89 opened and tracked there

The choice was between escaping the separator (which we did) or escaping all dashes in the names (which we didn't) or introduce other postfixes/suffixes (which we didn't).

The reason why this seems to be the better choice is that the very same name is also used elsewhere, e.g. in GCP IDs. Escaping the separator causes a guaranteed (but minimal) length increase of 1 resp. 2, which may still fit the lengths restrictions for said IDs. The other two options lead to even longer IDs. Of course, the last alternative is to have only a technical ID, but this would reduce human readability and if we don't have to, let's stick to human readable stuff, even though it means to have certain limitations on project and cluster names.

**Comment by rfranzke** [comment]
Let's not migrate the namespaces (too difficult), as the `shoot-<project>-<name>` is also the ID of all infrastructure resources.
Let's rather create new clusters with the new scheme, ok?

**Comment by vlerenc** [comment]
And have exceptions throughout the code? Well, if we have to, then so be it, but that's the proverbial technical debt. Sooner or later however, we may have to migrate for this or another reason.

**Comment by rfranzke** [comment]
No exceptions, we'll put the ID (`shoot-<project>-<name>`) in the Shoot status and use it from there.
I doubt that we can migrate all the infrastructure resources without downtime/issues. In AWS the names are often just tags, however, in GCP the names are often the technical IDs of the resources.

**Comment by vlerenc** [comment]
As said, sooner or later we will have to do something painful... we'll have to accept that eventually. Just saying. ;-)

But I agree, it would be waste to do it for this tiny ugly problem. Not worth it.
