### ISSUE TITLE
Adapt labels and annotations to the new API group

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1649]
Currently the annotation to trigger reconciliation on crds such as `Infrastructure`, `Worker` is `gardener.cloud/operation=reconcile`. However the annotation for Shoot is `shoot.garden.sapcloud.io/operation=reconcile`. There are annotation/label keys such as `garden.sapcloud.io/createdBy`, `namespace.garden.sapcloud.io/project`, `shoot.garden.sapcloud.io/ignore`, etc. that could be switched to `<foo>.gardener.cloud/<bar>` format.

**Comment by rfranzke** [comment]
According to @ialidzhikov most of this is done. We are now waiting a couple of releases before removing the final remaining artefacts, and then we can close this issue.
@ialidzhikov please correct me if I'm wrong and thanks for all your efforts!

**Comment by rfranzke** [comment]
@ialidzhikov Could you provide an update of the status of this issue? :)

**Comment by ialidzhikov** [comment]
> @ialidzhikov Could you provide an update of the status of this issue? :)

End-user related labels/annotations (API related ones) are adapted and cleaned up since longtime.

Wrt to the internal ones - I think the leftover items to tackle are:
- [x] controlplane NetworkPolicies still mainly use the deprecated `garden.sapcloud.io/role` label key in the selectors -> needs to be adapted to use `gardener.cloud/role` where it is possible and safe
  - https://github.com/gardener/gardener/pull/4572
  - https://github.com/gardener/gardener/pull/4607
- [x] controlplane Pods still maintain both `garden.sapcloud.io/role` and `gardener.cloud/role` -> end result we want is to have only  `gardener.cloud/role` (I am also leaving the etcd Pods out of scope as we don't want to trigger etcd restart just because of such change in the Pod labels).
  - https://github.com/gardener/gardener/pull/4768
  - https://github.com/gardener/gardener/pull/4783
