### ISSUE TITLE
Name Landscape and Infrastructure in Alert

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#169]
Can we please show the landscape name and the infrastructure kind in the alert, so that we can quickly see where we were hit and whether we were hit by an infrastructure outage like in the past days.

**Comment by rfranzke** [comment]
Closing as it's done, see e.g. this alert email:

```
Labels
alertname = VPNConnectionDown
app = kubernetes
cluster = shoot--project--name
instance = 10.243.129.245:9115
job = vpn-connection
pod = kube-apiserver-fcbd48b5b-zm958
pod_template_hash = 976804616
role = apiserver
seed_api = https://<apiserver-of-seed-cluster>
seed_profile = az
seed_region = westeurope
service = vpn
severity = critical
type = shoot
Annotations
description = VPN connection for kube-apiserver-fcbd48b5b-zm958 is down. No resources of the Shoot cluster can be accessed by this pod.
summary = VPN connection down
```

**Comment by vlerenc** [comment]
Where do I see it @rfranzke / @mvladev? When you closed it, I noticed it in the URL, but that was rather implicit. Now I have noticed that this implicit behaviour fails e.g. for our seeds for alerts from the soil:
```
Labels
alertname = KubeControllerManagerDown
cluster = shoot-garden-aws
job = kube-controller-manager
seed_api = https://35.195.210.103
seed_profile = gcp
seed_region = europe-west1
service = kube-controller-manager
severity = critical
type = seed
Annotations
description = There is no running K8S controller manager. Deployments and replication controllers are not making progress.
summary = Controller manager is down
```
I basically would like to have something that I can use to categorise the alerts. One problem certainly is that the notion of landscape is not part of the Open Source Gardener, but a naming/grouping property. Can we introduce it as alert configuration (that we include in all alerts) like we have it for the email credentials?

@mvladev Or can you expedite the process of getting dedicated email credentials and the community and we go by that?

**Comment by rfranzke** [comment]
You're right, thanks. The infrastructure is implicit due to the `seed_profile` (which in general does not need to contain the infra name but could have any name), and the landscape name was implicit as well due to the `seed_api` (which, again, does not need to contain any "landscape name" in general).
As you already pointed out we should one name/group property to the alert config for representing the landscape. The infrastructure should be a separate key, generated by Gardener and injected into the alertmanager config.
@mvladev or @dkistner, can you please take over?

**Comment by vlerenc** [comment]
@dkistner WDTY?

**Comment by rfranzke** [comment]
@dkistner @wyb1 will you do that soon? If not, let's close the ticket, it's open for too long anyways. We don't have yet a landscape/gardener installation name, but there is gardener/gardener-extensions#183 which needs such name for other reasons (FYI)

**Comment by wyb1** [comment]
I can add the infrastructure of the shoot to the alert but adding the landscape will be more difficult.
