### ISSUE TITLE
Too many conflicts for constraint and condition updates

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#1697]
Since #1642 we've observed many conflicting updates in the controller manager logs:
```
level=error msg="Attempt 1 failed to update Shoot xyz due to Operation cannot be fulfilled on shoots.core.gardener.cloud \"xzy\": the object has been modified; please apply your changes to the latest version and try again"
```

This is probably because the health and constraint checks run in parallel and try to update the shoot resource shortly after another. While it makes sense to do the checks in parallel, we should combine the results and update the shoot status afterwards to avoid the conflicts. I don't want to blame conflicts in general but we should avoid them at places we know they are very likely to happen. With that we reduce the pressure at the API server and save bandwidth.

Always happy to read your opinion!

**Comment by rfranzke** [comment]
Oh, I didn't see that this is happening. Can we simply change this logic? We can calculate the `conditions` and the `constraints` in parallel, but there should be only one update call to the status.
@tim-ebert ?

**Comment by rfranzke** [comment]
I start working on it.
