### ISSUE TITLE
ETCD Backup & Restore

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#17]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:44 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/31_

----

# Story
* As provider I want etcd backups for my shoot clusters, so that I can restore them should they be lost.
* Later: As provider I want etcd backups to be restored automatically should the PV be definitely lost or the current etcd can't start from the current state.   

# Motivation
Business continuity.

# Acceptance Criteria
- [x] Regular etcd backups are taken by the garden operator for all shoot clusters and are made known to the Gardener UI via TPRs/CRDs
  - [x] AWS
  - [x] Azure
  - [ ] GCP
  - [ ] OpenStack

# Resources
* Take a look at the [CoreOS etcd operator](https://github.com/coreos/etcd-operator) if you can
* Maybe [Heptio Ark](https://blog.heptio.com/announcing-two-new-heptio-open-source-projects-heptio-ark-and-heptio-sonobuoy-7cef88a06f8) (disaster recovery) may be interesting to check out
* See also https://github.com/coreos/etcd/blob/master/Documentation/op-guide/recovery.md#restoring-a-cluster

# Open Questions
How frequent can we backup the data? Can we replicate the data on a lower level with a sidecar deployment or would we need an etcd cluster then? Is there something like point in time recovery for etcd?

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://git.infra.removed/kubernetes/kube-docs/wiki/Operations%20Guide)?

:information_source: Migrated from Jira issue [KUBE-158](https://jtrack.removed/browse/KUBE-158)

**Comment by vlerenc** [comment]
Replaced with https://github.com/gardener/etcd-backup-restore/issues/1.
