### ISSUE TITLE
Support etcd encryption for Gardener resources

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#1704]
**What would you like to be added**:
Kubernetes has offered encryption for native resources since 1.13 (https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/). Gardener is an extension API server that comes with its own api groups and resources for which encryption should also be possible.

**Why is this needed**:
Some Gardener resources might contain sensitive information (e.g. values of `ControllerRegistration`), so secrecy should be protected by encryption.

**Comment by rfranzke** [comment]
cc @EmoinLanyu
