### ISSUE TITLE
Add hack/check-generate.sh

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1708]
g/g can have a `hack/verify-codegen.sh` script such as the k8s.io/sample-apiserver. The same mechanism we have also in g/gext where we have `hack/check-generate.sh`.
I would be very nice if g/g has similar script and the ci/cd to fail when the code generation is not ran.

**Comment by rfranzke** [comment]
If we add this a good idea would be to run everything inside a container, see also https://github.com/gardener/gardener-extensions/issues/122
