### ISSUE TITLE
Seed Cluster Monitoring Data Missing

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#172]
Some monitoring dashboards lack information (also reported in regards to raw data/etrics by the performance team, Kesavan S):
<img width="1379" alt="screen shot 2018-05-16 at 11 08 33" src="https://user-images.githubusercontent.com/4974203/40107904-d9cb26fc-58f9-11e8-9a2c-3305251b42c0.png">

Or:
<img width="1399" alt="screen shot 2018-05-16 at 11 08 09" src="https://user-images.githubusercontent.com/4974203/40107922-e2d1aa1e-58f9-11e8-9c07-6394a8aa6cef.png">

**Comment by mvladev** [comment]
The seed cluster's Prometheus is the problem. It is ingesting too many time-series (many containers / pods being created). I've reduced the retention period even further with #182 , but there are some problems in the 2.2.x release.

**Comment by rfranzke** [comment]
Closing this one, since the latest improvements the seed's Prometheus runs quite stable. Please reopen if necessary.
