### ISSUE TITLE
Harden Gardenlet RBAC privileges in the seed cluster

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1724]
With #1601 we have introduced the gardenlet, a component comparable with the kubelet in Kubernetes.

However, in this first introduction we have not hardened the `ClusterRole`s we bind the gardenlet to in the seed ([ref](https://github.com/gardener/gardener/blob/1e591cc942e3c968407ace20f3e9cc0f183f7438/charts/gardener/gardenlet/charts/runtime/templates/rbac.yaml#L5-L22)).

This is true for both the garden and the seed cluster.
For the garden cluster, we plan to address this with a special authorization plugin, see #1724.
For the seed cluster, we should harden these RBAC roles in order to only allow access to those resources it needs to access.

**Comment by rfranzke** [comment]
/assign @vpnachev @ialidzhikov 

First step would be to record the gardenlet's activities on the seed and improve its RBAC role (https://github.com/gardener/gardener/blob/master/charts/gardener/gardenlet/charts/runtime/templates/rbac.yaml#L16-L22).
@vpnachev suggested to use https://github.com/liggitt/audit2rbac to convert the recorded audit logs into RBAC rules.

/security
/normal
/in-progress

**Comment by timebertt** [comment]
FYI: with https://github.com/gardener/gardener/pull/3535 the gardenlet also needs permission for `leases` in the seed.
