### ISSUE TITLE
Garden Resource Lists Not Aligned

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#174]
When listing resources of a kind, e.g. shoots by calling `kubectl get shoots --all-namespaces`, the output is not aligned. Can this be improved? It would increase readability.

**Comment by swapnilgm** [comment]
This was [bug](https://github.com/kubernetes/kubernetes/issues/56282) with `CustomColumnPrinter` in kubernetes.

**Comment by vlerenc** [comment]
Oh, wow, it got fixed just lately. Who would think. Thanks for pointing out!
