### ISSUE TITLE
Multiple worker volumes, volume encryption and kubelet volume

### ISSUE THREAD

**Issue by guydc** [gardener/gardener#1743]
**What would you like to be added**:

Currently, only the root device of a gardener worker can be configured. This device is used both by the OS and k8s, meaning that k8s persistent state is stored on this volume. No additional volumes can be configured and attached to the worker machine. There is no way to indicate if a volume should be encrypted or not. 

Gardener should allow an arbitrary number of data volumes to be configured and attached to a worker node. Worker data volumes should be configurable for IaaS encryption, and one of them can be designated as the kubelet data volume. The kubelet data volume, if it exists, should be `xfs`-formatted and mounted to `/var/lib`. Non-kubelet data volumes should only be attached to the node. 

**Why is this needed**:

Ephemeral pod storage and `emptydir` volumes are persisted on the worker's volume, and may contain sensitive data that should be encrypted. Infrastructure providers have varying levels of support for OS volume encryption (limitations: [azure](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption-overview), [alicloud](https://www.alibabacloud.com/help/doc-detail/59643.htm)). As a result, such data cannot always be IaaS-encrypted. Data volume encryption is supported by all major providers. Using a data-volume for kubelet data would make encryption possible. 

Using xfs will enable [enhanced ephemeral storage management](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20180906-quotas-for-ephemeral-storage.md).

Additionally, support for arbitrary data volumes can enable scenarios such as memory expansion.

**Comment by rewiko** [comment]
Also having multiples disks allow isolation and guarantee the IOPS foreach mounted path. 
For example docker and kubelet path should use a different disk, when kubelet is using a lot's of IO because of an EmptyDir writing a lot, the docker volume and docker daemon will not be affected.
