### ISSUE TITLE
Seed(Soil) created by Gardenlet lacks volume infromation in Alicloud

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener#1744]
**What happened**:
When  deploying a Garden(soil) cluster, after gardenlet is deployed in the soil cluster, the seed representing soil cluster is generated by Gardenlet. However, the seed lacks all volume information like *persistentvolume.garden.sapcloud.io/minimumSize: 20Gi*.
And also, it is even worse, after update a Gardener cluster by enabling Gardenlet, *persistentvolume.garden.sapcloud.io/provider: FlexVolume* disappeared.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
Can you share the gardenlet component config?

**Comment by EmoinLanyu** [comment]
> Can you share the gardenlet component config?

It turns out to be a problem of configuration of gardenlet:

Current configuration is:
```
SeedConfig:
  Spec:
  Volume:
```

While it should be:

```
SeedConfig:
  Spec:
    Volume:
```

So perhaps we can close this issue :)
