### ISSUE TITLE
Write secret refs to Shoot status

### ISSUE THREAD

**Issue by petersutter** [gardener/gardener#1749]
**What would you like to be added**:
E.g. the kubeconfig for a shoot can be found in a secret named `${shootName}.kubeconfig`, at least this is the current convention. 
It would be nice if the secret references for a shoot would be written to the Shoot status.

**Why is this needed**:

**Comment by vpnachev** [comment]
>  It would be nice if the secret references for a shoot would be written to the Shoot status.

Could you elaborate?
Why is this needed?
