### ISSUE TITLE
Improve Shoot Hibernation Prevention Check

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#1751]
**What would you like to be added**:

Recently we have introduced a validation(https://github.com/gardener/gardener/pull/1642) that prevents shoot hibernation in case the cluster has a validating or mutating webhook which might block creation of new pods or nodes. The motivation is that such clusters cannot be waken up later.

The validation [logic](https://github.com/gardener/gardener/blob/ca5c68dd4102c519a31ca5f52462874c3a194803/pkg/operation/botanist/constraints_check.go#L59-L138) can be improved by using [ShouldCallHook](https://github.com/kubernetes/kubernetes/blob/127c47caf49bec4a59a0500f99b1b1d4cdbf340e/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/generic/webhook.go#L143-L204). 
The unit [tests]( https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/generic/webhook_test.go) provide good examples how it can be used.

So, the following api requests must not be blocked by any webhook
*  creations of pods in `kube-system` namespace labeled with `origin=gardener`.
* creation of nodes

**Why is this needed**:
There are clusters with not so harmful admission webhooks and the hibernation for them should be possible.

**Comment by timuthy** [comment]
We can also think about extending the list above by `endpoints` in `kube-system`. Or at least some other implementation to prevent the following scenario:

- Cluster with `Mutatingwebhookconfiguration` on `endpoints`
- Cluster entered hibernation
- The endpoints of the service backing the `Mutatingwebhookconfiguration` still existed
- KCM tried to renew it's leader election (`renew-deadline` 10s) but didn't succeed because the Kube-Apiserver timed out calling the webhook
- Eventually, all running `Pods` in the cluster couldn't be garbage collected and the shoot wasn't able to completely hibernate.

**Comment by rfranzke** [comment]
As suggest by @tim-ebert it makes also sense to improve the "check if endpoints exist" check. Custom operators might manage `Endpoint` objects on their own. Hence, let's ignore all `Endpoint`s that don't belong to `Service`s (identifiable by looking at the `Service` object with the same name like the `Endpoint` object - if no label selector is present then the `Endpoint` was not created by KCM endpoint controller).

**Comment by loewenstein** [comment]
Is there an eta for this issue?

**Comment by timebertt** [comment]
I will take a look at improving the "check if endpoints exist" check, now.
I think @vpnachev has already put some work (or at least thought) into improving the hibernation validation, so I will not touch that part of the issue.

**Comment by loewenstein** [comment]
Currently, clusters with Istio installed cannot be hibernated. That's why I asked. Not sure if endpoints are relevant. @vpnachev is there an eta for relaxing the Pod mutation webhook check?

**Comment by mvladev** [comment]
https://github.com/gardener/gardener/pull/2270
