### ISSUE TITLE
API-only repository for CRDs and client factories

### ISSUE THREAD

**Issue by tareksha** [gardener/gardener#1768]
Hi,

I'm trying to write some go code that uses gardener's generated CRD definitions and client factories. Specifically I'm talking about the package hierarchy under `github.com/gardener/gardener/pkg/client/` and `github.com/gardener/gardener/pkg/apis/`.

However, currently this causes fetching the whole code tree and pumping in a huge amount of indirect dependencies, eventually growing the final binary size by tens of MBs and bloating the build process. The repository structure seems less suited for reusing the client API as a library,

Is it possible to split the client and apis sub-packages int a dedicated repository with minimal indirect dependencies?

thank you

**Comment by timuthy** [comment]
Hi @tareqhs,

what do you use for dependency management, e.g. go mod and what does your build process looks like?

I presume that once vendored and pruned (tidy) the final binary should be quite small and building the software fast as well (unless you revendor every time).

**Comment by tareqhs** [comment]
hi @timuthy,
I use go 1.12 modules, no vendor dirs. My code is a standard kubernetes client code, roughly like this:
```go
import (
	garden "github.com/gardener/gardener/pkg/client/garden/clientset/versioned"
)
config := ...
gclient, err := garden.NewForConfig(config)
...
shoot, err := pdata.gclient.GardenV1beta1().Shoots("")...
```

**Comment by tareksha** [comment]
hi @timuthy,
I use go 1.12 modules, no vendor dirs. My code is a standard kubernetes client code, roughly like this:
```go
import (
	garden "github.com/gardener/gardener/pkg/client/garden/clientset/versioned"
)
config := ...
gclient, err := garden.NewForConfig(config)
...
shoot, err := gclient.GardenV1beta1().Shoots("")...
```
This code goes through some isolated CI flows and takes minutes to bring all the dependencies, eventually building an overly sized binary.

**Comment by rfranzke** [comment]
Hm, I don’t understand, you can still prune and tidy all unused packages that come from other repositories but are not used in pkg/apis or pkg/client as @timuthy pointed out. Then you‘ll only remain with the minimum number of required packages used to build these two. I think this is the way to go. I don’t think we can easily „just move the two packages out“. It requires some automatism like k/k has with its staging repositories, automatic release tagging and branch management, etc. - all of this we don’t have today.

**Comment by ialidzhikov** [comment]
Hi @tareqhs ,

1) Switch to `pkg/client/core/clientset/versioned`

I see you are using
```go
import (
	garden "github.com/gardener/gardener/pkg/client/garden/clientset/versioned"
)
```

which is the clientset for the old and deprecated `garden.sapcloud.io` apiGroup. The Gardener team introduced a new apiGroup which is `core.gardener.cloud`. The proper import for you needs to be
```go 
import (
	garden "github.com/gardener/gardener/pkg/client/core/clientset/versioned"
)
```

2) To prevent each time module resolution you can vendor once (and probably track your `vendor/` dir in the VCS) and use `-mod=vendor` flag (or `GOFLAGS=-mod=vendor`) to instruct the go tool to use the dependencies under `vendor/`.

3) We can check also from our side these packages for imports that brings some transitive dependencies but actually they are not used.

**Comment by tareksha** [comment]
hi @rfranzke, @ialidzhikov,

Thanks for the first suggestion, indeed it was my bad - i have to use the new versions anyway. This didn't really reduce the size - originally my binary grew from 15MB to 39MB due to gardener packages, now it is 38MB. I'm assuming the most of the dependencies are common here. `go mod tidy` didn't help much - it merely simplified `go.mod`.

Regarding the vendoring suggestion- I'm afraid I can't do this. And most dev can't either - go is moving to 1.12/1.13 for a reason and committing vendored packages will explode the version control. I really think we should have a proper repository for "library" or "sdk" usage of gardener APIs.

**Comment by ialidzhikov** [comment]
>  I'm assuming the most of the dependencies are common here.

There is `go mod why -m github.com/foo/bar` which can tell you why given package ended up under your `vendor/`. If there is a package you think that is brought by gardener/gardener and should not be under your `vendor/`, please share. Saying "it's too big" is not a valid argument.
#1770 will be a small improvement from our side. :)

> Regarding the vendoring suggestion- I'm afraid I can't do this. And most dev can't either - go is moving to 1.12/1.13 for a reason and committing vendored packages will explode the version control.

k/k are pushing their `vendor/`, moby/moby also, such as many other projects.

>  I really think we should have a proper repository for "library" or "sdk" usage of gardener APIs.

As far as I know k/k are just publishing the staging content of a package in the mono repo to dedicated repositories. In fact I guess there is no difference whether you will use the package from the dedicated repo, or from the mono repo.

**Comment by tareksha** [comment]
@ialidzhikov please allow me to put it simple. My goal is to use gardener's go APIs as go library for performing various operations on my shoots. The gardener code currently ends up bringing in a large dependency tree and dominating the build process.

I've also made a small research here. Actually I think the issue is actually more about internal package structuring. This is an example source:
```go
package main
import(
  garden "github.com/gardener/gardener/pkg/client/core/clientset/versioned"
)
func main()  {
  garden.NewForConfig(nil)
}
```
Compiling this code generated a binary of 36MB in size. More specifically, listing compiled packages via `go build -v myfile.go` yields this output - these are the packages required directly/indirectly for the gardener APIs alone:
```
k8s.io/apimachinery/pkg/selection
github.com/gardener/gardener/pkg/apis/core/v1alpha1/constants
github.com/gardener/gardener/pkg/apis/core/v1beta1/constants
k8s.io/utils/integer
golang.org/x/text/transform
github.com/gogo/protobuf/sortkeys
k8s.io/apimachinery/pkg/util/sets
github.com/hashicorp/errwrap
github.com/konsorten/go-windows-terminal-sequences
k8s.io/apimachinery/pkg/util/rand
k8s.io/apimachinery/pkg/version
github.com/gogo/protobuf/proto
github.com/google/gofuzz
gopkg.in/inf.v0
k8s.io/apimachinery/third_party/forked/golang/reflect
k8s.io/apimachinery/pkg/util/errors
k8s.io/apimachinery/pkg/fields
k8s.io/klog
k8s.io/apimachinery/pkg/conversion/queryparams
k8s.io/apimachinery/pkg/util/json
k8s.io/apimachinery/pkg/util/naming
k8s.io/apimachinery/pkg/conversion
k8s.io/apimachinery/pkg/types
k8s.io/apimachinery/pkg/util/validation/field
golang.org/x/text/unicode/bidi
k8s.io/apimachinery/pkg/util/runtime
golang.org/x/text/unicode/norm
golang.org/x/net/http2/hpack
k8s.io/apimachinery/pkg/runtime/schema
k8s.io/apimachinery/pkg/api/resource
k8s.io/apimachinery/pkg/util/intstr
golang.org/x/text/secure/bidirule
github.com/Masterminds/semver
k8s.io/apimachinery/pkg/util/validation
github.com/hashicorp/go-multierror
k8s.io/apimachinery/pkg/runtime
github.com/sirupsen/logrus
github.com/modern-go/concurrent
golang.org/x/net/idna
k8s.io/apimachinery/pkg/util/framer
k8s.io/apimachinery/pkg/labels
gopkg.in/yaml.v2
k8s.io/client-go/pkg/version
github.com/modern-go/reflect2
github.com/davecgh/go-spew/spew
golang.org/x/sys/windows
golang.org/x/net/http/httpguts
golang.org/x/net/context/ctxhttp
k8s.io/client-go/util/connrotation
k8s.io/apimachinery/pkg/runtime/serializer/recognizer
sigs.k8s.io/yaml
k8s.io/apimachinery/pkg/runtime/serializer/streaming
golang.org/x/net/http2
k8s.io/client-go/tools/clientcmd/api
golang.org/x/oauth2/internal
k8s.io/client-go/tools/metrics
k8s.io/apimachinery/pkg/util/yaml
k8s.io/client-go/util/keyutil
golang.org/x/time/rate
golang.org/x/oauth2
golang.org/x/crypto/ssh/terminal
k8s.io/apimachinery/pkg/util/clock
github.com/golang/protobuf/proto
k8s.io/client-go/util/cert
github.com/json-iterator/go
k8s.io/client-go/util/flowcontrol
k8s.io/apimachinery/pkg/util/net
k8s.io/client-go/transport
k8s.io/apimachinery/pkg/watch
github.com/golang/protobuf/ptypes/any
github.com/golang/protobuf/ptypes/timestamp
github.com/golang/protobuf/ptypes/duration
k8s.io/apimachinery/pkg/runtime/serializer/json
k8s.io/apimachinery/pkg/apis/meta/v1
github.com/golang/protobuf/ptypes
github.com/googleapis/gnostic/extensions
github.com/googleapis/gnostic/compiler
github.com/googleapis/gnostic/OpenAPIv2
k8s.io/api/rbac/v1
github.com/gardener/gardener-extensions/controllers/provider-gcp/pkg/apis/gcp
github.com/gardener/gardener-extensions/controllers/provider-azure/pkg/apis/azure
github.com/gardener/gardener-extensions/controllers/provider-alicloud/pkg/apis/alicloud
github.com/gardener/gardener-extensions/controllers/provider-aws/pkg/apis/aws
github.com/gardener/gardener-extensions/controllers/provider-openstack/pkg/apis/openstack
k8s.io/api/core/v1
github.com/gardener/gardener-extensions/controllers/provider-gcp/pkg/apis/gcp/v1alpha1
github.com/gardener/gardener-extensions/controllers/provider-azure/pkg/apis/azure/v1alpha1
github.com/gardener/gardener-extensions/controllers/provider-aws/pkg/apis/aws/v1alpha1
github.com/gardener/gardener-extensions/controllers/provider-alicloud/pkg/apis/alicloud/v1alpha1
github.com/gardener/gardener-extensions/controllers/provider-openstack/pkg/apis/openstack/v1alpha1
github.com/gardener/gardener/pkg/utils
k8s.io/apimachinery/pkg/runtime/serializer/protobuf
github.com/gardener/gardener-extensions/controllers/provider-gcp/pkg/apis/gcp/install
github.com/gardener/gardener-extensions/controllers/provider-aws/pkg/apis/aws/install
github.com/gardener/gardener-extensions/controllers/provider-azure/pkg/apis/azure/install
github.com/gardener/gardener-extensions/controllers/provider-alicloud/pkg/apis/alicloud/install
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured
github.com/gardener/gardener-extensions/controllers/provider-openstack/pkg/apis/openstack/install
k8s.io/apimachinery/pkg/api/errors
k8s.io/client-go/pkg/apis/clientauthentication
k8s.io/client-go/rest/watch
k8s.io/api/admissionregistration/v1beta1
k8s.io/api/auditregistration/v1alpha1
k8s.io/api/authentication/v1
k8s.io/client-go/pkg/apis/clientauthentication/v1alpha1
k8s.io/apimachinery/pkg/runtime/serializer/versioning
k8s.io/client-go/pkg/apis/clientauthentication/v1beta1
k8s.io/api/authentication/v1beta1
k8s.io/api/authorization/v1
k8s.io/api/authorization/v1beta1
k8s.io/api/certificates/v1beta1
k8s.io/apimachinery/pkg/runtime/serializer
k8s.io/api/coordination/v1
k8s.io/api/coordination/v1beta1
k8s.io/api/node/v1alpha1
github.com/gardener/gardener/pkg/apis/garden
k8s.io/api/apps/v1
k8s.io/api/apps/v1beta1
k8s.io/api/apps/v1beta2
k8s.io/api/autoscaling/v1
k8s.io/client-go/plugin/pkg/client/auth/exec
k8s.io/api/autoscaling/v2beta1
k8s.io/api/autoscaling/v2beta2
github.com/gardener/gardener/pkg/apis/core
k8s.io/client-go/rest
k8s.io/api/batch/v1
k8s.io/api/events/v1beta1
k8s.io/api/extensions/v1beta1
k8s.io/api/networking/v1
k8s.io/api/networking/v1beta1
k8s.io/api/batch/v1beta1
k8s.io/api/batch/v2alpha1
k8s.io/api/node/v1beta1
github.com/gardener/gardener/pkg/apis/core/v1alpha1
k8s.io/api/policy/v1beta1
github.com/gardener/gardener/pkg/apis/core/v1beta1
k8s.io/api/rbac/v1alpha1
k8s.io/api/rbac/v1beta1
k8s.io/api/scheduling/v1alpha1
k8s.io/api/scheduling/v1
k8s.io/api/scheduling/v1beta1
k8s.io/api/settings/v1alpha1
k8s.io/api/storage/v1
k8s.io/api/storage/v1alpha1
k8s.io/api/storage/v1beta1
github.com/gardener/gardener/pkg/client/core/clientset/versioned/scheme
k8s.io/client-go/kubernetes/scheme
github.com/gardener/gardener/pkg/client/core/clientset/versioned/typed/core/v1beta1
github.com/gardener/gardener/pkg/client/core/clientset/versioned/typed/core/v1alpha1
k8s.io/client-go/discovery
github.com/gardener/gardener/pkg/client/core/clientset/versioned
```
After analyzing the compile graph and the sizes of the intermediate compilation units, I can see that bulk mostly comes from the packages under `github.com/gardener/gardener-extensions`, these are brought by the conversion logic:
* https://github.com/gardener/gardener/blob/v0.33.6/pkg/apis/core/v1beta1/conversions.go
* https://github.com/gardener/gardener/blob/v0.33.6/pkg/apis/core/v1alpha1/conversions.go

**Comment by rfranzke** [comment]
The dependency to g/g-extensions is only needed for backwards compatibility and will go away in January 2020, so very soon. Will this solve your problem?
Eventually, everything that is vendored when importing `g/g/pkg/apis` is required to build/compile the binary, so how would putting the packages in a separate repository help with the overall size in the end?

**Comment by rfranzke** [comment]
As the g/gardener-extensions dependency is gone we will close this issue for now. Please reopen if you still have problems.
