### ISSUE TITLE
Remove confusing warning logs for CoreDNS

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1788]
**What would you like to be added**:
As of #1541 it is possible for end-users to customize CoreDNS. Though, in the 99% case the CoreDNS is *not* customized. Still, it produces regularly the following logs:

```
[WARNING] No files matching import glob pattern: custom/*.override
[WARNING] No files matching import glob pattern: custom/*.server
[WARNING] No files matching import glob pattern: custom/*.override
[WARNING] No files matching import glob pattern: custom/*.server
[WARNING] No files matching import glob pattern: custom/*.override
[WARNING] No files matching import glob pattern: custom/*.server
[WARNING] No files matching import glob pattern: custom/*.override
[WARNING] No files matching import glob pattern: custom/*.server
[WARNING] No files matching import glob pattern: custom/*.override
[WARNING] No files matching import glob pattern: custom/*.server
[WARNING] No files matching import glob pattern: custom/*.override
[WARNING] No files matching import glob pattern: custom/*.server
[WARNING] No files matching import glob pattern: custom/*.override
[WARNING] No files matching import glob pattern: custom/*.server
[WARNING] No files matching import glob pattern: custom/*.override
[WARNING] No files matching import glob pattern: custom/*.server
[WARNING] No files matching import glob pattern: custom/*.override
[WARNING] No files matching import glob pattern: custom/*.server
[WARNING] No files matching import glob pattern: custom/*.override
[WARNING] No files matching import glob pattern: custom/*.server
...
```

Let's please get rid of these logs to not unnecessary pollute it.

**Why is this needed**:
There is no benefit in seeing these logs and it is confusing for end-users.

**Comment by zanetworker** [comment]
the log level is already error only, looks like a bug to me in CoreDNS. 
  https://github.com/gardener/gardener/blob/c92bb7252c40564d61db234b5c711e5821b0a498/charts/shoot-core/components/charts/coredns/values.yaml#L40

Should we file an issue? or what do you suggest here?

**Comment by rfranzke** [comment]
Sure, if you think it's a bug then file an issue. If it's not a bug then it might make sense to clarify with the CoreDNS community whether there is an option to remove these logs.
