### ISSUE TITLE
Garden, Seed & Shoot Cluster Disaster Recovery

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#18]
# Story
- As provider I need a plan for disaster recovery, so that I can resurrect lost infrastructure and restore my service.

# Acceptance Criteria
Please find out what we need to do when we completely lose a shoot or even seed or soil cluster:
- [ ] **Total loss and recreation of only the shoot cluster worker environment**: What do we need to do to reconstruct the worker environment if we lose it from the VPC and instance profiles down to the VMs (most likely a no-brainer, just rerun the provisioning)
- [ ] **Total loss and recreation of the shoot cluster control plane**: What do we need to do to reconstruct the shoot cluster control plane (assuming we lost everything from the namespace down to the etcd persistence, but have a backup of the latter)
- [ ] **Total loss and move to another soil or seed cluster**: What do we need to do to move to/ reconstruct the soil or seed cluster (assuming we lost everything from the cluster itself down to the etcd persistence, but have a backup of the latter)
- [ ] **Total loss and move to another garden cluster**: What do we need to do to move to/reconstruct the garden cluster (assuming we lost everything from the cluster itself down to the etcd persistence, but have a backup of the latter)

Please manually execute the reconstruction of the above scenarios, validate the reconstructed clusters behave properly, and document the procedure in this ticket.

# Implementation Proposal
The idea is to learn how to move a control plane from one soil/seed cluster to another.

# Resources
Maybe [Heptio Ark](https://blog.heptio.com/announcing-two-new-heptio-open-source-projects-heptio-ark-and-heptio-sonobuoy-7cef88a06f8) (disaster recovery) may be interesting to check out?

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?

**Comment by vlerenc** [comment]
The idea is to learn how to move a control plane from one soil/seed to another.

**Comment by vlerenc** [comment]
Let's use Minikube (on an IaaS VM with IaaS LBs) to bootstrap a Gardener, create a ring of seeds (actually garden clusters) and finally transfer the first seed control plane into the last seed cluster, finally deploy an etcd cluster across the garden clusters, an API server as well, form a virtual distributed Kubernetes cluster and transfer the Gardener control plane  into that ring and shut down the Minikube cluster again. The result should be 3 seeds (actually garden clusters), one watching the other with a distributed Gardener using a distributed etcd on a distributed virtual Kubernetes cluster consisting only of API servers. The whole thing becomes the self-healing Gardener ring (to-be-tested).

**Comment by vlerenc** [comment]
As for moving control planes from one seed to another, please see https://github.com/amshuman-kr/gardener/blob/master/docs/proposals/shoot-control-plane-migration/README.md (in the context of https://github.com/gardener/etcd-backup-restore/issues/34).

**Comment by vlerenc** [comment]
Replaced by #232 and #233.
