### ISSUE TITLE
Allow ShootedSeed .spec.provider to be specified from "shoot.garden.sapcloud.io/use-as-seed" annotation

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1807]
Currently `shoot.garden.sapcloud.io/use-as-seed` allows specifying Seed taints, parts of seed spec.
But the `.spec.provider` section of the Seed is populated according to the Shoot spec.

https://github.com/gardener/gardener/blob/5f4ccba25c2b1912e3eecb0db0a05f5f3e039c6c/pkg/gardenlet/controller/shoot/seed_registration_control.go#L311-L315

It might be handy in some cases to be able to specify `.spec.provider.type` and `.spec.provider.region` to allow ShootedSeed on given provider to have scheduled Shoots from a different provider type.

**Comment by rfranzke** [comment]
Should we close this one for now? Or do you really want to implement this?
