### ISSUE TITLE
Gardener shoot cluster is unable to change its metadata.annotations while destroying

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardener#1816]
Hello,

i found this issue during my utilization of terraform-gardener-provider https://github.com/kyma-incubator/terraform-provider-gardener

In short, if i create an Gardener shoot cluster with some meta.annotations using terraform, i can't destroy this shoot cluster directly , i need to first modify the shoot cluster metadata.annotation as `"confirmation.garden.sapcloud.io/deletion" = true` and then perform destroy.

I submitted an issue in terraform-gardener-provider https://github.com/kyma-incubator/terraform-provider-gardener/issues/43 and suggest me to bring up issue here to triage whether this is an bug in gardener or in terraform-provider-gardener side.

Steps how to reproduce this issue:

1) adding an cluster with some customized annotation info in metadata, e.g.
```
metadata {
    name      = var.name
    namespace = var.gardener_namespace
    annotations = {
      "garden.sapcloud.io/purpose" = "development"
      "dashboard.garden.sapcloud.io/no-hibernation-schedule" = true
    }
  }
```

and then run `terraform apply` to create the shoot cluster

2) trying to delete the shoot directly using `terraform destroy`, error occurs indicating only an cluster with annotation "confirmation.garden.sapcloud.io/deletion" = true could be deleted.

3) i found an workround on this, before destroy the cluster i need to modify the cluster metadata.annotation first

```
annotations = {
    "garden.sapcloud.io/purpose" = "development"
    "dashboard.garden.sapcloud.io/no-hibernation-schedule" = true
    "confirmation.garden.sapcloud.io/deletion" = true
  }
```

and then i run `terraform apply` to modify the cluster, and then the cluster could be deleted via `terraform destroy`

From my understanding metadata.annotation in shoot is immutable, so this is work as design? or possible bug for gardener?

Thanks!

-Neo

**Comment by ialidzhikov** [comment]
Hi @neo-liang-sap,

Gardener requires the `confirmation.garden.sapcloud.io/deletion` to be set, to allow given Shoot to be deleted. 

For example when you try to delete a Shoot (without this confirmation annotation set in advance):
```
$ kubectl delete shoot -n garden-foo bar
Error from server (Forbidden): shoots.core.gardener.cloud "bar" is forbidden: must have a "confirmation.garden.sapcloud.io/deletion" annotation to delete
```

I think the error message
```
must have a "confirmation.garden.sapcloud.io/deletion" annotation to delete
```
is pretty descriptive.

The proper deletion should be:
```
$ kubectl annotate -n garden-foo shoot bar confirmation.garden.sapcloud.io/deletion=true
$ kubectl delete -n garden-foo shoot bar
```

See https://gardener.cloud/050-tutorials/content/howto/create-delete-shoot/

**Comment by neo-liang-sap** [comment]
Hi @ialidzhikov :
Thanks for the explanation, @rfranzke also explain this point to me via slack
-Neo
