### ISSUE TITLE
Use gardener-resource-manager to deploy logging/monitoring stack and seed bootstrapping components

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1825]
**What would you like to be added**:
We could use the gardener-resource-manager in the `garden` namespace of seeds to deploy the logging/monitoring stacks for shoots. Currently, we have several `Delete*` functions that are enlisting the resources of each chart which makes the whole monitoring and logging stack code hard to maintain and error-prone.

**Why is this needed**:
This will reduce a lot of code in our end, especially the `Delete*` functions for AlertManager, the whole logging or monitoring stack as the GRM would take over the job.

**Comment by rfranzke** [comment]
/remove lifecycle/rotten
@tim-ebert will also work on using the GRM for the seed bootstrapping.

**Comment by vpnachev** [comment]
cc @Kristian-ZH @vlvasilev

**Comment by rfranzke** [comment]
Let's
/close
this one in favor of #2754.
