### ISSUE TITLE
(*Botanist).WaitUntilKubeAPIServerServiceIsReady / Creation of K8s Shoots via Gardener on OpenStack

### ISSUE THREAD

**Issue by M-I-P-S** [gardener/gardener#185]
Hi colleagues,

since yesterday, creation of Kubernetes Shoot Clusters on OpenStack shows following message:

Create Processing:
Currently executing (*Botanist).WaitUntilKubeAPIServerServiceIsReady
Last Error
Failed to reconcile Shoot cluster state: Errors occurred during flow execution: '(*Botanist).WaitUntilKubeAPIServerServiceIsReady' returned '`.status.loadBalancer.ingress[]` has no elements yet, i.e. external load balancer has not been created (is your quota limit exceeded/reached?)'

@quota limit exceeded: According OpenStack, there're sufficient resources in the associated OpenStack tenant.
 
@Currently executing (*Botanist).WaitUntilKubeAPIServerServiceIsReady: It seems the LoadBalancer cannot be created.

Regards
Daniel

**Comment by rfranzke** [comment]
Handled internally, not related to Gardener itself.
