### ISSUE TITLE
Kibana clickjacking vulnerability

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener#1860]
**What happened**:
Kibana is vulnerable to clickjacking attacks. To prevent this Kibana must set an `X-Frame-Options` header so that it cannot be loaded from third party pages or from an iframe.

**Comment by nicklas-dohrn** [comment]
To set this header, you need to add ONE of the following lines to your kibana config file (config/kibana.yml):
server.customResponseHeaders: {"x-frame-options":"deny"}
server.customResponseHeaders: {"x-frame-options":"sameorigin"}

(the feature to set this header is at least available in Version 6.8 and up of Kibana:
[official documentation 6.8](https://www.elastic.co/guide/en/kibana/6.8/settings.html))

EDIT:
So the header is available from 5.6. in the documentation:
[official documentation 5.6](https://www.elastic.co/guide/en/kibana/5.6/settings.html)

**Comment by rfranzke** [comment]
ping @Kristian-ZH

**Comment by Kristian-ZH** [comment]
Thank you. Will check it

**Comment by Kristian-ZH** [comment]
Hmm we experienced some problems when we tried to upgrade the Kibana/ES versions in the past due to indices changes, but from what i can see in the documentation, this customResponseHeaders exists in Kibana 6.7 as well:

https://www.elastic.co/guide/en/kibana/6.7/settings.html

**Comment by mukhtorov** [comment]
Hi @nicklas-dohrn 
when I added `server.customResponseHeaders: {"x-frame-options":"sameorigin"}` it is giving server error 500.

Actually, I was rendering `iframe` so the url is dynamic. giving "refused to frame" error.

any suggestions pls..
