### ISSUE TITLE
Auto-restart controller managers in shoot maintenance time window

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1862]
**What would you like to be added**:
We could auto-restart (kill pods) of the controller-manager as self-repair mechanism for shoot clusters with problems. We often see that the {kube,cloud}-controller-managers are hanging and only a pod restart helps. The root cause there is unknown and probably some deadlock situation in the k/k codebase itself, though, the auto-restart could function as work around until the root cause is fixed upstream.

**Why is this needed**:
Reduce manual ops effort and improve auto-repair capabilities of shoots.

**Comment by ialidzhikov** [comment]
Each restart of kube-controller-manager/cloud-controller-manager will force the component to populates its caches once again and will contribute to the rate limits.

**Comment by rfranzke** [comment]
That's why we should only do it in the maintenance time window.
