### ISSUE TITLE
Kube-controller-manager replica count is 0 when cluster is un-hibernated

### ISSUE THREAD

**Issue by ggaurav10** [gardener/gardener#1866]
**What happened**:
When a hibernated cluster is woken up, the kube-controller-manager deployment's replica count remains 0. Because of this the nodes are not able to join.

**What you expected to happen**:
The kube-controller-manager replica count should be 1 for a running cluster

**How to reproduce it (as minimally and precisely as possible)**:
When dependency watchdog is not running, wake up a hibernated cluster.

**Anything else we need to know?**:
This is probably because of these lines:
https://github.com/gardener/gardener/blob/v0.35.2/pkg/operation/botanist/controlplane.go#L999-L1003
```golang
	replicaCount, err := common.CurrentReplicaCount(b.K8sSeedClient.Client(), b.Shoot.SeedNamespace, v1beta1constants.DeploymentNameKubeControllerManager)
	if err != nil {
		return err
	}
	defaultValues["replicas"] = replicaCount
```
There should be a `if b.Shoot.HibernationEnabled` check for this.

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
Can you elaborate under which circumstances this is happening? I have never seen this so far.

**Comment by ggaurav10** [comment]
The issue is seen in some clusters in live landscape
Link to the chats:
https://sap-cp.slack.com/archives/CBVQLMS6N/p1580128178032300?thread_ts=1580127951.030800&cid=CBVQLMS6N
https://sap-cp.slack.com/archives/CBVQLMS6N/p1580130852034100?thread_ts=1580127951.030800&cid=CBVQLMS6N

**Comment by ggaurav10** [comment]
Please refer: https://github.com/gardener/gardener/pull/1867#issuecomment-579096561
