### ISSUE TITLE
kube-apiserver and kube-controller-manager may run different Kubernetes minor versions

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1879]
**What happened**:
Currently we redeploy `kube-controller-manager` during the deletion flow using the `.spec.kubernetes.version`. We do not redeploy the `kube-apiserver` during the deletion flow. 
This is somehow an assumption that the Shoot was successfully reconciled with `.spec.kubernetes.version` before the deletion and (hence) that the `kube-apiserver` is using the same version.  The `kube-apiserver`may not be updated to `.spec.kubernetes.version` (gardenlet not running or reconciliation issues before this step).
When it comes to the deletion, `kube-apiserver` may run a different Kubernetes version (which is probably incompatible with the kube-controller-manager version).

**What you expected to happen**:
As we know the Kubernetes minor versions are not compatible. For example kube-controller-manager v1.17 cannot acquire leader election if the kube-apiserver version is < 1.17. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Create Shoot with `.spec.kubernetes.version` v1.16.6

2. During the creation, in the step that gardenlet waits for worker to be `Ready`, update `.spec.kubernetes.version` to be v1.17.2 and delete the Shoot.

3. Ensure that during the deletion `kube-apiserver` will run v1.16.6 and `kube-controller-manager` - v1.17.2. Ensure that `kube-controller-manager` will fail to acquire leader election with

```
E0203 23:18:19.206230       1 leaderelection.go:331] error retrieving resource lock kube-system/kube-controller-manager: leases.coordination.k8s.io "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
E0203 23:18:22.983164       1 leaderelection.go:331] error retrieving resource lock kube-system/kube-controller-manager: leases.coordination.k8s.io "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
E0203 23:18:25.874041       1 leaderelection.go:331] error retrieving resource lock kube-system/kube-controller-manager: leases.coordination.k8s.io "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
E0203 23:18:27.950057       1 leaderelection.go:331] error retrieving resource lock kube-system/kube-controller-manager: leases.coordination.k8s.io "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
```

The same would be reproducible if the gardenlet is not running and the user again first updates a minor version and then triggers a deletion.

And yes, I know that it's not so likely to happen in the happy scenario when everything is up.
I actually spent quite a lot of time to figure out why kube-controller-manager cannot acquire leader election. And the problem was the fact that the kube-apiserver and kube-controller-manager versions were different.
But still, users can still lock themselves in such cases...

- Gardener version: v1.0.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
Can probably be fixed by implementing #1240 (not only for hibernated shoots, but in general for all Shoots in deletion)
