### ISSUE TITLE
Impossible to delete a cluster with incorrect dns domain

### ISSUE THREAD

**Issue by kayrus** [gardener/gardener#1889]
**What happened**:

If cluster was created with incorrect dns domain, which doesn't have a secret to be used, then this cluster stuck. Adding dns secrets is not possible, because the field is immutable.

**What you expected to happen**:

I have to have an ability to delete this cluster or at least to update a spec and define secrets.

**How to reproduce it (as minimally and precisely as possible)**:

create a shoot cluster with:

```yaml
spec:
  dns:
    domain: foo.bar.
```

**Comment by timuthy** [comment]
This supposed to work but since we set the shoot `status` even for an unsuccessful operation (https://github.com/gardener/gardener/pull/1706) the check (https://github.com/gardener/gardener/pull/1378) has been failing.

**Comment by timuthy** [comment]
Closing this one in favor of #1926.
