### ISSUE TITLE
Investigate Node Problem Detector

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#19]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:44 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/33_

----

Please check out https://github.com/kubernetes/node-problem-detector. Is it worth anything? If so, how can it be integrated into the seed & shoot cluster approach and alerts be received. Please report results here.

:information_source: Migrated from Jira issue [KUBE-70](https://jtrack.removed/browse/KUBE-70)

**Comment by gardener-robot-ci-1** [comment]
**Comment by [vlerenc](https://github.com/vlerenc)**
_Tuesday Aug 08, 2017 at 11:34 GMT_

----

Andreas Herz started to look into the issue, but then joined the Vue.js story instead. Still, he may have some information in case other colleagues are picking up this issue later.

**Comment by gardener-robot-ci-1** [comment]
**Comment by [I331134](https://github.com/I331134)**
_Wednesday Aug 16, 2017 at 13:43 GMT_

----

I along with prashanth can check on this to see what community is already providing and planning around same.

**Comment by gardener-robot-ci-1** [comment]
**Comment by [I331134](https://github.com/I331134)**
_Tuesday Aug 29, 2017 at 11:35 GMT_

----

Working doc from community showing possible architectures and roadmap :  
https://docs.google.com/document/d/1cs1kqLziG-Ww145yN6vvlKguPbQQ0psrSBnEqpy0pzE/edit#

**Comment by gardener-robot-ci-1** [comment]
**Comment by [vlerenc](https://github.com/vlerenc)**
_Wednesday Aug 30, 2017 at 03:21 GMT_

----

Thank you for sharing. As discussed on the phone, since it's a push-based system, it will be interesting to see what they will do if the NPD is not calling back/home. I saw plans for a heartbeat for the daemons (though they didn't write what shall happen concretely in the case the daemon fails to call back/home), but none for the NPD itself and if the NPD fails to report anything for a while.

**Comment by gardener-robot-ci-1** [comment]
**Comment by [vlerenc](https://github.com/vlerenc)**
_Friday Nov 03, 2017 at 10:47 GMT_

----

The plan is to start integrating the NPD when we have capacity to also join the community in developing a/the remedy controller, maybe supported by the work we do currently around the Node(Set)Controller. At least, this would be a compelling and extremely useful contribution SAP could make to the overall quality of Kubernetes clusters around the world.

**Comment by vlerenc** [comment]
Moved to https://github.com/gardener/machine-controller-manager/issues/28.
