### ISSUE TITLE
Replace kube-lego with cert-manager

### ISSUE THREAD

**Issue by loewenstein** [gardener/gardener#190]
According to the [readme](https://github.com/jetstack/kube-lego/blob/master/README.md) kube-lego is in maintenance mode and suggests using [cert-manager](https://github.com/jetstack/cert-manager/) instead. Are there any plans to replace the kube-lego add-on with cert-manager?

**Comment by vlerenc** [comment]
Indeed, that's the plan (cert-manager). However, this makes little sense (for us) without an increased rate limit, which is currently in negotiations with Let's Encrypt.

**Comment by luisdavim** [comment]
> The main limit is Certificates per Registered Domain, (50 per week).
You have that many domains? you can combine up to 100 subdomains per cert and you can also use wild card certificates...
