### ISSUE TITLE
Control Plane as a Service

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#1907]
**What would you like to be added**:
Gardener is providing a fully manged K8S clusters as a service. It is taking care for everything:
* Infrastructure
* Nodes
* Control Plane with properly configure and enable cloud extensions(ccm, csi)
* Network plugins
* and others

In #1896 I was thinking loudly that the shoot API resource might need to support use-case where the Gardener provides and manages the control plane only and let the user have the full control over the infrastructure, nodes and cloud specific extensions. 

Based on whether the fields `shoot.spec.provider.[infrastructureConfig|workers]`  are provided or not, the Gardener will provide a fully managed cluster or just the control plane.

It should be possible to switch between both offerings K8SaaS and CPaaS for the same cluster.

For the CPaaS case the credentials for the IaaS API are not needed, so the Gardener has to manage it even if `shoot.spec.secretBindingName` is not provided.

**Why is this needed**:

In this way the end user has the full control and opinion how to setup its infrastructure, while the Gardener is taking care to operate, monitor and back-up its control plane.

**Comment by rfranzke** [comment]
> For the CPaaS case the credentials for the IaaS API are not needed

See my comment: https://github.com/gardener/gardener/issues/1896#issuecomment-583964646

> > Though, generally, please keep in mind that the control plane also contains provider-specific components like cloud-controller-manager or CSI controllers which are requiring a) the cloud provider credentials and b) proper configuration. I don't think it's reasonable to offer CPaaS without these essential components. If you want to offer CPaaS you have to find a way to let the user configure these components for his use-case (we don't control the infrastructure anymore, hence, user needs full control).

**Comment by vpnachev** [comment]
This is why I have used 
>  and let the user have the full control over the ... cloud specific extensions.

I have not much experience with CCM/CSI, but I believe they can be deployed outside the seed and talk with the k8s API via the "public" endpoint.

**Comment by amshuman-kr** [comment]
> I have not much experience with CCM/CSI, but I believe they can be deployed outside the seed and talk with the k8s API via the "public" endpoint.

But doesn't that kinda defeat the CPaaS idea?

**Comment by vpnachev** [comment]
> But doesn't that kinda defeat the CPaaS idea?

Why? The infrastructure can be anything and there is no extension that is aware about it, so it has to be handled by the shoot owner.
The Gardener will provide only general purpose components like etcd, kube apiserver, kube controller manager and kube scheduler, and maybe a few others.

**Comment by amshuman-kr** [comment]
> > But doesn't that kinda defeat the CPaaS idea?
> 
> Why? The infrastructure can be anything and there is no extension that is aware about it, so it has to be handled by the shoot owner.
> The Gardener will provide only general purpose components like etcd, kube apiserver, kube controller manager and kube scheduler, and maybe a few others.

That depends on what we mean by control-plane. Some infrastructure controllers (cloud-controller-manager, machine-controller-manager etc.) are as much _control-plane_ as the more general purpose components like etcd, kube-apiserver, etc.

A way to host such infra-specific control-plane components adjacent to the general purpose control-plane components would be nice (but, of course, hard). This is what I meant.

**Comment by vpnachev** [comment]
>... shoot API resource might need to support use-case where the Gardener provides and manages the control plane only and let the user have the full control over the infrastructure, nodes and cloud specific extensions.

I think it is clear that in this case Gardener and its extensions will not take care about VMs, VPC/subnets, cloud-controller-manager, csi and other cloud specific resources. So CPaaS is only the general purpose cloud agnostic components.

**Comment by rfranzke** [comment]
I don't think we will work anytime soon on it, nor it's unclear whether this is in the scope of g/g. Shall we close the issue for now? /cc @vlerenc @vasu1124 @gardener/gardener-maintainers

**Comment by vlerenc** [comment]
@rfranzke Are we reopening this one now again or create a new one, now that this subject matter is under discussion?

**Comment by rfranzke** [comment]
I would vote for opening a new issue - this one here was having a slightly different scope:

> here the Gardener provides and manages the control plane only and let the user have the full control over the infrastructure, nodes and cloud specific extensions.

What we actually worked on in the Hackathon end of 2021 was to only manage the Kubernetes control plane without the intention of letting the user manually connect/configure nodes or any cloud provider specifics.
