### ISSUE TITLE
Delete VPN service of shoot when the shoot is hibernated

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener#1921]
**What would you like to be added**:

**Why is this needed**:
To save cost, when a shoot is hibernated, the loadbalancer of VPN could be deleted.

**Comment by vlerenc** [comment]
I guess we can close this one with the VPN reversal @zanetworker ?

/cc @rfranzke

**Comment by rfranzke** [comment]
We will still support Kubernetes shoots < 1.18 while the VPN inversion will only work for >= 1.18.

**Comment by rfranzke** [comment]
I guess we will not invest into this one given that we have a proposal for a reversed VPN with #3771 and #3812 that will work independent of the Kubernetes version.
/close
