### ISSUE TITLE
Shoot with wrong ExternalDomain cannot be created nor deleted

### ISSUE THREAD

**Issue by EmoinLanyu** [gardener/gardener#1926]
**What happened**:
We have met this problem recently:
A user tried to create a Shoot with a customized domain name, however, he did not also provide the dns credential needed for his customized domain.
His default domain should be like `<shoot_name>.<project_name>.shoot.<gardener_domain>`, however, this is what he set `<shoot_name>.<some_customized_name>.<gardener_domain>`.

So the creation of this Shoot failed with following error as expected:
```
Could not initialize a new operation for Shoot deletion: unable to figure out which secret should be used for dns
```

And then the user tried to delete this Shoot. Gardener went on by skipping the above dns check and continued with creating the resources, and in the end, was blocked by the same check at the beginning of Shoot deletion steps. And thus the deletion failed.

The fact that although the dns domain of the Shoot is not correct, the infrastructure resources are created anyway, is causing a lot of trouble since the Shoot cannot be deleted now.

We have tried several ways to solve this problem and found that manual and force deletion of the Shoot will not work: we can of course manually clean up the resources created for the Shoot, and then try to delete the Shoot specification itself. But the shoots.core.gardener.cloud resource cannot be deleted because:
1. After recent changes in admission controller, finalizers of Shoot cannot be removed unless Shoot deletion flow succeeded.
2. Manually force delete corresponding registry in Etcd doesn't help, we can still get the resource using kubectl.

The only way we found to solve this problem is to change its dns domain to a correct one. However, this cannot be done easily via simply changing the field in the specification, because it is immutable.
**We have to manually force update the field directly in Etcd.**

**What you expected to happen**:
1. Perhaps the creation of such kind (with dns problem, for example) of Shoot should be refused? Because their fields in Shoot specification are immutable, users can't possibly change them if something goes wrong.
2. If the creation goes wrong when the creation has not yet begun. We should directly remove the Shoot api-resource instead of first create the infrastructure resources and delete them again.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot, customize the dns domain in Shoot.yaml. Use `<shoot_name>.<some_customized_name>.<gardener_domain>` instead of `<shoot_name>.<project_name>.shoot.<gardener_domain>`.
2. Delete the Shoot.

**Anything else we need to know?**:
I didn't try this on other landscapes or for other cloud providers, because removal of the problematic Shoot is brutal and may cause problem if not cautious enough. But this is a gardenlet problem, so it most likely will happen on every landscape and for every cloud provider.

**Environment**:
ac-canary.

- Gardener version: v1.0.2
- Kubernetes version (use `kubectl version`): client 1.16.3, server 1.15.7
- Cloud provider or hardware configuration: coreos on alicloud
- Others:

**Comment by EmoinLanyu** [comment]
Sorry, there is a mistake in the description, it should be:
Force delete of the Shoot will work, but we have to clean up a lot of things in etcd. Both `/registry/` and `/registry-gardener/` prefixes contain resources that need deleting.

**Comment by timuthy** [comment]
> If the creation goes wrong when the creation has not yet begun. We should directly remove the Shoot api-resource instead of first create the infrastructure resources and delete them again.

I don't think that removing a shoot automatically because of an error is something we should do. In general, I agree that it should be possible for the user to delete the shoot.

**Comment by timuthy** [comment]
Issue seem to happen again with Gardener `v1.72`.
