### ISSUE TITLE
Support custom roles for project members

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1943]
**What would you like to be added**:
Today, a member in a `Project` can have exactly one role (`.spec.members[*].role`). This is very limiting and only supports roles that are "hard-coded" in the GCM's project controller. Let's extend this model slightly to a list of roles (`.spec.members[*].roles`; deprecate `.spec.members[*].role`) and allow to add "custom" roles (not known by GCM's project controller, but corresponding role bindings in the project namespaces are automatically reconciled by it).

**Why is this needed**:
Support out-of-tree extensions that want to extend the project member role model.
/cc @timuthy @tim-ebert @vlerenc @grolu @wyb1

**Comment by donistz** [comment]
Please, explain why these roles have to be "custom". Is it expected these roles to be used to grant permissions in the Kubernetes clusters managed via the project?

**Comment by rfranzke** [comment]
Gardener as of today only supports admin and viewer roles. However, there might extension controllers that e.g. install CRDs into the Garden cluster. Project members should have the ability to CRUD these resources. With the „custom“ role concept it is very convenient for those extension to let the GCM project controllers reconciling the needed bindings. 
This is a very small adaption and only about management of the resources in the Garden cluster, not about any permissions for shoots.
