### ISSUE TITLE
Bare-metal worker support

### ISSUE THREAD

**Issue by ghost** [gardener/gardener#195]
Would it be possible to support workers with `machineType: bare-metal` so that the cluster's control plane runs in a cloud provider (e.g. OpenStack), but certain workers are bare-metal machines?

The installation and setup of such workers could be delegated to existing tools like the [Terraform Matchbox provider](https://github.com/coreos/terraform-provider-matchbox/), [xCAT](https://xcat.org/) or others.

**Comment by vasu1124** [comment]
Please have a look at https://github.com/gardener/machine-controller-manager .
And more in depth at the driver package https://github.com/gardener/machine-controller-manager/tree/master/pkg/driver . 
You could indeed delegate machine creation to other external tools. 
But beware that establishing the right environment (network & storage) which spans hybrid landscapes is not an easy feat. It is probably much easier to use the cloud provider (e.g. openstack ironic, aws ec2 bare metal) to reach the same result.
