### ISSUE TITLE
Kibana index went read-only

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1957]
**What happened**:
Kibana index went read-only and the hourly-curator was not removing the read-only setting from the kibana index.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Fill the elastic volume and ensure that it updates the indices (including the kibana one) to be read-only on given threshold.

2. Open Kibana and ensure it fails 
```
blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];: [cluster_block_exception] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];
```

Checking the logs of the hourly-curator:
```
2020-02-19 13:01:10,599 INFO      Trying Action ID: 1, "index_settings": Remove the selected indices from read only
2020-02-19 13:01:13,599 INFO      Applying index settings to 2 indices: ['logstash-2020.02.18', 'logstash-2020.02.19']
```

Its filter currently does not target the kibana index. 

I hat to manually set the read-only to false with:
```http
PUT .kibana_1/_settings
{
  "index": {
    "blocks.read_only_allow_delete": null
  }
}
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.0.4
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
@Kristian-ZH maybe you can help/have an idea here?

**Comment by Kristian-ZH** [comment]
Hmm, we have the following setting in the Configmap of our curator:

```
          index_settings:
            index:
              blocks:
                read_only_allow_delete: null
```

Maybe @vlvasilev can tell us more?

**Comment by vlvasilev** [comment]
The filter removes the read-only only from indices younger than 2 days.
If the kiban index is older than read-only will not be removed.

**Comment by rfranzke** [comment]
@vlvasilev so what do you suggest to prevent kibana index from becoming read-only?

**Comment by vlvasilev** [comment]
@rfranzke Prevention is impossible wen the storage is flooded. But we can remove it with another action in the curator configuration.

**Comment by rfranzke** [comment]
Understood, thanks. So, that means that we should enhance the curator configuration in order to fix this  issue, correct? Can you/Kristian take this?

**Comment by vlvasilev** [comment]
@rfranzke the fix is ready but not tested. I have lost connection to my gcp seed.

**Comment by rfranzke** [comment]
:-) Probably it got hibernated?
