### ISSUE TITLE
Default network settings of shoot has conflict with alicloud provider's network

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener#1963]
**What happened**:
I create a shoot in Hangzhou(China) region with default network settings. CoreDNS fails to resolve domains. The errors looks like:
```
[INFO] 100.96.0.16:44091 - 26558 "AAAA IN checkip.amazonaws.com. udp 39 false 512" NOERROR - 0 2.000202584s
[ERROR] plugin/errors: 2 checkip.amazonaws.com. AAAA: read udp 100.96.0.25:41374->100.100.2.136:53: i/o timeout
[INFO] 100.96.0.16:40188 - 48296 "A IN checkip.amazonaws.com. udp 39 false 512" NOERROR - 0 2.000206386s
[ERROR] plugin/errors: 2 checkip.amazonaws.com. A: read udp 100.96.0.25:38964->100.100.2.138:53: i/o timeout
[INFO] 100.96.0.16:35426 - 34308 "AAAA IN checkip.amazonaws.com. udp 39 false 512" NOERROR - 0 2.000206204s
[ERROR] plugin/errors: 2 checkip.amazonaws.com. AAAA: read udp 100.96.0.25:39065->100.100.2.136:53: i/o timeout
[INFO] 100.96.0.24:45256 - 33275 "A IN location-readonly.aliyuncs.com. udp 48 false 512" NOERROR - 0 2.000190848s
[ERROR] plugin/errors: 2 location-readonly.aliyuncs.com. A: read udp 100.96.0.25:51998->100.100.2.136:53: i/o timeout
[INFO] 100.96.0.16:34061 - 6643 "AAAA IN checkip.amazonaws.com. udp 39 false 512" NOERROR - 0 2.000198883s
[ERROR] plugin/errors: 2 checkip.amazonaws.com. AAAA: read udp 100.96.0.25:47800->100.100.2.136:53: i/o timeout
[INFO] 100.96.0.16:54042 - 32791 "A IN checkip.amazonaws.com. udp 39 false 512" NOERROR - 0 2.000208366s
[ERROR] plugin/errors: 2 checkip.amazonaws.com. A: read udp 100.96.0.25:53119->100.100.2.138:53: i/o timeout
[INFO] 100.96.0.24:53719 - 45697 "A IN alidns.aliyuncs.com. udp 37 false 512" NOERROR - 0 2.000193885s
[ERROR] plugin/errors: 2 alidns.aliyuncs.com. A: read udp 100.96.0.25:45382->100.100.2.136:53: i/o timeout
```
It seems no response from DNS server.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by mvladev** [comment]
Well in this case, the worker/service and pod cirds should be outside of the Carrier NAT network? (100.64.0.0/10)

**Comment by jia-jerry** [comment]
Some of my findings.
Alicloud seems to use CIDR  100.64.0.0/10. Refer to Carrier-grade NAT (RFC6598). Defautl networks of shoot has conflict with Alicloud provider. Some other proof is in PR: https://github.com/gardener/gardener-extension-provider-alicloud/pull/31

**Comment by jia-jerry** [comment]
> Well in this case, the worker/service and pod cirds should be outside of the Carrier NAT network? (100.64.0.0/10)

Yes. After I changed the networks of shoot in Hangzhou region, everything gets back.  Here is my settings
```
 pods: 172.16.0.0/16
 nodes: 10.250.0.0/16
 services: 172.17.0.0/16
```

**Comment by jia-jerry** [comment]
It should be fixed in the setup configuration
