### ISSUE TITLE
Add specific ServiceAccount for elasticsearch-logging

### ISSUE THREAD

**Issue by mkoynov** [gardener/gardener#1975]
**What would you like to be added**:
All elasticsearch-logging StatefulSets should use a specific non-default ServiceAccount. This ServiceAccount should also be created.

**Why is this needed**:
The aforementioned StatefulSet creates privileged Pods with a *default* account. The change will allow privileged containers to be created without the necessity to create a ClusterRoleBinding with a subject on all authenticated users. Instead, extension controllers should now be able to create RoleBindings/ClusterRoleBindings, binding the ServiceAccounts of privileged Pods to the **Privileged** PodSecurityPolicy's ClusterRole.

**Comment by rfranzke** [comment]
@vlvasilev any progress?

**Comment by vlvasilev** [comment]
@rfranzke sorry I forget. I will take action immediately
