### ISSUE TITLE
Investigate EFK Stack

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#20]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:44 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/34_

----

Please check out the EFK Stack (Elasticsearch + fluentd + Kibana; see various blogs, e.g. https://logz.io/blog/kubernetes-log-analysis). Is it what we should use? If so, how can it be integrated into the seed & shoot cluster approach. Please report results here.

:information_source: Migrated from Jira issue [KUBE-98](https://jtrack.removed/browse/KUBE-98)

**Comment by vlerenc** [comment]
Merged with https://github.com/gardener/gardener/issues/3.
