### ISSUE TITLE
unable to set values of spec. kubernetes.kubeControllerManager.nodeCIDRMaskSize while creating AWS shoot

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardener#2017]
**What happened**:

Hello, when trying to create shoot in AWS using [terraform-provider-gardener](https://github.com/kyma-incubator/terraform-provider-gardener) we found we were unable to set values of spec. kubernetes.kubeControllerManager.nodeCIDRMaskSize, this value keeps the default value of `24`

**What you expected to happen**:

this value could be set to sth like `16`
**How to reproduce it (as minimally and precisely as possible)**:
1) create an sample tf file using terraform-provider-gardener 
2) set nodeCIDRMaskSize like
```
spec {
  kubernetes {
    kube_controller_manager {
        node_cidr_mask_size = 16
      }
  }
}
```
3) using `terraform apply` to build the shoot - in gardener dashboard see the nodeCIDRMaskSize is 24

**Anything else we need to know?**:

This issue is originated from https://github.com/kyma-incubator/terraform-provider-gardener/issues/69

We've been working on using terraform-provider-gardener to build shoot for sometime, all are good as we can set every values according to shoot spec in https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml

The only thing we found it doesn't work is we were unable to set spec. kubernetes.kubeControllerManager.nodeCIDRMaskSize - whatever we set, it keeps default `24`

@rakesh-garimella / @dansible and me checked code of terraform-provider-gardener and it does handle and sending request to Gardener api just like any other fields but seems Gardener API server didn't handle the value of `nodeCIDRMaskSize`

Due to limitation of terraform i was unable to provide json sending to Gardener API server but i can paste our code snippet here as we are handling `nodeCIDRMaskSize` like any other fields

```
          kubernetes {
              allow_privileged_containers = false
              version                     = "1.16.4"

              kube_api_server {
                  enable_basic_authentication = false

                  oidc_config {
                      groups_claim   = "groups"
                      username_claim = "email"
                    }
                }

              kube_controller_manager {
                  node_cidr_mask_size = 16
                }

              kube_proxy {
                  mode = "IPTables"
                }
            }
```
In these snippets we were good at setting other fields e.g.  kube_proxy.mode / kubernetes.version but the only thing doesn't work is node_cidr_mask_size

Another wired thing i noticed in shoot spec is that in https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml#L130 - it doesn't provide samples for how to set nodeCIDRMaskSize but in `yaml` section of shoot we are seeing sample like 

![image](https://user-images.githubusercontent.com/42594392/76193011-10e1dd00-621e-11ea-8a98-76d2af8c6cef.png)

Is there any special treatment we need to consider while changing value of nodeCIDRSize in creating shoot?

Thanks!

**Environment**:

- Gardener version:
in Canary landscape
- Kubernetes version (use `kubectl version`):
v1.17.0
- Cloud provider or hardware configuration: AWS , not sure whether this issue happens only on AWS as i only tested on AWS
- Others:

**Comment by rfranzke** [comment]
@danielfoehrKn could you check?

**Comment by danielfoehrKn** [comment]
Yes, it seems like the NodeCIDRMaskSize flag in the example shoot is missing. Thanks for catching.

To your problem:

I tried to recreate your problem without luck. You suggest the Gardener ApiServer always sets the node CIDR mask size to 24 , so I tested that part. 
I was able to create a Shoot having Spec.kubernetes.kubeControllerManager.nodeCIDRMaskSize to 16.

![image](https://user-images.githubusercontent.com/33809186/76200505-0ad60700-61f2-11ea-951f-742798625af6.png)

I think the Gardener Terraform provider does not set the NodeCIDRMaskSize in the Shoot.
I am not too familiar with the terraform-provider-gardener - could you try to extract the actual Shoot JSON (using your tool of choice e.g Wireshark when deploying locally)?

**Comment by neo-liang-sap** [comment]
Hi @danielfoehrKn 
Thanks for looking into this issue.
Yes this issue doesn't exist while using `kubectl apply -f xxx.yaml` - i also success while building shoot in yaml way and able to edit NodeCidrMaskSize.
This issue only occurs while using terraform-provide-gardener way. As in issue description i worked with terraform-provider-gardener dev @rakesh-garimella as he confirmed this field is handled like other fields.

I tried to capture an wireshark file, as i'm testing against landscape i assume i should filter like `ip.addr== xxx` but i didn't find any clear text related to NodeCidrxxx.

Is it encrypted? or i used wrong filter?

I'm attaching wireshark capture result (in zip format) for review... [wireshark.zip](https://github.com/gardener/gardener/files/4306004/wireshark.zip)


Thanks.
-Neo

**Comment by danielfoehrKn** [comment]
I think it makes sense to open a bug issue in the kyma terraform-provider and investigate the issue. 
From Gardener side it seems to work. 

Lets shift the discussion over there.

**Comment by timuthy** [comment]
As @danielfoehrKn confirmed, the `nodeCIDRMaskSize` is configurable for KCM through the shoot API. Let's close this issue for now. Please re-open if you see any necessity.
