### ISSUE TITLE
SecurityContextDeny admission plugin prevents shoot reconciliation

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#2047]
**What happened**:
When a shoot enables the `SecurityContextDeny` admission plugin then the shoot reconciliation fails because certain pods cannot be created, for example `coredns`:

```
I0314 13:15:38.650500       1 event.go:258] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"coredns-59d994cd69", UID:"43b1e2ec-8581-4dec-9b88-2c649a138d08", APIVersion:"apps/v1", ResourceVersion:"300053", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "coredns-59d994cd69-rv9vd" is forbidden: pod.Spec.SecurityContext.RunAsUser is forbidden
E0314 13:15:38.650555       1 replica_set.go:450] Sync "kube-system/coredns-59d994cd69" failed with pods "coredns-59d994cd69-rv9vd" is forbidden: pod.Spec.SecurityContext.RunAsUser is forbidden
```

**What you expected to happen**:
Either the shoot reconciles or the API forbids to specify this admission plugin.

**How to reproduce it (as minimally and precisely as possible)**:
Set the `.spec.kubernetes.kubeAPIServer.admissionPlugins` to `[SecurityContextDeny]` in the `Shoot` spec.

- Gardener version: v1.1.5
- Kubernetes version (use `kubectl version`): 1.15.10
- Cloud provider or hardware configuration: GCP, probably all
- Others:

**Comment by mvladev** [comment]
This admission plugin doesn't work with `PodSecurityPolicy` admission plugin which is enabled by default. I'll disable it in the apiserver config
