### ISSUE TITLE
EveryNodeReady reported even though desired node replicas don't match actual ones

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#208]
When I wake up a cluster from hibernation (maybe also in other cases), I see a healthy control plane chip for the nodes, because the Gardener reports `EveryNodeReady`. Actually, wouldn't it make more sense to indicate, that the nodes are missing, i.e. the desired doesn't match the actual state (yet)?

**Comment by vlerenc** [comment]
The general question, I guess, is more about the reconciliation loop and that the status is only updated in reconciliation. However, when users invoke and operation (like wake-up) the shoot resource status and Dashboard don't change right away, which is surprising/confusing.

**Comment by rfranzke** [comment]
> When I wake up a cluster from hibernation (maybe also in other cases), I see a healthy control plane chip for the nodes, because the Gardener reports EveryNodeReady. Actually, wouldn't it make more sense to indicate, that the nodes are missing, i.e. the desired doesn't match the actual state (yet)?

The `EveryNodeReady` does only check whether every node that is known to the cluster is ready. It does not yet correlate the desired number of replicas of all machines to the number of registered nodes. Do you suggest to do that? 

> The general question, I guess, is more about the reconciliation loop and that the status is only updated in reconciliation. However, when users invoke and operation (like wake-up) the shoot resource status and Dashboard don't change right away, which is surprising/confusing.

The conditions checks are part of another controller that is not aware of anything the main Shoot controller does. Not sure whether I understand the question here. What is the suggestion?

**Comment by vlerenc** [comment]
About the first part: Yes, kind of thinking out loud whether that would make sense? From end-user perspective it would certainly do.

About the second part: It goes back to an observation made some weeks ago. I change something, but at first nothing happens. From end-user perspective, it's difficult to assess whether the change had an effect or not, because at first nothing happens.

**Comment by rfranzke** [comment]
> About the first part: Yes, kind of thinking out loud whether that would make sense? From end-user perspective it would certainly do.

Agreed, makes sense. The health check was there before we had `MachineDeployment` resources from which we actually could know how many nodes **should** have been registered. Another thing that becomes better with the machine controller.

> About the second part: It goes back to an observation made some weeks ago. I change something, but at first nothing happens. From end-user perspective, it's difficult to assess whether the change had an effect or not, because at first nothing happens.

With the above adaption at least the experience for the scenario you explained in the issue (waking up a hibernated Shoot) will improve (the `EveryNodeReady` condition would be `False` until all VMs have been recreated). However, I guess we can't do much about this "problem" in general. We have two controller loops (which is good), and even if the health check controller would correlate something from the main controller, e.g., only the fact that deploying a manifest worked doesn't mean that the underlying pods are already running. Most of the things are done with Kubernetes and some of them need time to get reflected (maybe the cluster needs to be auto-scaled first, and then the pods get created, as an example).
The way how Kubernetes solves it is to have precise information in an object's status conditions or by throwing events for errors the user needs to be informed about. If we have ideas for more health checks we could perform (that would be reflected in the `Shoot`s conditions and become visible to the user) to improve the user experience then we should definitely add them.

**Comment by rfranzke** [comment]
Can we close the issue now that 44e2e87 and 122945d have been pushed?

**Comment by vlerenc** [comment]
Thank you, sure.
