### ISSUE TITLE
"make dev-setup" returns "Unsupported Kubernetes Environment"

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2085]
**What happened**:
`make dev-setup` returns `Unsupported Kubernetes Environment`. With the latest minikube versions the minikube node name is no longer `minikube`.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ minikube version
minikube version: v1.8.2
commit: eb13446e786c9ef70cb0a9f85a633194e62396a1

$ k get node
NAME   STATUS   ROLES    AGE     VERSION
m01    Ready    master   2m49s   v1.18.0-rc.1

$ make dev-setup
Unsupported Kubernetes Environment:
make: *** [dev-setup] Error 1
```

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by vpnachev** [comment]
I tried to mitigate with the `--extra-config` flags `kubeadm.node-name=minikube` and 
`kubelet.hostname-override=minikube` but this did not help.
