### ISSUE TITLE
Resilience & Robustness Hardening Concept

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#21]
Check out chaos tools like (ask Juergen Schneider for input):
* https://kubernetes.io/docs/admin/kubelet and the chaos-chance option
* https://github.com/bloomberg/powerfulseal
* https://github.com/asobti/kube-monkey
* https://github.com/Netflix/chaosmonkey
* https://github.com/linki/chaoskube
* https://github.com/openebs/litmus

If so, how can we use #31 and one or more of the tools above for resilience & robustness hardening and integrate it into integration testing (for example enabled on staging to introduce random chance)? Please provide a concept paper for resilience & robustness hardening.

**Comment by vlerenc** [comment]
Moved to https://github.wdf.sap.corp/kubernetes/landscape-dev-garden/issues/9.
