### ISSUE TITLE
Enabling CRI on existing worker pool fails

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#2117]
**What happened**:

Adding gvisor CRI to an existing Shoot worker pool does not install gvisor. 

**What you expected to happen**:
Gvisor is successfully installed on the node
- Daemonset "containerd-gvisor" in the Shoot has been scheduled
- Worker nodes are properly annotated

**How to reproduce it (as minimally and precisely as possible)**:
1) Create a Shoot with containerd as container runtime.
2) After, add the gvisor CRI to the workers section like so:

```yaml
 cri:
   name: containerd
   containerRuntimes:
    - type: gvisor
```
3) Observe that the update is allowed by the API server
4) Wait until the Shoot has been reconciled successfully
5) Check that the Containerruntime resource has been successfully reconciled & the HealthCheck is ok for the deployed deamonSet
6) Check on the machine that runsc is not installed in /var/bin/containerruntimes

**Reason**

The problem is that the way the node labels are currently set, does not work when updating an existing worker pool to use gvisor.
[Currently only the kubelet adds the required label ](https://github.com/gardener/gardener/blob/51634b550b0819af24d2dd1a08d5a15288b48d46/charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet.flags#L25)'containerruntime.worker.gardener.cloud/gvisor=true'   to the node. However that is only being done during node creation.
Relying on the kubelet to add the node label is therefore not sufficient.

> 5) Check that the Containerruntime resource has been successfully reconciled & the HealthCheck is ok for the deployed deamonSet

- Gvisor extension deploys the DaemonSet and then considers the reconciliation as successful
- HealthCheck for the Deamonset is successful because: 

```yaml
NAMESPACE     NAME                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                                                                  AGE
kube-system   calico-node             1         1         1       1            1           beta.kubernetes.io/os=linux                                                                    3h39m
kube-system   containerd-gvisor       0         0         0       0            0           containerruntime.worker.gardener.cloud/gvisor=true,worker.gardener.cloud/cri-name=containerd   3h20m
```
The gvisor daemonset expect the label "containerruntime.worker.gardener.cloud/gvisor=true" which does not exist.
Though the daemonset has not been applied.

**Possible Solution** 

The worker extension resource is able to add labels to nodes in the particular worker group. 
This can be configured in the Shoot via: 
```yaml
labels:
   containerruntime.worker.gardener.cloud/gvisor: "true"
```
So as a current workaround you can just add the label manually via the Shoot.yaml.

As a proper bugfix though I would like to propose removing the kubelet created labels and relying solely on the labels defined in the worker.  The Gardener, if CRI is configured, can just implicitly create those labels in the Worker spec.

**Anything else we need to know?**:

I can take over this task.

**Environment**:

- Gardener version: Master
- Kubernetes version (use `kubectl version`): 1.17.1
- Cloud provider or hardware configuration: AWS - ubuntu
- Others:

**Comment by zanetworker** [comment]
The question is, should you enable CRI change in the first place? I am guessing there is much more on the node than just the binaries that needs cleaning up? Maybe first a delete then a create to ensure that all the left-overs are cleaned up?

**Comment by rfranzke** [comment]
> Currently only the kubelet adds the required label 'containerruntime.worker.gardener.cloud/gvisor=true' to the node. However that is only being done during node creation.

Why is this? Normally, the kubelet should restart with the new flags and then add the label. Can you check whether the user-data in the `kube-system/cloud-config-<worker-pool-name>` secret is correct (has the correct kubelet flag)?

**Comment by rfranzke** [comment]
@zanetworker For existing clusters/worker pools the `containerd` cannot be enabled - a new worker pool must be created for it. Enabling `gvisor` afterwards should not be a problem - it only adds the `DaemonSet` to the shoot (+binaries on the host) as well as a `RuntimeClass` object. Only pods using this runtime class will be handled by gvisor (cc @nimrodoron).

**Comment by danielfoehrKn** [comment]
> Why is this? Normally, the kubelet should restart with the new flags and then add the label


Actually thats a misconception. The kubelet only adds the labels when registering the node. See [here](https://kubernetes.io/docs/concepts/architecture/nodes/) and [here](https://github.com/kubernetes/kubernetes/issues/64899).


Another  problem is, that we need to deploy for each worker pool a ContainerRuntime CRD, unlike today where we deploy one per type (e.g gvisor). The major reason for this is, that we define the CRI on the workerPool level in the Gardener even with a ProviderConfig - so we cannot deploy only one gvisor ContainerRuntime for all pools. 
I ll open another issue for this  and describe it in more details. 

I am already working on a solution for both of these issues - took me more time than expected.

**Comment by zanetworker** [comment]
@rfranzke thanks :) 

I misunderstood the issue, I thought its meant for changing containerd  runtimes afterwards for workers.

**Comment by rfranzke** [comment]
> Actually thats a misconception. The kubelet only adds the labels when registering the node. See here and here.

Aha, ok, didn't know that. Interesting. What do you suggest?

> Another problem is, that we need to deploy for each worker pool a ContainerRuntime CRD, unlike today where we deploy one per type (e.g gvisor). The major reason for this is, that we define the CRI on the workerPool level in the Gardener even with a ProviderConfig - so we cannot deploy only one gvisor ContainerRuntime for all pools.

We are aware of it and it was a conscious decision to don't do it for now. @nimrodoron had concerns with deploying mutliple daemonsets.

**Comment by nimrodoron** [comment]
Hi, 
Regarding the second issue (One ContainerRuntime per type).
The RuntimeClass GVisor should be deployed once for the cluster, so there is no meaning for multiple CRD's. At the moment threre  is no meaning for ProviderConfig, but can be in the future, so we made a check that the provider config must be the same, but for the long term i believe it should be configured for the whole shoot spec and just provide for each worker if to enable it or not.

**Comment by danielfoehrKn** [comment]
> We are aware of it and it was a conscious decision to don't do it for now. @nimrodoron had concerns with deploying mutliple daemonsets.

Sorry I was unaware of that and it caused confusion on my side.  Nevertheless I do not understand why it was implemented this way. Let me point it out below.


> At the moment threre is no meaning for ProviderConfig, but can be in the future, so we made a check that the provider config must be the same, but for the long term i believe it should be configured for the whole shoot spec and just provide for each worker if to enable it or not.

As we can configure CRI on the worker level, I find it to be counter intuitive to only allow a provider config on the whole Shoot. I also think thats why it was not designed in the Shoot like this in the first place. 

While in gvisor there is not much configurability and having one RuntimeClass for all gvisor enabled nodes makes sense, we cannot be sure that is the case for all Container Runtimes to come.
[For instance already KataContainers seem to have a multitude of options](https://github.com/kata-containers/documentation/wiki/UserGuide#configuration). 

My point is that with the current design we prevent having a worker-pool specific configuration of the container runtime. Potentially the CRI configuration should have the flexibility to be different from worker pool to worker pool - I think that also a big advantage of having worker pools in the first place.  

Thanks to extensibility , for gvisor we can just deploy one RuntimeClass for the whole Shoot. Having multiple RuntimeClass CRDs does not prevent that. 
For other container runtimes the extension has the choice to do that or not, it is not limited by design.

> The RuntimeClass GVisor should be deployed once for the cluster, so there is no meaning for multiple CRD's

RuntimeClasses can also be worker pool specific, this is supported by the API since 1.16 - [see here for more info](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/runtime-class-scheduling.md). 
Also see the above point why having only one ContainerRuntime CRD limits the flexibility.


**Additionally** 
I do not really favour the  current approach of uninstalling the runsc and shim binaries from the host.
It is being done via preStop lifecycle hooks on the container of the DeamonSet. 
- [While DaemonSets do not get evicted by the kubelet easily](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/), you cannot prevent hat from happening: [see here](https://github.com/kubernetes/kubernetes/issues/63005)
- When runsc is being removed, all pods using the container runtime have to restart -> dangerous.
![image](https://user-images.githubusercontent.com/33809186/78115481-299b7800-7403-11ea-8fd2-ed2b3614e476.png)
- I do not think  having a pod that when it crashes / gets evicted / accidentially deleted by user (unawareness)  removes the container runtime and forcing all pods to restart is a good design.

What I would prefer is an "uninstall DeamonSet" that only restarts onFailure and is **only spawned whenever the CRI is being removed from the WorkerPool.**  This Daemon only targets the WorkerPool (we can add and remove CRI per Worker pool in the Shoot). In order to support that the DaemonSet needs a selector on the WorkerPool. 
In order to support that we cannot have only one ContainerRuntime CRD for all worker pools of the same type. **This is another reason for having a ContainerRuntime CRD for each pool.**

 Unfortunately Deamon sets that only restarts onFailure is a requested enhancement [and not yet implemented](https://github.com/kubernetes/kubernetes/issues/64623).  
To mitigate the risks described above I would at the moment opt for just removing the uninstall lifecycle hook. 

**To sum it up (sorry it got long)**
I think we need one ContainerRuntime per WorkerPool per runtime type 
- configurability per Worker Pool in the Shoot should not be ruled out per design due to configuration options of the CRI and RuntimeClass support. Might be not required for gvisor, but should not be impossible by design.
- let the extension decide on the container runtime deployment (one or many RuntimeClasses, ...). Provide the information how it is defined in the Shoot (on the worker pool level). 
- To support uninstall DaemonSet for a worker pool, the ContainerRuntime needs to know the worker pool it should remove the container runtime binaries from. Thus this information is needed in the ContainerRuntime CRD.

I also do not think that having only one ContainerRuntime config leads to a simpler implementation / maintenance. Rather I believe it limits us and we need to create workarounds later. 

Again sorry @nimrodoron to voice these concerns rather late. I was just testing the gvisor implementation and stumbled over it.

**Comment by danielfoehrKn** [comment]
> We are aware of it and it was a conscious decision to don't do it for now. @nimrodoron had concerns with deploying mutliple daemonsets.

@nimrodoron  what was you concern with multiple deamonSets?

**Comment by danielfoehrKn** [comment]
> Aha, ok, didn't know that. Interesting. What do you suggest?

Adding the gvisor label only during reconcile when deploying the worker. Then the provider-extension can take care of labeling the node (I already tested that).

**Comment by nimrodoron** [comment]
@danielfoehrKn 
I don't have concern with multiple deamonSets. Thanks for the information, sounds good.
Unfortunately for me, it is indeed too late. I got back to other projects and currently doesn't have capacity to proceed with this task.

**Comment by rfranzke** [comment]
I'm fully with you @danielfoehrKn, we discussed the same with @nimrodoron and decided that - due to his time constraints - we postpone it for later. But if you want to take up this task then please go ahead - very welcome.

**Comment by danielfoehrKn** [comment]
> I'm fully with you @danielfoehrKn, we discussed the same with @nimrodoron and decided that - due to his time constraints - we postpone it for later. But if you want to take up this task then please go ahead - very welcome.

Sure, will do. @nimrodoron no problem. Thanks a lot for the work already. 
How should we proceed[ with the gvisor PR](https://github.com/gardener/gardener-extension-runtime-gvisor/pull/2)? Shall we close it or should we merge it and then I create a PR based on that?

**Comment by rfranzke** [comment]
AFAIK @nimrodoron wanted to finish it end of this week or next week. Maybe you can work toegether, or, if @nimrodoron has no(t much) time anymore then hand it over to you?

**Comment by nimrodoron** [comment]
@danielfoehrKn, i think you can continue with GVisor and changes you suggested, thank you. I was just planned to finish a small task there, regarding image vector replacement in local development, but i am not sure i will have time soon and don't wan't you to wait.

**Comment by danielfoehrKn** [comment]
@nimrodoron alright, maybe just send me a PN on slack telling me what has to be done for the image vector.
