### ISSUE TITLE
Worker pool with swap enabled

### ISSUE THREAD

**Issue by vasu1124** [gardener/gardener#2120]
**What would you like to be added**:
Add the option to order worker nodes with swap **enabled**:
* start kubelet with `--fail-swap-on=false`
* bootstrap to configure variable amount of swap space on root disk
* enable swap
* taint node

**Why is this needed**:
The ABAP Server makes use of extended (shared) memory that typically is sized beyond available memory and can deal with swap effectively. The feature is required for cost efficiency.

We are aware of https://github.com/kubernetes/kubernetes/issues/53533. 
The interference with required system components/pods with high priority should be taken into consideration.

**Comment by vpnachev** [comment]
Could you elaborate these steps
> * bootstrap to configure variable amount of swap space on root disk
> * taint node

We are seeing users complaining that the local disk is out of space, so how we can take space of this disk for the swap partition? How much it should be? Maybe this should be exposed in the API.

I believe a label is the better option, not taint. Or maybe both, but with what effect should be the taint?

>  The ABAP Server makes use of extended (shared) memory that typically is sized beyond available memory and can deal with swap effectively. The feature is required for cost efficiency.

This does not looks to me very container friendly. How much such containers can be running on a single node?


PS. I am afraid that this feature might introduce a lot of trouble for both - Gardener users and operators, but it makes sense to be evaluated.

**Comment by vasu1124** [comment]
How much swap? The official recommendation is  2x RAM upto 320GB, depending on the physical RAM:
https://launchpad.support.sap.com/#/notes/1597355
I think in this case, we would add an additional dedicated disk for swap. 

> This does not looks to me very container friendly. How much such containers can be running on a single node?

Indeed, it is a special use case. You can run multiple ABAP servers/processes on a single node, their parallel usage is tested even with disk/swap pressure, so packaged in containers should work too. But it will cause friction with other workloads that expect guarantees.
That is why I suggest to taint the nodes to ensure that only swap-friendly workload (with a toleration) gets deployed on that worker pool. See https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/ .

**Comment by majst01** [comment]
Adding my comments here even if not involved in this special topic.
I just want to add my $0.02 from long term operations experience.
You will pay operational burden with infrastructure savings!
I am not sure how big your savings on the infrastructure side will be compared to the operational pain you will get. It is almost impossible to solve all heap fightings automatically, things will go bad, really bad, and bonus, you will get terrible disk performace as bonus.

Overcommitting memory is way more complex than cpu resources, see the efforts kernel developers spent on the OOM killer algorithms and facebook implemented a oomd for the sole purpose of this problem, even for machines without overcommitment.

**Comment by vlerenc** [comment]
@vasu1124 Is that a hard requirement? Otherwise I would prefer not to do it.

**Comment by vasu1124** [comment]
From my internal discussions, it will be a substantial requirement for production.
(We could substitute it with other forms of cheaper ram, like we did for HANA).

**Comment by vasu1124** [comment]
fyi https://chrisdown.name/2018/01/02/in-defence-of-swap.html

**Comment by vasu1124** [comment]
Wider swap support in Kubernetes is now being discussed as well: https://docs.google.com/document/d/1CZtRtC8W8FwW_VWQLKP9DW_2H-hcLBcH9KBbukie67M/edit#

**Comment by vasu1124** [comment]
https://github.com/kubernetes/enhancements/issues/2400

**Comment by vasu1124** [comment]
https://github.com/kubernetes/kubernetes/issues/53533

**Comment by BeckerMax** [comment]
Maybe we should reconsider adding this:
Kubernetes v1.22: alpha support for using swap memory, [ref](https://kubernetes.io/blog/2021/08/09/run-nodes-with-swap-alpha/). 

I am unsure how high we want to prioritise this though. @vasu1124 Are stakeholders currently requesting this? How high is their pain in configuring it themselves? Is their current option (like running a privileged pod and enabling swap themselves) good enough for them?

Any other opinions?
