### ISSUE TITLE
OperatingSystemConfigs are cleaned before the MachineDeployment being deleted

### ISSUE THREAD

**Issue by aylei** [gardener/gardener#2123]
**What happened**:
The background is we were doing some chaos tests for our platform applications, including random killing VMs via the cloud provider API. And the platform application would provision and tear down worker groups in the Shoot cluster frequently. 

Yesterday we saw that hundreds of worker machines that should have been released were still running. After some investigation, we noticed that the though those worker groups had been deleted in the shoot spec, **the MachineDeployments still exists**:

```
➜  kg machinedeployment
NAME                                       READY   DESIRED   UP-TO-DATE   AVAILABLE   AGE
shoot--chaos--8fd6130c-master-z1           1       1         1            1           3d5h
shoot--chaos--8fd6130c-master-z2           0       0         0            0           3d5h
shoot--chaos--8fd6130c-master-z3           0       0         0            0           3d5h
shoot--chaos--8fd6130c-app-2a-z1           0       2         2            0           24h
shoot--chaos--8fd6130c-app-2b-z1           0       2         2            0           24h
shoot--chaos--8fd6130c-app-2c-z1           0       2         2            0           24h
```

Meanwhile, the `extension-provider-aws` Pod complains that:

```
{"level":"error","ts":"2020-04-01T09:05:00.756Z","logger":"controller-runtime.controller","msg":"Reconciler error","controller":"worker_controller","request":"shoot--chaos--test/test","error":"Failed while waiting for all machine deployments to be ready: 'Machine shoot--chaos--test-victim-z1-6d969bf888-vvvxc failed: Machine shoot--chaos--test-victim-z1-6d969bf888-vvvxc is not healthy since 10m0s minutes. Changing status to failed. Node Conditions: [{Type:FrequentContainerdRestart Status:False LastHeartbeatTime:2020-04-01 08:50:48 +0000 UTC LastTransitionTime:2020-04-01 08:30:38 +0000 UTC Reason:NoFrequentContainerdRestart Message:containerd is functioning properly} {Type:KernelDeadlock Status:False LastHeartbeatTime:2020-04-01 08:50:48 +0000 UTC LastTransitionTime:2020-04-01 08:30:38 +0000 UTC Reason:KernelHasNoDeadlock Message:kernel has no deadlock} {Type:ReadonlyFilesystem Status:False LastHeartbeatTime:2020-04-01 08:50:48 +0000 UTC LastTransitionTime:2020-04-01
```

But the `OperatingSystemConfigs` and the actual `Secrets` that contains the userdata had already been cleaned (only the one of master worker group was left):

```
➜   kg operatingsystemconfig
NAME                                   TYPE     STATUS      PURPOSE     AGE
cloud-config-master-16ffc-downloader   ubuntu   Succeeded   provision   3d5h
cloud-config-master-16ffc-original     ubuntu   Succeeded   reconcile   3d5h
```

The shoot reconciliation continuously reported error on the Gardener UI, and the machine deployments were not get cleaned for hours since we noticed the problem. Finally we deleted the MachineDeployments and Shoot manually in order to release the machines.

**What you expected to happen**:
Machines and MachineDeployments were properly deleted after the worker groups are deleted in the shoot spec.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a shoot cluster with two work groups, `master` and `victim`, each with 1 worker.
2. Terminate the machine of `victim` via the cloud provider API (in my environment, AWS)
3. Wait the machine appeared in `.status.failedMachine` field of the MachineDeployment of the `victim` group
4. Delete the `victim` worker group in the shoot spec before the newly created machine download the userdata.
5. The newly created machine will stick in `Pending` forever because the userdata has been deleted.

**Anything else we need to know?**:
I suspected that the problem is caused by a race condition of `Gardenlet` and `WorkerController` in the extension Pod. According to the code, when reconciling Shoot, `Gardenlet` will delete the unused `OperatingSystemConfigs` first and then update the `Worker` object. Meanwhile, the `WorkerController` will wait for all MachineDeployments to become ready before cleanup the unused MachineDeployments. So, if a machine is down and a new machine is provisioned, there is a chance that the `OperatinSystemConfigs` are deleted before the newly created machine download the userdata.

**Environment**:

- Gardener version: `v1.0.4`
- Kubernetes version (use `kubectl version`): `v1.16.7`
- Cloud provider or hardware configuration: 
  - AWS
  - Ubuntu
  - Instance type `m5.xlarge`

**Comment by aylei** [comment]
I've noticed that the reconciling process of `Botanist` has been changed in master, but `ComputeOpreatingSystemConfigs` is still executed before `DeployWorkers`. So I suspect `master` suffers this issue too, though I have not had time to verify yet.

IMHO:
1. `Botanist` should only clean `OperatingSystemConfigs` that is not used by any workers, so at least the cleanup of `OperatingSystemConfigs` should be postponed after the workers are reconciled;
2. `WorkerController` should be able to clean unused MachineDeployments even if there are unready MachineDeployments. Assuming that all the MachineDeployments should be ready before proceeding to cleanup work is too optimistic.

I'd like to submit patches if these make sense. How do you think?

**Comment by rfranzke** [comment]
Hello @aylei, thanks for filing the issue. I haven't fully understood why the `OperatingSystemConfig` is relevant here.
Could it be more the case that you are describing the same like https://github.com/gardener/gardener-extensions/issues/623?

**Comment by aylei** [comment]
@rfranzke Thanks for your quick response!

IIUC, `OperatingSystemConfig` is the resources that generate the userdata for the worker nodes to download. I've sshed to the worker node and cannot download the usderdata from kube-apiserver.

For the issue you posted, I think they are not relevant because all the MachineDeployments I described are owned by the same `Worker` object.

**Comment by aylei** [comment]
After look at the pull request again, I ensure that  https://github.com/gardener/gardener-extensions/issues/623 does solve the problem, thanks @rfranzke !

**Comment by rfranzke** [comment]
> IIUC, OperatingSystemConfig is the resources that generate the userdata for the worker nodes to download. I've sshed to the worker node and cannot download the usderdata from kube-apiserver.

Yep, correct.

> For the issue you posted, I think they are not relevant because all the MachineDeployments I described are owned by the same Worker object.

Hm, but your steps for reproduction talk about two worker pools. The `Worker` object always contains the list of all pools. Out of this list the worker controller generates the desired `MachineDeployment`s.
Now, in your reproduction steps you make one of these machines in the `victim` group fail and then you remove the worker group from the pool spec. This means to the worker controller that it doesn't generate a desired `MachineDeployment` for `victim` anymore (because it doesn't know it anymore). However, in its reconciliation loop it was waiting for *all* machine deployments instead of only the desired ones. This will make it stuck forever.

**Comment by rfranzke** [comment]
OK, thanks a lot. Let's keep the issue open until you came back with results. By the way, we plan to release this soon (this week, hopefully).

**Comment by aylei** [comment]
Thanks, I will update to that version and keep you posted

**Comment by rfranzke** [comment]
I'm closing the issue as we believe it's fixed and as the issue was inactive for a while.
Kindly reopen if you still think the bug exists.
/close
