### ISSUE TITLE
Run all `make` commands in container.

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#2143]
All `make` commands require various dev resources to be available:

- `golang`
- `helm`
- various `gnu` utils  such as `tar`, `gzip`, `tr`, `base64`, `cut`, `find`, `grep`, `xargs`.
- `gingo`
- linters.

I think that the most reasonable way to get reproducible builds and things such as `make generate` is to run those commands in a pre-build container image.

**Comment by poelzi** [comment]
I highly suggest using nix and a proper shell/default.nix for the build process.
https://nixos.org/explore.html
[niv](https://github.com/nmattia/niv) allows you to have proper dependencies across different operating systems.

**Comment by voelzmo** [comment]
Closing in favor of #4519 to keep the conversation in a single place. Thanks for raising this issue, @mvladev!
