### ISSUE TITLE
[prometheus-operator/config-reloader] memory.limit_in_bytes: device or resource busy

### ISSUE THREAD

**Issue by dansible** [gardener/gardener#2163]
**What happened**:
When deploying prometheus onto a seed, we noticed that the `prometheus-config-reloader` container can fail with this error:

```
  Warning  Failed                  15m (x3 over 15m)  kubelet, ip-10-242-5-86.ap-southeast-2.compute.internal  Error: failed to start container "prometheus-config-reloader": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write 5242880 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/kubepods/burstable/poda0ef03a6-6461-4648-b0f3-ef75b1738582/prometheus-config-reloader/memory.limit_in_bytes: device or resource busy\\\"\"": unknown
```

This is a known issue with containers with low memory usage:
https://github.com/helm/charts/issues/11447
https://github.com/coreos/prometheus-operator/issues/2409
https://github.com/coreos/prometheus-operator/issues/2424

**Anything else we need to know?**:

The solution seems to be to increase the `memory limit` for the `prometheus-config-reloader` container to a value of at least`20mi`

**Environment**:

- Gardener version: `landscape-live-garden:0.64.0`
- Kubernetes version (use `kubectl version`): `kubectl: v1.18.0`, `kubernetes: v1.15.11`
- Cloud provider or hardware configuration: aws

**Comment by rfranzke** [comment]
Can you explain more? I don't really get the problem from the description. What has the prometheus-operator to do with seeds or shoots? If it is uses too less memory (limit) then why opening an issue here?

The `config-reloader` deployed in our Prometheus instances running in the seed actually has a memory limit of `20Mi`: https://github.com/gardener/gardener/blob/master/charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml#L223 and https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/templates/prometheus/statefulset.yaml#L89

**Comment by mvladev** [comment]
@rfranzke have a look  at https://github.com/gardener/gardener/pull/2164

**Comment by rfranzke** [comment]
Thanks @mvladev, got it. Does it make sense to update the issue description to be more accurate about the fact that the problem observed ALSO in the prometheus-operator affects our Prometheus instances as well?

**Comment by mvladev** [comment]
Updated
