### ISSUE TITLE
"gardenctl target shoot" throws segmentation error

### ISSUE THREAD

**Issue by praveendhac** [gardener/gardener#220]
Created new shoot cluster successfully. Saw segmentation error while setting target to Shoot cluster
`gardenctl target shoot pd-shoot1-azure`

**Crash Trace**
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x11ef756]

goroutine 1 [running]:
github.com/gardener/gardenctl/vendor/github.com/sirupsen/logrus.(*Logger).level(...)
	/Users/pdarshanam/go/src/github.com/gardener/gardenctl/vendor/github.com/sirupsen/logrus/logger.go:312
github.com/gardener/gardenctl/vendor/github.com/sirupsen/logrus.(*Logger).Debugf(0x0, 0x1cf383d, 0x64, 0xc42051bc30, 0x1, 0x1)
	/Users/pdarshanam/go/src/github.com/gardener/gardenctl/vendor/github.com/sirupsen/logrus/logger.go:116 +0x26
github.com/gardener/gardenctl/vendor/github.com/gardener/gardener/pkg/client/kubernetes.newKubernetesClient(0xc4200f0000, 0xc420106b40, 0x1da60c0, 0xc4200caaf0, 0x50, 0xc4200f0000, 0x0, 0x0)
	/Users/pdarshanam/go/src/github.com/gardener/gardenctl/vendor/github.com/gardener/gardener/pkg/client/kubernetes/client.go:139 +0x354
github.com/gardener/gardenctl/vendor/github.com/gardener/gardener/pkg/client/kubernetes.newClientSet(0xc4200f0000, 0x1da60c0, 0xc4200caaf0, 0x0, 0xc4200f0000, 0xc4200d4d20, 0xc4206a40c0)
	/Users/pdarshanam/go/src/github.com/gardener/gardenctl/vendor/github.com/gardener/gardener/pkg/client/kubernetes/client.go:88 +0x7f
github.com/gardener/gardenctl/vendor/github.com/gardener/gardener/pkg/client/kubernetes.NewClientFromFile(0xc4202b2f20, 0x1e, 0xc4200d4d20, 0x0, 0x0, 0x0)
	/Users/pdarshanam/go/src/github.com/gardener/gardenctl/vendor/github.com/gardener/gardener/pkg/client/kubernetes/client.go:45 +0x17d
github.com/gardener/gardenctl/cmd.getSeedForProject(0xc42040e120, 0xf, 0xc4206a40c0, 0x1012009)
	/Users/pdarshanam/go/src/github.com/gardener/gardenctl/cmd/target.go:626 +0xa7
github.com/gardener/gardenctl/cmd.getKubeConfigOfClusterType(0x1cad619, 0x4, 0x19, 0xc4202b21e0)
	/Users/pdarshanam/go/src/github.com/gardener/gardenctl/cmd/target.go:656 +0x105
github.com/gardener/gardenctl/cmd.clientToTarget(0x1cad619, 0x4, 0x1cae294, 0x7, 0x0)
	/Users/pdarshanam/go/src/github.com/gardener/gardenctl/cmd/miscellaneous.go:77 +0x56d
github.com/gardener/gardenctl/cmd.targetShoot(0xc420260b70, 0xf)
	/Users/pdarshanam/go/src/github.com/gardener/gardenctl/cmd/target.go:595 +0x1992
github.com/gardener/gardenctl/cmd.glob..func17(0x2451180, 0xc42019dee0, 0x2, 0x2)
	/Users/pdarshanam/go/src/github.com/gardener/gardenctl/cmd/target.go:121 +0x13ed
github.com/gardener/gardenctl/vendor/github.com/spf13/cobra.(*Command).execute(0x2451180, 0xc42019de20, 0x2, 0x2, 0x2451180, 0xc42019de20)
	/Users/pdarshanam/go/src/github.com/gardener/gardenctl/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/gardener/gardenctl/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x244f1a0, 0x0, 0x0, 0x100000000000028)
	/Users/pdarshanam/go/src/github.com/gardener/gardenctl/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/gardener/gardenctl/vendor/github.com/spf13/cobra.(*Command).Execute(0x244f1a0, 0x20, 0xc42003fdc0)
	/Users/pdarshanam/go/src/github.com/gardener/gardenctl/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/gardener/gardenctl/cmd.Execute()
	/Users/pdarshanam/go/src/github.com/gardener/gardenctl/cmd/root.go:64 +0x56b
main.main()
	/Users/pdarshanam/go/src/github.com/gardener/gardenctl/gardenctl.go:20 +0x20 `

**Project list**
`$ gardenctl ls projects
projects:
- project: garden-dev
  shoots:
  - pd-shoot1-azure`

The command sometimes throws secret not found error
`$ gardenctl target shoot pd-shoot1-azure
secrets "kubecfg" not found`

Could not reproduce the crash consistently.

**Comment by rfranzke** [comment]
Moved to gardener/gardenctl#31.
