### ISSUE TITLE
Allow alpha, beta, rc image tags for .spec.kubernetes.version

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2207]
**Why is this needed**:
For local development and testing you may want to create cluster with `.spec.kubernetes.version` such as `v1.19.0-alpha.1`, `v1.20.0-rc.1`, `v1.19.0-beta.3`, etc.

**What would you like to be added**:
At first glimpse there are multiple places to the adapted:
- validation on `gardener-apiserver` side prevents adding such version in the `CloudProfile`
- we currently have a hard-coded list of supported versions for kubernetes client
- imagevector pkg seems that does not handle fancy suffixes (for example returns that there is not appropriate image for tag `v1.19.0-alpha.1` when there is an image with `targetVersion: ">= 1.17"`)
- `semverCompare` statements in the charts
```
{{- if semverCompare ">= 1.12-0" .Capabilities.KubeVersion.GitVersion -}}
kubescheduler.config.k8s.io/v1alpha1
{{- else -}}
componentconfig/v1alpha1
{{- end -}}
```

returns `componentconfig/v1alpha1` for `v1.19.0-alpha.1`

**Comment by rfranzke** [comment]
@ialidzhikov do you think the current image vector overwrite mechanism aren't sufficient? When I was developing 1.19 and 1.20 I was using them to play with `rc` images and it worked pretty well.

**Comment by rfranzke** [comment]
@ialidzhikov I would suggest to close this issue given that the requirement can be implemented with the image vector overwrite. Apart from it, it doesn't seem to have much attention/need/value. Do you agree?
