### ISSUE TITLE
Create shoot failed

### ISSUE THREAD

**Issue by qiffang** [gardener/gardener#2211]
The error message is here
```
Backup Entry Reconciliation" encountered task errors: [task "Deploying backup entry extension resource" failed: retry failed with context deadline exceeded, last error: Error while waiting for BackupBucket object to become ready: retry failed with context deadline exceeded, last error: backup bucket encountered error during reconciliation: flow "Backup Bucket Reconciliation" encountered task errors: [task "Waiting until backup bucket is reconciled" failed: Error while waiting for backupBucket object to become ready: retry failed with context deadline exceeded, last error: gardener operation "reconcile" is not yet picked up by extension controller]]
```

the backup secret is existed in garden namespace

**Comment by rfranzke** [comment]
Can you check the `extensions.gardener.cloud/v1alpha1.BackupBucket` resource in the respective seed? What's the status? Can you share the logs of the respective provider extension in this seed?

**Comment by qiffang** [comment]
> Can you check the `extensions.gardener.cloud/v1alpha1.BackupBucket` resource in the respective seed? What's the status? Can you share the logs of the respective provider extension in this seed?

I have found the reason, thanks very much.
