### ISSUE TITLE
Make kubelet logs accessible.

### ISSUE THREAD

**Issue by hardikdr** [gardener/gardener#2226]
**What would you like to be added**:
We often see machines can't join the cluster for the timeout period. This can happen due to many reasons, including that of infrastructures. 
To debug such situations, we mostly have to ssh into the machines, find the kubelet or other systemd-unit logs. 
 
Opening this issue for the initial brainstorming around:
- Does it make sense to have the kubelet logs easily accessible?
- Would it be even feasible?
    - We don't deploy logging stack into the shoot. But I can imagine a simple web-server[may be temporary], where last X lines of logs of all the kubelets could be dumped via a dedicated systemd-unit. This could even be on-demand/debug-container, where logs are dumped only if certain web-server is reachable, else no-op.

- Any other ideas to achieve the same?

**Why is this needed**:
For better UX.

**Comment by timuthy** [comment]
/close
and continue with https://github.com/gardener/gardener/issues/3559.

**Comment by dguendisch** [comment]
Probably you meant: continuing with https://github.com/gardener/gardener/issues/3559
