### ISSUE TITLE
Admission controllers don't pick up recent secrets in k8s cluster

### ISSUE THREAD

**Issue by bergerx** [gardener/gardener#223]
We've been seeing that either `gardener-contoller-manager` nor `gardener-apiserver` picks up secrets which are recently created.

Versions in use:
* etcd: quay.io/coreos/etcd:v3.3.2 in garden namespace
* garden cluster: Azure AKS 1.9.6
* gardener versions we tried: 1.5.0, 1.6.1

We prepared a single yaml manifest with below items in given order:
- Secret: default-domain
- Secret: seed-azure
- Secret: core-azure
- CloudProfile: azure
- SecretBinding: core-azure
- Seed: azure

Then we ran `kubectl apply`, and both `SecretBinding` and `Seed` resources failed with below error. But even the consequent runs of same `kubectl apply` command kept failing for 2+ hours.

After we delete pods for both`gardener-contoller-manager` and `gardener-apiserver`, the next run of the exact same `kubectl apply` succeeded.

We are able to repeat this issue by 4 different people in different garden clusters, which tells us this is not a temporary issue with the environment. Seems like gardener component don't pick up secrets. Similar issue also happens when we update the secret, new values in the secret have not been picked up by `gardener-controller-manager`.

Note: I'm not sure if this is related but we can't use the Kubernetes cluster's etcd for Gardener so we deploy our own etcd into the garden namespace.

```
$ kubectl apply -f /tmp/rendered
namespace "dev" configured
secret "default-domain" unchanged
secret "seed-azure" unchanged
secret "core-azure" unchanged
cloudprofile.garden.sapcloud.io "azure" configured
Error from server (Forbidden): error when creating "/tmp/rendered": secretbindings.garden.sapcloud.io "core-azure" is forbidden: secret "core-azure" not found
Error from server (Forbidden): error when creating "/tmp/rendered": seeds.garden.sapcloud.io "azure" is forbidden: secret "seed-azure" not found
```

**Comment by rfranzke** [comment]
@bergerx the issue  should have been resolved. I could not reproduce it so far. Could you please try again with image tag `0.7.0-d0f1fda30b679c730680af3355bfa1424fe4f37e` and report your experiences? Please reopen this issue in case you are still facing problems.

> Similar issue also happens when we update the secret, new values in the secret have not been picked up by `gardener-controller-manager`.

Not sure what you mean here in detail. The controller manager reads the secret before every reconciliation (not from a cache, but from the live system). While a reconciliation is ongoing the secret is not refreshed  - maybe this was the situation you faced? If you still think there is a bug please open a different issue with a more detailed description of what you were trying to do. Thank you!
