### ISSUE TITLE
Revoke Kubeconfig/Change Admin Password

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#225]
Kubeconfig/password may have leaked. Therefore our users ask for a way to revoke it and get a new one.

**Comment by rfranzke** [comment]
Duplicate of #105

**Comment by vlerenc** [comment]
Thank you, I really need to get through this mess of a backlog and build my tools/setup. Sorry for bothering - I was milking a list of early user feedback from the enablement team.
