### ISSUE TITLE
☂️The Infrastructure is reconciled constantly when a Shoot is hibernated and terraform apply pod returns error

### ISSUE THREAD

**Issue by vlvasilev** [gardener/gardener#2253]
**What happened**:
After triggering hibernation the terraform pod is spawn, although it is not needed. If error occurs during execution of this pod this will continue each 30 seconds. During this infinite loop a logs will be created which will load the fluentd buffer with no end point messages, because elastic-search pod is scaled to 0. 
**What you expected to happen**:
No terraform should be triggered unless Infrastructure is marked for deletion.
**How to reproduce it (as minimally and precisely as possible)**:
Make your own shoot in Gardener WebUI with valid credentials. 
Hibernate the shoot.
Change the credentials in cloudprovider secret with fake ones.
Annotate the Infrastructure with `gardener.cloud/operation=reconcile`

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.3.1
- Kubernetes version (use `kubectl version`): 1.15.11
- Cloud provider or hardware configuration: azure
- Others:

**Comment by rfranzke** [comment]
The `deployInfrastructure` task is only triggered once during maintenance, so you suggest to not trigger it at all if shoot is hibernated? 
Can be done, however, for existing shoots/infrastructures of hibernated clusters there is no way to stop it (other than letting the `.status.lastOperation` being manually patched by an administrator).

**Comment by vlvasilev** [comment]
Can we just put this code snipped 

`if cluster.Shoot.Spec.Hibernation != nil && 
      cluster.Shoot.Spec.Hibernation.Enabled != nil && 
     *cluster.Shoot.Spec.Hibernation.Enabled {	
return reconcile.Result{}, nil	
}`
Into the reconciliation function of the Infrastructure controller?

**Comment by rfranzke** [comment]
This would a) require every infrastructure controller to change and b) leave the `Infrastructure` objects in a stale state.

**Comment by vlvasilev** [comment]
This issue does not require immediately reaction so after time every infrastructure controller will change eventually. 
To prevent Infrastructure objects being in a stale state we could change the LastOperationState to `Aborted` with desription "Abort Reconciliation because Shoot is hibernated" .

**Comment by vlerenc** [comment]
> The deployInfrastructure task is only triggered once during maintenance, so you suggest to not trigger it at all if shoot is hibernated?

Wasn't the problem in this case that the TF pod failed, again and again (unauthorised or something)? The pod was recreated every 30 seconds or so, always creating logs, always pushing into fluentd that could never ship its logs out and was at max capacity all the time. I think we have a timeout of 24h or so for an operation, but then again, in 24h the next maintenance is triggered.

It would be already a great help if we get that feature out for new clusters/woken up clusters and have a back-off for the TF pod in general. As it is right now, we burn through resources and ship endless logs that suffocate fluentd, which means we might miss other valuable logs along the way.

Uups, I see too late, the ticket was already closed. What about the TF back-off question above @rfranzke and @vpnachev?

**Comment by rfranzke** [comment]
Yes, that's another improvement in the `Infrastructure` controllers of the various extensions that are using Terraform. I'll look into it as part of the other planned improvements (e.g., today, we sometimes don't display the actual error messages because of non-optimal timeouts).

**Comment by vlerenc** [comment]
Excellent, thanks. Is there a ticket to refer from here, because this one is closed, but the subject "Infrastructure is reconciled constantly when a Shoot is hibernated and terraform apply pod returns error" makes sense.

**Comment by rfranzke** [comment]
No, I'll reopen this issue and refer to it from the various extension repos.
/reopen

**Comment by vlerenc** [comment]
Because we want our logs back, please:
/priority/critical

**Comment by rfranzke** [comment]
/remove status in-progress
/close
as all related PRs have been merged and will be part of the next extension releases
