### ISSUE TITLE
Gardenlet v1.3.* cannot bootstrap on Kubernetes v1.14.9

### ISSUE THREAD

**Issue by aylei** [gardener/gardener#2257]
**What happened**:
Install gardener v1.3.0 using garden-setup, gardenlet cannot bootstrap:

```
time="2020-04-29T12:29:57Z" level=info msg="[SEED RECONCILE] aws-us-west-2" seed=aws-us-west-2
time="2020-04-29T12:29:57Z" level=error msg="Seed bootstrapping failed: admission webhook \"crds.seed.admission.core.gardener.cloud\" denied the request: must have a \"confirmation.gardener.cloud/deletion\" annotation to delete" seed=aws-us-west-2
```

upgrade gardenlet to v.1.3.1 manually, error still exists.

**What you expected to happen**:
gardenlet v1.3.0 cannot bootstrap, neither v1.3.1

**How to reproduce it (as minimally and precisely as possible)**:
1. provision EKS v1.14.9
2. deploy gardener v1.3.0 or v1.3.1

**Anything else we need to know?**:
The log of admission controller:

```
gardener-seed-admission-controller-7c8569ddb6-nw9n5 gardener-seed-admission-controller time="2020-04-29T12:31:14Z" level=info msg="Deletion is not confirmed - preventing deletion" name=alicloudmachineclasses.machine.sapcloud.io namespace= operation=DELETECOLLECTION resource=apiextensions.k8s.io/v1beta1/CustomResourceDefinition
gardener-seed-admission-controller-7c8569ddb6-nw9n5 gardener-seed-admission-controller time="2020-04-29T12:31:14Z" level=error msg="must have a \"confirmation.gardener.cloud/deletion\" annotation to delete"
```

**Environment**:

- Gardener version:
`v1.3.0` and `v1.3.1`
- Kubernetes version (use `kubectl version`):
`v1.14.9-eks-f459c0`

**Comment by ialidzhikov** [comment]
MachineClass deletion should be handled by the provider extension?
Which version of provider-alicloud you are using? I guess you are using a version which is not adding the confirmation annotation.

**Comment by ialidzhikov** [comment]
Starting from [gardener/gardener-extension-provider-alicloud@v1.8.0](https://github.com/gardener/gardener-extension-provider-alicloud/releases/tag/v1.8.0), it should be able to "confirm" the deletion.

**Comment by aylei** [comment]
I don't have `provider-alicloud` installed:

```
➜  gardener kg ns
NAME                           STATUS   AGE
cert-manager                   Active   9d
default                        Active   9d
extension-provider-aws-jcckv   Active   9d
garden                         Active   9d
kube-node-lease                Active   9d
kube-public                    Active   9d
kube-system                    Active   9d
```

And I suspect the issue is caused by:
https://github.com/gardener/gardener/blob/c019bc088b5252b8a0ba1248bc4e0321e7f8b670/pkg/operation/common/utils.go#L283

The code deletes crds with label selector, but the admissin-controller does not respect the label-selector:

https://github.com/gardener/gardener/blob/c019bc088b5252b8a0ba1248bc4e0321e7f8b670/pkg/seedadmission/extension_crds.go#L84

```
```

**Comment by aylei** [comment]
I will try to fix this and test it locally

**Comment by aylei** [comment]
JOOC, is this issue ever caught in e2e or conformance test?

**Comment by rfranzke** [comment]
I'm rather confused why the gardenlet/seed controller tries to delete the AlicloudMachineClass as part of its bootstrapping process? 
It shouldn't have the `gardener.cloud/role=hvpa` label, or?

**Comment by rfranzke** [comment]
The gardener seed admission controller (GSAC) ignores unexpected CRDs, https://github.com/gardener/gardener/blob/master/pkg/seedadmission/extension_crds.go#L42-L59, so the `DELETE HVPA` CRD call should not matter.

**Comment by rfranzke** [comment]
> JOOC, is this issue ever caught in e2e or conformance test?

Never seen before. @Diaphteiros did you experience this?

**Comment by aylei** [comment]
> The gardener seed admission controller (GSAC) ignores unexpected CRDs, https://github.com/gardener/gardener/blob/master/pkg/seedadmission/extension_crds.go#L42-L59, so the `DELETE HVPA` CRD call should not matter.

IIUC, `DELETE CRDs with HVPA labels` matches the case:

```
case:  metav1.GroupVersionResource{Group: apiextensionsv1beta1.SchemeGroupVersion.Group, Version: apiextensionsv1beta1.SchemeGroupVersion.Version, Resource: "customresourcedefinitions"}
```

And because it a `DELETE COLLECTION` operation, all crds will be listed by:

```
err = c.List(ctx, o, client.InNamespace(request.Namespace)) 
```

I deployed a patched webhook with verbose logging just now and get this hypothesis verified:

```
I0429 14:32:29.635364       1 extension_crds.go:87] DELETECOLLECTION &AdmissionRequest{UID:412e8f16-8a26-11ea-bc15-023dd8eb3c30,Kind:apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition,Resource:{apiextensions.k8s.io v1beta1 customresourcedefinitions},SubResource:,Name:,Namespace:,Operation:DELETE,UserInfo:{system:serviceaccount:garden:gardenlet fbb19600-8305-11ea-bc15-023dd8eb3c30 [system:serviceaccounts system:serviceaccounts:garden system:authenticated] map[]},Object:{[] <nil>},OldObject:{[] <nil>},DryRun:*false,Options:{[] <nil>},RequestKind:<nil>,RequestResource:<nil>,RequestSubResource:,}
```

**Comment by aylei** [comment]
I'm testing whether get all hvpa crds and delete them one by one could solve the issue.

**Comment by aylei** [comment]
BTW, maybe the way webhook handles `DELETE COLLECTION` is flawed? It receives a `DELETE COLLECTION` request which may specify a label-selector but checks **all** the objects in that namespace for confirmation. 

Unfortunately, the `AdmissionRequest` does not have a label-selector in the request:

```
I0429 14:32:29.635479       1 extension_crds.go:88] DELETECOLLECTION options {Raw:[] Object:<nil>}
```

emmm, looks like a bug of kubernetes?

**Comment by rfranzke** [comment]
OK, nice digging, indeed, this makes sense. As far as I can tell there is no possibility for the webhook server to retrieve the sent label selector when doing `kubectl delete crd -l foo=bar`, or?

**Comment by aylei** [comment]
> As far as I can tell there is no possibility for the webhook server to retrieve the sent label selector when doing `kubectl delete crd -l foo=bar`, or?

Yes, I think so

**Comment by rfranzke** [comment]
Yes, indeed, this looks like a Kubernetes bug... :( Can you open an issue in k/k and reference it here?
As for the fix in g/g what you suggested makes sense for now (first fetch the HVPA CRDs by label and then delete them one by one...)

**Comment by aylei** [comment]
sure

**Comment by rfranzke** [comment]
Thanks @aylei for your help and contributions!

**Comment by aylei** [comment]
Okay, this has been fixed in kubernetes `v1.15` by https://github.com/kubernetes/kubernetes/pull/76346

Does gardener have a version requirement for seed cluster?

**Comment by rfranzke** [comment]
The minimum seed version is 1.11 at the moment. However, we are planning to revendor the k/k dependencies soon to kubernetes-1.18, at this point in time we would bump the minimum garden cluster version to 1.16. Probably in the same Go we could mark the minimum seed version to 1.15/1.16 as well then (cc @mvladev). For now, we still want to support < 1.15 seeds, so I guess the fix you described earlier would be a good improvement for the time being.

**Comment by aylei** [comment]
sounds good!

**Comment by timebertt** [comment]
@aylei 
I am currently working on https://github.com/gardener/gardener/issues/1633 and are in the process of migrating the seed bootstrap to using a ManagedResource. I have already deleted the `DeleteHvpa` function (which is causing the problem) in my branch, as it is not needed anymore (gardener-resource-manager cleans all objects, that have been removed from the ManagedResource).
So I think, if you are patient for a little longer, you can spare the effort on the fix :)

/assign @tim-ebert

**Comment by rfranzke** [comment]
I think it'd still be fair to release a hotfix of v1.3 to allow using it without HVPA feature gate enabled. Your improvement will only make it into a new minor release, @tim-ebert

**Comment by timebertt** [comment]
Sure, good point

**Comment by rfranzke** [comment]
@aylei any update?

**Comment by aylei** [comment]
Thanks for the ping, I upgraded my seed cluster to solve this issue formerly. And I'm afraid I don't have enough time to finalize and test the fix on v1.14.* these days because I'm working on the pre-release stage of our product.

**Comment by rfranzke** [comment]
Thanks for coming back!

**Comment by rrs-celonis** [comment]
Hi, the workaround doesnt work. I get no crd's matching the label `gardener.cloud/role=hvpa` but it still fails as GSAC tries to check all CRD's managed by gardener.
