### ISSUE TITLE
Document dependency-watchdog component

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2274]
Currently I cannot find any docs about dependency-watchdog. Currently it seems to be:
1. probing the kube-apiserver and scaling down the kube-controller-manager to 0 replicas when the kube-apiserver is reachable internally but unreachable externally
1. restarting control plane components in `CrashloopBackoff` once etcd is again available

**Comment by ialidzhikov** [comment]
/area/documentation

**Comment by vpnachev** [comment]
Should we move this issue to https://github.com/gardener/dependency-watchdog ?

PS. I am not authorized to do it.

**Comment by ialidzhikov** [comment]
> Should we move this issue to https://github.com/gardener/dependency-watchdog ?

Why? Afaik dependency-watchdog provides only the framework, the concrete probes are on g/g side.

**Comment by vpnachev** [comment]
Because I do not see any documentation there, too.
So we have to have something on both places.
