### ISSUE TITLE
OpenStack VLAN network type

### ISSUE THREAD

**Issue by dkusidlo** [gardener/gardener#229]
Currently the Gardener deploys OpenStack networks using the OpenStack default. This is in our case a VXLAN tunnel. For performance reasons we would like to be able to use VLAN as an alternative network type.

Probably something like this 
```
resource "openstack_networking_network_v2" "network" {
  name = "tf_test_network"
  segments = {physical_network = <physnet_name>, network_type = "vlan"}
}
```
in here https://github.com/gardener/gardener/blob/master/charts/seed-terraformer/charts/openstack-infra/templates/_main.tf#L28 

I already talked to @afritzler regarding the implementation.

**Comment by rfranzke** [comment]
@dkusidlo what happens with existing networks that get the
```terraform
segments = {physical_network = <physnet_name>, network_type = "vlan"}
```
change? Will they be recreated or can they be updated in place? If they get recreated, what will happen to the machines/volumes?

**Comment by bmaeck** [comment]
My understanding is that you can not easily change existing subnets. Which means you need to delete the old VXLAN based subnet and create a new VLAN based subnet. In this case all essources in the existing subnet needed to be deleted as well. 

@dkusidlo Please correct me if I am wrong.

**Comment by rfranzke** [comment]
Then we can't simply add this as it would break existing clusters. We would need to be careful and only do it for newly created Shoots.

**Comment by rfranzke** [comment]
@dkusidlo how do we continue here?

**Comment by dkusidlo** [comment]
@rfranzke Suse reported that a backport of this feature to our release (Newton) is not trivial due to changes in the database schema. 

I would close this issue and reopen it as soon as we either upgrade to a newer version or we get a backport.

**Comment by rfranzke** [comment]
OK, sounds reasonable. Thank you for the update!
