### ISSUE TITLE
Validate cloudprovider credentials

### ISSUE THREAD

**Issue by dansible** [gardener/gardener#2293]
**What would you like to be added**:
Add validation for `cloudprovider` secret

**Why is this needed**:
Currently, when uploading secrets via the UI, all secret fields are required and validated. However, when creating those credentials via the `cloudprovider` secret, there is no validation. This results in errors such as:

```
Flow "Shoot cluster reconciliation" encountered task errors: [task "Waiting until shoot infrastructure has been reconciled" failed: failed to create infrastructure: retry failed with context deadline exceeded, last error: extension encountered error during reconciliation: Error reconciling infrastructure: secret shoot--xxxx--xxxx/cloudprovider doesn't have a subscription ID] Operation will be retried.
```

**Comment by rfranzke** [comment]
g/g does not know anything about cloud provider credentials. 
Isn't it kind of similar to https://github.com/gardener/gardener-extension-provider-aws/issues/40, https://github.com/gardener/gardener-extension-provider-azure/issues/42, etc.?
Shall we close this issue in favor of those?

**Comment by dansible** [comment]
Ah yes, it would make more sense in the extension repo!

The two issues you referenced would be great for fixing a secret without all the fields in place but don't address validating a `cloudprovider` secret when it is created. The error in this issue was caused by a customer not including their Azure subscription ID into their secret (`secret shoot--xxxx--xxxx/cloudprovider doesn't have a subscription ID`)

Should I move this issue to the Azure extension repo? And also create similar issues for the other providers? Or update the tickets you referenced?

**Comment by rfranzke** [comment]
Whatever you prefer more, either updating/extending the scope of the existing issues or creating new issues. But yes, they should definitely be moved to the various provider extension repos, g/g cannot help, i.e., this issue here should be closed.

**Comment by dansible** [comment]
closing in favor of the issue in the azure extension: https://github.com/gardener/gardener-extension-provider-azure/issues/81

AWS: https://github.com/gardener/gardener-extension-provider-aws/issues/90
Openstack: https://github.com/gardener/gardener-extension-provider-openstack/issues/69
AliCloud: https://github.com/gardener/gardener-extension-provider-alicloud/issues/74

I did not create one for GCP as it only uses a single field for the json keyfile
