### ISSUE TITLE
ImagePullPolicy Admission Controller

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#23]
# Story
* As operator I want to control which container image I allow (black-/whitelist), so that I can ensure the safety of my Kubernetes cluster.

# Motivation
Security.

# Acceptance Criteria
- [ ] Admission controller that can be switched on or off:
  - [ ] Allow images from certain registries
  - [ ] Allow images with certain signatures

# Implementation Proposal
Implement an image policy webhook.

# Resources
- Design document: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/image-provenance.md
- Configuration: https://kubernetes.io/docs/admin/admission-controllers/#imagepolicywebhook
- OpenShift (as an example): https://docs.openshift.com/container-platform/3.3/admin_guide/image_policy.html

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by vasu1124** [comment]
How about using OPA?
http://www.openpolicyagent.org/docs/kubernetes-admission-control.html

**Comment by bergerx** [comment]
OPA seems cool, but how is it related to ImagePullPolicy admission controller? Even if we have OPA we still explicitly need ImagePullPolicy to be enabled on some clusters, ideally through the shoot definition.

Or, did you just put it as a related idea around having generic Admission Controller solution?

**Comment by rfranzke** [comment]
We won't work on this one in the foreseeable future, hence, closing it for now.
