### ISSUE TITLE
Configure cluster autoscaler safe-to-evict annotation only for etcd-main

### ISSUE THREAD

**Issue by swapnilgm** [gardener/gardener#2304]
**What would you like to be added**:
Gardener should only apply the `cluster-autoscaler.kubernetes.io/safe-to-evict=false` annotation from etcd-main crd. And not the etcd-events. 
**Why is this needed**:
Etcd-events is not that critical component. And kube-apiserver does not have blocker in case etcd-events rescheduling takes time in absence of such annotation. This will help saving costs because of underused nodes on which etcd-events pods will be scheduled.
 
With https://github.com/gardener/etcd-druid/issues/54, the etcd-druid will no longer add such annotation by default to etcd pod. And the annotation should be explicitly configured on etcd resources.

**Comment by rfranzke** [comment]
@swapnilgm @georgekuruvillak @amshuman-kr do you take care of this one?

**Comment by georgekuruvillak** [comment]
Ill take it up.

**Comment by swapnilgm** [comment]
Closed via #2317
