### ISSUE TITLE
Gardenlet `ControllerInstallationRequired` controller does not consider DNS Providers

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#2332]
**What happened**:

The Gardenlet does not reconcile the registered DNS Providers in the federated seed controller.

**What you expected to happen**:

Gardenlet should reconcile the DNS Provider to include it in the decision making whether a ControllerInstallation is required or not.

The DNSProvider CRD cannot be enqueued as an extension object.

**How to reproduce it (as minimally and precisely as possible)**:

[This commit ](https://github.com/gardener/gardener/commit/fc5c52001d98a5f1ffe8ab73e731a2cd868b5e89) cosmetically fixed the occuring panic in the Gardenlet.
The panic happens because the [DNSProvider is being registered as an extension object](https://github.com/gardener/gardener/blob/1bb22255b2142b59b7e94f2f67e320666fd7be2e/pkg/gardenlet/controller/federatedseed/extensions/artifact.go#L65-L64) - though it is none. 

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**How to categorize this issue?**

/area disaster-recovery
/area control-plane-migration
/kind bug
/priority normal

**Comment by rfranzke** [comment]
Why do you think the gardenlet does not reconcile the `DNSProvider` objects? The only effect of the commit you referenced is that the predicate function is not evaluated for `DNSProvider` objects as it doesn't apply (because it is now extension object), right? Am I missing something?

**Comment by rfranzke** [comment]
FYI: I still think it's not a bug, though, I've opened #2379 to make the code better in a way that object-tailored predicate functions can be provided now during the object registration.
