### ISSUE TITLE
CIDR validation in Gardener Scheduler should be propagated to the user

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener#2353]
**How to categorize this issue?**
/area usability
/kind enhancement
/priority normal

**What would you like to be added**:
One of my clusters got stuck in the "Pending Creation" state. After looking into the issue it turned out, that there was a CIDR collision between the provided node cidr range the default pod cidr. The validation error of the scheduler is not propagated to the user.

**Why is this needed**:
As a user I am not able to see what the problem for the "pending" cluster creation is. Would be grate to see the validation error from the scheduler.

**Comment by rfranzke** [comment]
Hm, there should have been an event, similar to what happens in Kubernetes with pods. Did you check `kubectl describe shoot`? Was the message in this event helpful?

**Comment by afritzler** [comment]
I tried that. Unfortunately I got an empty status

```
Status:
  Gardener:
    Id:
    Name:
    Version:
  Hibernated:    false
  Technical ID:
  UID:
Events:          <none>
```

And no events.

**Comment by timebertt** [comment]
Meanwhile the events are gone. But there were some before, when I checked :)
```
Events:
  Type     Reason            Age                  From                Message
  ----     ------            ----                 ----                -------
  Warning  SchedulingFailed  17m (x10 over 145m)  gardener-scheduler  Failed to schedule shoot 'ec7nn5ukdr' : admission webhook "validation.aws.provider.extensions.gardener.cloud" denied the request: [networks.zones[0].internal: Invalid value: "100.127.162.64/26": must not be a subset of "" ("100.96.0.0/11"), networks.zones[0].public: Invalid value: "100.127.162.0/26": must not be a subset of "" ("100.96.0.0/11"), networks.zones[0].workers: Invalid value: "100.127.161.0/25": must not be a subset of "" ("100.96.0.0/11"), networks.zones[1].internal: Invalid value: "100.127.162.192/26": must not be a subset of "" ("100.96.0.0/11"), networks.zones[1].public: Invalid value: "100.127.162.128/26": must not be a subset of "" ("100.96.0.0/11"), networks.zones[1].workers: Invalid value: "100.127.161.128/25": must not be a subset of "" ("100.96.0.0/11")]
```

**Comment by rfranzke** [comment]
Yes, the `status` is expected to be empty because there is no responsible controller (gardenlet) for the shoot as it wasn't scheduled yet. As the events exist, is there anything to improve from g/g's pov?

**Comment by afritzler** [comment]
Wouldn't it make sense to display this error on the dashboard instead of a spinning wheel with "pending creation"?

**Comment by rfranzke** [comment]
Probably yes, but if it's a dashboard issue only I'd suggest to close this one and reopen a new one at the gardener/dashboard repo.

**Comment by afritzler** [comment]
Thanks guys for the help!
