### ISSUE TITLE
Fake alert CloudControllerManagerDown due to the absence of service

### ISSUE THREAD

**Issue by aylei** [gardener/gardener#2355]
**How to categorize this issue?**

/area monitoring
/kind bug
/priority normal

**What happened**:

Deploy a shoot in gardener and the alert `CloudControllerManagerDown` is fired unexpectedly.

**What you expected to happen**:

No alerts when all components is healthy.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a shoot in gardener v1.4.1

**Anything else we need to know?**:

I've investigated the prometheus configuration, seems like that the prometheus discover cloud-controller-manager via the service, however, the service is not actually get created. 

```
kg svc -n shoot--drill--88015f87
NAME                         TYPE           CLUSTER-IP       EXTERNAL-IP                                                                   PORT(S)                      AGE
elasticsearch-logging        ClusterIP      172.20.28.144    <none>                                                                        9200/TCP,9114/TCP,9300/TCP   29h
etcd-events-client           ClusterIP      172.20.87.250    <none>                                                                        2379/TCP,2380/TCP,8080/TCP   29h
etcd-main-client             ClusterIP      172.20.114.55    <none>                                                                        2379/TCP,2380/TCP,8080/TCP   29h
grafana-operators            ClusterIP      172.20.179.118   <none>                                                                        3000/TCP                     29h
grafana-users                ClusterIP      172.20.32.184    <none>                                                                        3000/TCP                     29h
kibana-logging               ClusterIP      172.20.199.112   <none>                                                                        5601/TCP                     29h
kube-apiserver               LoadBalancer   172.20.151.138   xxx   443:31849/TCP                29h
kube-controller-manager      ClusterIP      None             <none>                                                                        10257/TCP                    29h
kube-scheduler               ClusterIP      None             <none>                                                                        10259/TCP                    29h
kube-state-metrics           ClusterIP      172.20.79.174    <none>                                                                        80/TCP                       29h
kube-state-metrics-seed      ClusterIP      172.20.211.190   <none>                                                                        80/TCP                       29h
machine-controller-manager   ClusterIP      None             <none>                                                                        10258/TCP                    29h
prometheus-web               ClusterIP      172.20.113.100   <none>                                                                        80/TCP                       29h
```

**Environment**:

- Gardener version: v1.4.1
- Kubernetes version (use `kubectl version`): v1.16.9 (shoot)
- Cloud provider or hardware configuration: AWS
- Others:

**Comment by rfranzke** [comment]
Thanks @aylei. It seems that [this configuration](https://github.com/gardener/gardener-extension-provider-aws/blob/master/charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/configmap-monitoring.yaml) (and those for other providers) is broken.

**Comment by gardener-botmanager** [comment]
@rfranzke Command "/platform aws azure gcp alicloud openstack packet" either unknown, wrongly parameterized or not permitted for issue/PR.

**Comment by timuthy** [comment]
have you double checked if we need any netpol to allow prometheus to connect to the CCM @rfranzke?

**Comment by rfranzke** [comment]
Thanks, nice question. The CCM already has the label to be able to get scraped by Prometheus: https://github.com/gardener/gardener-extension-provider-aws/blob/master/charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml#L30, https://github.com/gardener/gardener-extension-provider-packet/blob/master/charts/internal/seed-controlplane/charts/packet-cloud-controller-manager/templates/cloud-controller-manager.yaml#L24.
It also worked in my local tests.

**Comment by timuthy** [comment]
I was just wondering if we also need a `allow-to-ccm` netpol for the Prometheus pod. Thanks for taking care 👍

**Comment by rfranzke** [comment]
/close
as the related PRs were merged
