### ISSUE TITLE
New Bot Features Demonstration

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#2356]
/help
/ping @rfranzke @ialidzhikov

**Comment by ghost** [comment]
@vlerenc :information_source: Hi there, I am the Gardener bot :robot: and these are the commands I support:

Command                           | Authorised            | Description
--------------------------------- | --------------------- | -----------
`/add`&nbsp;label                 | Maintainer, Author    | Add label to issue or PR (default if no command is recognized); authors may only add certain white-listed labels (fully qualified) as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.
`/remove`&nbsp;label              | Maintainer            | Remove label from issue or PR
`/set`&nbsp;`milestone`&nbsp;ms   | Maintainer            | Set milestone at issue
`/unset`&nbsp;`milestone`&nbsp;ms | Maintainer            | Unset milestone at issue
`/assign`&nbsp;[@user...]         | Maintainer, Commenter | Assign given people (or yourself if none specified) to issue or PR; commenters may only assign themselves (no args/users permitted)
`/unassign`&nbsp;[@user...]       | Maintainer, Commenter | Unassign given people (or yourself if none specified) from issue or PR; commenters may only unassign themselves (no args/users permitted)
`/cc`&nbsp;[@user...]             | Maintainer, Author    | Request PR review from given people (or yourself if none specified) for PR
`/uncc`&nbsp;[@user...]           | Maintainer, Author    | No longer request PR review from given people (or yourself if none specified) for PR
`/hold`                           | Maintainer            | Add `reviewed/do-not-merge` label (and remove conflicting labels such as `reviewed/lgtm`  based on the `notPermittedWith` field in the [labels](#labels))
`/unhold`                         | Maintainer            | Removes `reviewed/do-not-merge` label
`/close`                          | Maintainer, Author    | Close issue or PR
`/reopen`                         | Maintainer, Author    | Reopen issue or PR

**Comment by ghost** [comment]
@rfranzke, @ialidzhikov 
<img src="https://source.unsplash.com/collection/981639/640x640">
<details>
<summary>Message</summary>

> /help
> /ping @rfranzke @ialidzhikov 
</details>

**Comment by ghost** [comment]
@vlerenc 
<img src="https://source.unsplash.com/collection/1120118/640x583">
<details>
<summary>Message</summary>

> /bark
</details>

**Comment by vlerenc** [comment]
Sorry, that was a nonsense issue. 😉

**Comment by ghost** [comment]
@vlerenc 
<img src="https://source.unsplash.com/collection/981639/640x525">
<details>
<summary>Message</summary>

> /ping @vlerenc 
</details>

**Comment by ghost** [comment]
@rfranzke 
<img src="https://source.unsplash.com/collection/1120118/640x583">
<details>
<summary>Message</summary>

> /bark
</details>
