### ISSUE TITLE
Gardener Cluster Audit Logs

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#236]
# Story
- As operator and user I want to see an event log showing who/what did what to my cluster, so that I can retrospectively analyse issues.

# Motivation
It is useful to understand what a human user or automated process did to a cluster to explain (and next time prevent) issues.

# Open Question
Should we really implement a solution only for clusters or rather think broader and have an audit log per project that shows all activity, clusters, secrets, members and whatnot?

# Acceptance Criteria
- [ ] Event log at shoot cluster resource level (in it or parallel to it) containing:
  - [ ] Who created or updated/patched (or deleted) a cluster and the modifications in the case of an update/patch
  - [ ] Machine controller manager added or removed or replaced a machine and why (e.g. detected DIskPressure, instructed by cluster autoscaler)

# Considerations
When considering cluster audit logs, one actually expects audit logs on project level, to also see what happened in member management or with the secrets. Should we defer the cluster audit logs to the general Garden cluster audit log, but how could/would we extract/represent that (semantically interesting) information in a helpful way (acceptance criteria above)? Also, it would only cover shoot resources, but not what happened "in" the cluster itself.

At present we don't really know what the Terraformer or the addon-manager do during reconciliation (actually, for Terraform, we can via the Terraform plan, but since this would require even more text scraping, it seems ill-advised to implement that until we replace Terraform).

Also, we are thinking about out-of-tree extensions, so whatever we design here, may eventually need to hold non-core events later.

# Release Notes
``` user release notes
- You can now see who modified a cluster and what was modified as well as see what the machine controller did to the worker pools and why.
```

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit tests are provided: Have you written automated unit tests?
- [ ] Integration tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added/changed public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the operations guide about ops-relevant changes?
- [ ] User documentation: Have you updated the READMEs/documentation about user-relevant changes?

**Comment by bergerx** [comment]
Do #331 and #495 address this issue?

**Comment by bergerx** [comment]
Oh this one is about "Garden" cluster not about shoots.

**Comment by rfranzke** [comment]
Yes, I'm not sure whether this should be kept open here. It is possible to define a custom audit policy for the Gardener API server already. I guess it's up to the Gardener provider to define a proper one that fits the individual needs.

**Comment by vlerenc** [comment]
@rfranzke ...but for instance MCM isn't transporting that information anywhere and that was the original reason for this ticket, i.e. that the cluster "changed" in the sense that e.g. a node was added/remove/replaced and the user wanted to know why. Not everything is reflected in the shoot resource.

I don't think we have reached the transparency required just yet. See also #2390.
