### ISSUE TITLE
cannot change seed name, because seed backup is not configured

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2366]
**How to categorize this issue?**

/kind bug
/priority critical

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

1. Try to create a new Shoot.

2. Ensure that the apply fails with

```
$ k apply -f shoot.yaml
Error from server (Forbidden): error when creating "shoot.yaml": shoots.core.gardener.cloud "foo" is forbidden: cannot change seed name, because seed backup is not configured, for shoot "foo"
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ghost** [comment]
@ialidzhikov Command "/cc swilen-iwanow " either unknown, wrongly parameterized or not permitted for issue/PR.
