### ISSUE TITLE
Hetzner cloud support

### ISSUE THREAD

**Issue by toonsevrin** [gardener/gardener#2371]
/kind enhancement
/priority normal

This issue serves as a tracker for everyone who would want Hetzner Cloud integration. I can potentially help with this if there is enough demand. 

Hetzner cloud is a cost-leader in cloud hosting.

Hetzner cloud has:
- [terraform definitions](https://www.terraform.io/docs/providers/hcloud/index.html)
- [csi driver](https://github.com/hetznercloud/csi-driver)
- [private networking](https://community.hetzner.com/tutorials/hcloud-networks-basic)

Hetzner cloud does not have:
- Loadbalancers: All though they do provide floating ips so this can be implemented with metaldb (or by using the workers as ingress nodes).
- Openstack

**Comment by vasu1124** [comment]
@toonsevrin would you like to discuss in [Slack #Gardener](https://kubernetes.slack.com/archives/CB57N0BFG)? 
Maybe you can form a community around Gardener on Hetzner. Also, you can get help with how to write the extentions ...

**Comment by toonsevrin** [comment]
I'm in the slack now :)

**Comment by majst01** [comment]
The "only" components you have to implement/adapt is the extension-provider-hetzner and machine-controller-manager. You can have a look at: 
https://github.com/metal-stack/gardener-extension-provider-metal for reference

**Comment by toonsevrin** [comment]
Makes me wonder: what are the trade-offs of implementing at the metal-stack level vs the gardener level?

**Comment by majst01** [comment]
to clarify: metal-stack is a cloud api for bare metal provisioning, same level from the gardener perspective like gcp or ec2 or openstack.

**Comment by vlerenc** [comment]
Any decision here? In any case, a new infrastructure requires a new extension, so nothing that would be done here. The ticket already went into stale. Care to contribute such an extension @toonsevrin ?

**Comment by toonsevrin** [comment]
@vasu1124 and I talked a bit about this on slack. At the time there were no plans to develop this in-house.

We touched slightly on me developing this as a student-employee (at SAP) but at the time I was too time constrained to consider doing this (due to exams and tax period for my business).

It seems that there is still quite a bit of interest from the community in this extension (understandably because Hetzner Cloud is a leading cost oriented provider). So if you're interested, we can discuss the possibility of me developing the extension!

On a sidenote: Does gardener integrate with the cluster-api yet? In that case I think it would be more valuable to write the extension on the cluster-api level for interoperability.

**Comment by hardikdr** [comment]
>Does gardener integrate with the cluster-api yet? 

At the moment no. Though, we are looking at a possibility of developing a dedicated `gardener-control-plane-provider` similar to the kubeadm-based provider in CAPI. - https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20191017-kubeadm-based-control-plane.md


>In that case I think it would be more valuable to write the extension on the cluster-api level for interoperability.

I don't think, it's easily possible to develop an interoperable provider, working with both CAPI and Gardener, as the  MachineAPI and InfrastructureAPI are different in both.

**Comment by berendt** [comment]
In the meantime load balancers can also be used on the Hetzner cloud.

From our point of view a broad support also of smaller CSPs makes a lot of sense for Gardener.

We would like to have a look at this topic.

@toonsevrin Do you have time to help?

**Comment by robinbraemer** [comment]
I'm also looking forward to get Gardner integration with Hetzner.

**Comment by toonsevrin** [comment]
@berendt I got in touch with @hardikdr a while ago as I also was very eager to get this going. At the time there was no position on their team available for me to work on this as a paid student employee. I doubt the situation has changed since then and am sadly enough unable to contribute on this in my unpaid time. Sorry :(

I think it is still a great and strategic move to support hetzner, so I hope someone does pick this up!

**Comment by berendt** [comment]
We would take over this and initiate the initial development in the coming weeks. First in https://github.com/23technologies/gardener-extension-provider-hcloud. We would then move it after completion. Not sure what the process is to get a repository in the Gardener namespace. Or if it would have to go to https://github.com/hetznercloud/ later.

**Comment by rfranzke** [comment]
There is https://github.com/23technologies/gardener-extension-provider-hcloud now, so let's
/close
this issue and follow up on above repo
