### ISSUE TITLE
Add grace period for conditions after successful Shoot reconciliation

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#2387]
**How to categorize this issue?**

/area ops-productivity
/area quality
/kind enhancement
/priority normal

**What would you like to be added**:
I see a lot of Shoot clusters, which finish to be created/woken up successfully (`lastOperation.state=Succeeded`) but need some more time to get completely healthy. E.g. `elasticsearch-logging` takes some time to completely start up (including volume provisioning) and therefore causes the `ControlPlaneHealthy` condition to be false for a short period of time after successful Shoot creation. Another example are the calico components, which take some time to start up and therefore sometimes cause either `SystemComponentsHealthy` or `EveryNodeReady` to be false.

I propose to add a grace period (of about `5m`, but configurable) after successful creation, in which failing health checks result in conditions with status `Progressing` instead of `False`.

**Why is this needed**:
These cases can happen quite often but don't indicate any problematic error. Pardoning those health checks for a short period of time after creation, can help gardener operators to filter out those non-problematic cases and focus on more relevant issues.

**Comment by rfranzke** [comment]
In a sync together with @tim-ebert we agreed to "start small" and re-use the existing [`conditionThreshold` configurations](https://github.com/gardener/gardener/blob/master/example/20-componentconfig-gardenlet.yaml#L48-L56). When a create/reconciliation operation is finished then the care controller could consider the `.status.lastOperation.lastUpdateTime` and mark the conditions as `Progressing` as they are expected to be unstable.
We can still think about a dedicated grace period in case this solution is not good enough.
