### ISSUE TITLE
Enable GPU Usage

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#24]
# Story
* As user I want to run GPU-dependent applications, so that I can use libraries such as Theano or Tensorflow on GPUs.

# Motivation
See above.

# Acceptance Criteria
- [x] Users can require nodes with GPUs
- [x] The GPU is actually available to (non-privileged) containers
- [x] CUDA usage for ML is possible
- [x] Theano or Tensorflow can consume available node GPUs

# Open Questions
- [ ] While CPUs are well compressible, how about GPUs (shader cores)?
- [ ] How do we provision the drivers into the OS images (image is fixed, so would daemon sets help)?

# Resources
See https://vishh.github.io/docs/user-guide/gpus for details. See also https://blog.openshift.com/use-gpus-with-device-plugin-in-openshift-3-9.

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?

**Comment by vlerenc** [comment]
Duplicate of https://github.com/gardener/gardener/issues/24.

**Comment by swapnilgm** [comment]
Reference for future investigation: https://kubernetes.io/docs/concepts/cluster-administration/device-plugins/

**Comment by vlerenc** [comment]
@afritzler provided a solution in https://github.com/afritzler/gpu-installer. He tested it with an AWS shoot cluster with p2 nodes and Tensorflow GPU usage.

**Comment by afritzler** [comment]
wrong user :P

**Comment by vlerenc** [comment]
We could integrate it into the Gardener as new addon and bind the daemon sets to worker pools with GPUs (we know that from the cloud profiles that list the number of GPUs; prerequisite: we transport that information into labels; @rfranzke and @dkistner). Or we do nothing and describe it only in the [HowTos/FAQ](https://github.wdf.sap.corp/pages/kubernetes/gardener/howtos) (@freegroup).

**Comment by afritzler** [comment]
So I renamed the repo now [0]. 

One thing to add here is:
- NodeLabeling and NodeSelector + Tolerations and Taints should be added to the manifests. 

I might make helm chart out of it.

https://github.com/afritzler/kubernetes-gpu

**Comment by afritzler** [comment]
Btw. we just successfully applied this to an OpenStack based setup with NVIDIA V100. The whole thing worked out of the box without any modification!

**Comment by vlerenc** [comment]
Great news!

**Comment by vlerenc** [comment]
I guess, the last thing missing is a HowTo in https://github.wdf.sap.corp/pages/kubernetes/gardener/howtos and then we can consider this done, at least as a first iteration, right?

**Comment by freegroup** [comment]
https://github.wdf.sap.corp/pages/kubernetes/gardener/doc/2017/01/16/howto-gpu.html

tutorial is written.

**Comment by bergerx** [comment]
Internal documentation link :'(

Is it possible to push the tutorial to github repo?

**Comment by vlerenc** [comment]
@marwinski @vasu1124 Any concrete/actionable plans to get the HowTos out into the public?

**Comment by vasu1124** [comment]
Looking at facilitating HowTos for community ... stay tuned.
