### ISSUE TITLE
Replace Heapster with the Kubernetes Metrics server

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#241]
From the 1.11 release notes:

> Deprecating Heapster: as part of the ongoing efforts to moving to the new Kubernetes monitoring model, Heapster is now deprecated. Clusters still using it for autoscaling should be migrated over to metrics-server and the custom metrics API. See the deprecation note below for more information on this. Clusters using Heapster for transfering metrics into long-term storage should consider using their metric solution's native Kubernetes support, if present, or should consider alternative solutions.

We should replace Heapster with the Kubernetes metrics server.

Heapster deprecation timeline: https://github.com/kubernetes/heapster/blob/master/docs/deprecation.md

**Comment by plkokanov** [comment]
I can start working on this little by little.

The kubernetes dashboard still uses heapster and they are currently also migrating to the metrics API: [2986](https://github.com/kubernetes/dashboard/issues/2986). 
We might have to keep heapster until all components we use, that are currently only supporting it, also switch to the metrics API.
