### ISSUE TITLE
TryUpdate and TryUpdateStatus not working as expected when conflict occurs.

### ISSUE THREAD

**Issue by swilen-iwanow** [gardener/gardener#2454]
**How to categorize this issue?**

/area robustness
/kind bug
/priority normal

**What happened**:

Using the `TryUpdateStatus` function from `pkg/utils/kubernetes/update.go` discovered
an issue that was preventing the resource to be updated as expected. The issue is preventing `status.state` from update if a conflict occurs, when using `tryUpdate()` . For example:
For the first call of `tryUpdateStatus` we have the obj `worker.status.state=nil`.
And in tryUpdate we get the object from the server, transform it so `worker.status.state=something`, we check the object for changes before and after the transform and if it has changed we try to update. If a conflict occurs we fail, but our in memory object has `worker.status.state=something`.
So on the next iteration we get the object from API Server, which still has `worker.status.state=nil` in the server, but the object in memory is with `worker.status.state=something` (for some reason client.Get() merges it). On the next step we transform it which doesn't change anything and test if the transformed object is different from the one received from the server. They are now equal so we don't update and simply return.

**What you expected to happen**:

`status.state` to be updated as expected.

**How to reproduce it (as minimally and precisely as possible)**:

Concurrently update an object using the `TryUpdate*` functions from `pkg/utils/kubernetes` package.

**Environment**:

- Gardener version: master

**Comment by timebertt** [comment]
This seems to be caused by the underlying json decoder (see https://github.com/gardener/gardener/pull/2450#issuecomment-644128313).

**Comment by plkokanov** [comment]
One way to fix this is to pass a copy of the object that we would want to modify to the transform func similar to how it is done for tryUpdateShoot: [shoot.go:48](https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/shoot.go#L48)

However, then `TryUpdate`, `TruUpdateStatus` and `tryUpdate` will have to return the updated object (if there's a chance for it to be used after the call)

I did a quick PR last week with only part of the code which is affected, but wasn't sure if that was the way we want to proceed: https://github.com/plkokanov/gardener/commit/90d51a7de9f3d504c4e33d6b45cd66799fd1e7ee

**Comment by timebertt** [comment]
Yes, this is one way to solve the issue.
But the problem with your approach is, that you return a `runtime.Object` from `TryUpdate` and so on. So if callers want to further work on the object, they will always have to cast it, which is not so desirable IMO.

But TBH, I don't have a better approach in mind as of now

**Comment by swilen-iwanow** [comment]
The easiest way to get rid of the bug is to remove this https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/update.go#L56  DeepEqual check, as it is the buggy part. The idea behind it is to check if the received and transformed objects are equal, but in case of a conflict it is not working as expected. The cons of this approach are that we are going to make an update request for object that are already in the desired state. Another way that comes to my mind is to pass the object to the transform function instead of using the closure. Then the API will be used something like this 
 	
        tryToUpdateInfra := &extensionsv1alpha1.Infrastructure{
		ObjectMeta: metav1.ObjectMeta{
			Name:      infraName,
			Namespace: infraNamespace,
		},
	}

	if err := kutil.TryUpdateStatus(bgCtx, wait.Backoff{Steps: 20, Duration: time.Second}, c, tryToUpdateInfra, func(infra runtime.Object) error {
		infraState, _ := json.Marshal(state{"someState"})
		infraAcc, err := extensions.Accessor(infra)
		if err != nil {
			return err
		}
		infraAcc.GetExtensionStatus().SetState(&runtime.RawExtension{Raw: infraState})
		tryToUpdateInfra = infraAcc.(*extensionsv1alpha1.Infrastructure)

		return nil
	}); err != nil {
		log.Println("Update didn't make it :(", err)
                return err
	}

**Comment by timebertt** [comment]
Hmm, I would not go for removing the `DeepEqual` check.
Also, passing a `runtime.Object` to the transform func yields the same problem as returning a `runtime.Object`: callers will always have to convert the object to the underlying type, that they want to work with.

I took another look at the `tryUpdate` function and found some way, that might work for all the requirements we have.
It adds a `*runtime.Scheme` param to the func, but this can maybe be defaulted to `scheme.Scheme` in `TryUpdate` and `TryUpdateStatus` if it is not passed by the caller.
But I have to check, if it really works, this was just a quick sketch...

```go
func tryUpdate(ctx context.Context, backoff wait.Backoff, c client.Client, scheme *runtime.Scheme, obj runtime.Object, updateFunc func(context.Context, runtime.Object, ...client.UpdateOption) error, transform func() error) error {
	key, err := client.ObjectKeyFromObject(obj)
	if err != nil {
		return err
	}

	return exponentialBackoff(ctx, backoff, func() (bool, error) {
		var objectFromServer runtime.Object

		// create new typed object of the given kind or fallback to an unstructured object if it is not registered in the scheme
		if typed, err := scheme.New(obj.GetObjectKind().GroupVersionKind()); err == nil {
			objectFromServer = typed
		} else {
			u := &unstructured.Unstructured{}
			u.SetGroupVersionKind(obj.GetObjectKind().GroupVersionKind())
			objectFromServer = u
		}

		// get the current object
		if err := c.Get(ctx, key, objectFromServer); err != nil {
			return false, err
		}

		// copy back the result from the server into the original object
		if err := scheme.Convert(objectFromServer, obj, nil); err != nil {
			return false, err
		}

		beforeTransform := obj.DeepCopyObject()
		if err := transform(); err != nil {
			return false, err
		}

		if reflect.DeepEqual(obj, beforeTransform) {
			return true, nil
		}

		if err := updateFunc(ctx, obj); err != nil {
			if apierrors.IsConflict(err) {
				return false, nil
			}
			return false, err
		}
		return true, nil
	})
}
```

**Comment by swilen-iwanow** [comment]
This looks possible solution, but I am worried if the Convert method would clean the obj from fields (when they don't exist in objectFromServer), that are set during previous runs by the transform, when there is a conflict 🤯🤯 . Who knows. We have to try it I guess. Would you or should I?

**Comment by timebertt** [comment]
Hmm, the reason I did it in this way, was to ensure, that the object is updated to exactly the version from the server before `transform` is called. But as said, I am not sure, if this will work.

If you want to try and take over this task, feel free to assign yourself to this issue using `/assign` 😉

**Comment by swilen-iwanow** [comment]
I am already assigned. Will try it and comeback to you 🤝

**Comment by timebertt** [comment]
Ah nice, I missed that 😄 
Thank you!

**Comment by swilen-iwanow** [comment]
We are preparing a demo for Thursday, I plan to work on this on Friday, if it is not a problem.
