### ISSUE TITLE
Failed to delete hibernated cluster w/ KAS network proxy

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#2458]
**How to categorize this issue?**

/area control-plane
/kind bug
/priority normal

**What happened**:
A 1.18.x shoot which had been created and hibernated could not be deleted after the `KonnectivityTunnel` feature gate was activated.

The Kube-Apiserver hung in the init state because of the following events:

```
  Warning  FailedMount  1s (x6 over 17s)  kubelet, ip-10-242-20-136.eu-west-1.compute.internal  MountVolume.SetUp failed for volume "vpn-seed-tlsauth" : secret "vpn-seed-tlsauth" not found
  Warning  FailedMount  1s (x6 over 17s)  kubelet, ip-10-242-20-136.eu-west-1.compute.internal  MountVolume.SetUp failed for volume "vpn-seed" : secret "vpn-seed" not found
```

**What you expected to happen**:
The shoot is deleted successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Disable `KonnectivityTunnel` (https://github.com/gardener/gardener/pull/2251)
1. Create 1.18.x shoot
1. Hibernate shoot
1. Activate `KonnectivityTunnel`
1. Reconcile shoot
1. Delete shoot

**Environment**:

- Gardener version: v1.6.1

**Comment by timuthy** [comment]
@zanetworker are you willing to take a look?

**Comment by rfranzke** [comment]
Probably related to #1240

**Comment by zanetworker** [comment]
@timuthy will take a look sometime later.

**Comment by danielfoehrKn** [comment]
Seeing something similar sometimes on the kube-apiserver. I ll keep an eye on it.
```
Unable to attach or mount volumes: unmounted volumes=[konnectivity-server-certs konnectivity-server-kubeconfig]
```

EDIT: most likely unrelated.

**Comment by zanetworker** [comment]
@danielfoehrKn I think this is different, to me this sounds like a problem with volume attachement  itself not with resources not found.

**Comment by zanetworker** [comment]
@timuthy I tried reproducing this issue with no success, did the steps you mentioned in the issue: 

1. Disable `KonnectivityTunnel`
1. Create 1.18.x shoot
1. Hibernate shoot
1. Activate `KonnectivityTunnel`
1. Reconcile shoot 
1. Delete shoot 

Also for the last step tried deleting the shoot after reconciliation while hibernation is enabled and after waking it up:
- Activate KT -> reconcile with hibernation enabled -> delete shoot (deleted)
- Activate KT -> wakeup shoot -> delete shoot (deleted)


I must be missing something (I am restarting the kubelet everytime I activate / deactivate to load the feature gate config in).
