### ISSUE TITLE
Streamline error codes

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#2469]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement
/priority normal

**What would you like to be added**:
We should streamline our error codes. Today, we have `ERR_INFRA_UNAUTHORIZED` and `ERR_INFRA_INSUFFICIENT_PRIVILEGES` which are both more or less the same. However, we use `ERR_INFRA_UNAUTHORIZED` mostly for 401 Unauthenticated errors. This might lead to confusing when doing operations.

Probably, we should either
1. add `ERR_INFRA_UNAUTHENTICATED` and deprecate `ERR_INFRA_UNAUTHORIZED`
1. add `ERR_INFRA_UNAUTHENTICATED` and deprecate `ERR_INFRA_INSUFFICIENT_PRIVILEGES`

Personally, I prefer 2.

**Why is this needed**:
Improve ops productivity

/cc @grolu

**Comment by timuthy** [comment]
+1 for option 2
