### ISSUE TITLE
IPVS Adoption

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#247]
In Kubernetes v1.11 IPVS-based in-cluster service load balancing graduated to GA (https://kubernetes.io/blog/2018/06/27/kubernetes-1.11-release-announcement):
> IPVS (IP Virtual Server) provides high-performance in-kernel load balancing, with a simpler programming interface than iptables. This change delivers better network throughput, better programming latency, and higher scalability limits for the cluster-wide distributed load-balancer that comprises the Kubernetes Service model. IPVS is not yet the default but clusters can begin to use it for production traffic.

**Comment by vlerenc** [comment]
@mvladev found this issue https://github.com/kubernetes/kubernetes/issues/57841, but otherwise it looks good and may help performance further @hardikdr @gonzolino @dkusidlo.

**Comment by m1093782566** [comment]
Seems kubernetes/kubernetes#57841 is not a real issue, please check: https://github.com/kubernetes/kubernetes/issues/57841#issuecomment-402007534

**Comment by mvladev** [comment]
Great news! Thank you @m1093782566!

**Comment by m1093782566** [comment]
You are welcome @mvladev :)

Please feel free to contact me when you have any question/problem in trying IPVS. I am the feature owner and responsible for fixing any issue.

**Comment by marwinski** [comment]
@DockToFuture: there was already an ipvs ticket - this one. As for calico - it adops automatically:

> Calico has support for kube-proxy’s ipvs proxy mode. Calico ipvs support is activated automatically if Calico detects that kube-proxy is running in that mode.
