### ISSUE TITLE
Wrong usage of client.MatchingFields

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2475]
**How to categorize this issue?**

/area quality
/kind bug
/priority normal

**What happened**:
Currently `secretToBackupBucketMapper` and `secretToBackupEntryMapper` both have usage wrong usage of `client.MatchingFields`.

https://github.com/gardener/gardener/blob/973993fdea1b0cfd843c9795f65fe4d9ad898fa2/extensions/pkg/controller/backupbucket/mapper.go#L61-L64

https://github.com/gardener/gardener/blob/973993fdea1b0cfd843c9795f65fe4d9ad898fa2/extensions/pkg/controller/backupentry/mapper.go#L47-L50

Both mappers will always return nil as the `List` invocation always returns non-nil err `field label not supported: spec.secretRef.namespace`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
You can put a log entry in the mapper to see that the error is always non-nil. Or you can use the follow `main.go` to reproduce the issue:

```golang
func main() {
	scheme := runtime.NewScheme()
	extensionsv1alpha1.AddToScheme(scheme)

	cl, err := client.New(config.GetConfigOrDie(), client.Options{Scheme: scheme})
	if err != nil {
		panic(err)
	}

	backupBucketList := &extensionsv1alpha1.BackupBucketList{}
	if err := cl.List(context.TODO(), backupBucketList,
		client.MatchingFields{"spec.secretRef.name": "foo"}, client.MatchingFields{"spec.secretRef.namespace": "bar"}); err != nil {
		panic(err)
	}

	fmt.Printf("%+v", backupBucketList)
}
```

```
$ go run main.go
panic: field label not supported: spec.secretRef.namespace

goroutine 1 [running]:
main.main()
	/Users/me/git/example/main.go:25 +0x32b
exit status 2
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.6.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by swapnilgm** [comment]
/status accepted

Thanks for reporting issue. I will work on it.
