### ISSUE TITLE
Update K8s dependencies to 1.18.x

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#2489]
**How to categorize this issue?**

/area robustness
/kind enhancement
/priority normal

**What would you like to be added**:
Update the `vendor` sources in g/g to K8s 1.18.x.

**Comment by timuthy** [comment]
To track progress: https://github.com/timuthy/gardener/tree/maintenance.vendor

**Comment by timuthy** [comment]
Update: As soon as #2588 has been merged, we proceed with the actual update work.

**Comment by phil9909** [comment]
FYI: This blocks us from updating [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/) from `0.5.x` to `0.6.x`.

We import `github.com/gardener/gardener/pkg/apis/core/v1beta1` in our go-code to dynamically create shoots.

**Comment by timebertt** [comment]
Why is this blocking you?
If you are only importing the API packages, you should be good to go for using different versions of k/k or controller-runtime. Right?

**Comment by phil9909** [comment]
This is what I assumed, but seems not to be true:

```
go build -o bin/manager main.go
# github.com/gardener/gardener/pkg/apis/core/v1beta1
../../../go/pkg/mod/github.com/gardener/gardener@v1.8.0/pkg/apis/core/v1beta1/conversions.go:84:15: scheme.AddConversionFuncs undefined (type *runtime.Scheme has no field or method AddConversionFuncs)
Makefile:57: recipe for target 'build' failed
make: *** [build] Error 2

```

`conversions.go` is apparently broken with k8s 1.18 dependencies

**Comment by timebertt** [comment]
Ah ok, makes sense.
Thanks for explaining!

**Comment by franpog859** [comment]
Hello! May I ask you when this update will be done? I currently use these versions of k8s dependencies in my component:
```
require (
	github.com/gardener/gardener v1.8.1
	...
	k8s.io/api v0.18.8
	k8s.io/apimachinery v0.18.8
	k8s.io/client-go v0.18.8
	sigs.k8s.io/controller-runtime v0.6.2
```
and the old Gardener's dependencies seem not to allow me to build it at all 😞
```
# github.com/gardener/gardener/pkg/apis/core/v1beta1
/Users/franpog859/go/pkg/mod/github.com/gardener/gardener@v1.8.1/pkg/apis/core/v1beta1/conversions.go:84:15: scheme.AddConversionFuncs undefined (type *runtime.Scheme has no field or method AddConversionFuncs)
```

**Comment by ialidzhikov** [comment]
It seems that the issues from above are caused by https://github.com/kubernetes/kubernetes/issues/84452 + https://github.com/kubernetes/kubernetes/pull/85891. In general we should be able now to switch `AddConversionFuncs` calls to `AddConversionFunc` and that should allow vendoring gardener/gardener with k/k@v0.18.x.

**Comment by timuthy** [comment]
I already did that in my WIP branch, e.g. https://github.com/timuthy/gardener/blob/159a91cfb4fa61fc9dfcae95601543c33dc16020/pkg/apis/core/v1alpha1/conversions.go and hope to finish the rest next week.

**Comment by franpog859** [comment]
Hello, @timuthy! May I ask you, what is the change's status? 
It's getting more and more urgent from my side to upgrade these dependencies 😞
