### ISSUE TITLE
Cannot bootstrap Seed when all gardenlet feature gates are false

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2492]
**How to categorize this issue?**

/kind bug
/kind regression
/priority normal

**What happened**:
Cannot bootstrap Seed when all gardenlet feature gates are false.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. `make start-gardenlet` on the master branch

2. Ensure that a Seed cannot be bootstrapped.
```
$ k describe seed seed-local-aws

    Message:               failed to delete manifests: 3 errors occurred: [could not delete object of kind "EnvoyFilter" "istio-ingress/proxy-protocol": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3", could not delete object of kind "Gateway" "istio-ingress/proxy-protocol": no matches for kind "Gateway" in version "networking.istio.io/v1beta1", could not delete object of kind "VirtualService" "istio-ingress/proxy-protocol-blackhole": no matches for kind "VirtualService" in version "networking.istio.io/v1beta1"]
    Reason:                BootstrappingFailed
    Status:                False
    Type:                  Bootstrapped
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
It seems like not only the seed bootstrap is affected. I am also unable to reconcile/create a Shoot successfully with `APIServerSNI` disabled.
