### ISSUE TITLE
Credential update for machines in rolling update

### ISSUE THREAD

**Issue by prashanth26** [gardener/gardener#2499]
**How to categorize this issue?**

/area operations
/kind bug
/priority normal

**What happened**:
I think what has happened is that there was a worker pool with valid credentials. The machine images were updated.  And then secret credentials were updated to an incorrect one. And then the credentials was again updated to the correct one. Bcoz the machine class had a deletion timestamp the credentials were not updated properly by the Gardener extension.

NAME READY DESIRED UP-TO-DATE AVAILABLE AGE
machinedeployment.machine.sapcloud.io/shoot--xxx-worker-z1 1 1 0 1 27h
NAME DESIRED CURRENT READY AGE
machineset.machine.sapcloud.io/shoot--xxx-worker-z1-c876ff6df 1 1 0 24h
NAME STATUS AGE
machine.machine.sapcloud.io/shoot--xxx-worker-z1-c876ff6df-lm4z9 Running 24h
NAME MACHINE TYPE AMI AGE
awsmachineclass.machine.sapcloud.io/shoot--xxx-worker-z1-a827a m5.large ami-x 24h
awsmachineclass.machine.sapcloud.io/shoot--xxx-worker-z1-ebc99 m5.large ami-y 27h

I could delete the machine using CLI, but I think there needs to be a fix in the gardener/extension to handle such cases and update the old machineSet's credentials.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: AWS
- Others:

**Comment by rfranzke** [comment]
@prashanth26 can you give an update or close this issue if it's not relevant anymore?

**Comment by prashanth26** [comment]
I haven't observed this since [PR #2626](https://github.com/gardener/gardener/pull/2626) is merged on the Gardener. Let's close it for now and reopen if we see it again. 

/close
