### ISSUE TITLE
Reserve Excess Capacity in Seed Cluster

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#254]
# Story
* As user I want my shoot cluster to be provisioned as fast as possible, so that I can work with the cluster right away (extremely useful for programmatic access and provisioning or for testing, training and demonstration purposes).

# Motivation
Initially we wanted to implement cluster excess capacity reservation in the mcm (gardener/machine-controller-manager#26), so that our seed clusters had sufficient capacity available for new shoot clusters. However, it seems easier to use low-priority pods to keep excess capacity available, which is also the general recommendation issued by the cluster autoscaler community that we are using. 

# Acceptance Criteria
- [ ] 3 new clusters or 5 % of the current number of clusters (whatever is larger) can be scheduled without provisioning of new machines in a seed cluster.

# Implementation Proposal
Let's use low priority pods (in exactly the configuration required for new shoot clusters) scheduled on the seed cluster. When a real shoot cluster control plane is scheduled with normal priorities, it will displace the low priority pods, but they will remain in the ledger and the cluster autoscaler will request new machines to fulfil the demand again. This will require the PriorityAdmissionPlugin. Since we most likely don't want to enable general configuration of admission plugins (preferred and most flexible solution, but may come with risks, that we would need to think through first), we can at least enable the PriorityAdmissionPlugin Gardener-wide (like the others we have enabled statically, which seems to have a limited impact/risk and makes this available for us in seed clusters, but also to our end users in shoot clusters).

For the entire discussion, take a look at gardener/machine-controller-manager#26.

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?
- [ ] User documentation: Have you informed Sylvia Pick about user relevant changes?

**Comment by prashanth26** [comment]
After having @hardikdr try a basic working of the low-prio pods for reserving excess capacity for a cluster. Now I shall be trying to integrate this into the gardener.

**Comment by vlerenc** [comment]
Thanks @prashanth26!

**Comment by vlerenc** [comment]
All related (in terms of the need to switch on an admission controller/plugin): #254 (priority), #257 (Initializers), #258 (PodNodeSelector , PodTolerationRestriction), #259 (PersistentVolumeClaimResize).

BLI for configurable admission controllers/plugins is now #263.

**Comment by prashanth26** [comment]
Gentle Reminder: We need to enable cluster-autoscaler on seed clusters (shoot-specs) to enable the working on reserve excess capacity. We will need to do this once, the new version of gardener is released.

**Comment by vlerenc** [comment]
Yes, @dkistner looks into this.
