### ISSUE TITLE
PVs cannot be destroyed after waking up one hibernated shoots

### ISSUE THREAD

**Issue by minchaow** [gardener/gardener#2545]
**How to categorize this issue?**

/area storage
/kind bug
/priority normal

**What happened**:
`PVs` cannot be destroyed for waking up shoot clusters. The status of `PVs` are always in `Terminating`.
When executing `kubectl get volumeattachments.storage.k8s.io`, I noticed `PVs` are still binding to the old nodes (which already destroyed during hibernating).
**What you expected to happen**:
`PVs` can be destroyed successfully.
**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy one `deployment` or `statefulset` with `PVC`.
2. Hibernate the shoot.
3. Wake up the shoot and delete the `deployment` or `statefulset`, and `PVC`, but the `PV` cannot be destroyed.
4. Execute `kubectl get volumeattachments.storage.k8s.io`, can see the `PV` is still binding to the old node.

**Anything else we need to know?**:
The issue seems related to CSI plugins. Tested on AWS and Alicloud, and both providers have the issue.

**Environment**:

- Gardener version: v1.6.5
- Kubernetes version (use `kubectl version`): 1.18.4
- Cloud provider or hardware configuration: alicloud-provider, aws-provider
- Others:

**Comment by prashanth26** [comment]
This issue seems to be affecting all providers. Here is the one for GCP - https://github.com/gardener/gardener-extension-provider-gcp/issues/172. Adding it as a back reference.
