### ISSUE TITLE
Gardener v1.7.0 seems to be breaking the extension-provider-aws v.1.10

### ISSUE THREAD

**Issue by hardikdr** [gardener/gardener#2558]
**How to categorize this issue?**

/area usability
/kind bug
/priority normal

**What happened**:  Latest gardener-extension-provider-aws seems not to be able to build when gardener v1.7.0 is vendored in. 

**What you expected to happen**: I expected the provider extension to build well against the latest release of g/g.

**How to reproduce it (as minimally and precisely as possible)**: 
1. Clone g-extension-provider-aws.
2. Following changes in the go.mod:
```
replace (
	github.com/gardener/gardener => github.com/gardener/gardener v1.7.0
...
)
```
3. `make revendor`
4. `make start`
Following error is seen:
```
pkg/controller/worker/machines.go:231:11: invalid indirect of dataVolumes[i].Name (type string)
pkg/controller/worker/machines.go:231:34: invalid indirect of dataVolumes[j].Name (type string)
pkg/controller/worker/machines.go:235:40: cannot use vol (type "github.com/gardener/gardener/pkg/apis/extensions/v1alpha1".DataVolume) as type "github.com/gardener/gardener/pkg/apis/extensions/v1alpha1".Volume in argument to computeEBSForVolume
```
- Not sure though, if it's specific to my local setup. 
**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.7.0
- Kubernetes version (use `kubectl version`): NA
- Cloud provider or hardware configuration: aws
- Others:

**Comment by ialidzhikov** [comment]
See https://github.com/gardener/gardener-extension-provider-aws/pull/129 for example as adaptation.
