### ISSUE TITLE
Resource reservation for kube and system daemons 

### ISSUE THREAD

**Issue by guydc** [gardener/gardener#2559]
**How to categorize this issue?**

/area robustness
/kind enhancement
/priority normal

**What would you like to be added**:
[Kubelet configuration](https://godoc.org/k8s.io/kubelet/config/v1beta1) can be used to [reserve resources for kube and system daemons](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/). Reserved resources are deducted from the node's capacity. Node allocatable resources can also be enforced by kubelet on three cgroups: system (eg. `system.slice`), kube (eg. `runtime.slice`) and pods (`kubepods`). If resources are enforced, relevant cgroup controllers are configured (`cpu.shares`, `memory.limit_in_bytes`, ...)

The shoot worker kubelet config should allow configuration of the following attributes: `SystemReserved`, `KubeReserved`. 

**Why is this needed**:
Currently, gardener does not support resource reservation, and the following [default configuration](https://github.com/gardener/gardener/blob/master/charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet-config-file) is used:

```
enforceNodeAllocatable:
- pods
kubeReserved:
  cpu: 80m
  memory: 1Gi
```

This configuration deducts `80m` and `1Gi` from node's capacity, and enforces the allocatable resources on the `kubepods` cgroup. For example, on a 8 CPU, 32 GB node, the `kubepods` cgroup would be configured with 8110 `cpu.shares` and 31769579520 `memory.limit_in_bytes`.  

In gardener nodes, kubelet and docker run as systemd services under the `system.slice` cgroup, which is configured with default values (eg. 1024 `cpu.shares`). The existing configuration can lead to starvation of kube components on nodes with high pod density and burstable, resource-intensive workloads: pods are not limited from consuming most of the node's resources and 
appropriate resources cannot be assigned to the kube/system cgroups.

**Comment by timuthy** [comment]
Thanks for opening this issue and the description @guydaichs.

Did I get it correctly that in your case, the values for the `system-reserved` cgroup were too low and thus the kube components where throttled? Btw. which kube components do you mean besides the kubelet process?

Have you tested the very same scenario with higher `system-reserved` values and saw the throttling not happening?

I'm not generally voting against this request but also wonder if we can use some more decent default values.

**Comment by guydc** [comment]
Hi @timuthy, 

> Did I get it correctly that in your case, the values for the `system-reserved` cgroup were too low and thus the kube components where throttled? Btw. which kube components do you mean besides the kubelet process?
>
> Have you tested the very same scenario with higher `system-reserved` values and saw the throttling not happening?

I refer to kubelet and docker. Our performance tests showed that increasing `system.slice` cpu shares improved the average pod start time by 30%, when multiple pods are scheduled on a certain node at a high rate. 
 
> I'm not generally voting against this request but also wonder if we can use some more decent default values.

I think that the default values are fine for most cases, and don't see a reason to change them in general. 

Our scenario involves large VMs, high pod density and turnaround, bursting workloads, and the pod init time has an impact on end-user experience. Kubelet and docker can consume as much as 2 cpu and 8GB on our nodes. Our use-case isn't typical, and some tuning is required in order to optimize certain operations. 

If you prefer to reduce the number of exposed parameters, it would probably be sufficient to only expose `kube-reserved`. We can use it to control the cpu share ratio between system components and pods. 

WDYT?

**Comment by timebertt** [comment]
/assign @guydaichs 
Thanks for picking up this task!

**Comment by guydc** [comment]
Following the discussion in #2574, I updated the requirement in this issue: only `SystemReserved`, `KubeReserved` should be exposed.
