### ISSUE TITLE
Generate a different password for the monitoring (and logging) stacks

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#256]
Since long, the cluster admin password is also used to secure the Grafana dashboard. That should be a different one, because the set of people (end users and cluster operators) may be different ones.

**Comment by plkokanov** [comment]
Created PR #271 

I've currently only added different password generation for the monitoring stack.
I will add password generation for the logging stack PR (#176) as soon as PR #271 gets approved.

**Comment by dkistner** [comment]
PR #271 is merged. Can we close this issue?

**Comment by rfranzke** [comment]
I guess we also want to use another password for securing access to AlertManager and Prometheus, right? @vlerenc 
With #271, a new password is only used for Grafana. AlertManager/Prometheus are still secured with the kube-apiserver's Basic Auth. credentials.
