### ISSUE TITLE
Integration Tests for Shoot Control Plane Migration

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#2561]
**How to categorize this issue?**

/area control-plane-migration
/kind enhancement
/priority normal

**What would you like to be added**:
Integration tests for `Shoot` control plane migration between working `Seeds`.
 
**Why is this needed**:
The control plane migration of `Shoots` between working `Seeds` is nearly ready to be tested. To do that the following tasks have to be completed:
- [x] Reuse the `CreateShoot` test definition to create the `Shoot` which will be migrated on one of the existing seeds.
- [x] Deploy an application on the `Shoot` - the guest book application can be reused.
- [x] Create a new test definition which can be used to create a `Shoot` with appropriate settings so that it can be registered as a `Seed`
- [x] Enhance the test framework with functionality which can be used to register `Shoots` as `Seeds` (required resources like `Cloudprofile`, backup `Secret`, and so on can be copied from existing shooted `Seeds`
- [x] Create a test definition to execute the `Seed` registration
- [x] Create the Control Plane Migration test
    - [x] Trigger migration and wait for the `Shoot` to be migrated from an existing `Seed` to the newly registered shooted `Seed`
    - [x] ~During the test continuously check if the guest book application is working.~
    - [x] After migration has completed make sure that the machines do not get recreated by comparing the `Machine` resources and the existing `Nodes`
    - [x] After migration has completed make sure that the cluster can be accessed without having to download new credentials and that all pods are working properly.

**Comment by danielfoehrKn** [comment]
> Initially the control plane migration tests will only be enabled for one provider and on the Dev and Staging landscapes.

Please do not mention internal landscapes.

**Comment by rfranzke** [comment]
Ping, just want to raise the importance and priority of these integration tests, especially for those parts which are not limited to the shoot control plane migration itself (e.g., the `ShootState` sync controller, etc.). In v1.8, we just had a regression that was undetected, so an integration test is very much needed.

**Comment by plkokanov** [comment]
Closing this as the tasks have been completed. We will open new issues for enhancements or any problems that come up with the integration tests
