### ISSUE TITLE
need --admission-control=PersistentVolumeClaimResize flag to use VolumeResize

### ISSUE THREAD

**Issue by freegroup** [gardener/gardener#259]
since kubernetes version 1.9 it seems to be possible to resize volumes on demand for this kind
of storage types
- gcePersistentDisk
- awsElasticBlockStore
- OpenStack Cinder
- glusterfs
- rbd

To be able to use this feature you need to allow expanding PVCs by setting **ExpandPersistentVolumes feature** gate to true. Also, enable **PersistentVolumeClaimResize** admission plugin if you want to prevent resizing of all claims unless you enable resize in storage class.

If you are using AWS you will pay for that unused space even if you don't need it at the moment.  Manual resize is possible, but it isn't convenient.

Maybe the settings for the api-server can be part of the shoot-yaml. In this case, it is more flexible and even alpha features can be enabled for test purpose.
currently, it seems to fixed at https://github.com/gardener/kubify/blob/9904f72847b267092c8f123aca3a83355a8c9b75/basetemplates/manifests/kube-apiserver.yaml#L31

**NOTE:** Online resize support should be available in Kubernetes v1.11, and you won't need to recreate resources for file system resize.

**Comment by vlerenc** [comment]
All related: #254 (priority), #257 (Initializers), #258 (PodNodeSelector , PodTolerationRestriction), #259 (PersistentVolumeClaimResize).

BLI for configurable admission controllers/plugins is now #263.

**Comment by vlerenc** [comment]
FYI: Feature gates can already be tweaked in the shoot resource. What remains is the configuration of admission plugins.

https://github.com/gardener/gardener/blob/f6f8e2382143d9179d8ec13657515e46ffc97669/pkg/apis/garden/types.go#L984-L1058

**Comment by vlerenc** [comment]
FYI: https://github.com/gardener/gardener/blob/f6f8e2382143d9179d8ec13657515e46ffc97669/pkg/apis/garden/types.go#L984-L1058
