### ISSUE TITLE
New project role for project members administration

### ISSUE THREAD

**Issue by donistz** [gardener/gardener#2592]
/kind enhancement
/priority normal

**What would you like to be added**:
New project role for project members administration
**Why is this needed**:
The members of the Gardner projects can be managed via the Gardner Dashboard and also via the Gardner API by any project member with the Gardener role “admin”. The problem is that when the Gardner API is used for an integration with an external UAM solution, project admins can still override the permissions configured by the external system. In order to resolve this problem the access for managing the project members have to be segregated using a separate role. This way the project owner can decide to whom to grant the UAM access via Gardener Dashboard/API and when the project is integrated with an external UAM solution, it will be possible to keep this access only for the project owner for emergency use cases.

Proposals for the name of the new role: “uam”  (from User Access Management)

**Proposal for the implementation:**
1)	Create a new Gardner project member role and segregate the access for managing project members only in this role.
2)	Make sure that this role will be always assigned to the project owner, just like the owner is always assigned with the admin role.
3)	For all existing projects assign the new role to all project members who have the admin role. The project owner will be able to remove it from the members that don’t need it later.
4)	Remove the permissions for the project members management from the admin role

**Comment by grolu** [comment]
I want to raise some concerns from the Dashboard side. Currently, the members are part of the project resource. We decide based on the permissions we receive via `SelfSubjectRulesReview` if a user can patch a project. If he is allowed to, we enable project administration (e.g. description, cost center etc.) as well as member management.
How to you plan to separate member management from project management? From my knowledge this could only be achieved via some custom admission webhook implementation. In this case we would also need to hard-code these special rights into the dashboard as this is a permission not represented via rbac rules. Maybe this could be a good point in time to rethink if we want to split project and member resources apart.
Moreover, what about service accounts? Shall they also be managed via the external UAM solution?

**Comment by grolu** [comment]
@petersutter

**Comment by rfranzke** [comment]
@grolu The idea was to introduce a custom verb `spec-members`, similar like [`spec-tolerations-whitelist`](https://github.com/gardener/gardener/blob/9855c1b1a89b36df125ac76e95998a0ab32ff09d/pkg/apis/core/types_project.go#L96-L98) that allows to modify the members of a project. I don't think a dedicated resource is helpful at this point in time.
So, you can still use `SelfSubjectRulesReview` but with `spec-members` instead of `patch`.

> In this case we would also need to hard-code these special rights into the dashboard as this is a permission not represented via rbac rules.

Hm, not sure why you are saying it. Is it a problem? Currently you have "hardcoded" the `patch`. Just exchange the string.

> Moreover, what about service accounts? Shall they also be managed via the external UAM solution?

IIUC no. @donistz, please comment.

**Comment by donistz** [comment]
> Moreover, what about service accounts? Shall they also be managed via the external UAM solution?

Hello, Service accounts are not managed via the external UAM solution. The UAM solution is integrated in the way to manage only persona uses via an approval flow.
@rfranzke: Thanks a lot for the feedback!

Kind regards,
Donka

**Comment by rfranzke** [comment]
Does this mean that any admin should still be allowed to add/remove ServiceAccounts to/from the project members even when not having this "spec-members" role (but only patch/update)?

**Comment by donistz** [comment]
> Does this mean that any admin should still be allowed to add/remove ServiceAccounts to/from the project members even when not having this "spec-members" role (but only patch/update)?

Service Accounts are a kind of technical configuration. It is required to make sure that the Service Accounts permissions will not allow the person who has access to the service account token to use it to manage persona users via the Gardner API but the Service Accounts management should be allowed via the regular "admin" role.

**Comment by grolu** [comment]
> Hm, not sure why you are saying it. Is it a problem? Currently you have "hardcoded" the patch. Just exchange the string.

What I meant is, that we need to implement a custom check for the member management, and cannot just use the Rules we receive via `SelfSubjectRulesReview. If you implement a custom verb I guess this would simplify thinks for us.

>Service Accounts management should be allowed via the regular "admin" role

Okay, but then we cannot just exchange the string, right? @rfranzke Service Accounts are basically users with a special prefix, so can admins still patch the service account users but not the other ones? Or do we need to separate the lists?

**Comment by rfranzke** [comment]
Personally, I'd prefer to split the lists, but I haven't found a good way to achieve this backwards-compatibly (together with the to-be-introduced custom verb). In a call with @petersutter we agreed that it would probably make sense to split the lists of members (e.g. `.spec.members` and `.spec.robots` in a new API version of the core API).

For now, let's keep `.spec.members` as it is and introduce the `uam` custom role as follows (as it's probably the easiest option for both g/g and g/d):

1. Next to `admin`/`viewer` we introduce the `uam` role that will be assigned by default to the project owner.
1. The `uam` role is backed by the `uam` custom verb for `projects`.
1. For all existing projects assign the `uam` to all admin project members. The project owner will be able to remove it from the members that don’t need it later.
1. **Only if the `uam` custom verb is bound to the respective user it is allowed to add/modify/remove subjects in the `.spec.members` list having `kind={User,Group}`**.
1. **It is always allowed to add/modify/remove subjects in the `.spec.members` list having `kind=ServiceAccount` if the respective user is bound to the `patch/update` verb.**

**Comment by vpnachev** [comment]
The dashboard is not using `kind: ServiceAccount` but `kind: User` for any type of user.
ref: https://github.com/gardener/dashboard/issues/384

**Comment by grolu** [comment]
Yes, currently we don't differentiate between users and service accounts this is something we need to do. But all existing service accounts will not be manageable by admins if we don't migrate them

**Comment by rfranzke** [comment]
No problem, we can check for both, `kind=User` and `name=system:serviceaccounts:*`. No need for a migration.

**Comment by grolu** [comment]
Okay then this is clarified, from dashboard side we are okay with this approach
