### ISSUE TITLE
"fluentbit.io/exclude=true" is not removed after .spec.purpose change

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2593]
**How to categorize this issue?**

/area logging
/kind bug
/priority normal

**What happened**:
With #2320  gardener-seed-admission-controller adds the `fluentbit.io/exclude=true` annotation to the controlplane Pods when the spec.purpose=testing. When the purpose is changed, the exclude annotation stays in the controlplane Pods and this prevents fluent-bit to collect logs from them.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create Shoot with `.spec.purpose=testing` and ensure that controlplane Pods have the annotation `fluentbit.io/exclude: "true"`

2. Change the purpose to `evaluation`

3. Ensure that logging components are deployed as part of the controlplane.

4. Ensure that the `fluentbit.io/exclude: "true"` is not removed from controlplane Pods.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.7.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
I am now sure how https://github.com/gardener/gardener/pull/2615 fixes this issue? Doesn't the seed-admission webhook require create, update operation for given controlplane pod to be able to mutate it and remove the annotation when Shoot `.spec.purpose` is changed from testing to something else?
I now switched the `.spec.purpose` from testing for a given Shoot and for some of the controlplane Pods the `fluentbit.io/exclude=true` annotation is still not removed.

**Comment by ialidzhikov** [comment]
```
# Shoot with `.spec.purpose=testing`:

$ k -n shoot--foo--bar get po -o yaml | grep exclude
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"

# patch shoot `.spec.purpose=evaluation` and wait for reconcile

# the exclude annotations are not removed
$ k -n shoot--foo--bar get po -o yaml | grep exclude
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"
      fluentbit.io/exclude: "true"
```

**Comment by rfranzke** [comment]
Yes, but isn't this a general problem with the approach to have the annotation on the pod? When you switch from production -> testing you won't find the annotations either, right?
What do you suggest?

**Comment by ialidzhikov** [comment]
> Yes, but isn't this a general problem with the approach to have the annotation on the pod? When you switch from production -> testing you won't find the annotations either, right?

Yep, right, it is also a problem for the `production -> testing` change.

> What do you suggest?

If I had an idea that could address it in a simple && elegant way, I would already share it. I wanted to mention that the steps to reproduce are still valid and applicable.

**Comment by rfranzke** [comment]
The only idea I have right now is to add the shoot purpose as an annotation to the pod template metadata section for workload resources, i.e. `Deployment`s, `StatefulSet`s, etc. Then, when the purpose changes, the pods will be rolled out, triggering the webhook to add/remove the fluentd annotation.

**Comment by vpnachev** [comment]
With our custom plugin, which has a cluster watcher (https://github.com/gardener/logging/pull/59) this annotation is no longer needed, so the whole admission webhook can be removed.

/assign @vlvasilev @Kristian-ZH

**Comment by Kristian-ZH** [comment]
Yup, this was added in the backlog yesterday: https://github.com/gardener/gardener/issues/2677
