### ISSUE TITLE
Cluster level logging API for end-users

### ISSUE THREAD

**Issue by g-pavlov** [gardener/gardener#2595]
**How to categorize this issue?**
/area logging
/kind enhancement
/priority normal

**What would you like to be added**:
An API to support end users in aggregating cluster level logging data with application logging and/or documentation how to do that.

**Why is this needed**:
Cluster level logging provides context that can aid troubleshooting and tracing root cause in application issues. Having application and cluster logs in different locations makes the task difficult. It would be beneficial to have the option to have them in one location and preferable one that is chosen by the user.

**Comment by vpnachev** [comment]
@g-pavlov you have to prefix the usernames with `@`

/assign @vlvasilev @Kristian-ZH

**Comment by vpnachev** [comment]
To the best of my knowledge we are not planning to provide anything for application logs. The costs to move all of this over the wire might grow too much, thus we are recommending shoot owners to deploy and configure their own logging solution that fits their needs.

**Comment by vpnachev** [comment]
Any progress here  @g-pavlov @Kristian-ZH @vlvasilev ?
If not, then we can close this issue as we will not implement it.

**Comment by Kristian-ZH** [comment]
This is a good feature but currently we have more important tasks based on the Logging stack stabilisation and we can close this for now
