### ISSUE TITLE
Optimise Cluster VPN

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#26]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:45 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/44_

----

# Story
* As provider I want to have a fast, reliable and safe cluster VPN, so that I get all these benefits for this crucial component in the seed & shoot approach.

# Motivation
Performance, simplicity, and security.

# Acceptance Criteria
- [ ] Investigate if there is a more elegant approach to SSH for the cluster VPN between the API server in the seed cluster and the workers in the shoot cluster
- [ ] Secure access with security groups

# Related Resources
* See https://groups.google.com/forum/#!topic/kubernetes-dev/rO-cUwJMixQ
* See https://groups.google.com/forum/#!msg/kubernetes-sig-api-machinery/bwJJ93qA99o/yejsv2JPBAAJ
* See [k8sniff](https://github.com/kubermatic/k8sniff)
* See [kubernikus wormhole](https://github.com/sapcc/kubernikus/tree/master/pkg/wormhole)

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://git.infra.removed/kubernetes/kube-docs/wiki/Operations%20Guide)?

:information_source: Migrated from Jira issue [KUBE-160](https://jtrack.removed/browse/KUBE-160)

**Comment by vlerenc** [comment]
Moved to https://github.com/gardener/vpn/issues/17.
