### ISSUE TITLE
Pods scheduled on non-ready Nodes

### ISSUE THREAD

**Issue by ghost** [gardener/gardener#2621]
**How to categorize this issue?**

/area networking
/area robustness
/kind bug
/priority normal

**What happened**:

When we do an update of the OS, we notice that pods which get run on new Nodes are not able to initiate network connections or have trouble resolving DNS addresses.

**What you expected to happen**:

When a Pod is being scheduled on a new Node it should be able to initiate connections (i.e. we expect that the Node is healthy and fully ready for workload)

**How to reproduce it (as minimally and precisely as possible)**:

Have a deployment with an application that makes a TCP/HTTP connection to another service the first thing it starts.

**Anything else we need to know?**:

It appears to be caused by network services (Calico?) not having fully started while pods are being migrated to the new Node.

It appears that this is a known issue in K8s:
* https://github.com/kubernetes/kubernetes/issues/75890
* https://github.com/kubernetes/enhancements/pull/1003

Both mention the usage of `taint` to wait on critical service initialization before a Node is deemed ready.
> Perhaps the simplest way to do this is to start nodes with a taint and implement a controller that runs on master nodes and removes taints appropriately.
> We can allow cloud providers to add a "no routes" taint (or use the existing NetworkUnavailable node condition) assuming the routes controller will remove it later. Worth noting that the GCP provider does this today but via the kubelet. We should make this functionality available to all the external providers.

**Environment**:

- Gardener version: `v1.7.2`
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"b4455102ef392bf7d594ef96b97a4caa79d729d9", GitTreeState:"clean", BuildDate:"2020-06-17T11:32:20Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: `GCP`
- Others:

**Comment by vpnachev** [comment]
One option that can be researched, is to set the taint `node.kubernetes.io/network-unavailable` via the kubelet flag`--register-with-taints`, expecting the kubelet automatically to remove it (this has to be double checked) once the node is ready.

**Comment by dguendisch** [comment]
For the record, this contributes as well to the described issue: https://github.com/projectcalico/node/issues/519
(having observed such an issue this week myself and reading through the linked issues, I'm starting to wonder how k8s can work at all for any dynamic/job-like workload that involves node autoscaling, it's just too easy that the node incl. networking is not usable yet, but still pods/jobs will happily schedule to that new node..., in my case we maybe mostly get away with this by having reserve-excess-capacity pods, so there's always at least one extra node, old enough, hopefully stable and fully working until we schedule the first jobs there...)
