### ISSUE TITLE
Support user to disable ssl-passthrough option in Nginx Ingress addon

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener#2632]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority blocker

**What would you like to be added**:
User needs to disable ssl-passthrough option in Nginx Ingresss.
**Why is this needed**:
HanaCloud team reported that they can't get source IP in their apps which are exposed via Nginx Ingress Controller on AliCloud.

_What they found_:
- Disable ProxyProtocol in Nginx Ingress. For HTTP url access, they can get the real source IP. For HTTPS, they can only get 127.0.0.1
- Enable ProxyProtocol in Nginx Ingress. For HTTP url access, connection will be broken. For HTTPS, they can get the real source IP.

_Root cuase_:
- When ssl-passthrough is enabled in Nginx Ingress, an extra process(TLS Proxy) wll be started in the container, which will accept TLS incomming connection from SLB and copy incomming data volume to Nginx. In this case, Nginx `doesn't` communicate with Cloud provider's loadbalancer. Instead, the man-in-the-middle acts as the loadbalancer's listener. For plain network connection(like HTTP), nginx directly listens the loadbalancer.
- AliCloud loadbalancer(L4) dosn't support ProxyProtocol and actually Proxy Protocol is not needed because loadbalancer(SLB) always pass real source IP to listeners. So if listeners enable ProxyProtocol, the communication for HTTP between Nginx and SLB will fail. But for TLS (HTTPS in our case) still succeeds with ssl-passthrough. It could be un-expected result because of a Nginx Ingress bug.

_Conclusion_
- Nginx Ingress has some bugs to pass Source IP to Nginx when  ssl-passthrough is enabled and ProxyProtocol is disabled.
- Workaround at Gardener: to provide an option in Shoot to `disable ssl-passthrough`. Besides of this, to disable ssl-passthrough, it can enhance communication efficiency by removing man-in-the-middle between nginx and loadbalancer.

**Comment by rfranzke** [comment]
The nginx-ingress addon is not recommended for production use-cases, and we decided long time back to not invest into it anymore (hence, we are also running a very old version). End-users can deploy their own, up-to-date nginx-ingress (or whatever else) controller and configure it properly for their use-case.

**Comment by jia-jerry** [comment]
Good suggestion.
