### ISSUE TITLE
Readiness probes missing for gardener-apiserver

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#2633]
**How to categorize this issue?**

/area robustness
/area high-availability
/kind bug
/priority normal

**What happened**:
When the gardener-apiserver deployment is updated, the replicaset controller immediately deletes Pods of the old replicaset without waiting for the new Pods to be ready, which causes a (short) unavailability of the gardener API.
This is because `readinessProbes` are missing in the Pod template.

As HVPA updates the deployment spec directly to scale the gardener-apiserver vertically, this can happen often and not only when a new version is deployed.

**What you expected to happen**:
gardener-apiserver to be rolled smoothly without any downtime.

**How to reproduce it (as minimally and precisely as possible)**:
Change the resource requests of the `gardener-apiserver` deployment to trigger a rolling update and observe an unavailability during the rolling update.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.7.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
Thanks @ialidzhikov!

One additional thought, I had about this topic:
We could also configure `minReadySeconds` additionally to `readinessProbes` in the `gardener-apiserver` deployment.

**Comment by ialidzhikov** [comment]
I hit https://github.com/kubernetes/kubernetes/issues/93599. We should wait until the fix is merged in the k/k master and then cherry-picked into release-v1.17 (as we are currently vendoring `v0.17.9`) and finally vendored on our side.

**Comment by timebertt** [comment]
@ialidzhikov WDYT about the `minReadySeconds`?

**Comment by ialidzhikov** [comment]
> @ialidzhikov WDYT about the `minReadySeconds`?

Hm, as far as I see `minReadySeconds` is a delay to wait for a Pod to be ready without any of its containers crashing. But wouldn't be this handled when we introduce the readinessProbe - my assumption is that the rollout will wait until the readiness probe of the newly created Pod is successful (wait for `initialDelaySeconds` and for `successThreshold`) before marking as Ready.

**Comment by timebertt** [comment]
Yes, I think `minReadySeconds` is an additional delay before continuing with the rollout. So I guess your perception is right.
Do you think, it makes sense to add it?

**Comment by ialidzhikov** [comment]
> Yes, I think minReadySeconds is an additional delay before continuing with the rollout.

Ah, I now understand it. This would be useful if we have a case in which readiness probe is successful but despite that we want to delay the Pod to be ready for another `minReadySeconds`. Do we have such case?

**Comment by timebertt** [comment]
I don't know. I'm basically asking you this question, as you have already worked on this topic and might have a better feeling for it :)

**Comment by ialidzhikov** [comment]
My assumption is that `/readyz` endpoint will be good enough to determine the readiness of gardener-apiserver Pod. If it is not, we can track down potential issues with it.
