### ISSUE TITLE
fluent-bit not collecting logs from master nodes

### ISSUE THREAD

**Issue by einfachnuralex** [gardener/gardener#2638]
**How to categorize this issue?**
/area logging
/kind enhancement
/priority normal

**What would you like to be added**:
We are deploying Gardener with garden-setup to a initial cluster, which is deployed with kubeadm.
On that initial cluster there is a elasticsearch instance and fluent-bit daemonset deployed by the gardenlet.

The fluent-bit daemonset does not have a toleration for the taint effect 'NoSchedule' on master nodes.
Therefore there are no logs collected from master nodes.

Does it make sense to add this tolerations to the fluent-bit daemonset?

File: https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
```
tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/master
  operator: Equal
```

**Why is this needed**:
With that toleration we were able to collect logs from master node too, instead of only worker nodes.

**Comment by rfranzke** [comment]
@einfachnuralex I think it's reasonable, the colleagues are currently on vacation. Feel free to submit a PR if you want.

**Comment by einfachnuralex** [comment]
@rfranzke Thx, i've opened the PR #2671
