### ISSUE TITLE
Dynamic RESTMapper limited

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#2675]
**How to categorize this issue?**

/area control-plane
/area scalability
/kind bug
/priority normal

**What happened**:
If the `APIServerSNI` feature gate is disabled and Istio is not installed on the Seed, it can happen, that under high load, the Shoot reconciliation will fail, because the dynamic REST mapper of the Seed client is rate limited:
```
could not delete object of kind \“EnvoyFilter\” \“istio-ingress/shoot--foo--bar\“: too many API calls to the RESTMapper within a timeframe, could not delete object of kind \“Gateway\” \“shoot--foo--bar/kube-apiserver\“: too many API calls to the RESTMapper within a timeframe, could not delete object of kind \“VirtualService\” \“shoot--foo--bar/kube-apiserver\“: too many API calls to the RESTMapper within a timeframe
```

The problem is, that the dynamic RESTMapper returns a different error than the expected `NoKindMatchError` in that case (ref https://github.com/kubernetes-sigs/controller-runtime/issues/1120) and therefore, the `TolerateErrorFunc` can't catch it:
https://github.com/gardener/gardener/blob/514f00cbd32cc3022032376f48ebaf0f3ad0ed3e/pkg/operation/botanist/controlplane/kube_apiserver_sni.go#L76-L85

The same problem can hit us in the seed bootstrap here:
https://github.com/gardener/gardener/blob/514f00cbd32cc3022032376f48ebaf0f3ad0ed3e/pkg/operation/seed/istio/proxy_protocol.go#L50-L58
e.g:
```
seed is not yet ready: condition \"Bootstrapped\" has invalid status False (expected True) due to BootstrappingFailed: failed to delete manifests: 1 error occurred: could not delete object of kind \"VirtualService\" \"istio-ingress/proxy-protocol-blackhole\": too many API calls to the RESTMapper within a timeframe"
```

**What you expected to happen**:
The Shoot reconciliation/Seed bootstrapping should not block in that case and should just ignore the error, because it means, that the Istio stuff is anyways not installed.

**How to reproduce it (as minimally and precisely as possible)**:
Simultaneously create hundreds of Shoots? 😁 🤔 

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.8.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timuthy** [comment]
Can we work this out by passing a different rate limiter?

**Comment by timebertt** [comment]
Yes, we could. But that would also mean having more discovery requests and the question would be again, how many rps/burst is enough...
Another option for mitigating it on our side, would be to also ignore the `ErrRateLimited` error returned by the rest mapper.
I would prefer this option over increasing the rate limits, as the default rate limits should be enough, as we don't have a very dynamic set of API resources.

Nevertheless, I would prefer finding a solution upstream in c-r, so let's wait results in the linked issue :)

**Comment by timebertt** [comment]
ref https://github.com/kubernetes-sigs/controller-runtime/pull/1151
