### ISSUE TITLE
Prevent Cross-Cluster Volume Access

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener#268]
# Story
- As user I want that no other user from another cluster to mount my volumes even if they are in the same infrastructure account, so that my data remains private.

# Motivation
Security. We do not recommend that multiple shoot clusters for different owners are deployed into one single infrastructure account (this recommendation is also given by the cloud providers that we have consulted). However, it is possible to set up multiple clusters in one infrastructure account and even VPC if desired and then it is also possible to access volumes of foreign clusters (no other resource exposure is known yet).

# Acceptance Criteria
- [ ] It is no longer possible by specifying the volume ID in the PV to access other cluster's infrastructure volumes.

# Implementation Proposal
It appears that the issue can be solved with an admission controller that checks all PV requests and denies their creation/update if the volume tag doesn't match the cluster tag.

# Release Notes
``` operator release notes
- Volumes from other clusters can no longer be accessed by a different cluster.
```

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit tests are provided: Have you written automated unit tests?
- [ ] Integration tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added/changed public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the operations guide about ops-relevant changes?
- [ ] User documentation: Have you updated the READMEs/docs/how-tos about user-relevant changes?

**Comment by vlerenc** [comment]
@marwinski, this appears to be a duplicate of #178. Can we then close the other? Also, can't this be done in AWS via IAM alone (based on tags)? Azure, GCP and OpenStack are anyways far too open. Azure and OpenStack (until out-of-tree cloud providers in Kubernetes are done) still hold the IaaS credentials, so the door is anyways wide open.

**Comment by marwinski** [comment]
@vlerenc the solution outlined here will also be beneficial for other cloud providers although they might just be too open for this to work at all (I am not sure they really are and we also might see improvements here in the following months). I would not implement a cloud provider specific solution as there is one that works in a generic way and is not much more difficult to implement.

As for issue #178: this is about reducing the policies in the instance profile and is unrelated although also an issue in the shared account model. I will provide an update to the ticket.

**Comment by vlerenc** [comment]
Thanks, I can work with that and have sharpened the user story and added the release notes and DoD.

**Comment by vlerenc** [comment]
@marwinski Next time please be as specific as possible, otherwise the ticket will remain in limbo until it gets more clearly spec'ed out. Thanks!

**Comment by rfranzke** [comment]
How do we continue here? I doubt that this is something that belongs to the Gardener core. Isn't this rather something that someone might want to deploy optionally on top? I mean, the thing we want to forbid/restrict here is actually a Kubernetes feature on purpose.

**Comment by marwinski** [comment]
see https://groups.google.com/forum/#!topic/kubernetes-sig-auth/hD7b0qMlDaE

That was the argument there as well... If you want something like quota or preventing the problem described above there appears to be no other way.

**Comment by rfranzke** [comment]
Sure, I agree that an admission controller would be able to solve the issue. I rather wanted to motivate to not track the status of this task in the Gardener core repository as it doesn't belong to the core. It should be part of another component/security addon/...
