### ISSUE TITLE
Health status of VPA for shoots is not visible in the `ControlPlaneHealthy` condition

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#2685]
**How to categorize this issue?**

/area ops-productivity
/kind bug
/priority normal
/platform all
/exp intermediate
/topology garden seed

**What happened**:
When the VPA is enabled for shoots (`.spec.kubernetes.verticalPodAutoscaler.enabled=true`) then its health is not visible in the `ControlPlaneHealthy` condition, i.e., the shoot care controller does not check it. This leads to the fact that a broken VPA is hardly detected.

**What you expected to happen**:
The `ControlPlaneHealthy` condition for shoots should also reflect the health of the VPA.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot with VPA enabled, break it, and see the `ControlPlaneHealthy` condition to be unchanged.

- Gardener version: v1.8
- Kubernetes version (use `kubectl version`): all
- Cloud provider or hardware configuration: all

**Comment by timebertt** [comment]
Should we outsource the VPA stuff to a `ManagedResource`?
We already have code for checking MRs, so we can reuse that :)

**Comment by rfranzke** [comment]
Not sure, we don't do this for other control plane components as of now, so this would be inconsistent/confusing. I'd suggest to do it similar like it's done for other components now, and then refactor it if we think it makes sense.
