### ISSUE TITLE
VPA admission controller is sometimes not using the recommended resource limits

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#2688]
**How to categorize this issue?**

/area auto-scaling
/kind bug
/priority normal
/platform all
/exp expert
/topology seed

**What happened**:
We've seen occurrences in which the VPA admission controller was not using the resource limits recommended by the VPA Recommender when a new pod was created. Only a restart of the VPA admission controller helped (i.e., after the restart it was using the recommended limits). Could it be related to stale caches? What can we do to workaround this problem on our side, i.e., to automatically resolve such situations without the necessity to manual ops interference. 

/cc @wyb1 @ggaurav10 @amshuman-kr 

**What you expected to happen**:
VPA admission controller should behave correctly.

**How to reproduce it (as minimally and precisely as possible)**:
No concrete steps as of now, sorry. Needs to be investigated.

- Gardener version: v1.8
- Kubernetes version (use `kubectl version`): v1.16.11 (seed cluster)
- Cloud provider or hardware configuration: all

**Comment by rfranzke** [comment]
Interesting: https://github.com/kubernetes/autoscaler/issues/2633

**Comment by amshuman-kr** [comment]
@rfranzke I don't recall this being too frequent earlier. Is this something that has become more frequent with recent shoot VPA changes?

Even [kubernetes/autoscaler#2633](https://github.com/kubernetes/autoscaler/issues/2633) talks about webhook config issues, and unfortunately, even the resolution ([kubernetes/autoscaler#2738](https://github.com/kubernetes/autoscaler/issues/2738)) will only result in VPA updater backing off if admission controller is down. That is certainly better than evicting pods continually but the ideal solution would still be to fix the webhook config. WDYT?

**Comment by rfranzke** [comment]
I also just saw it once last week Friday. Agreed, though, I'm not sure whether it's indeed related to the webhook config. I didn't check it, unfortunately, maybe it was indeed gone, but if so, I don't know why this should have happened.

**Comment by amshuman-kr** [comment]
Understood. Anyway, the case you mentioned in the issue text mentions restarting the admission controller pod restart which is different from a problem with the webhook config. So, something else also seems to be a problem too. Stale cache might be a problem which I saw with kupid too.

**Comment by rfranzke** [comment]
Hm, but doesn't the VPA admission controller register the webhook on start-up again?

**Comment by amshuman-kr** [comment]
> Hm, but doesn't the VPA admission controller register the webhook on start-up again?

Yes. But by _webhook config issue_ I didn't just mean only issue with the `MutatingWebhookConfiguration` but general connectivity issue from apiserver to the webhook which may not necessarily be solved by a pod restart. But in your case, a restart did solve the problem.

**Comment by rfranzke** [comment]
OK, I don't think we have a clear path forward and not enough information to get to the bottom of it. From the symptoms, it sounds very much like the webhook configuration was missing. Anyways, let's then close this issue and reopen as appropriate?
