### ISSUE TITLE
E2E test for deleting a shoot that wasn't reconciled with the new Gardener version yet

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#2692]
**How to categorize this issue?**

/area quality
/kind test
/priority normal

**What would you like to be added**:
We should add an integration test that tries to delete a `Shoot` that wasn't reconciled with the new Gardener versions yet.

**Why is this needed**:
Sometimes we add new functionality in the reconciliation flow that is also required by the deletion flow. However, not always the necessary code is also added to the deletion flow, i.e., when a shoot gets deleted without being reconciled first it might fail as certain assumptions don't hold true (see https://github.com/gardener/gardener/pull/2681).
An integration test for such case would be very helpful to detect such issues.

Disclaimer: In order to properly write such an integration test we need to be able to dynamically setup a new Gardener version. We agreed that we won't do it with the current garden-setup, thus, we'll first invest into a new deployment model with the landscaper (cc @dguendisch @schrodit) before tackling the mentioned integration test.

**Comment by timebertt** [comment]
Ref #1564

**Comment by rfranzke** [comment]
Another reason why we need this: https://github.com/gardener/gardener/issues/6961

**Comment by rfranzke** [comment]
@seshachalam-yv Can you explain your plans here? Which kind of upgrade scenarios are you working on?

**Comment by seshachalam-yv** [comment]
My plan is to add gardener upgrade tests by leveraging g/g e2e shoot creation test framework.

**Summary of my plan**

* Create a kind cluster non-HA/HA-single-zone/HA-multi-zone
* Install gardener `v1.x.x`
* Run Pre-upgrade tests (filter by label `pre-upgrade`)
> **Gardener upgrade Tests for Shoot::test-1 when Pre-upgrade (version:'`v1.x.x`')**
>- should create a shoot [gardener, pre-upgrade]
>- should hibernate a shoot [gardener, pre-upgrade] 
>- should delete PVC, to trigger etcd restoration after gardener upgrade [gardener, pre-upgrade, etcd
>-------------------------------


> **Gardener upgrade Tests for Shoot::test-2: when Pre-upgrade (version:'`v1.x.x`')**
>- should create a shoot [gardener, pre-upgrade]
>- deploying zero-downtime validator job to ensure no downtime while after upgrading gardener [gardener, pre-upgrade, high-availability]
>- ------------------------------

> **Gardener upgrade Tests for Shoot::test-3 when Pre-upgrade (version:'`v1.x.x`')**
>-  should create a shoot [gardener, high-availability, pre-upgrade]
> - ------------------------------


* **Install gardener `v1.y.y`**
* **Run Post-upgrade tests (filter by label `post-upgrade`)**

> **Gardener upgrade Tests for Shoot::test-1 when Post-upgrade (version:'`v1.y.y`')**
> - should be able to wake up a shoot which was hibernated in previous gardener release [gardener, post-upgrade]
> - should restore etcd when etcd node got corrupted in previous gardener release [gardener, post-upgrade, etcd]
> - should delete a shoot which was created in previous gardener release [gardener, post-upgrade]
> - ------------------------------

> **Gardener upgrade Tests for Shoot::test-2: when Post-upgrade (version:'`v1.y.y`')**
> - should be able to restore etcd when etcd pod's pvc is corrupted in previous gardener release: [gardener, post-upgrade, etcd]
> - verifying no downtime while upgrading gardener [gardener, post-upgrade, high-availability]
> - should able to delete a shoot which was created in previous release [gardener, post-upgrade, delete]
> - ------------------------------

> **Gardener upgrade Tests for Shoot::test-3 when Post-upgrade (version:'`v1.y.y`')**
> - should be able to upgrade a non-HA shoot which was created in previous gardener release to HA with failure tolerance type 'zone' [gardener, high-availability, post-upgrade]
> - should be able to delete a shoot which was created in previous gardener release [gardener, high-availability, post-upgrade]
> - ------------------------------

* **Uninstall gardener**
* **Delete kind cluster**

By these test cases, we can ensure all the shoot states are verified with new gardener version.

Based on need or while cutting a g/g Release we can run prow jobs to ensure there is no compatible issue while upgrading with previous g/g release version.

As the first step, I will raise PR with one simple test case and will setup infra and by this way review will be easy.
> **Gardener upgrade Tests for Shoot::test-2: when Pre-upgrade (version:'`v1.x.x`')**
>- should create a shoot [gardener, pre-upgrade]

> **Gardener upgrade Tests for Shoot::test-2: when Post-upgrade (version:'`v1.y.y`')**
> - verifying no downtime while upgrading gardener [gardener, post-upgrade, high-availability]
> - should able to delete a shoot which was created in previous release [gardener, post-upgrade, delete]

We can introduce three more targets to makefile
- `ci-e2e-gardener-upgrade-kind`
- `ci-e2e-gardener-upgrade-kind-ha-single-zone`
- `ci-e2e-gardener-upgrade-kind-ha-multi-zone`

Then next step, I will define prow jobs.

Will add remaining test cases once initial PRs got merged.

cc: @ashwani2k  @rfranzke @shreyas-s-rao
