### ISSUE TITLE
Gardenlet crashed with `concurrent map writes`

### ISSUE THREAD

**Issue by dguendisch** [gardener/gardener#2697]
**How to categorize this issue?**

/kind bug
/priority normal

**What happened**:
I just observed gardenlet crashing with `fatal error: concurrent map writes`

[gardenlet_crash_dump.txt.zip](https://github.com/gardener/gardener/files/5050821/gardenlet_crash_dump.txt.zip)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.7.4
- Kubernetes version (use `kubectl version`): 1.15.11
- Cloud provider or hardware configuration: aws (seed)
- Others:

**Comment by timebertt** [comment]
TBH, I have no clue on this issue.
I starred at the stacktrace, digged into the code and went through gh issues for the last 1,5 hours, but so far I have absolutely no idea why this might have happened.
Let's come back to this, when we see it happening again.

/unassign
/remove status/in-progress
