### ISSUE TITLE
Investigate ALB Ingress (In Contrast to NGINX Ingress)

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#27]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:45 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/45_

----

Investigate https://coreos.com/blog/alb-ingress-controller-intro. Is it any good? Can it replace nginx ingress on AWS as the more natural and IaaS-specific solution? What impact on costs will it have? Would you advise to switch to it? Please report results here.

Background: Vasu suggested to investigate into the subject in https://git.infra.removed/kubernetes/landscape-template/issues/4. See comments there. Basically, we must weight optimised support for individual infrastructures against the time we need for research, implementation and maintenance of optimised IaaS-specific solutions while we have no issue with the general purpose solution we have right now.

:information_source: Migrated from Jira issue [KUBE-111](https://jtrack.removed/browse/KUBE-111)

**Comment by vlerenc** [comment]
With the enlarged multi-cloud support we have today, it seems unlikely we can work on this topic anytime soon.
