### ISSUE TITLE
☂️-Issue for '--version' flag

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2703]
**How to categorize this issue?**

/area usability
/area ops-productivity
/kind enhancement
/priority 3

**What would you like to be added**:
The imagevector overwrite pkg is widely used in g/g and allows overwrite of images with digest (for example `image@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2`). This can cause issues for operator while investigating issues on the landscapes as it is not trivial to correlate the `digest` to the appropriate `tag` (and then to the appropriate version of the binary inside).

There are even cases in which `docker inspect` is not helping and does not show tags associated with the digest. And it takes quite a lot of time for a such small thing - understand the binary version behind the docker image by digest.

To deal with similar issues, we can add a `--version` flag for each component.

It seems to be a practice for k/k or kubernetes-sigs images:

```
$ docker run k8s.gcr.io/kube-apiserver:v1.18.6 kube-apiserver --version
Kubernetes v1.18.6

$ docker run coredns/coredns:1.7.0 --version
CoreDNS-1.7.0
linux/amd64, go1.14.4, f59c03d

$ docker run mcr.microsoft.com/k8s/csi/azuredisk-csi:v0.8.0 --version
Build Date: "2020-08-10T02:31:06Z"
Compiler: gc
Driver Name: disk.csi.azure.com
Driver Version: v0.8.0
Git Commit: 37a0784fbee9a141fc1bed2d26a1196d664f5d6b
Go Version: go1.13.10
Platform: linux/amd64
Topology Key: topology.disk.csi.azure.com/zone

```

And the list continues...

On the other side for our images:

```
$ docker run eu.gcr.io/gardener-project/gardener/gardener-resource-manager:v0.16.0 --version
Error: unknown flag: --version
Usage:
  gardener-resource-manager [flags]

  # help omitted

$ docker run eu.gcr.io/gardener-project/gardener/apiserver:v1.8.0 --version
Error: unknown flag: --version
Usage:
  gardener-apiserver [flags]

  # help omitted
```

**List of components:**
- [x] Gardener core components -> https://github.com/gardener/gardener/pull/3040
- [x] gardener-extension-provider-alicloud -> https://github.com/gardener/gardener-extension-provider-alicloud/pull/247
- [x] gardener-extension-provider-aws -> https://github.com/gardener/gardener-extension-provider-aws/pull/525
- [x] gardener-extension-provider-azure -> https://github.com/gardener/gardener-extension-provider-azure/pull/469
- [x] gardener-extension-provider-gcp -> https://github.com/gardener/gardener-extension-provider-gcp/pull/414
- [x] gardener-extension-provider-openstack -> https://github.com/gardener/gardener-extension-provider-openstack/pull/426
- [x] gardener-extension-runtime-gvisor -> https://github.com/gardener/gardener-extension-runtime-gvisor/pull/38

**Comment by rfranzke** [comment]
@ialidzhikov Can you outline what is missing for this issue or whether we still want to pursue it?

**Comment by ialidzhikov** [comment]
I think we can close now as all gardener components and "main" provider extensions do now support the `--version` flag. The maintainers for the other extensions (networking and OS extensions) can consider to add similar support if they see the need for it.

/close

**Comment by rfranzke** [comment]
Nice, thanks for driving @ialidzhikov!
