### ISSUE TITLE
Additional annotations for shoot components

### ISSUE THREAD

**Issue by wiegandf** [gardener/gardener#2705]
**How to categorize this issue?**
/area ops-productivity
/area monitoring
/kind enhancement
/priority normal

**What would you like to be added**:
It would be nice to have the option to specify additional annotations for shoot components. I guess we would need to extend https://github.com/gardener/gardener/tree/master/charts/shoot-core/components/charts and https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml. 
It should be possible to specify different annotations for each component.

**Why is this needed**:
We collect kube-system logs with fluent-bit. Unfortunately, they're not parsed correctly and thus, we can't set up alerts based on log level. We would like to use https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#annotation-examples-in-pod-definition also for gardener managed components in kube-system namespace and therefore require the option to specify additional annotations.

**Comment by rfranzke** [comment]
Thanks for opening the issue. I just want to add a quick thought: We might add/remove system components running in the `kube-system` namespace in the shoot clusters on the fly (e.g., based on certain configuration in the `Shoot` specification), or with new Gardener versions. Especially the second point might be somewhat critical as end-users themselves don't control the rollout of updates imposed by new Gardener versions. This means that new components might "suddenly" appear for which no annotations were presented. Opinions?
I'd be more happy with not exposing the annotations **per component** but rather one set of annotations put to all components, but I guess this wouldn't be too helpful for you/your use-case?!

**Comment by wiegandf** [comment]
Hi, I see your point. As you said, it wouldn't be very helpful for our use-case.
I think a set of annotations to put on all components is nice - and couldn't we extend the charts to use per component annotations as well if they are specified? 
Of course, when new components are added, they will miss the component specific annotations.

**Comment by rfranzke** [comment]
/close since this issue is open since a long time without anyone picking it up or any attention at all.

Edit: Such annotations/labels/whatever modifications seem to be required only for very specific use-cases and can be achieved by having mutating webhooks with the `gardener.cloud/role=system-component` label selector.
