### ISSUE TITLE
Refactor Node Bootstrap for worker nodes with CRI

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#2719]
**How to categorize this issue?**

/area os
/area security
/kind enhancement
/priority normal

**What would you like to be added**:

Remove the usage of the `docker` CLI during the Node bootstrap but use the CRI instead.
For worker pools that use CRI, this remove the dependency to `docker` altogether.

**CRI enabled worker pools currently require docker**:

Shoot worker pools can specify to use a CRI based container manager such as containerd instead of the default docker container runtime.

As a prerequisite to enabling CRI, the OS image (e.g AWS AMI) needs to have both docker and the CRI container manager preinstalled.

Docker is required because Gardener is using it for several fundamental tasks during the node bootstrap process
 - [Pull the Hyperkube OCI image](https://github.com/gardener/gardener/blob/baa5c6489dfb720597975e2c909af7c7ce595b7a/charts/shoot-cloud-config/templates/scripts/_cloud-config-script.sh#L21)
 - [Extract the kubectl from the OCI image](https://github.com/gardener/gardener/blob/cc33eb85338dfdfc42052ebf5d71cbc9f28657a8/charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet-monitor.service#L15-L14)
 - [Extract kubelet from the OCI image](https://github.com/gardener/gardener/blob/51634b550b0819af24d2dd1a08d5a15288b48d46/charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet.service#L25) 
 
 As a consequence, OS-Extensions such as [os-gardenlinux](https://github.com/gardener/gardener-extension-os-gardenlinux), always [have to enable the docker systemd service](https://github.com/gardener/gardener-extension-os-gardenlinux/blob/9dd9612d1514308f5a7f3c11d115f5bee9bd6891/pkg/generator/templates/cloud-init.gardenlinux.template#L46)

**Why is this needed**:

 - Always requiring Docker increases the OS image size: always required to contain docker packages for bootstrapping purposes rather than only containing the actual container runtime used to run the container.
  - Images with both docker and the CRI can still be offered for convencience reasons 
- Unwanted resource consumption by running `dockerd` daemon process on the host. 
  ```
  root       13320  0.1  1.7 804580 95004 ?        Ssl  Aug10   3:17 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
  ```
  - with a non-representative memory overhead of ~800 MB
   ```
   pmap 13320 | tail -n 1
   total           804584K

   ```
  - The docker daemon could be removed after the initial bootstrapping, but this is not implemented and also requires additional effort. It is better to get rid of it in the first place.

- Getting rid of the `dockerd` daemon process (any process for that sake) running with root permissions decreases [potential security vulnerabilities](https://www.cvedetails.com/vulnerability-list/vendor_id-13534/product_id-28125/Docker-Docker.html).

**Proposal details**

Kubernetes has since the [introduction of the Container Runtime Interface](https://kubernetes.io/blog/2016/12/container-runtime-interface-cri-in-kubernetes/) (CRI)  moved to CRI as the standard way of container managers to integrate with the kubelet.
The CRI is used by the Kubelet to interact with each container manager in the same fashion - no matter the underlying implementation.

The proposal is to replace the `docker` functionality used in the node bootstrapping process, with calls to the CRI interface implemented usually via a Unix Domain Socket (UDS). 
Docker would not be required any more to bootstrap Shoot worker nodes with CRI enabled. 
To be clear, the current bootstrapping process for worker pools that use the `docker runtime` will still uses the `docker` CLI for bootstrapping.

Gardener can leverage this concept to create a bootstrapping process that works for all CRI enabled container managers alike. 
An OS preinstalled client can interact with the CRI implementation at a predefined socket (e.g. `/run/containerd/containerd.sock` for containerd) to fulfil the steps required for the bootstrapping process.
These are essentially the same as previously done with the `docker` CLI (see above) - only doing the same with the CRI instead.
As a client implementation, the tool [crictl](https://github.com/kubernetes-sigs/cri-tools) can be used. 
This tool is a Kubernetes incubator project, regularly maintained for each Kubernetes / CRI release and seems to be adopted also by the major cloud providers.

**Comment by rfranzke** [comment]
FYI: Docker support in the kubelet is deprecated with Kubernetes v1.20, see https://github.com/kubernetes/kubernetes/pull/94624.

**Comment by danielfoehrKn** [comment]
I played around with `crictl` last year to create a bootstrapping mechanism that works independently of the CRI implementation. 

That works if `crictl` is preinstalled on the OS which was not well received.

Alternatively, you can use 
- `ctr`  which comes as standard for each `containerd` installation but has the drawback that it is an unsupported debug client.
- Use [`nerdctl` ](https://github.com/containerd/nerdctl/releases) and require it to be also preinstalled in the OS
