### ISSUE TITLE
Update shoot.gardener.cloud/tasks once the step is completed

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2742]
**How to categorize this issue?**

/area robustness
/kind enhancement
/priority normal

**What would you like to be added**:
Currently `shoot.gardener.cloud/tasks` annotations helps keeping track of "tasks" that need to be performed during the reconcile of a Shoot for example (`shoot.gardener.cloud/tasks='deployInfrastructure,restartControlPlanePods'`. Currently the annotation is updated at the end of the reconciliation flow. Which means that for example if Shoot is stuck for hours on waiting until worker is ready, then each reconcile/retry will execute the tasks again and again (for example `deployInfrastructure`, `restartControlPlanePods`). In some cases this can be undesired as for example restarting controlplane pods contributes to the cloud provider rate limit.
Generally we can remove the task, once the step associated with this task is completed successfully.

**Why is this needed**:
To prevent given task to be executed "n" times.

**Comment by vlerenc** [comment]
Thanks @ialidzhikov, I just wanted to open a similar ticket myself, but saw yours.

Can we please increase the priority as it had some impact on today's problems. I am not sure how much it interfered, but it certainly only increased the rate throttling issues by restarting "expensive" controller components again and again (resync against the infrastructure itself), not even speaking of interrupting ongoing operations.

/priority critical
