### ISSUE TITLE
☂️-Issue for unit/integration tests in the extensions library

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#2751]
**How to categorize this issue?**

/area dev-productivity robustness quality testing
/kind enhancement
/priority normal

**What would you like to be added**:
This is an umbrella issue for improving our unit test coverage in our extensions library ([`extensions` directory](https://github.com/gardener/gardener/tree/master/extensions)).
We lack unit and/or integration tests at too many places and should improve this. One important pain point is that we sometimes detect issues in the library only after revendoring it in an actual extension implementation (e.g., provider-aws). This results in additional work and effort that could be avoided by having good tests in the first place.

This issue lists the potential areas where we should improve:
- [x] ~~Unit tests for the generic worker actuator (https://github.com/gardener/gardener/tree/master/extensions/pkg/controller/worker/genericactuator)~~ (we don't want to invest here because we would rather like to rework/redesign the worker controller)
- [x] Dummy implementation of an extension controller (e.g., in `g/g/extensions/test`) which tests the basic controller flows and APIs of the extension library, potentially by leveraging https://sigs.k8s.io/controller-runtime/pkg/envtest
- ... (to be extended)

**Comment by timebertt** [comment]
In addition to the mentioned tests we could
- [x] make use of [go-apidiff](https://github.com/joelanford/go-apidiff) to easily detect breaking changes in signatures of the extensions library (see https://github.com/kubernetes-sigs/controller-runtime/blob/master/hack/apidiff.sh for an example usage) -> tracked in https://github.com/gardener/gardener/issues/5301

**Comment by timebertt** [comment]
We should definitely
- [x] add missing unit tests for the predicates provided by the extensions library (e.g. [`AddTypePredicate`](https://github.com/gardener/gardener/blob/092922b5765ad5e84cc93a40c87c5a80e5841023/extensions/pkg/predicate/predicate.go#L164) is untested but used in all extension controllers) ->tracked in https://github.com/gardener/gardener/pull/6249

**Comment by timebertt** [comment]
We need integration tests for
- [ ] the extension webhooks (start a manager, register webhooks using the extensions library, do some dummy mutations, assert that they are applied, ...)

Currently there's no way of telling if a change to the webhook library code will break something there (ref https://github.com/gardener/gardener/pull/3393#issuecomment-760014129).

**Comment by acumino** [comment]
> In addition to the mentioned tests we could
> 
> * [x]  make use of [go-apidiff](https://github.com/joelanford/go-apidiff) to easily detect breaking changes in signatures of the extensions library (see https://github.com/kubernetes-sigs/controller-runtime/blob/master/hack/apidiff.sh for an example usage)

For cross-reference - https://github.com/gardener/gardener/issues/5301

**Comment by rfranzke** [comment]
@ary1992 Are you still working on this?

**Comment by ary1992** [comment]
> @ary1992 Are you still working on this?

Not for now. Can we add a list of components for which tests need to be written?

**Comment by rfranzke** [comment]
As part of this issue, the only open topic seems to be the one reported in https://github.com/gardener/gardener/issues/2751#issuecomment-760015754

**Comment by ialidzhikov** [comment]
/unassign
as I also don't have capacity to start looking into this issue

**Comment by rfranzke** [comment]
It seems we will not find the capacity for actively working on this. Given that we don't have any real issues, I suggest to add the missing tests when we touch the code next time. Generally, we might want to overhaul the extensions library as such anyways, but that's a different story.
/close
