### ISSUE TITLE
Restrict Access to Metadata Service by Default

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener#276]
# Story

As a cluster administrator I want to provide clusters to my users which are secure by default and that don't leak any information that an attacker can use who is running code in the cluster. Access to the metadata service may compromise security as well as my leak information.

# Motivation

Although we tell our users of the impact of the metadata service and how to prevent possible dangers they might forget or ignore the advice making their solutions potentially vulnerable. There is also a problem as the metadata service is located on different IP addresses (e.g. 100.100.100.200 on Alibaba, 169.254.169.254 on AWS and OpenStack, metadata.google.internal on google)  that our users cannot envision. In the interest of security by default we shall deny access to pods by default. A cluster administrator who wants to re-enable access to the metadata service can do so at his own risk.

# Implementation Options

There are several options to shut down network communication with the metadata service that need to be evaluated prior to implementation. It is not possible to deploy a single or multiple network policies that would deny access to the metadata service. These are the options that have been discussed so far:

1. Use one of the following of a similar service to control to the metadata service:

- https://github.com/jtblin/kube2iam
- https://github.com/uswitch/kiam
- https://github.com/GoogleCloudPlatform/k8s-metadata-proxy

Personally I doubt that this is a good idea as the main purpose of these services appears to be to provide some kind of credentials and to prevent access is only a minor functionality (if at all).

2. Use a Webhook to add a network policy whenever a new namespace is created. 

This would include adding network policies for the kube-system and default namespaces at the time when the cluster is created. Deployment of this Webhook could be configured in the shoot manifest.

3. Deploy iptables rules during cloud init that deny traffic to the metadata service for pods

This is probably the easiest and most straightforward solution. As a downside however it would make it much more difficult for cluster administrators to remove these rules. This could be configured in the shoot manifest.

4. Deploy a Daemon set 

It appears possible to deploy a deamon set that would start a pod on each newly created node. From this pod the iptables rules could be deployed once that prevent traffic to the metadata service from pods.

5. An approach we haven't thought of so far 

...

Personally my favorite would be 2 above.

# Notes

- It is currently unknown whether the above mechanisms would prevent pods with `hostNetwork=true` to access the metadata service - we suspect not. 
- Keep in mind that the kubelet must be able to access the metadata service.

# Acceptance Criteria

- [ ] Knowledge is distributed: Have you spread your knowledge?
- [ ] ´The investigation is documented and a reason is given for the selected approach
- [ ] Limitations are documented
- [ ] A new issue is created which describes the implementation approach

**Comment by bergerx** [comment]
Since calico is used in `Shoot`s, could the Calico's Global Network Policy Resource be an option:
 https://docs.projectcalico.org/v3.1/reference/calicoctl/resources/globalnetworkpolicy 
Note that the Global Network Policy is a Calico specific resource and won't work for any other kubernetes network implementations.

**Comment by vlerenc** [comment]
Wow, @bergerx, I didn't know of that, thank you, that may indeed be the solution for our Calico-run clusters!

**Comment by vlerenc** [comment]
@mvladev, @alban, @dkistner, @marwinski, @swapnilgm, @amshuman-kr would you agree as well, that this would be the simplest solution to restrict access to the metadata service the fastest?

**Comment by mvladev** [comment]
@vlerenc @bergerx yes `GlobalNetworkPolicy` makes sense for the Shoot

**Comment by rfranzke** [comment]
Can this one be closed as it will probably be covered by the security addon planned by @marwinski, @alban and @schu?

**Comment by pranjaljain** [comment]
@rfranzke where can I see the status for planned security addon? 
Just wanted to know whether this issue related to access to metadata service is resolved or not?

**Comment by rfranzke** [comment]
I don't know, please reach out to @marwinski @alban and @schu.
The issue is closed because restricting access to metadata service from shoots is not part of Gardener core scope (consequently, not done).

**Comment by marwinski** [comment]
This functionality has been implemented in the security add-on which we plan to make public, however we don't have a timeline for this now.
