### ISSUE TITLE
Collect and expose Shoot alerts by the Gardener

### ISSUE THREAD

**Issue by dkistner** [gardener/gardener#277]
As a Shoot operator I want to be able to see the firing/pending/resolved alerts, which are referring my cluster, on a central place for example in the Gardener Dashboard.  =As Gardener operator I want to be able to see all Shoot alerts on a central place, for example in a Grafana Dashboard. As an enduser I want to have more transparency of my Shoot clusters health.

**Background**
Each Shoot has an own Prometheus instance, which monitors the clusters control plane, infrastructure and parts of its workload. The alerts for the Shoot are also triggered by this Prometheus instance and then pushed to its corresponding alertmanager instance to deliver the alert to its receivers. The only way to see a list of all active alerts is accessing the Shoots Prometheus directly. 

An Enduser has no option to see the active alerts at all. May that's also not required, but to have more detailed health information as only the conditions and the last operation state, would also be a benefit for the enduser and provides more transparency to the user.

**Implementation proposal**
The Gardener have the care controller, which collects already cluster conditions. The care controller could also query the Prometheus of the Shoot for active alerts and attach them to the status of the Shoot resource.

**Comment by rfranzke** [comment]
Do you still plan to implement this in the next time?

**Comment by dkistner** [comment]
Good question I have not planned to implement this soon. I would rather raise the question if we still need this, because we have meanwhile end user facing monitoring and could display a list with user related alerts there. 

On the other hand side we could not display the active alerts in the Gardener dashboard without these conditions (except if the dashboard queries Prometheus by their own). If we decide to introduce a condition with alert states then we would need to consider that alerts with different scopes exist (`users` and `operators`).

@rfranzke , @vlerenc WDYT?

**Comment by vlerenc** [comment]
We plan to expose Prometheus to the end user. That will alleviate the need for this a lot. On the other hand, looking with the eyes of an end user, wouldn't you agree that seeing a green cluster in the UI and active alerts in Prometheus give an inconsistent impression? Considering this, I would think it's interesting (medium priority) to have that in the shoot resources and consequently in the Dashboard.

**Comment by rfranzke** [comment]
@dkistner @wyb1 what's the plan here?

**Comment by rfranzke** [comment]
@dkistner @wyb1 can you please give an update?

**Comment by rfranzke** [comment]
/close
due to inactivity and no concrete plans - kindly reopen when it becomes relevant again
