### ISSUE TITLE
Cannot remove worker pool when Shoot is hibernated

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2784]
**How to categorize this issue?**

/area quality ops-productivity
/kind bug
/priority normal

**What happened**:
Currently Shoot reconciliation gets stuck when a worker pool of hibernated Shoot cluster is removed.

**What you expected to happen**:
Shoot reconciliation to do not stuck.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create Shoot with 2 worker pools

2. Hibernate the Shoot

3. After successful hibernation, delete one of the worker pools

4. Ensure that Shoot reconciliation hangs forever at step `Waiting until shoot worker nodes have been reconciled`

There is no machine-controller-manager Pods in the control plane.
```
$ k -n shoot--foo--bar get po
No resources found in shoot--foo--bar namespace.
```

But the provider extension waits forever unwanted machine deployments to be deleted:

```
{"level":"info","ts":"2020-08-27T06:50:58.463Z","logger":"aws-worker-actuator.worker-actuator","msg":"Waiting until unwanted machine deployment is deleted: shoot--foo--bar-cpu-worker2-z1 ...","worker":"shoot--foo--bar/bar"}

{"level":"info","ts":"2020-08-27T06:51:03.463Z","logger":"aws-worker-actuator.worker-actuator","msg":"Waiting until unwanted machine deployment is deleted: shoot--foo--bar-cpu-worker2-z1 ...","worker":"shoot--foo--bar/bar"}
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.9.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by prashanth26** [comment]
Okay, that explains the cause for the canary issue. Let us look into this one. cc: @hardikdr @AxiomSamarth .
