### ISSUE TITLE
'VPN Connection' tile shows always 'No data'

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2787]
**How to categorize this issue?**

/area monitoring
/kind bug
/priority normal

**What happened**:
'VPN Connection' tile shows always 'No data'.

**What you expected to happen**:
To have a tile that shows data or to do not have a tile at all.

**How to reproduce it (as minimally and precisely as possible)**:
1. Navigate to the grafana of a random Shoot

2. Ensure that the `VPN Connection` tile in the `VPN` dashboard shows always `No data`

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.9.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
@wyb1 , @istvanballok did you managed to check this issue?

**Comment by wyb1** [comment]
I will take a look tomorrow at what causes this and see how to fix it
