### ISSUE TITLE
Change generate_monitoring_docs script

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener#2790]
**How to categorize this issue?**

/area monitoring
/kind enhancement
/priority normal

**What would you like to be added**:
The [generate_monitoring_docs](https://github.com/gardener/gardener/blob/master/.ci/generate_monitoring_docs) script should call the `MonitoringConfiguration` function introduced in #2783 and produce the documentation based on that output.

**Why is this needed**:
With the introduction of #2783 some of the monitoring alerts will be generated with go instead of existing as `.json` files. This will make the current implementation of the [generate_monitoring_docs](https://github.com/gardener/gardener/blob/master/.ci/generate_monitoring_docs) script not generate the docs for all alerts (some alerts will exist as `.json` files and others will be generated with go).

**Comment by rfranzke** [comment]
@wyb1 Do you still plan to tackle this issue or shall we close it?

**Comment by wyb1** [comment]
We can close the issue
