### ISSUE TITLE
livenessProbe and readinessProbe for metrics-server

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2794]
**How to categorize this issue?**

/area monitoring
/kind enhancement
/priority normal

**What would you like to be added**:
metrics-server is an extension apiserver and as such it should respond to the endpoints `/readyz`, `/livez` and `healthz`. Currently we don't have defined a livenessProbe or a readinessProbe for the metrics-server deployment - https://github.com/gardener/gardener/blob/v1.9.0/charts/shoot-core/components/charts/metrics-server/templates/deployment.yaml.
Is there a reason (known issue/drawback) for not having the probes?

**Why is this needed**:
Minimize metrics-server unavailability.

**Comment by ialidzhikov** [comment]
It seems that the `/healthz` endpoint of the metrics-server is dependent to kube-apiserver avialability. In this issue https://github.com/kubernetes-sigs/metrics-server/issues/540 there are statements like `/healthz never recovers from failed state`. I also played locally with liveness and readiness probes on metrics-server and `/healthz` for sure fails when the apiserver is down. We for sure don't want `metrics-server` Pod in CrashLoopBackOff because of failing livenessProbe after a short apiserver downtime.
There is an open issue for improving the probes - https://github.com/kubernetes-sigs/metrics-server/issues/542.

**Comment by rfranzke** [comment]
@vpnachev shall we close this issue now?

**Comment by vpnachev** [comment]
No, we should switch to `/livez` and `/readyz` once https://github.com/kubernetes-sigs/metrics-server/issues/540 is fixed.

**Comment by serathius** [comment]
Version v0.4.0 was released.

**Comment by ialidzhikov** [comment]
Fixed with #3174.

/close
