### ISSUE TITLE
Missing events on AWS while watching k8s resources

### ISSUE THREAD

**Issue by Haegi** [gardener/gardener#2811]
**How to categorize this issue?**
/area networking
/kind bug
/priority normal

Tagging my team: @modulo11, @loewenstein, @phil9909

**What happened**:
When creating a pod with the istio sidecar and start watching resources, we do not receive any new events although the connection is still open.

Expected results:
```bash
$ kubectl logs -n test test-with-istio-fix test --timestamps
2020-09-01T13:09:27.563548430Z NAME                 DATA   AGE
2020-09-01T13:09:27.563594665Z istio-ca-root-cert   1      6s
2020-09-01T13:09:27.563599309Z test-map             1      6s
2020-09-01T13:13:20.692419620Z test2                0      0s
2020-09-01T13:13:27.107443087Z test2                0      7s
2020-09-01T13:29:49.764715205Z test2                0      0s
2020-09-01T13:29:49.867100083Z test2                0      0s
```
The last two entries are important here and missing in the actual result.

Actual results:
```bash
$ kubectl logs -n test test-with-istio test --timestamps
2020-09-01T13:09:31.114018235Z NAME                 DATA   AGE
2020-09-01T13:09:31.114058482Z istio-ca-root-cert   1      10s
2020-09-01T13:09:31.114074206Z test-map             1      10s
2020-09-01T13:13:20.692378964Z test2                0      0s
2020-09-01T13:13:27.107461449Z test2                0      7s
```
As you can see, the `test-with-istio` pod misses the event which occurred at around `13:29:49`

**What you expected to happen**:
Receiving new events is still happening. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Create appropriate k8s cluster
1. install `istio` with `istioctl install`
1. run `kubectl apply -f`[test.yaml](https://github.com/gardener/gardener/files/5167756/test.yaml.txt)
   - The pod `test-with-istio` might restart once. This is because of the race between starting `istio-proxy` and `test` container.
1. run `kubectl create configmap -n test test2 ; kubectl delete configmap -n test test2`
1. wait 15 minutes
1. run `kubectl create configmap -n test test2 ; kubectl delete configmap -n test test2` again
1. check logs `kubectl logs -n test test-with-istio test --timestamps` and `kubectl logs -n test test-with-istio-fix test --timestamps`
   - The pod with the fix should still show the create and delete event, but the pod without the fix (might) not show it.
   - The pod with the fix might have been auto-restarted by k8s.

**Anything else we need to know?**:
Current workaround:
Remove the pod from the service mesh and redirect traffic to it directly via the `traffic.sidecar.istio.io/excludeOutboundIPRanges` annotation.

**Environment**:
| Cloud Provider             | Istio Version |             Result |
| -------------------------- | :-----------: | -----------------: |
| Gardener AWS (k8s 1.16.12) |     1.6.8     |                :x: |
| Gardener AWS (k8s 1.18.5)  |     1.6.8     |                :x: |
| Gardener AWS (k8s 1.18.5)  |     1.7.0     |                :x: |
| Gardener GCP (k8s 1.16.12) |     1.6.8     | :white_check_mark: |
| Plain AWS EKS (k8s 1.16)   |     1.6.8     | :white_check_mark: |

**Comment by rfranzke** [comment]
The description is not very clear, but I guess the `test-with-istio` pod is a controller that sometimes misses `CREATE`/`UPDATE`/`DELETE` events for configmaps? I don't know why the problem should be related to Gardener itself. Your current workaround already indicates that you run a service mesh inside the cluster and that changing its configuration fixes the problem.
Can you please provide reproducible steps with a plain shoot cluster so that we can nail down the problem on Gardener side?

**Comment by modulo11** [comment]
We boiled down our original issue to these steps, where we create two pods (`test-with-istio`, `test-with-istio-fix`) of which one is part of the Istio service mesh and the other one isn't (see `test.yaml` for reference). Inside these pods we watch for changes of a specified `configmap` (but the resource type should not be important). After some time, one of the pods (`test-with-istio`) seems to not receive any more events while the connection to the API service seems to be present.

We ran this experiment on different cloud setups (Plain EKS, Gardener on AWS and GCP) and it appears to only happen when we use Gardener on AWS. All necessary steps to reproduce the issue are documented above.

**Comment by rfranzke** [comment]
My point was to have steps that can be executed inside a cluster that doesn't have Istio installed. If it's reproducible there as well then we can go one step further and investigate there. If it's only reproducible with istio mesh in between then it might be related to Istio itself/its configuration.

**Comment by loewenstein** [comment]
Actually the issue is supposedly somewhere between Istio/Envoy, the AWS LoadBalancer and the Kubernetes api-server on the seed. The workaround we apply is not really a service mesh configuration, it is rather an escape hatch to circumvent the Envoy for that particular target IP.

This might not _directly_ be a Gardener issue, but it could well be related to the AWS Load Balancer configuration that is used to ingress traffic to the api-server. And it definitely puts limits to run Istio as a workload on Gardener.

**Comment by timebertt** [comment]
I'm no istio expert and have actually no idea how the concrete connection flow looks like.
But one thing, that comes to my mind, which is different between AWS and GCP, is that the `kubernetes.default` endpoints object (the one behind the Service with ClusterIP `100.64.0.1`) has two IPs on AWS (both IPs, that the ELB DNS name resolves to) and on GCP only one IP. Could this cause any difficulties for envoy or your specific istio config?

**Comment by Haegi** [comment]
This issue was fixed by the introduction of the AWS NLB (at the moment enabled on dev).
