### ISSUE TITLE
Improve g-api stability during rolling updates

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#2814]
**How to categorize this issue?**

/area robustness high-availability
/kind enhancement
/priority normal

**What would you like to be added**:
As discussed in an internal thread, let's improve the stability/availability of the gardener-apiserver during rolling updates by
- [x] tweaking the deployments' rolling update strategy
- [x] maybe setting `minReadySeconds` and adding some delaying `preStop` hooks (might not be needed as pointed out by @timuthy)

similarly to the optimizations done in https://github.com/gardener/gardener/pull/1275.

**Why is this needed**:
We sometimes have some troubles keeping availability of g-api up during rolling updates (e.g. during deployments).

/cc @amshuman-kr

**Comment by amshuman-kr** [comment]
Some background to the optimizations in #1275.

1. The [`preStop` delay](https://github.com/gardener/gardener/pull/1275/files#diff-062a90a9b844a78dd06fb9fa802386beR110-R116) is to give the kube-proxies a chance to
propagate the changes to the iptables in all the nodes as noted [here](https://github.com/kubernetes/kubernetes/issues/43576).
1. The increase in `minReadySeconds` is to ensure that the new pods during rolling update stay ready while serving traffic for some time. The deployment controller [continues the rolling update](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#min-ready-seconds) only after that.
