### ISSUE TITLE
ApplyChart fails for existing resources with immutable fields

### ISSUE THREAD

**Issue by shturec** [gardener/gardener#282]
The issue was observed when the function [ApplyChart](https://github.com/gardener/gardener/blob/fe5a126d859e580cf20d2b934ac68b9fd0a873ea/pkg/operation/common/utils.go#L37) was invoked for a chart that deploys a [Service Catalog](https://github.com/kubernetes-incubator/service-catalog) `ServiceInstance` resource in a cluster that already has one. The error is the standard one that you receive when you try to change a resource immutable field.

After some investigation it was found out that the code [implementing](https://github.com/gardener/gardener/blob/master/pkg/client/kubernetes/base/apply.go) the [Client](https://github.com/gardener/gardener/blob/master/pkg/client/kubernetes/types.go)'s [Apply](https://github.com/gardener/gardener/blob/fe5a126d859e580cf20d2b934ac68b9fd0a873ea/pkg/client/kubernetes/types.go#L122) interface function [sends a PUT](https://github.com/gardener/gardener/blob/master/pkg/client/kubernetes/base/apply.go#L145), effectively overwriting all manifest fields, including immutable ones. This obviously fails updates of resources with immutable fields, such as 'ServiceInstance' and needs to be improved.

In the case of `ServiceInstance` what happens is the following. We provide the minimal subset of fields in a manifest required to create/update the resource. The create works fine. When it comes to update, the fact that the client sends a PUT with a minimal subset of fields means that it tries to recreate a resource with nil values for the fields not provided with the manifest, including immutable ones, which obviously results in error.

To improve the situation it is necessary to use PATCH for resources featuring immutable fields. Obviously, it's hard to tell, which fields are immutable. If it is not possible to entirely replace the PUT with PATCH maybe an option would be to provide optional configuration for the update method per resource (kind) to use in ApplyChar and comply with it if provided.

**Comment by rfranzke** [comment]
Hm, true. But where does Gardener need to deploy a `ServiceInstance` resource? Or do you simply want to re-use the function in another project?
As you said, it's hard to tell that in general. Also, PATCH isn't what we want in all cases.

**Comment by shturec** [comment]
Yes, I'm reusing the function in a controller extending gardener to deploy resources in seeds and shoots. It happens that I need Service Catalog resources, hence the problem. But they are just an example. Potentially, there could be any (custom) resource that may need patch. For gardener extensibility sake it would be great to enhance a bit the function to consider these scenarios too.

What about my suggestion to delegate to ApplyChart users to configure update behavior as an optional argument in the function signature? Would that make sense to achieve flexibility on demand?

**Comment by rfranzke** [comment]
Let's close this for now and possibly reopen after the exensibility epic.
