### ISSUE TITLE
Documentation for version upgrade process

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#2827]
**How to categorize this issue?**

/area documentation
/kind enhancement
/priority normal

**What would you like to be added**:
IISIC, we are lacking end-user facing documentation about what happens during a Shoot version upgrade (k8s and machine images).

We could add some documentation describing the process of version upgrades, for example for k8s versions:
- k8s patch version upgrade: API server rolled, other control plane components rolled, kubelets restarted (machines not rolled)
- k8s minor version upgrade: same like before but includes rolling the machines

**Why is this needed**:
Shoot owners want to know, what to expect from gardener during a version upgrade, and might want to plan accordingly.

**Comment by danielfoehrKn** [comment]
In general we need more documentation that explains which configuration changes on the Shoot (k8s version + changes in the worker config) causes either an in place update or a rolling update. 

- Also for instance that renaming a worker equals deleting the worker pool and creating a new one and not a rolling update.
