### ISSUE TITLE
Blocked Infrastructure Resource Cleanup

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#285]
With the number of clusters, the drag on ops grows as people "get ideas" and modify their infrastructure resources (if they happen to have direct access) in ways, Gardener will refuse to clean up. That's a safety measure (Gardener cleans up only resources it has created itself), but also a technical problem, as `Terraform` would be in our way, would we like to handle it differently.

Examples of that:
* Modified security groups or routing tables
* Network or internet gateway can't be deleted because of dependencies
* Existing VPC peering

Another safety measure is that we delete Kubernetes-managed resources via Kubernetes (concretely, the shoot cluster API server), so that we do not accidentally delete unmanaged resources (code that we don't have, cannot have bugs). However, sometimes resources remain dangling, the control plane cannot be resurrected (broken API server extension, e.g. #286) or ops just wants to get rid of an abandoned cluster, in which case we'd like to forcefully delete the resources in order to get rid of the cluster.

Examples of that:
* LBs not deleted
* PVs not deleted (that actually doesn't block Gardener, because volumes are not blocking deletion of any resources the Gardener creates, but it results in costs and since they are tagged, we could delete them)

What could be a way out to improve the situation for ops when dealing with abandoned or mistreated Kubernetes clusters?

Note: It was a deliberate decision not to invest in infrastructure-specific code that provisions, updates and deprovisions the infrastructure in the beginning of the Gardener development, so we went for the quick and simple solution and let Gardener use Terraform pods to handle the infrastructure. We always thought, we might eventually have to implement that ourselves, so that we could get rid of some nasty Terraform bugs/oddities, get the full IaaS functionality, deal with certain problems in a specific way and get better error handling (without textual scrapping of the Terraform output). Maybe it's time to tackle this topic, but will it be even a good idea?

**Comment by vlerenc** [comment]
FYI: Fitting development: https://blog.golang.org/go-cloud (at the time of this writing only GCP and AWS, but more to come).

**Comment by vlerenc** [comment]
@rfranzke @plkokanov @StenlyTU @PlamenPanev What would you see here as remaining issues?

**Comment by rfranzke** [comment]
> Examples of that:
> * Modified security groups or routing tables
> * Network or internet gateway can't be deleted because of dependencies
> * Existing VPC peering

All of this is not covered, but I think we cannot do anything about it.

> Note: It was a deliberate decision not to invest in infrastructure-specific code that provisions, updates and deprovisions the infrastructure in the beginning of the Gardener development, so we went for the quick and simple solution and let Gardener use Terraform pods to handle the infrastructure. We always thought, we might eventually have to implement that ourselves, so that we could get rid of some nasty Terraform bugs/oddities, get the full IaaS functionality, deal with certain problems in a specific way and get better error handling (without textual scrapping of the Terraform output). Maybe it's time to tackle this topic, but will it be even a good idea?

We sometimes see (during shoot creation) that Terraform forgets to create routes which requires ops effort (very rarely). Same for AWS IAM roles and EC2 key pair (even more unlikely/rarely). Switching completely might make sense in the future, however, IMHO Terraform does still provide a lot of benefits and I don't see an immediate need to switch now/soon.

**Comment by StenlyTU** [comment]
In addition to that:
for GCP clusters right now we are facing the problem with firewalls and routes - I've seen merged PR about that.
for OS there are cases when the cluster can't be deleted because of LB port still part of the subnet. Also during cluster creation, some users are missing the necessary network.

**Comment by rfranzke** [comment]
Closing this for now as mitigation has been implemented long back or other issues are opened in the gardener/gardener-extensions repository.
