### ISSUE TITLE
ssd sc use general name

### ISSUE THREAD

**Issue by runzexia** [gardener/gardener#2863]
**How to categorize this issue?**

/area TODO
/kind enhancement
/priority normal

**What would you like to be added**:

make StorageClass `gp2` and `gce-sc-fast` …… use same name

**Why is this needed**:
Our team uses clusters of cloud vendors such as gcp aws. But when we want to use ssd, we need to use the special sc name. For end users, the name of the type is not the most important, but their speed

**Comment by rfranzke** [comment]
This would introduce cross-provider extension coordination which is against the goals of our extensibility concepts.
Generally, I would recommend to let the users create the storage classes they need to run their workload themselves (this way they can also optimize the configurations to suit better to their use case).
