### ISSUE TITLE
expose pod eviction timeout kcm flag to enable shorter eviction time for control plane components in shooted seeds

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#2872]
**What would you like to be added**:
Faster pod eviction if liveliness probe fails. Default is 5m in KCM, but maybe 1m makes more sense so that we get ETCD and API servers “unglued” from broken nodes faster?

**Why is this needed**:
It is an improvement proposal from issues noticed in the past.

**Comment by rfranzke** [comment]
Not sure whether I understand it correctly, but you are talking about the `--pod-eviction-timeout` flag in KCM (with a default of `5m`), right? And you propose to set it to `1m` for shooted seeds?

**Comment by vlerenc** [comment]
Yes @rfranzke , I had it in my old notes (which I am now flushing into the backlogs ;-)), most likely from a previous discussion/issue a long time ago (maybe Gardener Ring?). We concluded back then, that the 5m "are awfully long".

**Comment by rfranzke** [comment]
/title Expose pod eviction timeout KCM flag to enable shorter eviction time for control plane components in shooted seeds
/assign

**Comment by rfranzke** [comment]
I've made it configurable, but it was already set to `2m0s` for all kube-controller-managers in all shoot clusters. We can set it to `1m0s` if we want, though, not sure if the expected behaviour will be established.
