### ISSUE TITLE
Bin-Packing for Control Planes

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#2873]
**What would you like to be added**:
@mvladev once rolled out a change for shoot clusters that switched the scheduler to bin-packing, which significantly reduced our shooted seed control plane costs. Since the change was affecting all shoots and some workload fails to come with proper requests/limits (in contrast to Gardener shoot control planes), we saw issues with such workloads and had to revert the change again. @mvladev suggested to take another shot at the subject matter and find a solution that switches Gardener shooted seeds to bin-packing to drive down control plane costs.

**Why is this needed**:
As we have seen in the past when we rolled out this change for the first time, it helps driving costs down.

**Comment by rfranzke** [comment]
Ref https://github.com/gardener/gardener/pull/1551 and https://github.com/gardener/gardener/pull/1610

**Comment by mvladev** [comment]
The problem today is that the `kube-scheduler` is slowly moving towards getting rid of the old configuration (there won't be any `ClusterAutoscalerProvider` build-into kube-scheduler in the near future). The scheduler configuration has just hit [beta in 1.19](https://kubernetes.io/docs/reference/scheduling/config/).

What I would suggest to have instead, while we wait for GA for kube scheduler config, is to deploy our own `kube-scheduler` with a specific name (e.g. `gardener-control-plane`) in Seed clusters. With this we can have our control plane components to use this scheduler. This would have the following pros and cons:

Pros:

- we are able to have this running on Seed clusters which not managed by Gardener
- won't interfere with other components using the default scheduler
- can be added fast without waiting for API GA from K8S

Cons:

- New feature gate should be introduced
- extra OPS for managing this scheduler (e.g. match Seed's API server version with scheduler one)

/cc @vlerenc

**Comment by mvladev** [comment]
I'm working on this and it's 40% done

/assign
