### ISSUE TITLE
initializeShootClient stuck in Timeout Error in the Cluster Creation Process

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener#288]
Currently we are experiencing an issue when creating Shoots on GCP. The creation of a cluster gets stuck with the following error:

```
Failed to reconcile Shoot cluster state: Errors occurred during flow execution: '(*Operation).InitializeShootClients' returned 'Get https://api.DNS-NAME-OF-MY-SHOOT/version?timeout=32s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)'
``` 

Eventually those failed clusters become healthy again after a 1-3 hour waiting period. it looks like there is a dead but established connection open against the Shoot API-server.

I found those issues on github which might be related:
https://github.com/giantswarm/kvm-operator/pull/484#issuecomment-395683790

> Problem is that k8sclient multiplexes multiple http connections thru one TCP connection and when TCP connection dead (but in established state), there is no way to force use new TCP connection.

This probably falls back to:
https://github.com/kubernetes/kubernetes/issues/133556
https://github.com/kubernetes/client-go/issues/374

Another possible solution (pretty ugly though) would be to fiddle around with the default timeout of the `RESTClient` [0]

[0] https://github.com/kubernetes/client-go/blob/master/discovery/discovery_client.go#L49

**Comment by afritzler** [comment]
After further debugging we found that a the `Send-Q` for the corresponding  API server TCP connection is pretty full:

via:
```
netstat -lanW
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address        Foreign Address     State
tcp        0   5511 10.241.130.171:44256 LB_IP_OF_API_SERVER_SHOOT_1:443  ESTABLISHED    
tcp        0   5946 10.241.130.171:52804  LB_IP_OF_API_SERVER_SHOOT_2:443  ESTABLISHED                                                      
```

That means that packets send to the LB are not acknowledged and fill up the queue. 

All working connections (with healthy Shoots) have an empty `Send-Q` field.

**Comment by mvladev** [comment]
@afritzler noisy neighbors?

**Comment by afritzler** [comment]
@mvladev not really. It is an issue in the Garden cluster itself (which is only running the controller/apiserver)

**Comment by bmaeck** [comment]
@afritzler maybe you can check with linux `ss` command for more details of the connection?
`ss -tie dst <LB_IP_OF_API_SERVER_SHOOT_1 >`

**Comment by afritzler** [comment]
I opened now an issue in the client-go project[0]. Lets see if somebody else is experiencing the same problem.

[0] https://github.com/kubernetes/client-go/issues/442

**Comment by afritzler** [comment]
@bmaeck could MTU be an issue? GCP machines have a < 1400 MTU.

**Comment by afritzler** [comment]
Found an interesting article covering the time out settings of the go net/http client [0].

Setting those values in the dialer and client seems to solve the creation problem on GCP.

[0] https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779

**Comment by afritzler** [comment]
@Adracus some interesting findings from comments of the medium post above:

* By default only two keep-alive connections per host are established. Google for DefaultMaxIdleConnsPerHost . This means that the net/http client immediately closes 998 out of 1K concurrent connections established to the given host after each request. This results in high network overhead and slow performance. This may be fixed by setting Transport.MaxIdleConnsPerHost to higher value.

* By default net/http client keeps up to Transport.MaxIdleConnsPerHost keep-alive connections per host until the server closes them. Servers tend to keep keep-alive connections open for extended periods of time. This means that multi-host web crawler built with default net/http client may end up holding a ton of open but unused keep-alive connections. This may result in sockets + goroutines’ leak.

* net/http client lacks the ability to limit per-host load. The client may easily open 10K concurrent connections to a single host irregardless of Transport.MaxIdleConnsPerHost value. This may result in a ton of network and server errors.

* There is no ability to set timeouts on a per-request basis in net/http client.

Help might come with [0] but not sure if we can get this into the Kubernetes clientset.

Also found this other interesting article on go net/http client timeouts [1].

[0] https://godoc.org/github.com/valyala/fasthttp#Client
[1] https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/

**Comment by adracus** [comment]
Some _very_ interesting Kubernetes issue:
https://github.com/kubernetes/kubernetes/issues/65012

**Comment by rfranzke** [comment]
See kubernetes/client-go#333: Root cause is the underlying infrastructure environment, nothing we can influence in Gardener itself.

**Comment by vlerenc** [comment]
Still, even if not many can access it, @afritzler can you please add the SPC ticket link to SAP IT here, once available.
