### ISSUE TITLE
Control plane Pods are being restarted too often with reason EvictedByVPA

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2882]
**How to categorize this issue?**

/area auto-scaling
/kind bug
/priority normal

**What happened**:
A Shoot was created 50m ago.

```
$ k get ns shoot--it--tmide-4w7
NAME                   STATUS   AGE
shoot--it--tmide-4w7   Active   50m
```

For a Shooted Seed with `spec.kubernetes.verticalPodAutoscaler.enabled=true` for this period of time there were 84 VPA evictions:

```
$ k -n shoot--it--tmide-4w7 get events | grep EvictedByVPA | wc -l
84
```

Basically if you watch the control plane Pods you can see that some of them (for example prometheus-0, loki-0, csi-driver-controller Pod) are being recreated like crazy. Similar evictions by VPA prevent the gardenlet healtch checks for controlplane to be not Ready (for example prometheus pod is being evicted before being detected as healthy from gardenlet).
If there is a machinery that is waiting for Shoot creation, it would wait until all Shoot status conditions are ready (as the create Shoot test does). Similar behaviour by VPA is not acceptable.

**What you expected to happen**:
I wouldn't expect Shoot creation to take 50m because the Shoot conditions cannot be ready caused by VPA doing too much eviction.

**How to reproduce it (as minimally and precisely as possible)**:
Not clear for now.

**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by amshuman-kr** [comment]
The most evicted pods seem to be the following. All the others were scale at most once.
```
g k -- -n shoot-garden-aws log vpa-updater-6cdf64bfbd-nnvnm | grep evicting | gsed 's/.*evicting pod//g' | sort | uniq -c | grep -v ' 1 '
  25  aggregate-prometheus-0
 179  loki-0
 143  prometheus-0
```

```
$ g k -- get pod --all-namespaces | grep -c aggregate
1

$ g k -- get pod --all-namespaces | grep -c loki-0
20

$ g k -- get pod --all-namespaces | grep -c prometheus-0
17
```

**Comment by ialidzhikov** [comment]
Nope

```
$ k -n shoot--it--tmide-4w7 get events | grep csi-driver-controller | grep EvictedByVPA | wc -l
36
```

**Comment by amshuman-kr** [comment]
You are right. I missed removing the hash suffix in pod names.

**Comment by amshuman-kr** [comment]
VPA Updater doesn't seem have too many [options to be tweaked](https://github.com/kubernetes/autoscaler/blob/30b1bb49d539a134f0a5c4646e43c9fc5f151718/vertical-pod-autoscaler/pkg/updater/main.go#L40-L60).

The only possibility seems to be [`--updater-interval`](https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-0.8.1/vertical-pod-autoscaler/pkg/updater/main.go#L41).

Other than this I can think of a few things. What is appropriate among these depends on which case triggers this issue and how frequently this happens. @ialidzhikov Does this happen only for shooted seeds or for normal shoots too?
- A larger gap between requests and limits in the target pod templates may reduce the eviction as the pods will be in the recommended range longer.
- Set higher requests (and limits) in pod templates and let VPA scale down eventually (which is much slower) if there is no load.
- Set higher `minAllowed` values in VPA instances for the affected targets to prevent scaling down too low leading to problems when the load increases eventually.. This has been encountered for different components already.

**Comment by vpnachev** [comment]
I can only point out that this is affecting also the extension pods deployed in the seed cluster, for example the os-gardenlinux extension was evicted 61 times in the last hour.
```bash
$ k -n extension-os-gardenlinux-w2mpq get events | grep EvictedByVPA | wc -l
61
```

**Comment by vpnachev** [comment]
Actually the eviction is done because the recommendations are not applied, the reason for which is that `vpa-webhook-config` mutatingwebhookconfigurations is gone.

**Comment by vpnachev** [comment]
The above might be related to https://github.com/gardener/gardener/pull/2802 (cc @ggaurav10 ).

**Comment by ialidzhikov** [comment]
```
$ k get events -A | grep EvictedByVPA | wc -l
7715
```

**Comment by amshuman-kr** [comment]
I see the VPA webhook config got created in the night. Is the eviction problem still there?
```
g k -- get mutatingwebhookconfigurations vpa-webhook-config
NAME                 CREATED AT
vpa-webhook-config   2020-09-24T02:15:13Z
```

**Comment by ggaurav10** [comment]
I am seeing that `vpa-webhook-config` is getting deleted and recreated again and again - every few seconds - atleast in gcp dev seed.

**Comment by ggaurav10** [comment]
looks like the following line is deleting the webhook because vpa is not enabled for `seed` resource:
https://github.com/gardener/gardener/blob/7fd3754574168a3318be5b0a54e78541e34d0831/pkg/operation/common/utils.go#L393

but since VPA is enabled for the `shoot` resource (which is acting as seed), the gardener-resource-manager is creating it again.
