### ISSUE TITLE
seed bootstrap fails on kubernetes 1.19 clusters

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/gardener#2891]
**How to categorize this issue?**

/area control-plane
/kind bug
/priority normal

**What happened**:
Tried to create a seed on a kubernetes 1.19.1 cluster. The seed does not become `Ready`. The logs show this:
```
failed to apply manifests: 2 errors occurred: [could not apply object of kind "Ingress" "garden/aggregate-prometheus": Ingress.extensions "aggregate-prometheus" is invalid: spec.rules[0].http.paths[0].pathType: Required value: pathType must be specified, could not apply object of kind "Ingress" "garden/grafana": Ingress.extensions "grafana" is invalid: spec.rules[0].http.paths[0].pathType: Required value: pathType must be specified]
```

**What you expected to happen**:
The seed to become `Ready`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a 1.19.1 cluster (I tried it on a shoot)
2. Deploy the gardenlet into that cluster

**Anything else we need to know?**:
I checked the kubernetes release notes and the field `pathType` did indeed change from optional to mandatory with kubernetes 1.19.

I tried to fix this myself, see this commit https://github.com/Diaphteiros/gardener/commit/64fd5a32aefc73554f3986818bc9cc27447b5251. This seems to have worked, however, now I get a different error that I don't really understand:
```
failed to apply manifests: 2 errors occurred: [could not apply object of kind "Ingress" "garden/aggregate-prometheus": Ingress.extensions "aggregate-prometheus" is invalid: spec.rules[0].http.paths[0].backend: Invalid value: "": resource or service backend is required, could not apply object of kind "Ingress" "garden/grafana": Ingress.extensions "grafana" is invalid: spec.rules[0].http.paths[0].backend: Invalid value: "": resource or service backend is required]
```

The template https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/templates/aggregate-prometheus/ingress.yaml#L20-L22 shows that the specified node is not empty, so I don't know where this error comes from.

**Environment**:

- Gardener version: `v1.10.1`
- Kubernetes version (use `kubectl version`): `v1.18.6`
- Cloud provider or hardware configuration: tried it on AWS
- Others:

**Comment by rfranzke** [comment]
Ref https://github.com/kubernetes/api/blob/master/networking/v1/types.go#L422-L438 - the `backend` type has changed which you need to adapt.

/in-progress
/assign @Diaphteiros

**Comment by rfranzke** [comment]
Any progress @Diaphteiros ?

**Comment by Diaphteiros** [comment]
@rfranzke I tried to adapt the ingress resources to the new apiGroup, but that broke backwards compatibility. I found out that there is a function in the helm template that sets the ingress apiGroup depending on the kubernetes version (https://github.com/Diaphteiros/gardener/blob/fix-seed-bootstrap/charts/utils-templates/templates/_versions.tpl#L75-L83).
I tried to copy this switch into the ingress templates in the charts, see https://github.com/Diaphteiros/gardener/commit/25c77d2a7fcf3b5974936638e64338aabb6e812d but I couldn't get it to work yet 😞

**Comment by rfranzke** [comment]
Hmm, what do you mean by "broke backwards compatibility"? The changes actually look promising, what's the exact error?

**Comment by Diaphteiros** [comment]
Since the ingress version is set dynamically, depending on the kubernetes version, it will be set to `networking.k8s.io/v1beta1` for clusters lower than kubernetes 1.19, which requires the old format for the ingress. So if I just update the ingress spec to the new format in a static manner, this will fail (at least it didn't work, when I tried it, the error message hinted that the `serviceName` field was missing, but I don't remember it exactly).
Therefore I tried to use the same condition that is used to determine the ingress apiGroup also for determining the format of the ingress spec, but then I always get some kind of templating error.

I will retry this on Monday and write the exact error message here.

**Comment by Diaphteiros** [comment]
I retried it with the linked commit. Seed bootstrap works fine, but shoot creation fails with this error message:
```
task "Deploying Shoot monitoring stack in Seed" failed: retry failed with context deadline exceeded, last error: render error in "core/charts/prometheus/templates/ingress.yaml": template: core/charts/prometheus/templates/ingress.yaml:24:56: executing "core/charts/prometheus/templates/ingress.yaml" at <.Capabilities.KubeVersion.GitVersion>: nil pointer evaluating interface {}.KubeVersion
```

**Comment by rfranzke** [comment]
Hm, I don't understand this error, the capabilities are set centrally in the chartrenderer itself, so I have no clue how this can be a nil pointer.
/cc @ialidzhikov @mvladev - any hints/ideas?

**Comment by ialidzhikov** [comment]
> I retried it with the linked commit. Seed bootstrap works fine, but shoot creation fails with this error message:
> 
> ```
> task "Deploying Shoot monitoring stack in Seed" failed: retry failed with context deadline exceeded, last error: render error in "core/charts/prometheus/templates/ingress.yaml": template: core/charts/prometheus/templates/ingress.yaml:24:56: executing "core/charts/prometheus/templates/ingress.yaml" at <.Capabilities.KubeVersion.GitVersion>: nil pointer evaluating interface {}.KubeVersion
> ```


The issue is caused by usage of the root context (`.`) inside `range`. 


`range` and `with` overwrite `.`, so we need to use `$.` to refer the root context.

```diff
  {{- range .Values.ingress.hosts }}
  - host: {{ required ".hostName is required" .hostName }}
    http:
      paths:
      - backend:
-          {{- if semverCompare ">= 1.19-0" .Capabilities.KubeVersion.GitVersion }}
+          {{- if semverCompare ">= 1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: grafana-{{ $.Values.role }}
            port:
              number: {{ required ".ports.grafana is required" $.Values.ports.grafana }}
          {{- else }}
          serviceName: grafana-{{ $.Values.role }}
          servicePort: {{ required ".ports.grafana is required" $.Values.ports.grafana }}
          {{- end }}
        path: /
        pathType: Prefix
  {{- end }}
```

@Diaphteiros , as I had everything locally set up I filed #2949 and added you as co-author (I hope this is fine for you).
