### ISSUE TITLE
[Flaky test] Extensions Controller BackupBucket Test Suite

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#2915]
**How to categorize this issue?**

/area testing
/kind flake
/priority critical

**What happened**:

`Extensions Controller BackupBucket Test Suite` (BackupBucket controller integration test) is flaky with a high rate:
- https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-master/jobs/master-pull-request-job/builds/9
- https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-master/jobs/master-pull-request-job/builds/10
- https://concourse.ci.gardener.cloud/builds/4168

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Not sure yet. The flake seems to be related to cpu pressure on the CI machines, as it fails at different steps of the test with `context deadline exceeded` errors or errors indicating, that the reconciler couldn't act.

I tried to reproduce it locally, no luck so far.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.11.0-dev
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
After half a day trying to reproduce it, I'm stuck with this.
I tried reproducing it
- in a cpu restricted docker container
- with [stress](https://godoc.org/golang.org/x/tools/cmd/stress)
- with stress in a cpu restricted docker container
- with different combinations of timeout settings, resource limitations, parallel executions...

But so far, no luck. With heavy cpu limits / high parallelism, the test times out starting the kube-apiserver:
```
Running Suite: Extensions Controller BackupBucket Test Suite
============================================================
Random Seed: 1601388879
Will run 2 of 2 specs

STEP: starting test environment
2020-09-29T14:14:39.507Z	DEBUG	controller-runtime.test-env	starting control plane	{"api server flags": []}
2020-09-29T14:15:02.091Z	ERROR	controller-runtime.test-env	unable to start the controlplane	{"tries": 0, "error": "timeout waiting for process kube-apiserver to start"}
github.com/go-logr/zapr.(*zapLogger).Error
	/Users/timebertt/go/src/github.com/gardener/gardener/vendor/github.com/go-logr/zapr/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).startControlPlane
	/Users/timebertt/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go:279
sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).Start
	/Users/timebertt/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go:241
github.com/gardener/gardener/extensions/pkg/controller/backupbucket_test.glob..func1.1
	/Users/timebertt/go/src/github.com/gardener/gardener/extensions/pkg/controller/backupbucket/backupbucket_suite_test.go:66
...
```

Any hints, what we could also try to reproduce the flake / nail the problem down?

Otherwise, my best bet would be to just increase the timeouts...

**Comment by rfranzke** [comment]
I guess the problem occurs when the CPU is throttled as part of the test execution (after the temporary control plane started up).

**Comment by timebertt** [comment]
Yes, exactly. That was also my assumption.
Any ideas how to reproduce such a behaviour?

**Comment by rfranzke** [comment]
No, not really. What would be the next step (assuming we can reproduce this)?

**Comment by timebertt** [comment]
> What would be the next step (assuming we can reproduce this)?

Hm, probably find suitable timeouts and test if it helps...
I will increase the timeouts a bit and do some smaller improvements tomorrow and then we can just observe it in the pipeline.

A small finding from today at least, but unfortunately not a fix for the flake: #2921

**Comment by rfranzke** [comment]
Is this still happening?

**Comment by timebertt** [comment]
> Is this still happening?

Nope, doesn't seem to be the case 😉 
So let's
/close
for now.

**Comment by timebertt** [comment]
/reopen

After quite a while without any flakes, it's happening again:
https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-master/jobs/master-pull-request-job/builds/261
https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-master/jobs/master-pull-request-job/builds/255.1

**Comment by timebertt** [comment]
Haven't seen any flakes again.
/close
