### ISSUE TITLE
links to a bunch of YAML files ends in 404

### ISSUE THREAD

**Issue by freegroup** [gardener/gardener#292]
**document** : https://github.com/gardener/gardener/blob/master/docs/deployment/configuration.md 
**wrong link** : https://github.com/gardener/gardener/blob/master/example/cloudprofile-aws.yaml

**document** : https://github.com/gardener/gardener/blob/master/docs/deployment/kubernetes.md 
**wrong link** :https://github.com/gardener/gardener/blob/master/docs/deployment/../../example/seed-aws-dev.yaml 

**document** : https://github.com/gardener/gardener/blob/master/docs/development/process.md 
**wrong link** :https://github.com/gardener/gardener/blob/master/docs/development/compare

**document** : https://github.com/gardener/gardener/blob/master/docs/deployment/configuration.md 
**wrong link** :https://github.com/gardener/gardener/blob/master/docs/deployment/../../example/secret-alerting-smtp.yaml

**document** : https://github.com/gardener/gardener/blob/master/docs/deployment/configuration.md 
**wrong link** :https://github.com/gardener/gardener/blob/master/docs/deployment/../../example/componentconfig-gardener-controller-manager.yaml

**document** : https://github.com/gardener/gardener/blob/master/docs/deployment/configuration.md 
**wrong link** :https://github.com/gardener/gardener/blob/master/docs/deployment/../../example/seed-aws-dev.yaml

**document** : https://github.com/gardener/gardener/blob/master/docs/deployment/configuration.md 
**wrong link** :https://github.com/gardener/gardener/blob/master/docs/deployment/../../example/shoot-azure.yaml#L10

**document** : https://github.com/gardener/gardener/blob/master/docs/deployment/configuration.md 
**wrong link** :https://github.com/gardener/gardener/blob/master/docs/deployment/../../example/secret-seed-aws-dev.yaml

**document** : https://github.com/gardener/landscape-setup/blob/master/README.md 
**wrong link** :https://github.com/gardener/gardener/blob/master/example/shoot-aws.yaml

**document** : https://github.com/gardener/gardener/blob/master/docs/deployment/configuration.md 
**wrong link** :https://github.com/gardener/gardener/blob/master/docs/deployment/../../example/secret-core-aws.yaml

**document** : https://github.com/gardener/gardener/blob/master/docs/deployment/configuration.md 
**wrong link** :https://github.com/gardener/gardener/blob/master/docs/deployment/../../example/secret-internal-domain.yaml

**document** : https://github.com/gardener/gardener/blob/master/docs/deployment/configuration.md 
**wrong link** :https://github.com/gardener/gardener/blob/master/docs/deployment/../../example/secret-default-domain.yaml 

**document** : https://github.com/gardener/gardener/blob/master/docs/development/local_setup.md 
**wrong link** :https://github.com/gardener/gardener/blob/master/docs/development/../../example/shoot-azure.yaml#L10

**document** : https://github.com/gardener/gardener/blob/master/docs/deployment/configuration.md 
**wrong link**: https://github.com/gardener/gardener/blob/master/docs/deployment/../../example/secretbinding-core-aws.yaml

**Comment by plkokanov** [comment]
This error can also be observed with the following files:

docu: https://github.com/gardener/gardener/blob/master/docs/development/local_setup.md

link :https://github.com/gardener/gardener/blob/master/example/secret-internal-domain.yaml


All files in the example folder had a number added before their name.
I'll make a PR to fix the documentation asap.

**Comment by freegroup** [comment]
still some broken links

**document**: https://github.com/gardener/gardener/blob/master/docs/development/process.md 
**link**: https://github.com/gardener/gardener/blob/master/docs/development/compare

**document**: https://github.com/gardener/documentation/blob/master/CONTRIBUTING.md 
**link**: https://code.google.com/p/go-wiki/wiki/CodeReviewComments
(should be https://github.com/golang/go/wiki/CodeReviewComments ) 

**document**: https://github.com/gardener/landscape-setup/blob/master/README.md 
**link**: https://github.com/gardener/gardener/blob/master/example/shoot-aws.yaml

**Comment by plkokanov** [comment]
@freegroup 

**link**: https://github.com/gardener/gardener/blob/master/docs/development/compare 
mentioned this in #296 this deserves a separate issue imo.

**document**: https://github.com/gardener/landscape-setup/blob/master/README.md
**link**: https://github.com/gardener/gardener/blob/master/example/shoot-aws.yaml 
is for the landscape-setup so I'll create a separate issue and PR for that repository


**document**: https://github.com/gardener/documentation/blob/master/CONTRIBUTING.md
**link**: https://code.google.com/p/go-wiki/wiki/CodeReviewComments
(should be https://github.com/golang/go/wiki/CodeReviewComments )
The available link works and redirects to the suggested new one. Maybe the old is outdated?

**Comment by freegroup** [comment]
hi - code.google.com is outdated and not supported anymore. We should avoid redirects.
Make things easier for the build job which checks the documentation for dead links.
