### ISSUE TITLE
Documenation on etcd and etcd-druid usage in gardener

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#2930]
**How to categorize this issue?**

/area documentation control-plane
/kind enhancement
/priority normal

**What would you like to be added**:
Currently, we don’t have any documentation about the usage of etcd and etcd-druid in gardener.

We should add some documentation about
- how etcd-druid is used to bring up the etcds for Shoot clusters
- why we have `etcd-main` and `etcd-events` and what the differences are
- how the deployment flow for etcds look like and how the provider extension webhooks can/should interact with them ([this doc](https://github.com/gardener/gardener/blob/master/docs/extensions/controlplane-webhooks.md#etcd-main-and-etcd-events) probably has to be updated)
- how etcd versions are upgraded

**Why is this needed**:
etcd is an important component for the shoot clusters and we should document how it is deployed, upgraded and so on.
Also documentation for the contract between gardener and the extension webhooks should be kept up-to-date.

**Comment by rfranzke** [comment]
@danielfoehrKn would this be something for the quality focus this week?
