### ISSUE TITLE
Max cap for shoots per seed in scheduler

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#2938]
**What would you like to be added**:
We have seen seeds (`gardenlet`) go down after being overloaded with shoots, so it may be safer to have a max cap for shoots per seed until we have implemented the automated seed cluster management that would automatically add new seeds.

**Why is this needed**:
To prevent the `gardenlet` on a seed to go down.

/cc @danielfoehrKn

**Comment by danielfoehrKn** [comment]
>  it may be safer to have a max cap for shoots per seed until we have implemented the automated seed cluster management that would automatically add new seeds

Is having a max cap. of Shoot clusters for a Seed not independ of the  automated seed cluster management?
Shoot clusters can be pinned to a Seed, so the automated seed cluster management does not help in this case.

Maybe we can implement the max cap for shoots per seed via
 
**Scheduler**
 - component configuration with default hard max number of Shoots. Overridden by config on the Seed.

**Seed**
 - soft limit of Shoot clusters
   -  scheduler will not schedule any more Shoots to the Seed if soft limit is reached
   - only if no Seed is found during [filterCandiates](https://github.com/gardener/gardener/blob/2fb3b07c5c741b432889ce155a89a82cd88532b1/pkg/scheduler/controller/shoot/scheduler_control.go#L280) it would retry with allowing to go over the soft limit (but not over the hard limit)
 - hard limit
   - if not set, defaults to global scheduler configuration

The future Seed management would
 - only configure the soft limit on a Seed
 - more Shoot clusters than soft eviction can cause a control plane migration for e.g `evaluation` clusters (comparable [Soft kublet eviction](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#soft-eviction-thresholds))

Overall I think having soft and hard limits is not too much effort to implement (compared to only hard).
WDYT

**Comment by vlerenc** [comment]
Sure, sounds reasonable, thank you very much!

As for your question:
> Is having a max cap. of Shoot clusters for a Seed not independ of the automated seed cluster management?

Maybe, maybe not. Seed cluster management may have additional insights (monitoring data, infrastructure considerations, particular seed specs in case of bring-your-seeds, etc.). For the time being, we don't have these things and the rule(s) will be simple (just a cap), so let's go for your proposal then, but I would be open that both, hard and soft caps are defined from the outside, which you have above. 👍 

And in regards to:
 > Shoot clusters can be pinned to a Seed, so the automated seed cluster management does not help in this case.

We could also reject such shoots with "pinned seeds", if the seed has reached its hard cap. WDYT?

**Comment by danielfoehrKn** [comment]
> We could also reject such shoots with "pinned seeds", if the seed has reached its hard cap

From my perspective that makes sense. Should be added in an admission plugin.

**Comment by danielfoehrKn** [comment]
We decided that we would start with the `hard cap` for Shoots. 
We ll keep the `soft cap` in mind when the control plane migration is enabled and work started on the automated seed cluster management.

**Comment by mvladev** [comment]
It's better to put that configuration in the Seed status like [the Node status](https://github.com/kubernetes/api/blob/2c3c141c931c0ab1ce1396c3152c72852b3d37ee/core/v1/types.go#L4582-L4593) is set. The flow would be quite simple:

- a gardenlet is set with some resources it has as a capacity. 
- it updates the `Seed` status with that `capacity` and how much it actually is available (this is the `allocatable` field.
- this would allow the scheduler to choose a seed cluster based on the allocatable and capacity score.

This would allow also in the future to expand with some additional resources e.g. a Shoot would require 10 persistent volumes and the Seed can allocate only 5.

**Comment by mvladev** [comment]
Furthermore, cloud-provider extensions can also update the Status with some cloud-specific limitations (e.g. 300 LoadBalancers limit in Azure)

**Comment by vlerenc** [comment]
I like that @mvladev, maps to an established practice, having `capacity` or rather `allocatable`.

Then again, also with this in place, schedulers are nasty. They cannot easily react to new / unknown resources, which makes scheduling pods on nodes hard (memory, cpu, disks, pods, ...) and so introducing later more resource types will require also changes in the scheduler to respect them.

**Comment by mvladev** [comment]
> and so introducing later more resource types will require also changes in the scheduler to respect them.

If the logic is generic, then it should not require any additional changes. It's just a dictionary of `resource-name` and `allocatable-value`.
