### ISSUE TITLE
Graduate APIServerSNI (+ ManagedIstio) feature gate

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#2942]
**How to categorize this issue?**

/area control-plane
/area cost
/area scalability
/kind enhancement
/priority normal

**What would you like to be added**:
The `APIServerSNI` and `ManagedIstio` (usually used together) should be graduated to **beta** after we have collected sufficient experience and test results on regularly tested and busy landscapes. Any potential issues and blockers graduating this feature can be referenced or documented here.

Steps:
- [x] Enable feature gates on development landscape 
- [x] Enable feature gates on landscape featuring extended automated tests
- [x] Enable feature gates on landscape with stakeholder workload (large landscape)
- [x] Enable Prometheus metrics and Grafana Dashboards for `ManagedIstio`
- [x] Add `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` environment variables to all Gardener components to avoid going to through the `apiserver-proxy`
- [x] Replace `nginx` with `envoy` to have the same proxy on both the client and server side. Enovy supports [upstream proxy protocol transport](https://www.envoyproxy.io/docs/envoy/v1.16.0/intro/arch_overview/other_features/ip_transparency.html?highlight=envoy%20filters%20listener%20proxy_protocol#proxy-protocol)
- [x] Add Prometheus scraping for `apiserver-proxy`
- [x] Expose `apiserver-proxy`'s `envoy` metrics` available for scraping.
- [x] Allow for end-users to specify the `istio-ingress-gateway` namespace and name.
- [x] Add `PodDisruptionBudget` for `istio-ingress-gateway` and `istiod`
- [x] Add a `MutatingWebhookConfiguration` for `Pods` in the Shoot cluster, adding `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT`. It'll run as a sidecar to the API Server (to not have any extra latency to all `CREATE` requests) with `FailurePolicy: Ignore` and very low `timeoutSeconds` - (1 or 2)
- [x] Set KEEPALIVE on both `apiserver-proxy` and `istio-ingressgateway`
- [x] ~Change the port of `kube-apiserver` gateways to `9443` to prevent issues if `istio-ingressgateway` service has port `443` is removed.~
- [x] ~Preserve original source IP~ GA feature

/cc @mvladev

**Why is this needed**:
Both feature gates are an essential milestone to host control planes in a cost efficient and scalable manner.

**Comment by timuthy** [comment]
Waiting for https://github.com/gardener/gardener/pull/2954 before we proceed with the activation on the last landscape.

**Comment by mvladev** [comment]
I've updated the issue with additional requirements.

**Comment by timuthy** [comment]
Thanks @mvladev.

> Allow for end-users to specify the istio-ingress-gateway namespace and name.

Can you elaborate what is meant by this requirement?

**Comment by mvladev** [comment]
> Can you elaborate what is meant by this requirement? 

Today it's hard-coded to `istio-ingress` namespace and `istio-ingress-gateway`. It can be different if `ManagedIstio` is not used and there is some custom installation. By default, IGW is installed in the `istio-system` namespace.

**Comment by timebertt** [comment]
@mvladev Thanks for adding the action items, makes perfect sense!
I think it would be good, to first add proper monitoring for this feature gate, before we enable it on an end-user facing environment (or even one Seed of it).

Therefore my question: would you be able to implement those requirements so we can proceed with the graduation and then enable it on end-user facing environments?

**Comment by mvladev** [comment]
I'm working on enabling the metrics atm

**Comment by timebertt** [comment]
Great, thanks!
/assign @mvladev

**Comment by rfranzke** [comment]
@vlerenc asked to have an annotation on the `Shoot` that allows to overwrite the feature gate setting for this particular cluster, similar to what we've done for the `KonnectivityTunnel` in #3007 

WDYT @mvladev ?

**Comment by vlerenc** [comment]
@mvladev @rfranzke I was merely asking whether we have it, because we could support that. But I only asked in case we hit a hard wall somewhere if we now roll it out to thousands of clusters. If we don't have it, no need to invest now into it. We can continue with the roll-out - it just feels safer to have such a thing and not being forced to roll back things, but if it looks good, we can just decide to go on.

**Comment by rfranzke** [comment]
Sure, thanks. A severe difference compared to the `KonnectivityTunnel` feature is also that this has effects on the seed (costs, etc.) which is not accessible by end-users (while they would still be able to {en,dis}able the `APIServerSNI` feature for their particular shoot if we go this "annotation" way.

**Comment by vlerenc** [comment]
@rfranzke Right. My thoughts were actually, that if we have it, only we would/could do that, but not end users. Like with quotas, we would do that only on an exception basis. Anyway, nothing to worry about right now (or in the future), if everything runs (stays) smoothly. :-)

**Comment by rfranzke** [comment]
According to @mvladev we have observed rare issues with the `apiserver-proxy` when running on large worker nodes.
@mvladev can you provide an update here? What is missing to promote the feature gate to `beta` and enable it by default?

**Comment by rfranzke** [comment]
ping @mvladev
