### ISSUE TITLE
Add custom monitoring for extensions

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener#2946]
**How to categorize this issue?**

/area monitoring
/kind enhancement
/priority normal

**What would you like to be added**:
The current [extensions contract](https://github.com/gardener/gardener/blob/master/docs/extensions/logging-and-monitoring.md#monitoring) only supports adding monitoring in the shoot control plane. This concept should be extended to allow extensions to be monitored from the `aggregate-prometheus` in the garden namespace.

**Why is this needed**:

Custom metrics exposed by extension controllers (like the [external-dns-management](https://github.com/gardener/external-dns-management) controller @MartinWeindel ) are not collected. These metrics can provide insights into the components and our landscape that we currently do not collect.

**Proposal**:

Extensions create a configmap either in the garden namespace or in the extension namespace that is picked up by gardener similar to the current contract. The configmap will have configuration for the `aggregate-prometheus` and contain dashboards for grafana.

**Comment by wyb1** [comment]
After discussing with @MartinWeindel @timebertt and @istvanballok we came up with the following proposal. We will add a new singleton `prometheus` which we will call `seed-prometheus` in the `garden` ns (it could also be deployed in a different ns).
# Seed-prometheus
Will be responsible for all system components running on the seed (i.e. everything other than shoot control planes).

## Contract between seed-prometheus and extensions

The `seed-prometheus` will discover all pods in the extension namespaces and only scrape pods with annotations similar to those of the prometheus operator. Example:
- `prometheus.io/scrape: true`
- `prometheus.io/port: 8080`

## Providing dashboards

The extensions can also provide dashboards for the grafana running in the garden ns. Grafana provides a [sidecar](https://github.com/grafana/helm-charts/tree/main/charts/grafana#sidecar-for-dashboards) that can discover and provision dashboards from configmaps. The configmap just needs the proper label to be discovered.

![image](https://user-images.githubusercontent.com/8710621/115198929-ea65c500-a0f2-11eb-9b59-d0219775e840.png)

**Comment by timebertt** [comment]
Thanks for your proposal! As said in person, I like it very much and I'm already looking forward to the improved monitoring experience! 🚀 

One minor comments and one question from my side:

1. I would propose to use `prometheus.io/{scrape,port}` (not the `.io`), as it seems to be kind of a standard in the community (e.g. comes as part of many helm charts and the prometheus helm chart also uses those annotations by default, see [here](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus#scraping-pod-metrics-via-annotations)).
2. Can you clarify how the `grafana` box in the diagram relates to the current grafana instance in the `garden` ns of Seeds, that we already have? Is this the same instance or a new one? If it's a new one, will it also host existing seed monitoring dashboards? :)

**Comment by wyb1** [comment]
Thanks for the feedback @timebertt!

1. You are right. I will update the comment to reflect that.
2. The grafana already exists and I propose we simply reuse it. The grafana will have multiple prometheus datasources, but I don't see that being an issue. Either way it should be used to host existing and new seed monitoring dashboards.

**Comment by timuthy** [comment]
@wyb1 Can you shortly explain how this new `seed-prometheus` is different from the Prometheus instance (seed monitoring stack) we already have in the `garden` namespace or what's the motivation for adding a new Prometheus instead of reusing the existing one?
Btw. which controller will be responsible for deploying `seed-prometheus`?
Thanks :)

**Comment by wyb1** [comment]
The motivation of adding a new prometheus is so that we have a prometheus dedicated to only monitor components running on the seed. This should be the entry point for operators when debugging issues with the seed. There are 2 reasons for not reusing the `aggregate-prometheus` which is also running in the garden ns.
1. The purpose of the `aggregate-prometheus` is to aggregate data (i.e. data with low cardinality). If we start collecting data from every extension we will have lots of high cardinality data in this prometheus.
2. The `seed-prometheus` will act as buffer protecting the `aggregate-prometheus` from being overloaded with too many metrics and filling the disk since we could have any number of extensions exposing metrics and we don't have any control over which metrics we collect.

Maybe I am being overly cautious since we *could* reuse the `aggregate-prometheus` but we would most likely have to resize the disk at some point or perform some other operational tasks for `aggregate-prometheus` if we use it for this purpose.
