### ISSUE TITLE
Dashboard for the usage, minAllowed and maxAllowed for components scaled by VPA/HVPA and alerts when usage reaches close to maxAllowed

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/gardener#2950]
**How to categorize this issue?**

/area monitoring
/kind post-mortem
/priority normal

**What would you like to be added**:
We need a way to visualize the `minAllowed` and `maxAllowed` configurations (if any) along with the resource usage, requests, limits and VPA recommendations for all the control-plane components scaled by VPA/HVPA. We also need to trigger alerts when the components' resource usage crosses a threshold percentage (`75%`?) of their configured `maxAllowed` value.

We need these for the control-planes of shoots, seeds and gardener.

**Why is this needed**:
We need to react earlier to control-planes going close/reaching their max configured limits and a well known and accessible place for consumers (potentially, shoot cluster admins too?) to see the information.

**Possible solution approach**:
One option for a partial solution (at least for the shoot and seed control-planes) might be to enhance the existing [VPA dashboard](https://github.com/gardener/gardener/blob/master/charts/seed-monitoring/charts/grafana/dashboards/operators/vpa-dashboard.json). If this is not suitable/desirable, we could create a new dashboard.

**Comment by rfranzke** [comment]
/touch
@amshuman-kr what's the plan here? Do you still plan adding the dashboards?

**Comment by rfranzke** [comment]
Given that this issue is open since a long time without anyone picking it up or any attention at all, shall we close it? Or do you plan to invest into something like this @shreyas-s-rao @voelzmo?
