### ISSUE TITLE
☂️ -Issue for graduating KonnectivityTunnel feature gate to beta

### ISSUE THREAD

**Issue by einfachnuralex** [gardener/gardener#2956]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority normal

**What would you like to be added:**
The Konnectivity feature is in alpha state at the moment and has serias stability issues.
It make sense to collect all problems here and track the progress to beta. 

Feel free to add your problems with Konnectivity feature here.

**Comment by einfachnuralex** [comment]
Currently we run version 0.0.12 of the apiserver-network-proxy in a test environment and use the http-connect method of this proxy. 
Kubernetes version is 1.18.6/1.19.2 and we are working on a Openstack environment. Also we tried the GRPC connection method, but with the same results.
We implemented a liveness probe for the proxy which checks if the proxy is crashed, that was a problem in the past because of to low resource limits. 
Also we added the parameter `--delete-existing-uds-file=true` to the server, because a restart of the proxy server sometimes leed to a crash of the proxy because the existing socket file. 

But the connections over the apiserver-network-proxy is still unstable. Sometimes it runs for days without problems, sometimes there are connection issues frequently a day.

As we use shooted seeds the controlplane and extensions run in different clusters and communicate over the proxy. Then the webhook calls fails and the seed is not able to work properly.

Here are some sample errors:
```
I1002 07:04:00.489822       1 trace.go:116] Trace[34027178]: "Call mutating webhook" configuration:gardener-seed-admission-controller,webhook:pods.seed.admission.core.gardener.cloud,resource:/v1, Resource=pods,subresource:,operation:CREATE,UID:7191bc99-d482-4223-939c-9ba046b2304e (started: 2020-10-02 07:03:50.489203698 +0000 UTC m=+59064.563525480) (total time: 10.000557727s):             
W1002 07:04:00.489909       1 dispatcher.go:169] Failed calling webhook, failing open pods.seed.admission.core.gardener.cloud: failed calling webhook "pods.seed.admission.core.gardener.cloud": Post https://gardener-seed-admission-controller.garden.svc:443/webhooks/mutate-pods?timeout=10s: context deadline exceeded
E1002 07:04:00.489935       1 dispatcher.go:170] failed calling webhook "pods.seed.admission.core.gardener.cloud": Post https://gardener-seed-admission-controller.garden.svc:443/webhooks/mutate-pods?timeout=10s: context deadline exceeded
---
I1002 07:06:30.931402       1 trace.go:116] Trace[1926132325]: "Call mutating webhook" configuration:gardener-extension-provider-openstack,webhook:controlplane.openstack 
.extensions.gardener.cloud,resource:apps/v1, Resource=deployments,subresource:,operation:UPDATE,UID:f06331e7-ab7d-43a8-9173-26a9e3eefe07 (started: 2020-10-02 07:06:20.90 
8218043 +0000 UTC m=+59214.982539840) (total time: 10.023127502s):
W1002 07:06:30.938962       1 dispatcher.go:181] Failed calling webhook, failing closed controlplane.openstack.extensions.gardener.cloud: failed calling webhook "control 
plane.openstack.extensions.gardener.cloud": Post https://gardener-extension-provider-openstack.extension-provider-openstack-ddnsg.svc:443/controlplane?timeout=30s: net/h 
ttp: TLS handshake timeout
---
I1002 07:08:40.004592       1 trace.go:116] Trace[1918653169]: "Call mutating webhook" configuration:vpa-webhook-config,webhook:vpa.k8s.io,resource:autoscaling.k8s.io/v1, Resource=verticalpodautoscalers,subresource:,operation:UPDATE,UID:383f07ab-c9cf-4db2-81ce-bda1d162a74b (started: 2020-10-02 07:08:29.991618038 +0000 UTC m=+59344.065939822) (total time: 10.012919374s):
E1002 07:08:40.004980       1 dispatcher.go:170] failed calling webhook "vpa.k8s.io": Post https://vpa-webhook.arden.svc:443/?timeout=30s: net/http: TLS handshake timeout
```

**Comment by ialidzhikov** [comment]
ping @DockToFuture

**Comment by mvladev** [comment]
After #3399 is merged, I'll create an additional PR that would also allow for a separate deployment of `konnectivity-server` even if SNI is not enabled.
