### ISSUE TITLE
Update VPA to vertical-pod-autoscaler-0.9.0

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/gardener#2961]
**How to categorize this issue?**

/area auto-scaling
/kind enhancement
/priority normal

**What would you like to be added**:
Update VPA to [vertical-pod-autoscaler-0.9.0](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.9.0)

**Why is this needed**:
1. Allow custom timeout value for webhook calls [kubernetes/autoscaler#3549](https://github.com/kubernetes/autoscaler/pull/3549) can help us revert https://github.com/gardener/gardener/pull/2802 while still solving https://github.com/gardener/gardener/issues/2779 by a simple change to the webhook timeout config in the charts.
1. VPA - Always process OOM samples [kubernetes/autoscaler#3079](https://github.com/kubernetes/autoscaler/pull/3079) can address https://github.com/gardener/gardener/issues/2890 by reacting better to oomkills.
1. CLI flags for VPA recommender aggregations config [kubernetes/autoscaler#2905](https://github.com/kubernetes/autoscaler/pull/2905) can help us configure VPA to scale down recommendations faster than `24h` (perhaps as quickly as after `2h`). That was the rationale behind this PR in the first place. But aggressive scale downs will only exacerbate the spike-handling problem we have been increasingly facing with the VPA recommender. Perhaps we should go a bit slow on this one.

cc @wyb1 @ggaurav10 @rfranzke @vlerenc @ialidzhikov @kallurbsk @istvanballok

**Comment by vpnachev** [comment]
> Allow custom timeout value for webhook calls kubernetes/autoscaler#3549 can help us revert #2802 while still solving #2779 by a simple change to the webhook timeout config in the charts.

What is the benefit from reverting it? Now we have full control over the configuration and can adjust it easily to our needs.

**Comment by amshuman-kr** [comment]
> What is the benefit from reverting it? Now we have full control over the configuration and can adjust it easily to our needs.

Only hypothetical. We do not have to duplicate possible future changes to other parts of the webhook configuration that are not directly of interest to us.
