### ISSUE TITLE
Customize annotations on vpn-shoot service

### ISSUE THREAD

**Issue by tareksha** [gardener/gardener#2964]
**How to categorize this issue?**
/area audit-logging
/area monitoring
/area networking
/area security

**What would you like to be added**:

The ability to add custom annotations to the managed service `vpn-shoot` in `kube-system` namespace inside the shoot. Right now the service is pretty much static and not configurable:
https://github.com/gardener/gardener/blob/v1.11.1/charts/shoot-core/components/charts/vpn-shoot/templates/service.yaml

**Why is this needed**:

Adding annotations allows to configure some properties in the underlying ELB that is created in AWS. Specifically speaking, adding these annotations causes the service controller to configure access logs on the load balancer:
* `service.beta.kubernetes.io/aws-load-balancer-access-log-enabled`
* `service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name`
* `service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix`

more info here
https://kubernetes.io/docs/concepts/services-networking/service/#elb-access-logs-on-aws

**Comment by danielfoehrKn** [comment]
I wonder if this is rather an issue for the AWS provider - or could that be implemented in the Gardener?

Not sure if that should be implemented as a generic possibility to add Annotations to resources in the Shoot - or expose functionality via the `providerConfig` where the provider then adds a webhook.

**Comment by rfranzke** [comment]
This is a
/duplicate #2705

Generally, the Shoot API cannot cater for all possible, not-foreseeable use-cases. In #2705 it is being discussed to allow adding a set of annotations for all components **without** fine-granular configurability (i.e., which of those annotations are added to which resource). The proper solution for this is to build a webhook that adds whatever you need to whatever resource you want.
