### ISSUE TITLE
Golang race detector finds races in Gardener Code

### ISSUE THREAD

**Issue by BeckerMax** [gardener/gardener#2965]
Running the [data race detector](https://golang.org/doc/articles/race_detector.html) on Garden components detects multiple races. This issue is meant for discussing how we proceed with the findings.

Background:
My goal was to find a test setup which detects issues coming from shared access to data structures like https://github.com/gardener/gardener/pull/2860. The issue #2860 was caused by shared access on the same slice. This would qualify as a race the detector could find if multiple workers would modify the [admission plugins object](https://github.com/vpnachev/gardener/blob/684ba8a6fea0221ba74583f5e9fd818fbb5f6a84/pkg/operation/botanist/controlplane.go#L1066) concurrently. My assumption is that this could occur if multiple Shoots with modifications to the admission plugins would be reconciled in parallel. 
In order to provoke the error I built the gardener binaries with the `--race` flag and ran them locally. Multiple races were detected unrelated to the above issue.

Open points:
- Analyze criticality of the detected races for the different gardener binaries.
- Possibly run the race detector (for a limited time) on dev. To be kept in mind: The cost of race detection varies by program, but for a typical program, memory usage may increase by 5-10x and execution time by 2-20x.

Tasks:
- [ ] Build a race detector enabled container images flavor and run them on dev (permanently and when we do release validation).

/area control-plane
/area testing
/area quality
/priority normal
/kind discussion

**Comment by BeckerMax** [comment]
Next step is to run Gardener locally with the `-race` flag. Create a few Shoots and then look at the findings. Compile the findings of the race detector and see wether they are actionable. Post the findings into this issue.

**Comment by acumino** [comment]
/reopen
/lifecycle/frozen

**Comment by timebertt** [comment]
We discussed this issue again and had the following thoughts:

- running the race detector probably reveals some races out of our control, false positives or even ones that we are not interested in
- we would need some experience about how valuable running the race detector is
- it's unclear what's the behavior on a race (log or panic?) and how we would follow up on races found on landscapes or in CI
- we generally don't want to close it without action, so the next step is to run the race detector locally and clarify these questions

**Comment by ialidzhikov** [comment]
/unassign
as I also don't have capacity to start looking into this issue (it is also unclear what we want to achieve with this issue)

**Comment by rfranzke** [comment]
This issue is stale since > `2y` and never got much attraction. It seems it is not relevant at all. Let's
/close
it now since every attempt to work on this yielded in giving up eventually in favor of other issues with more priority.
If you think different, feel free to reopen it with the intention to work on it in the next time.
