### ISSUE TITLE
CoreDNS dashboard shows always 'No data'

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2966]
**How to categorize this issue?**

/area monitoring
/kind bug
/priority normal

**What happened**:
CoreDNS dashboard shows always 'No data'

**What you expected to happen**:
To have a dashboard that shows data or to do not have a dashboard at all.

**How to reproduce it (as minimally and precisely as possible)**:
1. Navigate to the grafana of a random Shoot

2. Ensure that the the tiles in `CoreDNS` dashboard always show `No data`. Probably the issue is related to the fact that coredns Pods are not listed for selection (`None` is shown instead).

- Gardener version: master

**Comment by wyb1** [comment]
The metric names have changed. I will have to update Prometheus to collect these new metrics and update the dashboard
/assign
