### ISSUE TITLE
Consuming host-attached SSDs for docker-images and/or kubelet

### ISSUE THREAD

**Issue by hardikdr** [gardener/gardener#2976]
**How to categorize this issue?**

/area storage
/kind enhancement
/priority normal

**What would you like to be added**: 
Many of the large/high-end machines in different cloud-providers come with host-attached SSDs nowadays, one such example is the `X1e` series in AWS, [see](https://aws.amazon.com/ec2/instance-types/x1e/). These SSDs could be as large as 2 TBs, generally free, and consumable.

Customers ordering such high-end machines are likely to also have large docker-images and/or large-amount of container logs. Such already attached SSDs could be used for storing such large-data, and avoid attaching a larger root-disk separately for storing the same.

Currently, at the gardener we expect users to always order a fresh root-disk(eg. EBS in AWS) of a certain size, which would be hosting OS, docker(-images), kubelet, etc with this [API](https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml#L46-L55). 

Opening this issue to discuss the possible solutions around, how could an already attached SSD be better utilized for hosting kubelet and docker-images. 
- One of the possible solutions could be, to allow configuring mount paths for kubelet/docker via Shoot, though haven't thought it through in terms of feasibility.

**Why is this needed**: For better utilization of the host-attached SSDs.

**Comment by hardikdr** [comment]
cc @vlerenc @danielfoehrKn

**Comment by vlerenc** [comment]
Opening up here for configuration may be beneficial also for the bare metal and edge use cases where we will have to allow end users to make appropriate use of the given hardware (a lot more than with the current hypervisor provisioned VMs where you get nothing unless you specify it - with only the exception of these high-end and dedicated instance types).

**Comment by majst01** [comment]
Regarding bare metal: We at metal-stack already discussed the possibility to leverage locally attached disks not only for PODs wit our [CSI Driver](https://github.com/metal-stack/csi-driver-lvm), but also for native usage like @hardikdr described. One of the main difficulties is to detect unassigned block devices, format and mount them automatically without any knowledge of the machine setup before and without the risk of destroying potentially important data.

**Comment by rfranzke** [comment]
This issue is open since a long time without anyone picking it up or any attention at all. Is it still relevant or shall we close it?
