### ISSUE TITLE
Add keep-after-project-deletion annotation when adopting namespaces

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#2978]
**How to categorize this issue?**

/area usability
/kind bug
/priority normal

**What happened**:
In my local setup, gcm cleaned up the `garden` project and also namespace, as I don't have any shoots or other resources in the project.
```
time="2020-10-15T08:42:18+02:00" level=info msg="[STALE PROJECT RECONCILE] Project is being marked as 'stale' because it is not being used by any resource" project=garden
time="2020-10-15T08:42:18+02:00" level=info msg="[STALE PROJECT RECONCILE] Project is stale since 2020-07-13 14:41:09 +0200 CEST" project=garden
time="2020-10-15T08:42:18+02:00" level=info msg="[STALE PROJECT RECONCILE] Project will be deleted at 2020-10-11 14:41:09 +0200 CEST" project=garden
time="2020-10-15T08:42:18+02:00" level=info msg="[STALE PROJECT RECONCILE] Deleting Project now because it's auto-delete timestamp is expired" project=garden
```

**What you expected to happen**:
As the `garden` project is a bit of a special case, I would expect, that it won't be marked as `stale` and deleted by the project stale controller. 

**How to reproduce it (as minimally and precisely as possible)**:
- Delete all resources from the `garden` project
- See gcm mark the project as `stale`
- See gcm delete the project after the configured time in the GCM config

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
@gardener/gardener-maintainers WDYT? Should we exclude the `garden` project from being touched by the project stale controller?

**Comment by timuthy** [comment]
> As the garden project is a bit of a special case

Do you mean because of the "protected" setting for a seed?

I personally don't use a `garden` project for my local setup but rather the files in `/example` where the project is called [dev](https://github.com/gardener/gardener/blob/master/example/05-project-dev.yaml).

**Comment by timebertt** [comment]
> > As the garden project is a bit of a special case
> 
> Do you mean because of the "protected" setting for a seed?

Not only because of that. But also, because it is bound to the `garden` namespace, where probably also other important system resources are located, e.g. `gardener-apiserver` and it's config.

> I personally don't use a `garden` project for my local setup but rather the files in `/example` where the project is called [dev](https://github.com/gardener/gardener/blob/master/example/05-project-dev.yaml).

ATM I don't use the `garden` project either, but I have created it some months ago to test some cases with ShootedSeeds or something similar, but deleted all the resources afterwards (thus, it was marked staled).

I would argue, that this is not only a problem in the local development scenario, but also for "production" use-cases. If an operator once tried creating some shooted seeds and deleted them afterwards and just uses a "normal" registered seed, the `garden` project will also be marked as stale and deleted sometime in the future.
In this run, also other resources, like the `gardener-apiserver` and so on might get deleted.

**Comment by timebertt** [comment]
In a talk about this, @timuthy pointed out, that the `garden` project is actually not that special and does not have to be bound to the `garden` namespace, actually (just to clarify, as I was mistaken here).

Also he mentioned, that one could use the `namespace.gardener.cloud/keep-after-project-deletion` annotation in order to prevent gcm from cleaning up the `garden` namespace.
Should we add this to the dev-setup scripts? And maybe also to `charts/gardener/controlplane`?

Also we could add the annotation by default, when creating a project, that uses an existing namespace like proposed in https://github.com/gardener/gardener/pull/2436#pullrequestreview-430599830.

WDYT?

**Comment by timuthy** [comment]
Yep, thanks @timebertt for summing up. I think your latest proposal makes sense.

**Comment by timebertt** [comment]
/title Add keep-after-project-deletion annotation when adopting namespaces

**Comment by rfranzke** [comment]
/unassign @danielfoehrKn 

@timebertt @timuthy: While thinking about the proposed solution I got some doubts about its feasibility:

1. If we add this `keep-after-project-deletion` annotation to the namespace ALWAYS when a `Project` is a created with a `non-nil` `.spec.namespace` field then we will run into issue in Gardener installations that use the Gardener Dashboard. The reason is that the Gardener Dashboard creates `Project`s always with a `non-nil` `.spec.namespace`. Hence, those project namespace will never be cleaned up again (unless the dashboard also deletes the namespace, but that's somewhat ugly).
1. My second thought was to allow annotating the `Project` itself with the `keep-namespace-after-project-deletion` annotation, but this will again open an "attack vector" as it would allow end-users to spam the system, i.e., we will again end-up with orphaned resources.
1. I don't have a good idea how to overcome these limitations, hence, should we simply do nothing and keep it as it is? This would mean that someone has to indeed proactively put the `keep-after-project-deletion` annotation to the namespace when he wants to keep it (like your use-case with the `garden` namespace, @timebertt). All of this works out of the box already.

WDYT? Do you have other thoughts/ideas?

**Comment by timuthy** [comment]
Thanks @rfranzke. I also think it's not too critical and hence I'm fine to offload this task to the operator.

**Comment by timebertt** [comment]
Yes, this isn't too critical, I agree.

Nevertheless, one comment, because I probably understood the initial idea a bit differently (https://github.com/gardener/gardener/pull/2436#pullrequestreview-430599830):

> 1. If we add this `keep-after-project-deletion` annotation to the namespace ALWAYS when a `Project` is a created with a `non-nil` `.spec.namespace` field then we will run into issue in Gardener installations that use the Gardener Dashboard. The reason is that the Gardener Dashboard creates `Project`s always with a `non-nil` `.spec.namespace`. Hence, those project namespace will never be cleaned up again (unless the dashboard also deletes the namespace, but that's somewhat ugly).

I thought, the idea was to add the annotation to the namespace only when **adopting** it, so when a `Project` with a non-nil `spec.namespace` is reconciled for the first time **and** the namespace already exists, but not adding it when `spec.namespace` is set, but the namespace doesn't exist.


Anyways, this will only change for newly created projects, so I additionally propose to add the annotation to the garden namespace in our dev-setup scripts.
WDYT?

**Comment by rfranzke** [comment]
Thanks for the clarification @timebertt, this makes sense! Here is the PR: https://github.com/gardener/gardener/pull/3179
