### ISSUE TITLE
Expose KonnectivityTunnel as feature gate in shoot spec

### ISSUE THREAD

**Issue by DockToFuture** [gardener/gardener#2982]
**How to categorize this issue?**

/kind enhancement
/priority normal

**What would you like to be added**:

Expose `KonnectivityTunnel` as a feature gate in the shoot spec configuration.

**Why is this needed**:

The `KonnectivityTunnel` is another solution for the seed to shoot communication which has a lot of benefits over the `OpenVPN tunnel` solution, especially for private setups as is mentioned [here](https://github.com/gardener/gardener/blob/master/docs/usage/reverse-tunnel.md). At the moment the  `KonnectivityTunnel` can be enabled via featureGates in the [gardenlet](https://github.com/gardener/gardener/blob/master/example/20-componentconfig-gardenlet.yaml#L86) configuration.
Since this feature is not [stable](https://github.com/gardener/gardener/issues/2956) and we are depending on the upstream, we can't replace the `OpenVPN tunnel` solution with it. But it would be good if we can enable it in the shoot spec via a featureGate, to use it for testing or non-productive clusters. This would make setups in private zones much easier and it would not be needed to build provider specific solutions as for example mentioned [here](https://github.com/gardener/gardener-extension-provider-gcp/issues/56) for the gcp-provider.

/cc: @stiller-leser, @dkistner

**Comment by timuthy** [comment]
As discussed, let's make it configurable via a shoot annotation, e.g. `alpha.konnectivity-tunnel.shoot.gardener.cloud`, besides the Gardenlet configuration mentioned in the issue description. (/cc @rfranzke)
