### ISSUE TITLE
Race condition for gardener/controlplane/charts/application chart

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#2983]
**How to categorize this issue?**

/area robustness
/kind bug
/priority normal

**What happened**:
The chart `gardener/charts/gardener/controlplane/charts/application` was used to deploy necessary assets to the virtual garden cluster. Sometimes though, the containing `ServiceAccounts` cannot be created by KCM because of the [ValidatingWebhookConfiguration](https://github.com/gardener/gardener/blob/b7449f036123a01398c3dd10726bde5d5f296538/charts/gardener/controlplane/charts/application/templates/validatingwebhook-admission-controller.yaml#L1) which is part of the very same chart.

**What you expected to happen**:
The `ServiceAccounts` to be reconciled successfully, i.e. `Secrets` with service account tokens are created.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy chart `gardener/charts/gardener/controlplane/charts/application` with `.Values.global.admission.enabled: true`.

**Anything else we need to know?**:
As this is a race condition, the error is not reproducible every time.

/cc @ialidzhikov thanks for the analysis
/cc @Diaphteiros 

**Environment**:

- Gardener version: v1.11.x

**Comment by rfranzke** [comment]
Any idea what we can do to prevent this from happening?

**Comment by timuthy** [comment]
> Any idea what we can do to prevent this from happening?

At the moment I can only think of moving the `ValidatingWebhookConfiguration` to a separate chart.
Do you have another idea?
