### ISSUE TITLE
support for additional architectures

### ISSUE THREAD

**Issue by ezeeyahoo** [gardener/gardener#2986]
Suppose if I want to deploy this service on PPC based cluster. Does it offer solution in that regard?

**Comment by timebertt** [comment]
No, we currently build only linux/amd64 images.

/kind enhancement
/area usability
/title Support for additional architectures

**Comment by ezeeyahoo** [comment]
Would comminity like to consider if I enhance a bit to support PPC64LE architecture?

**Comment by timebertt** [comment]
Hmm, I think in general there should be not so much speaking against support for additional architectures.
Though, I personally can't judge, how big the implications will be and how much interest there is.

@ccwienk @AndreasBurger can we build multi-arch images in our pipelines?
/cc @vasu1124 @vlerenc

**Comment by dguendisch** [comment]
From qualification point of view: we'd need to disclaim that we cannot fully qualify such builds today (i.e. integration tests) due to lack of hardware/software for these architectures.

**Comment by vlerenc** [comment]
Indeed @ezeeyahoo, we were already asked about ARM support and have thought somewhat about that. There are multi-arch images, but then again we would increase network traffic with them. It may make more sense to have and pull dedicated images per worker pool, but that is somewhat more effort, especially when in mixed mode with other architectures.

In the end, it's a matter of bandwidth and pull, but we are generally open for contributions. Testing may be challenging though and we would need community support for that.

**Comment by ezeeyahoo** [comment]
Thanks for responses

I am wondering, where can I test the deployment and what is minimum deployment requirement component-wise that I have to build and test. My current status is I have got docker image ready to be tested.

**Comment by ezeeyahoo** [comment]
Thanks for responses

I am wondering, ~~where can I test the deployment and~~(going through documentation) what is minimum deployment requirement component-wise that I have to build and test. My current status is I have got docker image of gardener ready to be testedtested and currently working on gardenctl.

**Comment by gerrith3** [comment]
HI all - what kind of hardware support do you need?  From a ppc64le/IBM Power brand perspective, we have a number of options, our preferred is just to set up and use Travis CI today, although more CI integrations with our Power Cloud are coming.  We can also provide free access to VMs via a partnership with OSL:  https://osuosl.org/services/powerdev/ .  If you want to go that route, let me know, I'm willing to sponsor the project to get you VM access.  

As far as customer demand, we currently have a large customer/ISV/partner asking us to look into this.  I believe they are using gardener today on Intel and hoping to use it on Power as well.  Apologies for not seeing this earlier....  Let me know if you have any other questions.  @ezeeyahoo is trying to figure out what it might take to port this and may be able to help with any porting activity to get this going.  Combined with a regular CI environment (btw, we also have Jenkins if that's what you prefer over at OSL, I think at the same link above) we should have a path forward.
