### ISSUE TITLE
Make DNS Entry TTL configurable

### ISSUE THREAD

**Issue by schrodit** [gardener/gardener#2998]
**How to categorize this issue?**

/kind enhancement
/priority normal

**What would you like to be added**:

The ttl of the DNS entry deployed by the gardenlet is currently set to [120](https://github.com/gardener/gardener/blob/master/charts/seed-dns/entry/values.yaml#L3).
Some dns providers enforce a minimum ttl of more than 120 e.g. 300.

To support such dns providers, it should be possible to make the ttl configurable.

**Comment by schrodit** [comment]
The gardenlet could omit the dnsentry ttl and rely on the dns controller to set an appropriate default.

The ttl value would be configured using the controller registration and it would be possible to set different ttl values depending on the dns provider.

**Comment by timuthy** [comment]
> The gardenlet could omit the dnsentry ttl and rely on the dns controller to set an appropriate default.
> 
> The ttl value would be configured using the controller registration and it would be possible to set different ttl values depending on the dns provider.

I think that's a valid approach. Opinions @gardener/gardener-maintainers?

**Comment by rfranzke** [comment]
Generally, yes, sounds good, but where would we configure the 120s that we use today? If we completely rely on the controller registrations then we would have an "incompatible" change because you have to sync them again when updating Gardener.

**Comment by schrodit** [comment]
> we would have an "incompatible" change because you have to sync them again when updating Gardener
That change would also requires a change in the [dns contract](https://github.com/gardener/gardener/blob/master/docs/extensions/dns.md#what-needs-to-be-implemented-to-support-a-new-dns-provider).
And it would require that the ttl has to be set by the dns extension, which may lead to adjustments in the dns extension controller.

The idea of configuring the ttl in the dns controller was that there are different dns providers with different min ttls.
We also thought about the cloudprofiles but they are not dns provider specific.

Another issue with that approach is that Gardener would not be able to set different ttls for different use cases anymore (e.g. short-living txt entries vs long-living api server records).
Don't know if this is a valid use case.

PS:
In case of the external dns management there would be no change as the default there is already 120: https://github.com/gardener/external-dns-management/blob/master/charts/external-dns-management/values.yaml#L305

**Comment by timuthy** [comment]
> PS:
In case of the external dns management there would be no change as the default there is already 120: https://github.com/gardener/external-dns-management/blob/master/charts/external-dns-management/values.yaml#L305

Then we either risk this incompatible change @rfranzke or we make it configurable via the Gardenlet configuration.
