### ISSUE TITLE
Add Cluster Logging

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#3]
# Stories
* As operator I want cluster logging, so that I can check on my cluster(s).

# Motivation
We need means to get to the logs of our own (cluster)s, but we can influence/bend this BLI. The goal is to improve the work of an operator (of the week), not to provide a 100 % solution. Certain logs are much more important than others, e.g. etcd and machine controller logs are kind of critical, API server is important as well (but may generate a lot of logs, of which I can't tell at the moment if we can hold them all at a reasonable price), but others are less important or don't need to preserved for long. If that's the case, we may not have to stuff them into the logging stack (which makes it less expensive) as we always have the Docker logs on the machines themselves. If e.g. networking fails, it fails immediately. There was never the need to go back two weeks to dig out some old logs, so maybe we do not need to preserve the daemon sets logs in our shoot cluster. Keep that in mind to reasonably form this BLI.

# Acceptance Criteria
- [ ] All pod/container logs are exposed to admins in a remotely accessible UI
  - [ ] Shoot cluster control plane in the seed cluster (if we need, we can cut that down to the more important pods like e.g. etcd and machine controller)
  - [ ] Shoot cluster addons in the shoot cluster (if we need, we can omit that)
- [ ] Historic data is kept for the past two weeks (and truncated if it exceeds a certain unreasonable size)
- [ ] CPU & Memory footprint is reasonable/small (if not we may have to consider having only one stack per seed; in that case we might also rethink our monitoring stack approach)

## Out Of Scope
- Like with the monitoring data we accept the loss of all logs when the Gardener has to drain a seed of its shoot clusters or loses its seed cluster for good and must move the shoot cluster control plane to another seed cluster

# Implementation Proposal
Please check out the EFK stack (Elasticsearch + fluentd + Kibana; see various blogs, e.g. https://logz.io/blog/kubernetes-log-analysis). Is it what we should use?

If yes, should we handle it like the monitoring stack:
* Aim at a logging stack that is co-deployed with every shoot cluster control plane and monitoring stack
* Investigate what needs to be done technically to get to the logs in the shoot cluster namespace in the seed and the kube-system namespace in the shoot
* Find our what needs to be done to contain the costs, i.e. keep historic data for the past two weeks and truncate it if it exceeds a certain unreasonable size

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by vlerenc** [comment]
Ticket is **on hold** until management has decided whether we may do it ourselves or have to wait for some central service.

**Comment by afritzler** [comment]
Any idea what this "center service" would look like?

**Comment by vlerenc** [comment]
Decision is to follow the well established pattern we already went for with the monitoring stack.

**Comment by pkokanov** [comment]
This issue is being worked on in PR #176
