### ISSUE TITLE
Pod Container/Local Disk Quota

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#30]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:45 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/48_

----

# Story
* As operator I want to limit the impact of containers that consume all disk space, so that they dont put the entire node in danger or out of operation.

# Motivation
At present any container that consumes its implicitly created root volume can break down the entire node as there is no quota in place (Dockers /var/lib/docker is hosted on the ephemeral root disk at present together with everything else).

# Acceptance Criteria
- [ ] Ideally constrict a container root volume to a certain quota, so that only the container itself is impacted if it runs out of quota
- [ ] Alternatively, if thats not possible, discuss whether mounting /var/lib/docker separately would help (then however, all containers would be affected and would that improve anything at all, e.g. not sure how operable Docker will be if /var/lib/docker is put together on a single mount point and has no disk space left; will it respond to remote queries and will it be possible to remove a container and its implicit volumes?)
- [ ] Alternatively, if also thats not possible or doesnt make sense, check whether a saturated node would automatically be dumped and recreated if it becomes unresponsive or find out what must be done to achieve this (if nodes are cattle, we still need to terminate the node so that it can be recreated by the autoscaling group)

# Definition of Done

- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Developer documentation: Have you updated our [documentation](https://git.infra.removed/kubernetes/k8s-docs/wiki) and/or the CHANGELOG.txt?

:information_source: Migrated from Jira issue [KUBE-31](https://jtrack.removed/browse/KUBE-31)

**Comment by gardener-robot-ci-1** [comment]
**Comment by [vlerenc](https://github.com/vlerenc)**
_Thursday Jul 20, 2017 at 04:59 GMT_

----

Note by Hardik:

On a side note , I believe it should also be ensured that /var/run/docker.sock , does not get exposed to the Pod/Container running over k8s. Otherwise pod can then configure new docker-client pointed to .sock which in turn can mess up with the host machine.

https://www.lvh.io/posts/dont-expose-the-docker-socket-not-even-to-a-container.html

**Comment by gardener-robot-ci-1** [comment]
**Comment by [vlerenc](https://github.com/vlerenc)**
_Thursday Jul 20, 2017 at 04:59 GMT_

----

Very true, thank you. However, at present I lack the knowledge on how we can secure our cluster. Certainly, privileged containers are a huge problem (a big no-no). In addition, we will need means to limit what a user can mount locally. Some weeks ago we asked us the same question and saw that Kubernetes allows to tune such things via a security context, but we never tried it. Do you know whether this will work (using security contexts) or what do you propose?

**Comment by gardener-robot-ci-1** [comment]
**Comment by [vlerenc](https://github.com/vlerenc)**
_Thursday Jul 20, 2017 at 04:59 GMT_

----

Note by Hardik:

As long as I know , path-specific access restriction with hostPath is not yet implemented in k8s.
Though there is a concept of PodSecurityPolicy(PSP) , which can be used to restrict the set(un-privileged) of users from using the hostPath feature at all.

Have a look:
* https://github.com/kubernetes/kubernetes/blob/master/examples/podsecuritypolicy/rbac/README.md
* https://github.com/kubernetes/kubernetes/issues/39269

**Comment by gardener-robot-ci-1** [comment]
**Comment by [vlerenc](https://github.com/vlerenc)**
_Thursday Jul 20, 2017 at 04:59 GMT_

----

Thanks Hardik.

**Comment by vlerenc** [comment]
https://github.com/gardener/auto-node-repair already takes care of it. https://github.com/gardener/node-controller-manager will replace the functionality.
