### ISSUE TITLE
Invalid credentials error on machineDeployment updates

### ISSUE THREAD

**Issue by prashanth26** [gardener/gardener#3023]
**What happened**:
Invalid Credentials error on rolled out machines

I am seeing this occurring when a machineDeployment has undergone a rolling update (with new machineset/machines) and is pointing to a new set of machineClass (and credentials) and one of the old machine pointing to the old machineClass (and old credentials) is stuck in the deletion and the credentials are outdated. Now with updating the credentials to a new one, only the new machineClass receives the update but the old machineClass doesn't. This seems to be a corner case that we need to improve handling here. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

- Create a machineDeployment with valid credentials.
- Now invalidate the credentials by removing access to it.
- Now trigger a rolling update in parallel by modifying the machineClass. 
- The update fails.
- Now update credentials to the new one on machineDeployment by pointing to new credentials. 
- Now the old machine is still stuck in deletion with old credentials. 

**Anything else we need to know**:
Probably occurs more with clusters in hibernation deletion. 

**Environment**:
Openstack

**Comment by prashanth26** [comment]
Agreed. Even I was confused as to where to keep the issue. But I think it's better solved at g/g.

**Comment by prashanth26** [comment]
I will take a look at this issue. However, will need a few days to start working on this as I want to finish the MCM OOT story for AWS. Will assign it to me when I start working on this.

**Comment by timuthy** [comment]
@prashanth26 can you provide an update, is the issue already being worked on?

**Comment by prashanth26** [comment]
Hi @timuthy ,

I wasn't getting any time to work on this. However, @vpnachev was kind enough to pick it instead of me for now. So I think he is working on this.

**Comment by vpnachev** [comment]
All extension have been fixed, I am closing now this issue.
/close
