### ISSUE TITLE
Cannot retrieve logs or exec in Shoot cluster

### ISSUE THREAD

**Issue by alcasim** [gardener/gardener#305]
Hi, we're suffering an intermittent issue with our shoot clusters from two different gardener environments.

Basically, each time we try to retrieve logs from any pod or exec anything in a pod, we get the same "server misbehaving" error:
`kubectl logs -n kube-system addons-kube-lego-59b74dd564-8h2lc
Error from server: Get https://shoot--msa-sandbox--dex-sbx-cpu-worker-84bb4f499f-rpsvz:10250/containerLogs/kube-system/addons-kube-lego-59b74dd564-8h2lc/kube-lego: dial tcp: lookup shoot--msa-sandbox--dex-sbx-cpu-worker-84bb4f499f-rpsvz on 10.0.0.10:53: server misbehaving`

Same story trying `kubectl exec` or even `helm ls`:
`helm ls
Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp: lookup shoot--msa-sandbox--dex-sbx-cpu-worker-84bb4f499f-rpsvz on 10.0.0.10:53: server misbehaving`

We did some research trying to find a cause for this. We noticed when this happens is usually during a Shoot Reconcile run from Gardener, it keeps stuck on "Waiting until the VPN connection has been established...",  from the gardener-controller logs:
`time="2018-08-02T10:03:29Z" level=info msg="Waiting until the VPN connection has been established..." opid=z5rXSzPO shoot=msa-sandbox/dex-sbx`
`time="2018-08-02T10:03:34Z" level=info msg="Waiting until the VPN connection has been established..." opid=z5rXSzPO shoot=msa-sandbox/dex-sbx`
`time="2018-08-02T10:03:39Z" level=info msg="Waiting until the VPN connection has been established..." opid=z5rXSzPO shoot=msa-sandbox/dex-sbx`
`time="2018-08-02T10:03:44Z" level=info msg="Waiting until the VPN connection has been established..." opid=z5rXSzPO shoot=msa-sandbox/dex-sbx`
`time="2018-08-02T10:03:49Z" level=info msg="Waiting until the VPN connection has been established..." opid=z5rXSzPO shoot=msa-sandbox/dex-sbx`

Sometimes it heals by itself after waiting up to 24h, but it's not something easy to reproduce. It can happen with long-term living shoots or with recently created shoots. I have checked logs from kube-apiserver vpn-seed container and I couldn't see anything abnormal (I cannot check logs in shoot cluster vpn-shoot container because the issue). 

Regarding kube-apiserver container itself, we saw nothing strange but this error, which constantly appears in logs:
`I0723 07:07:01.523481 1 logs.go:49] http: TLS handshake error from 10.244.2.1:54712: EOF`

At this point we would need some help to troubleshoot the root cause, to check if it's related to a possible bug in Gardener, to something strange with our cloud provider (Azure). Can you give us some guidance  on what to check next?

Thanks!

**Comment by rfranzke** [comment]
Is this a Kubernetes 1.11 cluster?

**Comment by alcasim** [comment]
@rfranzke yes, shoot cluster is on 1.11

**Comment by rfranzke** [comment]
Can you check `kubectl get nodes -o wide`. You will probably see nodes that do not report an internal IP. We see this as well with Kubernetes 1.11 and suspect the kubelet to have a bug.
A "workaround" has been implemented in the Gardener (restart of these kubelets) and will be released with the next version. To fix the problem now, you have to recreate the machines (by deleting the corresponding `Machine` objects), or you manually SSH into your VMs and restart the kubelet systemd unit.

**Comment by alcasim** [comment]
@rfranzke thanks for the reply. Looks like we're facing exactly that, as some nodes didn't had internal IP address

I'm trying deleting the machines, but we will also stick to k8s 1.10 until next gardener version is released :)

Thanks for your help! I think this issue can be closed now
