### ISSUE TITLE
Support custom registry-mirror

### ISSUE THREAD

**Issue by mwindower** [gardener/gardener#3064]
**How to categorize this issue?**

/area cost
/kind enhancement
/priority normal

**What would you like to be added**:
An ability to configure a custom registry mirror to use as pull through cache for images from DockerHub.

The docker daemon would need an environment variable like this: `DOCKER_OPTS=--registry-mirror <URL>`

And containerd would need this section in its configuration file:

```
[plugins.cri.registry.mirrors]
  [plugins.cri.registry.mirrors."docker.io"]
    endpoint = ["<uri>"]
```

**Why is this needed**:
Docker limits pull requests starting from 2nd November on: https://docs.docker.com/docker-hub/download-rate-limit/
This means that unauthenticated pulls are rate limited based on the source IP.

With `provider: metal` at metal-stack we hide all cluster traffic behind a single IP.
Therewith we will be hit by this rate limit with clusters > two nodes.

It`s also a cost saving for all providers when a "local" registry mirror is used to cache images.

**Comment by danielfoehrKn** [comment]
I think this is a valid use-case.
Looking at the draft PR I would  opt for putting a custom registry option not into the CloudProfile, but into the Shoot. Possibly on worker pool level even.

@rfranzke  more container runtime specific are spreading across Gardener components. This will most likely only increase as we mostly cover only default container runtime settings. 
I would like to see a dedicated ContainerRuntime Extension for `docker`, `containerd` centralising all container runtime coding (& making it more extensible for future runtimes). 
Have not had time to write up a GEP yet though.

**Comment by rfranzke** [comment]
Let's
/close
this one in favor of #2719 which is an issue for a larger refactoring about the container runtimes in general. When it will be tackled such configuration options can be kept in mind.

**Comment by majst01** [comment]
In the meantime we modified our os-metal-extension https://github.com/metal-stack/os-metal-extension/pull/9 which changes the current docker daemon config in the same way for all our clusters. This mitigates the current docker hub pull limit for our customers.

We will remove this once #2719 is able to configure this per shoot. We can of course help testing !
