### ISSUE TITLE
Shoot deletion is stuck while trying to deploy resources in a namespace with status "Terminating"

### ISSUE THREAD

**Issue by krgostev** [gardener/gardener#3090]
**How to categorize this issue?**
/area control-plane
/kind bug
/priority normal

**What happened**:
Shoot deletion is stuck with error: 
`task "Deploying network policies" failed: retry failed with context deadline exceeded, last error: failed to apply manifests: 8 errors occurred: [could not apply object of kind "NetworkPolicy" "shoot--it--tmxtz-jsk/allow-to-aggregate-prometheus": networkpolicies.networking.k8s.io "allow-to-aggregate-prometheus" is forbidden: unable to create new content in namespace shoot--it--tmxtz-jsk because it is being terminated...`

What happened is this:
1. The shoot namespace in the seed is in terminating status for a long time, so the deletion process fails with: `Flow "Shoot cluster deletion" encountered task errors: [task "Waiting until shoot namespace in Seed has been deleted" failed: retry failed with context deadline exceeded, last error: namespace "shoot--it--tmxtz-jsk" is not yet cleaned up]`
2. The deletion flow starts again and it is stuck as it is trying to deploy components to a namespace that is in status `Terminating`

**What you expected to happen**:
The deletion flow should continue with task "Waiting until shoot namespace in Seed has been deleted" if the shoot namespace in the seed is just hanging in `Terminating` status for some reason. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Ensure that the shoot namespace in the seed is stuck in terminating status. For example, add a finalizer to some object that will never be removed.
2. Try to delete the shoot.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.12.2
- Kubernetes version: Shoot: 1.18.9, Seed: 1.17.12
- Cloud provider or hardware configuration: openstack

**Comment by ialidzhikov** [comment]
Thank you for reporting! I think this issue is recently fixed with https://github.com/gardener/gardener/pull/3085. We will include it in the upcoming v1.12.3 patch release.
Please, feel free to reopen if you have any comments.

/close
