### ISSUE TITLE
Expose max-requests-inflight parameter of kube-apiserver in Shoot

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#3108]
**How to categorize this issue?**

/area usability scalability
/kind enhancement
/priority normal

**What would you like to be added**:
We should expose the `--max-requests-inflight` parameter on the `kube-apiserver` deployment in the `Shoot` resource so that end-users can change it in case their clusters' workloads require it to be higher/lower.

**Why is this needed**:
Mainly for scalability reasons.

**Comment by timuthy** [comment]
What about `--max-mutating-requests-inflight`?

We should consider to cap the value(s) as this can can lead to a DoS, especially if `APIServerSNI` is enabled. WDYT? (/cc @mvladev)
