### ISSUE TITLE
☂️-Issue for upgrading to k/*@v0.19 and controller-runtime@v0.7

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#3109]
**How to categorize this issue?**

/area quality robustness open-source
/kind enhancement
/priority normal

**What would you like to be added**:

[controller-runtime v0.7](https://github.com/kubernetes-sigs/controller-runtime/releases/v0.7.0) was released. We can now go ahead our dependencies to `k/*@v0.19` and `c-r@v0.7.0`.

This issue tracks all the tasks, that have to be done and should be followed up on, as the release is quite big.

**Why is this needed**:
We should adopt the newest improvements from upstream and shouldn't miss anything important during the migration 😄 

| | Status |
| --- | --- |
| ✅| completed |
| ☑️ | partly completed |
| 🚧| in progress |
| ❔| to be clarified |
| ℹ️| interesting, but not relevant (yet) |
| ❌| incomplete |

# To-Dos for g/g
- ✅ vendor `k/*@v1.19`, `c-r@v0.7.0`
- ✅ update our forks: `third_party/forked/kubernetes` (no action required) and `github.com/gardener/kube-openapi`
- ✅ remove `client.Client` implementation in `pkg/client/kubernetes/utils` in favor of `manager.Options.ClientDisableCacheFor` (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1249)
- ✅ adapt all helper functions to use `client.Object` where necessary, switch from `controllerutils.Object` to `client.Object` (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1195)
- ✅ adapt all our reconcilers to the new reconciler interface (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1054)
- ✅ drop our c-r fork, which was vendored in order to include https://github.com/kubernetes-sigs/controller-runtime/pull/1151
- ✅ adapt `extensionshandler.EnqueueRequestsFromMapFunc` and all extensions mappers to upstream interface changes (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1119)
- ✅ remove usage from deperacted/removed helper funcs in `pkg/log` https://github.com/kubernetes-sigs/controller-runtime/pull/1105
- ✅ migrate gardener-seed-admission-controller and shoot extension webhook handlers to controller-runtime handlers in order to adapt to changed admission types (make it work with both `admission/{v1beta1,v1}`) and get rid of custom handling/encoding/decoding logic (ref (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1284))
- ✅ adapt gardenlet bootstrap/cert rotation code to changes in csr client and API (ref https://github.com/kubernetes/kubernetes/pull/91754 and [KEP#1513](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/1513-certificate-signing-request#api-changes-between-v1beta1-and-v1))

# Follow-up tasks for g/g
- ✅ Remove `kutils.KeyFromObject` in favor of `client.ObjectKeyFromObject` (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1224) ➡️ https://github.com/gardener/gardener/pull/3463
- ✅ Use vendored version flag: see [here](https://github.com/gardener/gardener/blob/150c823da993ecfeed8e73ae5725af6092fa4d8a/pkg/version/verflag/verflag.go#L27) ➡️ https://github.com/gardener/gardener/pull/3472
- ✅ Use autoscaling/v2beta2 for Kubernetes 1.12+ [here](https://github.com/gardener/gardener/blob/2ff872d3f2fddfaddca0fb1131e02f78a268d101/pkg/operation/botanist/controlplane.go#L887) ➡️ https://github.com/gardener/gardener/pull/3486
- ✅ Remove `kubernetes.Interface.RESTMapper` in favor of `client.RESTMapper` (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1058, https://github.com/kubernetes-sigs/controller-runtime/pull/1109, ...) ➡️ https://github.com/gardener/gardener/pull/3473
- ✅ remove remaining `meta.Accessor` usages in favor of `client.Object` where applicable (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1195) ➡️ https://github.com/gardener/gardener/pull/3476
- ✅ configure clients to use protobuf when talking to g-api (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1149) ➡️ https://github.com/gardener/gardener/pull/3467
- ✅ add some flags/options to make leader election lock of extension controllers / grm configurable (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1147) ➡️ https://github.com/gardener/gardener/pull/3479
- ✅ remove finalizer-related helper funcs from `pkg/controllerutils` and `extensions/pkg/controller` in favor of `controller-runtime/pkg/controller/controllerutil` (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1104) ➡️ https://github.com/gardener/gardener/pull/3463
- ✅ migrate remaining webhook handlers in extensions and gardener-admission-controller to controller-runtime handlers as well to make it work with both `admission/{v1beta1,v1}`; adapt gardener webhook manifests and extension webhook self-registrations to also accept `admission/v1` (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1284)
- ℹ️ a generic ComponentConfig implementation has been added (ref https://github.com/kubernetes-sigs/controller-runtime/pull/891)

# Changes for extensions/repos vendoring g/g
| | Meaning |
|--|--|
| ⚠️| breaking change / action required |
| 🏃| others, good to have |
| ℹ️| for information only, action depends |

- ⚠️ check the [release notes](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.7.0) for further required actions
- ⚠️ vendor `k/*@v1.19`, `c-r@v0.7.0`
- ⚠️ drop gardener/controller-runtime fork, if vendored
- ⚠️ remove usage of `client.Client` implementation in `pkg/client/kubernetes/utils` in favor of `manager.Options.ClientDisableCacheFor` (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1249)
- ⚠️ `WorkerDelegate.{MachineClass,MachineClassList}` must now return `client.{Object,ObjectList}` instead of `runtime.Object`
- ⚠️ remove usage of `controller.SetupSignalHandlerContext` in favor of `signals.SetupSignalHandler` (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1205)
- ⚠️ leader election is switched to `ConfigMapsLeases` by default, which requires new RBAC permissions for `coordination.v1/lease` (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1144)
- ⚠️ propagate contexts wherever it became necessary now (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1116)
- ⚠️ adapt usage of `handler.EnqueueRequestsFromMapFunc` or `extensionshandler.EnqueueRequestsFromMapper` (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1109)
- ⚠️ adapt to other small self-explanatory breaking changes in gardener's packages
- 🏃 use new leaderelection flags/options
- 🏃 switch from zapr to klogr using the new flags/options/helpers
- ℹ️ default webhook port was changed to 9443 (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1076)
- ℹ️ "successful reconciliation" is no longer logged (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1096)

**Comment by timebertt** [comment]
> we are planning to cut controller-runtime v0.7.0 on or just after 11/19 (two weeks from today)

🎉 
ref https://groups.google.com/g/kubebuilder/c/9r0mqKl5ZFc/m/DUsEex_1AQAJ

**Comment by timebertt** [comment]
[c-r@v0.7.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.7.0) was released

**Comment by timebertt** [comment]
For reference: my progress is on https://github.com/timebertt/gardener/commits/vendor/kk-cr

**Comment by MartinWeindel** [comment]
*Note:* On revendoring an extension you may run into a problem with the dependency `github.com/googleapis/gnostic/openapiv2`. The directory name changed from CamelCase to lowercase.
Depending on your git settings, you may have to delete the directory vendor/github.com/googleapis/gnostic/OpenAPIv2, commit the changes, and add it again after a `make revendor`

**Comment by timebertt** [comment]
/close
as all action items have been resolved.

Summarized some thoughts around consolidating the whole logging stuff in https://github.com/gardener/gardener-resource-manager/issues/66, but this is indeed a separate topic.
