### ISSUE TITLE
Custom CA certs are not activated on the node

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#3112]
**How to categorize this issue?**

/area ops-productivity
/kind bug
/priority normal

**What happened**:
The cluster CA certificate is installed in the /etc/ssl/certs/ROOTCerts.pem file but it is not activated and missing in the /etc/ssl/certs/ca-certificates.crt

Looking into the logs of the service
```bash
$ journalctl -u updatecacerts
-- Logs begin at Wed 2020-11-04 18:36:59 UTC, end at Wed 2020-11-04 19:01:54 UTC. --
Nov 04 18:37:51 ip-10-222-29-135 systemd[1]: Starting Update CA bundle at /etc/ssl/certs/ca-certificates.crt...
Nov 04 18:37:51 ip-10-222-29-135 update-ca-certificates[1247]: Updating certificates in /etc/ssl/certs...
Nov 04 18:37:52 ip-10-222-29-135 update-ca-certificates[1247]: 0 added, 0 removed; done.
Nov 04 18:37:52 ip-10-222-29-135 update-ca-certificates[1247]: Running hooks in /etc/ca-certificates/update.d...
Nov 04 18:37:52 ip-10-222-29-135 update-ca-certificates[1247]: done.
Nov 04 18:38:01 ip-10-222-29-135 systemd[1]: updatecacerts.service: Succeeded.
Nov 04 18:38:01 ip-10-222-29-135 systemd[1]: Finished Update CA bundle at /etc/ssl/certs/ca-certificates.crt.
Nov 04 18:38:08 ip-10-222-29-135.eu-west-1.compute.internal systemd[1]: Condition check resulted in Update CA bundle at /etc/ssl/certs/ca-certificates.crt being skipped.
```
It is executed, but no certificates are added. 
While I am on the node, running 
```bash
$ update-ca-certificates
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```
again does not add the custom certificates.
But using the option `--fresh` it re-adds all certificates including the custom one
```bash
$ update-ca-certificates  --fresh
Clearing symlinks in /etc/ssl/certs...
done.
Updating certificates in /etc/ssl/certs...
127 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```

**What you expected to happen**:
Custom CA certs from the cloudprofile or worker spec and the cluster CA cert to be activated on the nodes.

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster with Garden Linux or Ubuntu (SuSE nodes are not affected) and curl the cluster API - it should fail to verify the cert issuer
```bash
$ curl https://api.foo.bar.shoot.example.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

If the certs are properly activated, the curl should succeed
```bash
$ curl https://api.foo.bar.shoot.example.com
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.12.4
- Kubernetes version (use `kubectl version`): v1.18.9 
- Cloud provider or hardware configuration: Seen on AWS and OpenStack, but should be the same on all cloudproviders.
- Others:

**Comment by cbarbian-sap** [comment]
I don't think that this has fixed the issue.

In order to have running `update-ca-certificates` (with or without --fresh) any effect (on debian'ish OS such as gardenlinux), at least one of the following conditions would have to be fulfilled:
-  the certificate is stored in `/usr/share/ca-certificates` **and** the according filename is listed in `/etc/ca-certificates.conf`   
- the certificate is stored in `/usr/local/share/ca-certificates` with a file suffix `.crt`

Just adding it to some file such as `ROOTcerts.pem` in `/etc/ssl/certs` is useless.
