### ISSUE TITLE
Shoot reconciliation failed with an error when attempting to update the managed resource `extension-worker-mcm-shoot`

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener#3118]
**How to categorize this issue?**

/area ops-productivity
/kind bug
/priority normal

**What happened**:
During DoD activities, we noticed multiple errors where shoot reconciliation failed with an error when attempting to update the managed resource `extension-worker-mcm-shoot` (or sometimes, `extension-controlplane-shoot-webhooks`). This is a transient error that disappears during one of the next retries. However, it may cause multiple clusters in all landscape to fail during a single day, spamming the "clusters with issues" view in the dashboard.

**What you expected to happen**:
No such errors.

**How to reproduce it (as minimally and precisely as possible)**:
Unfortunately, we don't know how to reliably reproduce the issue yet.

**Anything else we need to know?**:
* The dashboard error is similar to `task "Waiting until shoot worker nodes have been reconciled" failed: Error while waiting for Worker shoot--hc-ci--577962-haas/577962-haas to become ready: extension encountered error during reconciliation: Error reconciling worker: could not apply machine-controller-manager shoot chart: could not apply control plane shoot chart for worker 'shoot--hc-ci--577962-haas/577962-haas': could not create or update managed resource 'shoot--hc-ci--577962-haas/extension-worker-mcm-shoot': managedresources.resources.gardener.cloud "extension-worker-mcm-shoot" already exists`
* This error is very strange since the Gardener code that fails with "could not create or update managed resource 'shoot--hc-ci--dmove-1c9-haas/extension-worker-mcm-shoot'" does `controllerutil.CreateOrUpdate`, which should never fail with "already exists". Perhaps it's a caching issue in the client?
* Provider uses image `eu.gcr.io/sap-se-gcr-k8s-public/eu_gcr_io/gardener-project/gardener/extensions/provider-aws:v1.16.0`, it vendors `sigs.k8s.io/controller-runtime v0.6.3`. Could it be somehow related to https://github.com/kubernetes-sigs/controller-runtime/issues/1222? See also https://github.com/gardener/gardener-extension-networking-calico/pull/55 and https://github.com/gardener/gardener/pull/2940.

**Environment**:

- Gardener version: v1.12.3
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.12", GitCommit:"5ec472285121eb6c451e515bc0a7201413872fa3", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS
- Others:

**Comment by stoyanr** [comment]
@timebertt also found the following clues:

We seem to have some problems with short watches in `provider-aws`:

```
$ kail -n extension-provider-aws-tpgxg -l app.kubernetes.io/name=gardener-extension-provider-aws  --since 6h | grep 'reflector.go'
extension-provider-aws-tpgxg/gardener-extension-provider-aws-546cdd99d6-r6vq9[gardener-extension-provider-aws]: W1103 12:29:11.791574       1 reflector.go:405] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: watch of *v1alpha1.ManagedResource ended with: very short watch: sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Unexpected watch close - watch lasted less than a second and no items received
extension-provider-aws-tpgxg/gardener-extension-provider-aws-546cdd99d6-r6vq9[gardener-extension-provider-aws]: W1103 13:14:55.989171       1 reflector.go:405] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: watch of *v1alpha1.ManagedResource ended with: very short watch: sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Unexpected watch close - watch lasted less than a second and no items received
extension-provider-aws-tpgxg/gardener-extension-provider-aws-546cdd99d6-r6vq9[gardener-extension-provider-aws]: W1103 16:09:44.708069       1 reflector.go:405] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: watch of *v1alpha1.ManagedResource ended with: very short watch: sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Unexpected watch close - watch lasted less than a second and no items received
```

Also, I have also seen some strange logs in the Seeds’ API servers like these:
```
shoot--garden--aws-eu6/kube-apiserver-96f56cd77-6rzc8[kube-apiserver]: I1103 16:29:46.966176       1 cacher.go:1220] Forcing watcher close due to unresponsiveness: *unstructured.Unstructured
shoot--garden--aws-eu6/kube-apiserver-96f56cd77-6rzc8[kube-apiserver]: I1103 16:30:02.695585       1 cacher.go:1220] Forcing watcher close due to unresponsiveness: *unstructured.Unstructured
shoot--garden--aws-eu6/kube-apiserver-96f56cd77-6rzc8[kube-apiserver]: I1103 16:30:03.203104       1 cacher.go:1220] Forcing watcher close due to unresponsiveness: *unstructured.Unstructured
shoot--garden--aws-eu6/kube-apiserver-96f56cd77-6rzc8[kube-apiserver]: I1103 16:30:03.372210       1 cacher.go:1220] Forcing watcher close due to unresponsiveness: *unstructured.Unstructured
```

It seems like we have some problems with our watches on the Seeds, so we have to look into this again.
Unfortunately, we don’t have any component-specific metrics about this stuff, so it is really hard to find the root cause here (kind of related to [gardener/gardener#2815](https://github.com/gardener/gardener/issues/2815))

**Comment by stoyanr** [comment]
@timebertt Since we don't have a way to reliably reproduce the issue, do you have a suggestion for a meaningful next step in order to further investigate or fix it? Perhaps adding additional metrics or logs could help?

**Comment by timebertt** [comment]
> @timebertt Since we don't have a way to reliably reproduce the issue, do you have a suggestion for a meaningful next step in order to further investigate or fix it? Perhaps adding additional metrics or logs could help?

Yes, additional metrics will definitely help us to understand such problems a bit better in the future. Although, they will not guarantee, that we will be able to fix them 😉 

Other than that, it might be good to check, if the watch cache in the Seeds' API servers are overflowing again like we saw with the ConfigMaps a few months back.
If that's the case, we can probably work around this by increasing the watch cache size again, upgrading the effected Seeds to 1.19 (to enable dynamic cache sizes) or even better: fix the root cause of the high update rate by teaching grm not to set the last update timestamp on every health check, if the result didn't change (or something similar).

/remove area/ops-productivity
/area scalability robustness

**Comment by dimakow** [comment]
Hi colleagues,
i could reproduce that issue in a dev-cluster of ours with around 2000 HANA-facades (i also opened issue https://github.tools.sap/kubernetes-live/issues-live/issues/155). So it should be also possible for you to reproduce the issue when putting enough load on the API-server.
Regards, Dirk
