### ISSUE TITLE
Seed Grafana failed to load Extensions dashboard

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#3121]
**How to categorize this issue?**

/area monitoring
/kind bug
/priority normal

**What happened**:
Seed Grafana failed to load "Extensions" dashboard (see screenshot). I was able to reproduce it on multiple seed clusters. It worked occasionally when I reloaded the page several times.

<img width="1118" alt="Screen Shot 2020-11-05 at 16 04 51" src="https://user-images.githubusercontent.com/40451181/98258303-fdd80600-1f80-11eb-9f97-c83a5d742da7.png">

**How to reproduce it (as minimally and precisely as possible)**:
1. Open Seed Grafana via `grafana` Ingress in `garden` namespace.
2. Click on `Extensions` dashboard.

/cc @wyb1 

**Environment**:

- Gardener version: v1.12.3

**Comment by wyb1** [comment]
Seems to be related to the datasource. Whenever the datasource is loki, the CPU and Memory usage panels are broken.
![image](https://user-images.githubusercontent.com/8710621/98346400-31b13b00-2016-11eb-91fc-5e6cbeee0923.png)

Whenever the datasource is changed to prometheus and the label is adjusted then the CPU and memory panels work but the logs from loki no longer exist.
![image](https://user-images.githubusercontent.com/8710621/98346843-dcc1f480-2016-11eb-9e2a-693727b90bab.png)

@Kristian-ZH any suggestions on how to get loki working with the Prometheus labels?

**Comment by rfranzke** [comment]
ping @Kristian-ZH @vlvasilev

**Comment by Kristian-ZH** [comment]
I am going to check it, but on the first look it could be related to known issue where we hit the inodes limit of the disk with Loki chunks. This causes Loki to break quite often

**Comment by Kristian-ZH** [comment]
Hmm i checked and can not see any issues at the moment. We had an issue before, where the Loki was constantly scaled-up/down because of the misconfigured hvpa. This issue was fixed and currently the dashboards are looking fine.
Can you please recheck if everything is working as expected @timuthy @wyb1 ?

**Comment by timuthy** [comment]
I don't experience the issue at the moment, either. Thanks for checking @Kristian-ZH.
/close
