### ISSUE TITLE
API Server Rate Limiting Shoot Grafana Dashboard

### ISSUE THREAD

**Issue by lumi017** [gardener/gardener#3127]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority critical

**What would you like to be added**:
We currently have no visibility on rate limiting consumption of the Gardener cluster. We should have the metrics available and a Grafana dashboard to provide the visibility over the consumption.

**Why is this needed**:
Help to debug issues due to rate limiting.

**Comment by timebertt** [comment]
Can you further specify, which "rate limits" you are talking about? If I get it right, this is about the API server side throttling of requests, correct?

/area monitoring
/cc @wyb1 @istvanballok

**Comment by lumi017** [comment]
Yes

**Comment by wyb1** [comment]
@lumi017 would this metric be sufficient? https://github.com/kubernetes/kubernetes/blob/40ef0ad6e938c8b5bf827e6dbce68f1ad2b25900/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L122

We would add the metric as described in this issue  #3225 and add a dashboard for the shoot API Servers.

**Comment by lumi017** [comment]
This is a low hanging fruit which is fast to add. What would be better is to have more detail so you can see by verb such as GET, PUT, CREATE, UPDATE, PATCH, DELETE, etc.
