### ISSUE TITLE
Deactivate the kubeconfig provided in Gardener dashboard

### ISSUE THREAD

**Issue by dimakow** [gardener/gardener#3138]
/area security
/kind enhancement
/priority normal

**What would you like to be added**:
Hello gardener team,
please provide the possibility to deactivate the admin-kubeconfig accessible in Gardener dashboard.

**Why is this needed**:
We are already creating & rotating a kubeconfig each 24h with the help of service accounts. Since we do not need the gardener provided kubeconfig, we would like to disable it completely.

**Comment by rfranzke** [comment]
/touch
Now that #5220 was promoted we could look into this issue.

**Comment by rfranzke** [comment]
There is a PR (https://github.com/gardener/gardener/pull/5524) refactoring the entire logic of the end-user kubeconfig handling - it makes sense to base the work on top of this PR and not on top of `master`.
