### ISSUE TITLE
Docker daemon on Shoot nodes doesn't use self signed certificates

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener#316]
Currently the Docker daemon on the shoot machines is not using self signed certificates which might be needed if you want to pull from custom registries with self-signed certs at their endpoints.

We are able to distribute rootCAs on the nodes via the `caBundle` property in the `cloudprofile`. However the docker daemon needs a restart in order to pull those changes.

**Comment by BRuhland** [comment]
e.g. it is not possible to use the internal Artifactory, which is needed for us.
