### ISSUE TITLE
Cleanup v1.10 - v1.14 related code

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#3170]
Since quite some time our testing for v1.10 and v1.11 in the README.md states:

```
[1] Version is technically supported but no longer actively tested. Regressions will go unnoticed.
```

I believe we can proceed with clean up of the handling for these versions for the following reasons:
- we you do a change in g/g or any other component you (as PR author) have to consider whether your change will work (whether the corresponding API version is supported)  in v1.10 or v1.11
- v1.10 and v1.11 are pretty old and IMO it does not bring much value to have these versions listed as `technically supported` when we don't do any testing against them. ` technically supported but no longer actively tested` is a vague statement

/kind cleanup
/priority normal

**Comment by rfranzke** [comment]
Should we also cleanup 1.12 - 1.14?
