### ISSUE TITLE
Unable to create a Shoot with .metadata.generateName 

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#3172]
**How to categorize this issue?**

/kind bug
/kind regression
/priority normal

**What happened**:
According to https://github.com/gardener/gardener/issues/1783 it should be possible to create a Shoot `.metadata.generateName`.
But currently I fail with this operation. I am trying to apply:

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  generateName: test
  namespace: garden-foo
spec:
  # omitted
```

```
$ k apply -f ~/bar.yaml --dry-run=server
error: error when retrieving current configuration of:
Resource: "core.gardener.cloud/v1beta1, Resource=shoots", GroupVersionKind: "core.gardener.cloud/v1beta1, Kind=Shoot"
Name: "", Namespace: "garden-foo"
from server for: "/Users/baz/bar.yaml": resource name may not be empty
```

**What you expected to happen**:
To be able to create a Shoot with `.metadata.generateName `

- Gardener version: v1.12.8
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
Last time I checked, `generateName` didn't work with `k apply` (not only for gardener, but also for k8s core resources).
I think, it always tries to fetch the current state of the object before patching it.

`k create -f` should work, though.
Can you confirm that?

**Comment by ialidzhikov** [comment]
You are right, it works with `k create -f`. I wasn't aware of this difference between apply and create. Thank you for letting me know.

/close
