### ISSUE TITLE
Allow setting Seed spec.settings.loadBalancerServices.annotations via "shoot.gardener.cloud/use-as-seed"

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#3186]
In order to remove the deprecated annotations with https://github.com/gardener/gardener/pull/3185, we should make possible setting the `spec.settings.loadBalancerServices.annotations` field for a ShootedSeed.

**Comment by RaphaelVogel** [comment]
Gardener on CCloud setup for the new domains (e.g. S4) also need this annotations, since we explicitly need to specify the FIP subnet where the LB for the API servers should get their IP from
