### ISSUE TITLE
Update apiserver-network-proxy images

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#3208]
**How to categorize this issue?**

/area networking
/kind enhancement
/priority normal

**What would you like to be added**:
There are new releases of https://github.com/kubernetes-sigs/apiserver-network-proxy - by the time of writing this the latest version is v0.0.14, we are still using v0.0.12. v0.0.13 includes also https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/112.

/cc @DockToFuture @mvladev

**Comment by mvladev** [comment]
I'll work on that.
