### ISSUE TITLE
sporadic error message "service account 'default' missing"

### ISSUE THREAD

**Issue by freegroup** [gardener/gardener#324]
from time to time an error message is shown during the cluster creation.
This error goes by after reconciliation/retry but I think this can be optimized ;-)

### error during create a cluster
<img width="843" alt="bildschirmfoto 2018-08-16 um 10 40 30" src="https://user-images.githubusercontent.com/1155039/44198160-ebbfe200-a140-11e8-8e05-5538d40b5790.png">

### error during create another cluster
<img width="888" alt="bildschirmfoto 2018-08-16 um 10 41 00" src="https://user-images.githubusercontent.com/1155039/44198162-ebbfe200-a140-11e8-8e61-09ec1e8595ff.png">

**Comment by rfranzke** [comment]
Background -> quoting myself from slack: "That's a rarely seen race condition which might happen during initial cluster creation. Gardener creates a namespace, and Kubernetes shall create the "default" service account after that. If Gardener is too fast deploying something in that namespace, then this error occurs."
