### ISSUE TITLE
Annotation on Node for triggering kubelet restart

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#3246]
**How to categorize this issue?**

/area ops-productivity control-plane-migration disaster-recovery
/kind enhancement
/priority normal

**What would you like to be added**:

Let's add an annotation, e.g. `node.gardener.cloud/operation=restart-kubelet` or something similar, that will, when added to a `Node` object, cause the `cloud-config` script on that node to restart the kubelet unit.

**Why is this needed**:

We have seen several occurrences in the past, where kubernetes components including the kubelet, were working on outdated data after restoring `etcd-main` and therefore receive error messages from the API server like this one:
```
Nov 25 08:46:15 shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-bhxxn kubelet[2003273]: E1125 08:46:15.079258 2003273 reflector.go:153] object-"shoot--d072924--hc-haas"/"gardener-resource-manager": Failed to list *v1.Secret: secrets "gardener-resource-manager" is forbidden: User "system:node:shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-bhxxn" cannot list resource "secrets" in API group "" in the namespace "shoot--d072924--hc-haas": no relationship found between node "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-bhxxn" and this object
```

Restarting the kubelet helps in such circumstances, so let's add such an annotation in order to partly automate the procedure.
This will save operators quite some effort in such situations and might also be triggered by gardener itself in the future when it knows, that an etcd restoration happened, e.g. as part of a control plane migration.

**Comment by rfranzke** [comment]
Could be done together with #3237

**Comment by vlerenc** [comment]
Good point @timebertt . @plkokanov will we then automatically restart all `kubelets` after control plane migration?

**Comment by plkokanov** [comment]
In the case of the good path we shouldn't run into this problem during CP Migration as an etcd snapshot is taken after the APIServer is shut down. So we would never restore from outdated data.

However, if no recent snapshot could be taken due to some problems on the seed we could potentially hit this issue. So __if possible__, I think we could only limit this to the bad case scenario.
