### ISSUE TITLE
Changing Seed IngressDomain will make Shoot monitoring unavailable until next Shoot Reconcile

### ISSUE THREAD

**Issue by BeckerMax** [gardener/gardener#3281]
/area networking
/kind bug

/priority normal

**What happened**:
After changing the `seed.spec.dns.ingressDomain` the monitoring Ingresses in the Shoot namespaces of the Seed will keep the old ingressDomain until the Shoots get [reconciled](https://github.com/gardener/gardener/blob/6a4526b135da570f567c2fb5bd597bd07e02b915/pkg/gardenlet/controller/shoot/shoot_control_reconcile.go#L386).
If the Shoots are reconciled at a later point in time (for example in a later maintenance window) then Shoot monitoring will be unavailable until then.

**What you expected to happen**:
Changing the ingressDomain in the Seed should not disable Shoot monitoring until the next Shoot reconcile.

**Anything else we need to know?**:
Seeing two options currently:

A) Add migration logic to adapt Ingresses when the Seed is reconciled
B) Making ingressDomain immutable

**Comment by BeckerMax** [comment]
As @timuthy mentioned changing the ingressDomain for ShootedSeeds is currently not possible so I lean towards making the ingressDomain immutable for pure Seeds.

**Comment by rfranzke** [comment]
+1 for making it immutable for now. The argument would be that the domain of a shoot is also immutable.
@BeckerMax would you open a PR?
