### ISSUE TITLE
Administrator are lacking some privileges

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#3288]
**How to categorize this issue?**

/area user-management
/kind enhancement
/priority normal

**What would you like to be added**:

Currently, users bound to the `gardener.cloud:system:administrators` ClusterRole are not able to access events in the `events.k8s.io` API group.
When debugging one particular issue around events, I missed those permissions.

As an operator I would like to either have full access to all API groups or at least to all API groups, that I need to investigate some issues.

There might be a reason for not given operators full admin access, though I'm not sure, what the current argument for this is.

/assign @mvladev @donistz 
Can you comment on that and clarify here?

**Why is this needed**:

**Comment by timebertt** [comment]
> There might be a reason for not given operators full admin access, though I'm not sure, what the current argument for this is.

@donistz @mvladev Can somebody elaborate on that and quickly clarify the reasons here?

**Comment by mvladev** [comment]
From a security standpoint is better to remove add permissions as your go than to remove them post factum.
