### ISSUE TITLE
Ambiguous reference to undefined services / pods in shoot error message

### ISSUE THREAD

**Issue by briantopping** [gardener/gardener#3317]
**How to categorize this issue?**
/area control-plane
/kind enhancement
/priority normal

**What would you like to be added**:
When `.spec.provider.infrastructureConfig.networks` and `.spec.provider.infrastructureConfig.networks` is not defined in a `Shoot`, the fallback is to use `.spec.networks.shootDefaults.services|pods` in the `Seed`. When neither is defined, an error message similar to this is generated:
```
Error syncing gardener-scheduler garden-test5/shoot1: 0/1 seed cluster candidate(s) are eligible for scheduling: {test => invalid networks: [Required value: services is required Required value: pods is required]}"
```
The error message is coming from here (https://github.com/gardener/gardener/blob/master/pkg/scheduler/controller/shoot/scheduler_control.go#L410-L440) which is called here (https://github.com/gardener/gardener/blob/master/pkg/scheduler/controller/shoot/scheduler_control.go#L288-L291).

I fixed it in my situation by stumbling upon `.spec.networks.shootDefaults`, but that is apparently not ideal.

**Why is this needed**:
I would say this is a low priority and was easily resolvable with the team online, but wanted to note the point of confusion.

**Comment by timebertt** [comment]
Yes, there's room for improvement here.
Can you improve the error message?

**Comment by briantopping** [comment]
Hey Tim, I’m thinking if the full element path is available, that would make it so developers don’t have to be in the namespace collision detection game. Reuse of names is good, it reduces semantic complexity. The full path solves both issues?
