### ISSUE TITLE
Unresolved task dependencies should log like lagging ControllerInstallation

### ISSUE THREAD

**Issue by briantopping** [gardener/gardener#3334]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority normal

**What would you like to be added**: The controller that reconciles `ControllerInstallation` objects periodically reports unfinished installations. It would be great if task dependencies were treated the same way. 

**Why is this needed**: As a new user, it took significant time to discover the very elegant task sequencing and management in Gardenlet. One of the things I have had good success with is to generate a debug-level message at the entry of such tasks so a user that enables the messages can see what has been attempted, hopefully with a dump of interesting parameters (but not so much that the logs explode). The downside of this is the code gets littered with these messages and that may diminish the developer experience. 

By integrating a timer task that periodically dumps the the state machine context, a hung process is easily identified because successive messages are the same. Typically, all dependencies of a task will complete with only one or two remaining. These can be more easily checked than searching the code and checking every dependency of the current task.

**Comment by rfranzke** [comment]
Hm, the "hung"/currently executed tasks are populated into the `Shoot`'s `.status.lastOperation.description` field. Isn't this "good enough" for now?

**Comment by briantopping** [comment]
Hi @rfranzke i was just trying to track issues that I thought would be most helpful.
