### ISSUE TITLE
Removing shoot annotation in  "RestartControlPlanePods" fails

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#3351]
**How to categorize this issue?**

/kind bug
/priority normal

**What happened**:

Removing shoot annotation in  "RestartControlPlanePods" fails because it is operating on an outdated version.
This is a temporary situation and should not lead right away to a failed reocniliation.

> Warning  ReconcileError  45s (x5 over 17m)      gardenlet  Flow "Shoot cluster reconciliation" encountered task errors: [task "Restart control plane pods" failed: Operation cannot be fulfilled on shoots.core.gardener.cloud "em-prod-aus": the object has been modified; please apply your changes to the latest version and try again]
**What you expected to happen**:

Possible reason
 - shoot is updated by Gardenlet at the same time

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

[I think the retry of the annotation removal is not high enough](https://github.com/gardener/gardener/blob/4f397c424923fc2c496fc37b0d1f9b3cac996692/pkg/gardenlet/controller/shoot/shoot_control_reconcile.go#L502-L501). We should increase it. Otherwise, the task fails quite instantly leading to more full reconciliations and backoff.
 
**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
> [I think the retry of the annotation removal is not high enough](https://github.com/gardener/gardener/blob/4f397c424923fc2c496fc37b0d1f9b3cac996692/pkg/gardenlet/controller/shoot/shoot_control_reconcile.go#L502-L501). We should increase it. Otherwise, the task fails quite instantly leading to more full reconciliations and backoff.

Another option would be to use patch requests instead. If we do a constant patch for removing the annotation key, this can probably be done without optimistic locking and thus, wouldn't require retry on conflict semantics.
