### ISSUE TITLE
Failed to unbootstrap Seed Cluster (image is required)

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#3378]
/kind bug
/kind regression
/priority normal

**What happened**:
Deletion of Seed cluster does not work.

**What you expected to happen**:
Deletion of Seed cluster to work.

**How to reproduce it (as minimally and precisely as possible)**:

1. Register a v1.18.14 Seed cluster.

2. Make sure that it is successfully bootstrapped and registered.

3. Delete the Seed cluster

4. Make sure that the deboostrap fails with:
```
time="2021-01-12T11:38:54+02:00" level=error msg="Failed to unbootstrap Seed Cluster (image is required)." seed=seed-local
time="2021-01-12T11:39:10+02:00" level=error msg="Failed to unbootstrap Seed Cluster (image is required)." seed=seed-local
time="2021-01-12T11:39:25+02:00" level=error msg="Failed to unbootstrap Seed Cluster (image is required)." seed=seed-local
```

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
Any idea where this is coming from? cc @BeckerMax @mvladev
