### ISSUE TITLE
Robustness and Resilience

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#34]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:45 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/54_

----

# Stories
* As provider I want to ship a robust and resilient system, so that I have less complaints.

# Motivation
The less complaints we get, the more productive our users probably are and the more we can concentrate on adding valuable features.

# Acceptance Criteria
- [ ] Vague: The system behaves correctly, also under stress

:information_source: Migrated from Jira issue [KUBE-86](https://jtrack.removed/browse/KUBE-86)

**Comment by vlerenc** [comment]
We reached a point of high robustness and resilience.
