### ISSUE TITLE
☂️-Issue for missing docs / doc enhancements

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#3405]
**How to categorize this issue?**

/area documentation
/kind enhancement
/priority 3

**What would you like to be added**:

Docs for
- [x] Secrets that are created for every shoot in the project namespace in the garden cluster: list of names, description of each secrets, what's included, how it can be used, ...
- [x] Add docs for missing controllers in https://github.com/gardener/gardener/blob/master/docs/concepts/controller-manager.md 
  - [x] This should be taken care of by work on #4251 
  - [x] `Plant` controller (@acumino)
- [x] gardenlet
  - [x] Shoot care controller (why we garbage collect `Evicted` and `OutOfCpu` pods)
- [x] Revise documentation for local Garden dev environment options, e.g. architectural figure, use-cases, etc.
- [x] etcd/etcd-druid: https://github.com/gardener/gardener/issues/2930
- [x] Explanation of BackupBucketsController and Backupentries flow (@BeckerMax)
- [ ] Gardener Networkmodel overview (VPN, configuration options of networks incl. shootdefaults, Caveates for configuration)
- [ ] Document networking CIDR ranges. Currently the corresponding fields are immutable, so end users cannot change these fields when they need to. We should at least document that the users should consider these networking CIDRs depending on the cluster side - for example podCIDR can be too small for n Nodes.
- [ ] Document CAs and certificates that Gardener creates for a shoot clusters, what they are used for and why they are required.

Please add more ideas!

**Comment by timebertt** [comment]
> Explanation of BackupBucketsController and Backupentries flow (@BeckerMax)

Partly adressed in #3637

**Comment by danielfoehrKn** [comment]
We are missing a detailed Guide on how to set up the Gardener control plane (Gardener API server, GCM, Scheduler, Gardener Admission Controller) end-to-end, similar to the [Gardenlet manual setup Guide](https://github.com/gardener/gardener/blob/master/docs/deployment/deploy_gardenlet_manually.md). 
I think the Gardenlet set up guide was helpful to many adopters and I think it would make sense to have the same thing for the control plane.

The new Guide could cover
- General installation options similar to [this](https://github.com/gardener/gardener/blob/master/docs/deployment/deploy_gardenlet.md)
   - automatically via garden-setup (link to it)
   - via landscaper-component "control-plane" (to come)
   - manually
  
**Manual installation Guide**
- Prerequisites (Virtual Garden API server deployment, etcd cluster, API server setup for API aggregation)
- Installation options
  - Background: Virtual Garden & which advantages & when not to use it (e.g bare metal with full apiserver access). Can be adopted from [here](https://github.com/gardener/garden-setup#concept-the-virtual-cluster).
  - Setup without Virtual Garden (how to deploy helm chart [controlplane](https://github.com/gardener/gardener/tree/master/charts/gardener/controlplane))
  - Setup with virtual Garden
    - deploy chart [application](https://github.com/gardener/gardener/tree/master/charts/gardener/controlplane/charts/application) to virtual Garden
    - deploy chart [runtime](https://github.com/gardener/gardener/tree/master/charts/gardener/controlplane/charts/runtime) to runtime cluster

**Comment by rfranzke** [comment]
Similar to https://github.com/gardener/gardener/issues/1564#issuecomment-1589601533, so
/close
for now
