### ISSUE TITLE
Deletion of Shoot Level Logging Resources Deletes Cluster Level Role and Rolebinding

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#3433]
**How to categorize this issue?**

/area logging
/kind bug
/priority normal
/assign @vlvasilev 

**What happened**:
Each reconciliation of shoot with `testing` purpose ensures that the logging resources in the shoot namespace in the seed are deleted:
https://github.com/gardener/gardener/blob/24121a7c7b3cd0180ff871fca54e995c4d0b9178/pkg/operation/botanist/logging.go#L42-L44

However, this method lists and deletes clusterrole and clusterrolebinding matching `gardener.cloud/role=logging`
https://github.com/gardener/gardener/blob/24121a7c7b3cd0180ff871fca54e995c4d0b9178/pkg/operation/common/utils.go#L331-L358
The effect is that the `fluent-bit-read` [clusterrole](https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-role.yaml) and [clusterrolebinding](https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-role-binding.yaml) are deleted which brakes the cluster controller in the fluent-bit plugin:
```
E0120 10:27:20.049653       1 reflector.go:153] github.com/gardener/gardener/pkg/client/extensions/informers/externalversions/factory.go:117: Failed to list *v1alpha1.Cluster: clusters.extensions.gardener.cloud is forbidden: User "system:serviceaccount:garden:fluent-bit" cannot list
resource "clusters" in API group "extensions.gardener.cloud" at the cluster scope
```

**What you expected to happen**:
The cluster level resources to not be deleted on shoot reconciliation

**How to reproduce it (as minimally and precisely as possible)**:
Reconcile a shoot with testing purpose. Use the following gardenlet feature gate settings
```yaml
Logging: true
CachedRuntimeClients: false
```

**Anything else we need to know?**:
cc @timebertt 
It is not reproducible with
```yaml
CachedRuntimeClients: true
```

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
Nice finding and description @vpnachev  thanks!
