### ISSUE TITLE
Metrics for flow execution

### ISSUE THREAD

**Issue by dkistner** [gardener/gardener#345]
The crucial operations of the Gardener are executed within a flow. A flow consists of ordered steps to create/reconcile/update/delete Shoots or BackupInfrastructures. To achieve more observability regarding those operations we should expose some flow metrics in the Gardener Controller Manager.

For example, we want to know how long took a flow execution and if it succeed or not. Furthermore the metrics should refer to a Shoot (also BackupInfrastructures belong to a Shoot). This could help to improve analyses of Shoot issues.

Those metrics could for example look like this:
```
# metric for a flow duration with classification for Shoot, project and operation executed in the flow.
garden_cm_flow_duration_seconds{project="garden-dev", shoot="test", operation="reconcile"} 90

# metric for a flow duration with classification for Shoot, project and operation executed in the flow.
garden_cm_flow_success{project="garden-dev", shoot="test", operation="reconcile"} 1 # 0 = failed, 1 = success
```

Flows are running not regularly, which means their metrics would only appear when a flow gets completed. We need for each Shoot/BackupInfrastructure own time series. Keeping those metrics in memory would consume much memory and could lead in the worst case to an OOM scenario of the Gardener Controller Manager, which have to be avoided.

Therefore we need a way to deliver those metrics fast to Prometheus after they appear and deallocate the memory.

#### Push Gateway
Flows are similar like batch jobs and the [Prometheus recommandation for batch jobs](https://prometheus.io/docs/practices/instrumentation/#batch-jobs) is using a push gateway. Pushing of metrics can be easily archived by the `prometheus-client-golang` (already used by the Gardener) [push package](https://godoc.org/github.com/prometheus/client_golang/prometheus/push). But then we need to deploy the Prometheus [PushGateway](https://github.com/prometheus/pushgateway) to receive those metrics and pass push configuration to the Gardener.

#### Metrics Cache
We could integrate a metrics cache in the Gardener Controller Manager which behavious something similar like push gateway. For example, we would cache the flow metrics for 5 minutes and expose the cached metrics every time when the `/metrics` endpoint of the Gardener Controller Manager is called.
This would limit the memory consumption. The metrics needs to be timestamped already in the client, which is now possible ([see here](https://github.com/prometheus/client_golang/pull/443)). We would need to implement the cache and the cleanup logic which should not cause much effort.

**Comment by dkistner** [comment]
@mvladev, @vlerenc What do you mean?

**Comment by vlerenc** [comment]
I am not sure how this will look like after the we have done the extensibility epic. The components will be loosely coupled, Gardener will no longer know everything (the actual goal), which will make debugging harder. So, I would think, we should postpone this topic and incorporate such thoughts rather in the extensibility epic (how can we maintain some level of observability when going this path).

**Comment by rfranzke** [comment]
What's the status/plan here?

**Comment by dkistner** [comment]
I think we will not do this in the near future, because we have similar metrics already via the `gardener-metrics-exporter` (not with that detail level). Therefore I will close the issue for now and if we need more detailed insight in the future we can open it again.
