### ISSUE TITLE
Metrics / Dashboards for expiry of Shoot CAs/certs

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#3453]
**How to categorize this issue?**

/area security monitoring
/kind enhancement
/priority normal

**What would you like to be added**:

Metrics and dashboard (panels) for expiration dates of the different Shoot CAs/certs.

**Why is this needed**:

Operators and endusers want to have a good overview when all the CAs and certs used in a shoot will expire.
Currently, all shoot cluster CAs/certs have a validity of 10 years (see [here](https://github.com/gardener/gardener/blob/464f105c111eacc4d00fbcad846fdacff385a70c/pkg/utils/secrets/certificates.go#L288)), so no certs should expire soon. But it would be great to have some dedicated metrics and dashboards for it.

Thanks @dergeberl for the proposal.

**Comment by timebertt** [comment]
/touch
@rfranzke @BeckerMax do we consider this as part of https://github.com/gardener/gardener/issues/3292?

**Comment by rfranzke** [comment]
The certificates will still be valid for `10y` and end-users are responsible for rotating them regularly, so such metrics/dashboards don't seem helpful anymore, do they? We have the `last{Initiation,Completion}Time` fields for the rotation in the `ShootStatus` instead.

**Comment by timebertt** [comment]
Right, then let's 
/close
this
