### ISSUE TITLE
"unbootstrap Seed Cluster" fails with "no matches for kind \"ManagedResource\" in version"

### ISSUE THREAD

**Issue by invidian** [gardener/gardener#3464]
**How to categorize this issue?**

/area TODO
/kind bug
/priority normal

**What happened**:

Created Seed fails with the following condition in status:
```
  - lastTransitionTime: "2021-01-26T12:37:10Z"
    lastUpdateTime: "2021-01-26T13:10:43Z"
    message: "Failed to unbootstrap Seed Cluster (3 errors occurred:\n\t* no matches
      for kind \"ManagedResource\" in version \"resources.gardener.cloud/v1alpha1\"\n\t*
      no matches for kind \"ManagedResource\" in version \"resources.gardener.cloud/v1alpha1\"\n\t*
      no matches for kind \"Etcd\" in version \"druid.gardener.cloud/v1alpha1\"\n\n)."
    reason: DebootstrapFailed
    status: "False"
    type: Bootstrapped
```

**What you expected to happen**:

Creating Shooted Seed cluster works as expected.

**How to reproduce it (as minimally and precisely as possible)**:

I created a Shooted Seed cluster using https://github.com/gardener/gardener-extension-provider-packet, which I currently work on. Then I tried removing this Shooted Seed, for which I had to apply some workarounds to get rid of it, like:
```
kubectl annotate shoot mat-seed-2 confirmation.gardener.cloud/deletion=true
kubectl annotate shoot mat-seed-2 confirmation.gardener.cloud/deletion=true
kubectl annotate shoot mat-seed-2 confirmation.gardener.cloud/deletion=true
kubectl annotate worker mat-seed-2 confirmation.gardener.cloud/deletion=true
kubectl annotate controlplane mat-seed-2-exposure confirmation.gardener.cloud/deletion=true
kubectl annotate controlplane mat-seed-2 confirmation.gardener.cloud/deletion=true
kubectl annotate network mat-seed-2 confirmation.gardener.cloud/deletion=true
kubectl annotate infrastructure mat-seed-2 confirmation.gardener.cloud/deletion=true
for i in extension-controlplane-shoot extension-controlplane-shoot-webhooks referenced-resources; do kubectl patch managedresource $i  -p '{"metadata":{"finalizers":[]}}' --type=merge; done
```

Later on, I created Shooted Seed with the same name again and this occured. After changing the name of the cluster everything worked as expected.

**Anything else we need to know?**:

Checking registered CRDs on Shooted Seed cluster indeed shows, that `ManagedResource` and `Etcd` types are not registered.

**Environment**:

- Gardener version: v1.15.3
- Kubernetes version (use `kubectl version`): v1.19.7
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
I think this issue should be fixed meanwhile due to some recent improvements in this code.
/close
Kindly reopen if you think it still persists.
