### ISSUE TITLE
Using SeedTemplate instead of Seed in GardenletConfiguration

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener#3469]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority normal

**What would you like to be added**:
The design of the `GardenletConfiguration` resource should be improved:
* Currently, it embeds `Seed` in `SeedConfig`: https://github.com/gardener/gardener/blob/a1b0891be6061c9511b7d6038e381c4a1a6c0f04/pkg/gardenlet/apis/config/types.go#L288-L291. Instead, it should embed `SeedTemplate`: https://github.com/gardener/gardener/blob/a1b0891be6061c9511b7d6038e381c4a1a6c0f04/pkg/apis/seedmanagement/v1alpha1/types_managedseed.go#L75-L83 using the internal version in `config` and the external one in `v1alpha1`. 
* Currently, it does not validate the `Seed` embedded via `SeedConfig`. The `SeedTemplate` should be validated by calling a function similar to e.g. https://github.com/gardener/gardener/blob/a1b0891be6061c9511b7d6038e381c4a1a6c0f04/pkg/apis/seedmanagement/validation/managedseed.go#L114-L128. 
* The explicit validation of `SeedConfig` should be removed from `seedmanagement/validation`.
* Potentially, `SeedTemplate` should be also moved to `core` (and its validation to `core/validation`) to avoid the extra dependency to `seedmanagement`. This dependency would not lead to a circular dependency because `GardenletConfiguration` is not used explicitly in `ManagedSeed` (only via a `RawExtension`), but it's perhaps still a good idea to avoid it.

**Why is this needed**:
As discussed in https://github.com/gardener/gardener/pull/3414#discussion_r563806533, it is inconsistent and confusing that `seedConfig` / `seedTemplate` of a ManagedSeed is validated, but the the `seedConfig` of the standalone `GardenletConfiguration` is not validated. Since this is potentially a breaking change, we agreed to do it in a separate PR.

**Comment by stoyanr** [comment]
@timebertt Opened this one as discussed. Do you have any comments?

**Comment by timebertt** [comment]
No comment, sounds promising to me.
