### ISSUE TITLE
Using Invalid instead of BadRequest or Forbidden in admission plugins

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener#3470]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority normal

**What would you like to be added**:

Currently the error handling in most admission plugins is both wrong and inconsistent, since errors due to invalid field values are reported either as `BadRequest` (400) or as `Forbidden` (403). Neither of these HTTP errors is appropriate for this situation.

Instead, such errors should be reported as `Invalid` (413) with a list of field errors as a parameter. The only admission plugin written in this way currently is the `ManagedSeed` admission plugin (not yet merged, see #3416), as this was the proper way identified during the review of #3177.

**Why is this needed**:

Reporting errors appropriately would improve the user experience when an admission fails for some reason:
* The error message would better reflect the root cause of the error (invalid value of a field instead of e.g. bad request).
* Multiple invalid fields could be collected and reported together, instead of reporting just the first error that has been encountered, as is the case already in the `ManagedSeed` admission plugin.

**Comment by stoyanr** [comment]
@timebertt Opened this one as discussed. Do you have any comments?

**Comment by timebertt** [comment]
Nope, sgtm

**Comment by acumino** [comment]
I looked into the issue, 

The 413 HTTP error is defined as follow -
StatusRequestEntityTooLarge        = 413 // RFC 7231, 6.5.11

```
15.5.14.  413 Content Too Large

   The _413 (Content Too Large)_ status code indicates that the server
   is refusing to process a request because the request content is
   larger than the server is willing or able to process.  The server MAY
   terminate the request, if the protocol version in use allows it;
   otherwise, the server MAY close the connection.
```

I don't find this very nice to use error `413` for `errors due to invalid field values`, as this indicates `Content Too Large`.
Also,
`apierrors.NewInvalid()` return the `StatusUnprocessableEntity` i.e 422 http error code.
which is defined as follows - 

```
15.5.21.  422 Unprocessable Content

   The 422 (Unprocessable Content) status code indicates that the server
   understands the content type of the request content (hence a 415
   (Unsupported Media Type) status code is inappropriate), and the
   syntax of the request content is correct, but was unable to process
   the contained instructions.  For example, this status code can be
   sent if an XML request content contains well-formed (i.e.,
   syntactically correct), but semantically erroneous XML instructions.
```

The `422` seems more reasonable. WDYT? @stoyanr

**Comment by acumino** [comment]
cc - @stoyanr @rfranzke @ialidzhikov

**Comment by rfranzke** [comment]
I think this `413` was a typo. Let's use `apierrors.NewInvalid` as suggested in the prose of the description.
