### ISSUE TITLE
Using CreateOrUpdate instead of Reconcile for methods that reconcile creation or update

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener#3471]
**How to categorize this issue?**

/area control-plane
/kind technical-debt
/priority normal

**What would you like to be added**:

Functions and methods named `Reconcile` (or `reconcile`) that actually reconcile the creation or update of a resource in controllers and actuators should be renamed to `CreateOrUpdate` (or `createOrUpdate`), similarly to `Delete` (or `delete`) functions and methods that reconcile the deletion of a resource. 

Of course, methods named `Reconcile` that implement the `reconcile.Reconciler` interface should not be renamed. Typically, the implementation of such methods branches into `CreateOrUpdate` and `Delete` methods depending on whether the object is being deleted or not.

Whenever comments, error messages etc. are referring to "reconciling a resource" vs. "deleting a resource" they should be reworded to refer to "reconciling a creation or update" vs. "reconciling a deletion".

**Why is this needed**:

Currently the name `Reconcile` is used ambiguously for two very different kinds of methods:

* Reconcile a resource in general, usually as a result of implementing `reconcile.Reconciler`.
* Reconcile the creation or an update of a resource, as opposed to the deletion.

This creates confusion for us as developers. It also spills into comments and error messages, e.g. there are references to "reconciling a resource" vs. "deleting a resource" - while in fact, what actually happens is "reconciling a creation or update" vs. "reconciling a deletion". 

We should use the right terminology to avoid confusing ourselves and our users.

**Comment by stoyanr** [comment]
@rfranzke Opened this one as suggested. Do you have any comments?

**Comment by rfranzke** [comment]
I'm fine with this if we do it consistently everywhere.

**Comment by timebertt** [comment]
Personally, I don't see any problems with the current naming.
But if there is indeed confusion for many devs and it is worth the effort to rename it everywhere, I'm also not against changing it.

**Comment by timuthy** [comment]
> Personally, I don't see any problems with the current naming.

+1

**Comment by stoyanr** [comment]
Closing, the feedback so far is rather on the negative side and I don't see this as sufficiently high priority either.
