### ISSUE TITLE
Gardener tested on PPC64LE with minikube single node deployment

### ISSUE THREAD

**Issue by ezeeyahoo** [gardener/gardener#3475]
Hi,

Before making PR, I would request community to review through my progress.
https://github.com/ezeeyahoo/gardener/commits/master

Overview of changes made:-
25a317141aae47d210565b1cdc8dee35a14aca6c - Dockerfile
08289a87bce0183b7240ee97147f516d5800a981 - hack/local-development/dev-setup

Docker base images created successfully

Previous thread: #2986

**Comment by timebertt** [comment]
Please open a (draft) PR, if you want your changes to be reviewed.
Thanks.
/close
