### ISSUE TITLE
Enable private load balancer usage for the kube api servers on the seeds

### ISSUE THREAD

**Issue by hassbert** [gardener/gardener#3478]
**How to categorize this issue?**
/area networking
/area security
/kind enhancement
/kind discussion
/priority normal

**What would you like to be added**:
I would like to add the `to-private-networks` networkpolicy to the dependency watchdog prober.

[here](https://github.com/gardener/gardener/blob/4769e2b102502312967fc9d1c1ab8983eb767104/charts/seed-bootstrap/charts/dependency-watchdog/templates/probe-deployment.yaml#L22-L27):
```
labels:
  ...
  networking.gardener.cloud/to-private-networks: allowed
```

**Why is this needed**:
This would enable the usage of private load balancers as kube api server on the seeds. Usage of private load balancer increases the security and is a requirement for some teams to operate.

**Comment by timebertt** [comment]
Seems like there is no obvious reason for not doing such a change.
Feel free to drop a PR with your improvement.
