### ISSUE TITLE
☂️-Issue for immutable ConfigMaps/Secrets (+ using checksum name suffixes instead of checksum annotations)

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#3484]
**How to categorize this issue?**

/area robustness
/kind enhancement
/priority normal

**What would you like to be added**:
Instead of checksum annotations in the `core/v1.PodTemplate` for mounted `ConfigMap`s/`Secret`s we should use checksum suffixes for the names of those `ConfigMap`s/`Secret`s. Additionally, we should set `.immutable=true` ([ref](https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-immutable)).

**Why is this needed**:
Prevent pods from mounting a `ConfigMap`/`Secret` with outdated/old/incompatible `data`.
Find more details here: https://github.com/gardener/gardener-resource-manager/issues/104

**Comment by timebertt** [comment]
We should also make use of this for gardenlets deployed by `ManagedSeed`s.
Potentially, we can even use it for gardenlets deployed by the chart/landscaper component.
