### ISSUE TITLE
Hanging ControllerInstallations block Seed deletion

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#3495]
**How to categorize this issue?**

/area usability
/kind bug
/priority normal

**What happened**:

When deleting a Seed, we currently see some problems with the cleanup of controller installations:

- the federated seed controller stops to properly report the `ControllerInstallationRequired` condition ([this part](https://github.com/gardener/gardener/blob/03794c4fab012f16625540cd2989ab8f328be93d/pkg/gardenlet/controller/federatedseed/extensions/controllerinstallation_control.go#L196)) when the gardenlet is restarted and the seed is already marked for deletion, because of this early exit: https://github.com/gardener/gardener/blob/03794c4fab012f16625540cd2989ab8f328be93d/pkg/gardenlet/controller/federatedseed/seed_control.go#L179-L182
Therefore, the gardener controller manager won't remove the `ControllerInstallation` in case the last reported condition status is `Required` (see [here](https://github.com/gardener/gardener/blob/9e188335bf4c1a3cc29f75f7a5ecadc24b0fb250/pkg/controllermanager/controller/controllerregistration/controllerregistration_seed_control.go#L363-L365)), and the seed deletion will be block forever.
- When the Seed uses the gardener managed dns for the seed ingress feature (i.e. `seed.spec.dns.provider` is set), a ControllerInstallation for types `DNSProvider/<seed-dns-provider-type>` will hang forever, as it is always computed as a wanted ControllerInstallation and there is no logic for the seed deletion case: https://github.com/gardener/gardener/blob/9e188335bf4c1a3cc29f75f7a5ecadc24b0fb250/pkg/controllermanager/controller/controllerregistration/controllerregistration_seed_control.go#L289-L291

**What you expected to happen**:

The Seed deletion should succeed and should not require any manual cleanup.

**How to reproduce it (as minimally and precisely as possible)**:

For the first bug: delete a Seed and start the gardenlet *afterwards*. See, that the reported `ControllerInstallationRequired` will not be updated anymore.

For the second bug: delete a Seed, that uses the managed ingress dns feature. See, that the `ControllerInstallation` for the dns provider will not be cleaned up.

In both cases the Seed will be stuck in deletion forever.

**Environment**:

- Gardener version: `v1.16.0`

**Comment by timebertt** [comment]
I assume, these are the issues, that you, @stoyanr and @invidian, also encountered. Can you confirm or are there additional bugs?

/assign @timebertt 
for the first bug
and 
/assign @BeckerMax 
for the second bug.

**Comment by timuthy** [comment]
@Diaphteiros IIRC you experienced such issues as well.

**Comment by BeckerMax** [comment]
Second bug is handled in #3511

**Comment by timebertt** [comment]
I observed another race condition which contributes to this issue:

- if the gardenlet is running outside of the seed cluster (e.g. in the dev setup) it needs the kubeconfig secret for the seed (`seed.spec.secretRef`) to access it in order to cleanup any controllerinstallations during seed deletion. 
But if the seed controller finishes its cleanup first before the controllerinstallation controller is done, the secret will already be gone, as the seed controller deletes it after debootstrapping. This way the controllerinstallation controller is stuck, can't cleanup anymore and will block the seed deletion again.

**Comment by rfranzke** [comment]
Interesting @timebertt, thanks for reporting it here. Indeed, we only wait for `Shoot`s and `BackupBucket`s to be gone, but there is also the `ControllerInstallation`s that we should wait for (because they reference the `Seed`).

**Comment by timebertt** [comment]
The remaining two issues described in this issue will be fixed by https://github.com/gardener/gardener/pull/3653

**Comment by BeckerMax** [comment]
Addressed through:
1. https://github.com/gardener/gardener/pull/3653
2. https://github.com/gardener/gardener/pull/3575 
/close
