### ISSUE TITLE
Reserve Excess Cluster Capacity

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#35]
**Issue by [vlerenc](https://github.com/vlerenc)**
_Tuesday Aug 08, 2017 at 05:59 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/71_

----

# Story
* As user I want to be able to schedule my workload (if of reasonable size) in my shoot cluster in seconds, even if all nodes of the shoot cluster are busy, so that I am more productive.
* As operator I want to be able to create new shoot cluster control planes in the seed clusters in seconds, even if all nodes of the seed cluster are busy, so that I am more productive.

# Motivation
The [cluster autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) seems to react only when pods can't be scheduled on any of the current nodes due to insufficient resources. That means, it takes minutes after the event until the pod can be scheduled.

# Acceptance Criteria
- [ ] We run the cluster with excess capacity, a configurable combination of an absolute excess capacity minimum and a percentage, e.g. (calculation here in "nodes", but may be CPU/Memory, too, if that's easier/better): max(1, 5% of the current number of nodes)

# Implementation Proposal
None, but if this can't be done with the current [cluster autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) and nobody works on it, consider whether a contribution would be possible.

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?

**Comment by gardener-robot-ci-1** [comment]
**Comment by [rfranzke](https://github.com/rfranzke)**
_Thursday Aug 31, 2017 at 10:38 GMT_

----

There is an proposal for allowing exactly the above scenario (reserving cluster resources by cluster-autoscaler) which is planned to be release with Kubernetes v1.8 (according to the [1.8 feature tracking spreadsheet](https://docs.google.com/spreadsheets/d/1AFksRDgAt6BGA3OjRNIiO3IyKmA-GU7CXaxbihy48ns/edit#gid=0)).

See this for more information: https://github.com/kubernetes/autoscaler/pull/77/files

**Comment by vlerenc** [comment]
Moved to https://github.com/gardener/machine-controller-manager/issues/26.
