### ISSUE TITLE
Use kubernetes' k8s.io/pkg/apis/meta/v1/Conditions for newer APIs

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#3509]
**How to categorize this issue?**

/kind enhancement
/kind api-change
/priority normal

**What would you like to be added**:

Use the kubernetes' [standardized conditions](https://github.com/kubernetes/enhancements/blob/ade94beb15cfbcb1afcc12445f1691d45e2db062/keps/sig-api-machinery/1623-standardize-conditions/README.md) for newer APIs .

The new standard conditions are available in [apimachinery](https://github.com/kubernetes/apimachinery/blob/1aed267868afc2e68ad04a150e5f80a984e6e367/pkg/apis/meta/v1/types.go#L1354-L1414) version `>= 1.19` together with [helper functions](https://github.com/kubernetes/apimachinery/blob/1aed267868afc2e68ad04a150e5f80a984e6e367/pkg/api/meta/conditions.go#L17-L102). 

**Why is this needed**:

Standardization.

**Comment by timebertt** [comment]
In general, sgtm.
Though, we still have the error codes list in our conditions:
https://github.com/gardener/gardener/blob/21ce5acb214d2d65f2af90ac8a7d0d3e158e4e5d/pkg/apis/core/v1beta1/types_utils.go#L50

Is your proposal then to embed the apimachinery conditions in our condition types?

**Comment by rfranzke** [comment]
We discussed this issue today and decided to
/close
it since it doesn't bring additional value compared to the dev time and the resulting "code verbosity" resulting out of embedding the upstream type into our API.
