### ISSUE TITLE
Allow annotations on shoot Services

### ISSUE THREAD

**Issue by briantopping** [gardener/gardener#3510]
**How to categorize this issue?**
/area control-plane
/kind enhancement
/priority normal

**What would you like to be added**:
As in https://github.com/gardener/gardener/pull/2380, I need the ability to add arbitrary annotations at a seed level to services that are created by shoots. Where the existing PR successfully adds annotations to services that are created for the control plane, shoots also need this facility.

**Why is this needed**:
When a shoot Service of `type: LoadBalancer` is created, the installed load balancer returns an address from default IPAM for the LB. This is insufficient when there are multiple address pools to choose from, for instance.

One way to solve this would be similar to #2380 in that a list of annotations is applied to all services of `type: LoadBalancer` that are created by a shoot. This is helpful, but too coarse. Different shoot Services will have different exposure requirements. 

The most flexible solution is to interpret the list of annotations as regexes and allow the services in the shoot to match against them. In this manner, a Service may include an annotation such as `metallb.universe.tf/address-pool: external5` and if the seed had a regex of `metallb.universe.tf/address-pool: external.*`, the requested annotation would be allowed and added to the Service proxy in the seed cluster as requested (`metallb.universe.tf/address-pool: external5`) when it is created. 

The reason for doing this at the seed level and not the shoot level is to administratively constrain use of load balancer resources by seed.

**Comment by timuthy** [comment]
There are two points I'd like to comment on:
- Using annotations is vague and unstable since it's not really part of an official API contract. We're also about to replace the `use-as-seed` annotation by `ManagedSeed` (see [here](https://github.com/gardener/gardener/blob/master/docs/proposals/13-automated-seed-management.md#managedseed-resource))
- The requirement sounds quite specific because in your case you care about `Service`s while on another operator may needs this for `Ingress` resources or even CRs. Thus, such a requirement may be implemented by a Gardener [extension](https://github.com/gardener/gardener/tree/master/extensions) rather than by the Gardener core itself.

**Comment by danielfoehrKn** [comment]
@timuthy  we should really create a sample gardener-extension with helpful comments to provide an easy starting point. 

That extension would need to inject the annotations into the managed-resources in the Seed cluster. I do not think we have an existing example for this.

**Comment by briantopping** [comment]
Hi guys, thanks for the feedback! I guess this is specific in that my immediate need is to expose a `Service` to the seed cluster load balancer and have it assign the correct address. Load balancers generally do this with annotations, but maybe I should be asking if there are other ways to do this? I don't want to solve a problem that has already been solved elsewhere.

What I know right now about exposing shoot services (and my Gardener experience is limited) is that L7 services can be exposed through nginx, but there's no good way to expose L3 services that require specific ports on addresses from specific address pools. That's the problem I'm trying to solve here. Without pool selection specific to the service being proxied, all shoot services must be exposed using the same pool, and if any of those services require public exposure, they must **all** accept public exposure in order to satisfy the needs of the one public service (since the LB cannot distinguish the requests to choose from the proper pool). Some services really shouldn't be exposed publicly, so there's a likely security problem if such a port was found in a port scan of public addresses.

I actually did think about whether other API objects could benefit from this facility (such as `Ingress`) and I think they could. I agree that annotations are vague and unstable, this is why I proposed regexes for matching so the local administrator could have control over what shoots were allowed to request and could change them as necessary. In a balance between usability, Gardener team workload and product flexibility, regex matching changes the solution from a very expensive and exhaustive undertaking that still may resort to plug-ins for every service that the team had time to retrofit to one where the local administrator can take initiative to whitelist expressions that are allowed with local jurisdiction. I don't understand what drawbacks there are to such a solution.

Anyway, assuming that this can be done as an extension, that's great! I am still unable to find the code where shoot service proxies are created though and I'd like to look at both the code and it's callers to understand expectations.  Thanks!

**Comment by briantopping** [comment]
Hi guys, thanks for the feedback! I guess this is specific in that my immediate need is to expose a shoot `Service` to the seed cluster load balancer and have it assign the appropriate address. Load balancers generally do this with annotations. Maybe I should be asking if there are other ways to do this? I don't want to solve a problem that has already been solved elsewhere. I simply cannot find a means to solve the issue and the shoot clusters that I am porting in are dependent on this facility.

What I know right now about exposing shoot services (and my Gardener experience is limited) is that L7 services can be exposed through nginx, but there's no good way to expose L3 services that require specific ports on addresses from specific address pools. That's the problem I'm trying to solve here. Without pool selection specific to the service being proxied, all shoot services must be exposed using the same pool, and if any of those services require public exposure, they must **all** accept public exposure in order to satisfy the needs of the one public service (since the LB cannot distinguish the requests to choose from the proper pool). Some services really shouldn't be exposed publicly, so there's a likely security problem if such a port was found in a port scan of public addresses.

I actually did think about whether other API objects could benefit from this facility (such as `Ingress`) and I think they could. I agree that annotations are vague and unstable, this is why I proposed regexes for matching so the local administrator could have control over what shoots were allowed to request and could change them as necessary. In a balance between usability, Gardener team workload and product flexibility, regex matching changes the solution from a very expensive and exhaustive undertaking that still may require a retrofit of every provider extension to support it. Instead, this "hack" is actually an elegant way to give local administrators a secure means of allowing shoot owners to take advantage of local facilities in a manner they are already quite comfortable with, as well as stop them from using facilities that they are not authorized for. 

Anyway, assuming that this can be done as an extension, that's great!

**Comment by timuthy** [comment]
These are valid points @briantopping, thanks for clarifying.

As you said:
> Instead, this "hack" is actually an elegant way to give local administrators a secure means of allowing shoot owners to take advantage of local facilities in a manner they are already quite comfortable with, as well as stop them from using facilities that they are not authorized for.

This is a perfect use case for an extension e.g., a security extension which is either very specific to your use-case or more generic so that the Gardener community will profit from it as well.

As I still see this requirement as a functionality on top of Gardener for which we have adequate extension points, I'd refrain from implementing this as an in-tree feature of the core. My recommendation is to have a look at already available extensions like https://github.com/gardener/gardener-extension-shoot-cert-service or https://github.com/gardener/gardener-extension-shoot-dns-service. In addition, I have opened https://github.com/gardener/gardener/issues/3534 to follow @danielfoehrKn's suggestion - help is appreciated :).

Otherwise, can we close this issue as we agree to follow the extension approach?

**Comment by briantopping** [comment]
Thank you @timuthy. After consultation with @danielfoehrKn and @stoyanr, we have discovered that the code in question is [in the Kubevirt organization](https://github.com/kubevirt/cloud-provider-kubevirt) and that's why it could not be found. @stoyanr further explained that the method of proxying for a shoot `Service` is specific to the gardener-kubevirt provider, so it is unlikely that packaging this solution as an extension will have applicability outside of Kubevirt only. This means that the changes really are a PR for cloud-provider-kubevirt, not an extension at all.

Once this is working, I will be able to make a better illustration of the use case. Maybe at that point the discussion will be worth reconsidering, but will close this for now. Very grateful for all of your help, thank you!
