### ISSUE TITLE
[Community] Create sample gardener extension

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#3534]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement
/priority normal

/cc @danielfoehrKn @briantopping

**What would you like to be added**:
For the community it'd be helpful to have a sample Gardener extension, similar to [sample-apiserver](https://github.com/kubernetes/sample-apiserver), which serves as a skeleton for new extensions as well as explains/demonstrates different aspects about building such an extension, esp. with Gardener's [extensions packages](https://github.com/gardener/gardener/tree/master/extensions).

**Why is this needed**:
For understanding and developing Gardener extensions more effectively for the community.

**Comment by rfranzke** [comment]
Should we close this in favor of #5024?

**Comment by berendt** [comment]
Makes sense to me.
