### ISSUE TITLE
Upgrade Loki to v2.0

### ISSUE THREAD

**Issue by Kristian-ZH** [gardener/gardener#3549]
**How to categorize this issue?**

/area logging
/kind enhancement
/priority normal

**What would you like to be added**:
Upgrade Loki to version v2.0.

**Why is this needed**:
With the new version the following features can be used ([docs](https://grafana.com/blog/2020/10/28/loki-2.0-released-transform-logs-as-youre-querying-them-and-set-up-alerts-within-loki/)):
- Extract labels from log lines at query time
- Generate alerts from any query

**Comment by dguendisch** [comment]
I guess you will be upgrading directly to [v2.1.0](https://github.com/grafana/loki/releases/tag/v2.1.0)?

**Comment by Kristian-ZH** [comment]
Yes, when we fix the current bugs in the logging stack I will upgrade Loki to the newest available version

**Comment by rfranzke** [comment]
@Kristian-ZH can you update the issue with your progress?

**Comment by Kristian-ZH** [comment]
I do not have any progress here. Currently I am working on another tasks out of the logging scope, but  @vlvasilev  can take this issue as well

**Comment by Kristian-ZH** [comment]
/close

A PR is merged
