### ISSUE TITLE
Get logs from the shoot nodes

### ISSUE THREAD

**Issue by vlvasilev** [gardener/gardener#3559]
**What would you like to be added**:
A log processor should be installed on the shoot nodes to scrape processes like kubelet, docker, kernel and etc. 

**Why is this needed**:
When a node can't join the cluster or just stops it is unclear the reason for that.
Operators can't access the end  users nodes and is very hard to debug such an issue.

**Comment by vlvasilev** [comment]
@mvladev idea copied from [Slack thread](https://sap-ti.slack.com/archives/C0172CDN3AS/p1613123434203700?thread_ts=1613058001.196200&cid=C0172CDN3AS)
```
The idea is:
- deploy fluent-bit in Shoot cluster + Service account
- add Role + RoleBinding that allows that serviceAccount to perform some RBAC action
- fluent-bit uses the SA token for authentication
  See https://github.com/grafana/loki/blob/8a9b94a8bc8b0ec6d9fd8a408b9d6d7e62b7a04f/pkg/promtail/client/config.go#L30 and https://github.com/prometheus/common/blob/3dae578366e0d25e8257e6a11049b24c091f94f2/config/http_config.go#L90
- Add https://github.com/brancz/kube-rbac-proxy as a sidecar to loki
- It would use --kubeconfig to point to the shoot cluster
- It would have --insecure-listen-address to 0.0.0.0:8080 --upstream to 127.0.0.1:3100
- create service / add to existing service 8080
- Provide custom SubjectAccessReview https://github.com/brancz/kube-rbac-proxy/tree/master/examples/rewrites
- expose that port via 8080 Ingress (edited) 
```
But we have to store the RBAC token on the shoot nodes.
Is this a security vulnerability?

**Comment by mvladev** [comment]
> But we have to store the RBAC token on the shoot nodes.
Is this a security vulnerability?

The same would be said for kubelet's certificates. At the end you'll need to have an  way to authenticate against the Shoot cluster.

**Comment by rfranzke** [comment]
If I understand it correctly then the above proposes to stream the logs over the internet to the Loki in the seed (for every node). Is this correct? If yes, I would expect that this has significant effects on 💰 for traffic and network I/O, doesn't it? Do you have an estimation on how much data would be transferred and how this would increase the costs for a cluster?

**Comment by vlvasilev** [comment]
@rfranzke By receiving all logs from a node on my local set up I get about 50-60 MB per 24 hours.
But if we don't need all of the journald logs then it could be lower.

**Comment by timebertt** [comment]
@vlvasilev @Kristian-ZH 
I just now realized, that we don't keep the logs of shoot system-components running on the shoot worker nodes yet (e.g. `metrics-server` or `csi-driver-node`, etc.
Is this planned / was this in scope of this issue?
