### ISSUE TITLE
Improve Prometheus Grafana Dashboards

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#36]
# Story
- As operator I want useful Prometheus Grafana dashboards, so that I have best observability for my ops tasks.

# Motivation
As discussed in the internal review, please take some time to finalize the dashboards, so that we have a good starting point/it is clear what purpose the dashboards serve.

# Acceptance Criteria
- [ ] Remove duplicate information (some duplicate information makes sense to be repeated in different dashboards, though) 
- [ ] Find better names
  - [x] All Nodes -> Cluster Overview (as-is)
  - [x] Kubernetes Cluster Monitoring -> Node Details (rename Cluster gauges into Node gauges, because that's what they are)
  - [x] Deployments -> Kubernetes Deployments (we saw the data was missing for the API server)
  - [x] Pod -> Kubernetes Pods
  - [ ] Resource Requests -> Resource Requests (the metrics are maybe wrong; let's either fix or remove them)

In addition we should also:
- [ ] Provide guide how to tweak a dashboard, create or remove them

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by alcasim** [comment]
Hi,

I’m wondering how to contribute to this issue, as I’m interested in providing better dashboards for shoot cluster monitoring. I already started something removing the restriction of metric collection on “kube-system” namespace for the shoot cluster, I want to make that switchable so it won’t impact the actual upstream behavior, but if selected it will collect metrics from all namespaces in shoot cluster. 

With my change, I noticed  “Node Details” dashboard works better (some graphs such like “Total usage” starts working).

In my use case, an operator has to be aware of resources used by pods in the different shoot cluster namespaces, no matter what metrics are being collected in the shoot cluster from the application owners. Nevertheless in my use case we are enforcing to collect application metrics into a separate Prometheus instance (we’re also deploying dedicated Grafana and AlertManager), refraining to collect any cluster-related metrics. Application developers will check these metrics accessing the Grafana provided by Gardener.

So, I’m happy to discuss if this change I have tried is interesting for the project and I should fill a PR for it (I’m also happy to reac in Slack if that works better for you).

**Comment by alcasim** [comment]
Also, the information for the "Resource Requests" dashboard is indeed wrong, as requested CPU and memory from seed and shoot containers are used in the dashboard. Limiting to type=shoot in the metrics starting with "kube_pod_container_resource_requests_" solves the issue, when metrics from all namespaces are collected (if limited to kube-system, only requests on kube-system namespace are displayed)

**Comment by vasu1124** [comment]
@mvladev
