### ISSUE TITLE
Seed managed ingress domain is not backward-compatible

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#3652]
**How to categorize this issue?**

/area quality
/kind bug
/priority normal

**What happened**:

Although the Seed field `spec.dns.IngressDomain` is deprecated in favor of `spec.ingress.domain`. 
Only setting the latter field results in 

`#   Error: errors validating the configuration: [seedConfig.spec.ingress.controller.kind: Unsupported value: “”: supported values: “nginx” seedConfig.spec.dns.provider: Required value: ingress controller requires dns.provider to be set]`

**What you expected to happen**:

The Seed field _ingress.domain_ can be set in a backward-compatible way with `dns.IngressDomain` without having to use managed ingress.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by danielfoehrKn** [comment]
cc @BeckerMax

**Comment by BeckerMax** [comment]
/assign
We did not have the usecase in mind that someone switches to the new setting but does not want to enable the managed ingress. But I think it makes sense to support that as it is currently allowed as well. We can define `seedConfig.spec.ingress.controller` as a pointer.

**Comment by rfranzke** [comment]
@BeckerMax can you share your progress on this issue?

**Comment by BeckerMax** [comment]
I gave this issue a relatively low prio because for now one can still use the old setting. I would tackle it in the next week.

**Comment by rfranzke** [comment]
It seems this issue is no longer relevant, shall we close it?

**Comment by BeckerMax** [comment]
Please reopen if there are more use cases for this change.
