### ISSUE TITLE
Collect metrics and dashboards for node disk I/O

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#3667]
**How to categorize this issue?**

/area monitoring
/kind enhancement
/priority normal

**What would you like to be added**:

Configure the Shoots' `node_exporter` to collect disk I/O metrics (`--collector. diskstats`), whitelist the metrics in prometheus and build some charts around it in grafana.

**Why is this needed**:

Having metrics about disk I/O and visualizing them will help operators and endusers identify problems that are caused in limited disk I/O, e.g. if a I/O-heavy application is running into its limits because the underlying PV doesn't provide the required IOPS.

**Comment by timebertt** [comment]
/cc @wyb1 @istvanballok
Would you be able to tackle this one?
Seems like we have recently been bitten by this in some of our Seed clusters. Metrics and dashboards for disk/volume IOPS would support such investigations.

**Comment by wyb1** [comment]
We can tackle this issue. This will be done in two steps:

1. Provide these metrics and a dashboard for the shoots (including shooted seeds).
2. Extend the monitoring of our seeds to also include the metrics. This is necessary to have observability for our seeds that are not shoots.

Step one is straightforward and step 2 will require some more effort.

**Comment by istvanballok** [comment]
/reopen
(we haven't added the dashboards yet)

**Comment by rfranzke** [comment]
Do you still plan to add the dashboards?
