### ISSUE TITLE
De-bootstrapping a seed sometimes fails with "no matches for kind Etcd"

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener#3685]
**How to categorize this issue?**

/area control-plane
/kind bug
/priority normal

**What happened**:

De-bootstrapping a seed sometimes fails with:
```
Failed to unbootstrap Seed Cluster (1 error occurred:\n\t* no matches for kind \"Etcd\" in version \"druid.gardener.cloud/v1alpha1\"\n\n)
```

**What you expected to happen**:
No such errors during seed de-bootstrapping.

**How to reproduce it (as minimally and precisely as possible)**:
* With `master`: delete a Seed resource, wait until the `etcd-druid` managed resource is deleted from the seed cluster, and immediately restart the `gardenlet` responsible for the seed manually.
* With `v1.18.0-dev-7f0ae078d09fe5927d01a4df0821c2bf0d98332a` the issue is reproducible without having to restart gardenlet.

**Anything else we need to know?**:
I believe the issue is caused by the fact that the code in https://github.com/gardener/gardener/blob/e23f221891e9ef45d09e57f553a02e7191f210ed/pkg/operation/botanist/controlplane/etcd/bootstrap.go#L295 is not re-entrant - once the managed resource is deleted, it can no longer succeed because listing the `Etcd` resources requires the CRD, but the CRD had already been deleted.

**Environment**:

- Gardener version: `v1.18.0-dev-7f0ae078d09fe5927d01a4df0821c2bf0d98332a`
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by vpnachev** [comment]
I faced this problem a week ago and prepared a work-in-progress commit https://github.com/gardener/gardener/commit/a9ca7245e63996b5a1737e0f9b9ab22836cad8dd , but still have not time to fully understand the problem and whether my "fix" is correct.

**Comment by stoyanr** [comment]
I am also currently looking into this, since it blocks some integration tests in dev. @vpnachev I think your fix will work, let me try to reproduce the issue locally better and I will test the fix as well.
@rfranzke @BeckerMax I don't think that PR will fix this, since the bug is in the `Destroy` function of a concrete component. I may be wrong though.

**Comment by stoyanr** [comment]
The issue is 100% reproducible with version `v1.18.0-dev-7f0ae078d09fe5927d01a4df0821c2bf0d98332a`, without having to manually restart gardenlet or do anything else. With `master` however it's not, to reproduce it there you have to manually restart `gardenlet` in exactly the right moment (quite tricky to do actually). I believe the issue should be fixed regardless.
