### ISSUE TITLE
mvcc: database space exceeded error beyond 2gb in etcd db 

### ISSUE THREAD

**Issue by nikhilsap** [gardener/gardener#369]
During our test, we were generating load on database of the ETCD.
we were not able to go beyond 2 GB.
once db size reaches 2GB, It throws error.

> mvcc: database space exceeded 

 
As per [community guidelines](https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/limit.md), the default size is 2gb.

**Comment by rfranzke** [comment]
@georgekuruvillak @swapnilgm could you please take a look here?

**Comment by nikhilsap** [comment]
@georgekuruvillak @swapnilgm @rfranzke i am preparing a PR to handle this. 
This PR will have the  relevant configmap parameter (quota-backend-bytes) to handle more than 2 GB.

**Comment by rfranzke** [comment]
Cool, thank you!

**Comment by swapnilgm** [comment]
@nikhilsap Thank you for bringing that to our notice.
