### ISSUE TITLE
Delay hibernation

### ISSUE THREAD

**Issue by petersutter** [gardener/gardener#3699]
**How to categorize this issue?**
/area dev-productivity
/area cost
/kind api-change
/kind enhancement
/priority normal

**What would you like to be added**:
There should be an option to postpone or prepone the next hibernation schedule

**Why is this needed**:
Usually you have a hibernation schedule for your development cluster according to your regular business hours. In case you need to work with the cluster longer than usual, there should be an option to hibernate the cluster at a later point (once).
Contrary, when you need to work with the cluster earlier than usual, it would be good to have an option to wake up the cluster earlier (once).
A workaround of course is to manually adapt the hibernation schedule, but then you have to remember to change it back afterwards, otherwise it will run longer than you usually need it which is wasting money.

/cc @mandelsoft

**Comment by vlerenc** [comment]
> Contrary, when you need to work with the cluster earlier than usual, it would be good to have an option to wake up the cluster earlier (once).

That's actually already possible. You just wake it up manually, is it not?

This leaves only the first request, i.e. to not hibernate at schedule. Frankly, I am not sure whether it's worth the effort, but I agree, it would be handy sometimes, though I usually forget and then it gets hibernated under my hands. ;-)

Anyway, I would assume some new field like `spec.hibernation.[].active` would help already (to turn the schedule off/on). However, implementing something like one-time skip flag like `spec.hibernation.[].skipNextOccurrence` is maybe a bit too/very sophisticated for something like this, wouldn't you say?

**Comment by rfranzke** [comment]
> This leaves only the first request, i.e. to not hibernate at schedule. Frankly, I am not sure whether it's worth the effort, but I agree, it would be handy sometimes, though I usually forget and then it gets hibernated under my hands. ;-)

Probably the Dashboard could show a hint if the time approaches? :)

**Comment by petersutter** [comment]
> That's actually already possible. You just wake it up manually, is it not?

well basically yes, but you have to wait for it to be ready. If you can prepone the schedule, the cluster is already available when you need it. But this scenario is probably less used and I'm fine to skip it. I thought I mention it, as it's basically just the opposite of the other action and maybe not much of a difference when it comes to the implementation, I would assume.

> Anyway, I would assume some new field like spec.hibernation.[].active would help already (to turn the schedule off/on).

Same issue as when manually extending the schedule. If you forget it, it will waste money.

> skipNextOccurrence

If I have a schedule like the following and on Friday evening at 4pm I skip the next occurrence, this would mean that my cluster would hibernate automatically on Tuesday at 5pm the earliest, right?
```yaml
    schedules:
      - start: '00 17 * * 1,2,3,4,5'
        end: '00 06 * * 1,2,3,4,5'
        location: Europe/Berlin
```
How about a field like `spec.hibernation.postponeNextSchedule` with type `time.Duration`.

> Probably the Dashboard could show a hint if the time approaches? :)

Sure, but then it would come in handy if the user could postpone the schedule :)

**Comment by timuthy** [comment]
> How about a field like spec.hibernation.postponeNextSchedule with type time.Duration.

This would be part of the shoot `spec` and will be active until `spec.hibernation.postponeNextSchedule` is reset again which kind of implies that the hibernation control would need to adjust the shoot `spec` again, so that postponing the next hibernation schedule really only happens for the next schedule. I don't think that this would be ideal.

**Comment by timuthy** [comment]
With the cron specification we use today, we almost have everything we need because one can set a schedule for a specific date. The only thing that is missing is an option, that a very specific value is supposed to overrule another, more generic schedule.

**Comment by vlerenc** [comment]
@petersutter @timuthy I am wondering, would you really think about that in advance/is it really worth the effort?

I am actually fine (and did so in the past) to change the hibernation time window, when I thought about it in advance, but in most cases, the cluster "was hibernated under my hands" and the above wouldn't have helped me much.

Just saying/trying to put things in perspective.

**Comment by timuthy** [comment]
> @petersutter @timuthy I am wondering, would you really think about that in advance/is it really worth the effort?
> 

No, I don't think so either. +1

**Comment by petersutter** [comment]
It happened to me several times that I wanted to extend the schedule temporarily and as @mandelsoft approached me with the same inquiry I opened this issue so that it can be discussed.

It's not super critical for me as I also just extend the hibernation schedule as workaround. If it's a major implementation task it's probably not worth the effort.

**Comment by rfranzke** [comment]
From above discussion, it seems that the implementation effort is not fair compared to the benefits of the results, and most likely nobody will work on it anytime soon. Shall we close?
