### ISSUE TITLE
Enable PodSecurityPolicy

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#37]
**Issue by [mvladev](https://github.com/mvladev)**
_Thursday Aug 31, 2017 at 14:57 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/97_

----

As part of for #47. 

Documentation can be found [here]( https://kubernetes.io/docs/concepts/policy/pod-security-policy/). Steps should be:
- [x] Enable `PodSecurityPolicy` admission control for all Shoot clusters
- [ ] Create PSP RBAC roles by default. See this [reference](https://github.com/kubernetes/examples/tree/master/staging/podsecuritypolicy/rbac) for examples.

**Comment by gardener-robot-ci-1** [comment]
**Comment by [vlerenc](https://github.com/vlerenc)**
_Tuesday Sep 05, 2017 at 09:26 GMT_

----

We should find a way to make transparent to the user which modifications we made on top of a vanilla Kubernetes cluster, e.g. in the creation summary or cluster overview page in the Gardener (with links to kubernetes.io to read up more on the subject, e.g. pod security policies).

**Comment by gardener-robot-ci-1** [comment]
**Comment by [vlerenc](https://github.com/vlerenc)**
_Friday Sep 15, 2017 at 03:56 GMT_

----

@i068969 could you please prepare a PR for this?

**Comment by gardener-robot-ci-1** [comment]
**Comment by [vlerenc](https://github.com/vlerenc)**
_Friday Sep 15, 2017 at 03:58 GMT_

----

@d023280 please see my comment from 5th of September. Do you have an idea where we could show such information?

**Comment by gardener-robot-ci-1** [comment]
**Comment by [mvladev](https://github.com/mvladev)**
_Monday Sep 25, 2017 at 08:44 GMT_

----

Work is done in #112. However, because PSP lacks some needed features (ordering/priority) we should postpone this until k8s 1.9

**Comment by gardener-robot-ci-1** [comment]
**Comment by [mvladev](https://github.com/mvladev)**
_Monday Sep 25, 2017 at 13:25 GMT_

----

Removed milestone due to Problems with PSP

**Comment by vlerenc** [comment]
Moved internally.
