### ISSUE TITLE
Do not fire alerts for shoots in deletion

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener#3712]
**How to categorize this issue?**

/area monitoring
/kind bug

**What happened**:

Received `KubeApiserverDown` alerts for shoot clusters that were recently deleted.

**What you expected to happen**:

To not receive `KubeApiserverDown` alerts for recently deleted shoot clusters.

**Comment by wyb1** [comment]
Increasing the time it takes for the alert to fire might be a quick fix, but I would like to investigate why exactly this happens.

**Comment by rfranzke** [comment]
Any progress on this @wyb1?

**Comment by wyb1** [comment]
I found 2 different causes for the alert.
1) Whenever shoots are in deletion Prometheus can no longer scrape the Kube API Server and gets a 403. I think this issue may be unrelated.
```
server returned HTTP status 403 Forbidden
```
If deletion takes more than 5 minutes, we get an alert.

API Server is logging many 
```
1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
```

2) There is no kube-apiserver to scrape so Prometheus assumes it is down. If deletion takes too long the alert will fire.

@rfranzke can we delete the monitoring stack sooner in the deletion flow? I see that it was [changed](https://github.com/gardener/gardener/pull/2900) 6 months ago. If we can't change that I suggest we delete all Prometheus rules at the beginning of the deletion flow.

**Comment by rfranzke** [comment]
I think we could delete Prometheus early, but we should keep Grafana to be able to access Loki logs.
