### ISSUE TITLE
Trigger ManagedSeed gardenlet rollout

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#3724]
**How to categorize this issue?**

/area usability ops-productivity
/kind enhancement
/priority normal

**What would you like to be added**:

Currently, there is no way to manually trigger an immediate rollout of a ManagedSeed's gardenlet.
ManagedSeed rollouts are jittered with `gardenletConfiguration.controllers.managedSeed.syncJitterPeriod`. 
But sometimes an operator wants to shortcut this delay and immediately rollout changes to a gardenlet's configuration.

The trigger could be the same like the one we already have for shoots, extensions resources and managed resources: an annotation `gardener.cloud/operation=reconcile`.

**Comment by timebertt** [comment]
/cc @stoyanr 
WDYT?

**Comment by stoyanr** [comment]
@timebertt Does it make sense to add it for `ManagedSeedSets` as well?

**Comment by timebertt** [comment]
> @timebertt Does it make sense to add it for `ManagedSeedSets` as well?

@stoyanr, yes I think, it would also make sense there.
