### ISSUE TITLE
Update Calico to 3.2.x

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#376]
According to @databus23 we should update to Calico 3.2.x that contains a fix for vSphere/DVS (https://github.com/projectcalico/felix/pull/1838). It will limit the port range to the ephemeral port range, so that ports used for back communication in pods that are masqueraded on the host remain there so that they match the usual security groups for stateless DVS.

**Comment by rfranzke** [comment]
@databus23 @BugRoger will you take this one?
