### ISSUE TITLE
Support envtests with gardener resources

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#3765]
**How to categorize this issue?**

/area dev-productivity testing
/kind enhancement

**What would you like to be added**:

Support for writing integration tests with controller-runtime's `envtest` package that can use gardener API resources.

A promising approach is to add a wrapper for `envtest`, that is spinning up and registering g-api in the test environment.

**Why is this needed**:

`envtest` is great for writing integration tests that can be executed without any infra against a temporary control plane.
Though, we currently can't use gardener resources, as `envtest` primarily only supports `CRDs` but not extension API servers.

### Steps

- [x] add gardener envtest package ➡️ https://github.com/gardener/gardener/pull/3796
- [x] adding an example integration test suite for a controller ➡️ https://github.com/gardener/gardener/pull/3925, see https://github.com/gardener/gardener/blob/278e9b4e584404e14ec1b0d214987a19f4352eb0/pkg/controllermanager/controller/shoot/shoot_retry_control_test.go#L44 also see https://github.com/gardener/gardener/issues/4655
- [x] adding an example integration test suite for a webhook (e.g. GAC audit policy webhook)
- [x] ~contributing upstream and get rid of our fork~ not required anymore with https://github.com/kubernetes-sigs/controller-runtime/pull/1449#issuecomment-863049761
- [x] disable race detector for envtests (see https://github.com/gardener/gardener/issues/4036) ➡️ https://github.com/gardener/gardener/pull/4265
- [x] ~~retry starting g-api on failure to further improve stability during resource contention in pipelines~~ ➡️ not observed in prow anymore, postponed until observed again

**Comment by timebertt** [comment]
Minimum required changes for this scenario in upstream `envtest` package are proposed in https://github.com/kubernetes-sigs/controller-runtime/pull/1449.

**Comment by rfranzke** [comment]
@timebertt can you outline the next steps here so that everybody is aware? Is it only about contributing the required changes upstream and getting rid of our fork again, or is there more?

**Comment by timebertt** [comment]
I updated the issue description with the next steps. However, I'm not working on any of those tasks currently.
/unassign
Others are welcome to contribute to this :)

**Comment by timebertt** [comment]
All tasks are done now!
/close
