### ISSUE TITLE
VPA-updater gets OOM killed

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#3769]
**How to categorize this issue?**

/area scalability
/kind bug
/priority 3

**What happened**:

On Seed cluster that has VPA enabled, the `vpa-updater` of a Shoot cluster is OOMKilled, because it recommends to low memory:

```
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 24 Mar 2021 15:39:51 +0200
      Finished:     Wed, 24 Mar 2021 15:40:38 +0200
    Ready:          False
    Restart Count:  59
    Limits:
      cpu:     44m
      memory:  125Mi
    Requests:
      cpu:     11m
      memory:  50Mi
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
We have a VPA for it, see https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/charts/vpa/charts/runtime/templates/vpa-updater.yaml.
As it's not clear how to continue here and as it doesn't seem to be too relevant as of today, let's
/close
for now until it becomes relevant again.
