### ISSUE TITLE
Confusion about images' latest tag

### ISSUE THREAD

**Issue by dongyingbo** [gardener/gardener#3794]
**How to categorize this issue?**

/area delivery
/kind bug
/priority 3

**What happened**:
Currently the latest tag is not applied to v1.19.x but to v1.16.x. For example it is v1.16.6-dev-87995ad2e1599d2963d538afb9b0ba1eceece816 for admission-controller image when my opening this issue.
When installing with charts/gardener/controlplane admission-controller fails to start because of compatibility.

**What you expected to happen**:
I would expect my first day installation succeeds smoothly and avoid this kind of confusion. Latest label should be applied to latest images.

**How to reproduce it (as minimally and precisely as possible)**:
1. clone this repo
2. with any kubernetes cluster, kind for example, install chart charts/gardener/controlplane
3. you will find admission-controller pod fails to start

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by acumino** [comment]
In general we don't recommend to use latest tag. For gardener the latest tag is pointed at the most recent updated image and it can be hot fix or minor branch.
