### ISSUE TITLE
Investigate Vault Integration with Kubernetes

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#38]
**Issue by [vasu1124](https://github.com/vasu1124)**
_Wednesday Sep 20, 2017 at 12:29 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/110_

----

Vault 0.8.3 now supports Kubernetes integration via the TokenReview API.
https://www.vaultproject.io/docs/auth/kubernetes.html

**Comment by vlerenc** [comment]
Unclear scope and purpose.
