### ISSUE TITLE
Gardenlet panics when deployed to a managed seed

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener#3816]
**How to categorize this issue?**

/area control-plane
/kind bug
/priority 3

**What happened**:

When deployed to a managed seed via a `ManagedSeed` resource, gardenlet panics:

```
panic: need an internal domain secret but found none

goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.Must(...)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:171
github.com/gardener/gardener/pkg/gardenlet/controller.(*GardenletControllerFactory).Run(0xc000f079b8, 0x256c860, 0xc0006f1280, 0xc000254300, 0xc00005e800)
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/factory.go:145 +0x1ce5
github.com/gardener/gardener/cmd/gardenlet/app.(*Gardenlet).startControllers(0xc000991720, 0x256c860, 0xc0006f1280, 0x252d101, 0x251a740)
	/go/src/github.com/gardener/gardener/cmd/gardenlet/app/gardenlet.go:493 +0x152
github.com/gardener/gardener/cmd/gardenlet/app.(*Gardenlet).Run.func1(0x256c860, 0xc0006f1280, 0x256c860, 0xc0006f07c0)
	/go/src/github.com/gardener/gardener/cmd/gardenlet/app/gardenlet.go:445 +0x65
github.com/gardener/gardener/cmd/gardenlet/app.(*Gardenlet).Run(0xc000991720, 0x256c860, 0xc00052ecc0, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/cmd/gardenlet/app/gardenlet.go:475 +0x790
github.com/gardener/gardener/cmd/gardenlet/app.run(0x256c860, 0xc00052ecc0, 0xc0003c08a0, 0x1db7840, 0xc0007d5d60)
	/go/src/github.com/gardener/gardener/cmd/gardenlet/app/gardenlet.go:171 +0x10a
github.com/gardener/gardener/cmd/gardenlet/app.NewCommandStartGardenlet.func1(0xc0007ec840, 0xc00028e6a0, 0x0, 0x1, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/cmd/gardenlet/app/gardenlet.go:201 +0x99
github.com/spf13/cobra.(*Command).execute(0xc0007ec840, 0xc00004c070, 0x1, 0x1, 0xc0007ec840, 0xc00004c070)
	/go/src/github.com/gardener/gardener/vendor/github.com/spf13/cobra/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0007ec840, 0xc00052ecc0, 0x0, 0x1)
	/go/src/github.com/gardener/gardener/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/gardener/gardener/vendor/github.com/spf13/cobra/command.go:895
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/src/github.com/gardener/gardener/vendor/github.com/spf13/cobra/command.go:888
main.main()
	/go/src/github.com/gardener/gardener/cmd/gardenlet/main.go:36 +0x12c
```

**What you expected to happen**:
No panic.

**How to reproduce it (as minimally and precisely as possible)**:
Create a `ManagedSeed` resource with `gardenlet`, or use the `use-as-seed` annotation.

**Anything else we need to know?**:

**Environment**:

- Gardener version: master (d6914db40e716cb1e60c5e726f64ffea4405d8ee)
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by vpnachev** [comment]
Which version/commit of gardener is this?

**Comment by stoyanr** [comment]
* Reproducible with the latest master (0f17e91bee804921fe05f15ee39232c4b8971cee) when testing locally and running managed seed integration tests on dev landscape.
* Seems to be related to #3700, at least this PR introduced the code that actually causes the panic.

**Comment by stoyanr** [comment]
@vpnachev discovered that the issue is caused by a deadlock in the seed creation logic:

* gardenlet looks for an internal domain secret in the seed namespace, e.g. (`seed-xxx`)
* however, at this point this namespace (and the secret) doesn't even exist, it will be created by GCM only after the seed is there (which obviously will never happen since `gardenlet` crashes with the above error).

The workaround would be to manually create the internal domain secret in the seed namespace by copying the one in the `garden` namespace. Doing this when testing locally solves the issue. However, on dev this is not possible, because it fails with the following error:

```
Error from server (cannot create internal domain secret because there can be only one secret with the 'internal-domain' secret role): error when creating "tmp/internal-domain-internal-dev-k8s-ondemand-com.yaml": admission webhook "internal-domain-secret.gardener.cloud" denied the request: cannot create internal domain secret because there can be only one secret with the 'internal-domain' secret role
```
