### ISSUE TITLE
BackupEntries remain in the Source Seed after Control Plane Migration

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#3838]
**How to categorize this issue?**

/area control-plane-migration
/kind bug
/priority 2

**What happened**:
Sometimes after executing Control Plane Migration, the migrated `Shoot`'s `extensions.gardener.cloud/v1alpha1.BackupEntry` is still present in the __Source Seed__.

**What you expected to happen**:
There should be no `BackupEntry` for the migrated `Shoot` in the __Source Seed__

**How to reproduce it (as minimally and precisely as possible)**:
Create a `Shoot` cluster and migrate it. The issue dues not occur with every migration.

**Anything else we need to know?**:
After closer investigation of the issue here is what happens:
During the `Migrate` operation where we remove the `Shoot`'s control plane from the __Source Seed__, the BackupEntry in the Seed is annotated with `gardener.cloud/operation=migrate` which removes its finalizers. Afterwards the resource is deleted. At the end of the `Migrate` operation the `Spec.SeedName` of the `BackupEntry` in the garden cluster is switched to the __Destination Seed__. However, it seems that the `BackupEntry` controller in the `gardenlet` reconciles the resource either after the `BackupEntry` has been removed from the __Source Seed__ but before the `Spec.SeedName` has been changed or reconciles it with outdated data. This basically redeploys the `BackupEntry` on the __Source Seed__

**Environment**:

- Gardener version: 1.20.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: all
- Others:

**Comment by plkokanov** [comment]
One option would be to add a `Status.SeedName` field to the `BackupEntry` in the garden cluster and it will do any steps to migrate the `BackupEntry` from the __Source Seed__ to the __Destination Seed__ if `Status.SeedName` != `Spec.SeedName` - similar to what happens with the `Shoot` resource. The `BackupEntry` in the Seed will not be directly annotated with `gardener.cloud/operation=migrate` as this will be taken care of by the `BackupEntry` controller in the gardenlet.

Another would be to annotate the `BackupEntry` with `gardener.cloud/operation=migrate` and once it is done with with migrating the `BackupEntry` in the seed cluster, it removes this annotation and sets its `Spec.SeedName` = nil. Then it waits for the shoot reconciliation in the `gardenlet` to set its new `Spec.SeedName`.

@amshuman-kr @rfranzke wdyt?

**Comment by rfranzke** [comment]
I like the first proposal for similarity reasons to the `Shoot` resource and to let the `BackupEntry` controller in gardenlet coordinate this/encapsulate the required knowledge, so that the `Shoot` controller in gardenlet doesn't need to know about these details and just change the `.spec.seedName`.

**Comment by timuthy** [comment]
One question: Will we have a similar handling for `spec.bucketName`? According to https://github.com/gardener/gardener/issues/3491#issuecomment-790656701, the bucket will also change after migration.

**Comment by plkokanov** [comment]
> One question: Will we have a similar handling for `spec.bucketName`? According to [#3491 (comment)](https://github.com/gardener/gardener/issues/3491#issuecomment-790656701), the bucket will also change after migration.

I guess we would have a better idea of how to handle this once we have agreed on how to migrate data between the buckets of the source and destination seeds. We could add the source bucket to the `BackupEntry.Status.BucketName` and have the destination bucket in the `BackupEntry.Spec.BucketName` - but we will have to keep those until the etcd data is migrated.
