### ISSUE TITLE
Regression: Seed creations fails if seed name contains a dot "." on 1.20.x

### ISSUE THREAD

**Issue by christianhuening** [gardener/gardener#3872]
**How to categorize this issue?**

/area robustness
/kind bug
/priority 2

**What happened**:
Garden Seed creation from acre.yaml fails if the garden base seed name contains a ".". Error in `sow` is:

```
jq: error (at <stdin>:147): Cannot iterate over null (null)
Error: seed 'garden.gcp' did not become ready within 300 seconds.
```

Error in Gardenlet shows as:

```
time="2021-04-13T08:23:53Z" level=info msg="Waiting until namespace \"seed-garden.gcp\" is created."
time="2021-04-13T08:23:56Z" level=error msg="failed to run gardenlet controllers: failed to register the seed: retry failed with context canceled, last error: namespace \"seed-garden.gcp\" still not created"
time="2021-04-13T08:23:56Z" level=info msg="Lost leadership, terminating."
```

The error in the gardenlet shows that it's attempted to create a namespace with a dot in its name, which is simply not supported.

**What you expected to happen**:

Either throw an error on acre.yaml validation OR rewrite dots to dashes etc.

**How to reproduce it (as minimally and precisely as possible)**:

try to run garden-setup with an acre.yaml where iaas[0].name = "garden.test" with garden

**Anything else we need to know?**:
This worked in Gardener 1.19.x

**Environment**:

- Version of garden-setup (release or commit): 3.8.0
- Versions of components (only needed if you overwrote the defaults): Gardener 1.20.2
- Where does the underlying base cluster come from and which operating system does it use?: GKE @ cos_containerd
- Which cloud provider is configured for the setup? GCP

**Comment by Diaphteiros** [comment]
For context: The reason this fails in garden-setup is the error in the gardenlet. @christianhuening said that everything worked fine with Gardener `v1.19` and it doesn't work anymore with Gardener `v1.20`, so this sounds like a regression in the Gardener. The problems seems to be the `.` in the seed name.
