### ISSUE TITLE
Use `ManagedResource` for Istio deployment and remove Istio on seed deletion

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/gardener#3881]
**How to categorize this issue?**

/area operations
/kind enhancement
/priority 3

**What would you like to be added**:
An option to remove istio and all resources belonging to it from the cluster when a seed with the `ManagedIstio` feature gate active is deleted.

**Why is this needed**:
If the gardenlet is deployed with the `ManagedIstio` feature gate (which is enabled by default in the current version), it will deploy istio into the seed cluster, consisting of two namespaces (`istio-ingress` and `istio-system` by default) and multiple cluster-scoped resources like CRDs (at least I assume that they came into my cluster this way). However, when the seed is deleted, there is no nice way to remove istio again - even if the two namespaces are deleted, a bunch of cluster-scoped resources (or resources in other namespaces) remains. A cleanup script is tedious to maintain, as it needs to be adapted whenever the istio components change.

It would therefore be nice if Gardener was not only able to deploy istio, but also to remove it again.

**Comment by rfranzke** [comment]
Can this be implemented by deleting the respective namespaces and CRDs? Would this be enough?

**Comment by Diaphteiros** [comment]
Would be fine for my purposes.
