### ISSUE TITLE
Aggregate failing health check reports

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#3897]
**How to categorize this issue?**

/area quality
/kind enhancement
/priority 3

**What would you like to be added**:

I would like to propose **aggregated** health check reports.

Gardener has the following health checks that contribute to the Readiness conditions in the `Status` of a Shoot cluster.
-  [Health checks executed by the Gardenlet ](https://github.com/gardener/gardener/blob/929c5f9174f60f6ddc4226d6c6eafc0afc5316db/pkg/operation/care/health.go#L231)
   - e.g, worker pool has enough nodes registered, kube apiserver has enough replicas,
  
- [Health check reports by Extensions](https://github.com/gardener/gardener/blob/929c5f9174f60f6ddc4226d6c6eafc0afc5316db/pkg/operation/care/health.go#L198) on Extension resources (ControlPlane, Worker, ...). 

**Problem**: [Health check reports from the Extensions are dropped ](https://github.com/gardener/gardener/blob/929c5f9174f60f6ddc4226d6c6eafc0afc5316db/pkg/operation/care/health.go#L348)as soon as there is also a failing health check executed by the Gardenlet care controller. I would expect an aggregated result over all errors. 

**Example**:

ControlPlane CRD in Seed reports multiple failing health checks:

```
1) deployment “cloud-controller-manager” in namespace “shoot--d060239--garden”
        is unhealthy: Deployment does not have minimum availability (MinimumReplicasUnavailable).
        2) deployment “csi-snapshot-controller” in namespace “shoot--d060239--garden”
        is unhealthy: Deployment does not have minimum availability (MinimumReplicasUnavailable).
```

However, the Shoot reports for the `ControlPlaneHealthy` condition type:

```
{
    “lastTransitionTime”: “2021-04-20T07:58:58Z”,
    “lastUpdateTime”: “2021-04-20T08:20:05Z”,
    “message”: “stateful set "prometheus" is unhealthy: not enough ready replicas (0/1).“,
    “reason”: “HealthCheckUnsuccessful”,
    “status”: “False”,
    “type”: “ControlPlaneHealthy”
  },
```

**Why is this needed**:

 - To deliver a complete overview of the health of the Cluster. 
 - Easier operations in case of problems with the cluster (complete overview of problems).

**Comment by rfranzke** [comment]
Hm, it was rather a conscious decision to exit early when the first check fails (instead of always checking everything), mainly to not pollute the shoot status/resource in general.

**Comment by danielfoehrKn** [comment]
> Hm, it was rather a conscious decision to exit early when the first check fails (instead of always checking everything), mainly to not pollute the shoot status/resource in general.

Yes, I would like to challenge the status quo due the reasons mentioned above. 
I think that gives an incomplete overview of the health of the status.

**Comment by rfranzke** [comment]
Do you have an idea how to overcome the reasons that led to the "status quo", or, alternatively, an argument why they do no longer apply?

**Comment by danielfoehrKn** [comment]
> an argument why they do no longer apply?

They still apply, though I do not think the right thing to do is just dropping valid health check reports and therefore hiding problems.

> Do you have an idea how to overcome the reasons that led to the "status quo"

First of all, I do not think that failing health checks are polluting the Shoot, but rather necessary information.
But what could be done is externalizing the aggregated health check reports into a dedicated resource.
The `Shoot` would still have a high level health check condition that is basically a condensed version of the aggregated report.

I think we first should agree that there is currently a problem and as the next step talk about concrete solutions.

**Comment by timebertt** [comment]
While I do kind of understand @danielfoehrKn's motivation, I don't think, this is the way to go.

I do understand, that often times shoot conditions are showing errors (e.g. "grafana unhealthy" or "kcm unhealthy") that are actually not the "root cause" (e.g. actually "prometheus" or "etcd/k-api" are the problematic components) and thus the health message might be misleading.

Though, I would argue that putting in every single failed check into the health message is not actually helping in figuring out the "root cause" of an issue or what to do as an operator. It might be even more confusing and will mainly pollute the shoot resource again.
If we want to improve the situation and help operators, we should rather think about how to "prioritize" health check failures via certain heuristics. However, this will not be "correct" every time and might still point to other problem than the "root cause".
So I don't know, if this approach would be worth the effort.

**Comment by danielfoehrKn** [comment]
> Though, I would argue that putting in every single failed check into the health message is not actually helping in figuring out the "root cause" of an issue or what to do as an operator. **It might be even more confusing** and will mainly pollute the shoot resource again.

I would argue it is more confusing to just arbitrarily drop health check reports from the Seed.

> If we want to improve the situation and help operators, we should rather think about how to "prioritize" health check failures via certain heuristics. However, this will not be "correct" every time and might still point to other problem than the "root cause".

I agree,  that it is hard to prioritize health check failures.
However, we already do that implicitly today. We always prioritize health check messages coming directly from the Gardenlet over aggregated reports from Extensions. 

>  It might be even more confusing and will mainly pollute the shoot resource again.

It seems to me that both @rfranzke  and @timebertt  are rightfully concerned about overloading / "polluting" the Shoot status.
This seems to be the main reason why aggregating health check reports is rejected.
I think this argument misses the point. 
**Why**: This issue does not say "put all health check messages into the Shoot status". While this would be a possible implementation to overcome the problems described above, it certainly is not the only one.
I think we should first talk about the actual problem and then only as a next step talk about a solution that does not "pollute" the Shoot status. Otherwise, the problem is dismissed because of a possible implementation (?).
To make it more clear what I meant with that:

**Current approach**: Drop health check reports from the Extensions as soon as there is a failing health check for the same category (e.g ControlPlaneHealthy) executed by the Gardenlet.

**Reason for current approach**
  - not overload the Shoot's Status

**Advantage of current approach**
 - less network traffic to the Gardener API server

**Disadvantage of current approach / Problem**
- Arbitrarily prioritize Gardenlet health check messages over aggregated health checks from Extensions, thus hiding reports from extensions. This leads to an incomplete overview / wrong impression of "what is wrong in the cluster".
- Dashboard cannot present an accurate and nicely presented overview of what's wrong with the cluster. I would argue this also confuses Shoot Owners (the dashboard is used not only by operators!).

**Possible solutions**
 - Do not do anything. Accept and document clearly e.g. [here](https://github.com/gardener/gardener/blob/5a69f918cc63bdd1a78c9eeac71222eec2e8ef04/docs/extensions/shoot-health-status-conditions.md).
 - Properly prioritize health check reports and only show the "root cause" -> hard to do according to @timebertt 
 - Put all health check reports into the Shoot Status -> will "overload" the Shoot
 - Create a resource for each namespace (similar to `ShootExtensionStatus`) that collects and categorizes ([with strong types](https://github.com/gardener/gardener/issues/3899))  failing health check reports e.g `ShootHealth`. An aggregated report stemming from this information is then put into the Shoot status.
   "Three failing health checks concerning the Shoot"s control plane. There are problems with the VPN connection, area2 from health check, area3 from health check." 
 The details can then be read by consumers (e.g operator, dashboard) from the `ShootHealth` resource.

**Steps**
 
1.  Do the advantages of the current approach outweigh the disadvantages? If yes -> leave it like it is.
2. No: come up with a solution.  Ideally even overcomes the reason for the current approach.

In any case, I think it is good that we talk about it here again.

**Comment by rfranzke** [comment]
At this point, personally, I feel that the proposed complexity (new API/resource -> more distribution of relevant information for users, new controller -> more code, one more resource per shoot -> increased etcd data volume, ...) might not be worth the benefits, at least at this time.
In my experience, it never was an issue that I didn't have a complete overview of all the many components of the shoot. If there was at least one problem and I needed to look into a cluster, then I was already getting the status/complete view. Do you maybe have an example for a problem or situation that would have improved your life when we would have had implemented what you propose?
Still, I'm open to discuss and dive into the details if more users are thinking that we should get active here. Let's collect some feedback/opinions. :)

**Comment by danielfoehrKn** [comment]
For me, the effect is that I do not look at the HealthCheck messages but rather directly check the ExtensionResources. So as an operator, the HealthCheck have only limited value to me.
For experienced operators that also know about the implementation details of the health checks, this might not be an issue - but I doubt the same holds true for other groups.

**Comment by rfranzke** [comment]
Given that there is no consensus and this activity is open since a long time without much activity, shall we close it for now? Or is this still relevant/important enough to follow-up?

**Comment by timebertt** [comment]
I don't see enough priority/urgency to work on this right now. However, I think we will definitely revisit the topic of improving the operator's view on landscape issues.
I would vote for closing the issue for now, as we will anyways have to start brainstorming again, when it becomes more relevant.

**Comment by rfranzke** [comment]
Sounds reasonable, thanks for a second opinion!
/close
