### ISSUE TITLE
Workflow Jobs Testing Capacity Shortage on Seed Clusters

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#39]
We had to terminate the cluster auto scaler on the seeds because:
* An older Calico version is deployed there and we know that it results in issues after lots of scale-up/down due to bugs that fail to cleanup IP ranges
* It still lacks (was said to be implemented for v1.8 but wasn't) the feature to reserve excess capacity and our seed clusters started breathing with the integration tests, which resulted in many issues as pods take minutes to be scheduled

However, now we have a fixed number of workers in the seeds. This means we have to scale manually, but lack indication thereof.

Therefore we need workflow jobs per seed that test for the used vs. the available capacity and warn the operator of a coming shortage.

**Comment by vlerenc** [comment]
With shoot'ed seed and the machine controller this won't be necessary anymore.
