### ISSUE TITLE
Relax client-side validation for templates in ManagedSeedSet

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#3909]
**How to categorize this issue?**

/area usability ops-productivity
/kind enhancement

**What would you like to be added**:

When creating a minimal `ManagedSeedSet`, e.g.
```yaml
apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: ManagedSeedSet
metadata:
  name: gcp-eu
  namespace: garden
  labels:
    provider: gcp
    region: europe-west1
spec:
  replicas: 3
  selector:
    matchLabels:
      provider: gcp
      region: europe-west1
  template:
    metadata:
      labels:
        provider: gcp
        region: europe-west1
    spec:
      seedTemplate:
        metadata:
          labels:
            provider: gcp
            region: europe-west1
        spec: {}
  shootTemplate:
    metadata:
      labels:
        provider: gcp
        region: europe-west1
    spec:
      secretBindingName: gcp-secret
      cloudProfileName: gcp
      region: europe-west1
      # ...
      networking:
        nodes: 11.240.0.0/16
        pods: 11.241.128.0/17
        services: 11.241.0.0/17
        type: calico
      provider:
        type: gcp
        # ...
```

via `kubectl`, the client-side validation (based on the OpenAPI spec) will fail because of some required fields, e.g.:

```
$ kaf local/managedseed/57-managedseedset-seedtemplate.yaml
error: error validating "local/managedseed/57-managedseedset-seedtemplate.yaml": error validating data: 
[ValidationError(ManagedSeedSet.spec.template.spec.seedTemplate.spec.networks): missing required field "pods" in com.github.gardener.gardener.pkg.apis.core.v1beta1.SeedNetworks,
ValidationError(ManagedSeedSet.spec.template.spec.seedTemplate.spec.networks): missing required field "services" in com.github.gardener.gardener.pkg.apis.core.v1beta1.SeedNetworks, 
ValidationError(ManagedSeedSet.spec.template.spec.seedTemplate.spec): missing required field "dns" in com.github.gardener.gardener.pkg.apis.core.v1beta1.SeedSpec, 
ValidationError(ManagedSeedSet.spec.template.spec.seedTemplate.spec): missing required field "provider" in com.github.gardener.gardener.pkg.apis.core.v1beta1.SeedSpec];
if you choose to ignore these errors, turn validation off with --validate=false
```

Though, these fields are actually optional in server-side validation and are defaulted from the shoot spec values (e.g. network cidrs will be taken from shoot spec, as they have to be the same).

To workaround this limitation, one can either
- specify the same values explicitly twice (in shoot and seed template)
- specify empty strings in the respective fields in the seed template
- pass `--validate=false` to disable `kubectl`'s client-side validation

I propose to relax the client-side validation for the templates used in the `ManagedSeedSet` resource (i.e. shoot and seed template) by marking the fields as `// +optional` in the API types. This will make the client-side validation for `ManagedSeedSet`s succeed, also if the mentioned fields are not given.

Though, this approach obviously has the drawback, that fields are marked as optional in the API types / docs, that are actually not optional when creating standalone `Shoot`s or `Seed`s.

Any opinions about the proposal?

/cc @stoyanr

**Comment by stoyanr** [comment]
> Though, this approach obviously has the drawback, that fields are marked as optional in the API types / docs, that are actually not optional when creating standalone Shoots or Seeds.

Because of the above, I tend slightly to prefer not to do as suggested, also since there are multiple workarounds. Having `+optional` fields that are in fact mandatory might be confusing for users and cause more damage than the convenience of e.g. not having to specify a few empty fields. I don't really have a strong opinion though.

Note that this behavior is only reproducible when `seedTemplate` is used (and not `gardenlet`). Note also that it's not limited to ManagedSeedSets, ManagedSeeds have the same issue.

/cc @rfranzke @danielfoehrKn What do you think?

**Comment by rfranzke** [comment]
I agree with @stoyanr, I think the drawbacks don't justify such change, especially because `ManagedSeedSet`s are (at least today) not the most frequently used resources in the Gardener API while `Seed`s/`Shoot`s are.

**Comment by timebertt** [comment]
Thanks for adding your opinions. As no one else supported my proposal, I think we can discard it and close the issue.
/close
