### ISSUE TITLE
Add minimumVolumeSize field to cloud profiles

### ISSUE THREAD

**Issue by petersutter** [gardener/gardener#396]
Currently the minimumVolumeSize of workers is hardcoded in the gardener. It would be nice if this information can be factored out to the cloud profiles so that also the gardener dashboard can provide a proper validation by just reading the respective value from the cloud profile

AWS minmumVolumeSize 20: https://github.com/gardener/gardener/blob/46e8736955e852daaeb396a01d67843269532c2b/pkg/apis/garden/validation/validation.go#L1101

Azure minmumVolumeSize 35: https://github.com/gardener/gardener/blob/46e8736955e852daaeb396a01d67843269532c2b/pkg/apis/garden/validation/validation.go#L1160

GCP minmumVolumeSize 20: https://github.com/gardener/gardener/blob/46e8736955e852daaeb396a01d67843269532c2b/pkg/apis/garden/validation/validation.go#L1204

Openstack: none?

AliCloud minmumVolumeSize 20:
https://github.com/gardener/gardener/blob/46e8736955e852daaeb396a01d67843269532c2b/pkg/apis/garden/validation/validation.go#L1297

https://github.com/gardener/dashboard/issues/118

**Comment by rfranzke** [comment]
Will be done as part of the extensibility epic. I have added a field to the example `CloudProfile` resource in the proposal document (https://github.com/gardener/gardener/commit/6e527ba2e19caf4262dea6e75aa8b1105b78913d#diff-211ac3b72ed2dbadb74b3e8304eb4c71R120).
