### ISSUE TITLE
Adapt to helm v3

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#3961]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement

**What would you like to be added**:

We should finally adapt all our hack scripts and so on to helm v3 and install v3 in `install-requirements.sh`.

**Why is this needed**:

Most developers will have migrated to helm v3 by now. When doing some development for gardener that uses helm for templating stuff (e.g. `hack/local-development/local-garden/configure-rbac` or `hack/generate-controller-registration.sh`), they will have to switch back to helm v2 again, as scripts break with v3 or result in other generation results.
This is quite annoying and I've been bitten by this quite often now.

**Comment by rfranzke** [comment]
@timebertt can this be closed?

**Comment by timebertt** [comment]
Yep 👍 
/close
