### ISSUE TITLE
Shoot cannot be created due to a a race condition with the shoot state

### ISSUE THREAD

**Issue by schrodit** [gardener/gardener#3962]
**How to categorize this issue?**

/kind bug
/priority 3

**What happened**:

A cluster that was running several days was deleted.
**Directly** after the cluster was deleted a new cluster with the same name has been created. 

Gardener was unable to create the new shoot due to a already existing shoot state resource with a different owner. (see below for a concrete error message).

_my assumption_:
I suspect that gardener relies on the k8s garbage collection for the shoot state deletion after the owning shoot is deleted.
But if the garbage collection does not happen before a shoot with the same name is created, the old state conflicts with the new shoot.

Detailed err message:
```
Flow "Shoot cluster deletion" encountered task errors: [task "Ensuring that ShootState exists" failed: retry failed with context deadline exceeded, last error: ShootState.core.gardener.cloud "myshoot" is invalid: metadata.ownerReferences: Invalid value: []v1.OwnerReference{v1.OwnerReference{APIVersion:"core.gardener.cloud/v1beta1", Kind:"Shoot", Name:"myshoot", UID:"7ca9d19a-4d5c-43ef-8b9e-fa80dafc179a", Controller:(*bool)(0xc0a3bc3a80), BlockOwnerDeletion:(*bool)(0xc0a3bc3a81)}, v1.OwnerReference{APIVersion:"core.gardener.cloud/v1beta1", Kind:"Shoot", Name:"myshoot", UID:"b75f622a-469c-4a23-9747-d054d3715a11", Controller:(*bool)(0xc0a3bc3a82), BlockOwnerDeletion:(*bool)(0xc0a3bc3a83)}}: Only one reference can have Controller set to true. Found "true" in references for myshoot and myshoot] Operation will be retried.
```

**What you expected to happen**:

The shoot state should get cleaned up before the shoot resource is deleted.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a shoot named `shoot-abc`
2. Delete that shoot and directly afterwards create a new shoot with the same name.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.21.0
- Kubernetes version (use `kubectl version`): 1.20.5
- Cloud provider or hardware configuration: GCP

**Comment by rfranzke** [comment]
Can you please share some relevant logs of the GC controller in KCM?

**Comment by schrodit** [comment]
[kcm-shootstate-gc.log](https://github.com/gardener/gardener/files/6391864/kcm-shootstate-gc.log)
Do you also need the kcm logs of a successfull run when the kcm was able to delete the shootstate?

Sidenote: I needed approx. 5 retries until I could reproduce the issue with increased verbosity.
Used Script:
```
#! /bin/bash

function provisionCluster() {
    export GARDENER_CLUSTER_NAME=$1
    export DEFINITION_PATH=$2
    echo "Creating cluster: ${GARDENER_CLUSTER_NAME}"
    # create the cluster
    cat "${DEFINITION_PATH}" | kubectl create -f -
    # wait for the cluster to be ready
    kubectl wait --for condition="ControlPlaneHealthy" --timeout=10m shoot "${GARDENER_CLUSTER_NAME}"
    echo "Cluster ${GARDENER_CLUSTER_NAME} was created succesfully"
}

function delete_cluster(){
    local name="$1"
    set +e
    echo "Deleting cluster '${name}'"
    kubectl annotate shoot "${name}" confirmation.gardener.cloud/deletion=true --overwrite
    kubectl delete shoot "${name}" --wait=true
    set -e
}

GARDENER_CLUSTER_NAME="ts-test"
DEFINITION_PATH=$1

delete_cluster ${GARDENER_CLUSTER_NAME}
provisionCluster ${GARDENER_CLUSTER_NAME} ${DEFINITION_PATH}
```

**Comment by BeckerMax** [comment]
We discussed this issue in the core quality round. Results:
- In the above log we see `"ts-test" is forbidden: shoot ts-test in namespace garden-core still exists` which shows that the garbage collector tries to delete the shootstate but an admission [plugin](https://github.com/gardener/gardener/blob/a4005e7fd4001e224e4c494d14a7d04c1af81c36/plugin/pkg/shootstate/validator/admission.go#L164) prevents that

Way forward:
- No longer rely on the garbage collector but delete shoot state explicitly as part of the shoot deletion flow.
- Delete `validateShootStateDeletion` admission plugin - as it would no longer work (shoot resource will still exist when shoot state is deleted).
- Use deletion confirmation plugin if we want to make sure that the state is deleted.

**Comment by BeckerMax** [comment]
Thanks @schrodit for the detailed issue including logs and a script to reproduce it 👍🏼

**Comment by timebertt** [comment]
@BeckerMax are you working on this?

**Comment by BeckerMax** [comment]
Yes, I would like to finish it. Hopefully today.

**Comment by timebertt** [comment]
Ok, great 👍 
/assign @BeckerMax

**Comment by valentinvieriu** [comment]
This situation still occurs.

**Comment by timebertt** [comment]
@valentinvieriu yes, and as you can see from the linked PR, we are currently working on a fix :)
