### ISSUE TITLE
Gardener UI throwing an error when kubeconfig file is valid

### ISSUE THREAD

**Issue by vrock28** [gardener/gardener#398]
Hi,

I am attaching the screen shot from the UI error i hit while trying to upload a valid Kubeconfig YAML file.

<img width="894" alt="screen shot 2018-09-28 at 2 01 39 pm" src="https://user-images.githubusercontent.com/30268685/46197405-632f8680-c327-11e8-8ec5-0243d4f7a5a2.png">
<img width="908" alt="screen shot 2018-09-28 at 2 02 03 pm" src="https://user-images.githubusercontent.com/30268685/46197406-632f8680-c327-11e8-8945-0e842e0d7b84.png">

**Comment by rfranzke** [comment]
We hvae disabled the login in the kubernetes dashboard as it does not work properly for kubeconfigs with client certificates which we generate. You don't have to login, please just use "Skip".
