### ISSUE TITLE
Validate feature flags upon Shoot K8s version update

### ISSUE THREAD

**Issue by BeckerMax** [gardener/gardener#3987]
**How to categorize this issue?**
Certain configuration of the shoot resource is only compatible with certain Kubernetes versions. If a Shoot owner updates the Kubernetes version she might miss that therefore certain configuration can become invalid, for example runtimeConfig or feature flags,...
This can lead to an unavailable Shoot cluster after a K8s update.

/area usability
/area ops-productivity

/kind enhancement
/priority 4

**What would you like to be added**:
Upon a K8s major update in the Shoot resource validate feature flags (i.e. for the apiserver). Deny the update if the feature flags are no longer valid with the new version.

**Why is this needed**:
Improved user experience. Less ops effort to fix broken clusters.

cc @schrodit

**Comment by danielfoehrKn** [comment]
I remember discussions about this in the past.
I believe we purposefully left that to the user because it would require Gardener to maintain a complete list of feature flags per Kubernetes version.
Not sure if the effort is worth it.

**Comment by rfranzke** [comment]
The maintenance effort is negligible - a new Kubernetes version is released every 4 months, and when we add support for it to Gardener we might have to update the feature gate list for it - that's it.
The main argument for not doing it so far was that we also have other configurations (e.g., runtime config) which is way harder to validate. We always argued that using such "alpha" features is on the own risk of the end-user. However, in practice it seems that validating the feature gates relieves the SREs/operators from some tedious tasks.
