### ISSUE TITLE
[ci-pipeline ] - early-exit for broken garden-operators

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#40]
**Issue by [ccwienk](https://github.com/ccwienk)**
_Thursday Oct 19, 2017 at 13:39 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/150_

----

if garden-operator binary is obviously broken (as in: panics upon simple ./garden-operator --help or similar smoke-test), do not bother to run ci-pipeline
maybe this is already handled by existing unit tests?

**Comment by vlerenc** [comment]
Wrong component.
