### ISSUE TITLE
Shooted seed is not getting updated when updating soil seed (1.15.5 -> 1.18.1)

### ISSUE THREAD

**Issue by hassbert** [gardener/gardener#4002]
**How to categorize this issue?**
/area operations
/kind bug
/priority 3

**What happened**:
I updated my gardener landscape from 1.15.5 to 1.18.1 via [garden-setup](https://github.com/gardener/garden-setup).
I have a shooted seed `eval-euc-1` created via the [`use-as-seed` annotation](https://github.com/gardener/gardener/blob/77e09dd522d7bfb682cc35d0be437201b606061b/docs/usage/shooted_seed.md)

```
    shoot.gardener.cloud/use-as-seed: >-
      true,shootDefaults.pods=100.96.0.0/11,shootDefaults.services=100.64.0.0/13,disable-capacity-reservation,loadBalancerServices.annotations.service.beta.kubernetes.io/aws-load-balancer-internal="true",with-secret-ref,backup.provider=aws,backup.region=eu-central-1,backup.secretRef.name=aws-seed-evaluation,backup.secretRef.namespace=garden,featureGates.APIServerSNI=false,featureGates.ManagedIstio=false

```

The update of all the gardener components including the soil seed was properly performed but the shooted seed was not updated.

```
➜  workspace gardenctl kubectl get seeds
NAME         STATUS   PROVIDER   REGION         AGE     VERSION   K8S VERSION
eval-euc-1   Ready    aws        eu-central-1   13d     v1.15.5   v1.19.7
soil         Ready    aws        eu-central-1   13d     v1.18.1   v1.19.10
```

Furtermore the newly introduced managedseed object is also not getting registered properly:

```
➜  workspace gardenctl kubectl get managedseeds --all-namespaces
NAMESPACE   NAME         STATUS          SHOOT        GARDENLET   AGE
garden      eval-euc-1   NotRegistered   eval-euc-1   True        13d
```

Error message of the managedseed object:
```
Events:
  Type     Reason          Age                 From       Message
  ----     ------          ----                ----       -------
  Normal   Reconciling     11m (x861 over 9d)  gardenlet  Shoot garden/eval-euc-1 is reconciled
  Warning  ReconcileError  11m (x861 over 9d)  gardenlet  Could not register shoot garden/eval-euc-1 as seed: could not deploy gardenlet into shoot garden/eval-euc-1: render error in "gardenlet/charts/runtime/templates/secret-kubeconfig-garden-bootstrap.yaml": template: gardenlet/charts/runtime/templates/secret-kubeconfig-garden-bootstrap.yaml:15:17: executing "gardenlet/charts/runtime/templates/secret-kubeconfig-garden-bootstrap.yaml" at <required ".Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.kubeconfig is required" .Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.kubeconfig>: error calling required: .Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.kubeconfig is required
```

**What you expected to happen**:
Once I update the soil seed the shooted seed is getting updated properly.
Furthermore I would expected that the newly introduced managed seed is getting registered properly.

**How to reproduce it (as minimally and precisely as possible)**:
- create a gardener landscape with gardener version 1.15.5 using garden-setup (version [3.4.0](https://github.com/gardener/garden-setup/releases/tag/3.4.0)
- create a shooted seed with the annotation posted above
- update gardener landscape with gardender version 1.18.1 using garden-setup (version [3.7.0](https://github.com/gardener/garden-setup/releases/tag/3.7.0)

**Anything else we need to know?**:
Slack conversation: https://kubernetes.slack.com/archives/CB57N0BFG/p1619125155320100?thread_ts=1619006099.311900&cid=CB57N0BFG
Just as a remark: I am aware that the garden-setup project is not intended to use for updates but this issue should not be caused by using garden-setup as the update is getting performed properly and the shooted seed is created separately from the infrastructure garden-setup is creating.

Furthermore: new shooted seeds are getting rolled out properly with version 1.18.1 but the managedseed object is not getting registered as well with the same error as shown above:

```
➜  workspace gardenctl kubectl get seeds
NAME         STATUS   PROVIDER   REGION         AGE     VERSION   K8S VERSION
eval-euc-1   Ready    aws        eu-central-1   13d     v1.15.5   v1.19.7
eval-usw-2   Ready    aws        us-west-2      2d10h   v1.18.1   v1.19.7
soil         Ready    aws        eu-central-1   13d     v1.18.1   v1.19.10
```

**Environment**:

- Gardener version: 1.15.5 -> 1.18.1
- Kubernetes version (use `kubectl version`): 1.19.7 and 1.19.10
- Cloud provider or hardware configuration: aws
- Others: let me know if you need some more context :)

**Comment by timebertt** [comment]
/cc @stoyanr @danielfoehrKn 
Can you check this issue, as you have recently touched the corresponding helm charts?
