### ISSUE TITLE
Transient machine creation errors on Azure incorrectly categorized as ERR_INFRA_DEPENDENCIES

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener#4019]
**How to categorize this issue?**

/area ops-productivity
/kind bug
/priority 3

**What happened**:

Gardener stopped reconciling a cluster after encountering the following error, which was labeled as `ERR_INFRA_DEPENDENCIES`: `machine(s) failed: 1 error occurred: "shoot--hc-dev--ere39-az-haas-default-z2-69ff5-9fslk": Cloud provider message - Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded']`. Consequently, the dashboard was showing the following message: `Infrastructure operation failed as unmanaged resources exist in your cloud provider account. Please delete all manually created resources related to this Shoot.`

However, the machine creation was retried by MCM and the second time (2 minutes later) it was successful:
```
$ k logs machine-controller-manager-78c7d899b7-fb66l | grep shoot--hc-dev--ere39-az-haas-default-z2-69ff5-9fslk
E0510 08:19:29.585379       1 machine.go:478] Error while creating machine shoot--hc-dev--ere39-az-haas-default-z2-69ff5-9fslk: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
I0510 08:19:29.786348       1 machine.go:421] Creating machine "shoot--hc-dev--ere39-az-haas-default-z2-69ff5-9fslk", please wait!
...
I0510 08:21:07.082209       1 machine.go:499] Created/Adopted machine: "shoot--hc-dev--ere39-az-haas-default-z2-69ff5-9fslk", MachineID: azure:///eastus/shoot--hc-dev--ere39-az-haas-default-z2-69ff5-9fslk
...
I0510 08:21:23.450330       1 machine.go:938] Machine shoot--hc-dev--ere39-az-haas-default-z2-69ff5-9fslk successfully joined the cluster
```

The error was labeled as `ERR_INFRA_DEPENDENCIES` due to the following string: `Future#WaitForCompletion: context has been cancelled`. This string is intended to match user errors caused by unmanaged resources, but is perhaps too general. I don't think there were any unmanaged resources involved, it was rather a transient error in Azure.

**What you expected to happen**:
The error should not have been labeled `ERR_INFRA_DEPENDENCIES`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.21.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: Azure
- Others:

**Comment by stoyanr** [comment]
@rfranzke, the string that was matched was introduced by you with 36d6681aa3cfa8b60042ed33cde920fcddbf3b42, do you remember why it was introduced this way?

**Comment by vlerenc** [comment]
This comment might not be of much help, but in general, the infrastructure extensions should be better suited to guess certain classes of issues, namely all that are rooted in the infrastructure or interacting/communicating with it. In this case though, things get messier as we have specific parts of the infrastructure outsourced elsewhere, here into the MCM drivers.

The whole topic of error codes was often contemplated, but nobody was ever happy with the outcome. Improvements, yes, but it remains a "difficult" subject matter.

Would we have time/the wish to pick it up/re-discuss our options? We in development, operators, and end users would all benefit from a better contract between our components and better (=correct and concise) error codes in the shoot status/Dashboard.

**Comment by rfranzke** [comment]
@stoyanr To me it seemed that this error is clearly an infrastructure problem and the Gardener operators cannot help fixing it. Hence, I was looking for a way to hide it from them so that they are not bothered with it. `ERR_INFRA_DEPENDENCIES` seemed to be the closest choice looking at the available options.

>  This string is intended to match user errors caused by unmanaged resources

Hm, not only. For me, "INFRA DEPENDENCIES" can also mean that the error is caused by/dependent on the IaaS provider. Again, maybe all of this can be done way better, but looking at the current state and the available options, it seemed the best fit.

> but is perhaps too general.

Why do you think so?

> Consequently, the dashboard was showing the following message: Infrastructure operation failed as unmanaged resources exist in your cloud provider account. Please delete all manually created resources related to this Shoot.

Probably the text in the dashboard can be improved to reduce confusion.

**Comment by stoyanr** [comment]
> Why do you think so?

I meant that it's certainly not unique to "unmanaged resources", and this is exactly what the error message claimed the root cause to be.

> Probably the text in the dashboard can be improved to reduce confusion.

Yes, but this won't solve the overall issue: instead of retrying on what was likely an infrastructure-related transient error, Gardener stops reconciling and miscategorizes the issue as "user error", leaving the user wondering what could be done, while a simple retry would solve the issue.

How about simply removing `Future#WaitForCompletion: context has been cancelled` from the list? Perhaps we would then miss issues that are not transient and are indeed "user errors", but then we could look for better strings to identify them?

**Comment by rfranzke** [comment]
Sure, no objections.
