### ISSUE TITLE
Increase character limit from 12 to 32 (or higher) for the name of a cluster (Display Name?)

### ISSUE THREAD

**Issue by rufreakde** [gardener/gardener#4025]
/area control-plane
/area ops-productivity
/kind enhancement
/priority 3

**What would you like to be added**:
Having the name of a cluster with more signs. And allow it to be edited after cluster creation (Maybe a displayname)

**Why is this needed**:
This allows us to make the matching of clusters to landscapes we have much simpler as we can make it more descriptive for devs and ops and do not have to have some excel or wiki to maintain.

Much simpler to order use and maintain without documentation overhead. Example:
```
metadata:
  name: <Azure>-<IntegrationSpace>-<EdgeDevice>
```
Azure could be AWS or another IntegrationSpace could be Dev or Prod, and Edge Device if available also could be in the name. 

If it is not possible to change the name length is it is reused. Maybe a displayname with more signs would be a quick and really helpful change.

**Comment by rfranzke** [comment]
I doubt that we can generally increase the name length limits due to limitations of the cloud providers. 
Resource names are immutable and cannot be changed after creation.
Though, you can use `.metadata.labels` in order to set arbitrary display names.
Would this work for you?

**Comment by rufreakde** [comment]
Usually the cloudproviders do accept a min of 50 signs right? In some cases 63 no?
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules
https://aws.amazon.com/about-aws/whats-new/2019/08/elasticache_supports_50_chars_cluster_name/
https://cloud.google.com/compute/docs/naming-resources

Are you sure this is an issue? maybe it was before but is not anymore?

Is the `metadata.labels` displayed in the UI so we can use the Gardener UI Overview to have specific display names?

It is not like we want to implement a new feature just to have a different dashboard again to maintain to display the names we would just want to reuse the Gardener UI. And there the "name" is just to short to be "usable" in productive systems. The Gardener UI overview is nice but the name limitation is to harsh. I Understand that it is used for the cloud providers but gardener could maintain a displayname additionally and display that on in the UI if the cloudproviders limitations really are a limiting factor here.

**Comment by rfranzke** [comment]
> Are you sure this is an issue? maybe it was before but is not anymore?

Maybe, needs to be checked for all providers and resources in detail. Generally, it's not only the project name/cluster name who is concatenated when a resource in a cloud provider is created, see e.g. https://github.com/gardener/gardener-extension-provider-aws/blob/f4e3ca6b8b87664c5dbc4e39f5e7fb87360ee3f7/pkg/controller/infrastructure/templates/main.tpl.tf#L191.
I'm open to lift/relax the length restrictions if we are sure that we won't run into issues with it.

> Is the metadata.labels displayed in the UI so we can use the Gardener UI Overview to have specific display names?

I don't know, probably you can reach out to @grolu @petersutter or open an issue in the gardener/dashboard repository. IIRC, there is some support for displaying custom labels, but the colleagues can explain better.

**Comment by rufreakde** [comment]
@rfranzke would be nice to follow up the limitations if it really is not possible to squeeze out some signs this would be beneficial for all users. 

And as for the custom label support I will create a followup issue on:
https://github.com/gardener/dashboard

**Comment by petersutter** [comment]
> And as for the custom label support I will create a followup issue on:
> https://github.com/gardener/dashboard

@rufreakde please see https://github.com/gardener/dashboard/blob/master/docs/usage/custom-fields.md as this could be what you are looking for

**Comment by krasimirdermendzhiev** [comment]
I will write here, but if would like you can change it.

When I use for my cluster name example: kyma-cluster. I have issue with deploy Kyma from Service Hub with message:

"Unable to create the release: template: kyma/templates/_helpers.tpl:57:4: executing "kyma.checkRequirements" at <fail (printf "Resulting cluster domain '%s' has length '%d' and exceeds maximum length of '64' for certificate generation. Please create a cluster with a shorter name." $shootInfo.data.domain $domainLen)>: error calling fail: Resulting cluster domain 'kyma-cluster.promart.shoot.canary.k8s-hana.ondemand.com' has length '65' and exceeds maximum length of '64' for certificate generation. Please create a cluster with a shorter name." 

There is no option to change the name for my cluster and I need to delete and then create again. I think is good to have note, verification or exception for cluster name when I will create cluster with Kyma, but I think this problem can occur with another Service Hub deploy.

**Comment by rfranzke** [comment]
I'm unsure how to proceed with this issue. I tend to closing it since my last information was that cloud provider resources have a certain length limit (as explained in https://github.com/gardener/gardener/issues/4025#issuecomment-844870240). I doubt whether someone will find capacity/time soon to double-check this for each and every cloud provider and resource we create. Generally, shortening the project name helps to be able to use longer shoot cluster names (or vice versa).
Other opinions?

@krasimirdermendzhiev This issue is with Let's Encrypt and the default domain used in your environment which already is long by itself. Given that the https://github.com/gardener/gardener-extension-shoot-cert-service is an extension gardener/gardener is not aware of, adding validation to gardener/gardener for such things doesn't make much sense. I suggest to open an issue there (at this place such validation code seems to be reasonable given the limitation of 64 chars from Let's Encrypt).

**Comment by rufreakde** [comment]
I encountered this kyma helm install issue as well. IMHO it would be fine for me to shorten this general name even more but add a display name for all clusters as default. @petersutter suggested to enable the name ourselves and this might solve the issue. But is this not a use case that should be default?

Having an ID with very strict naming length as discussed above. But also have a descriptive naming field as display-name I mean it is technically possible to achieve this.

I could even name my clusters with abbreviations on the name (id) level and add descriptive full names that way.
If I ever have some time to extend our UI with this field would it also be possible to create some kind of PR to enable this extra field as default to help extend this limitation?

**Comment by rfranzke** [comment]
> But is this not a use case that should be default?

Apparently not, at least I haven't seen much pull on this topic. You are free to define labels and annotations on `Shoot` resources to provide any additional information you want, and as @petersutter explained the Dashboard can even display them in case they follow a certain convention. It seems this is good enough for now (given the capacity circumstances explained above).

> If I ever have some time to extend our UI with this field would it also be possible to create some kind of PR to enable this extra field as default to help extend this limitation?

I'm not sure whether I fully got it, but in case this question is about the Gardener Dashboard then I recommend to open a separate issue at https://github.com/gardener/dashboard/issues or talk to @gardener/dashboard-maintainers to get their feedback upfront.

**Comment by grolu** [comment]
We already have an open issue regarding exposing the custom fields feature, to make it easier to use.
https://github.com/gardener/dashboard/issues/1071

**Comment by rufreakde** [comment]
> We already have an open issue regarding exposing the custom fields feature, to make it easier to use. [gardener/dashboard#1071](https://github.com/gardener/dashboard/issues/1071)

very nice cross reference already thumbed up the other thread
