### ISSUE TITLE
Helm integration

### ISSUE THREAD

**Issue by Demonsthere** [gardener/gardener#403]
Hello,
In the current setup of Gardener, it is not possible to upgrade tiller using the `helm upgrade` method:

```bash
helm list
Error: incompatible versions client[v2.10.0] server[v2.9.1]
helm init --upgrade
$HELM_HOME has been configured at /Users/foo/.helm.

Tiller (the Helm server-side component) has been upgraded to the current version.
Happy Helming!
helm ls
Error: incompatible versions client[v2.10.0] server[v2.9.1]
```

And the only method of upgrading helm is to modify the image in the `tiller-deploy` deployment in `kube-system` namespace. 

However, such a change is then overwritten by the Reconcile mechanism, and helm is again downgraded.

I assume, the default cli method should work, or is this a design decision? 
Best regards

**Comment by rfranzke** [comment]
It is intended that the addons managed/deployed by Gardener are reconciled at any time to the state Gardener desires. Please install tiller on your own if you want to control its lifecycle on your own.
BTW: We are going to remove the in-tree addon management and will replace it by a more pluggable solution in the future: #246.
