### ISSUE TITLE
Shoots hibernation falied due to PDB violation of coredns deployment

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener#4038]
**How to categorize this issue?**

/area control-plane
/kind bug
/priority 3

**What happened**:

Hibernation of an alicloud shoot failed with:
```
task "Waiting until shoot worker nodes have been reconciled" failed: Error while waiting for Worker shoot--it--tmp6x-qtf/tmp6x-qtf to become ready: extension encountered error during reconciliation: Error reconciling worker: Failed while waiting for all machine deployments to be ready: 'retry failed with context deadline exceeded, last error: Waiting until all machines have been hibernated (1 still awake)...'
```

In the MCM logs, one can see that the machine could not be drained because of a PDB violation:
```
I0511 11:21:31.682342       1 drain.go:858] Pod kube-system/coredns-66d5b48-tw4cz couldn't be evicted from node izgw8e6lx4eklozw4vauwzz. This may also occur due to PDB violation. Will be retried. Error: Cannot evict pod as it would violate the pod's disruption budget.
```

The PodDisruptionBudget `coredns` specifies max unavailable of 1. 
```
spec:
  maxUnavailable: 1
```

The `coredns` deployment has 2 replicas, but since all other nodes are already gone, there is no way to drain the last remaining replica from the last remaining node.

**What you expected to happen**:
Hibernation to succeed.

**How to reproduce it (as minimally and precisely as possible)**:
Not really sure, I only saw this once during my today's DoD shift. However, I wonder what measures do we take to prevent this from happening, so that it doesn't fail on each (or most) hibernations?

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.21.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: Alicloud
- Others:

**Comment by vpnachev** [comment]
This should not be a Gardener/Gardener-extension issue - see https://github.com/gardener/gardener/blob/86c5e87142bb45bcb58965c9e6ec891d2c910596/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go#L243-L249.

@gardener/mcm-maintainers please check too.

**Comment by prashanth26** [comment]
Yes, in a hibernation case all the machines should be force deleted. We do perform a drain, however, we keep the timeout to just a minute as seen [here](https://github.com/gardener/machine-controller-manager/blob/master/pkg/util/provider/machinecontroller/machine_util.go#L951-L966). So it could be the case that you see the error for a short period until the machine deletion goes through as one of the drains could've retried. However, I expect the shoot hibernation to happen in the next few minutes (time taken for VM to delete).   

How often did you see it?

**Comment by stoyanr** [comment]
I think it took longer than a minute, the cluster was in this state for at least 20 min. I manually adapted the PDB to let it go through. I only observed it once. Let's keep it open for a couple of more days, if I don't observe it for a second time I will close the ticket.

**Comment by stoyanr** [comment]
Closing as promised.
