### ISSUE TITLE
Only allow using Shoot addons for evaluation clusters beginning with v1.22

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#4079]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 3

**What would you like to be added**:
Only allow to enable addons in `.spec.addons` in `Shoot` resources if 
- `.spec.kubernetes.version` is lower than `v1.22.0`.
- `.spec.purpose=evaluation` and the `.spec.kubernetes.version` is greater or equal `v1.22.0`.

**Why is this needed**:
The addons are just provided by Gardener to enable "hello-world" use-cases and are not recommended for production usage.  They are not regularly maintained, updated without end-users' control, and don't allow for a lot of customization/configuration.
Hence, let's prohibit using them if the shoot purpose is not `evaluation` to make clear that end-users who want to use their clusters for production need to deploy their own addons.

**Comment by vpnachev** [comment]
> if the .spec.kubernetes.version is greater than v1.22.0.

Why with this limitation?

**Comment by rfranzke** [comment]
For backwards-compatibility

**Comment by vpnachev** [comment]
What about if a 1.21 cluster with purpose `production` is upgraded to 1.22 and the addons are enabled?
If it is initiated by the shoot owner, ok - he will see the error and find out that cannot upgrade.
But such validation will brake the forceful minor version [upgrade](https://github.com/gardener/gardener/blob/7c4388ee8bb0eaecfbae451772dc2577df45cc3f/pkg/controllermanager/controller/shoot/shoot_maintenance_control.go#L237-L252) in GCM.

**Comment by rfranzke** [comment]
Yes, it will be denied by the API and it won't be possible to upgrade.

**Comment by vpnachev** [comment]
What do you think to extend the maintenance controller to also disable the addons when it is upgrading non evaluation shoot to k8s version >=1.21? Or to change its purpose to `evaluation` when at least one addon is still enabled?
The fact that forceful minor upgrade is happening makes me think that the shoot owner does not care much about the cluster and the GCM is allowed to apply such changes.

**Comment by rfranzke** [comment]
I would like to avoid any additional complexity. We haven't done such things in the past either (e.g., when we disallowed basic auth for newer Kubernetes versions). I would rather want to let the upgrade fail explicitly instead of silently removing some addons (which potentially break the end-users' workload).

**Comment by vpnachev** [comment]
> I would rather want to let the upgrade fail explicitly 

Agree, but what does this mean for GCM? Will it set the shoot to failed state? If not, then it will be silently failing.

**Comment by rfranzke** [comment]
Probably, but this is another problem out of scope of this issue. You might want to open a separate issue to track this.

**Comment by dguendisch** [comment]
In this case probably the guestbook tests (and others?) need to be amended by deploying their own ingress controller.
Today they rely on one being present and only create `ingress` resources.

**Comment by rfranzke** [comment]
@dguendisch In which case? We could also allow to enable the addon for both `evaluation` and `testing` purposes, would this be good enough for the integration tests?

**Comment by dguendisch** [comment]
We intentionally don't set the `testing` purpose (so that we do have logging&monitoring to test it :) ).
I rechecked, our shoots do have the `evaluation` purpose, I couldn't find where we set it and @schrodit suggested that it's the default. If this is true, we are good to go and the tests will still find nginx ingress.
