### ISSUE TITLE
Drop support for seeds running K8s <= 1.17

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#4083]
**How to categorize this issue?**

/area security
/area performance
/area scalability
/kind enhancement
/priority 3

**What would you like to be added**:
Gardener should only support seed clusters running K8s 1.18.x and later.

**Why is this needed**:
At the moment the minimum supported version of a seed cluster is K8s `1.15` or `1.16` if `ManagedIstio` is enabled ([ref](https://github.com/gardener/gardener/blob/master/docs/usage/supported_k8s_versions.md#seed-cluster-versions)). However, these versions aren't officially supported any more ([ref](https://kubernetes.io/releases/version-skew-policy/)) and thus often don't contain important security or bug fixes. There might be exceptions when cloud providers maintain their own fork (e.g. GKE) but we don't want to rely on these exception and neither do we want to motivate using a non-maintained K8s version in any Gardener landscape.
After discussing with @timebertt and @rfranzke, we decided to go for a minimum version of `1.18` (one version below official version skew) as [support for this version was added to Gardener over a year ago](https://github.com/gardener/gardener/pull/2111) and most cloud providers offer this version as well. This should give us enough confidence that the community already run their seeds with `>= 1.18` or can update them accordingly.

But there is another reason to go for at least `1.18`: [Server-Side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/). We identified many places, especially in the Gardenlet code, that will benefit from SSA compared to Json-Merge/Strategic-Merge patches that are used today. Less conflicts, less network transfers, less API calls, lower code complexity, etc.. Other components in the Gardener landscape, e.g. Etcd-Druid or provider extensions, will benefit from SSA to at least the same extent.

**Comment by timebertt** [comment]
Thanks for the excellent summary!
One addition: If the `SeedKubeScheduler` feature gate is enabled, we also require `>=1.18` as a seed cluster kubernetes version already ([ref](https://github.com/gardener/gardener/blob/master/docs/deployment/feature_gates.md#list-of-feature-gates))

**Comment by timebertt** [comment]
With this, we will also be able to finally get rid of the infrastructure cleanup wait, which will make shoot deletion faster by ~5m 🎉 
https://github.com/gardener/gardener/blob/e3e68ccb2a198c27e2943d07b79d4e342ad14741/pkg/gardenlet/controller/shoot/shoot_control_delete.go#L432-L448

**Comment by rfranzke** [comment]
I don't know, we have to test that thoroughly. We have seen issues with AWS when we deactivated the explicit LB deletion with https://github.com/gardener/gardener-extension-provider-aws/pull/290 and had to reactive it with https://github.com/gardener/gardener-extension-provider-aws/pull/295 because it didn't work as expected.

**Comment by ialidzhikov** [comment]
https://github.com/gardener/gardener/pull/4426 was only a doc change that raises the requirement for the Seed Kubernetes version. I guess we can also clean up the handling for Kubernetes < 1.18 in few releases (I assume we have handling in the seed-bootstrap chart, there is also https://github.com/gardener/gardener/issues/4083#issuecomment-851287062 that needs further investigations, etc).

**Comment by rfranzke** [comment]
FYI: With #5272 we have dropped support for clusters < 1.17.

**Comment by timebertt** [comment]
> I guess we can also clean up the handling for Kubernetes < 1.18 in few releases (I assume we have handling in the seed-bootstrap chart, there is also [#4083 (comment)](https://github.com/gardener/gardener/issues/4083#issuecomment-851287062) that needs further investigations, etc).

@rfranzke @ialidzhikov does it make sense to perform this cleanup now/soon?
If so, maybe one of @acumino @shafeeqes @ary1992 can take this over.

**Comment by rfranzke** [comment]
I checked the code and there doesn't seem to be more things to cleanup, so
/close

We decided to tackle https://github.com/gardener/gardener/issues/4083#issuecomment-851287062 separate once we raise the minimum Kubernetes version for shoots (to 1.18 or higher).
