### ISSUE TITLE
Evaluate dns-autoscaler as replacement of HPA for CoreDNS

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#4084]
**How to categorize this issue?**

/area auto-scaling networking
/kind enhancement
/priority 3

**What would you like to be added**:
Evaluate dns-autoscaler as replacement of HPA for CoreDNS.

Currently simple [horizontal](https://github.com/gardener/gardener/blob/v1.23.0/charts/shoot-core/components/charts/coredns/templates/coredns-hpa.yaml) pod autoscaler that scales based on the CPU usage. The community provides a [guideline](https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/) how dns-autoscaler to be used for the CoreDNS. This solution also respect the size of the cluster and can help in large clusters.

**Why is this needed**:

**Comment by ScheererJ** [comment]
I would like to introduce the cluster proportional dns autoscaling as described in the [guideline](https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/) as an option next to the existing horizontal pod autoscaling of core dns. Both approaches have up- and downsides. While the former one takes the cluster size into account, the latter one considers the actual cpu load. Therefore, I believe it would be beneficial if operators could choose between both modes of operation depending on their scenario.
As the switch is not only temporary, I think it makes sense to extend the shoot cluster specification accordingly. My proposal is to add an `autoscaling` flag to `shoot.spec.dns`:
```
...
spec:
...
  dns:
    autoscaling: horizontal|cluster-proportional
    domain: ...
    providers: ...
...
```

What do you think?

**Comment by vpnachev** [comment]
`shoot.spec.dns` is about the external address of the API of the cluster and also some DNS configurations for the requested hostname, i.e. it is not about the CoreDNS.

Personally, I think it should be in `shoot.spec.addons`.

**Comment by rfranzke** [comment]
I am with @vpnachev, though, maybe we should introduce a new section `.spec.systemComponents` and can have `.spec.systemComponents.coreDNS.autoscaling.mode: horizontal|cluster-proportional`. The `.spec.addons` section was always referring to optional components like k-dashboard or nginx-ingress. WDYT?

**Comment by vlerenc** [comment]
Hmm... I have difficulties with this proposal in general. If you make it configurable, I see mostly downsides:
- We have the effort to offer that
- We have the burden to maintain both approaches
- We will be asked for a recommendation anyway, because how should people know
- We will be confronted with the statement that it's our responsibility to do it right (no other managed service provider offers that as a configuration option)
- Above else, if it fails, we cannot deflect to the cluster owners and they will still insist that it's our responsibility (and it is)
- And if they switch and it doesn't work, then for other reasons, we are back at square one

So, I have difficulties. Why are these thoughts wrong? If they are not, shouldn't we rather hold our horses and think about a better solution? If both approaches have flaws and neither we nor the cluster owners know what's better, then we should not do something hastily and reconsider our options again, should we not?

**Comment by ScheererJ** [comment]
@vlerenc From my perspective, the main reason for making it configurable was that we will need a longer period of time to switch from one solution to another for such a crucial thing as dns. In the discussion with @rfranzke annotations came up as an option, but was voted against as ugly if it was to stay like that mid term. Therefore, the idea was to introduce something in the shoot spec instead.

In general, I believe our current solution for dns autoscaling is very limited. We have already seen some clusters (most recently in December) hitting the limits of the 5 coredns replicas. A mitigation for this is node-local-dns with its own set of problems, especially when switching it off again (essentially requiring to roll the cluster). The dns-autoscaler as linked in the issue mostly falls in between the current solution and a solution with node-local-dns, but it can add more flexibility in terms of configuration (if we want to allow it). The only downside it can have is that for smaller clusters it might result in less coredns replicas than the existing solution. This is why I would not want to switch everything automatically and cautiously move slowly.

Not sure why you assume that there would be no default/documentation when both are standard in the gardener context. To spill it out load: I want to have a default option and this default might change over time. We could provide more flexibility in terms of configuration in that cluster operators could adapt the autoscaling according to their needs, e.g. if a cluster simply performs more dns queries it could increase the number of replicas.

For me, the goal would be to move over completely to dns-autoscaler in the long run, but this might take a long time (read: year(s)). Please let me know in case you
- agree with the approach/proposal
- disagree and want to stay with the current dns solution (Then we might want to close the issue.)

Obviously, any feedback in between is also welcome.

**Comment by vlerenc** [comment]
Thanks @ScheererJ @DockToFuture for the out-of-band discussion. Now I understand better and indeed, I share your view that we should make it configurable (as part of the shoot spec). Not so much as a temporary solution to test the auto-scaler, as I initially thought was the intention, but, as you have pointed out, as means to allow stakeholders to tweak the settings should the auto-scaling solution not work as expected/good enough. We aren't in the line of fire then anymore and people can help themselves. The alternatives (or compensating side-solutions) aren't available yet (we see unbalanced DNS pod usage, so need vertical scaling as well, but VPA has many shortcomings and we haven't resolved those yet; node-local DNS has some unexplained technical issues as well that we haven't fully understood and has some limitations we haven't resolved yet). That gives us not many other options, if we want to resolve the DNS issues anytime soon, but that's what we want/need, so your proposal is the best and we should do as you suggested.
