### ISSUE TITLE
Namespace deletions may lead to projects without corresponding namespaces

### ISSUE THREAD

**Issue by adracus** [gardener/gardener#409]
Sometimes the deletion of a namespace that a project references goes unnoticed in our project controller. We have to add adapt our code / add a garbage collection loop that can collect and delete such orphaned projects.

**Comment by rfranzke** [comment]
How is be possible? We register a validating webhook that gets triggered on namespace deletion and deny deletion of namespaces if it wasn't done via the project resource?!

**Comment by petersutter** [comment]
I created a project with the dashboard (the dashboard currently only creates the namespace). After I created the project I quickly deleted it again from the dashboard. Most likely it was a race condition.

**Comment by rfranzke** [comment]
Still, I don't understand. If the namespace has been deleted already then the project creation should fail (as the namespace name gets written to the project's `.spec.namespace` field, but then namespace does no longer exist).

Have you done this on your local setup/minikube cluster?

**Comment by petersutter** [comment]
no this was done on the dev landscape
