### ISSUE TITLE
Optimize memory footprint of gardener-apiserver

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4106]
**How to categorize this issue?**

/area cost scalability
/kind enhancement
/priority 3

**What would you like to be added**:

While looking into https://github.com/gardener/gardener/pull/4100#discussion_r638534525, @BeckerMax and I discovered, that `gardener-apiserver` consumes a huge amount of memory in large landscapes, e.g. in a landscape with ~2.4k shoots:
```
gardener-apiserver-676df7b954-4jhq4                  333m         7046Mi
gardener-apiserver-676df7b954-6hxzr                  1580m        6953Mi
gardener-apiserver-676df7b954-9jqt5                  287m         8851Mi
gardener-apiserver-676df7b954-cw2ml                  200m         5971Mi
gardener-apiserver-676df7b954-w6gxr                  382m         5138Mi
gardener-apiserver-676df7b954-xmgc8                  255m         6043Mi
```

Part of this is probably due to watching `ShootState`s in admission plugins – they are very large resources (in the same landscape, all `ShootStates` were about `650MiB` in total).

Steps to reduce the memory footprint, that look quite promising:
- try to get rid of `ShootState` watches in admission plugins (all other gardener components also don't watch `ShootStates`) and replace it with other means (metadata-only watches/clients or direct reads where applicable)
- check if we can/should reduce the default/maximum watch cache size for `ShootStates`

**Why is this needed**:

This is needed to cut down cost for large gardener installations.

**Comment by rfranzke** [comment]
I assume we can close this issue for now. After #8073, we have drastically reduced the number of `ShootState`s, so memory usage has dropped significantly (by roughly 1 - 1.5 GiB for big landscapes).
Feel free to reopen with new steps if you think otherwise.
/close
