### ISSUE TITLE
Update architecture documentation

### ISSUE THREAD

**Issue by RaphaelVogel** [gardener/gardener#4120]
**How to categorize this issue?**

/area documentation
/kind enhancement
/priority 4

**What would you like to be added**:
Update the architecture picture (https://github.com/gardener/gardener/blob/master/docs/concepts/architecture.md) and description to reflect changes with regards to "reversed cluster VPN" and "shoot API server via SNI"

**Comment by timebertt** [comment]
cc @mvladev @DockToFuture @ScheererJ
