### ISSUE TITLE
☂️-issue for Server-Side Apply in Gardener

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4122]
**How to categorize this issue?**

/area dev-productivity scalability
/kind impediment

From https://github.com/gardener/gardener/issues/4083:

> [...] [Server-Side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/). We identified many places, especially in the Gardenlet code, that will benefit from SSA compared to Json-Merge/Strategic-Merge patches that are used today. Less conflicts, less network transfers, less API calls, lower code complexity, etc.. Other components in the Gardener landscape, e.g. Etcd-Druid or provider extensions, will benefit from SSA to at least the same extent.

While investigating how and under which circumstances SSA can be leveraged in Gardener as part of https://github.com/gardener/gardener/pull/4027, we got aware of the following major problems that will most probably prevent us from leveraging SSA as originally intended. @timuthy and I agreed on summarizing them in an issue for future reference.

- removing/unsetting fields in custom resources via apply that were set during a previous apply is buggy (ref https://github.com/kubernetes/kubernetes/issues/101036, https://github.com/kubernetes-sigs/structured-merge-diff/issues/171). The bug was fixed in `v1.21` and backported to `v1.{18,19,20}`, though we would heavily depend on it once gardener uses SSA to deploy/reconcile extension resources (e.g. `Infrastructure`) in the seed.
  - We probably don't want to add additional requirements for specific patch versions for the seed's k8s versions (e.g. require at least `v1.18.19`), so this effectively prevents us from properly using SSA for this use case.
- switching from the typical `CreateOrUpdate`-logic to SSA in a controller doesn't seem to be straight-forward for resources that were created before SSA was enabled (resources that don't have field ownership tracked in `metadata.managedFields` yet).
  - The problem is, that the first apply will add the `before-first-apply` field manager, that owns all fields that were present before the apply. Once the new field manager (e.g. `gardenlet`) wants to remove a field, it will only give up ownership but the field will still not be removed, as it is still co-owned by the `before-first-apply` manager.
  - In order to workaround this issue and take over sole ownership of all fields during the migration, we need to take ownership of at least one field before the first apply
  - e.g. take ownership of timestamp annotation:
  ```
  $ k patch infra infra --type=merge -p '{"metadata":{"managedFields": [{"apiVersion":"extensions.gardener.cloud/v1alpha1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:gardener.cloud/timestamp":{}}}},"manager":"gardenlet","operation":"Update","time":"2021-05-27T13:03:49Z"}]}}'
  ```
  - and then apply the full spec, which will make the new manager owner of all spec fields

There are also other minor problems with SSA, that won't hinder us from using it, but are worth keeping in mind:
- `ApplyConfiguration`s for built-in API resources are only available in `client-go@v1.21+` (ref https://github.com/kubernetes/enhancements/issues/2155), so we will need to vendor `v1.21` first before using SSA for built-in types, where using go structs is not applicable
- `ApplyConfiguration`s for our own API types need to be generated using [applyconfiguration-gen](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/code-generator/cmd/applyconfiguration-gen), so same condition for them as above
- several issues cause the `resourceVersion` to be bumped on every SSA even though it's a no-op (https://github.com/kubernetes/kubernetes/issues/100024)
  - one of them regarding the `creationTimestamp` is solved in `v1.22` (ref https://github.com/kubernetes/kubernetes/pull/100032)
- `status` is tracked in `managedFields` although not set explicitly by an applier (as our extension API types don't specify `omitempty` for the status field)
  - not problematic as long as the status is protected by the `/status` subresource and status itself is not updated via SSA
  - fixed in `v1.21` (ref https://github.com/kubernetes/kubernetes/pull/99661)
- changes via the `/scale` subresource are not tracked in `managedFields`
  - fixed in `v1.22` (ref https://github.com/kubernetes/kubernetes/pull/98377)
  - not problematic for us right now (I think), as long as we don't use SSA for resources scaled by HPA

**Comment by timebertt** [comment]
So far there's no decision whether to drop the idea of using SSA in gardener or pursue it further. However, the list above shows that we have to be very conscious about when we can properly leverage it.
We still want to understand the `before-first-apply` manager and the reasoning behind it, so maybe this provides us with some more arguments for taking a decision here.

**Comment by timebertt** [comment]
There is an upstream issue about the migration from CSA/`CreateOrUpdate` to SSA: https://github.com/kubernetes/kubernetes/issues/99003

**Comment by timuthy** [comment]
We recently discussed this topic again in the context of naming conflicts between `gardener/gardener` and its extensions.

Currently, Gardener does not enforce a unified naming scheme or reserve any specific prefix for Kubernetes resources. As a result, naming conflicts and resource overwrites can easily occur, especially when resources are managed via `ManagedResource`s. This makes it difficult for operators to identify the root cause and find a solution.

With SSA and field managers, such conflicts are typically reported earlier in the process and are more visible in the controller logs.

@timebertt, quite some time has passed since we identified the issues listed above, and most, if not all, have been addressed in the meantime. Does it make sense to revisit the topic again?

/cc @matthias-horne @MartinWeindel @LucaBernstein

**Comment by timebertt** [comment]
Hmm, I think this needs some more careful evaluation. My feeling is that server-side apply is not well-suited for controllers for ensuring a desired spec in specific objects. Generic controllers applying some input (Flux Kustomize controller or ManagedResource controller) are a different story however and might benefit from server-side apply (but changes semantics to keep changes by users to system components for example).
I'm happy to discuss this in more detail and I'm interested in your thoughts on solving the mentioned naming conflicts in ManagedResources.
