### ISSUE TITLE
Definitions/decisions for helm chart repository

### ISSUE THREAD

**Issue by morremeyer** [gardener/gardener#4123]
**How to categorize this issue?**
/area delivery
/kind enhancement
/priority 3

**What would you like to be added**:

As [discussed in Slack](https://kubernetes.slack.com/archives/CB57N0BFG/p1621333321024300) and in #1823, there is interest in having a helm chart repository for all charts needed to successfully deploy gardener.

I want all charts that are required to deploy and maintain a gardener setup to be included in that repository (not necessarily from the start, but that should be the goal). Charts only used/needed for development do not need to be part of the repository.

**Why is this needed**:

To simplify deployment without landscaper or garden-setup.

**What I want to discuss**:

I want to discuss a bit about the approach we should take for this so that everyone is aware about the efforts being made and aim and direction they are being made for/in.

**Current state/proposal**:

I am currently working on the addition of a release workflow for the controlplane and gardenlet charts. This is using [helm's chart releaser](https://github.com/helm/chart-releaser) („cr“) tool which simplifies a lot of the work to be done.

cr packages the charts and releases them as a GitHub release, then creates the necessary index.yaml file and pushes it to the `gh-pages` branch which will then be published to GitHub pages.

**Open Questions**:

* I’d like to have feedback on the proposed workflow with chart-releaser and GitHub pages - is this acceptable for the maintainers, what do you think about it?
* Which charts are only needed for testing/development? 
* Do we need to include the charts needed for testing/development?
* Is the current directory structure under `charts` required as-is? The limitation of my current work to the controlplane and gardenlet chart is mostly based on the fact that `cr` can only release charts from one directory. To simplify the chart release mechanism, it would be beneficial to have all charts directly in the `charts/` directory.
* How do we want to handle chart versioning? The [helm best practices](https://codefresh.io/docs/docs/new-helm/helm-best-practices/#chart-versions-and-appversions) have a good overview of 1-1 versioning vs. seperated versioning. I lean towards a seperated versioning as it enables us to release the charts in between of gardener releases.

**Comment by lotharbach** [comment]
These are the charts and their sources that we consume for our helm-based setups:
```
git clone --depth 1 --branch "v${GARDENER_VERSION}" --depth 1 https://github.com/gardener/gardener.git $REPO/gardener
git clone --depth 1 --branch "$GARDEN_SETUP_VERSION" https://github.com/gardener/garden-setup.git $REPO/garden-setup
git clone --depth 1 --branch "$DASHBOARD_VERSION" https://github.com/gardener/dashboard.git $REPO/gardener-dashboard

rsync -vLr --delete $REPO/gardener/charts/gardener/controlplane/ $FOLDER/gardener-controlplane/
rsync -vLr --delete $REPO/gardener/charts/gardener/gardenlet/ $FOLDER/gardenlet/
rsync -vLr --delete $REPO/garden-setup/components/etcd/cluster/chart/ $FOLDER/garden-etcd/
rsync -vLr --delete $REPO/garden-setup/components/kube-apiserver/chart/ $FOLDER/kube-apiserver/
rsync -vLr --delete $REPO/gardener-dashboard/charts/gardener-dashboard/ $FOLDER/gardener-dashboard/
rsync -vLr --delete $REPO/gardener-dashboard/charts/identity/ $FOLDER/identity/

find $FOLDER -name Chart.yaml -type f -exec sed -i "s/version: 0.1.0/version: $GARDENER_VERSION/g" {} +
```

I think everything except controlplane and gardenlet in charts/gardener is not meant for human consumption. For a setup that enables the virtualGarden you need to install 
charts/gardener/controlplane/charts/application/ and runtime/ seperately with different kubeconfig targets, so I believe they need to be released as seperate charts in addition to the complete "controlplane" chart. I suggest to copy the charts into a single folder as required by chart-releaser so the structure in git can stay as it is, at least for now.

**Comment by timebertt** [comment]
> * I’d like to have feedback on the proposed workflow with chart-releaser and GitHub pages - is this acceptable for the maintainers, what do you think about it?

> * How do we want to handle chart versioning? The helm best practices have a good overview of 1-1 versioning vs. seperated versioning. I lean towards a seperated versioning as it enables us to release the charts in between of gardener releases.

I have some concerns about the proposed approach. I would rather release charts in lock-step with gardener itself, because of the following reasons:
- usually we adapt the controlplane and gardenlet charts to changes in the components in the same PR (as this is the easiest flow). Releasing new chart versions for every change to the charts would mean having released charts that require newer component versions, that may not have been release yet. To do this properly, we would have to adapt the charts separately when also releasing the components, which is quite the inconvenient flow FMPOV.
- existing tooling for deploying those charts (garden-setup, landscaper and internal tools) already assume, that both the charts and the components are released in lockstep
- I don't see a real benefit of releasing charts in between gardener releases

> These are the charts and their sources that we consume for our helm-based setups: [...]

As there are charts involved from other repos, I can imagine, that having a dedicated repo (e.g. `gardener/charts`) to where charts are synced after releases of the individual repos is a pragmatic and (probably) simple option.

@Diaphteiros @schrodit @ccwienk for more opinions

**Comment by morremeyer** [comment]
> usually we adapt the controlplane and gardenlet charts to changes in the components in the same PR (as this is the easiest flow)

That’s a very good point and we definitely shouldn’t break this workflow. As helm requires the usage of semver, we can’t keep the version numbers the same anyway.

> existing tooling for deploying those charts (garden-setup, landscaper and internal tools) already assume, that both the charts and the components are released in lockstep

Do they assume that the releases are in lockstep or that the version numbers are the same?

> I don't see a real benefit of releasing charts in between gardener releases

In my opinion, if a chart has a bug, there should be a possibility to fix that bug without waiting for the next gardener release.

> As there are charts involved from other repos, I can imagine, that having a dedicated repo (e.g. gardener/charts) to where charts are synced after releases of the individual repos is a pragmatic and (probably) simple option.

I think this is a good idea as it would likely simplify certain workflows, especially the chart releasing which could then likely use the chart-releaser GitHub action without needing any workarounds.

**Comment by timebertt** [comment]
> Do they assume that the releases are in lockstep or that the version numbers are the same?

Our internal tooling checks out g/g at the to-be-deployed version and applies the helm chart from the file system (basically what @gesslein described above). I assume, garden-setup does the same (but I don't know).

> In my opinion, if a chart has a bug, there should be a possibility to fix that bug without waiting for the next gardener release.

We are quite fast with doing patch releases in g/g. So if there is a bug in the helm chart, we can quickly release patch releases with fixes exactly like we also do for the binaries (see https://github.com/gardener/gardener/blob/master/docs/development/process.md).
This is how we handled things in the past already when we had bugs in the helm charts and it worked quite well, so I don't see any problem with this workflow. Do you?

**Comment by morremeyer** [comment]
> I don't see any problem with this workflow. Do you?

No, if we don’t have a dependency for the chart to have the exact same version as the gardener release, we’re good imho.

So we’d basically be keeping the same workflow, just with a version bump of the charts on each gardener release depending on the changes made.

Let’s wait for feedback by the others to see how we can proceed.

**Comment by schrodit** [comment]
Hi,
sorry for joining late in the discussion.

My comments on the topic:

> cr packages the charts and releases them as a GitHub release, then creates the necessary index.yaml file and pushes it to the gh-pages branch which will then be published to GitHub pages.

We already maintain a helm chart repo for our [test charts](https://github.com/gardener/gardener/blob/master/test/framework/resources/repository/repositories.yaml#L8) in our google cloud bucket (https://storage.googleapis.com/gardener-public/integrationtests-charts).
Would it be possible with the CR tool to use the google storage?

> Our internal tooling checks out g/g at the to-be-deployed version and applies the helm chart from the file system (basically what @gesslein described above). I assume, garden-setup does the same (but I don't know).

Yes garden-setup also clones the github repo.

> existing tooling for deploying those charts (garden-setup, landscaper and internal tools) already assume, that both the charts and the components are released in lockstep

In fact we plan to also create artifacts for every headupdate and pull request similar to the docker images.
This will be part of the long waiting pre-release testing of gardener.

Aside from that, the Gardener Landscaper components will be included in the docker images so we do not rely on a chart repository (cc @danielfoehrKn ).<br>
Sidenote: In fact we in the Landscaper work with the new helm oci artifact distribution e.g. https://github.com/gardener/landscaper/blob/master/hack/create-helm-chart.sh#L47

> How do we want to handle chart versioning? The helm best practices have a good overview of 1-1 versioning vs. seperated versioning. I lean towards a separated versioning as it enables us to release the charts in between of gardener releases.
>
> >usually we adapt the controlplane and gardenlet charts to changes in the components in the same PR (as this is the easiest flow)
>
> > > That’s a very good point and we definitely shouldn’t break this workflow. As helm requires the usage of semver, we can’t keep the version numbers the same anyway.
>
> > > > So we’d basically be keeping the same workflow, just with a version bump of the charts on each gardener release depending on the changes made.So we’d basically be keeping the same workflow, just with a version bump of the charts on each gardener release depending on the changes made.

These are good points but I think I do not get the result of that discussion.
Currently the gardener chart version is hardcoded to `0.1.0`.
So the suggested flow is that the chart version will not be the same as the gardener version but rather will be manually bumped if changes happen?

**Comment by morremeyer** [comment]
>  Would it be possible with the CR tool to use the google storage?

No, cr is explicitly made for github pages. I’m not at all set on using github pages, it was just the easiest tool to get started with.

>  So the suggested flow is that the chart version will not be the same as the gardener version but rather will be manually bumped if changes happen?

The chart version will only be bumped (and therefore the release process triggered) when a gardener release happens (to avoid having a released chart version that requires component versions that are not released).

Due to the requirement by helm that chart versions are semver, we won’t be able to keep the gardener version and the chart version(s) in sync once we start versioning the charts - not every breaking change to the charts will be accompanied by a breaking change in gardener.

If we start with the next gardener release and set the chart version to the gardener version of that release, the chart versions will always be at least the gardener version, but will eventually have larger numbers:

* Every gardener release triggers a chart version update due to the image version change in the default values
* Changes in the chart due to new features in components (= gardener minor version bump) may mean breaking changes in the Chart, bumping its major version.

**Comment by morremeyer** [comment]
@schrodit, @timebertt Given the current state and the plans that you have, especially with landscaper: Is there a preferred solution for the requirement „I want to use the controlplane and gardenlet charts in a helm native way (i.e. without cloning the git repo)?“

I’d like to push this topic forward to resolve that clunky step in our deployments, but I also don’t want to make it overly complex.

**Comment by schrodit** [comment]
> @schrodit, @timebertt Given the current state and the plans that you have, especially with landscaper: Is there a preferred solution for the requirement „I want to use the controlplane and gardenlet charts in a helm native way (i.e. without cloning the git repo)?“
> 
> I’d like to push this topic forward to resolve that clunky step in our deployments, but I also don’t want to make it overly complex.

With the Landscaper we use a dedicated installer that has the helm charts embedded.
Pushing the charts to another registry does not interfere with the Landscaper plans.

I think its more about the maintenance aspect which is the decision of the core team.
@timebertt do you have a preferred way forward?

**Comment by timebertt** [comment]
> @timebertt do you have a preferred way forward?

Well, I outline my proposal above and I think, I haven't seen any concerns/objections. 
So I'm fine with continuing like that or discussing concrete steps.

**Comment by morremeyer** [comment]
Thanks for your comments.

## Proposal

I would for now not use a seperate `gardener/charts` repository for now as this would lead to duplicated code, but we should keep this in mind for possible future changes.

I think the easiest to achieve and least complex solution to solve the requirements for a „pure helm chart deployment“ is the following:

* Configure `cr` for the g/g repository in a [GitHub Action](https://github.com/helm/chart-releaser-action), but only for the `charts/gardener` directory. This will only package the `controlplane` and `gardenlet` charts, but those are currently the only charts needed for a pure helm deployment.
* Configure `cr` for the g/dashboard repository in a GitHub Action for the `charts` directory.
* Only bump version numbers for the charts when releasing a new version of gardener (or the dashboard in case of the dashboard repository).

With this, both repositories would have a new `gh-pages` branch to which `cr` would push the chart index to and which would be the source for a GitHub Pages page.

This would result in two helm repositories (one for g/g, one for g/dashboard) which is in my opinion a worthy tradeoff as it **does not require any changes** to the current development workflows.

Additional maintenance/efforts will be:
* possible debugging of the cr GitHub action if releases fail
* periodic updates of the cr GitHub action when needed

## Implementation

I would take care of 

* Opening a PR in both g/g and g/dashboard to 
  * create the `gh-pages` branch with an index page so that requests to https://gardener.github.io/gardener/ and https://gardener.github.io/dashboard/ don’t run into a 404, but a short „this is a helm chart repository, check the repository at $link“ page.
  * add a GitHub Action that runs `cr` on the proposed directories
* be part of/available for maintenance/debugging of the GitHub Actions and release workflow in general for at least the foreseeable future.

## Approvals

@timebertt, @schrodit: As you are the maintainers who have so far commented this, do you agree? Please comment or simply thumbs up this comment - if you agree, I’ll start the implementation.

**Comment by schrodit** [comment]
> I would take care of
>
> Opening a PR in both g/g and g/dashboard to
> create the gh-pages branch with an index page so that requests to https://gardener.github.io/gardener/ and https://gardener.github.io/dashboard/ don’t run into a 404, but a short „this is a helm chart repository, check the repository at $link“ page.
> add a GitHub Action that runs cr on the proposed directories
be part of/available for maintenance/debugging of the GitHub Actions and release workflow in general for at least the foreseeable future.

looks good to me and I think we are currently fine with 2 helm repositories.
We should then also add the release flow and responsibility somewhere in the docs (maybe https://github.com/gardener/gardener/blob/master/docs/development/process.md)

**Comment by morremeyer** [comment]
#4259 adds the helm chart releasing.

I’d also like to PR https://github.com/morremeyer/gardener/tree/gh-pages to create the index page for GitHub pages, but GitHub doesn’t allow a PR to a non-existing branch. If one of the maintainers wants to do this, you can push the contents of my branch to a `gh-pages` branch in this repository.

I’ll now get to work on the changes for g/dashboard and link them here once finished.

**Comment by timebertt** [comment]
@morremeyer Sorry for jumping in just now.

TBH, I'm a bit confused, why you're now proposing to publish charts in multiple repositories, although I proposed to publish them in a dedicated repo, e.g. `gardener/charts`, see https://github.com/gardener/gardener/issues/4123#issuecomment-851323237. There were no objections/concerns about that earlier, so why are we moving now into a different direction?

I would imagine the flow to be somewhat like this:
- `gardener/gardener` or `gardener/dashboard` gets released
- workflow kicks in on release published event and triggers a `workflow_dispatch` / `repository_dispatch` event on `gardener/charts` (similar to the [gardenctl release workflow](https://github.com/gardener/gardenctl/blob/master/.github/workflows/update-gardenctl.yml), which publishes a new version in the [homebrew-tap](https://github.com/gardener/homebrew-tap/blob/master/.github/workflows/update-tags.yml))
- this workflow in `gardener/charts` fetches the given charts folder from the released repo using the given release tag, rewrites the chart version in `Chart.yaml` and pushes them to the `master/main` branch into the `charts` directory
- `cr` action is configured in `charts/gardener` and be triggered on push events, so it will immediately release the charts after the previous step

Advantages of this approach:
- only one helm repo to add, maintain, etc.
- we don't mess up tags on all repos that publish charts (e.g. I wouldn't want to pollute the g/g release list with extra chart releases)
- no additional work needed by the releasing person
- only minimal configuration needed in g/g and g/dashboard and the "main logic" for chart handling and publishing would reside in g/charts

So, that's the approach, that makes most sense from my perspective.
If you want to do something else, let's have a call next week and discuss it or use it to clarify open questions first, before you waste any time on PRs.

One question is still open for me:
- How do you plan on handling the `application` / `runtime` subcharts of the `gardener/controlplane` chart? Because they basically have to be installed individually and a single published helm chart in the repo wouldn't allow that, if I'm not mistaken.

**Comment by morremeyer** [comment]
@morremeyer No worries, better now than later :) 

I took your proposal to use a seperate `gardener/charts` repo as an alternative idea, not as a preference from your side. I didn’t know about the `workflow_dispatch` events that you already use (as with the gardenctl example) - this clears things up for me, thank you!

Now that I got that, I can get behind your proposal 100%.

Regarding the `application` and `runtime` subcharts: Those are automatically packaged into the .tgz of the chart release (even recursively), you can see that e.g. in my test `index.yaml` at https://github.com/morremeyer/gardener/blob/04de616182c4caaa9ef60a2b49beded09dacc62c/index.yaml, where the [controlplane-0.1.0.tgz](https://github.com/morremeyer/gardener/releases/download/controlplane-0.1.0/controlplane-0.1.0.tgz) contains all needed files.

To get started with this, someone would need to create the `gardener/charts` repository so that I can PR to it.

Thanks again @timebertt for the input!

**Comment by timebertt** [comment]
> Now that I got that, I can get behind your proposal 100%.

Nice, that's great to hear!

> To get started with this, someone would need to create the `gardener/charts` repository so that I can PR to it.

Will do :)

> Regarding the `application` and `runtime` subcharts: Those are automatically packaged into the .tgz of the chart release (even recursively), you can see that e.g. in my test `index.yaml` at https://github.com/morremeyer/gardener/blob/04de616182c4caaa9ef60a2b49beded09dacc62c/index.yaml, where the [controlplane-0.1.0.tgz](https://github.com/morremeyer/gardener/releases/download/controlplane-0.1.0/controlplane-0.1.0.tgz) contains all needed files.

Ok. How would you then use the subcharts as a user? Because you have to apply them to different clusters, if you want to use the virtual garden construct... If you don't, then I expect you can just install everything at once and this should be straight forward, right?

**Comment by timebertt** [comment]
> To get started with this, someone would need to create the `gardener/charts` repository so that I can PR to it.

Here you go: https://github.com/gardener/charts, https://gardener.github.io/charts/ 🚀

**Comment by morremeyer** [comment]
> Ok. How would you then use the subcharts as a user? Because you have to apply them to different clusters, if you want to use the virtual garden construct... If you don't, then I expect you can just install everything at once and this should be straight forward, right?

I’ve so far not used the virtual garden construct, but I don’t think it would be possible with that, yes. To enable this, we’d likely have to package both charts seperately and use them as dependencies for the `controlplane` chart. @gesslein, do you have more insight into that?

I would however nevertheless start with the work on `g/charts` to add controlplane, gardenlet and dashboard to it - if we need to pull in the subcharts as dependencies, this can be added later. Do you agree @timebertt?

**Comment by timebertt** [comment]
> I would however nevertheless start with the work on `g/charts` to add controlplane, gardenlet and dashboard to it - if we need to pull in the subcharts as dependencies, this can be added later. Do you agree @timebertt?

Yes, that sounds reasonable. Let's start with that.
If we want to support the virtual garden use case later on, it should be possible by publishing dedicated charts and just make the `controlplane` chart a compound of both (so you can still install both at the same time as before).
As I understood, the helm charts are mainly supposed to support the "getting started" users, they will probably not care about the virtual garden concept.

**Comment by christianhuening** [comment]
I am currently working to set up the virtual garden also via helm charts. The approach from @gesslein that I also adopted is to use this chart for the virtual garden k8s apiserver: https://github.com/gardener/garden-setup/tree/master/components/kube-apiserver/chart 

I am currently pulling all the required charts down and build a central super chart from that in our internal tooling pipeline.

**Comment by morremeyer** [comment]
@timebertt To commit the changes in g/charts once the charts have been pulled and the version updated, I’ll use [what is already there in the homebrew-tap](https://github.com/gardener/homebrew-tap/blob/3fbba877e4eac72c42d02efd93bc1e6da465f676/.github/workflows/update-tags.yml#L16-L25).

Can I reuse the `gardener-robot-ci-1` user here? If no, which user with which mail adress should I use?

**Comment by timebertt** [comment]
That sounds good, no objections/concerns 👍

**Comment by morremeyer** [comment]
### Technical refinement 

@timebertt and I met today to discuss some technical details and refinements. We came to the following conlusions:

* the `g/charts` repository should only contain resources that we need to publish the charts. For `g/g` charts, this is e.g. `charts/gardener` and `charts/utils-templates`
* the `g/charts` repo will contain a `charts/$repository` directory for every repository that we sync charts from. This is to prevent conflicts between different files and to make it clear which repository the files originate from.
* the `g/charts` repo should not have to be changed if there are changes to the charts structure, therefore we will add a new artifact to `g/g` and `g/dashboard` releases: A `charts.tar.gz` file that contains all needed files for the `g/charts` repository. This artifact will be generated in a GitHub Action in the respective repsitory. This solution allows us to keep all necessary changes in one repository, so no changes need to be made to `g/charts` when the chart dependencies or structure changes.
* `cr` will be executed in `g/dashboard` in a GitHub action that runs `cr` once per sub-directory of `charts`.

/assign morremeyer

**Comment by morremeyer** [comment]
@timebertt and I discussed another implementation detail regarding when `cr` is run:

The plan was to update the charts in the `workflow_dispatch` workflow and push the changes to the repository. A second workflow would then run `on: push` to run `cr`.

During implementation, I discovered that this is not possible without a workaround (PAT that has push access). 

@timebertt and I therefore decided to also run `cr` in the `workflow_dispatch` workflow that is updating the charts. The original workflow that only runs `on: push` will be kept to enable manual changes shall they ever be needed.

**Comment by morremeyer** [comment]
I talked to @timebertt again at the beginning of this week as the use of `cr` would require a lot of workarounds that would be hard to maintain. The use of helms packaging and indexing features would also lead to considerable maintenance effort as the scripting for that would have to be complicated.

We therefore decided to implement the publishing of the helm charts with [helms experimental OCI support](https://helm.sh/docs/topics/registries/) as it fulfils all requirements. With this approach, we can also packages the `application` and `runtime` charts needed for virtual garden without any additional overhead as all scripts are kept generic (vs. the approach with cr where they would need to be specific for each repository we sync charts from). [cc @gesslein]

I’ve implemented this in my fork of the charts repository and end-to-end tested it.

As we need one more permission for the gardener-workflow-app, I contacted @petersutter to take care of this. Once this is done, I’ll open the PRs and link them here.

**Comment by petersutter** [comment]
@morremeyer 

I have created the  app [`gardener-github-workflow-charts`](https://github.com/organizations/gardener/settings/apps/gardener-github-workflow-charts) and installed it into the repository `charts`.

The app has the following permissions:
- `Actions`: Workflows, workflow runs and artifacts. `Read & Write`
- `Metadata`: Search repositories, list collaborators, and access repository metadata. `Read-only`

The permissions are required for the usage of the API https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event

I have created the following organization secrets:
- `GARDENER_GITHUB_WORKFLOW_CHARTS_APP_ID`
- `GARDENER_GITHUB_WORKFLOW_CHARTS_APP_PRIVATE_KEY`

Both keys can be read in the following repositories:
- `gardener`
- `dashboard`

**Comment by timebertt** [comment]
@morremeyer can you update this issue with the current status?

**Comment by morremeyer** [comment]
@timebertt Sorry for being that quiet. I haven't been able to spend any time on this issue as I'm not involved with using gardener anymore.

I can take care of finishing the process/PRs in the upcoming weeks. I'm however not able to support with potential issues in the future.

If this is a deterrent, I suggest keeping this issue in mind as documentation, but closing it to signify the lack of time to contribute.

**Comment by timebertt** [comment]
For anyone subscribed to this issue:
There is https://github.com/gardener-community/gardener-charts introduced by @JensAc @mxmxchere
(also see blog post: https://23technologies.cloud/en/blog/gardener-chart-releaser)
I think it covers everything discussed in this issue.
