### ISSUE TITLE
ShootState Owner Reference bug is wrongly detected as user issue

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#4139]
**How to categorize this issue?**

/area ops-productivity
/kind bug
/priority 3

**What happened**:
When a shoot cluster is affected by https://github.com/gardener/gardener/issues/3962, it is assigned to the `ERR_CONFIGURATION_PROBLEM` category because of the `Invalid value` string in the error message.
However, shoot owner may not have access to the ShootState to fix the ownerReferences, thus classifying this problem as user problem is wrong.

**What you expected to happen**:
To properly classify the shoot state owner reference errors as non-user issues.

**How to reproduce it (as minimally and precisely as possible)**:
See #3962, but make sure that you are not running Gardener landscape with the fix from #4100.

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
Let's close this as https://github.com/gardener/gardener/issues/3962 has been fixed a long time ago.
I think, we should rather refactor the error code handling entirely and not rely on such generic regexes. But this is a much larger topic and needs to be thought through before.
/close
