### ISSUE TITLE
Creation of shoot cluster with wrong OIDC config is allowed

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#4153]
**How to categorize this issue?**
/kind bug
/priority 3

**What happened**:
A shoot cluster with wrong OIDC configuration was created 
```yaml
spec:
  kubernetes:
    kubeAPIServer:
      oidcConfig:
        signingAlgs:
          - abc
```

Later, the `kube-apiserver` deployment was failing with
```
task "Waiting until Kubernetes API server reports readiness" failed: retry failed with context deadline exceeded, last error: kube-apiserver deployment has outdated replicas, logs of newest pod:
...
Error: oidc: unsupported signing alg: "abc"
...
```

**What you expected to happen**:
The OIDC [validation](https://github.com/gardener/gardener/blob/893f4042fa3e4a1814ab04b4dd79e9a09e1f914a/pkg/apis/core/validation/shoot.go#L586-L635) needs to be improved and to disallow unsupported fields to prevent creation of broken shoot clusters.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot with the above OIDC spec.

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
Only the algorithms listed in https://datatracker.ietf.org/doc/html/rfc7518#section-3.1 should be allowed. As the KAPI fails when invalid signing algs are configured, no special handling wrt backwards-compatibility is required.
