### ISSUE TITLE
Configure cluster-wide surge rate

### ISSUE THREAD

**Issue by pluemer** [gardener/gardener#4167]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority 3

**What would you like to be added**:

An option to configure a maximum _cluster-wide_ surge rate for shoot worker nodes.

**Why is this needed**:

Currently, the maximum surge rate for shoot worker nodes can only be configured on a worker group level by setting `maxSurge` in `.spec.provider.workers[]`. As the number of nodes can vary significantly between worker groups, a reasonable surge rate has to be determined per worker group and updated as nodes are added/deleted to not run into cloud provider API rate limits. A cluster-wide surge rate would help to determine a value with which the maximum number of nodes is rolled without running into API rate limits.

**Comment by timuthy** [comment]
For your use case, what would be the best way to distribute such a global `maxSurge` value over the configured worker pools?

**Comment by pluemer** [comment]
> For your use case, what would be the best way to distribute such a global `maxSurge` value over the configured worker pools?

The ratio of a worker group's surge rate to the cluster-wide surge rate should be inverse to the ratio of the worker group's number of nodes to the cluster's total number of nodes, i.e. the more nodes a worker group has, the lower the relative surge rate should be.

**Comment by timuthy** [comment]
Understandable from the motivation you wrote down in the description. Other users might expect a bigger `maxSurge` for big worker pools, to let the rolling update happen faster.

**Comment by pluemer** [comment]
> Understandable from the motivation you wrote down in the description. Other users might expect a bigger `maxSurge` for big worker pools, to let the rolling update happen faster.

We could still add another field to specify the algorithm later if another behavior is requested by other users. What do you think?

**Comment by vlerenc** [comment]
At first I thought, this could also be a machine-controller-manager (MCM) topic as it controls all machines and could control a cluster-wide maxSurge. But either way, I fear this is getting far too complex (too many possible options; custom attachable "algorithm"). Just with schedulers, where you can deploy your own, you can change the settings dynamically with a custom controller, too. Then you have (exactly) what you want/need (see also below).

I anyway doubt this is helping many people. You now argue for quotas concerning only one cluster. I see multiple issues:
- Quota is defined per machine type, so unless you have multiple worker pools with the same machine types (which I haven't seen in the wild), this is pretty much not helpful.
- Often, teams/users have multiple clusters, so even if a per-cluster maxSurge gets implemented, it doesn't solve the cross-cluster quota issues where one cluster "steals" resources from another.
- And then there may be other "entities" using up your quota not even related to Gardener/Kubernetes, e.g. people trying something out in your account.

So, please forgive me, but considering the very narrow use case here and the complexities on the other hand, I don't think it will be done unless you can bring forward stronger arguments.
