### ISSUE TITLE
Landscaper Integration

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#4188]
**How to categorize this issue?**

/area delivery
/kind enhancement
/priority 3

**What would you like to be added**:
Let's integrate with Landscaper and develop components adhering to the APIs and contracts.

**Why is this needed**:
Ease of management of Gardener landscapes

**Comment by rfranzke** [comment]
/assign @danielfoehrKn 
/in-progress

Related PRs:
- #3130
- #3627
- #3757
- #3809
- #3981 
- #3999
- #4283
- #4287
- #4331
- #4835 
- #4865
- #5072
- #5130
- #5233
- #5276

**Comment by danielfoehrKn** [comment]
Closing as landscaper + Gardener integration is postponed (potentially canceled).
