### ISSUE TITLE
Keep Backups after Cluster Deletion

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#42]
**Issue by [vlerenc](https://github.com/vlerenc)**
_Tuesday Oct 24, 2017 at 00:24 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/159_

----

At present, all backups are deleted when the cluster is deleted. It would be better to not delete them  right away and instead keep them for some time and let a garbage collector of sorts delete only those older than a certain grace period (e.g. one month).

**Comment by vlerenc** [comment]
Moved to https://github.com/gardener/etcd-backup-restore/issues/5.
