### ISSUE TITLE
core/v1beta1.Provider should implement runtime.NestedObjectEncoder

### ISSUE THREAD

**Issue by brumhard** [gardener/gardener#4214]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 3

**What would you like to be added**:
I would like the `Shoot` or rather the `Provider` struct in "github.com/gardener/gardener/pkg/apis/core/v1beta1" to implement the `runtime.NestedObjectEncoder` interface.

**Why is this needed**:
The `Provider` contains two fields of type `*runtime.RawExtension`. If the struct is encoded for example when trying to send a request via the kubernetes client package, those fields won't be encoded properly (won't include `TypeMeta` in the json).
This can be fixed by implementing the NestedObjectEncoder interface.
I validated the described behaviour with the following test file.
In this case I implemented the dummy type `InternalShoot` to check the behaviour if the interface is implemented as opposed to the normal `Shoot` type.

I'd be happy to open a PR for that.

```Go
package api

import (
	"bytes"

	openstack "github.com/gardener/gardener-extension-provider-openstack/pkg/apis/openstack/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/serializer/json"
	"k8s.io/client-go/kubernetes/scheme"

	openstackinstall "github.com/gardener/gardener-extension-provider-openstack/pkg/apis/openstack/install"
	gardeninstall "github.com/gardener/gardener/pkg/apis/core/install"
	gardencore "github.com/gardener/gardener/pkg/apis/core/v1beta1"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

type InternalShoot struct {
	*gardencore.Shoot
}

// Implement the interface
func (s *InternalShoot) EncodeNestedObjects(e runtime.Encoder) error {
	if err := encodeNestedRawExtension(e, s.Spec.Provider.InfrastructureConfig); err != nil {
		return err
	}

	if err := encodeNestedRawExtension(e, s.Spec.Provider.ControlPlaneConfig); err != nil {
		return err
	}

	return nil
}

// encodeNestedRawExtension will encode the object in the RawExtension (if not nil) or
// return an error.
func encodeNestedRawExtension(e runtime.Encoder, ext *runtime.RawExtension) error {
	if ext == nil {
		return nil
	}
	if ext.Raw != nil || ext.Object == nil {
		return nil
	}
	data, err := runtime.Encode(e, ext.Object)
	if err != nil {
		return err
	}
	ext.Raw = data
	return nil
}

var _ = Describe("shoot decode", func() {
	var enc runtime.Encoder
	var shoot runtime.Object = &gardencore.Shoot{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "test",
			Namespace: "a",
		},
		Spec: gardencore.ShootSpec{
			Provider: gardencore.Provider{
				ControlPlaneConfig: &runtime.RawExtension{Object: &openstack.ControlPlaneConfig{
					LoadBalancerProvider: "octavia",
				}},
				InfrastructureConfig: &runtime.RawExtension{Object: &openstack.InfrastructureConfig{
					FloatingPoolName: "floating-net",
					Networks: openstack.Networks{
						Workers: "10.250.0.0/16",
					},
				}},
			},
		},
	}
	BeforeEach(func() {
		gardeninstall.Install(scheme.Scheme)
		openstackinstall.Install(scheme.Scheme)
		enc = scheme.Codecs.EncoderForVersion(&json.Serializer{}, gardencore.SchemeGroupVersion)
	})
	Context("shoot does not implement NestedObjectEncoder", func() {
		It("should fail", func() {
			buffer := &bytes.Buffer{}
			err := enc.Encode(shoot, buffer)
			Expect(err).ToNot(HaveOccurred())
			Expect(buffer.String()).ToNot(ContainSubstring("openstack.provider.extensions.gardener.cloud/v1alpha1"))
		})
	})
	Context("shoot implements NestedObjectEncoder", func() {
		BeforeEach(func() {
			scheme.Scheme.AddKnownTypes(gardencore.SchemeGroupVersion, &InternalShoot{})
			shoot = &InternalShoot{shoot.(*gardencore.Shoot)}
		})
		It("should work", func() {
			buffer := &bytes.Buffer{}
			err := enc.Encode(shoot, buffer)
			Expect(err).ToNot(HaveOccurred())
			Expect(buffer.String()).To(ContainSubstring("openstack.provider.extensions.gardener.cloud/v1alpha1"))
		})
	})
})
```

**Comment by brumhard** [comment]
Of course the same thing applies for all other types that use `*runtime.RawExtension` as property types. A quick search in github revealed that there are plenty of types using it with none of them implementing the interface.

**Comment by timebertt** [comment]
Hi @brumhard.
I think, `runtime.RawExtension.Object` is supposed to only be used after decoding an object to save extra back-and-forth encoding and decoding during conversion ([ref](https://github.com/kubernetes/kubernetes/blob/0bc75afcf262e20a23966c10a3224f8acd1cc117/staging/src/k8s.io/apimachinery/pkg/runtime/types.go#L49-L89)).
Clients should generally always encode the `RawExtension` objects first and then send them via `Raw` to the server.
Serializers are only supposed to take care about the `Raw` field. That the json serializer will also encode the `Object` field is just legacy behavior ([ref](https://github.com/kubernetes/kubernetes/blob/0bc75afcf262e20a23966c10a3224f8acd1cc117/staging/src/k8s.io/apimachinery/pkg/runtime/extension.go#L39)). But the protobuf serializer for example, doesn't touch the `Object` field ([ref](https://github.com/kubernetes/kubernetes/blob/0bc75afcf262e20a23966c10a3224f8acd1cc117/staging/src/k8s.io/apimachinery/pkg/runtime/generated.pb.go#L182)).

Also, I don't see any good reference implementation of `runtime.NestedObjectEncoder` in any of the upstream kubernetes API types. And it seems to target only unversioned embedded objects ([ref](https://github.com/kubernetes/kubernetes/blob/0bc75afcf262e20a23966c10a3224f8acd1cc117/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go#L221)).

I think, what you wanna do, is to either add `ObjectMeta` to your `runtime.RawExtension.Object` (in case you want to rely on the json serializer's special behavior) or encode the embedded object beforehand with the proper scheme+encoder.

**Comment by brumhard** [comment]
Hi there @timebertt, thank you for you detailed explanation.
From the MarshalJSON documentation I have to agreee that it looks like this is actually not the correct way.
Still it feels kinda cumbersome to first decode all nested `RawExtension` fields with the correct scheme and then put it into the struct (just much more code).

I took the implementation from [some openshift code](https://github.com/openshift/client-go/blob/master/vendor/github.com/openshift/api/authorization/v1/codec.go), so it seems like at least openshift is using that (seems like they have their own [serialization package](https://github.com/openshift/api/blob/master/pkg/serialization/serialization.go) just for that purpose).

So I guess the interface isn't too common but it would still improve the experience for the gardener types, since I had a really hard time figuring out that it's not marshaled correctly (the `RawExtension` docs only mention the decoding). 
Also I don't think that it's only for unversioned objects, a few lines after your referenced line it's called again ([ref](https://github.com/kubernetes/kubernetes/blob/0bc75afcf262e20a23966c10a3224f8acd1cc117/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go#L238)).

Anyways I appreciate your detailed answer and I guess I would understand if you don't want to put in the effort for something that isn't too widely used. Now that I know how to solve that, I guess I will get used to it. Maybe there is just some more documentation needed for the RawExtension type in general.

**Comment by timebertt** [comment]
I think, there would be one more problem with the approach proposed above, that I didn't mention so far:
I assume, this will break protobuf serialization, because `RawExtension` fields have to be encoded in json and embedded as plain byte arrays in protobuf, as there are no generated protobuf types for the extension provider configs. And even if there were, gardener-apiserver couldn't know about them.
I might be wrong here, but I still don't want to mess with these kind of things, as they might silently break things without noticing it here in gardener/gardener.

So I appreciate your willingness to use another approach. :)
Do you agree, that we should close this issue, then?

**Comment by brumhard** [comment]
Sure okay works for me 👍  No need to break anything for a minor developer experience improvement.
