### ISSUE TITLE
Missing retry handling in hibernation controller

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4239]
**How to categorize this issue?**

/area robustness
/kind enhancement

**What would you like to be added**:

Retry handling in gardener-controller-manager's hibernation controller.

**Why is this needed**:

Currently, when shoots specify a hibernation schedule, gcm will try to hibernate the shoot (set `spec.hibernation.enabled`) accordingly. However, if there is some temporary problem with for example g-api, a Get/Update request might fail, but the requests are not retried as there is no proper error/retry handling in the [hibernation cron job](https://github.com/gardener/gardener/blob/609107f2b19584315cc639b52668f73820dfc44a/pkg/controllermanager/controller/shoot/shoot_hibernation_types.go#L104).

Controllers should be able to cater with temporary failures and retry actions with exponential backoff in order to eventually reconcile actual state with desired state.

**Comment by timebertt** [comment]
@plkokanov what's the status here?

**Comment by BeckerMax** [comment]
Plamen started with this issue and made some progress so we will keep him assigned.
