### ISSUE TITLE
Exclude pause container images from binary scanning

### ISSUE THREAD

**Issue by ThormaehlenFred** [gardener/gardener#4272]
/area security
/kind technical-debt
/priority 3

**What would you like to be added**:
please look at https://github.com/gardener/gardener-extension-networking-calico/pull/89 and do the same for pause container 3.1 if you agree to this approach as Gardener component owner.

**Why is this needed**:
The pause container image cannot be scanned with the respective tool and returns results of no value.

**Comment by timebertt** [comment]
Seems like a simple change, you should be able to do it 🚀 
However, I don't understand, why such internal specifics need to be in the open source repository.
