### ISSUE TITLE
Kubernetes API server must use approved cipher suites

### ISSUE THREAD

**Issue by ThormaehlenFred** [gardener/gardener#4300]
**How to categorize this issue?**
/area security
/kind enhancement
/priority 3
/platform aws-gov

**What would you like to be added**:
Limit the value of tls-cipher-suites with K8s v1.22 to TLS 1.3 cyphers (available since [Kubernetes v1.19](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#bug-or-regression-18):
TLS_AES_128_GCM_SHA256, 
TLS_CHACHA20_POLY1305_SHA256,
TLS_AES_256_GCM_SHA384
and limit the value of tls-cipher-suites with K8s v1.22 to the ones which are mandated by [STIGs](https://stigviewer.com/stig/kubernetes/2021-04-14/finding/V-242418) required for public sector U.S. and other countries.
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
TLS_ECDHE_ECDSA_WITH_AES_256_GCM _SHA384

The list above is a subset of the current list of [Kubernetes](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/) -> --tls-cipher-suites strings

**Why is this needed**:
Gardener's current list of tls-cipher-suites is:
see in [code](https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager_test.go#L769)
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
TLS_RSA_WITH_AES_128_CBC_SHA,
TLS_RSA_WITH_AES_256_CBC_SHA,
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

Assessment
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (should stay as required by STIGs),
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (should stay as required by STIGs),
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 (should stay as required by STIGs),

TLS_RSA_WITH_AES_128_CBC_SHA (should be removed, because presumably SHA1),
TLS_RSA_WITH_AES_256_CBC_SHA (should be removed, because presumably SHA1),
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (should be removed, presumably because SHA1)

By performing this security configuration adaptation Gardener starts to show [crypto-agility](https://en.wikipedia.org/wiki/Cryptographic_agility), which is one of the prerequisites to be prepared for the upcoming post quantum crypto (PQC) era see [NIST recommendations](https://www.nccoe.nist.gov/projects/building-blocks/post-quantum-cryptography). Beside security configuration adaptations like leveraging cyphers with longer encryption keys >256 bit (see the recommended list above), there are more recommendations as a preparation for PQC era, like TLS 1.3 adoption. 
Beside the agility to correct configurations we need the agility to support and add new algorithm implementations.

**Comment by vlerenc** [comment]
@ThormaehlenFred Just for clarification, because we didn't really understand the statement: we should limit the cipher suites to these 9 then?

```
TLS_AES_128_GCM_SHA256
TLS_AES_256_GCM_SHA384
TLS_CHACHA20_POLY1305_SHA256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM _SHA384
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
```

**Comment by ThormaehlenFred** [comment]
From an external consultant in U.S. I got the information to remove CHACHA20. So the list of remaining ciphers would look like this.
```
TLS_AES_128_GCM_SHA256
TLS_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM _SHA384
```
But I will check if now all of them are TLS 1.3 and if this should be the final list.

**Comment by ThormaehlenFred** [comment]
1. Regarding TLS 1.3 and STIGs the above list is the final list to be applied. 
2. To be quantum computer save in the future we will have to replace the currently used public key algorithms (RSA, (EC)DSA and DH). For AES and SHA it is enough to increase the length. However, this will come with a certain performance penalty which can vary widely between devices. Therefore if applicable a comprehensive testing of the performance impact when enforcing AES_256_GCM_SHA384 instead of AES_128_GCM_SHA256 is recommended already now. If applicable please do this performance testing in the context of a future PR for this issue. We will reference these results when the need for becoming quantum computer save becomes more urgent e.g. by future compliance obligations. Because this will then be the cost in performance and increased compute power we will have to pay for more security.

**Comment by rfranzke** [comment]
From #4363

>  vlerenc commented 33 minutes ago • 
/reopen Uh, @ThormaehlenFred just noticed that the cipher task wasn't completed, but we require that change to improve security/pass the audit. The checkbox was ticked, but the linked issue is open and indeed, https://github.com/gardener/gardener/blame/master/pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager_test.go#L769 shows no change. I will now untick the checkbox.

>  rfranzke commented 1 minute ago
Why? What is missing? c0d0c92 is part of the 1.22 support PR.

**Comment by vlerenc** [comment]
Hmm... we couldn't find it the gardener repo, the ticket (this here) is open, but the line item was marked as closed. If all is good, great. This commit is shown as:

> "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

**Comment by rfranzke** [comment]
> we couldn't find it the gardener repo, the ticket (this here) is open, but the line item was marked as closed.

Probably @timuthy forgot to close it. So, you didn't see any issues with a real system? Can we then finally close it? :-)

> "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

This is because we squash-merged the PR that contains this commit. The respective code is here: https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/tls_cipher_suites.go

**Comment by ThormaehlenFred** [comment]
pkg/utils/kubernetes/tls_cipher_suites.go in https://github.com/gardener/gardener/pull/4562/files# shows that with v1.22 the following ciphers are used:
```
					"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
					"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
					"TLS_AES_128_GCM_SHA256",
					"TLS_AES_256_GCM_SHA384",
					"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
					"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
```
