### ISSUE TITLE
Test failures with `error dialing backend: proxy error from vpn-seed-server`

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4302]
**How to categorize this issue?**

/area networking
/kind bug

**What happened**:

I observed some test failures with errors similar to the following:

```
2021-07-02 10:49:52 | Shoot container runtime testing
-- | --
  |   | 2021-07-02 10:49:52 | /src/test/integration/shoots/operations/containerruntime.go:30
  |   | 2021-07-02 10:49:52 | [DEFAULT] [SERIAL] [SHOOT] should add worker pool with containerd [It]
  |   | 2021-07-02 10:49:52 | /src/test/framework/gingko_utils.go:26
  |   | 2021-07-02 10:49:52 |  
  |   | 2021-07-02 10:49:52 | Unexpected error:
  |   | 2021-07-02 10:49:52 | <*errors.StatusError \| 0xc0012b88c0>: {
  |   | 2021-07-02 10:49:52 | ErrStatus: {
  |   | 2021-07-02 10:49:52 | TypeMeta: {Kind: "", APIVersion: ""},
  |   | 2021-07-02 10:49:52 | ListMeta: {
  |   | 2021-07-02 10:49:52 | SelfLink: "",
  |   | 2021-07-02 10:49:52 | ResourceVersion: "",
  |   | 2021-07-02 10:49:52 | Continue: "",
  |   | 2021-07-02 10:49:52 | RemainingItemCount: nil,
  |   | 2021-07-02 10:49:52 | },
  |   | 2021-07-02 10:49:52 | Status: "Failure",
  |   | 2021-07-02 10:49:52 | Message: "error dialing backend: proxy error from vpn-seed-server:9443 while dialing 10.250.0.7:10250, code 503: 503 Service Unavailable",
  |   | 2021-07-02 10:49:52 | Reason: "",
  |   | 2021-07-02 10:49:52 | Details: nil,
  |   | 2021-07-02 10:49:52 | Code: 500,
  |   | 2021-07-02 10:49:52 | },
  |   | 2021-07-02 10:49:52 | }
  |   | 2021-07-02 10:49:52 | error dialing backend: proxy error from vpn-seed-server:9443 while dialing 10.250.0.7:10250, code 503: 503 Service Unavailable
  |   | 2021-07-02 10:49:52 | occurred
  |   | 2021-07-02 10:49:52 |  
  |   | 2021-07-02 10:49:52 | /src/test/integration/shoots/operations/containerruntime.go:123
```

```
2021-07-02 10:39:48 | Operating system testing
-- | --
  |   | 2021-07-02 10:39:48 | /src/test/integration/shoots/operatingsystem/os.go:40
  |   | 2021-07-02 10:39:48 | OperatingSystem load
  |   | 2021-07-02 10:39:48 | /src/test/integration/shoots/operatingsystem/os.go:46
  |   | 2021-07-02 10:39:48 | [DEFAULT] [SERIAL] [SHOOT] should not segfault [It]
  |   | 2021-07-02 10:39:48 | /src/test/framework/gingko_utils.go:26
  |   | 2021-07-02 10:39:48 |  
  |   | 2021-07-02 10:39:48 | Unexpected error:
  |   | 2021-07-02 10:39:48 | <*errors.StatusError \| 0xc001696280>: {
  |   | 2021-07-02 10:39:48 | ErrStatus: {
  |   | 2021-07-02 10:39:48 | TypeMeta: {Kind: "", APIVersion: ""},
  |   | 2021-07-02 10:39:48 | ListMeta: {
  |   | 2021-07-02 10:39:48 | SelfLink: "",
  |   | 2021-07-02 10:39:48 | ResourceVersion: "",
  |   | 2021-07-02 10:39:48 | Continue: "",
  |   | 2021-07-02 10:39:48 | RemainingItemCount: nil,
  |   | 2021-07-02 10:39:48 | },
  |   | 2021-07-02 10:39:48 | Status: "Failure",
  |   | 2021-07-02 10:39:48 | Message: "error dialing backend: proxy error from vpn-seed-server:9443 while dialing 10.250.1.73:10250, code 503: 503 Service Unavailable",
  |   | 2021-07-02 10:39:48 | Reason: "",
  |   | 2021-07-02 10:39:48 | Details: nil,
  |   | 2021-07-02 10:39:48 | Code: 500,
  |   | 2021-07-02 10:39:48 | },
  |   | 2021-07-02 10:39:48 | }
  |   | 2021-07-02 10:39:48 | error dialing backend: proxy error from vpn-seed-server:9443 while dialing 10.250.1.73:10250, code 503: 503 Service Unavailable
  |   | 2021-07-02 10:39:48 | occurred
  |   | 2021-07-02 10:39:48 |  
  |   | 2021-07-02 10:39:48 | /src/test/integration/shoots/operatingsystem/os.go:79
```

It seems like, the tunnel connection is not quite stable and the `pods/exec` calls fail because the API server is not able to connect to the kubelet.

**What you expected to happen**:

The test not to fail and the tunnel connection to be stable.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: `v1.26.0-dev-27a7ec46a1c8724f7b2f1b1b709177eb4d22945a`
- Kubernetes version (use `kubectl version`): `v1.21.2`
- Cloud provider or hardware configuration: AWS, GCP
- Others:

**Comment by timebertt** [comment]
/cc @DockToFuture @ScheererJ

This might be related to https://github.com/gardener/gardener/issues/4303 but I don't have proof for it / can't do a proper RCA.

**Comment by ScheererJ** [comment]
@timebertt Was the issue reproducible for you or just randomly happening? Did you execute the tests separately or in a larger group? In the latter case which suite did you execute?

**Comment by vpnachev** [comment]
`k exec` and `k logs` to a cluster with ReversedVPN enabled was sporadically failing with same/similar error last days, but I have no chance to investigate what actually is causing it and some minutes later it was again up and running.

**Comment by timebertt** [comment]
> @timebertt Was the issue reproducible for you or just randomly happening? Did you execute the tests separately or in a larger group? In the latter case which suite did you execute?

I just observed some failures like the ones described here during regular test runs of the `shoot-default-serial-test-suite` on our internal development landscape (will send you a link in a private chat).
It was not happening consistently, but still in multiple test runs. So far I have no steps to reproduce, but I opened this issue to track such occurrences.

**Comment by timebertt** [comment]
I just encountered this with `kubectl logs`:

```
$ k -n extension-dns-external-tv6zq logs -f dns-controller-manager-7f454c47cc-wdq8f
Error from server: Get "https://10.240.0.102:10250/containerLogs/extension-dns-external-tv6zq/dns-controller-manager-7f454c47cc-wdq8f/dns-controller-manager?follow=true": proxy error from vpn-seed-server:9443 while dialing 10.240.0.102:10250, code 503: 503 Service Unavailable
```

I will send you some logs from `vpn-{seed-server,shoot}` and `envoy-proxy` via a private message.

**Comment by timebertt** [comment]
I encountered more test failures that seem related to this, predominantly the `Dashboard should be available` test step:

```
/src/test/integration/shoots/applications/shoot_app.go:56
  [DEFAULT] [RELEASE] [SHOOT] Dashboard should be available [It]
  /src/test/framework/gingko_utils.go:26

  Unexpected error:
      <*errors.fundamental | 0xc0001f40f0>: {
          msg: "http request should return 200 but returned 503 instead",
          stack: [0x1ee7fb0, 0x1ee7c6e, 0x1f51e58, 0x1ef2b34, 0x9f7ce3, 0x9f78fc, 0x9f6ec7, 0x9fb12f, 0x9fa7d2, 0xa217f1, 0xa21307, 0xa20af7, 0xa23206, 0xa2fcb8, 0xa2f9f6, 0x1f65afc, 0x52a20f, 0x474701],
      }
      http request should return 200 but returned 503 instead
  occurred

  /src/test/integration/shoots/applications/shoot_app.go:103
```

E.g. ref https://grafana.ingress.tm.core.shoot.live.k8s-hana.ondemand.com/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bcontainer%3D%5C%22main%5C%22,tm_testdef%3D%5C%22shoot-release-test-suite%5C%22,argo_workflow%3D%5C%22dev-manualscdw7-wf%5C%22%7D%22%7D,%7B%22mode%22:%22Logs%22%7D%5D

**Comment by ScheererJ** [comment]
#4362 probably fixed the most important (visible) part of this problem. It should give connections enough head room to wait for a reconnect of the vpn connection to happen. tcp retransmissions will take care of everything.

However, there are still some issues open, which will be tackled separately:
- All vpn connections of shoots of a seed are reset when a shoot is created/deleted (or the vpn envoyfilter of the shoot is changed). This can cause a lot of micro-outages in the vpn connection. However, they are only visible as few second long stalling of the operation. tcp retransmission do their magic again. (The reason for this is https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/draining.)
- Establishing the vpn connection takes longer than expected (around 5s), which adds to the pauses in the connection when a reset happens.

**Comment by timebertt** [comment]
Should we then reopen the issue for tracking these issues?

**Comment by ScheererJ** [comment]
> Should we then reopen the issue for tracking these issues?

No hard feelings either way. We can reopen this one or create two new ones.

**Comment by timebertt** [comment]
Ok, then please create new ticket(s) so these tasks can be tracked 👍 
If you want, you can open an ☂️-issue for graduating the `ReversedVPN` feature gate (similar to https://github.com/gardener/gardener/issues/2822 or https://github.com/gardener/gardener/issues/2942) and add all of the hickups we see in production to that. This will give a good overview over the state of the feature.

**Comment by ScheererJ** [comment]
Opened #4381 and #4382 to track further findings related to `ReversedVPN`.
