### ISSUE TITLE
Missing readinessProbes for vpn-seed-server

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4303]
**How to categorize this issue?**

/area networking
/kind enhancement

**What would you like to be added**:

The `vpn-seed-server` should have `readinessProbes` to properly signal pod readiness to the Deployment/Service controller.

**Why is this needed**:

`vpn-seed-server` is a critical component in the connection between `kube-apiserver` and shoot nodes (if the `ReversedVPN` feature gate is enabled), so we should make sure, that the Deployment controller only continues rollouts, when new Pods are indeed ready, and the Service controller only adds Endpoints for ready Pod to prevent the `kube-apiserver` from connecting to unready `vpn-seed-server` Pods.

**Comment by ScheererJ** [comment]
As the `vpn-seed-server` is a singleton, I guess this is not that relevant in terms of service routing. Nevertheless, it makes sense to add a readinessProbe. Therefore, we will work on it.

**Comment by timebertt** [comment]
Well, during rolling updates, there will still be multiple instances and we will want to make sure, that traffic is only routed to the healthy instance.
