### ISSUE TITLE
Allow usage of CNI with eBPF (Cilium, GKE Dataplane2) when using API SNI feature

### ISSUE THREAD

**Issue by christianhuening** [gardener/gardener#4309]
**How to categorize this issue?**

/area cost
/area networking
/area control-plane
/kind enhancement
/priority 2

**What would you like to be added**:
GKE made the DataplaneV2 based on Cilium and eBPF generally available starting with K8s 1.20.6-gke1000 (https://cloud.google.com/kubernetes-engine/docs/concepts/dataplane-v2). Upgrade from existing clusters to the new dataplane are not supported.

If a GKE cluster with DataplaneV2 is used together with the Gardener ApiServer SNI feature, the dependency of the istio sidecar apparently prevents communication from the base clusters Gardenlet with a control plane apiserver for a new shoot. 

AFAIK this was already mentioned in the initial proposal for the SNI feature: https://github.com/gardener/gardener/blob/master/docs/proposals/08-shoot-apiserver-via-sni.md#future-work 

the same is true when running ManagedSeeds or Shoots with the APIServerSNI feature

**Why is this needed**:
To allow usage of GKE clusters with the new Dataplane V2

**Comment by vpnachev** [comment]
cc @mvladev

**Comment by lotharbach** [comment]
I believe I'm hitting what is basically the same problem with a ManagedSeed/Shoot that is using extension-networking-cilium, and I guess anything with cilium would have this problem. Do you agree this is not specific to GKE and could rename this issue to make it clear that cilium/eBPF and API SNI currently can't work together?

**Comment by christianhuening** [comment]
@gesslein yes, i agree. I had found that later but forgot to update this ticket
