### ISSUE TITLE
AKS documentation contains AWS specifics and outdated

### ISSUE THREAD

**Issue by siredmar** [gardener/gardener#4329]
**How to categorize this issue?**

/area documentation
/kind bug
/priority 4

**What happened**:
I'm trying to setup gardener on a AKS cluster. However there are several issues with that documenatation (https://github.com/gardener/gardener/blob/master/docs/deployment/aks.md)
* outdated (`section Initialize Helm on the Cluster`) -> `init` command is removed from helm
* several AWS specific occurrences

**What you expected to happen**:
I'd expect a documentation that allows me to easily setup gardener on AKS.

**How to reproduce it (as minimally and precisely as possible)**:
Just look at the docs :)

**Anything else we need to know?**:
Excited to see gardener working once its setup.

**Comment by timebertt** [comment]
cc @Diaphteiros 
should we link garden-setup in this doc or remove it entirely in favor of garden-setup?
