### ISSUE TITLE
Expose logs of machine-controller-manager to end users

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4340]
**How to categorize this issue?**

/area logging
/kind enhancement
/kind discussion
/priority 3

**What would you like to be added**:
As far as I see currently the machine-controller-manager logs are not exposed to the end users. Exposing them to the end users can make sense.

**Why is this needed**:
In multiple cases we see that end users cannot complete RCA on their side because they don't have access to the MCM logs. We see that in such cases, the MCM logs actually can reveal the root cause. End users often ask questions like "Why Node `foo` was replaced?", "Why a new Node was not able to join the cluster during given period of time?", etc. If end users have access to the MCM logs, then they will be able to answer such type of questions on their own.
Currently we also expose cloud-controller-manager logs and logs from CSI components - they are also components that interact with the cloud provider APIs.

/cc @vpnachev @prashanth26 @Kristian-ZH @vlvasilev 

/cc @vlerenc I recall we were discussing this topic in the past. Any opinion from your side?

**Comment by vlerenc** [comment]
@ialidzhikov Indeed, it would be great to give the people access to the MCM and CA logs as they often raise questions like why a node was replaced or why scale-out/-in didn't happen, etc.

See also https://github.com/gardener/machine-controller-manager/issues/140.

So yes, ideally the Grafana dashboards should expose those logs (that we anyway have).

**Comment by prashanth26** [comment]
> @ialidzhikov Indeed, it would be great to give the people access to the MCM and CA logs as they often raise questions like why a node was replaced or why scale-out/-in didn't happen, etc.
> 
> See also [gardener/machine-controller-manager#140](https://github.com/gardener/machine-controller-manager/issues/140).
> 
> So yes, ideally the Grafana dashboards should expose those logs (that we anyway have).

I agree with this. I think CA logs are already exposed. However, yes exposing MCM logs also makes sense.

**Comment by Kristian-ZH** [comment]
Yes, CA logs are already exposed.
About the MCM: @vlvasilev can you please do this?

**Comment by Kristian-ZH** [comment]
I also suggest to add it only in `Controlplane Logs Dashboard` because the separated dashboards by container will be deleted soon.

**Comment by vlvasilev** [comment]
I will do it tomorrow

**Comment by vpnachev** [comment]
Almost all provider extensions are now exposing the MCM logs.
Once https://github.com/gardener/gardener/pull/4387 is also merged, we can close this issue.

**Comment by vpnachev** [comment]
This task is now completed and I am closing this issue as all required PRs are merged.
