### ISSUE TITLE
Use secret reference or cert-manager to provide certificates to the helmchart

### ISSUE THREAD

**Issue by fynluk** [gardener/gardener#4345]
**How to categorize this issue?**

/area ops-productivity
/area security
/kind enhancement
/priority 3

**What would you like to be added**:
We would like to add the possibility to install gardener via helmcharts without the use of inline certificates.
We have two approaches. The first one will use secret references instead of inline certificates, where we expect the secrets to already exist in the cluster. This could also be used with tools like [external-secrets](https://github.com/external-secrets/kubernetes-external-secrets).
The second approach will use [cert-manager](https://cert-manager.io/) to create a self-signed CA and new certificates. This approach is an advancement of the first approach, with a few additional cert-manager resources that create the right tls secrets at the right location.

**Why is this needed**:
To simplify deployment via helmcharts by decreasing the values.yaml and no inline certificates any longer.
A clear benefit of using the cert-manager would be the automatic renewal feature, but right now we do not test that.

**Current state/proposal**:
We started with the gardener-apiserver helmcharts and modify the values.yaml by adding some boolean variables to specify whether inline certificates (default values true and 'old' inline notation still works), a custom secret reference, or a new ca should be used.
In the template files we added many if-clauses to provide this feature.
We have an almost finished prototype which we will finalize and send as a PR if you/the community support the proposal.

**Comment by timebertt** [comment]
> The first one will use secret references instead of inline certificates, where we expect the secrets to already exist in the cluster.

Sounds good, this should also be sufficient to use something like cert-manager or external-secrets as well.
Feel free to assign yourself via `/assign` to this issue and open the PR.
