### ISSUE TITLE
kubeconfig rotation on deleting Shoot can deadlock the deletion

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4346]
**How to categorize this issue?**

/area quality
/kind bug
/priority 3

**What happened**:
In large landscapes we often have Shoots that fail to be deleted because of various reasons (user issues, transient errors, etc). Under some circumstances, kubeconfig rotation for Shoot in deletion can deadlock the Shoot deletion.

**What you expected to happen**:
kubeconfig rotation on deleting Shoot to do not deadlock the Shoot deletion. Or the kubeconfig rotation to be forbidden on Shoot in deletion.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a v1.19.x Shoot cluster

2. Add dummy finalizer for example to the `volumesnapshots.snapshot.storage.k8s.io` CRD to simulate issue that will cause the ControlPlane deletion to fail.

3. Delete the Shoot. Make sure that first the deletion will fail on the step `Waiting until shoot control plane has been destroyed`, then in the next tries it will fail on the step `Waiting until Shoot control plane has been reconciled`

4. Rotate the kubeconfig credentials while the deletion is failing on step `Waiting until Shoot control plane has been reconciled`

5. Restart the kube-apiserver Pods (to simulate eviction for example) and make sure the new kube-apiserver Pods cannot get ready

```
$ k -n shoot--foo--bar get po -l role=apiserver
NAME                              READY   STATUS             RESTARTS   AGE
kube-apiserver-674b556bfb-q4cdl   1/2     CrashLoopBackOff   6          11m

$ k -n shoot--foo--bar describe po kube-apiserver-674b556bfb-q4cdl
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Pulled     11m                   kubelet            Container image "eu.gcr.io/gardener-project/alpine-iptables:3.10.3" already present on machine
  Normal   Created    11m                   kubelet            Created container set-iptable-rules
  Normal   Started    11m                   kubelet            Started container set-iptable-rules
  Normal   Started    11m                   kubelet            Started container vpn-seed
  Normal   Created    11m                   kubelet            Created container vpn-seed
  Normal   Pulled     11m                   kubelet            Container image "eu.gcr.io/gardener-project/gardener/vpn-seed:0.19.0" already present on machine
  Normal   Killing    10m                   kubelet            Container kube-apiserver failed liveness probe, will be restarted
  Normal   Created    10m (x2 over 11m)     kubelet            Created container kube-apiserver
  Normal   Started    10m (x2 over 11m)     kubelet            Started container kube-apiserver
  Warning  Unhealthy  10m (x4 over 11m)     kubelet            Liveness probe failed: HTTP probe failed with statuscode: 401
  Warning  Unhealthy  9m59s (x8 over 11m)   kubelet            Readiness probe failed: HTTP probe failed with statuscode: 401
  Normal   Pulled     6m31s (x6 over 11m)   kubelet            Container image "k8s.gcr.io/kube-apiserver:v1.19.12" already present on machine
  Warning  BackOff    86s (x17 over 5m31s)  kubelet            Back-off restarting failed container
```

6. Remove the dummy finalizer from the `volumesnapshots.snapshot.storage.k8s.io` CRD and make sure that the deletion still fails because the apiserver is now unavailable

Basically the `static-token` Secret in the Seed is updated with the new token, while the probes in kube-apiserver Deployment spec still refer to the old Bearer token -> liveness and readiness probes fail with 401 (the token for the probes can be only updated with the `Deploying Kubernetes API server` step).
The deadlock is that step `Waiting until Shoot control plane has been reconciled` (when the ControlPlane is in deletion) relies on the apiserver to be available for clean up of resources. On the other side gardenlet can never proceed to the `Deploying Kubernetes API server` step as it depends on the `Waiting until Shoot control plane has been reconciled` step.

**Environment**:

- Gardener version: v1.27.0-dev-c1841f54d8a9aa35d9567cec1b504b7564afabee
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
@gardener/gardener-maintainers wdty about forbidding kubeconfig rotation on Shoot in deletion? I guess such operation on Shoot in deletion does not make sense in general and can only interfere with the deletion flow.

**Comment by vpnachev** [comment]
Makes sense. 
Should we explicitly forbid it via validation on update request or it is enough the controller simply to skip this operation?
I lean toward the silently skipping the rotation.

**Comment by ialidzhikov** [comment]
I think it's better to have a validation that rejects the update. If we have backwards compatibility concerns, then we can have a feature gate for it, hence we can allow gardener operators to enable it in controlled manner.
