### ISSUE TITLE
☂️ CIS Benchmark compliance

### ISSUE THREAD

**Issue by majst01** [gardener/gardener#4361]
**How to categorize this issue?**

  /area control-plane
  /area certification
  /area security
  /kind discussion
  /priority 4

More and more customers require formal verification of security related aspects of the produced clusters. One approach is to run a well known and established tool to identify potential security related weaknesses and report the results.

We have choose [kube-bench](https://github.com/aquasecurity/kube-bench) to check the compliance against the  [CIS Benchmark](https://www.cisecurity.org/benchmark/kubernetes/). We where running `kube-bench` against a k8s cluster v1.20.x, created with gardener v1.18.x. 

This identified the following 3 findings:

`[FAIL] 1.2.6 Ensure that the --kubelet-certificate-authority argument is set as appropriate`

> Result: Argument is not set
>
> CIS recommendation: ... connections [from the apiserver to the kubelet] terminate at the
> kubelet’s HTTPS endpoint. By default, the apiserver does not verify the kubelet’s serving
> certificate, which makes the connection subject to man-in-the-middle attacks, and unsafe to
> run over untrusted and/or public networks.
>
> Reasoning: Connections between the apiserver and the kubelet are protected by the VPN tunnel.
> Thus thes connections do not run directly over public networks. However configuring a
> certificate-authority would increase security.

`[WARN] 1.2.10 Ensure that the admission control plugin EventRateLimit is set`

> Result: Plugin is not set
>
> CIS recommendation: Using EventRateLimit admission control enforces a limit on the number
> of events that the API Server will accept in a given time slice. A misbehaving workload
> could overwhelm and DoS the API Server, making it unavailable. [...] You need to carefully
> tune in limits as per your environment.
>
> Reasoning: Tuning this Limit as per environment probably isn't possible, however setting some
> (high) default would minimize the riscs and would make auditors happy.

`[WARN] 5.1.6 Ensure that Service Account Tokens are only mounted where necessary`

> Result: Service Account Tokens are mounted in many pods.
>
> CIS recommendation: Mounting service account tokens inside pods can provide an avenue for
> privilege escalation attacks where an attacker is able to compromise a single pod in the
> cluster. Avoiding mounting these tokens [...]
>
> Reasoning: `automountServiceAccountToken: false` should be set wherever possible to avoid
> that pods get a service account token mounted in them.

We would like to address these findings in cooperation with the gardener community. We then would create individual Issues/PR per finding.
As a long term goal we can imagine to run these benchmarks automated on a regular basis.

**Comment by timebertt** [comment]
cc @ThormaehlenFred @dguendisch @vlerenc

**Comment by rfranzke** [comment]
The last part ("[WARN] 5.1.6 Ensure that Service Account Tokens are only mounted where necessary") should have been addressed with #5099 and #5128.
