### ISSUE TITLE
Establishing the `ReversedVPN` connection takes longer than expected

### ISSUE THREAD

**Issue by ScheererJ** [gardener/gardener#4382]
**How to categorize this issue?**

/area networking
/kind bug
/priority 3

**What happened**:
Establishing the vpn connection between `vpn-seed-server` and `vpn-shoot` takes around 4-5s on usual landscapes. This is longer than expected.
```
Fri Jul 16 12:22:59 2021 TCP connection established with [AF_INET]10.243.130.40:40706
Fri Jul 16 12:23:01 2021 10.243.130.40:40706 peer info: IV_VER=2.4.7
Fri Jul 16 12:23:01 2021 10.243.130.40:40706 peer info: IV_PLAT=linux
Fri Jul 16 12:23:01 2021 10.243.130.40:40706 peer info: IV_PROTO=2
Fri Jul 16 12:23:01 2021 10.243.130.40:40706 peer info: IV_NCP=2
Fri Jul 16 12:23:01 2021 10.243.130.40:40706 peer info: IV_LZ4=1
Fri Jul 16 12:23:01 2021 10.243.130.40:40706 peer info: IV_LZ4v2=1
Fri Jul 16 12:23:01 2021 10.243.130.40:40706 peer info: IV_LZO=1
Fri Jul 16 12:23:01 2021 10.243.130.40:40706 peer info: IV_COMP_STUB=1
Fri Jul 16 12:23:01 2021 10.243.130.40:40706 peer info: IV_COMP_STUBv2=1
Fri Jul 16 12:23:01 2021 10.243.130.40:40706 peer info: IV_TCPNL=1
Fri Jul 16 12:23:01 2021 10.243.130.40:40706 [vpn-shoot-client] Peer Connection Initiated with [AF_INET]10.243.130.40:40706
Fri Jul 16 12:23:01 2021 vpn-shoot-client/10.243.130.40:40706 MULTI_sva: pool returned IPv4=192.168.123.6, IPv6=(Not enabled)
```

```
Fri Jul 16 12:22:58 2021 OpenVPN 2.4.7 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  5 2019
Fri Jul 16 12:22:58 2021 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Fri Jul 16 12:22:58 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]52.211.31.126:8132
Fri Jul 16 12:22:58 2021 Attempting to establish TCP connection with [AF_INET]52.211.31.126:8132 [nonblock]
Fri Jul 16 12:22:59 2021 TCP connection established with [AF_INET]52.211.31.126:8132
Fri Jul 16 12:23:01 2021 TCP_CLIENT link local: (not bound)
Fri Jul 16 12:23:01 2021 TCP_CLIENT link remote: [AF_INET]52.211.31.126:8132
Fri Jul 16 12:23:01 2021 [vpn-seed-server] Peer Connection Initiated with [AF_INET]52.211.31.126:8132
Fri Jul 16 12:23:02 2021 TUN/TAP device tun0 opened
Fri Jul 16 12:23:02 2021 /sbin/ip link set dev tun0 up mtu 1500
Fri Jul 16 12:23:02 2021 /sbin/ip addr add dev tun0 local 192.168.123.6 peer 192.168.123.5
Fri Jul 16 12:23:02 2021 Initialization Sequence Completed
```
**What you expected to happen**:
The connection should be established in a second or maybe up to 3 seconds.

**How to reproduce it (as minimally and precisely as possible)**:
Just look into the logs of `vpn-seed-server` or `vpn-shoot`.

**Anything else we need to know?**:
Unfortunately, there seems to be some strange code in the proxy server handling of open vpn that simply causes the client to wait for 2s:
https://github.com/OpenVPN/openvpn/blob/7029cece844d9324aff687981b8b6c33b099db2d/src/openvpn/proxy.c#L1066

**Environment**:

- Gardener version: v1.28-dev
- Kubernetes version (use `kubectl version`): v1.20.8

**Comment by ScheererJ** [comment]
Due to #4362 this issue is less relevant as the overall connection will continue to exist for established connections and new connections have a bigger buffer until an error is reported back.

**Comment by vlerenc** [comment]
@mvladev Could you please update this ticket?

Also, @marwinski opened https://github.com/gardener/vpn2/issues/4 which seems to describe the same problems as https://github.com/gardener/gardener/issues/4381 and https://github.com/gardener/gardener/issues/4382 opened by @ScheererJ . Which ones do we keep?

**Comment by ScheererJ** [comment]
Interestingly, #4434 seems to improve the connect time reducing it by about 2s to around 3s.

**Comment by rfranzke** [comment]
@ScheererJ @DockToFuture Is this issue/ticket still relevant/up-to-date?

**Comment by ScheererJ** [comment]
The connection time of around 3s seems long, but does not seem to cause problems anymore as the connections are fairly stable, i.e. initial connection establishment is not as fast as we would like it to be, but it is good enough.
