### ISSUE TITLE
Gardenlet fails to start if extension CRDs are not already present in the seed cluster.

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#4399]
**How to categorize this issue?**

/area usability
/kind regression
/priority 1

**What happened**:
 Trying to start `gardenlet` for a brand new seed fails with:
 ```
time="2021-07-20T14:23:41Z" level=error msg="failed to run gardenlet controllers: failed initializing extensions controller: no matches for kind \"Extension\" in version \"extensions.gardener.cloud/v1alpha1\""
 ```
 
**What you expected to happen**:
`gardenlet` to start properly and the seed to be bootstrapped.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the guidelines in the [local setup guide](https://github.com/gardener/gardener/blob/master/docs/development/local_setup.md) and try to register a new seed, then start `gardenlet` for that seed (`SEED_NAME=<new-seed> make start-gardenlet`)
Alternatively, delete the CRDs from an existing seed cluster and try to start `gardenlet`

Managed seeds currently cannot be created for the same reason and the `gardenlet` will be stuck in a CrashLoopBackOff

**Anything else we need to know?**:
This seems to be caused by the removal of the federated seed controller. Previously [these controllers](https://github.com/gardener/gardener/blob/f7174cd44959967ab15b470ae20512ff6cd19412/pkg/gardenlet/controller/extensions/extensions.go#L57-L67) were started dynamically only after a seed has been bootstrapped. Now they are started immediately when `gardenlet` starts, however they depend on the extension CRDs being present in the cluster. This creates a deadlock since the bootstrap functionality never gets called.

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timuthy** [comment]
@xrstf do you have capacity to work on a fix?
