### ISSUE TITLE
Stale project controller does not detect project usage

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#4417]
**How to categorize this issue?**

/kind bug
/area ops-productivity robustness usability
/priority 3

**What happened**:
The stale project controller is  reconciling the project resource on pre-defined period of time. The default sync period is 12 hours and during this long time a user can create and delete a shoot cluster, the controller will not see it and will still consider the project as stale 

**What you expected to happen**:
Each usage of project to be counted when considering it as stale.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
This can be mitigated by using much shorter sync periods, e.g. 5 to 15m as the shoot creation and deletion usually requires 10+ minutes.

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
> This can be mitigated by using much shorter sync periods, e.g. 5 to 15m as the shoot creation and deletion usually requires 10+ minutes.

Probably the better alternative is to just watch the resources, that the project stale controller cares about, i.e., Shoot, SecretBinding, etc. in the project namespace and then equeue the project.
This is closer to how k8s controllers should usually work.

**Comment by vpnachev** [comment]
Sure, this what I mean with 

>  Each usage of project to be counted when considering it as stale.

without going into implementation detail. Shorter sync periods is just mitigation, not a real fix.

**Comment by rfranzke** [comment]
Is this fixed with #4447?

**Comment by vpnachev** [comment]
AFAIK, from the resources listed in https://github.com/gardener/gardener/blob/master/docs/concepts/controller-manager.md#stale-projects-reconciler, only shoot resources are actively watched, so I would say this issue is partially implemented.

**Comment by rfranzke** [comment]
Probably also related to #4251
