### ISSUE TITLE
gardenlet cannot bootstrap new Seed cluster when VPA setting is enabled and ManagedIstio=true

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4419]
**How to categorize this issue?**

/kind bug
/priority 3

**What happened**:
Currently there is kind of deadlock in seed bootstrap - istiod component has a VPA and on seed bootstrap istiod component is applied before the whole seed-boostrap chart. But the seed-bootstrap chart is the piece that contains the VPA CRD. So istiod component fails to deploy as the CRD is missing.

**What you expected to happen**:
Successful seed bootstrap.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Seed with VPA enabled

```yaml
spec:
  settings:
    verticalPodAutoscaler:
      enabled: true
```

2. Start gardenlet with ManagedIstio feature gate enabled

3. Make sure that seed bootstrap is in deadlock with:

```
$ make start-gardenlet SEED_NAME=foo

time="2021-07-22T17:30:05+03:00" level=error msg="Seed bootstrapping failed: failed to apply manifests: 1 error occurred: could not apply object of kind \"VerticalPodAutoscaler\" \"istio-system/istiod\": no matches for kind \"VerticalPodAutoscaler\" in version \"autoscaling.k8s.io/v1beta2\"" seed=foo

time="2021-07-22T17:30:25+03:00" level=error msg="Seed bootstrapping failed: failed to apply manifests: 1 error occurred: could not apply object of kind \"VerticalPodAutoscaler\" \"istio-system/istiod\": no matches for kind \"VerticalPodAutoscaler\" in version \"autoscaling.k8s.io/v1beta2\"" seed=foo

time="2021-07-22T17:30:45+03:00" level=error msg="Seed bootstrapping failed: failed to apply manifests: 1 error occurred: could not apply object of kind \"VerticalPodAutoscaler\" \"istio-system/istiod\": no matches for kind \"VerticalPodAutoscaler\" in version \"autoscaling.k8s.io/v1beta2\"" seed=foo

time="2021-07-22T17:31:05+03:00" level=error msg="Seed bootstrapping failed: failed to apply manifests: 1 error occurred: could not apply object of kind \"VerticalPodAutoscaler\" \"istio-system/istiod\": no matches for kind \"VerticalPodAutoscaler\" in version \"autoscaling.k8s.io/v1beta2\"" seed=foo
```

**Environment**:

- Gardener version: v1.27.x
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by vpnachev** [comment]
Just one detail toward how to reproduce it, the cluster backing the seed must not be installed with VPA via other means (if it is a shoot cluster, `spec.kubernetes.verticalPodAutoscaler.enabled` must be `false`)
