### ISSUE TITLE
Configure separate disk for /var/lib/kubelet for worker nodes

### ISSUE THREAD

**Issue by mkska** [gardener/gardener#4424]
**How to categorize this issue?**
/area os
/area storage
/kind enhancement
/priority 3

**What would you like to be added**:
At the moment, only the WHOLE `/var/lib` can be assigned to additional disks using for worker nodes:
https://github.com/gardener/gardener/blob/a6eda4d63195f9373c1c17055f1b18d3f962bfb9/example/90-shoot.yaml#L50-L55

This configuration description:
<html>
<body>

kubeletDataVolumeName | (Optional)KubeletDataVolumeName contains the name of a dataVolume that should be used for storing kubelet state.
-- | --

</body>
</html>

The problem is that the OS and services (e.g. docker) would still create their own folder structure and use `/var/lib`.
And by this, there is no clear separation of the storage of `kubelet` working folder from others as the description indicates.

In my opinion, with the setting of `kubeletDataVolumeName` the point would be to:
_Only the `/var/lib/kubelet` is mounted to different disk, and not the whole `/var/lib`._
I'd like to add an option to mount the additional disk to `/var/lib/kubelet` only.

**Proof**
```
# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0   50G  0 disk               <======= OS FS
|-sda1   8:1    0    1M  0 part 
|-sda2   8:2    0   16M  0 part /boot/efi
|-sda3   8:3    0    1G  0 part /usr
`-sda4   8:4    0   49G  0 part /
sdb      8:16   0   25G  0 disk /var/lib      <======= Additional disk
sdc      8:32   0  128G  0 disk 
`-sdc1   8:33   0  128G  0 part /mnt/resource
sr0     11:0    1  652K  0 rom  

```

These folder will be located on the additional disk besides the kubelet folder
```
/var/lib# ls -1
apt
calico
cloud-config-downloader
cni
dbus
dictionaries-common
docker
dockershim
dpkg
dracut
gardener-user
gardener-user-ssh.key
grub
kube-proxy
kubelet           <==== not separated on different storage
logrotate
lost+found
misc
nfs
pam
polkit-1
private
python
quota
sudo
systemd
ucf
vim
waagent
```

**Why is this needed**:
I believe that the point of  `kubeletDataVolumeName` is to separate kubelet workdir from OS filesystem. Even if it is configured;
once kubernetes workload impacts the storage behind the `/var/lib/kubelet` on a give host, it could effect the whole host and system since the OS is still using the very same disk for different services (through `/var/lib`).

**Comment by vpnachev** [comment]
Have you tried pure containerd+runc without docker?
It seems containerd is using `/run/containerd/` in contrast to docker which is using `/var/lib/docker` and docker will be soon removed as part of #4110.

**Comment by mkska** [comment]
Hi @vpnachev,

Problem still exists with containerd CRI.
Containerd is storing the data/state under `/var/lib/containerd`.

Even if the API reference/documentation mention that the `kubeletDataVolumeName` the kubelet folder storage device is specified - the whole /var/lib is moved to the other storage device.

Mounting path should be `/var/lib/kubelet` instead of `/var/lib`:
https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/extensions/operatingsystemconfig/executor/templates/scripts/execute-cloud-config.tpl.sh#L47-L58

Is it possible to make such a change, or create an extension, so really the 'kubelet' folder would end up on a different storage device?

Thanks,
mkska

**Comment by oliver-goetz** [comment]
This issue looks legit.
When `gardener-node-agent` is active the nodes cannot join the cluster on worker groups where `kubeletDataVolumeName` is set. GNA stores files in `/var/lib/gardener-node-agent` and it might not like if there is suddenly a new disk. 

/reopen
/remove-lifecycle rotten
/assign
