### ISSUE TITLE
Failed to bootstrap seeds running Kubernetes 1.15

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#4427]
**How to categorize this issue?**

/area quality
/kind regression
/priority 3

**What happened**:
After registering a seed cluster which runs Kubernetes `1.15` the following bootstrap error occur:

```
time="2021-07-23T14:28:07+02:00" level=error msg="Seed bootstrapping failed: failed to apply manifests: 2 errors occurred: [could not apply object of kind \"CustomResourceDefinition\" \"default/dnsrecords.extensions.gardener.cloud\": no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1\"
```

**What you expected to happen**:
The seed cluster to be bootstrapped successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Register a Kubernetes cluster running 1.15 as a seed.

**Anything else we need to know?**:
~I created https://github.com/gardener/gardener/pull/4426 for the main branch. But we should decide how to deal with this issue for release `v1.27`. It seems inappropriate to raise the min seed version through a patch version, IMO, but opinions are welcome (/cc @stoyanr, @ialidzhikov).~

**Environment**:

- Gardener version: v1.27
- Kubernetes version (use `kubectl version`): 1.15

**Comment by ialidzhikov** [comment]
We can simply switch to apiextensions.k8s.io/v1beta1 apiVersion (as all other similar CRDs) without touching the the min required Seed version, right? I am not sure why you couple this with changing the min required Seed version..

**Comment by timuthy** [comment]
> I am not sure why you couple this with changing the min required Seed version..

`admissionregistration.k8s.io/v1beta1` will be removed with Kubernetes 1.22 ([ref](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes)), so we anyway need to get rid or want to get rid of the `v1beta1` version.
But we can easily use `admissionregistration.k8s.io/v1beta1` for Gardener `v1.27` to fix this. WDYT?

**Comment by ialidzhikov** [comment]
> But we can easily use admissionregistration.k8s.io/v1beta1 for Gardener v1.27 to fix this. WDYT?

Yep, I would vote to go that way for master and affected release branch for now.
