### ISSUE TITLE
Garbage collect cloud-config secrets in the kube-system namespace of shoot clusters

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#4433]
**How to categorize this issue?**

/area quality os ops-productivity
/kind enhancement
/priority 3

**What would you like to be added**:
For each worker pool of a shoot clusters a `cloud-config-<pool-name>-<hash>` secret is maintained in the shoot cluster.
This secrets are containing a script that is downloaded on each node of the pool end executed as part of the node bootstrap and node in-place update activities. The secrets lifecycle is managed via the `shoot-cloud-config-execution` managed resource.

If for whatever reason a similar secret is created in the shoot cluster by external agent, it should be deleted by the Gardenlet or GRM. 

**Why is this needed**:
To not let duplicated or leaked cloud-config secrets. When operating such cluster, it would be easier to find the actual secret used by the nodes.

**Comment by timuthy** [comment]
> If for whatever reason a similar secret is created in the shoot cluster by external agent, it should be deleted by the Gardenlet or GRM.

Can you elaborate what you mean by "a similar secret"? Are you suggesting to delete any secret that has a  `cloud-config-` prefix but is not used by the node?

**Comment by vpnachev** [comment]
It depends to the clients and how they find these secrets. And yes, the prefix is one option. Other one is label selector https://github.com/gardener/gardener/blob/0f094f27d0f3b538b15414a28e1de60c4d3f4444/pkg/operation/botanist/worker.go#L88-L110.

**Comment by rfranzke** [comment]
IIUC, in a recent discussion we decided to not pursue this for now. Should we close it?

**Comment by vpnachev** [comment]
If it will not be fixed at all, then close it. But if you plan to have it fixed sometime in the future, then it is better to keep it open but with lower priority.
