### ISSUE TITLE
Node health check can be compromised by faulty cloud-config checksum secrets existing in the shoot

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#4436]
**How to categorize this issue?**

/area quality os ops-productivity
/kind bug
/priority 3

**What happened**:
In the kube-system namespace of the shoot clusters external agents can create cloud-config secrets with wrong data that breaks the nodes health checks by injecting faulty checksum.

Here https://github.com/gardener/gardener/blob/0f094f27d0f3b538b15414a28e1de60c4d3f4444/pkg/operation/botanist/worker.go#L88-L110 the cloud-config secret for a worker pool can be duplicated. If it is later in the list, it can easily overwrite the desired checksum. But the agent on the node is working with correct secret and apply the real desired checksum. Later, the node health check finds that these checksum differ and reports the node as unhealthy.

**What you expected to happen**:
The node health check to properly detect that a cloud-config secret is duplicated instead of overwriting the desired checksum or the checksum to be retrieved exactly from the cloud-config secret dedicated for the particular worker pool instead of finding it in the shoot cluster.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a shoot cluster with worker pool `pool-1`.
2. List the cloud-config secrets in the kube-system namespace
```bash
k -n kube-system get secrets  -l worker.gardener.cloud/pool -L worker.gardener.cloud/pool
NAME                        TYPE     DATA   AGE   POOL
cloud-config-pool-1-c8518   Opaque   1      19m   pool-1
```
3. Create another secret with labels `gardener.cloud/role: cloud-config` and `worker.gardener.cloud/pool: pool-1`. Just make sure the name of this secret is lexicographically later in the list, e.g. `dcloud-config-pool-1-c8518`. A command like
```bash
k -n kube-system get secrets cloud-config-pool-1-c8518 -o json | jq '.metadata.name="dcloud-config-pool-1-c8518"'  | k -n kube-system create -f -
```
can be used to achieve this.
4. Wait node health check to be executed (usually 30 seconds) and make sure the Node condition is healthy.
5. Amend the `checksum/data-script` annotations for the newly created secret to something different, for example
```bash
k -n kube-system annotate secrets --overwrite dcloud-config-pool-1-c8518 checksum/data-script="abc"
```
6. Wait again the health checks to be executed.
7. Verify that the nodes of the `pool-1` pool are reported with outdated cloud-config checksum as the desired checksum is `abc`.
```bash
$ k get shoots foo -o jsonpath='{@.status.conditions[?(@.type == "EveryNodeReady")].message}'
2 errors occurred:
        * the last successfully applied cloud config on node "ip-10-222-15-248.eu-west-1.compute.internal" is outdated (current: e9c4642830abf5da01dc8b69d749df470e23fb2666efa9708c73acc043646d67, desired: abc)
        * the last successfully applied cloud config on node "ip-10-222-28-159.eu-west-1.compute.internal" is outdated (current: e9c4642830abf5da01dc8b69d749df470e23fb2666efa9708c73acc043646d67, desired: abc)
```

To recover the shoot back to healthy state, it is enough just to delete the duplicated secret
```bash
$ k -n kube-system delete secrets dcloud-config-pool-1-c8518
```
and wait again some seconds for the health check controller to reconcile 
```bash
$ k get shoots foo -o jsonpath='{@.status.conditions[?(@.type == "EveryNodeReady")].message}'
All nodes are ready.
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
IIUC, in a recent discussion we decided to not pursue this for now. Should we close it?

**Comment by vpnachev** [comment]
If it will not be fixed at all, then close it. But if you plan to have it fixed sometime in the future, then it is better to keep it open but with lower priority.
