### ISSUE TITLE
Introduce Shoot identity for authentication to external systems

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#4450]
**How to categorize this issue?**

/area security
/kind api-change
/kind enhancement
/priority 3

**What would you like to be added**:

New field in the `Shoot` specification called `serviceAccountName` that would be used to associate a `Shoot` cluster with`ServiceAccount` in the Garden cluster. Said `ServiceAccount`'s Token would be used to authenticate to external systems.

**Why is this needed**:

Today, when Gardener would like to talk to external systems (Cloud Providers API, DNSasS API, etc...) in most cases the following steps must happen:

1. end-user has to create an identity entity (user/service account/secret) in said system
1. grant said entity the ability to perform some operation in the system (e.g. create a role that allows List all Virtual Machines in a Cloud Provider and bind this role to the entity)
1. store those secrets / credentials in the Gardener cluster
1. Gardener would then copy those secrets to the Seed cluster and use them in various controllers / components that talk to said identities

There are multiple challenges with this approach:

1. The end-user has to manually rotate those credentials (create new password / secret for said entity, replace the existing on in the Gardener cluster and trigger reconciliation)
1. Said credentials are stored somewhere else (needs extra care about security, proper storage).

More and more external systems support OpenID Connect Identity Federation (e.g. [aws](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html) or [google](https://cloud.google.com/iam/docs/access-resources-oidc)). This allows for those systems to trust the Gardener cluster as Identity Provider removing the need to store credentials issued by them in the Gardener cluster. WIth this change the above flow would be changed to:

1. create `ServiceAccount` in the Gardener cluster (or can use the `default` one) 
1. configure OpenID Connect Identity Federation in said system, pointing to the Gardener cluster's OpenID Connect Discovery document (to add the address specified in the `kube-apiserver`'s `--oidc-issuer-url` flag)
1. Map claims in ServiceAccount Tokens issued by the Gardener cluster to roles in the system (e.g. allow claim `sub` in the `id_token` with value `system:serviceaccount:garden-identity-federation:aws` to assume role `vm-reader`)
1. set `spec.serviceAccountName`  pointing to  the `ServiceAccount` (e.g `aws` - the subject from above) in the `Shoot`
1. Controllers in the Seed cluster can issue those tokens and use them to authenticate to said systems.

Example for AWS:

1. [Create](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html) OpenID Connect Identity Provider pointing to the Gardener cluster `https://gardener.foo.bar`
1. Create a role that Grants some permissions and configure the trust policy of said role:

    ```json
    {
    "Version": "2012-10-17",
    "Statement": [
        {
        "Effect": "Allow",
        "Principal": {
            "Federated": "arn:aws:iam::12344567:oidc-provider/gardener.foo.bar"
        },
        "Action": "sts:AssumeRoleWithWebIdentity",
        "Condition": {
            "StringEquals": {
            "gardener.foo.bar:aud": "aws-sts",
            "gardener.foo.bar:sub": "system:serviceaccount:garden-identity-federation:aws"
            }
        }
        }
    ]
    }
    ```

1. Gardener controllers can now use the `TokenRequest` of `ServiceAccount` to issue token:

    ```yaml
    apiVersion: authentication.k8s.io/v1
    kind: TokenRequest
    metadata:
      name: token
      namespace: garden-identity-federation
    spec:
      audiences: ["aws-sts"]
      expirationSeconds: 1200
    ```
   
   and use said token to assume the role created in 2. and exchange the `id_token` for AWS-STS-issued token

**Comment by mvladev** [comment]
Also in this case - the information which `AWS` role to assume, is `AWS`-specific and should be put in the configuration for that specific extension.

**Comment by rfranzke** [comment]
@vpnachev @dimityrmirchev Is this still something you plan to do when you have time/capacity?

**Comment by dimityrmirchev** [comment]
No, this will not be implemented for the time being so I guess we can close the issue. Maybe @donistz can share a bit more info about an alternative solution.

**Comment by rfranzke** [comment]
OK, thanks for clarification. I saw there is parallel work going on in the provider extensions allowing end-users to drop their cloud provider credentials entirely while using those "centrally-managed" credentials provided by Gardener operators:

- https://github.com/gardener/gardener-extension-provider-azure/pull/401
- https://github.com/gardener/gardener-extension-provider-gcp/pull/365

> This eliminates the need for users to bring their own service account.
The service account can be managed by the Gardener operator in a different project in the same GCP organisation.
Users just need to assign the managed service account to their own project with proper permissions.
This gives the operator also the ability to rotate credentials in centralised way.

It seems that such work achieves the same goals originally described in this issue. Probably @dkistner or @kon-angelo can comment on this.

**Comment by donistz** [comment]
The alternative solution for the Gardener service authentication to consumer IaaS accounts/subaccounts/projects is called "central service account". It will be implemented in the IaaS extensions as an alternative to the static service account credential configured by the Gardener service consumers. Here are some details:
GCP : https://github.com/gardener/gardener-extension-provider-gcp/issues/362
OpenStack: https://github.com/gardener/gardener-extension-provider-openstack/issues/357
Azure: https://github.com/gardener/gardener-extension-provider-azure/issues/383
The alternative solution is also preventing the problem where the issuer and the consumer of an authentication token are operated by one and the same entity(organization).
