### ISSUE TITLE
Fetching clusters programatically

### ISSUE THREAD

**Issue by tareksha** [gardener/gardener#447]
Hi,

I have a gardener running and managing my cluster. I am trying to write automation tools that configure kubernetes/helm clients automatically from scratch. The tools should authenticate with the gardener and fetch the kubernetes configuration file of the relevant cluster automatically.

Is there a documented REST API in gardener that I can use for fetching information about the clusters?

thank you

**Comment by rfranzke** [comment]
Hi,

Gardener itself has no REST API for fetching the kubeconfig of a shoot, but it uses the hosting Kubernetes cluster to store it as a secret.

For a shoot named `my-cluster` running in namespace `garden-my-project` you can fetch the kubeconfig by doing

```bash
$ kubectl -n garden-my-project get secret my-cluster.kubeconfig -o jsonpath={.data.kubeconfig}
```

Does this answer your question?

**Comment by tareksha** [comment]
hi @rfranzke 
this does not solve my problem because it actually requires the .kube/config that we are trying to fetch..
thanks

**Comment by rfranzke** [comment]
Hm, then I did not understand what you are trying to do. Can you explain again? You run Gardener in cluster A and have a shoot cluster B? If you want to fetch the kubeconfig for B then my answer above is what you need, but obviously you're trying something else?!

**Comment by tareksha** [comment]
I have a completely clean environment without any session data. I want to log-in to gardener programmatically (maybe obtain the JWT that is used by the API ? ) and fetch the kubeconfig file for some cluster. Is this possible ?

**Comment by rfranzke** [comment]
What do you mean by "log-in to Gardener programmatically"? Are you talking about the [Gardener dashboard](https://github.com/gardener/dashboard)? If so, kindly raise the question at this repo: https://github.com/gardener/dashboard.

**Comment by tareksha** [comment]
opened it
https://github.com/gardener/dashboard/issues/222
thank you @rfranzke

**Comment by rfranzke** [comment]
OK, thanks!!! Will close this one then. Have a great day!
