### ISSUE TITLE
Cannot create shoot cluster

### ISSUE THREAD

**Issue by dat1041988** [gardener/gardener#4474]
Create shoot cluster failed with following error (attached file).
Need some help!

Thanks!

Env:
Opentack
Garden-setup 3.12.0
Garden k8s cluster: 1.20.7

[gardener-resource-manager-log.txt](https://github.com/gardener/gardener/files/6935514/gardener-resource-manager-log.txt)

**Comment by timuthy** [comment]
The following entry hints towards a network issue in your seed cluster. Can you please check?

```
{"level":"info","ts":"2021-08-04T14:19:42.560Z","logger":"controller-runtime.manager.resource-controller","msg":"could not get rest mapping for ClusterRoleBinding '/metrics-server:system:auth-delegator': Get \"https://kube-apiserver/api?timeout=32s\": dial tcp: i/o timeout"
```

@Diaphteiros have you seen this issue with the mentioned Garden-Setup version before?

**Comment by dat1041988** [comment]
I don't create addition seed cluster, using garden base cluster as seed cluster. In base cluster, i don't see a network issue. I checked network by ping & nslookup svc, it's ok.

In Garden namespace, gardener-seed-admission-controller always refresh (Kill & Create new one, seem like VPA apply new resource, is that normal?)

![image](https://user-images.githubusercontent.com/42293819/128309386-99b05caf-f7c2-43b9-92b6-eaee83fa0442.png)
