### ISSUE TITLE
Copy charts to a temporay dir on gardenlet start

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#448]
The `charts` folder is read in runtime by the garden controller manager. For local development, this can lead to situations when the controller is started on branch `X` then developer switches to branch`Y` leading to unexpected behavior https://github.com/gardener/gardener/pull/363#issuecomment-429657753: 

> The problem might be with reading in runtime of the charts folder. I often switch branches - I probably ran controller with my local _versions branch and switched to some other branch - the charts dir was checkout-ed and It rendered correctly.
As a workaround and to ensure stability and reliability, when the controller is started, we might want to copy the entire charts folder in a temporary dir and read charts from it.

**Comment by rfranzke** [comment]
WDYT about https://github.com/kevinburke/go-bindata?

**Comment by mvladev** [comment]
That's a better solution indeed.

**Comment by msohn** [comment]
You may consider to use

`git --work-tree=/path/to/outputdir checkout HEAD -- subdirname`

in order to let git create a consistent copy of a committed version of a subdirectory in another directory. With this approach git will eliminate potential race conditions while copying the chart

**Comment by rfranzke** [comment]
In gardener/gardener-extensions we're using [packr](https://github.com/gobuffalo/packr), I can we can implement something similar for gardener/gardener.
