### ISSUE TITLE
Eliminate the `predicate.FromMapper` usage to ensure code consistency

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#4487]
**How to categorize this issue?**

/area open-source
/kind cleanup
/priority 3

**What would you like to be added**:
We should move all predicates from /extensions to /pkg:
- Use `predicate.NewPredicateFuncs` instead of `FromMapper` to eliminate dependency to `/extensions/pkg/predicate`
- Move predicates to `/pkg/predicate`
- Create aliases for moved predicate functions in `extensions/pkg/predicate/predicate.go` to be backwards compatible.

**Why is this needed**:
There is an expected overlap for required predicates as we transition to Controller-Runtime also for Gardener components (GCM, Gardenlet, Scheduler). We don't want to make any Gardener packages being dependent on packages residing in `/extensions` because this will soon or later cause import cycles. Hence, we should move all predicates to `/pkg/predicate` so that both, Gardener and extensions, can use them.

**Comment by rfranzke** [comment]
#4860 has moved the generic predicates (i.e., those not strictly related to extensions) to `pkg/controllerutils/predicate`. IIUC, the only thing left for this issue is eliminating the [`FromMapper` usage](https://github.com/gardener/gardener/search?q=FromMapper). Is this correct @timuthy?

**Comment by timuthy** [comment]
Yes, that's correct @rfranzke. The original intention of this issue was to just maintain one `predicate.go` file in Gardener that can be used for both gardener and extensions but I'm also fine keeping it the way it is today. Eliminating the `FromMapper` usage becomes then only a nice-to-have code consistency.

**Comment by rfranzke** [comment]
OK, thanks @timuthy, sounds reasonable, then let's do it this way and close the issue afterwards.
/title Eliminate the `predicate.FromMapper` usage to ensure code consistency
