### ISSUE TITLE
Alert Volume

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#45]
**Issue by [vlerenc](https://github.com/vlerenc)**
_Tuesday Oct 24, 2017 at 07:03 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/163_

----

Please investigate the current alert volume (at present far too many for manual inspection). Are we having too many alerts fired or too early? If not, what's wrong with the clusters, what do we need to change, which features are missing?

The key point is: How can we improve either (alerts or clusters) and lower the alert volume to a reasonable amount that an operator can/should investigate (at present, that's simply not possible, giving the sheer alert volume).

**Comment by gardener-robot-ci-1** [comment]
**Comment by [mvladev](https://github.com/mvladev)**
_Wednesday Oct 25, 2017 at 01:02 GMT_

----

I'm not yet about the firing too early, but some of the things I'm planning to do is

- [x] If no nodes are available, mute all alerts for shoot elements
- [x] if VPN is down, mute all alerts for shoot elements
- [x] better grouping by alertnames

**Comment by gardener-robot-ci-1** [comment]
**Comment by [mvladev](https://github.com/mvladev)**
_Wednesday Oct 25, 2017 at 12:53 GMT_

----

From my tests it will work very good, let's keep it open for a couple of days and see if we can improve it further.

**Comment by gardener-robot-ci-1** [comment]
**Comment by [mvladev](https://github.com/mvladev)**
_Wednesday Oct 25, 2017 at 15:03 GMT_

----

- [x] etcd was missing metrics endpoints after refactoring
- [x] kube-state-metrics is not present in Azure

**Comment by vlerenc** [comment]
Done, needs retesting.
