### ISSUE TITLE
Make CloudProfiles ready to be used in conjunction with Quotas

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#450]
In the context of enabling quotas for shoots we have to add another field named `advertised` or `deprecated` to the `machineTypes` and `volumeTypes` structs of the `CloudProfile`s.

From Markus: "But one use case that comes into my mind why we can't remove the old machine types that are still in use is the Quota/Trial use case. Because there the amount of currently used CPUs and memory is determined based on the machine types of the currently existing shoots."

Hence, when using `Quota`s we need to keep those `machineTypes` and `volumeTypes` that we don't want to offer for creating new clusters in the `CloudProfile`s as long as they are used by shoots having quota constraints.
The [ShootValidator admission plugin](https://github.com/gardener/gardener/tree/master/plugin/pkg/shoot/validator) needs to be adapted properly.

**Comment by rfranzke** [comment]
Or, another even better and more clean option could be to check in an admission controller that a machineType/volumeType cannot be removed if it's in use by shoots under quota. With that we wouldn't force the Gardener provider to keep these settings up-to-date, effectively reducing ops effort.

**Comment by rfranzke** [comment]
@mliepold are you interested in taking this one?

**Comment by mliepold** [comment]
Yes, I can take this one.
And an admission controller makes sense to prevent that a machine or volume type is deleted, if it is still used. But it doesn't solve the problem with switching to new (and better) machine types and also doesn't solve the internal requirement of not advertising some big machine types in the UI. For this we still need to add a field to the ```machineTypes``` and ```volumeTypes``` structs of the ```CloudProfile```.

**Comment by rfranzke** [comment]
OK, with the admission controller we could prevent removing in-use machine/volume types, however, we can't prevent that newly created clusters use those we don't want to be used anymore. Agreed, then let's go with the first approach and introduce an `advertised={true,false}` (`*bool)` field to the machine/volume types in the `CloudProfile` which is defaulted to `true` if not specified.

**Comment by mliepold** [comment]
After a discussion with the Dashboard team and @rfranzke we decided to name the flag ```usable={true,false} (*bool)```. The default value is ```true```. 
If the flag is set to ```false```, the machine/volume type can't be used anymore to create new shoot clusters. And these machine/volume types won't be displayed in the Dashboard anymore.
