### ISSUE TITLE
[good first issue] Make Seed lease sync/duration period configurable

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4504]
**How to categorize this issue?**

/area scalability
/kind enhancement

**What would you like to be added**:

Make Seed lease sync/duration period configurable, currently the gardenlet uses hard-coded values for lease duration and sync period (see [here](https://github.com/gardener/gardener/blob/v1.28.0/pkg/gardenlet/controller/seed/seed_lease_control.go#L43)).
Instead, there should be proper configuration fields in [`SeedControllerConfiguration`](https://github.com/gardener/gardener/blob/v1.28.0/pkg/gardenlet/apis/config/v1alpha1/types.go#L225) or a similar controller configuration struct for the seed lease controller.

**Why is this needed**:

Updating leases for every Seed every 2 seconds generates quite some load on the garden kube-apiserver in larger landscapes with many seeds.

**Comment by timebertt** [comment]
Thanks @hzliangbin for picking this up!
Just a small heads-up: the seed lease controller is refactored with #4503 (411992bc616fabd76ca5660ab78111a3383a1d68).
Depending on what gets merged first, you might need to rebase a bit.

**Comment by hzliangbin** [comment]
@timebertt ok

**Comment by hzliangbin** [comment]
sorry, just too busy recently, anyone who interested can take it.
