### ISSUE TITLE
Enabling scheduled backup compaction for ETCD via gardenlet feature gate

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/gardener#4511]
**How to categorize this issue?**

/area control-plane cost high-availability disaster-recovery
/kind enhancement
/priority 2

**What would you like to be added**:

The [upcoming release](https://github.com/gardener/etcd-druid/milestone/15?closed=1) of `etcd-druid` includes the feature to [schedule periodic compaction of incremental snapshots](https://github.com/gardener/etcd-druid/blob/master/docs/compactor.md) in the ETCD backup. This feature improves the disaster-recovery behaviour by setting an upper limit to the [time taken to restore ETCDs from backup](https://github.com/gardener/etcd-druid/issues/88).

However, enabling this for all ETCDs in the landscape might incur additional cost especially in network traffic.

To gain more control over the rollout of this feature, it would be good to introduce a new [`gardenlet` feature gate](https://github.com/gardener/gardener/blob/584ae9587896f5c04cd33a13e14b1774b37d32d9/pkg/gardenlet/features/features.go#L27-L38) (say, `ETCDBackupCompaction`) so that the feature can be enabled only in the soil clusters first (to gain control over the ETCD restoration time for the seed ETCDs) and only later in other seed clusters if there is a need.

Further,
1. Would it also be a good idea to introduce an overall gardener feature-gate?
1. If we decide to switch on the feature on other seed clusters (other than the soil cluster) eventually, would it also be a good idea to have a mechanism to control which shoot ETCDs get this functionality (maybe based on an additional field or the existing `purpose` field in the `Shoot` spec)?

cc @dguendisch @dkistner @mliepold @ashwani2k 

**Why is this needed**:

ETCD restoration time can be [quite long (`45m` to `1h` or even longer)](https://github.com/gardener/etcd-druid/issues/88#issuecomment-470154740) if there are a lot of incremental snapshots to be applied during restoration (the incremental snapshots can only be applied sequentially).

This affects larger shoot clusters where the number of changes flowing into the ETCD is quite large (such as seed clusters).

**Comment by dkistner** [comment]
> If we decide to switch on the feature on other seed clusters (other than the soil cluster) eventually, would it also be a good idea to have a mechanism to control which shoot ETCDs get this functionality (maybe based on an additional field or the existing purpose field in the Shoot spec)?

How about using an annotation on the Shoot resource for this?

**Comment by vpnachev** [comment]
> Would it also be a good idea to introduce an overall gardener feature-gate?

TBH, I don't think a gardenlet feature gate is the correct implementation. You can simply expose some etcd-druid configuration options via the gardenlet config, just like it is done for the logging and SNI https://github.com/gardener/gardener/blob/0bb7e5842c2b51ab0cf3c33a343cac75288ee101/pkg/gardenlet/apis/config/v1alpha1/types.go#L75-L82.

**Comment by rfranzke** [comment]
@abdasgupta @timuthy Do you still plan to have such feature gate? In the recent PRs, I think etcd backup compaction can be configured via gardenlet configuration, is this enough?

**Comment by timuthy** [comment]
Thanks for reminding @rfranzke. You're right, we discussed this option internally and decided to go with the typical options instead of introducing a feature gate because they usually come with a graduation plan, i.e. the feature gate itself will eventually be removed again. But compaction should be turned on/off by operators if they see demand for it, so it's independent from the graduation state.

**Comment by rfranzke** [comment]
Great, thank you!
