### ISSUE TITLE
kube-dns service cannot be created because of ClusterIP conflict

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4514]
**How to categorize this issue?**

/area robustness
/kind bug

**What happened**:

The `kube-dns` service of the managed resource `shoot-core` could not be created during shoot creation as the specified ClusterIP is already used by the service `addons-nginx-ingress-controller`:

```
$ kubectl -n kube-system get svc
NAME                              TYPE           CLUSTER-IP    EXTERNAL-IP                              PORT(S)                      AGE
addons-nginx-ingress-controller   LoadBalancer   100.64.0.10   some-lb.eu-central-1.elb.amazonaws.com   443:30932/TCP,80:32101/TCP   26h
...
```

`spec.clusterIP` of the `kube-dns` service is hard-coded to the 10th IP of the shoot's service CIDR ([ref](https://github.com/gardener/gardener/blob/7a4d0fb41871065c3692704dc0f8bb5ee60847d1/pkg/operation/shoot/shoot.go#L611)), while other services like `addons-nginx-ingress-controller` don't specify `spec.clusterIP`, hence they are dynamically allocated from the service CIDR.

The `shoot-core` ManagedResource fails to be reconciled:
```
  - message: 'Could not apply all new resources: 1 error occurred: error during apply
      of object "v1/Service/kube-system/kube-dns": Service "kube-dns" is invalid:
      spec.clusterIPs: Invalid value: []string{"100.64.0.10"}: failed to allocated
      ip:100.64.0.10 with error:provided IP is already allocated'
    reason: ApplyFailed
    status: "False"
    type: ResourcesApplied
```

Thus, the shoot's `SystemComponentsHealthy` condition will transition to `False`.

**What you expected to happen**:

The `kube-dns` service's ClusterIP should be "reserved" and not be allocated to other services, so that the `kube-dns` service can be created successfully.

**Preliminary analysis**:

Looking at the code for [`DeployManagedResourceForAddons`](https://github.com/gardener/gardener/blob/543217d363c57073e0bf681f19937e95fd6419c9/pkg/operation/botanist/addons.go#L259) it seems like this is a race condition in the way we deploy both `ManagedResources`. It might happen, that gardener-resource-manager first tries to create some of the services without a static ClusterIP before creating the `kube-dns` service. Thus, one of them might "steal" the static IP, which causes that the `kube-dns` service cannot be created.

This race condition might surface, when gardener-resource-manager is restarted while deploying the `ManagedResources`, its watch connection is reset or something similar.

Note that the chances of hitting this issue is very low, as the service CIDR is typically quite large (e.g. `/13`) and hence it's quite unlikely, that this specific IP is allocated dynamically.

**How to reproduce it (as minimally and precisely as possible)**:

You can provoke the error by deleting the `kube-dns` service and re-creating one of the other services with `spec.clusterIP` set to the reserved IP.

Thanks @MartinWeindel for reporting!

**Comment by timebertt** [comment]
One solution that was proposed is to add a validating webhook to shoots that allows the reserved ClusterIP to only be used by the `kube-dns` service (cc @vpnachev @danielfoehrKn).
This could also prevent this issue from happening, when users tamper with the `kube-dns` service and delete it during a shoot's lifecycle.

However, adding such a webhook would require a new component similar to the [API Server proxy pod webhook](https://github.com/gardener/apiserver-proxy#api-server-proxy-pod-webhook). 
It seems like creating such a component is a high effort (especially regarding maintenance) when considering the low chances of hitting this issue. Also, the issue is very easy to resolve (just delete the offending service).

Instead, I propose to extract the coredns resources (including the `kube-dns` service) into a dedicated ManagedResource (following earlier refactorings like #3257, #4096).
This ManagedResource should then be deployed as the first one in a dedicated flow task. The task should then also wait for the service to be created before creating other ManagedResources and Services in the shoot.
I think, this would be a sufficient and adequate solution to this issue.
WDYT?

**Comment by rfranzke** [comment]
> Instead, I propose to extract the coredns resources (including the kube-dns service) into a dedicated ManagedResource (following earlier refactorings like #3257, #4096).
This ManagedResource should then be deployed as the first one in a dedicated flow task. The task should then also wait for the service to be created before creating other ManagedResources and Services in the shoot.
I think, this would be a sufficient and adequate solution to this issue.
WDYT?

+1, exactly this is what we should do :)

**Comment by BeckerMax** [comment]
as discussed in the quality focus meeting:
As this deals with a corner case (during initial cluster creation), it has a relatively easy fix (retrigger cluster recreation) and it was reported only once we decided to close this issue. Please reopen if we see this more often.

/close
cc @rfranzke @timebertt
