### ISSUE TITLE
gardenlet always creates (useless?) ssh-keypair.old Secret on Shoot creation/reconciliation

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4527]
/area quality
/area auto-scaling
/kind bug
/priority 3

**What happened**:
gardenlet always creates (useless?) ssh-keypair.old Secret on Shoot creation/reconciliation. First I was quite surprised that  ssh-keypair.old Secret is created on landscapes even when `RotateSSHKeypairOnMaintenance` feature gate was never enabled.
Then I found the communication in https://github.com/gardener/gardener/pull/4224/#discussion_r653302565.

Currently this is creating a huge waste as a these ssh-keypair.old Secrets contribute a large portion of the Secrets' count in the garden cluster. It is also proportional to the Shoots' count - more Shoots, more (useless?) ssh-keypair.old Secrets.

**What you expected to happen**:
ssh-keypair.old to be created only when a `rotate-ssh-keypair` operation is requested.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Shoot

2. Make sure that the `${SHOOT_NAME}.ssh-keypair.old` Secret exist in the garden cluster. Note that no `rotate-ssh-keypair` operation was requested and the `RotateSSHKeypairOnMaintenance`  feature gate of gardener-controller-manager was never enabled -> so rotate-ssh-keypair operation was never requested.

```
$ k -n garden-foo get secrets | grep bar
bar.kubeconfig        Opaque                                3      13s
bar.monitoring        Opaque                                3      13s
bar.ssh-keypair       Opaque                                2      13s
bar.ssh-keypair.old   Opaque                                2      13s
```

**Environment**:

- Gardener version: v1.28.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by vpnachev** [comment]
cc @petersutter
