### ISSUE TITLE
Allow configuration of --service-account-extend-token-expiration or disable it

### ISSUE THREAD

**Issue by shahar-h** [gardener/gardener#4559]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority 3

**What would you like to be added**:
Currently `--service-account-extend-token-expiration` is enabled by default for shoot kube-apiserver, which means [bound service account tokens](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume) would be extended up to 1 year instead of 1 hour.
Are you planning to disable it or expose a configuration in shoot spec?

**Why is this needed**:
We would like to be able to control automatic token rotation period, and 1 year is too long from security aspects.

**Comment by shahar-h** [comment]
Any update? I noticed that kubelet rotates bound token once in a hour, but the old token is still valid for a year.
The only way to revoke it is to delete the pod.

**Comment by rfranzke** [comment]
/assign

I am currently working on a refactoring of how the kube-apiserver deployment (PR hopefully to be open today or tomorrow). After this one is approved and merged, I can take a look at this request, it shouldn't be too difficult.

**Comment by rfranzke** [comment]
Once #4639 is merged I can tackle this.
