### ISSUE TITLE
Introduce a validating logic for Container Runtime type

### ISSUE THREAD

**Issue by vanjiii** [gardener/gardener#4561]
**How to categorize this issue?**

/area TODO
/area ops-productivity
/kind enhancement
/priority 3

**What would you like to be added**:
To be introduce a validating logic in https://github.com/gardener/gardener/tree/master/pkg/apis/extensions/validation for the `extensions.ContainerRuntime`. For reference explore the existing ones. 

Also it should be properly register in the existing validating webhooks.

Edit DescribeTable.Entry for ContainerRuntime in the `pkg/seedadmissioncontroller/webhooks/admission/extensionresources/admission_test.go` after #4499  is merged

**Why is this needed**:
It is useful to have validating mechanism for that type like they are for all other types.

/cc @stoyanr

**Comment by rfranzke** [comment]
@vanjiii Are you working on this one?

**Comment by vanjiii** [comment]
> @vanjiii Are you working on this one?

Currently no.
