### ISSUE TITLE
Consider using `metav1.{SetMetaDataLabel,SetMetaDataAnnotation}` instead of `kutil.{SetMetaDataLabel,SetMetaDataAnnotation}`

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4576]
/kind cleanup
/priority 3

**What would you like to be added**:
Some time ago I added `SetMetaDataLabel` to the `k8s.io/apimachinery/pkg/apis/meta/v1` pkg - https://github.com/kubernetes/kubernetes/pull/93027.

Currently we have `kutil.{SetMetaDataLabel,SetMetaDataAnnotation}` that I think these funcs should be equivalent to `metav1.{SetMetaDataLabel,SetMetaDataAnnotation}`.
We can adapt usages of `kutil.{SetMetaDataLabel,SetMetaDataAnnotation}` to `metav1.{SetMetaDataLabel,SetMetaDataAnnotation}`.

**Comment by timebertt** [comment]
I also considered removing the `kutil` funcs in favor of their `metav1` counterparts.
Howerver, the `kutil` variants can also be used in generic functions that just have a `client.Object` for example. `metav1` funcs require passing a `*metav1.ObjectMeta`.
So I guess, we can replace many but not all usages in our codebase.
