### ISSUE TITLE
Follow-up on removal of deprecated IGW AWS annotations 

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4578]
**How to categorize this issue?**

/area quality
/kind cleanup
/priority 3

**What would you like to be added**:
https://github.com/gardener/gardener/pull/3185 deprecates the AWS specific annotations on the `istio-ingressgateway` Service in favour of the `.spec.settings.loadBalancerServices.annotations` field in the Seed spec.

**Why is this needed**:
To do not have AWS specific annotations on the `istio-ingressgateway` Service.

**Comment by ialidzhikov** [comment]
I actually have some doubts on exactly how to proceed with this issue.

The first question that I asked was "Is the NLB (hence the svc annotations) for the istio-ingressgateway for AWS a hard requirement, a recommended LB type or just an option that does not matter much?". [GEP-08](https://github.com/gardener/gardener/blob/master/docs/proposals/08-shoot-apiserver-via-sni.md) writes that
> (this loadbalancer should be a simple Layer-4 TCP proxy)

but to be honest at least for me this does not give a clear answer to the above question (I am not an expert in the networking area). I was able to successfully create Shoots on a Seed with istio-ingressgateway that is classical LB but again - not sure whether this experiment is enough to make statements for the above question.

I agree that it is odd to have the AWS NLB annotations hard-coded in the gardener code-base. On the other side if the NLB (hence the svc annotations) are a hard requirement (or highly recommended setup) it would be odd and error-prone to require the annotations to be set on the Seed itself:

```yaml
```

**Comment by ialidzhikov** [comment]
I actually have some doubts on exactly how to proceed with this issue.

The first question that I asked to myself was "Is the NLB (hence the svc annotations) for the istio-ingressgateway for AWS a hard requirement, a recommended LB type or just an option that does not matter much?". [GEP-08](https://github.com/gardener/gardener/blob/master/docs/proposals/08-shoot-apiserver-via-sni.md) writes that
> (this loadbalancer should be a simple Layer-4 TCP proxy)

but to be honest at least for me this does not give a clear answer to the above question (for sure I am not an expert in the networking area). I was able to successfully create Shoots on a Seed with istio-ingressgateway that is classical LB but again - not sure whether this experiment is enough to make statements for the above question.

I agree that it is odd to have the AWS NLB annotations hard-coded in the gardener code-base. On the other side if the NLB (hence the svc annotations) are a hard requirement (or highly recommended setup) it would be odd and error-prone to require the annotations to be set on the Seed spec itself for all AWS Seeds:

```yaml
    loadBalancerServices:
      annotations:
        service.alpha.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```

Possible approaches:
- Require/recommend via the usage documentation that annotations have to be set in the Seed spec for AWS Seeds when the ManagedIstio and APIServerSNI features are enabled. Remove the hard-coded annotations after some time and rely on the Seed spec.
- Leave it as it is today and remove the deprecations.
- (If the NLB is a hard requirement or highly recommended) think of extensibility approach that would allow a provider extension to mutate the istio-ingressgateway svc (?)

Opinions?

/cc @ScheererJ @DockToFuture

**Comment by ialidzhikov** [comment]
No feedback on https://github.com/gardener/gardener/issues/4578#issuecomment-989854330, hence
/unassign

**Comment by ScheererJ** [comment]
My preference would be

- Leave it as it is today and remove the deprecations.

**Comment by rfranzke** [comment]
OK, so then the open task is to remove the deprecations, correct?

**Comment by ScheererJ** [comment]
> OK, so then the open task is to remove the deprecations, correct?

From my perspective: Yes.
