### ISSUE TITLE
Pods/Infrastructure Not Reconciled After Restore

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#46]
**Issue by [vlerenc](https://github.com/vlerenc)**
_Tuesday Nov 07, 2017 at 16:06 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/186_

----

We seem to have issues when we restore a backup: Pods/containers that were created after the last backup turn into unmanaged zombies once the backup is restored, i.e. the kubelet doesn't kill them even though it should know that it created them once, but they are no longer scheduled for that node.

The assumption is that we may have similar issues with PVs or LBs.

Therefore we should first check whether we have indeed reconciliation issues with PVs or LBs. Next we should check what else (that we control) might be misaligned/turn into zombies. Finally we should come up with a plan how to address these issues. Maybe there are already issues filed by others or we need to file new ones. Maybe we need to contribute or we can mitigate with minimal effort (e.g. a rolling update will resolve the pod/container issue from above).

As for the customer load in the shoot cluster as such: If Kubernetes isn't addressing this issue, we can't. We should therefore inform the customers, in general (a priori) and when it happens (on occasion). Other than that, I see no way we could reconcile whatever the customer is running as cluster workload (could be custom resource definitions with all kinds of side effects or anything else). We simply don't know and can't handle this situation in a clean way.

**Comment by vlerenc** [comment]
As discussed with the above finding in November last year, we should invest in incremental/continuous backups, so that we can restore a backup that doesn't deviate from the infrastructure and everything too much (hopefully not at all), otherwise we break the cluster.

**Comment by vlerenc** [comment]
Replaced with follow-up action https://github.com/gardener/etcd-backup-restore/issues/2.
