### ISSUE TITLE
Support End-User Configuration for set of encrypted resources

### ISSUE THREAD

**Issue by mandelsoft** [gardener/gardener#4606]
**How to categorize this issue?**

  /area control-plane
/kind enhancement
/priority 2

**What would you like to be added**:

Enable end users to configure additional resources for etcd encryption.

**Why is this needed**:

So far only secrets are encrypted in shoot clusters. Because there may be other custom resources in shoot clusters
that may contain sensitive data, it is required to be able to influence the set resources intended to be encrypted.

As far as I understood this info is taken from an API Server config file, that is not yet configurable via the shoot manifest.

An actually important use case for this feature is the landscaper. It uses resources for data objects and deploy items 
that may contain sensitive data and therefore urgently need to be encrypted in etcd.

**Comment by rfranzke** [comment]
Work has been started and pushed to https://github.com/timebertt/gardener/tree/enh/encrypted-resources.

**Comment by reshnm** [comment]
It looks like with Kubernetes 1.26.x, encryption of  custom resources will be supported: https://github.com/kubernetes/kubernetes/pull/113015

Are there any plans to support this for in Gardener? This would be really helpful to encrypt custom resources that contain sensitive data.

**Comment by rfranzke** [comment]
Interesting, so without https://github.com/kubernetes/kubernetes/pull/113015 the feature would not even have worked as expected. In this case, it's actually good that we haven't implemented it yet 😅 

@reshnm We plan to eventually support it, yes, but we don't have a timeline for it yet. But given that it would only work for 1.26+ it isn't too urgent either. Probably we won't make it in 2022, but hopefully early next year.

/remove lifecycle/stale

**Comment by reshnm** [comment]
@rfranzke Thank you for the clarification 👍

**Comment by rfranzke** [comment]
In order to deploy the Gardener control plane with `gardener-operator` (ref https://github.com/gardener/gardener/issues/7016), this issue is a prerequisite.

**Comment by In-Ko** [comment]
Hey guys, is there a timeline for this ?

**Comment by rfranzke** [comment]
Hi @In-Ko, not yet - we still have it on our radar, and we implemented a few prerequisites as part of #7016 (ref https://github.com/gardener/gardener/issues/4606#issuecomment-1434299846), however the majority of the story is still missing. #7016 is completed now and we plan to focus on #8023 next, perhaps we can come back to this issue after that. Please keep watching it for updates.
