### ISSUE TITLE
Persist kubernetes events in observability stack

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4612]
**How to categorize this issue?**

/area monitoring logging
/kind enhancement

**What would you like to be added**:

We should persist kubernetes events (for example for seed components and shoot control plane and system components) and make them available alongside logs and metrics in our observability stack(s)

**Why is this needed**:

Kubernetes events are supposed to be short-lived and are collected after 1 hour by default.
However, events often carry important hints for understanding behavior and debugging issues of production components.
But due to the short-lived nature, operators and developers can't properly leverage the information carried by events.

**Comment by dguendisch** [comment]
fwiw: we deployed https://github.com/heptiolabs/eventrouter for the testmachinery for this exact purpose.

**Comment by timebertt** [comment]
We definitely need this, but it's not clear yet who will take this over.
/remove-lifecycle rotten
/lifecycle frozen
