### ISSUE TITLE
Add support for KubeSchedulerConfiguration kubescheduler.config.k8s.io/v1beta2 

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#4617]
**How to categorize this issue?**

/area open-source
/kind enhancement
/priority 3

**What would you like to be added**:
Kubernetes `v1.22` adds `KubeSchedulerConfiguration` in version `kubescheduler.config.k8s.io/v1beta2`. However, we cannot use this config version for the `SeedKubeScheduler` out of the box because both `NodeResourcesLeastAllocated` ([disabled in config](https://github.com/gardener/gardener/blob/53847edc6c7ffa7dfd4bf54ace3739a1d15c66c8/pkg/operation/botanist/component/gardenerkubescheduler/gardener_kube_scheduler_bootstrap.go#L73)) and `NodeResourcesMostAllocated` ([enabled in config](https://github.com/gardener/gardener/blob/53847edc6c7ffa7dfd4bf54ace3739a1d15c66c8/pkg/operation/botanist/component/gardenerkubescheduler/gardener_kube_scheduler_bootstrap.go#L77)) have been removed from the list of available plugins ([ref](https://github.com/kubernetes/kubernetes/pull/101822/files#diff-f8599401f1c49b5a1125e02bf4bbfb46cdeb1a86c3818974588f36e9d91c6687R100)) in `v1beta2` and are already deprecated in `v1beta1`. They were replaced by a new plugin `NodeResourcesFit`, see [here](https://github.com/kubernetes/kubernetes/pull/101822). We need to verify if and how this can serve as a proper replacement for our use-cases.

**Why is this needed**:
The mentioned plugins are deprecated and once Kubernetes drops the support for `v1beta1` the `KubeSchedulerConfiguration` breaks.

**Comment by timuthy** [comment]
@mvladev do you have the capacity to take a look?

**Comment by rfranzke** [comment]
This might be related to https://github.com/gardener/gardener/issues/4741

**Comment by vlerenc** [comment]
We have more demand for such a feature in the meantime from big players, so it's no longer interesting just for Gardener itself (its seeds). Who would be most familiar with the subject matter to discuss?

Also, would it make sense to hold back #4741 until this one is sorted out? And should we close #1455 as duplicate (this one here is newer, but has more up-to-date information/links). Or would that be inappropriate as this one here is more concerned with us/Gardener and our seeds specifically (the title doesn't tell, but the text points at seeds specifically)?

**Comment by timuthy** [comment]
> Who would be most familiar with the subject matter to discuss?

IIRC, @ialidzhikov wanted to take over. Is this still true?

> And should we close #1455 as duplicate

Hm, I don't see a close relation between both issues. #1455 requests a configuration for end-users while this here solely addresses a compatibility problem for the `SeedKubeScheduler` feature.
