### ISSUE TITLE
Rotation of cloudprovider secret requires a Shoot reconcilation 

### ISSUE THREAD

**Issue by BeckerMax** [gardener/gardener#4630]
**How to categorize this issue?**
/area control-plane
/area documentation
/kind discussion

**Why is this needed**:

Repeatedly Shoot owners are surprised by the behaviour that after they rotate a cloudprovider secret in the garden cluster it is not instantly synced to the Seed cluster. If they deactivate the old cloudprovider secret in the infrastructure **before** reconciling the Shoot this leads to authentication errors (for example in the cloud-controller-manger).

**What would you like to be added**:

Approaches (to be detailed and discussed in the comments):
* Better inform the users about the behaviour by:
   1. Showing additional information on the dashboard after a secret is changed.
   2. Documenting the rotation behaviour in the docs -> https://github.com/gardener/gardener/pull/4631
* Force a reconciliation of all affected shoots after a rotated cloudprovider secret.

Which of those approaches would you find beneficial?

**Comment by BeckerMax** [comment]
> Force a reconciliation of all affected shoots after a rotated cloudprovider secret.

This could be implemented by a webhook watching for secrets. We could make this more efficient by first introducing a label for all cloudprovider secrets. In case a cloudprovider secret changes all secretbindings referencing that secret need to be listed. All shoots using that Secretbinding get labeled with the reconcile annotation.

All in all, in a former discussion with @rfranzke and @timuthy we leaned towards not implementing such a solution as it might lead to unexpected reconciliation of the Shoots for the stakeholder.

**Comment by timebertt** [comment]
Can this be closed with #4631?

**Comment by BeckerMax** [comment]
> i. Showing additional information on the dashboard after a secret is changed.

This is still open and I would close this issue after the dashboard change is merged.

**Comment by donistz** [comment]
There are two scenarios for this activity that are not yet covered:
[1] We have service consumers with >10 clusters created using one and the same IaaS account. Now they have to reconcile all these clusters one by one after changing the secret of the IaaS account. It will be good to have an option to reconcile with one click/one command all clusters that depend on one secret. 
[2] Many of our stakeholders already use the Gardener API to implement automated secret rotation because their corporate security rules require frequent static secrets rotation. Some of these rotations are scheduled and there is no person available to babysit the process. It will be good if Gardener API is extended with an optional parameter, so that customers are able to choose if they want to enforce cluster reconciliation when they change the secret via Gardener API or for example to call the Gardener API to reconcile all clusters that depend on a IaaS secret before to delete the old secret via the IaaS API.

**Comment by timuthy** [comment]
> Many of our stakeholders already use the Gardener API to implement automated secret rotation

Then they can also automate shoot cluster reconciliation with the Gardener API by annotating the affected shoot(s) with `gardener.cloud/operation: reconcile`.

**Comment by donistz** [comment]
> by annotating the affected shoot(s)

`kubectl -n garden-<project-name> annotate shoot <shoot-name> gardener.cloud/operation=reconcile`

@timuthy  Is there an easy way to find the list with clusters that depend on a concrete secret? In order to use `annotate shoot `one should know the names of all affected shoots in advance.

**Comment by timebertt** [comment]
> It will be good to have an option to reconcile with one click/one command all clusters that depend on one secret.

I don't think that reconciling all clusters at once is a good idea if they are using the same credentials, as this is known to quickly exhaust rate limits.

Regarding both 1 and 2, regular reconciliation (happing roughly every 24 hours) should actually be enough for the majority of cases and will not cause any new issues.
For the rare special cases, e.g. rotating leaked credentials, users are free to trigger an immediate reconciliation on all clusters by adding the reconcile annotation.

BTW, this should be doable in one kubectl command: 
```
k -n <project-namespace> annotate shoot gardener.cloud/operation=reconcile --overwrite --all
```

**Comment by timuthy** [comment]
> @timuthy Is there an easy way to find the list with clusters that depend on a concrete secret? In order to use annotate shoot one should know the names of all affected shoots in advance.

Precisely, you would need to find (1) all `SecretBinding`s which refer to the affected `Secret` and then (2) all `Shoot`s that have a reference to the `SecretBinding` in the same project namespace. However, if you roll a `Secret` and have GitOps in place then you probably also know the related `SecretBinding`s and `Shoot`s.
Users already have the freedom to implement such scenarios with the Gardener APIs whether they want to reconcile immediately, one shoot after another, or in a longer fashion (as mentioned by @timebertt).
