### ISSUE TITLE
Use immutable ConfigMaps/Secrets for gardenlet

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4646]
**How to categorize this issue?**

/area robustness
/kind enhancement

**What would you like to be added**:

The gardenlet is deployed with multiple ConfigMaps and Secrets by the gardenlet chart, the `ManagedSeed` controller and the gardenlet landscaper component: config, image vector overwrite(s), cert and kubeconfig secrets.

We should set `.immutable=true` for those ConfigMaps and Secrets just like for other components.

**Why is this needed**:

Prevent pods from mounting a ConfigMap/Secret with outdated/old/incompatible data.
Find more details here: #3484 gardener/gardener-resource-manager#104

**Comment by BeckerMax** [comment]
consider looking at vpn-shoot which uses helm charts which use immutable.
/priority 3
/assign
