### ISSUE TITLE
Automatically restart calico if vpn-shoot fails to start

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener#4649]
**How to categorize this issue?**

/area robustness
/kind enhancement
/priority 3

**What would you like to be added**:

A way to automatically restart calico if system components like the `vpn-shoot` are failing to come up due to `FailedCreatePodSandBox` errors.

**Why is this needed**:

Often times only calico needs to be restarted and then the system components can start again.

**Comment by vpnachev** [comment]
I guess this issue should be moved to https://github.com/gardener/gardener-extension-networking-calico.
It also looks like a duplicate of https://github.com/gardener/gardener-extension-networking-calico/issues/70.

**Comment by timuthy** [comment]
/close
As @vpnachev mentioned, that issue should be tackled by the Calico extension.
