### ISSUE TITLE
Gardenlet should reload kubeconfig after rotation instead of exiting

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#4662]
**How to categorize this issue?**

/area robustness
/kind enhancement
/priority 3

**What would you like to be added**:
Instead of exiting after its client certificate was rotated/renewed, the gardenlet should dynamically refresh its client and keep running.

/cc @danielfoehrKn @timebertt 

**Why is this needed**:
Less restarts of gardenlet, hence, less load on the garden and seed clusters.

**Comment by danielfoehrKn** [comment]
I discussed that topic with @timebertt during the implementation. I believe the reason why it was not done is because we used Informers with static clients all over the place. As far as I can remember these clients could not be refreshed.  
I think that nowadays we are in better shape here. Maybe @timebertt knows more details here

**Comment by timebertt** [comment]
> I discussed that topic with @timebertt during the implementation. I believe the reason why it was not done is because we used Informers with static clients all over the place. As far as I can remember these clients could not be refreshed.

Yep, this is also what I remember. I think, we mainly agreed on this approach, as it was quite simple and we didn't see a problem with it.
However, I agree that it makes sense to look into this again.

IIRC, the kubelet is actually able to refresh the client certificate during runtime. We might want to take a look, how this is achieved and if we can leverage similar mechanisms.

**Comment by timebertt** [comment]
There is https://github.com/kubernetes-sigs/controller-runtime/tree/master/pkg/certwatcher, but I think this is only for webhook servers.
However, maybe we can get some inspiration from it.
