### ISSUE TITLE
Shoot deletion should not wait for `ControlPlane` if it already has a `deletionTimestamp`

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#4724]
**How to categorize this issue?**

/area ops-productivity robustness
/kind bug
/priority 3

**What happened**:
When a `Shoot` is deleted and the corresponding `extensions.gardener.cloud/v1alpha1.ControlPlane` resource already has a `.metadata.deletionTimestamp` then we should not wait for its reconciliation to be finished.

This is intended to be implemented here and was introduced with https://github.com/gardener/gardener/pull/3960: https://github.com/gardener/gardener/blob/38ad556a7dec689b35c3ee6dd3cf59bd64b5c705/pkg/gardenlet/controller/shoot/shoot_control_delete.go#L643-L648

However, this only returns `false` when the `kube-apiserver` deployment is not found.

**What you expected to happen**:

It should return `false` even if the `kube-apiserver` is still running and not wait for a `ControlPlane` reconciliation.

**Environment**:

- Gardener version: v1.32.0
- Kubernetes version (use `kubectl version`): all
- Cloud provider or hardware configuration: all

**Comment by plkokanov** [comment]
I just have a worry that this might cause a problem when #4584 is merged. I will have time to test it out today file a PR if there are no issues.
