### ISSUE TITLE
Owner `DNSRecord` resources might get stuck without reconciliation

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#4725]
**How to categorize this issue?**

/area ops-productivity robustness
/kind bug
/priority 3

**What happened**:

For arbitrary reasons, controllers might miss events and don't react. We are mitigating this for the extensions controllers by annotating the current time when gardenlet demands a reconciliation (https://github.com/gardener/gardener/blob/61548c1ee9d9b7de046e78bdd048ced16eed7ba3/pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go#L144).

However, when the `CreateOnly` field of the `dnsrecord` Golang component is `true` and this create event is missed by the extension controller then this timestamp will never get updated (https://github.com/gardener/gardener/blob/61548c1ee9d9b7de046e78bdd048ced16eed7ba3/pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go#L164-L173), resulting in a stuck object (unless the extension controller itself restarts at some point in time).

**What you expected to happen**:

Until the `DNSRecord` was successfully reconciled we should behave the same as for all other extension resources. Probably `CreateOnly` should be renamed to `ReconcileOnce`.

**Environment**:

- Gardener version: v1.32.0
- Kubernetes version (use `kubectl version`): all
- Cloud provider or hardware configuration: all

**Comment by timebertt** [comment]
I think, this can especially cause troubles, if clusters go into a failed state before the owner DNSRecord is created.
Then the dns controller will simply ignore the resource and not reconcile it at all. If the cluster comes out of a failed state, the owner DNSRecord is never touched again and thus not reconciled (as there is no watch event).
