### ISSUE TITLE
Improve error message when `ManagedResource` is stuck in deletion

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#4727]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement
/priority 3

**What would you like to be added**:
When a `Shoot` cannot be deleted because the `ControlPlane` resource is stuck because some `ManagedResource` is stuck then the following error is presented:

```text
Error deleting controlplane: error while waiting for managed resource containing shoot CRDs chart for controlplane 'shoot--foo--bar/bar' to be deleted: retry failed with context deadline exceeded, last error: resource shoot--foo--bar/extension-controlplane-shoot-crds still exists
```

Can we extend the information to read which resources are exactly blocking the deletion (the `.status.resources` field in the `ManagedResource` should have the information)? Then we could also define a regex for error code matching to classify such issues properly.

**Why is this needed**:
Better error message -> better ops productivity -> easier error categorization.

**Comment by plkokanov** [comment]
I finally had some time to work on the issue and i'm currently testing my changes.
