### ISSUE TITLE
As on operator, I want `crictl` to be installed and preconfigured, such that I can use it for debugging the container runtime

### ISSUE THREAD

**Issue by voelzmo** [gardener/gardener#4729]
**How to categorize this issue?**

/area os
/area control-plane
/kind enhancement
/priority 3

**What would you like to be added**:
Install [`crictl`](https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md) and configure it for the runtime used on the node (`/etc/crictl.yaml`).

Pro:
* one tool for all CRI runtimes (even for dockershim), therefore only one tool to master and no if/else in ops-guides, scripts, etc.
* no need to fiddle with cri-specific tools like `ctr` with its own drawbacks (e.g. you have to set `CONTAINERD_NAMESPACE=k8s.io`, otherwise, you don't see anything with it)

Con:
* another thing to install and manage on all images. See discussion in https://github.com/gardener/gardener/issues/2719#issuecomment-843851930

Other options:
* Installing `crictl` in our ops-pod instead of the OS images will result in the tool being available much quicker in production systems, as we don't have to wait until a new OS version has been deployed by every Shoot owner
* Installing `nerdctl` instead of `crictl`

**Why is this needed**:
We're forcing migration off the built-in dockershim with #4110 and expect more and more clusters to be configured with `containerd`. This means, operators need to get more comfortable operating and debugging clusters with this configuration. There are multiple options for CLIs like the already installed `ctr`, `nerdctl` or `crictl`. However, it will still take a while until we got rid of all production clusters with `docker`. To help streamlining the operation and debugging experience, we should strive to unify this process as much as possible.

**Comment by timebertt** [comment]
Do we want to pursue this further?

**Comment by voelzmo** [comment]
Working with `ctr` continues to be a pain, every time we're looking at `containerd` issues I see people being tempted to bring in other tools (`nerdctl`, for example) so while I'm not sure about the initial premise of this item (having the same tool regardless of which container runtime it is), I definitely see a need to improve the operator experience for `containerd` clusters.
