### ISSUE TITLE
Harmonize finalizer addition across all controllers

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4730]
**How to categorize this issue?**

/area robustness
/kind enhancement

**What would you like to be added**:

From https://github.com/gardener/gardener/pull/4696#discussion_r714603123:

In some controllers (e.g. shoot controller) we return `nil` after adding the finalizer and wait for an update watch event to prevent duplicated reconciliations (see https://github.com/gardener/gardener/pull/2364).
However, a majority of the other controllers behaves differently and presumably does duplicated/unwanted reconciliations.

We should harmonize the behavior in all our controllers to 
- prevent duplicated reconciliations
- cause less confusion along developers and have a good template for new controllers

Ideas would be
- a) adopt the logic from the shoot controller everywhere (return `nil` after adding finalizer)
- b) changing the update event handlers to enqueue objects only when the generation changed (instead of comparing `metadata.generation` and `status.observedGeneration`), this is also what controller-runtime supports out of the box with `predicate.GenerationChangedPredicate` (see https://github.com/gardener/gardener/pull/4696#discussion_r714791574)

**Comment by rfranzke** [comment]
@shafeeqes Can you please describe what is missing here after https://github.com/gardener/gardener/pull/5683?

**Comment by shafeeqes** [comment]
b) changing the update event handlers to enqueue objects only when the generation changed (instead of comparing metadata.generation and status.observedGeneration), this is also what controller-runtime supports out of the box with predicate.GenerationChangedPredicate

since all the controllers are not yet refactored.

**Comment by rfranzke** [comment]
Thanks @shafeeqes. As discussed earlier in our meeting, let's
/close
this issue for now since the main motivation (preventing duplicate reconciliations) was tackled. We might optimize the other suggestion as part of #4251, however there is no immediate necessity to pursue this task outside of the planned `controller-runtime` refactoring activities.

**Comment by oliver-goetz** [comment]
@timebertt @rfranzke after implementing b) finalizers are not enforced anymore. When finalizers are removed by someone/something else the reconciler does not add them unless a change which affects the generation happens or the controller is restarting.
Is this an accepted side effect or a bug?

**Comment by timebertt** [comment]
Is there a difference in this regard between a) and b)?
I think forcefully removing the finalizers is always a dangerous operation and is generally not prevented (e.g., LB services, PVCs, PVs). 
It should not be protected because sometimes that's the only way to get rid of resources, however you should know what you're doing 😄

**Comment by oliver-goetz** [comment]
Other controllers do the same, that's true 👍 
I just checked for b) because it is on my agenda now. However, there might be not much to do anyway. I have the impression most of our controllers are already adapted this way.

**Comment by rfranzke** [comment]
This sounds good @oliver-goetz, please confirm :) If there is nothing to be done, even better!

**Comment by oliver-goetz** [comment]
It is harmonized at most refactored controllers, but the more I check, the more places I find, where it's not done yet 😄
