### ISSUE TITLE
kube-proxy/conntrack-fix container is missing resource requests/limits

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4736]
**How to categorize this issue?**

/area auto-scaling networking
/kind bug

**What happened**:

The `conntrack-fix` sidecar of the `kube-proxy` is missing resource requests/limits.
It should be set to allow better scheduling and enable autoscaling (if the Shoot VPA feature is enabled).

**Comment by timebertt** [comment]
cc @DockToFuture @ScheererJ @wyb1 @istvanballok @marwinski

**Comment by rfranzke** [comment]
Is this really needed? This container is just doing minimal work and very likely will never be required to auto-scale. 👀

**Comment by timebertt** [comment]
VPA seems to recommend resources and apply them on Pod creation.
However, if VPA is not enabled, there are no resource requests in the Pod spec.
But I don't remember if this caused an actual issue.

**Comment by BeckerMax** [comment]
Following on the discussion in the Quality focus meeting:
- This container itself is minimal and should never need autoscaling.
- If VPA is enabled resource requests are attached. Therefore, the pod will be scaled.
Consequently, can we close the issue then?

**Comment by timebertt** [comment]
> However, if VPA is not enabled, there are no resource requests in the Pod spec.
But I don't remember if this caused an actual issue.

With this,
/close
