### ISSUE TITLE
☂️ -Issue for removal of the `SeedKubeScheduler` feature gate

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#4741]
**How to categorize this issue?**

/area auto-scaling
/kind enhancement
/priority 3

**What would you like to be added**:

❗ The `SeedKubeScheduler` feature gate is deprecated in favor of the `bin-packing` scheduling profile that can be configured for a Shoot referred by a ManagedSeed. For more details, see the discussion in https://github.com/gardener/gardener/issues/1455. Hence, the new tasks are:
- [x] Deprecate the `SeedKubeScheduler` feature gate -> https://github.com/gardener/gardener/pull/6599
- [x] Remove the `SeedKubeScheduler` feature gate -> https://github.com/gardener/gardener/pull/7052

---

<details>

<summary>Expand to see the old description of the issue!</summary>

The `SeedKubeScheduler` feature gate was introduced with 1.15 and is in alpha state since then. Let's push its beta promotion so that operators can confidently enable it.

Next steps and open points that were discussed with Martin V. on a handover session:
- Existing issue that on a large landscape we hit related to volume limits. Pods were attached to instances, but the instance had already hit its volume attachment limit on the infrastructure.
    ~~We suspect issue with the AWS CSI driver.~~ The issue has to be reproduced and properly investigated.
  - The issue has be reproduced -> https://github.com/gardener/gardener/issues/5064
  - Upstream PR created to k/autoscaler to address the issue -> https://github.com/kubernetes/autoscaler/pull/4539
  - The findings from https://github.com/gardener/gardener/issues/5064 lead to https://github.com/gardener/autoscaler/issues/107
- Add support for the new kube-scheduler API version `kubescheduler.config.k8s.io/v1beta2` (available in K8s 1.22). There is already issue about it - https://github.com/gardener/gardener/issues/4617. The plugins that we currently use `NodeResourcesLeastAllocated` and `NodeResourcesMostAllocated` are deprecated in v1beta1 and removed in v1beta2.
  - https://github.com/gardener/gardener/pull/5538
- Add support for the new kube-scheduler API version `kubescheduler.config.k8s.io/v1beta3` (available in K8s 1.23).
  - https://github.com/gardener/gardener/pull/5584
- Enable the feature gate and drive its promotion. According to Martin V., in the past, when we enabled the feature gate, the utilization was increased from ~30% to ~60%.
- (!) If we enable the feature, we can hit the cgroup issues on our Seed Nodes even more frequently. We will have more utilization on the Seed nodes. Currently in our setup we don't have the recommended cgroup setup and workload issues can harm system components. This item has to be properly checked.

</details>

**Why is this needed**:
Better resource utilization in the seed clusters.

**Comment by rfranzke** [comment]
I think we don't plan to graduate this feature gate, right? If this is correct, can you please adapt the title and the description/open tasks?

**Comment by ialidzhikov** [comment]
> I think we don't plan to graduate this feature gate, right? If this is correct, can you please adapt the title and the description/open tasks?

Done.
