### ISSUE TITLE
Graceful deletion for custom resources in shooted seed namespace

### ISSUE THREAD

**Issue by Gerrit91** [gardener/gardener#4743]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority 3

**What would you like to be added**:

Graceful deletion for custom resources (CRs) deployed by extension-providers in a seed's shoot namespace.

**Why is this needed**:

We have an extension-provider that deploys a small operator (kind of similar to the MCM pattern) including SA, RBAC resources and a CR that this operator is taking care of into the seed's shoot namespace through the control plane chart. 

When deleting a shoot cluster, the Gardener deletes the operator along with the CR (which has a finalizer) all at the same time. The operator does not have enough time for removing the finalizer of the CR such that shoot deletion hangs at 98% (deleting shoot namespace in seed) because the shoot namespace still contains the CR — without an operator being able to clean it up. 

At the moment, we deactivated the deletion flow of our operator and do not use finalizers in order to workaround the problem.

There are certain similarities to https://github.com/gardener/gardener/pull/3562, but this issue is only about resources located in the seed cluster's shoot namespace.

I briefly discussed this topic with @timebertt on Slack (thanks!), who also pointed out possible solutions for the issue:

> ...
> - add another separate chart to the generic control plane actuator for deploying and deleting your operator (including SA, RBAC and stuff) separately from the CR (however this doesn’t solve the missing wait operation – we might use a ManagedResource for that and wait until it is ready/cleaned up) [...]
> - add an optional interface with some additional Delete/Wait methods that is called by the generic actuator at the right places if it’s passed on creation [...]
> ...

**Comment by timuthy** [comment]
This is related to how the worker actuator was enhanced a while ago https://github.com/gardener/gardener/commit/140ee20eb7bb1afb1a90dc6324d829ff57dd1029. There we had the same situation, that the existing steps were not sufficient any more and introduced (`DeployMachineDependencies`, `CleanupMachineDependencies`).
