### ISSUE TITLE
Upgrade k8s.io/* to v0.22, sigs.k8s.io/controller-runtime to v0.10

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4772]
**How to categorize this issue?**

/area open-source
/kind task

**What would you like to be added**:

We should upgrade to the latest versions of our go upstream dependencies:
- `sigs.k8s.io/controller-runtime@v0.10.x`: https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.10.0
- `k8s.io/*@v0.22.x`

It's probably a good idea to complete this one before continuing on https://github.com/gardener/gardener/issues/4251.

## Important changes / Action items

Here is a list of a few upstream changes to look out for when vendoring g/g, k/* and c-r in any of our repos (e.g. extensions). Please consider the release notes of [controller-runtime@v0.10.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.10.0) and upwards as well for a more complete list and more details.
This list contains some action items for g/g as well.

### ⚠️ breaking / most notable changes

- https://github.com/kubernetes-sigs/controller-runtime/pull/1640
  - previously, a client call wouldn't unset present fields on the in-memory object if they were unset in the API server's response (standard behavior of json decoder in stdlib / k8s libs)
  - now, the client zeroes out fields before decoding into the passed object
  - similarly, the fake client now also zeroes out fields before decoding (https://github.com/kubernetes-sigs/controller-runtime/pull/1651), so this might make tests using the fake client fail if they were implemented incorrectly
  - [x] remove our workarounds in g/g for the old behavior (mainly `kutil.CreateResetObjectFunc`), as they are not needed anymore with the changed client behavior

- https://github.com/kubernetes-sigs/controller-runtime/pull/1626
  - [Many important APIs are not served anymore in 1.22](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22), however they are still present in the published API packages (https://github.com/kubernetes/api/tree/release-1.22 and friends)
  - [x] `envtest.WebhookInstallOptions.*Webhooks` and `envtest.CRDInstallOptions.CRDs` have to be switched from `client.Object` to the respective typed objects

- https://github.com/kubernetes-sigs/controller-runtime/pull/1587
  - currently, we don't seem to be using `rest_client_request_latency_seconds` (so far we are also exposing it only on a few components)

### ℹ️ other changes / good to know / for information only:

- https://github.com/kubernetes-sigs/controller-runtime/pull/1627
  - [x] consider setting `controller.Options.RecoverPanic=true` -> https://github.com/gardener/gardener/pull/5383
- https://github.com/kubernetes-sigs/controller-runtime/pull/1588
  - [x] consider using `server.StartedChecker()` for components serving webhooks -> https://github.com/gardener/gardener/pull/5380
- https://github.com/kubernetes-sigs/controller-runtime/pull/1665
  - [x] don't need to set `GVK` / `TypeMeta` on `envtest.WebhookInstallOptions.*Webhooks` explicitly anymore
- https://github.com/kubernetes-sigs/controller-runtime/pull/1678
  - only applies to native controller-runtime controllers using `source.Kind`, g/g can only benefit from it once https://github.com/gardener/gardener/issues/4251 is completed
- https://github.com/kubernetes-sigs/controller-runtime/pull/1629
  - [x] upgrade envtest binaries to at least v1.21 (to get etcd v3.5) and make sure, we use `--unsafe-no-fsync` to stop writing to disk in envtests ➡️ https://github.com/gardener/gardener/pull/4851
- https://github.com/kubernetes-sigs/controller-runtime/pull/1647

**Comment by timebertt** [comment]
I will wait for https://github.com/gardener/gardener/pull/4757 progress before starting on this in order to avoid too many conflicts.

**Comment by timebertt** [comment]
/unassign
as I have completed all steps that were on my list. The other remaining tasks in this list are not urgent and can be taken over by others as well.

**Comment by acumino** [comment]
@timebertt, IIUC `consider the setting controller.Options.RecoverPanic=true` can only be done for the controller, native to controller-runtime. If that is right, I think we should move ahead with this after the refactoring of `gardener-controller-manager` and `gardenlet`. WDYT?

**Comment by timebertt** [comment]
> can only be done for the controller, native to controller-runtime

Yes, that's true.

We can either do it for the controller's that are already controller-runtime native controllers today (admission-controller, resource-manager, scheduler) or later once all controllers are refactored.
However I expect "later" to be rather in a few months because of other priorities. So I would vote for doing it now for our c-r native controllers.

**Comment by acumino** [comment]
/cc @rfranzke 
Can we close this given all the extensions PR are merged now?

**Comment by rfranzke** [comment]
Sure, please close if there is nothing left to be done :)

**Comment by acumino** [comment]
> Sure, please close if there is nothing left to be done :)

Ready check PR for all provider-extension I think there is no need for this in any other extension.
