### ISSUE TITLE
The kube-controller-manager can get stuck with 0 replicas after control plane migration

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#4773]
**How to categorize this issue?**

/area control-plane-migration
/kind bug
/priority 3

**What happened**:
Triggered control plane migration for an azure cluster, which seemed to finish successfully, but then I noticed that the VPN tunnel pod in the shoot never comes up. The reason for that is that the kube-controller-manager in the shoot's control plane had 0 replicas.

The issue seems to come during the `restore` operation and from this code: https://github.com/gardener/gardener/blob/b12f41152e867e6c0678311c9a82400ea7f0e5e6/pkg/operation/botanist/kubecontrollermanager.go#L99-L106
It will check that the operation is not `create`, and that the shoot isn't being hibernated or woken up and return the already existing replicas count for the kube-controller-manager deployment. Since it is a `restore` procedure and the kube-controller-manager has not yet been created in the new control plane, the replicas are 0.
The reason that we have not seen this issue before is that something else seems to be waking up the kube-controller-manager after it is initially created with 0 replicas.

**What you expected to happen**:
The kube-controller-manager to be created with 1 replicas when the shoot is being restored and is not hibernated.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot cluster and migrate it. Observe that during the restore phase the kube-controller-manager is initially created with 0 replicas and later on scaled to 1.

**Anything else we need to know?**:

**Environment**:

- Gardener version: latest master version
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: GCP
- Others:

**Comment by timebertt** [comment]
> The reason that we have not seen this issue before is that something else seems to be waking up the kube-controller-manager after it is initially created with 0 replicas.

I guess, that "something" would be https://github.com/gardener/dependency-watchdog :)

**Comment by plkokanov** [comment]
> I guess, that "something" would be https://github.com/gardener/dependency-watchdog :)

Thanks, was probably going to spend some time until I remember that the dependency-watchdog component also manages some of the control-plane deployments replicas :).
