### ISSUE TITLE
Seed conditions are not copied to Shoot if parent gardenlet is unavailable

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4776]
**How to categorize this issue?**

/area robustness ops-productivity
/kind enhancement

**What would you like to be added**:

Currently, the gardenlet's shoot care controller copies the Seed conditions over to the Shoot status, if the shoot is registered as a ManagedSeed: https://github.com/gardener/gardener/blob/0320bb0241020ad19a0f0b536d8f490a8feaaf39/pkg/gardenlet/controller/shoot/shoot_care_control.go#L328-L338

However, when the parent gardenlet is unavailable, the shoot conditions can become outdated. 

We should either
- make sure, that the shoot conditions always provide the same information as the seed conditions (i.e. move the logic to GCM)
- or drop copying the seed conditions to shoots entirely

**Why is this needed**:

If the conditions are not up to date, they don't provide any benefit at all over looking directly at the seed conditions.

**Comment by timebertt** [comment]
Monitoring will be affected by this as well if we decide for option 2.
cc @wyb1 @istvanballok

**Comment by wyb1** [comment]
Option 2 should not be an issue since we have the metric `garden_seed_condition`. Some components/alerts may still use the `garden_shoot_condition` metric to evaluate the condition of a shooted seed but the migration *should* be relatively simple.
