### ISSUE TITLE
Deletion sometimes stuck for Shoots with invalid DNS Credentials

### ISSUE THREAD

**Issue by grolu** [gardener/gardener#4778]
**How to categorize this issue?**

/kind bug
/priority 3

**What happened**:
I created several clusters for which I configured DNS providers with invalid credentials. Sometimes those clusters can no longer be deleted. Deletion fails and cluster gets stuck in `Delete Failed` state. Retry operation also does not solve the problem.

```
Flow "Shoot cluster deletion" encountered task errors: [task "Deploying additional DNS providers" failed: retry failed with context deadline exceeded, last error: 1 error occurred:
	* Error while waiting for DNSProvider shoot--lukas--test1/aws-route53-other-secret to become ready: state Error: cannot get hosted zones: InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: d4f0a8d9-b24c-4c58-b038-74fc2216df13

]
```

```
task "Deploying additional DNS providers" failed: retry failed with context deadline exceeded, last error: 1 error occurred:
	* Error while waiting for DNSProvider shoot--lukas--test1/aws-route53-other-secret to become ready: state Error: cannot get hosted zones: InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: d4f0a8d9-b24c-4c58-b038-74fc2216df13

Delete Failed
Invalid cloud provider credentials.
```

**What you expected to happen**:
Deletion should not fail as there are no resources that require cleanup (credentials have been invalid all the time, so no DNS records have been created).

**How to reproduce it (as minimally and precisely as possible)**:
Create invalid DNS credentials. Use them for a new shoot. Delete shoot. However, the issue does not occur always but most of the time.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.33.0-dev
- Kubernetes version (use `kubectl version`): 1.21.3
- Cloud provider or hardware configuration: aws
- Others:

**Comment by timuthy** [comment]
@MartinWeindel @mandelsoft for that requirement we need to know if there is really no cleanup required because credentials could also be invalided at a later point.
What would be a reliable way to figure out if the DNS controller has ever created an entry? Checking `status.targets`?

**Comment by MartinWeindel** [comment]
@timuthy asked:

> @MartinWeindel @mandelsoft for that requirement we need to know if there is really no cleanup required because credentials could also be invalided at a later point.
What would be a reliable way to figure out if the DNS controller has ever created an entry? Checking status.targets?

There are either no `DNSEntry` objects in the namespace at all or the existing `DNSEntries` contain no `status.targets` field

**Comment by timuthy** [comment]
Thanks @MartinWeindel. I deleted the comment because I realized afterwards that the question is not relevant. I think we can then finalize the failing `DNSProvider`s if there are no `DNSEntries`.
