### ISSUE TITLE
Restore phase of control plane migration can fail for Azure AVSet clusters

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#4793]
**How to categorize this issue?**

/area control-plane-migration
/kind bug
/priority 3

**What happened**:
Triggered control plane migration for an azure availability set cluster in the westus2 region. During the restore phase, the following error occurred:
```
flow "Shoot cluster reconciliation" encountered task errors: [task "Waiting until shoot infrastructure has been reconciled" failed: Error while waiting for Infrastructure shoot--faas-live--us20/us20 to become ready: error during reconciliation: Error restoring infrastructure: failed to apply the terraform config: Terraform execution for command 'apply' could not be completed:

* compute.AvailabilitySetsClient#Delete: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="OperationNotAllowed" Message="Availability Set 'shoot--faas-live--us20-avset-workers' cannot be deleted. Before deleting an Availability Set please ensure that it does not contain any VM."]
```

**What you expected to happen**:
The restore phase to complete successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Initially (before migration) the terraform state was saved with the following configuration for the availability set:
```
"attributes": {
  "id": "<some-id>",
  "location": "westus2",
  "managed": true,
  "name": "shoot--<namespace>--<shoot>-avset-workers",
  "platform_fault_domain_count": 2,
  "platform_update_domain_count": 5,
  "proximity_placement_group_id": null,
  "resource_group_name": "shoot--<namespace>--<shoot>",
  "tags": {},
  "timeouts": null
}
```

However, during restoration the `<shoot>.infra.tf-config` config map had the following configuration for availability sets:
```
resource "azurerm_availability_set" "workers" {
  name                         = "shoot--faas-live--us20-avset-workers"
  location                     = "westus2"
  resource_group_name          = azurerm_resource_group.rg.name
  platform_update_domain_count = "5"
  platform_fault_domain_count  = "3"
  managed                      = true
}
```

Notice that the `platform_fault_domain_count` in the terraform config is 3, whereas in the state it is 2. I guess this caused terraform to want to delete the existing avset and recreate it.

I checked the CloudProfile and found out that for the westus2 region the `faultDomainCount` is 3, and that is why in the new terraform config in the new seed `platform_fault_domain_count  = "3"` __So perhaps this was changed at some point?__

During reconciliation the`faultDomainCount` is saved in `infrastructure.status.providerStatus.availabilitySets[].countFaultDomain`. So in future reconciliations the shoot can still keep its existing configuration for faultDomainCount by retrieving it from the infra's status.

However, during the restoration phase the providerStatus is not added to the newly created infrastructure resource on the new seed cluster, and the `faultDomainCount` is retrieved from the CloudProfile where it has a different value.

**Environment**:

- Gardener version: 1.32.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: Azure
- Others:

**Comment by plkokanov** [comment]
If the infrastructure has already been reconciled once and created, on subsequent reconciliations when terraform values are computed, the `infrastructure.Status.ProviderStatus` field exists and the `countFaultDomains` value is extracted from there instead of the `CloudProfile`. 
However, during the restore operation the `infrastructure.Status.ProviderStatus` filed is nil, which means that the  `countFaultDomains` value will be extracted from the `CloudProfile`, which could have changed

I've come up with two ways to do it but would like to check with @dkistner @kon-angelo and @rfranzke which would be the better one:

1. Simply save the providerStatus in the `infrastructure.Status.State` field, together with the terraform state, then load it from the `infrastructure.Status.State` field at the beginning of the restoration. You can check an example change here:
https://github.com/plkokanov/gardener-extension-provider-azure/commit/0ffdf3b15c40546f4201fe307e9a8036dc693fd4
This change is backwards compatible, but it will require a reconciliation of the infra resource so that the `infra.Status.State` field is updated. (We could store only the availabilitySets from the providerStatus which is what is required to get the countFaultDomain information)

2. Extend our terraform library with an additional function e.g. `GetOutputVariablesFromState(stateConfigMap []byte, variables ...string) (map[string]string, error)`. Then use this method during the restoration operation of the infrastructure resource to create the provider status from the available terraform state data, and assign it to the infrastructure. Example change: https://github.com/plkokanov/gardener-extension-provider-azure/commit/6a4a369bd4df5a973ac5ed7b88e5c0d45cad552c
This change is also backwards compatible and does not require a reconciliation of the infra resource. However, a few lines of code in the existing reconciliation logic when computing the terraform variables are worrying me: https://github.com/gardener/gardener-extension-provider-azure/blob/c7ad350b15fb7d48782d09edea9458126c020dce/pkg/internal/infrastructure/terraform.go#L605-L612
At the start of the restore operation, when we try to compute the provider status values from the terraform state [here](https://github.com/plkokanov/gardener-extension-provider-azure/blob/6a4a369bd4df5a973ac5ed7b88e5c0d45cad552c/pkg/controller/infrastructure/actuator_restore.go#L43), the `infrastructure.Status.ProviderStatus` field will be nil, and those lines will not get executed. (we would still get the correct countFaultDomain value from the terraform state though)

**Comment by rfranzke** [comment]
+1 for the first approach
