### ISSUE TITLE
API server dashboard panel with duration of conversion webhooks

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4794]
**How to categorize this issue?**

/area monitoring ops-productivity
/kind enhancement

**What would you like to be added**:

API Server monitoring dashboard panel showing the duration of [conversion webhooks](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-conversion) based on metric `apiserver_crd_webhook_conversion_duration_seconds` (histogram).

**Why is this needed**:

If shoot owners are using CRD conversion webhooks, they and operators want to see how well they perform to analyze whether they have an impact on general cluster performance.

**Comment by timebertt** [comment]
cc @wyb1 @istvanballok

**Comment by rfranzke** [comment]
@wyb1 @istvanballok @rickardsjp WDYT about this one?
