### ISSUE TITLE
Allow creation of CloudProfile containing expirationDates in the past

### ISSUE THREAD

**Issue by lotharbach** [gardener/gardener#4797]
**How to categorize this issue?**
 
/area usability
/area ops-productivity
/kind enhancement
/priority 3

**What would you like to be added**:
I would like to create CloudProfiles containing versions with expirationDate set to the past, even if it does not make sense.

**Why is this needed**:
Checking all expirationDates against the current date might be actionable feedback for a human kubectl user, but it causes idempotence: what I was able to apply yesterday, I'm no longer able to apply today or tomorrow. This reduces our ability to share, reuse, template and merge CloudProfile yamls , and apply them automatically an unmodified across installations/stages with GitOps tooling or similar pipelines.

**Comment by danielfoehrKn** [comment]
Sounds ok to me &  should be an easy fix in the validation logic for the CloudProfile.
@gesslein is this something you would like to work on?
