### ISSUE TITLE
[GRM] Cache breaks when managed CRD gets deleted

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#4802]
**How to categorize this issue?**

/area usability
/kind bug
/priority normal

**What happened**:
When the GRM manages a `CustomResourceDefinition` and it's deleted later on then its logs will be flooded with e.g.

```
E0622 14:28:52.025347       1 reflector.go:123] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:204: Failed to list *v1beta2.VerticalPodAutoscaler: the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)
```

**What you expected to happen**:
GRM does stop watching the respective CRD.

**How to reproduce it (as minimally and precisely as possible)**:
Let GRM manage a CRD and then delete it.

**Anything else we need to know?**:

**Environment**:

- Gardener-Resource-Manager version: `master`
- Kubernetes version (use `kubectl version`): `v1.18.0`

**Comment by timebertt** [comment]
Let's close this, I don't see how this can be fixed and the consequences are rather harmless (flooded logs) but no actual bug or anything, I assume.
/close
