### ISSUE TITLE
[GRM] Introduce modes

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#4804]
**How to categorize this issue?**

/area control-plane
/kind enhancement

**What would you like to be added**:
In the scope of gardener/gardener-resource-manager#74, @mandelsoft @timebertt @rfranzke discussed about different use cases and modes the GRM should support in the future. We put together the following proposal:

- [x] Add `resources.gardener.cloud/origin` to deployed resources in order to identify the responsible GRM and ManagedResource. (@mandelsoft will take over)

```
resources.gardener.cloud/origin: <Origin-ID>/<Namespace>/<Name>
```

- [ ] Add support for `resources.gardener.cloud/mode` annotation to be added to managed resources:
```
- "Ignore"
  - Removes resource from state, no action in cluster, does nothing else.
  - Use case: Move a resource from ManagedResource A -> B.

- "EnsureExists"
  - Creates resource if not available.
  - No Update.
  - Deletes resource if deleted from ManagedResource.
  - Use case: Create resource which can be adjusted by shoot owner but still can be deleted.

- "Keep"
  - Creates resource if not available
  - Updates resource
  - No Deletion
  - Use case: Create a default configuration, e.g. CoreDNS config, in shoot cluster.

- "FallBack" (default mode)
 - Creates resource if not available.
 - Updates resource if responsible as per `resources.gardener.cloud/origin` annotation.
 - Deletes resource if responsible as per `resources.gardener.cloud/origin` annotation.
 - Use case: Avoid interference of multiple GRMs targeting the same cluster, e.g. shooted seeds.
```

- [ ] Remove `"resources.gardener.cloud/ignore"` and `"resources.gardener.cloud/keep-object"` in a future version.

**Comment by rfranzke** [comment]
Do we still plan to do this? TBH, I don't think it's very important and what we have today seems to be good enough (there is not any pull on this whatsoever). Let's close it?

**Comment by timuthy** [comment]
I agree @rfranzke. Let's close this issue, the idea itself won't get lost in case we'll meet this or a similar requirement again in the future.
/close
