### ISSUE TITLE
☂️ Integration tests for resource-manager

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4805]
**How to categorize this issue?**

/area testing dev-productivity
/kind enhancement

**What would you like to be added**:

We need several [integration tests (envtests)](https://github.com/gardener/gardener/blob/master/docs/development/testing.md#integration-tests-envtests) for gardener-resource-manager. There are a few integration tests for some of the more recent features (e.g. tokenrequestor), but the core functionality of resource-manager is not tested at all so far.

Basically, we should add integration tests for all controllers covering a reasonable amount of cases:

- [x] ManagedResource controller, basic case: create, update, delete ManagedResources; condition `ResourcesApplied` is correctly maintained: https://github.com/gardener/gardener/pull/5610 (@kris94 @plkokanov)
- [x] ManagedResource controller, condition `ResourcesHealthy` is correctly set to `Progressing`, if set of resources is changed: https://github.com/gardener/gardener/pull/5772 (@acumino)
- [x] ManagedResource controller, modes/annotations on resource: ignore, delete on invalid update, keep object: https://github.com/gardener/gardener/pull/5772 (@acumino)
- [x] ManagedResource controller, different classes: responsibility, predicates, finalizers, etc.: https://github.com/gardener/gardener/pull/5772 (@acumino)
- [x] ManagedResource controller, reconcile on operation annotation: https://github.com/gardener/gardener/pull/5772 (@acumino)
- [x] ManagedResource controller, preserve replicas/resources: resources with annotations `resources.gardener.cloud/preserve-{replicas,resources}`, resources scaled by HPA/VPA/HVPA: https://github.com/gardener/gardener/pull/5772 (@acumino)
- [x] ManagedResource controller, ignore case (https://github.com/gardener/gardener/pull/5556)
- [x] Secret controller: finalizer, reconciliation on secret change, etc.: https://github.com/gardener/gardener/pull/5687 (@acumino)
- [x] Health controller, condition `ResourcesHealthy` is correctly maintained: healthy/missing/unhealthy objects, not set if MR is currently being applied: https://github.com/gardener/gardener/pull/5469 (@timebertt)
- [x] Garbage collector, basic case: unreferenced resources are deleted, referenced resources are kept: https://github.com/gardener/gardener/pull/5534 (@rfranzke)

**Why is this needed**:

With the growing number of features of resource-manager, it becomes imperative to have automated tests for all of them to not introduce regressions / miss any important case, when performing changes to the codebase.
There are also not many unit tests for core functionality of resource-manager, so there should be at least some integration tests covering the base cases.
ref https://github.com/gardener/gardener/issues/5357

**Comment by timebertt** [comment]
/assign
for the health controller test

**Comment by timebertt** [comment]
/unassign
Test for the health controller is added in https://github.com/gardener/gardener/pull/5469.
It can be used as a template for other cases in this issue.

**Comment by rfranzke** [comment]
/assign
for the garbage collector test

**Comment by rfranzke** [comment]
/unassign
Test for the garbage collector is added in https://github.com/gardener/gardener/pull/5534
