### ISSUE TITLE
Allow expansion for `.spec.networking.nodes` CIDR

### ISSUE THREAD

**Issue by kon-angelo** [gardener/gardener#4834]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority 3

**What would you like to be added**:

Allow the expansion of the `.spec.networking.nodes` CIDR that is currently validated as an immutable field. 

**Why is this needed**:

Certain providers (e.g. Azure) do allow the expansion of their VPC. Users would like to take advantage of that feature to create more address space for new nodes, new subnets etc. This is currently not possible because the immutability of the nodes CIDR creates a big limitation on the conditions for such expansion. 

Generally the extensions check the following condition for the network ranges:
```
VPC >= nodes >= workers

*workers = the subnet(s) where the VMs are created.
```
That means that even if we manage to expand the network from infrastructure perspective the available addresses are always constricted by the nodes range.

Current usage of the nodes field:
+ I am largely unaware of any meaningful usage inside Gardener (the main repo) of this field. Aside from the valid-CIDR and the immutability checks.
+ The extensions use it for validation as mentioned above.
+ Calico uses it to detect the correct network interface depending on the configuration (@DockToFuture | @ScheererJ 
 correct me if I am wrong).

The fact that it is only an expansion means that clusters should not be affected at all. 

Furthermore, it is not necessary for the immutability check to be completely removed and instead it can be moved downstream. The extensions and in particular those that do not support such change can adopt it accordingly.

**Comment by kon-angelo** [comment]
I had the chance to dive a little bit deeper into that. First of all, looking for uses of the field in inside all repos I could trace the users of this field as follows:
+ gardener
+ calico extension
+ all provider extensions

Notable uses for the other repos (non-gardener/gardener):
+ The vsphere extension is the only one relying on this field to create the subnet for the nodes. In comparison all the other extensions generally need to have a range explicitly mentioned in their providerInfrastructureConfig.
+ Alicloud is perfoming it's own immutability check for the nodes network [ref](https://github.com/gardener/gardener-extension-provider-alicloud/blob/72fa8bf20fe4de40f0dee6d1305f72820905a05f/pkg/apis/alicloud/validation/shoot.go#L47)
+ Calico uses it to detect the correct network interface in case multiple exist [ref](https://github.com/gardener/gardener-extension-networking-calico/blob/a55ea43d3b5eeace343bef091d22de4f1eacf361/pkg/controller/actuator_reconcile.go#L104). I actually tried to see if updating the nodes had any effect on calico and I could see that the calico pods were reconciliating correctly with the new configuration and no issue whatsoever. 

Gardener uses the field mainly to avoid overlapping ranges between seeds and shoots. A side-effect of the expansion is that it reduces the available space for the other party and additional checks are needed to validate that previously established invariants are still holding. That means that after the change the shoot must remain disjoint from its seed. Additionally in the case of a managed seed, it must be verified against all its existing shoots it hosts. Therefore it is best if the operation is not allowed for managed seeds (in the beginning at least).
 
 On that topic, Gardener already supports setting the value dynamically by setting [infrastructureStatus.NodesCIDR field](https://github.com/gardener/gardener/blob/7251939d365f42d137f3ca71812e82f797172678/pkg/apis/extensions/v1alpha1/types_infrastructure.go#L90) which currently is not used by any extension at all. I tested it with modified provider workflows and it worked perfectly. However due to the immutability check as per the original issue, it can not be updated after assigned a value so it is not truly dynamic. The changes in the shoot reconciliation workflow from using this field are mostly related to network policies that need to be reapplied after the infrastructure has been reconciled.

As such to support the expansion I would recommend the following first steps:
+ Change the immutability check in g/g to an expansion check (check whether the new value is exactly a superset of the old) as a baseline.
+ Add additional validation in g/g so the field is immutable only for managedseeds. 
+ Validate shoots so that they don't overlap with their existing seeds (this is already in place).
+ Adopt immutability checks as a first step in all extensions that make use of the field to ensure same as current behavior.

**Comment by ebensom** [comment]
/remove-lifecycle rotten
/reopen

The Kyma project would also welcome if this enhancement was implemented. 
Unfortunately we configured `spec.networking.nodes` to 10.250.0.0/19 and assigned the whole subnet range to the single zone workers CIDR (this is the case for both AWS and Azure Shoots).

Now we are about to support the upgradeability of Kyma runtimes from single zone to multi-zone, and for that, the changeability of `.spec.networking.nodes` is a blocker enhancement. If expansion of the field was possible, we would be able to support it like:

1. For AWS, we would patch the shoot `.spec.networking.nodes` from `10.250.0.0/19` to `10.250.0.0/16` , and extend the `.spec.provider.infrastructureConfig.zones` with a 2nd (and 3rd upon request) zone, where the worker/internal/public CIDR doesn't overlap with zone 1, and all come as a sub-CIDR of `10.250.0.0/16`
2. For Azure, we would patch the shoot `.spec.networking.nodes` from `10.250.0.0/19` to `10.250.0.0/16`, and transform `.spec.provider.infrastructureConfig` to have dedicated subnets per zone, with NAT gateway enabled per zone. The subnets would all come from `10.250.0.0/16` and the first zone would have the legacy `10.250.0.0/19` sub-CIDR.

@kon-angelo Would it be possible to increase the priority of this enhancement?

**Comment by jackygui** [comment]
@kon-angelo, any plan to release this enhancement? As we have discussed months before that support the multi-AZ for NAT gateway in Azure HC infrastructure.

**Comment by pbochynski** [comment]
We still wait for the issue to enable the upgrade of existing clusters to multi-zone setup like @ebensom mentioned in the previous comment.

**Comment by kon-angelo** [comment]
We want to progress with this topic and support the nodes CIDR block expansion for supported infrastructures. In order to reach the desired outcome we need changes for both gardener and the provider extensions. The following plan outlines the necessary changes:

- [ ] Adopt the Node CIDR immutability check (or at least an expansion check for supported infras) for all provider extensions. This will give us feature parity with the current version while allowing us to remove the check from Gardener.
   - [ ] AWS
   - [ ] GCP
   - [ ] Azure
   - [ ] Openstack
   - [x] Alicloud
   - [x] VSphere
- [x] Deprecate/remove the Node CIDR immutability check from g/g. This is dependant on all provider extensions having adopted the immutability check  -> https://github.com/gardener/gardener/pull/7368
- [x] Allow VPC expansion for supported infrastructures. Unfortunately not VPC expansion does not work equally well for all infra providers. For some like Azure it is easy to resize the network size, but for others like AWS it is only possible to add secondary ranges but not mutate the primary CIDR blocks. For now we will focus supporting the former case. 
   - [x] Azure
   - [x] GCP
- [x] Allow Node CIDR expansion from provider extensions. The current expected invariants like ensuring that VPC >= Node CIDRs should remain as is. For scenarios like "bring-your-own-VPC/VNet" where the VPC range is not known at admission time, we should perform additional checks during `config-validator` pre-hook of the infrastructure reconciliation.
   - [x] Azure
   - [x] AWS
   - [x] GCP
