### ISSUE TITLE
Extended RBAC for Robot user

### ISSUE THREAD

**Issue by linuxbsdfreak** [gardener/gardener#4846]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority 2

**What would you like to be added**:
GET and LIST in RBAC for the Robot user for customresourcedefinitions.apiextensions.k8s.io 

**Why is this needed**:

We are using Terraform to launch Shoots using the Robot K8s Creds using the https://github.com/hashicorp/terraform-provider-kubernetes provider.  The K8s Terraform Provider uses list to look up which CRD contains the schema for the CR that is being currently managed, and  GET to retrieve the schema from that CRD. 

**Technical explanation from Hashicorp**

In the earlier alpha k8s provider  version was not extracting schema directly from the CRD object, but rather from the /openapi/v2 endpoint on the API server (which isn't subject to authz). We stopped doing that because that schema is not precise: the CRD contains OpenAPIv3 which then gets approximated to OpenAPIv2 by the API server for exposing on that endpoint.
This was causing the structure of some CRs to not be consistent across TF operations and would result in "inconsistent state after apply" errors. That's the reason we now extract OpenAPIv3 schema directly from CRDs.

**Comment by stoyanr** [comment]
There is no CRD for shoots. Even if we add get and list permissions for CRDs for project members (the robot user is simply a project member), I don't see how this could help. Shoots are resources handled by the Gardener API server and so they don't have a CRD.

**Comment by rfranzke** [comment]
I think what @stoyanr makes sense and there is nothing to do on our end, so
/close
