### ISSUE TITLE
Ensure managed resource deletion by GRM doesn't fail due to pods stuck in `Terminating` state

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener#4853]
**How to categorize this issue?**

/area ops-productivity robustness
/kind enhancement
/priority 3

**What would you like to be added**:

When managed resources are deleted by the GRM, sometimes what happens is that such a resource can't be deleted because e.g. one of the deployments it tries to delete can't be deleted, because some of its pods are stuck in `Terminating` state due to being unable to mount configmaps or secrets that are themselves part of the managed resource and have been already deleted.

What you typically see in such situations:

```
$ k describe managedresource runtime-gvisor-zrlr6 -n garden | grep Message
    Message:               Could not clean all old resources: 1 error occurred: deletion of old resource "apps/v1/Deployment/extension-runtime-gvisor-zrlr6/gardener-extension-runtime-gvisor" is still pending
```

One fo the pods of the above deployment is stuck in `Terminating` state with the following errors:

```
Warning  FailedMount  16m (x289 over 9h)    kubelet  MountVolume.SetUp failed for volume "imagevector-overwrite" : configmap "gardener-extension-runtime-gvisor-imagevector-overwrite" not found
Warning  FailedMount  2m30s (x296 over 9h)  kubelet  MountVolume.SetUp failed for volume "gardener-extension-runtime-gvisor-token-t224f" : secret "gardener-extension-runtime-gvisor-token-t224f" not found
```

And the relevant messages from the GRM log:

```
{"level":"info","ts":"2021-10-15T07:15:20.464Z","logger":"controller-runtime.manager.resource-controller","msg":"Starting to delete ManagedResource","object":"garden/runtime-gvisor-zrlr6"}
{"level":"info","ts":"2021-10-15T07:15:20.464Z","logger":"controller-runtime.manager.resource-controller","msg":"Deleting","resource":"v1/ConfigMap/extension-runtime-gvisor-zrlr6/gardener-extension-runtime-gvisor-imagevector-overwrite"}
{"level":"info","ts":"2021-10-15T07:15:20.464Z","logger":"controller-runtime.manager.resource-controller","msg":"Deleting","resource":"autoscaling.k8s.io/v1beta2/VerticalPodAutoscaler/extension-runtime-gvisor-zrlr6/gardener-extension-runtime-gvisor-vpa"}
{"level":"info","ts":"2021-10-15T07:15:20.464Z","logger":"controller-runtime.manager.resource-controller","msg":"Deleting","resource":"v1/ServiceAccount/extension-runtime-gvisor-zrlr6/gardener-extension-runtime-gvisor"}
{"level":"info","ts":"2021-10-15T07:15:20.464Z","logger":"controller-runtime.manager.resource-controller","msg":"Deleting","resource":"apps/v1/Deployment/extension-runtime-gvisor-zrlr6/gardener-extension-runtime-gvisor"}
{"level":"info","ts":"2021-10-15T07:15:20.529Z","logger":"controller-runtime.manager.resource-controller","msg":"Deletion is still pending","object":"garden/runtime-gvisor-zrlr6","err":"Could not clean all old resources: 1 error occurred: deletion of old resource \"apps/v1/Deployment/extension-runtime-gvisor-zrlr6/gardener-extension-runtime-gvisor\" is still pending"}
```

We should investigate how to prevent such failures. We could perhaps introduce some "dependency" mechanism between the resources, ensuring that they are created / deleted in certain order. Or we could introduce some forceful killing of pods that are found in such state after the deletion of a deployment (statefulset, daemonset) has failed a certain number of times.

Some more observations:
* The order in which resources are applied / deleted by the GRM appears to be random. In practice they are all deleted at the same time, without waiting for any deletion to complete before proceeding with the next one.
* This error happens only rarely, which suggests that `kubelet` would in general not mind deleting a pod after its mounted secrets / configmaps have been deleted. However, there are obviously situations in which this happens - perhaps if a pod was just starting when the managed resource deletion occurred and the configmap / secret could not be properly mounted yet.

**Why is this needed**:

**Comment by stoyanr** [comment]
@timebertt Suggested to try to reproduce the `kubelet` behavior outside of GRM, as it may be due to an upstream issue.

**Comment by timebertt** [comment]
Let's close this issue as it has been open for some time without more occurrences or new investigation details.
/close
