### ISSUE TITLE
Make kubelet parameter `--serialize-image-pulls` configurable

### ISSUE THREAD

**Issue by anbrsap** [gardener/gardener#4855]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority 3

**What would you like to be added**:

In a shoot manifest some kubelet parameters can already be configured via `spec.kubernetes.kubelet.*`.

There should be an additional field `serializeImagePulls` with boolean value that directly translates into kubelet parameter `--serialize-image-pulls`.

**Why is this needed**:

Pulling images in parallel improves pod startup performance.

**Comment by rfranzke** [comment]
I think changes similar to #4282 would be needed. Any contribution is welcome!
