### ISSUE TITLE
Add Support for Maintenance Mode 

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener#489]
What do you think about adding a maintenance mode/switch into Gardener in which we don't allow any creation/deletion of shoots?

Why?
To prevent inconstancy when we do a controlled restore of a cluster we currently might run into a situation where our backup (even the incremental one) might miss objects which have been created/deleted. In addition any infrastructure related jobs (creation or reconcile) should also be put on hold to prevent inconsistency.

**Comment by rfranzke** [comment]
Not exactly sure about the use-case, but wouldn't a `kubectl -n garden scale deploy/gardener-controller-manager --replicas=0` suffice to achieve the same?

**Comment by afritzler** [comment]
Well that will work for us, however is combined with a downtime experience for the user. I was thinking about something were we also tell the user in the dashboard via a notification or something - and scaling down the controller in the background.

**Comment by rfranzke** [comment]
OK, but how do you envision this? Is that really something that needs to be build into Gardener? Can you elaborate on how that could be implemented?

**Comment by afritzler** [comment]
Ok, I guess we can close this one for now since there is no high prio need for that.
