### ISSUE TITLE
Creation of Shoot with name "gardener" fails when UseDNSRecords=true

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4895]
**How to categorize this issue?**

/area quality
/kind bug
/priority 3

**What happened**:
Cannot create a Shoot with name "gardener" when `UseDNSRecords` feature gate is enabled.
Currently there is a name collision between the Secret that gardenlet creates for the internal kubeconfig (its name is "gardener-internal") and the Secret that is created by gardenlet for the internal DNSRecord (its name is "<shoot-name>-internal"). When the Shoot name is "gardener", then both Secret names are "gardener-internal" which leads the Shoot creation to fail.

**What you expected to happen**:
To be able to create a Shoot with name "gardener".

**How to reproduce it (as minimally and precisely as possible)**:
0. Make sure that the `UseDNSRecords` feature gate of gardenlet is enabled.

1. Create a Shoot with name "gardener".

2. Make sure that the Shoot creation fails with

```yaml
  lastErrors:
    - description: >-
        task "Initializing connection to Shoot" failed: retry failed with
        context deadline exceeded, last error: error creating new ClientSet for
        key "garden-foo/gardener": the secret does not contain a field with
        name 'kubeconfig'
      taskID: Initializing connection to Shoot
```

The "gardener-internal" Secret data looks like:

```yaml
data:
  AWS_ACCESS_KEY_ID: <omitted>
  AWS_REGION: <omitted>
  AWS_SECRET_ACCESS_KEY: <omitted>
```

**Environment**:

- Gardener version: v1.34.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
@stoyanr We should have named the secrets `dns-{internal,external}` or something similar.
Renaming/migration should still be possible without a big hassle, I assume.
