### ISSUE TITLE
taint support in worker groups

### ISSUE THREAD

**Issue by bergerx** [gardener/gardener#492]
We want to dedicate some worker groups to some namespaces (more specifically we want pods in monitoring namespace to run on a dedicated worker group)

We are planning to use PodNodeSelector and PodTolerationRestriction Admission Controllers (implemented here https://github.com/gardener/gardener/issues/258) to restrict the pod in the namespace to a specific worker group by using worker group labels.

These primitives help us to restrict the pods in the namespace to the worker group (openshift uses it already, see an example here: https://docs.openshift.com/container-platform/3.6/admin_guide/scheduling/pod_placement.html#controlling-pod-placement-projects) but doesn't help to prevent pods in other namespaces to be placed to the dedicated worker group. We need to use taints for that, but tainting nodes in kubernetes is not declarative.

Here is an example scenario:
* you have a worker group named `monitoring` in a shoot 
* gardener will automatically set `worker.garden.sapcloud.io/group=monitoring` label on nodes in worker group
* you run `kubectl taint node -l worker.garden.sapcloud.io/group=monitoring  worker.garden.sapcloud.io/group=monitoring:NoSchedule` to set the taint on the monitoring worker group nodes
* then you scale up the worker group, a new node will join to the cluster
* but new node won't have the taint

Because the `kubectl taint` command is imperative and taint definitions are not declarative, it will force us to run a `kubectl taint` command each time the related worker group is scaled out. A better option is to be able to set taints on a worker group (e.g in here `shoot.spec.cloud.*.workers`).

As an example you can see that GKE now supports this feature: https://cloud.google.com/kubernetes-engine/docs/how-to/node-taints#creating_a_node_pool_with_node_taints

**Comment by bergerx** [comment]
Just saw this related issue on mcm https://github.com/gardener/machine-controller-manager/issues/174

**Comment by vlerenc** [comment]
Right, closing this here, because it will be covered by MCM.
