### ISSUE TITLE
Invalid memory address or nil pointer dereference in ETCD component

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#4964]
**How to categorize this issue?**

/area control-plane
/kind bug
/exp beginner

**What happened**:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1e37097]

goroutine 7610 [running]:
github.com/gardener/gardener/pkg/operation/botanist/component/etcd.(*etcd).Deploy(0xc0013c9c00, 0x292ddb0, 0xc001b05c80, 0x1, 0xc000bdc768)
        /home/vpnachev/go/src/github.com/gardener/gardener/pkg/operation/botanist/component/etcd/etcd.go:198 +0x337
github.com/gardener/gardener/pkg/utils/flow.Parallel.func1.1(0xc001eb9ee4, 0xc001f5e840, 0xc001b78510, 0x292ddb0, 0xc001b05c80)
        /home/vpnachev/go/src/github.com/gardener/gardener/pkg/utils/flow/taskfn.go:132 +0x66
created by github.com/gardener/gardener/pkg/utils/flow.Parallel.func1
        /home/vpnachev/go/src/github.com/gardener/gardener/pkg/utils/flow/taskfn.go:130 +0x105
```

**What you expected to happen**:
Optional fields to be validated before to be used here https://github.com/gardener/gardener/blob/29ffac5ed724458803b7748800e9de6f07c84f0a/pkg/operation/botanist/component/etcd/etcd.go#L198

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.34.0, 97e2e316891bfad3c7e381d7fea7d068f7453aa9
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
Seen also with `gardenlet@v1.34.0`
