### ISSUE TITLE
Cloud config downloader is missing the API server address with DNS-less seed clusters

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#4968]
**How to categorize this issue?**

/area usability robustness
/kind bug

**What happened**:
I have created a shoot cluster in a landscape where
- There is no internal domain secrets
- The DNS is disabled in the seed settings, `seed.spec.settings.shootDNS.enabled=false`
- It is irrelevant, but I also made sure the gardenlet is started with `APIServerSNI=false`

Effectively, the public IP of the `kube-apiserver` service now has to be used by all clients running outside the seed, e.g. the kubelet. Looking for the value of the server in the OSC resource reveal it is not set there for any of the three OSC downloaders I have:
```bash
$ k get osc -o json | jq  '.items[] | select(.spec.purpose=="provision") | .spec.files[] | select(.path=="/var/lib/cloud-config-downloader/credentials/server")| .content.inline.data | @base64d' -r
https://
https://
https://
```

**What you expected to happen**:
The OSC resource to have the public address of the API server properly set in DNS-less environments.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: 29ffac5ed724458803b7748800e9de6f07c84f0a
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
Thanks! Managed to reproduce it.
/accepted
