### ISSUE TITLE
Add nameserver to worker nodes

### ISSUE THREAD

**Issue by thonacker** [gardener/gardener#4973]
**How to categorize this issue?**

/area ops-productivity
/area usability
/kind enhancement

**What would you like to be added**:

It shoudld be possible to add DNS nameserver via Gardener to worker nodes. Currently we need to apply DaemonSets to change them.

**Why is this needed**:

Hyperscalers such as MS Azure and GCP are connected to internal networks. To resolve internal services like Docker registries and GitHub it would be a time saver to be able to add nameservers via Gardener to worker nodes.

Internal ticket:
https://${Internal_GitHub}/kubernetes-canary/issues-canary/issues/1418

**Comment by rfranzke** [comment]
IMO there are too many examples where end-users might want to change specific settings on their nodes and Gardener cannot take care of all of them. I'd say that the `DaemonSet` approach is a good one.
