### ISSUE TITLE
Hibernate/Wake-Up Clusters

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#50]
# Story
- As user/operator I want to hibernate clusters, so that I can save costs when I don't need the clusters anymore/temporarily.

# Motivation
We have seen that users try to hibernate their clusters to save costs (we were also asked how to do that). That's actually great and we haven't seen this form of responsibility ever elsewhere.

However, users have no means at present to do so in a clean way. One user manually tweaked the ASG, something that turned off all nodes and hence also the cluster auto-scaler, which turned the cluster into NotReady in our alert dashboard/flagged the cluster, which again created unnecessary ops effort. With the machine controller manager that path will be blocked (we will grasp more control of the cluster to provide our SLAs) and we will revert or rather make such tweaks impossible.

# Acceptance Criteria
- [x] Cluster can be scaled down to 0 machines across all pools
- [x] No false monitoring alerts fired

# Implementation Proposal
Use the machine controller manager to achieve this. Alerts are temporarily disabled (VPN down, daemon sets down, nodes gone).

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by gardener-robot-ci-1** [comment]
**Comment by [rfranzke](https://github.com/rfranzke)**
_Monday Dec 11, 2017 at 14:07 GMT_

----

With the availability of the `machine-controller-manager` we can reduce the node replica count to `0` and disable all worker node alerts temporarily.

**Comment by gardener-robot-ci-1** [comment]
**Comment by [d029221](https://github.com/d029221)**
_Thursday Jan 11, 2018 at 08:17 GMT_

----

That would be a great feature also for our use case.
Can you say when it will be available?

**Comment by gardener-robot-ci-1** [comment]
**Comment by [vlerenc](https://github.com/vlerenc)**
_Thursday Jan 11, 2018 at 08:31 GMT_

----

Not really, in 2 months maybe.

**Comment by vlerenc** [comment]
We should ask @mvladev how to silence the alerts. We could e.g. use `garden.sapcloud.io/operatedBy` to silence them (poor man's solution) or, as suggest by @rfranzke, scale down the alertmanager to 0 (preferred).

**Comment by petersutter** [comment]
can we have an annotation to hibernate the shoot instead of setting the autoscaler max to 0 so that we do not "lose" the autoscaler configuration?

**Comment by rfranzke** [comment]
Yes, we plan to add a new field to the shoot spec for the same.

**Comment by petersutter** [comment]
is there already an issue regarding this that you can link here or should we reopen this issue?

**Comment by rfranzke** [comment]
Created #191 to track.
