### ISSUE TITLE
SeedAuthorizer: Do not allow `DELETE` for BackupBuckets unconditionally

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5082]
**How to categorize this issue?**

/area quality security
/kind bug

**What happened**:
From the current handling in the SeedAuthorizer, it seems that it always allows `DELETE` verbs and does not perform relationship checks.

https://github.com/gardener/gardener/blob/3678f65531c172e56fffc65d7c27d82559203513/pkg/admissioncontroller/webhooks/auth/seed/authorizer.go#L107

**What you expected to happen**:
TO do not allow `DELETE` verb unconditionally.

**How to reproduce it (as minimally and precisely as possible)**:
(I haven't tried myself but the following steps would do the trick)

1. With the identity of gardenlet `gardener.cloud:system:seed:foo` try to delete a BackupBucket that belongs to another Seed (`spec.seedName=bar`)

2. Make sure that the above deletion is not rejected with `no relationship found between seed 'foo' and this object`

**Environment**:

- Gardener version: v1.36.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
Support for `BackupBucket` resources in the seed authorizer was initially added with #3884. In this PR, `delete` was not "always allowed", however, this was changed with https://github.com/gardener/gardener/pull/4111/commits/458b130c1dc92e2f174f54ff9367aff4cee01420, probably to work around #5083.

We could now do something similar to #5066, but let me look into #5083 first to check if this can be improved generally.
