### ISSUE TITLE
OpenStack Cluster 4 Support

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#51]
**Issue by [vlerenc](https://github.com/vlerenc)**
_Thursday Nov 23, 2017 at 13:17 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/224_

----

# Story
* As user I want to deploy shoot clusters on OpenStack Cluster 4, so that I can run my workload in SAP DCs.

# Acceptance Criteria
- [x] User can get a working shoot cluster on OpenStack Cluster 4 in his own tenant
  - [x] Operator supports new infrastructure
  - [x] UI supports new infrastructure
  - [x] Dev & Prod seed clusters are deployed
  - [x] Garden Setup is updated

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://git.removed/kubernetes/kube-docs/wiki/Operations%20Guide)?
- [ ] User documentation: Have you informed Sylvia Pick about user relevant changes?
- [ ] Release comments: Does the Jira story have proper release notes?

**Comment by gardener-robot-ci-1** [comment]
**Comment by [D067570](https://github.com/D067570)**
_Monday Jan 08, 2018 at 09:33 GMT_

----

I was able to enter my account secrets but can't select them in the "create cluster" dialog. 
Any progress/timeline for this feature? We have a high demand for that because we need connectivity to internal systems.

Also naming is a bit confusing. Sometimes it's called Openstack sometimes SAP Cloud Platform but official name is Converged Cloud (as far as I know).

**Comment by gardener-robot-ci-1** [comment]
**Comment by [vlerenc](https://github.com/vlerenc)**
_Tuesday Jan 09, 2018 at 09:29 GMT_

----

@d038928 Could you please handle this question? Thank you Jürgen.

**Comment by gardener-robot-ci-1** [comment]
**Comment by [d038928](https://github.com/d038928)**
_Tuesday Jan 09, 2018 at 10:13 GMT_

----

Converged Cloud Infrastructure is the base for several control planes (GMP, VMWare, more than one OpenStack Environments, ...). We are working on enabling Kubernetes cluster in SAP DCs in the context of SAP Cloud Platform which means technically that we rely on OpenStack Industry Edition. At the moment, provisioning Kubernetes cluster is not enabled in our productive Gardener UI, but our plans are to bring a closed beta on the way early 2018. Furthermore, at the moment we don't have concrete timelines for supporting other OpenStack environments (like OpenStack VMWare Enterprise Edition, also known as Monsoon3). 

@D067570 I propose to do a short sync on that topic to clarify your requirements, so please give me a call depending on the importance of your question (as you are on training during the next days).

**Comment by vlerenc** [comment]
Implemented.
