### ISSUE TITLE
`seed-*` namespace in garden is not cleaned up after seed deletion

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#5164]
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:

Seed `local` was deleted, but the namespace `seed-local` in the garden cluster was not cleaned up.

**What you expected to happen**:

The namespace to be cleaned up along with the seed itself.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Seed
2. Observe the namespace `seed-$name` to be created
3. Delete the Seed
4. Observe that the namespace is still present and is not cleaned up

**Comment by acumino** [comment]
@timebertt,  I tried to reproduce it many times and it worked as expected. Are you still facing this issue?
While deleting the seed was your GCM also running?

**Comment by timebertt** [comment]
I can't reproduce this anymore as well. The namespace has an owner reference to the seed, so the namespace is cleaned up after the seed has been deleted.
There must have been some weird circumstances, when it happened back then. But I can't remember, so
/close
