### ISSUE TITLE
Blackbox Reporter missing network policy label to be able to communicate with APIServer when Cilium is used

### ISSUE THREAD

**Issue by christianhuening** [gardener/gardener#5185]
**How to categorize this issue?**

/area monitoring
/area control-plane
/kind bug

**What happened**:
We have Cilium active as CNI in all our clusters. When enabling alerting via alertmanager we received a lot of alerts from shoots indicating they wouldn't be able to reach the api-server. It turned out that the blackbox-reporter pod was missing a network policy label to be allowed to talk to the apiserver 

**What you expected to happen**:
blackbox reporter correctly being labelled with network policy label

**How to reproduce it (as minimally and precisely as possible)**:
deploy shoot with reversevpn and enable alerting

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.33.1
- Kubernetes version (use `kubectl version`): 1.20.12
- Cloud provider or hardware configuration: GCP + AWS
- Others:

**Comment by rfranzke** [comment]
Can you explain how this is related to reversed VPN?

**Comment by christianhuening** [comment]
🤔 it probably is not now that you say it. I thought that the alert check and network policy was special due to the fact the we have reverse vpn enabled and the connection is initialized from the shoot to the seed to begin with, but that has nothing to do with it AFAIK.

**Comment by christianhuening** [comment]
we found out that the problem is apparently cilium when using 0.0.0.0/0 as CIDR destination for an egress policy.  @istvanballok found this issue: https://github.com/cilium/cilium/issues/16147#issuecomment-843611823
