### ISSUE TITLE
Code generation is required after release

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5197]
**How to categorize this issue?**

/area quality delivery
/kind regression
/kind bug

**What happened**:
After https://github.com/gardener/gardener/pull/5115 , `make check-generate` after a release will fail because the provider-local ControllerDeployment/ControllerRegistration is not up-to-date (ref https://github.com/gardener/gardener/pull/5115#discussion_r771513464).

**What you expected to happen**:
`make check-generate` to do not fail after a successful release.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Environment**:

- Gardener version: v1.39.0-dev
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
/assign

We decided to not render the version into the `ControllerRegistration` for provider-local but just the static `latest` tag. This way, no generation is needed on release.
