### ISSUE TITLE
Shoot deletion fails on `Waiting until main and event etcd report readiness`

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5240]
/area quality
/kind bug
/kind regression
/priority 1

**What happened**:
Looks like with https://github.com/gardener/gardener/pull/5209 a regression is being introduced that prevents Shoot to be deleted successfully. 

**What you expected to happen**:
Shoot deletion to do not hang/fail on task `Waiting until main and event etcd report readiness`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot.

2. After successful creation delete the Shoot.

3. Make sure that the deletion fails with:
```yaml
  lastErrors:
  - description: "task \"Waiting until main and event etcd report readiness\" failed:
      2 errors occurred:\n\t* Error while waiting for Etcd shoot--foo--bar/etcd-events
      to become ready: object's \"gardener.cloud/timestamp\" annotation is not \"2022-01-10
      15:59:46.118532 +0000 UTC\" but \"2022-01-10 15:59:46.460425 +0000 UTC\"\n\t*
      Error while waiting for Etcd shoot--foo--bar/etcd-main to become
      ready: object's \"gardener.cloud/timestamp\" annotation is not \"2022-01-10
      15:59:46.120311 +0000 UTC\" but \"2022-01-10 15:59:46.594125 +0000 UTC\"\n\n"
    lastUpdateTime: "2022-01-10T16:04:46Z"
    taskID: Waiting until main and event etcd report readiness
```

**Environment**:

- Gardener version: 83f20512c06d5e7b6505c8d94db063585501e11a
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
The issue is that in the deletion flow we have the following 3 consecutive tasks:

https://github.com/gardener/gardener/blob/83f20512c06d5e7b6505c8d94db063585501e11a/pkg/gardenlet/controller/shoot/shoot_control_delete.go#L253-L267

`Waiting until main and event etcd report readiness` is actually using the `etcd` field of the component 

https://github.com/gardener/gardener/blob/83f20512c06d5e7b6505c8d94db063585501e11a/pkg/operation/botanist/component/etcd/waiter.go#L47

that is being set by the `Deploy` func of the component.

https://github.com/gardener/gardener/blob/83f20512c06d5e7b6505c8d94db063585501e11a/pkg/operation/botanist/component/etcd/etcd.go#L192

To my understanding what happens:
1. `Deploying main and events etcd` sets the etcd with a given timestamp
2. `Scaling up etcd main and event` sets a new timestamp annotation
3. `Waiting until main and event etcd report readiness` is using as expected annotation value the value from step 1. but the value is actually the one from step 2.

~~As this issue is a blocker for the release validation, should I revert the whole #5209 or only the part of it about the timestamp annotation?~~

**Comment by rfranzke** [comment]
Side note: Interestingly, the [`pull-gardener-e2e-kind` job](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/5209/pull-gardener-e2e-kind/1480455404826660864) executed for #5209 has caught the problem (the test itself failed). However, the entire run was wrongly marked as "successful", allowing the PR to be merged.
cc @timebertt
