### ISSUE TITLE
Drop `Logging` feature gate in favor of gardenlet configuration

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#5277]
**How to categorize this issue?**

/area usability
/kind enhancement

**What would you like to be added**:
The `Logging` feature gate should be deprecated and removed. Instead, the logging feature should be enabled/disabled/configured via the gardenlet configuration.

**Why is this needed**:
The feature will never be promoted given that it's an optional feature, so having introduced it in the first place was the wrong approach. We already have logging-related configuration in the gardenlet config: https://github.com/gardener/gardener/blob/b822dfb5e86d418f541bb66dea4a6632c78f6fc5/example/20-componentconfig-gardenlet.yaml#L126-L137

**Comment by acumino** [comment]
I synced with @ialidzhikov and we decided to follow this approach:

Step 1: Deprecate the `logging` feature gate and keep it for a few more versions for backward compatibility as all of our landscapes explicitly enable this feature gate.
Introduce a new subfield `enabled` in `logging` field of  `GardenletConfiguration` for globally enabling and disabling logging and keeping its default value to false.

Step 2: Drop the `logging` feature gate.

@vlvasilev

**Comment by rfranzke** [comment]
> Deprecate the logging feature gate and keep it for a few more versions for backward compatibility as all of our landscapes explicitly enable this feature gate.

Why? It's alpha and we can easily drop it without breaking any promises. We do the same for the component configurations, I don't see a difference here. Shouldn't we make this less complex and rather work with a "breaking" release note asking folks to adapt their configuration?

**Comment by ialidzhikov** [comment]
The general idea was to make it a little bit more graceful. If we drop the feature gate, then with the gardener version update the gardener operator has to adapt to the breaking change right away. If we make it with the deprecation and backwards-compatibility handling, then this adaptation can be done in a later point in the time (does not strictly depend on the gardener version update).
In short, I am fine with both approaches - one is more graceful wrt to the rollout, the other one is less complex (without additional compatibility logic).
