### ISSUE TITLE
resource-manager does not respect `--max-concurrent-workers`

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#5281]
**How to categorize this issue?**

/area ops-productivity
/kind bug

**What happened**:

`--max-concurrent-workers` was set to `0`, but resource-manager kept reconciling `ManagedResources`.

**What you expected to happen**:

resource-manager to respect its flags.

**How to reproduce it (as minimally and precisely as possible)**:

1. Prepare the environment
```bash
make kind-up
k apply -f example/resource-manager/10-crd-resources.gardener.cloud_managedresources.yaml
k apply -f example/resource-manager/20-managedresource.yaml
```
2. Start resource-manager
```bash
$ make start-resource-manager
...
{"level":"info","ts":"2022-01-17T10:24:12.475+0100","msg":"FLAG: --max-concurrent-workers=10"}
...
```
3. Stop resource-manager
4. Delete a managed `ConfigMap`, e.g.
```bash
$ k delete cm test-1234
configmap "test-1234" deleted
```
5. Edit `hack/local-development/start-resource-manager`, set `--max-concurrent-workers=0` and start resource-manager again
```bash
$ make start-resource-manager
...
{"level":"info","ts":"2022-01-17T10:25:03.289+0100","msg":"FLAG: --max-concurrent-workers=0"}
...
```
6. Observe, that the `ConfigMap` is recreated, although resource-manager is not supposed to reconcile the `ManagedResource`
```bash
$ k get cm test-1234
NAME        DATA   AGE
test-1234   0      7s
```

**Environment**:

- Gardener version: current `master` 5f0ae8df63ec1e6b46751fc41bb1393485f55c20, but this shouldn't be new

**Comment by timuthy** [comment]
Btw. this is true for nearly every controller we set up with Controller-Runtime. 

See https://github.com/kubernetes-sigs/controller-runtime/blob/0a3dd2a36dd971ea2fdcb163b0457e6be0d315bd/pkg/controller/controller.go#L112

**Comment by rfranzke** [comment]
Given that this works "as designed" (see @timuthy's link), we agreed
/close
ing this issue for now. As the goal of this request is probably similar to https://github.com/gardener/gardener/issues/4806, let's rather focus on this.
If you feel we should still support a `--disable-controller` flag (similar to what we support for the extensions library) then kindly open a new issue.
