### ISSUE TITLE
ControlPlane migration test is wrongfully adding `BeforeSuite` in `Describe`

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#5350]
**How to categorize this issue?**

/area control-plane-migration
/kind bug

**What happened**:

@vpnachev reported in https://github.com/gardener/gardener/pull/5313#issuecomment-1024080188, that the control plane migration test is no longer able to be executed successfully after the upgrade to ginkgo v2.
That's because ginkgo doesn't allow to add `BeforeSuite` calls inside container nodes like `Describe`.
This was never working as intended before, but now ginkgo v2 is now able to complain about it and fails the test because it detected a programmer-level error.
See http://onsi.github.io/ginkgo/#suite-setup-and-cleanup-beforesuite-and-aftersuite

**What you expected to happen**:

The test to be written correctly, so that it can be executed as intended.

**Comment by timebertt** [comment]
@kris94 @plkokanov can you take care to resolve this issue?

**Comment by plkokanov** [comment]
Thanks, I saw it last week as well but missed submitting it as an issue 😅. I think that just replacing the `CBeforeSuite` with a `BeforeEach` should be good enough solution.
