### ISSUE TITLE
BoundServiceAccountTokenVolume  - control time           

### ISSUE THREAD

**Issue by ALNBAND** [gardener/gardener#5355]
HI,

We plan to do upgrade to k8s 1.22.x and for 1.21.x we use the feature gate `BoundServiceAccountTokenVolume : false`
As it seems that the default is true for 1.22 when using gardener , how we can increase the token expiration time?

**Comment by rfranzke** [comment]
Generally, as indicated in the issue template, for support/questions please reach out to the public [#gardener](https://kubernetes.slack.com/archives/CB57N0BFG) Slack channel.

/close

As for your question: The `BoundServiceAccountTokenVolume` was promoted to GA with Kubernetes 1.22 (unrelated to Gardener), hence, it's enabled by default.
Your specific question is more related to Kubernetes, so I would suggest to reach out to their community.
Gardener allows configuration of `kube-apiserver`'s `--service-account-max-token-expiration` and `--service-account-extend-token-expiration` flags ([ref](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/)) via https://github.com/gardener/gardener/blob/ca661c0502eb1f885a2ac3793913025788d5102d/example/90-shoot.yaml#L182-L183, however, I'm not sure whether the [default token expiration](https://github.com/kubernetes/kubernetes/blob/0038bcfad495a0458372867a77c8ca646f361c40/plugin/pkg/admission/serviceaccount/admission.go#L430) time injected via the automatic mount can be changed.

**Comment by ALNBAND** [comment]
@rfranzke - From here you can see that the feature gate marked for deletion in 1.23, this is what make the confusion... 
https://github.com/kubernetes/kubernetes/pull/101992 

So those values will influence the token rotation time for `BoundServiceAccountTokenVolume` ? 
```
#     extendTokenExpiration: true
#     maxTokenExpiration: 1m
```
As the default with this future now is 1 hour and we want to change it to 1 month...

**Comment by rfranzke** [comment]
> So those values will influence the token rotation time for BoundServiceAccountTokenVolume ?

>> Gardener allows configuration of `kube-apiserver`'s `--service-account-max-token-expiration` and `--service-account-extend-token-expiration` flags ([ref](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/)) 

> As the default with this future now is 1 hour and we want to change it to 1 month...

Can you explain how you would configure this via Kubernetes (when you had direct control to the `kube-apiserver`, `kube-controller-manager`, etc. deployments)?

**Comment by ALNBAND** [comment]
@rfranzke Not sure I understand your question, this is not something that  should be control in general ? e.g. the way I remove it via featureGate I suppose that there is a way to configure it globally for all the SA volume? isn't it ?

**Comment by ALNBAND** [comment]
@rfranzke  - I mean the rotation time for service account

**Comment by rfranzke** [comment]
I don't know. As said, this is something specific to Kubernetes and I suggest to follow up with their community to clarify this question. If it is possible then I suspect it is some CLI flag that needs to be set when starting `kube-apiserver` or `kube-controller-manager`.

This is why I asked

> Can you explain how you would configure this via Kubernetes (when you had direct control to the kube-apiserver, kube-controller-manager, etc. deployments)?

If you can tell me how this works I can tell you whether it is possible via Gardener. If it is not possible today then we could probably make it possible in the future.
