### ISSUE TITLE
Improve CoreDNS deployment for multi-zonal shoot clusters

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#5359]
**How to categorize this issue?**

/area high-availability networking
/kind enhancement

**What would you like to be added**:
From a report of an end-user:

> Mostly impacted K8s clusters are the regional ones deployed to more than one zone.
> There are possibilities, where all coredns deployment replicas are scheduled on a single node or every replica is on separate worker node, within the same availability zone.
> Currently node affinity rules are configured to behave in the way mentioned above (rule is preferred only during scheduling), because of `preferredDuringSchedulingIgnoredDuringExecution` policy.
> 
> 1. coredns scheduling rules to be configurable if not already, through Gardener.
> 2. Gardener to be able to recognize that cluster setup is multi-zonal and to schedule all replicas between different availability zones

**Why is this needed**:
> We've encountered occasional connection timeouts, when one availability zone is in downtime & all coredns replicas are scheduled on the node within this zone.

**Comment by rfranzke** [comment]
/cc @ScheererJ @DockToFuture 

@DockToFuture already replied (out-of-band) as follows:

> We could introduce the topology for zones(`topologyKey: topology.kubernetes.io/zone`) and weight it more than the topology for hostnames:
> 
> ```
>     spec:
>       affinity:
>         podAntiAffinity:
>           preferredDuringSchedulingIgnoredDuringExecution:
>           - podAffinityTerm:
>               labelSelector:
>                 matchExpressions:
>                 - key: k8s-app
>                   operator: In
>                   values:
>                   - kube-dns
>               topologyKey: kubernetes.io/hostname
>             weight: 90
>           - podAffinityTerm:
>               labelSelector:
>                 matchExpressions:
>                 - key: k8s-app
>                   operator: In
>                   values:
>                   - kube-dns
>               topologyKey: topology.kubernetes.io/zone
>             weight: 100
> ```
> 
> But I would not switch away from `preferredDuringSchedulingIgnoredDuringExecution`.

**Comment by timuthy** [comment]
We might also want to consider [pod topology spread constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) to achieve this.

**Comment by ScheererJ** [comment]
One of the limitations of pod topology spread constraints as well as anti-affinity is that they are only considered at scheduling time, but ignored at execution time. Especially in conjunction with our autoscaling we might end up with an unbalanced spread unless we employ something like [Descheduler](https://github.com/kubernetes-sigs/descheduler).
@rfranzke @timuthy What are your thoughts about Descheduler?

**Comment by timuthy** [comment]
That's a good point @ScheererJ.

`CoreDNS` has `HPA - MINPODS: 2, MAXPODS: 5`.

Example with cluster in `3` availability zones:
- `t1`
  -  Deployment has `4` replicas.
  -  West: `1`, East: `2`, Central: `1`
  -  Distributed deployment ✅ 

- `t2`
  -  Deployment is scaled down to `3` replicas.
  -  West: `0`, East: `2`, Central: `1`
  -  Imbalanced distribution ❌ 

Does this example express the concern you mentioned?
cc @shreyas-s-rao

**Comment by DockToFuture** [comment]
That is exactly the case which could happen when not using the [Descheduler](https://github.com/kubernetes-sigs/descheduler) mentioned by @ScheererJ .

**Comment by ScheererJ** [comment]
@timuthy Yes, indeed. It does not even need three availability zones. Regularly scaling up and down with two availability zones will likely also put you into the same spot.
(It is also explicitly mentioned by the documentation of topology spread constraints.)
