### ISSUE TITLE
`loki-0` pod is stuck in `ContainerCreating` for a long time when shoot node logging is enabled

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#5363]
**How to categorize this issue?**

/area ops-productivity
/kind bug

**What happened**:
When the shoot node logging feature is enabled then the `kube-rbac-proxy` container is part of the `loki` `StatefulSet` deployed in shoot namespaces in the seed clusters.
However, with #5010, the `kube-rbac-proxy` relies on a token issued by the `TokenRequestor` controller part of `gardener-resource-manager`.

The logging stack is deployed quite early in the shoot flow: https://github.com/gardener/gardener/blob/ca661c0502eb1f885a2ac3793913025788d5102d/pkg/gardenlet/controller/shoot/shoot_control_reconcile.go#L155-L159

The reason is to fetch logs of the control plane components as early as possible.

We can either

1. deploy the logging stack only after `gardener-resource-manager` became ready
2. deploy the logging stack twice, first w/o any sidecar containers needed for the shoot node logging feature, later (after `gardener-resource-manager` became ready) w/ all needed sidecar containers

The first approach has the downside of having loki available only later as part of the shoot creation. This can make debugging issues challenging when the shoot creation got stuck in an early state.
The second approach has the downside of a redeployment of the `Pod` with a potential re-attachment of its volume, typically a costly operation for cloud providers.

**What you expected to happen**:
`loki` should only be deployed when all prerequisites (like such token) are fulfilled.

**How to reproduce it (as minimally and precisely as possible)**:
1. Enable shoot node logging feature in gardenlet
2. Create a shoot
3. See the `loki-0` pod stuck in `ContainerCreating` for a long time (until `gardener-resource-manager` is deployed and the pod creation is retried)

**Environment**:

- Gardener version: v1.39.1

**Comment by dguendisch** [comment]
For me the complexity of deploying loki twice wouldn't be worth the effort. Also customers rarely ask us to provide an RCA if cluster creation was failing (for some time). So usually we investigate failed cluster creations when the failing situation is still present in which case we have enough k8s resources to analyze and then typically don't need loki.
Hence +1 on deploying it after GRM (in the hope that this is also easier / less complex).
