### ISSUE TITLE
Optimize node listing calls to reduce load on API server

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#5374]
**How to categorize this issue?**

/area scalability
/kind enhancement

**What would you like to be added**:
We run the `health-monitor` for kubelet on every node which performs a costly "node list" call in every execution: https://github.com/gardener/gardener/blob/f57cd81abb585064a7766808cfc4f155359656fd/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/templates/scripts/health-monitor.tpl.sh#L49

Additionally, we run the `cloud-config-downloader` which performs similar "node list" call in every execution: https://github.com/gardener/gardener/blob/3fde233848e015e9a9b070a60fa9ffaa0395a551/pkg/operation/botanist/component/extensions/operatingsystemconfig/executor/templates/scripts/execute-cloud-config.tpl.sh#L179

This is quite costly, especially in large cluster where we have a lot of nodes. Let's improve this by performing the "node list" call only once in the `cloud-config-downloader` to get to know the node name. This node name can be persisted in a file on the disk. From then on, the content of this file can be used and we can switch to "get node" calls instead.

**Why is this needed**:
Better scalability, less network I/O, less costs.

**Comment by BeckerMax** [comment]
/priority 2 
On clusters with large node counts this causes significant load on the etcd through API server list calls. We should look at that with prio 2

**Comment by petersutter** [comment]
We have seen an issue on `alicloud` where `$(hostname)` does not match the value of label `kubernetes.io/hostname` and thus no node with this label can be found (case sensitive).
E.g. hostname was `iZuf66s0llotbbevcbdfqzZ` and `kubernetes.io/hostname` was `izuf66s0llotbbevcbdfqzz`
