### ISSUE TITLE
In very rare cases shoot secrets can get regenerated during reconciliation

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#5377]
**How to categorize this issue?**

/area control-plane-migration
/kind bug
/priority 3

**What happened**:
During reconciliation the secrets' data for the `ca-vpn` and `ca` certificate authorities in the `ShootState` were regenerated. It seems that they get somehow deleted together with other secrets that are cleaned up during the `GenerateAndSaveSecrets` step. 

**What you expected to happen**:
The data for the `ca-vpn` and `ca` secrets to never be regenerated in the `GenerateAndSaveSecrets` step

**How to reproduce it (as minimally and precisely as possible)**:
I still have no idea how to reproduce this issue consistently. It seems to happen very very rarely.

**Comment by rfranzke** [comment]
Let's
/close
this in favor of #5503
