### ISSUE TITLE
Validation of equality between `MachineDrainTimeout` and `maxGracefulTerminationSeconds` flags

### ISSUE THREAD

**Issue by AxiomSamarth** [gardener/gardener#5378]
**How to categorize this issue?**

/area auto-scaling
/kind enhancement

**What would you like to be added**:
A quantitative equality check where the MCM `MachineDrainTimeout` flag is always greater than or equal to `maxGracefulTerminationSeconds ` flag of CA.

**Why is this needed**:
There are two flags that could be set in the Shoot yaml. One is MCM [`MachineDrainTimeout`](https://github.com/gardener/gardener/blob/5baac06c204771e1adabcc039a2222b037f9f8e0/example/90-shoot.yaml#L123)(Time after which the pods will be force evicted) and another is CA [`maxGracefulTerminationSeconds`](https://github.com/gardener/gardener/blob/5baac06c204771e1adabcc039a2222b037f9f8e0/example/90-shoot.yaml#L245)(Maximum number of seconds CA waits for pod termination when trying to scale down a node.)

These two eviction processes are independent of each other. In case where CA scales down the nodes and MachineDrainTimeout is less than the MaxGracefulTerminationSeconds then MCM will override the MaxGracefulTerminationSeconds and force drains the node which might not be what customers expect to happen (one customer even raised a concern about it recently)

So, it would be good to keep a validation such that `MachineDrainTimeout` is always greater than or equal to `MaxGracefulTerminationSeconds`.

cc: @himanshu-kun @ashwani2k

**Comment by himanshu-kun** [comment]
/close
CA drain is followed by MCM drain so they shouldn't interfere.
