### ISSUE TITLE
[Flaky Test] ClientMap Internal Suite is flaky

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#5410]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:

`GenericClientMap initialized ClientMap #GetClient [It] should create a new ClientSet and start it automatically`

<details>
<pre>
------------------------------
• Failure [0.015 seconds]
GenericClientMap
/go/src/github.com/gardener/gardener/pkg/client/kubernetes/clientmap/internal/generic_clientmap_test.go:35
  initialized ClientMap
  /go/src/github.com/gardener/gardener/pkg/client/kubernetes/clientmap/internal/generic_clientmap_test.go:47
    #GetClient
    /go/src/github.com/gardener/gardener/pkg/client/kubernetes/clientmap/internal/generic_clientmap_test.go:76
      should create a new ClientSet and start it automatically [It]
      /go/src/github.com/gardener/gardener/pkg/client/kubernetes/clientmap/internal/generic_clientmap_test.go:95

      Unexpected call to *mock.MockInterface.DiscoverVersion([]) at /go/src/github.com/gardener/gardener/pkg/client/kubernetes/clientmap/internal/generic_clientmap.go:100 because: there are no expected calls of the method "DiscoverVersion" for that receiver

      /go/src/github.com/gardener/gardener/pkg/client/kubernetes/mock/mocks.go:131
------------------------------
</pre>
</details>

**CI link**:

https://concourse.ci.gardener.cloud/builds/2734135#L61ecda8e:352

**Reason for failure**:

This test suite seems to be susceptible to resource contention.

**Anything else we need to know**:

**Comment by rfranzke** [comment]
Happened again in #5556: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/5556/pull-gardener-unit/1504071320869015552

**Comment by rfranzke** [comment]
And again in #5595: https://concourse.ci.gardener.cloud/builds/5327183

**Comment by rfranzke** [comment]
And again in #5550: https://concourse.ci.gardener.cloud/builds/5320994

**Comment by timebertt** [comment]
I was able to reproduce this locally using:
```
$ ginkgo build ./pkg/client/kubernetes/clientmap/internal
$ stress -p 50 ./pkg/client/kubernetes/clientmap/internal/internal.test
...
3932 runs so far, 2 failures
```
(ref https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/flaky-tests.md#deflaking-unit-tests)

**Comment by timebertt** [comment]
I assume that timing stuff is making problems under CPU load as we have seen in some other test suites. 
Probable fix would be to switch to fake clocks in this suite as well and drop the `time.Sleep` calls like this one:
https://github.com/gardener/gardener/blob/7396ae48b182b4b5887091543e6d13b4c4b1dab3/pkg/client/kubernetes/clientmap/internal/generic_clientmap_test.go#L163-L164

**Comment by rfranzke** [comment]
Another one in #5679: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/5679/pull-gardener-unit/1508477589600079872

**Comment by rfranzke** [comment]
Another one in #5688: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/5688/pull-gardener-unit/1508742205383118848

**Comment by acumino** [comment]
This one also seems flaky - https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/5687/pull-gardener-unit/1509170313273806848
