### ISSUE TITLE
Use the `machine.metadata.label[node]` field instead of `machine.status.node` during worker restoration

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#5411]
**How to categorize this issue?**

/area control-plane-migration
/kind enhancement

**What would you like to be added**:
Currently when restoring the `Worker` resource, machine objects are fetched from the `worker.status.state` field and deployed in the shoot's namespace inside the seed cluster. Afterwards the `machine.status.node` field of these objects is patched so that it corresponds to the node the machine is responsible for. With this the creation of a new node is prevented. once the machine-controller-manager starts:
https://github.com/gardener/gardener/blob/ab3caf94c3fdeb3d6701dc4c8addb485e56a1cae/extensions/pkg/controller/worker/genericactuator/actuator_restore.go#L130-L146

However, there is also a `machine.metadata.labels[node]` field present in the machine object, which also points to the node that the machine object is responsible for. The restoration logic would be simpler if we relied on the field from the labels instead of relying on `machine.status.node`.

**Additional info**
I tested a few control plane migrations by only relying on `machine.metadata.labels[node]` and they finished successfully (without recreating the nodes) but I would like a confirmation from @gardener/mcm-maintainers if this would work in all cases.

**Comment by AxiomSamarth** [comment]
Hey @plkokanov,

If a label is present on the `machine` object then that means that there is, for sure, a backing VM instance on cloud provider (which we can assume here is a healthy running node)

You can very well consider patching the migrated machine objects with `machine.metadata.labels[node]` and it will not lead to creation of new nodes though creation will be triggered and also MCM will update the `machine.Status.Node` with the `nodeName `[here](https://github.com/gardener/machine-controller-manager/blob/4215b07f21f7b95a9336597073d24f88cfc9a3b5/pkg/util/provider/machinecontroller/machine.go#L516-L519).

**Comment by himanshu-kun** [comment]
Yes as @AxiomSamarth said that if `machine.Status.Node` is empty, reconciliation will fill it up . But after looking at the code I figured that the `machine.Status.Node` can be removed anyways and machine controller can rely just on only node label as requested in the issue https://github.com/gardener/machine-controller-manager/issues/389

I will raise a PR soon for the same
