### ISSUE TITLE
Never successfully created `DNSRecord` cannot be deleted

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#5413]
**How to categorize this issue?**

/area ops-productivity
/kind bug

**What happened**:
After seeing https://github.com/gardener/gardener/issues/5364#issuecomment-1027903217, I'm now seeing

```
task "Destroying nginx ingress DNS record" failed: Failed to delete DNSRecord shoot--foo--bar/bar-external: Error deleting dnsrecord: could not find DNS hosted zone for name api.some.custom.domain.com
```

Hence, it seems a never successfully created `DNSRecord` can not be deleted anymore.

**What you expected to happen**:
Successful deletion of shoot.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot with invalid DNS configuration to produce above error and then delete the shoot.

**Environment**:

- Gardener version: v1.39

**Comment by voelzmo** [comment]
cross-linking for reference: 
* historic similar issue https://github.com/gardener/gardener/issues/4778
* PR by @MartinWeindel https://github.com/gardener/gardener/pull/5234

So maybe this is actually fixed already but the fix hadn't been re-vendored to the extension at the time this happened? In theory, this should not be reproducible anymore now that extensions have been re-vendored with the above fix by Martin. Can you re-check, @rfranzke?

**Comment by rfranzke** [comment]
Great, with an up-to-date extension this is indeed no longer reproducible.
/close
