### ISSUE TITLE
Update of ManagedSeeds from ManagedSeedSet

### ISSUE THREAD

**Issue by dergeberl** [gardener/gardener#5441]
**How to categorize this issue?**
/area control-plane
/kind question

**What happened**:

If creating Seeds with a `ManagedSeedSet` the seeds did not get updated when parameters will be updated (for example values for `spec.template.spec.gardenlet.config`)

Is that behavior correct or is it a bug?

**What you expected to happen**:

All fields that are not immutable should be updated to the `ManagedSeeds` from an `ManagedSeedSet`. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a `ManagedSeedSet`
2. Update settings in for example `spec.template.spec.gardenlet.config`
3. The `ManagedSeeds` did not get reconciled with the new settings

**Environment**:

- Gardener version: 1.37.3
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: openstack
- Others:

**Comment by timebertt** [comment]
Yep, that's not implemented yet. From https://github.com/gardener/gardener/pull/3713:

> Only creation and deletion of replica shoots and managed seeds is performed currently by this controller. Updates, revision history, etc. are not yet covered.

Unfortunately, the work on https://github.com/gardener/gardener/issues/2885 (GEP-13) was stopped in favor of other topics with higher priority.
Feel free to follow along there or assign yourself / get in touch if you want to work on it.

I propose to `/close` this one in favor of https://github.com/gardener/gardener/issues/2885 if you don't mind.

**Comment by dergeberl** [comment]
Okay thanks for clarification and the Info.

I will close that issue.
