### ISSUE TITLE
cluster autoscaler downscale configuration

### ISSUE THREAD

**Issue by bergerx** [gardener/gardener#546]
In some of our clusters (mainly on perf test clusters) we struggle with the autscaler being aggressive for our use case.

E.g. we run perf/load tests 10-20 minutes apart on the cluster and currently after each test the autoscaler kicks in and unnecessarily downscales the cluster just before the next round of tests are started. This forces us to disable the autoscaler feature since it's also impacting our test results.

It would enable us to get power of autoscaler if we have are able to have control over downscale configuration (some would be enough, not all are required). Hence I'm not sure which flag should be best to tune to make downscaling less aggressive. 

From https://github.com/gardener/autoscaler/blob/0.2.0/cluster-autoscaler/FAQ.md#i-have-a-couple-of-nodes-with-low-utilization-but-they-are-not-scaled-down-why (referred the docs from `gardener/autoscaler` and not `kubernetes/autoscaler` on purpose since i'm not sure about the amount of drift from upstream):

```
* node was unneeded for less than 10 minutes (configurable by --scale-down-unneeded-time flag),
* there was a scale-up in the last 10 min (configurable by --scale-down-delay-after-add flag),
* there was a failed scale-down for this group in the last 3 minutes (configurable by --scale-down-delay-after-failure flag),
* there was a failed attempt to remove this particular node, in which case Cluster Autoscaler will wait for extra 5 minutes before considering it for removal again,
* using large custom value for --scale-down-delay-after-delete or --scan-interval, which delays CA action.
```

**Comment by luisdavim** [comment]
looks like these parameters are configurable in the shoot spec under `kubeControllerManager`.
https://github.com/gardener/gardener/blob/master/example/90-shoot-azure.yaml#L75

or am I reading this wrong?

**Comment by rfranzke** [comment]
@luisdavim no, these flags control the horizontal pod autoscaler, not the cluster autoscaler.
@bergerx The configuration of any components is a huge topic for itself that will at least be solvable easier with the planned extensibility concepts. Anyway, I've not yet fully understood your scenario. You are doing performance tests on a shoot, so why do you need the autoscaler here at all? If you don't need the cluster after the performance tests any more, isn't hibernation an option here (and wake-up as soon as you do the next test run)? Or do you do the tests every 10-20min (if so, why)? That comes back to my question why you need the cluster autoscaler here at all.

**Comment by rfranzke** [comment]
@hardikdr @prashanth26 what do you think, which flags make sense to get exposed?
In the end, the problem is that flags can come and go, but once they are in the Shoot API we can't remove them incompatibly. We have to find a good way to expose them if we want to.

**Comment by hardikdr** [comment]
This issue was discussed once in the community call, I am not very sure of a good way to expose the component-specific flags into Shoot-API. The question also stands if we should make all the components[or only autoscaler] completely configurable or gradually expose set flags to shoot-API on need-basis. If later, we can then have a final check to expose a specific set of flags from autoscaler.
