### ISSUE TITLE
Identify/Describe Gardener's ability to scale in terms of seed/shoot clusters

### ISSUE THREAD

**Issue by SimonKienzler** [gardener/gardener#5479]
**How to categorize this issue?**

/area documentation
/kind enhancement

**What would you like to be added**:

Could the documentation provide information about Gardener's ability to scale with some "rule of thumb" numbers? For example, a rough estimation and/or best practices for the following ranges would be very interesting:

* Hoy many shoots can a single Garden cluster handle?
* How many shoots can/should be placed on a seed?
* How many seeds can be used in a single Gardener setup?
* Are there any experiences of service regression when exceeding certain thresholds (like number of active Gardenlets, etc.)

I'd e.g. expect to find information like this on the [architecture page](https://gardener.cloud/docs/gardener/concepts/architecture/).

**Why is this needed**:

I'm aware that this is also dependent on a a lot of factors not involving Gardener itself (like the used infrastructure). However, I'm trying to build a reasonable intuition about what Gardener is capable of and how it behaves at scale.

If there is already any information on this topic that I didn't find, I'm also happy about some pointers.

**Comment by vlerenc** [comment]
Creation of tens of thousand of clusters is not practical (takes too long, costs too much), so we would have to get creative here. Maybe we could write a "hollow infrastructure extension" (and "hollow machine driver") that would create "hollow clusters", much like [kubemark](https://github.com/kubernetes-sigs/cluster-api-provider-kubemark) does with "hollow nodes" to test huge landscapes with many clusters. With this, we could test Gardener and Dashboard all the way down to the `gardenlet`, and independent extensions like DNS and cert controller. By tweaking it we could simulate also failure rates and how the landscape reacts to those. Maybe https://github.com/localstack/localstack can help to even better mock the infrastructure and simulate a large landscape. It looks interesting also in general for other tests, MCM or Gardener.
