### ISSUE TITLE
Define feature gates centrally instead of once per component

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#5486]
**How to categorize this issue?**

/area dev-productivity quality
/kind cleanup

**What would you like to be added**:

We define feature gates multiple times, once per component which uses it.

E.g. the `UseDNSRecords` feature gate is defined three times:
https://github.com/gardener/gardener/blob/744e0ff5db4f7f58d70a2f43546d379303f8a2cf/pkg/apiserver/features/features.go#L28
https://github.com/gardener/gardener/blob/744e0ff5db4f7f58d70a2f43546d379303f8a2cf/pkg/controllermanager/features/features.go#L29
https://github.com/gardener/gardener/blob/744e0ff5db4f7f58d70a2f43546d379303f8a2cf/pkg/gardenlet/features/features.go#L35

Also, there is one `featuregate.NewFeatureGate()` call per component, i.e. one feature gate map per component.

Instead, feature gates should be defined centrally once and added to `utilfeature.DefaultMutableFeatureGate` like in k/k:

https://github.com/kubernetes/kubernetes/blob/b181e174f25df752eb176c2393b95569646230d3/pkg/features/kube_features.go#L829
https://github.com/kubernetes/kubernetes/blob/b181e174f25df752eb176c2393b95569646230d3/pkg/features/kube_features.go#L822-L824

**Why is this needed**:

Redefining features gates is a source of programmer errors: one can easily forget to adapt the multiple definitions. Also shared code might be looking at features gates without someone noticing, that the feature gate is not registered with the component's map of feature gates.

**Comment by ialidzhikov** [comment]
I think that there are some benefits when each component has its own map of feature gates. It makes much more easy to check which feature gate is relevant for which component. If we switch to the approach to define them centrally then each component will register all feature gates - which can be misleading -> you will be allowed to configure a feature gate for a component when the component does not support such feature gate or does not have handling for it. When the feature gates count grows it is also polluting the help text - for example https://github.com/kubernetes-sigs/cloud-provider-azure/issues/943 where azure CCM gets all kube-apiserver feature gates registered -> help text shows completed unrelated feature gates where most of them do not make any sense to the azure CCM.

**Comment by rfranzke** [comment]
We agreed to add documentation about which feature gates are relevant for which of our components. Additionally, we would like to move the `FeatureGateSpec` (containing information about the maturity level) to a central place (`pkg/features`) and then just import it in the relevant components.
