### ISSUE TITLE
Update the AKS deployment guide

### ISSUE THREAD

**Issue by bergerx** [gardener/gardener#551]
The AKS deployment guide ([docs/deployment/aks.md](https://github.com/gardener/gardener/blob/master/docs/deployment/aks.md)) became old as AKS service went GA since then and now has RBAC and AAD support.

We need to update the doc to reflect the changes in the AKS.

**Comment by bergerx** [comment]
I'll try to create a PR for this.

**Comment by rfranzke** [comment]
Nice, thank you Bekir!
