### ISSUE TITLE
Monitoring Crash

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#557]
I was trying to get a picture on a performance test cluster by going to the dashboard garden-devx-londo/perf and opening up Grafana, but when I switched to last 30 days, Prometheus fell down:
```
$ k get pods
NAME                                         READY     STATUS    RESTARTS   AGE
alertmanager-0                               2/2       Running   0          5d
cloud-controller-manager-59d9db976f-bgh4n    1/1       Running   0          5d
cluster-autoscaler-789b7c6ddf-4xhw2          1/1       Running   0          21h
etcd-events-0                                2/2       Running   0          5d
etcd-main-0                                  2/2       Running   1          5d
grafana-744f44c64d-657xg                     1/1       Running   0          5d
kube-addon-manager-565fbf4df4-4zwd7          1/1       Running   0          5d
kube-apiserver-66668c8656-b56zr              3/3       Running   11         5d
kube-apiserver-66668c8656-zqx2q              3/3       Running   0          11h
kube-controller-manager-7668ccfb8b-7xdcx     1/1       Running   0          5d
kube-scheduler-7df7c9cb65-rr4qs              1/1       Running   0          5d
kube-state-metrics-6cd4c88964-lcmtg          1/1       Running   0          5d
kube-state-metrics-seed-65ffdc98d-dnzbl      1/1       Running   0          5d
machine-controller-manager-9548d579b-7hr7t   1/1       Running   3          5d
prometheus-0                                 3/3       Running   1          21h
```
Turned into:
```
NAME                                         READY     STATUS    RESTARTS   AGE
alertmanager-0                               2/2       Running   0          5d
cloud-controller-manager-59d9db976f-bgh4n    1/1       Running   0          5d
cluster-autoscaler-789b7c6ddf-4xhw2          1/1       Running   0          21h
etcd-events-0                                2/2       Running   0          5d
etcd-main-0                                  2/2       Running   1          5d
grafana-744f44c64d-657xg                     1/1       Running   0          5d
kube-addon-manager-565fbf4df4-4zwd7          1/1       Running   0          5d
kube-apiserver-66668c8656-b56zr              3/3       Running   11         5d
kube-apiserver-66668c8656-zqx2q              3/3       Running   0          11h
kube-controller-manager-7668ccfb8b-7xdcx     1/1       Running   0          5d
kube-scheduler-7df7c9cb65-rr4qs              1/1       Running   0          5d
kube-state-metrics-6cd4c88964-lcmtg          1/1       Running   0          5d
kube-state-metrics-seed-65ffdc98d-dnzbl      1/1       Running   0          5d
machine-controller-manager-9548d579b-7hr7t   1/1       Running   3          5d
prometheus-0                                 2/3       Running   2          21h
```

**Comment by vlerenc** [comment]
When I go back 7 days, it looks like a Swiss cheese:
<img width="845" alt="screen shot 2018-11-27 at 12 31 37" src="https://user-images.githubusercontent.com/4974203/49079285-78019b00-f240-11e8-8a90-b94110f8998a.png">

**Comment by mvladev** [comment]
@ vlerenc there are several issues which should be resolved:

- you should not be able to select 30days as currently Prometheus persists data only for 14 days top
- using the dashboard to query for those metrics is quite heavy. At the moment we calculate them on the flight. A better approach would be to simply store those queries as metrics. For example for the latency we do this `sum by(verb) (rate(apiserver_latency_seconds:quantile[5m]) >= 0)` like https://github.com/gardener/gardener/blob/33439ba20840fb89bed39e11b7b84a655797c73a/charts/seed-monitoring/charts/prometheus/rules/kube-etcd3.rules.yaml#L54-L56
- Prometheus was down during those periods
- we should set a more aggressive query evaluation timeout to prevent heavy queries

**Comment by vlerenc** [comment]
@mvladev How is this helpful? I mean, the problem was the week before last week, within the 14 days, but I couldn't select 14 days, so I selected 30 days. Either way, what purpose does the data serve if I can't call it up? And if you set a "more aggressive query evaluation timeout to prevent heavy queries", then I also don't get the data, but that was the whole purpose of the monitoring. Is there a constructive proposal how to enable ops into getting the data conveniently?

Besides this question, I would be interested to hear, why Prometheus was down or whether it really was down? Prometheus had only one restart, but could it have been also something else, like VPN issues or other load related issues? Then again, I would expect CPU+memory for the control plane as this data is collected on the seed cluster. Do you really believe, that Prometheus was down for longer and why?

**Comment by dkistner** [comment]
In any way I agree with Martin to remove the time selection of 30d when we only hold the data for max 14 days.

I don't know if it's a good idea to create recording rules for all dashboard queries, because I can't assess how much load this will produce when we calculate them every 30s or 1m. This is something which we may have to try out. If we decide to go in this direction we have to limit the amount of selectable time ranges in the dashboards and we have to calculate the query load when we determine the requested resources within the reconciliation loop.

@vlerenc You are right cpu+memory metrics are collected by the Seed Prometheus, but the Shoot Prometheus will scrape only the most recent of those metrics from the Seed Prometheus. If the Shoot Prometheus was down, then the old metrics will be not scraped afterwards. It will continue to scrape only the most recent ones. I can't say why Prometheus crashed. May the queries produces high load and lead in a oom situation. We should try to reproduce this and monitor the memory behaviour.

**Comment by vlerenc** [comment]
Sure, if we can drop 30 days or replace it with 14 days, even better. I was just saying, I wanted to take a look at what we have, because it happened in the week before last week.

The point being, that I wanted to take a look, which is why we collect the data. To analyse problems.

As for the lost metrics, I understand the two Prometheuses, but I don't know whether it really crashed. It had only one restart, not many. The metrics however looked like a Swiss Cheese.

On the other hand, when I looked into the cluster, I had the feeling, that Prometheus was in distress. Maybe because it was scaled based on the number of nodes and not the actual load, so it had the same problems like the too small API servers.

**Comment by vlerenc** [comment]
I hope it's ok, if I assign you @wyb1, because you are currently looking into the subject matter together with @kistner. When everything works out nicely with the VPA, please close this ticket. Thank you in advance.

**Comment by vlerenc** [comment]
I guess, we can close this one now that we have no instabilities anymore and started to use VPA anyway.
