### ISSUE TITLE
E2E / integration test for `AdminKubeconfigRequest` feature

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#5586]
**How to categorize this issue?**

/area testing
/kind enhancement

**What would you like to be added**:

An automated test for the `AdminKubeconfigRequest` feature. Could be a new e2e test or a step in one of the existing e2e tests or an integration test.

**Why is this needed**:

`AdminKubeconfigRequest` was promoted to GA in https://github.com/gardener/gardener/pull/5511.
However, there is no automated test for verifying the functionality. Hence, the functionality has to be tested manually in order to prevent bugs and regressions.

**Comment by timebertt** [comment]
@acumino @petersutter can you take care of adding a test?

**Comment by rfranzke** [comment]
From https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally.md#creating-a-shoot-cluster:

> ⚠️ Please note that in [this](https://github.com/gardener/gardener/blob/master/docs/extensions/provider-local.md#dnsrecord) setup shoot clusters are not accessible by default when you download the kubeconfig and try to communicate with them. The reason is that your host most probably cannot resolve the DNS names of the clusters since provider-local extension runs inside the KinD cluster (see this for more details). Hence, if you want to access the shoot cluster, you have to run the following command which will extend your /etc/hosts file with the required information to make the DNS names resolvable:

How would we overcome this as part of an e2e test?

**Comment by timebertt** [comment]
In the e2e test, we could workaround this simply looking up the external `DNSRecord` of the shoot and swap out the hostname in the kubeconfig with the resolved IP address.

**Comment by timebertt** [comment]
With https://github.com/gardener/gardener/pull/5649, `shoots/adminkubeconfig` was exposed to endusers. 
I think, it would be good to add an e2e test for it accordingly.
