### ISSUE TITLE
add --rm flag to cloud-init image preload

### ISSUE THREAD

**Issue by alcasim** [gardener/gardener#560]
We have spotted thousands of finished containers in the shoot nodes as a result of the cloud-init unit image pre-load. We are talking about 30000 containers in a week, which is pretty high and should not be happening, impacting also in kubernetes not being able to purge images, and node disk space usage

So far, I think it can be easily solved adding the flag `--rm` to the `docker run` command on this line:
https://github.com/gardener/gardener/blob/e146c72eea2d9fd08b3885dfff6a9cd54199bc06/charts/shoot-cloud-config/charts/downloader/templates/cloud-config/_download-cloud-config.sh#L39

**Comment by rfranzke** [comment]
Thanks @alcasim for reporting this one, we have fixed that and are going to create a new release.
