### ISSUE TITLE
enhancements of error messages

### ISSUE THREAD

**Issue by epDHowwD** [gardener/gardener#5609]
**How to categorize this issue?**

/area control-plane
Could also be 'usability'.

/kind enhancement

**What would you like to be added**:

When updating from k8s version 1.21 to 1.22 I received an error message upon cri.name being unsupported:
> for: "generated/shoot-d058015-orc.yaml": shoots.core.gardener.cloud "d058015-orc" is forbidden: [spec.provider.workers[0].cri.name: Unsupported value: "containerd": supported values: "docker" spec.provider.workers[1].cri.name: Unsupported value: "containerd": supported values: "docker"]

As I changed the k8s version and that is connected to the CRI solution on the hosts, and neither before nor after did set the cri spec I was confused by that error message. After discussion with gardener experts ([SAP internal reference](https://github.tools.sap/kubernetes-canary/issues-canary/issues/1909)) this is related to the host OS version, which does not support the default container runtime anymore. It would be an enhancement of the mentioned error message to point to the relation to the host OS here. Especially that the supported values set is deducted from that. (And other criteria if any)

Another error message I saw when updating was:
> The Shoot "d058015-orc" is invalid: spec.addons: Forbidden: addons can only be enabled on evaluation shoots for versions >= 1.22

As my shoot was an evaluation shoot for me and I was using 1.21 with addons before, I was confused by this error message in the reading that I have to have at least 1.22 to be allowed to use addons. What the error actually wants to say is that beginning from kubernetes version 1.22 the usage of addons is only allowed for shoots with spec.purpose being evaluation. I would therefore propose to enhance the message as follows:

> The Shoot "d058015-orc" is invalid: spec.addons: Forbidden: Beginning with Kubernetes version 1.22 addons can only be enabled on shoots that set spec.purpose: "evaluation".

<br class="Apple-interchange-newline">
**Why is this needed**:
To help the reader of the error messages to understand the problem. That reduces the load on giving support for experienced issues.

**Comment by ialidzhikov** [comment]
https://github.com/gardener/gardener/pull/5623 and https://github.com/gardener/gardener/pull/5637 should address this issue.

**Comment by ialidzhikov** [comment]
I am closing this issue as both PRs are merged.

/close
