### ISSUE TITLE
[GRM] Use different webhook names for the shoot and seed mutating webhook respectively

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#5636]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement

**What would you like to be added**:
The admission webhook name `projected-token-mount.resources.gardener.cloud` to be enhanced so that it can describe whether this is the GRM deployed in-the shoot or in the control plane for managed seed clusters.

**Why is this needed**:
It is not impassible, but it is hard to debug errors like:
```
Error creating: Internal error occurred: failed calling webhook "projected-token-mount.resources.gardener.cloud": Post "https://gardener-resource-manager.garden.svc:443/webhooks/mount-projected-service-account-token?timeout=10s": dial tcp 10.243.147.28:10250: i/o timeout
```

as there are two different mutatingwebhookconfigurations `gardener-resource-manager` and `gardener-resource-manager-shoot` configuring webhook `projected-token-mount.resources.gardener.cloud`.

**Comment by timebertt** [comment]
One could distinguish between these webhooks by checking the URL. E.g. 
- `https://gardener-resource-manager.garden.svc:443` points to the resource-manager deployed as a seed component
- `https://gardener-resource-manager.shoot--<project>--<shoot-name>:443` points to resource-manager deployed in the shoot control plane.

@vpnachev Is that be sufficient?
