### ISSUE TITLE
Cloud-config-downloader can invalidate its own token and stop working

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#5674]
**How to categorize this issue?**

/area ops-productivity quality 
/kind bug

**What happened**:
A shoot cluster node has temporary issue with its root filesystem, i.e. there was no space left on the device. At this time, the `cloud-config-downloader` may try to update the token value on the filesystem https://github.com/gardener/gardener/blob/d4ab9bfc38133473741eae930f379f1082adf35e/pkg/operation/botanist/component/extensions/operatingsystemconfig/downloader/templates/scripts/download-cloud-config.tpl.sh#L61

But this fails with
```
/var/lib/cloud-config-downloader/download-cloud-config.sh: line 61: echo: write error: No space left on device
```

Since then, the `cloud-config-downloader` is failing to connect to the API of the shoot with
```
Could not retrieve the shoot access secret with name cloud-config-downloader with existing token
```

Probably the write attempt corrupted/deleted the content of the token file which prevented `cloud-config-downloader` to do its job.

**What you expected to happen**:
The `cloud-config-downloader` should be more cautious when it is writing to critical files, like the token file. It could write it to a second file (eventually on `tmpfs` filesystem) and then move it to the token file only if the content differs.

**How to reproduce it (as minimally and precisely as possible)**:
I have not tried, but it should be possible to reproduce the `no space left on device`, e.g. with `dd` a large file can be created.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.42
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

cc @vlerenc

**Comment by rfranzke** [comment]
We discussed this in today's quality sync meeting, however, (if at all) we prefer a simple solution as you suggest: Writing the token to another file and then `mv`ing it to the original file if the content differs. What's the benefit of `tmpfs`? Is this complexity justified given that this seems to be a VERY rare issue (only seen once for thousands of VMs with tokens downloaded every minute or so). Do you agree?

**Comment by vpnachev** [comment]
No objections from my side, the idea with `tmpfs` was proposed by @vlerenc and I included it, but he can elaborate on it. 
It is indeed an issue that I have seen only once so far, but the token rotation is relatively new feature, ref: #5121, so we don't have much experience with it.

**Comment by vlerenc** [comment]
Wait, what? ;-) I wasn't proposing `tmpfs` @vpnachev. That would not work. The purpose of my proposal was to have it on the disk already and then move it. I wrote:

> Write token or any sensitive file for that matter first to temp file (here it was /var/lib/cloud-config-downloader/credentials/token) and when this succeeds, `mv` it over to the target destination (then we wouldn’t be impacted by a full file system)

I meant "temp file" on the same volume, so that `mv` is just a  "rename" preserving the inode. `tmpfs` or any volume wouldn't serve that purpose.

**Comment by rfranzke** [comment]
Thanks for clarification. I think this is reasonable, no matter of the fact that we just saw this once now. @plkokanov can you take care this week (it should be just a few more lines)?

**Comment by vpnachev** [comment]
> Wait, what? ;-) I wasn't proposing tmpfs @vpnachev. That would not work. 

You are right, I need to pay more attention and get the details of what I am reading, it is my fault :wink:

**Comment by vlerenc** [comment]
Yeah, I think it's probably a corner case, because in most cases the disk pressure doesn't go away by itself and then MCM will replace the node. Then again, who knows (what kind of GCs run) and now that we rotate and need the disk, we may see it more often.

And don't worry @vpnachev , I wasn't exact either. ;-)
