### ISSUE TITLE
Configuration Option for Kubelet Extra Args

### ISSUE THREAD

**Issue by jdrueckert** [gardener/gardener#5690]
**How to categorize this issue?**

Didn't see an area identifier for "configuration", so I'll go with these instead:
/area control-plane
/area usability

/kind enhancement
/kind api-change

**What would you like to be added**: An extension of `[v1beta1.KubeletConfig](https://gardener.cloud/docs/gardener/api-reference/core/#core.gardener.cloud/v1beta1.KubeletConfig)` with a configuration option for extra args to be passed to the Kubelet CLI.

**Why is this needed**:
Kubernetes developed a new [feature for applying the seccomp default profile to all workloads](https://kubernetes.io/docs/tutorials/security/seccomp/#enable-the-use-of-runtimedefault-as-the-default-seccomp-profile-for-all-workloads). This feature is currently only available as alpha and, thus, not enabled by default. To enable it, two additional args have to be passed when starting the Kubelet: `--feature-gates=SeccompDefault=true` and `--seccomp-default`.

The first one of the two can already be configured in the shoot spec via the `[v1beta1.KubernetesConfig](https://gardener.cloud/docs/gardener/api-reference/core/#core.gardener.cloud/v1beta1.KubernetesConfig)` of `[v1beta1.KubeletConfig](https://gardener.cloud/docs/gardener/api-reference/core/#core.gardener.cloud/v1beta1.KubeletConfig)`.

The second one currently cannot be configured because according to @hendrikKah "there is no option to supply additional flags".

**Comment by rfranzke** [comment]
It is on purpose that not all fields of the configuration are exposed, especially not those which are still alpha or experimental. However, you can help yourself by setting the `KUBELET_EXTRA_ARGS` environment variable on the worker nodes (https://github.com/gardener/gardener/blob/f3e414ecd8ff2b0a2143e569b57f93a25a18dc9f/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component.go#L127) and restart the `kubelet` systemd service.

**Comment by josephine-rueckert** [comment]
Hi @rfranzke 
We have the requirement to not do this manually for a single cluster but as a general part of our shoot configuration.
Is it possible to configure environment variables for the worker nodes as part of the gardener shoot config to achieve the "workaround" you proposed (without the need to restart the `kubelet` service)?

If not, I'd be interested in whether or not adding general support to configure kubelet extra args or at least support to configure this specific one can be included in your roadmap and if so, what the timeline would be.
FYI @vlerenc

**Comment by rfranzke** [comment]
I am having mixed feelings about allowing such general configuration because it will result in additional operational effort. Users will (even more easily than today) break their clusters because Gardener cannot validate such additional configuration in any meaningful way. That's why we only expose a certain subset of the flags for the Kubernetes components today.
Actually, this is a risk already today given that there is this `KUBELET_EXTRA_ARGS` environment variable in the `systemd` unit specification, however making it a first class citizen in the API will make it probably worse.

**Comment by josephine-rueckert** [comment]
I can totally understand that concern. How about only the specific `--seccomp-default` arg?
Being able to enable this feature for applying the seccomp default profile to all workloads would make it so much easier for people to create a more secure baseline for their clusters and workloads.

Alternatively: IIRC, gardener already enforces the AppArmor default profile for all workloads, right? (At least I noticed, that without adding the AppArmor annotation, my workloads were confined).
Are there plans on your side to apply this generally for seccomp as well? (which would obliterate the need for adding that arg in the shoot configuration)

**Comment by rfranzke** [comment]
> I can totally understand that concern. How about only the specific --seccomp-default arg?

Generally I have no objections exposing this, however the field is still alpha. We should probably wait for its beta promotion (at least) to prevent that incorporating it into our API now can result in avoidable migration efforts in the future in case they change this field when before promotion. Generally, https://github.com/gardener/gardener/pull/4282 is an exemplary PR for what needs to be done to expose such a new field.

> Alternatively: IIRC, gardener already enforces the AppArmor default profile for all workloads, right? (At least I noticed, that without adding the AppArmor annotation, my workloads were confined).
Are there plans on your side to apply this generally for seccomp as well? (which would obliterate the need for adding that arg in the shoot configuration)

I am not aware of any such enforcements or any plans 👀

**Comment by josephine-rueckert** [comment]
> We should probably wait for its beta promotion

Okay, fair enough. I don't think there's any official plans for bringing it to beta yet, but I found https://github.com/kubernetes/enhancements/pull/3240 which says it's targeting the v1.25 cycle.

> I am not aware of any such enforcements or any plans 👀

Not even for AppArmor? Interesting... then I need to double-check again, where this comes from 🤔
I was pretty sure it came from gardener, because the confinement was present even on a blank gardener cluster deployed via the dashboard without any additional configuration or deployment from our side...

**Comment by pre** [comment]
This was closed as `Completed` but it seems this is not available / has not been implemented?

Does this mean that a new Github issue feature request should be created to request this again?

**Comment by jdrueckert** [comment]
My bad, sorry. Just re-checked the K8s v1.25 enhancements list and it seems like the `--seccomp-default` field will indeed become beta with K8s v.125 planned to be released August 23rd.
