### ISSUE TITLE
Shoot cannot determine seed by profile and region in local scenario

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#570]
I follow [setup_local.md](https://github.com/gardener/gardener/blob/master/docs/development/local_setup.md#check-local-setup). The step that applies the shoot fails:
```bash
$ k apply -f dev/90-shoot-local.yaml
Error from server (Forbidden): error when creating "dev/90-shoot-local.yaml": shoots.garden.sapcloud.io "local" is forbidden: no adequate seed cluster found for this cloud profile and region
```

Meanwhile the seed is available.
As workaround when I set in `dev/90-shoot-local.yaml` in `.spec.cloud.seed` to `local` the admission validation passes.

It looks like the seed selection by `.spec.cloud.profile` and `.spec.cloud.region` does not work for the local scenario with:
```yaml
spec:
  cloud:
    profile: local
    region: local
[...]
```

I guess we need to improve the admission logic to handle also the local scenario. Guys, correct me if I am wrong or I miss something.

**Comment by rfranzke** [comment]
For the local setup the step of finding an appropriate seed does anyway not make sense, so your workaround is fine. If you want please file a PR that adds `.spec.cloud.seed` to the local manifest.
