### ISSUE TITLE
Enhance flow with additional functions

### ISSUE THREAD

**Issue by unmarshall** [gardener/gardener#5710]
**How to categorize this issue?**
  /area control-plane
  /kind enhancement

**What would you like to be added**:
Proposal is to add additional methods in the flow framework defined in `pkg/util/flow`

**Why is this needed**:

1. Enhance `RetryUtilTimeout` to also take a jitter 
2. Add a method in `TaskFn` to allow specifying exact number of `retryAttempts`, with a `delayInterval` and `exitConditionalFn` to exit early if the `func(error) bool` returns true.

**Comment by unmarshall** [comment]
Will submit a PR with the enhancements soon.

**Comment by timebertt** [comment]
> 1. [...]
> This allows construction of the Flow much earlier and delink constructing a flow from running a flow

Inside the task you can simply `return nil` if some condition is met. So I would consider, that this is already possible today.

> 3. [...]

This is probably also better done in the task itself to not bloat the flow definition more than it is already bloated.

**Comment by unmarshall** [comment]
Yes it is true that you can achieve by returning nil from within the task. In that case you do not even need `DoIf` as that can easily been part of the task itself. I think the intent was to separate out the triggering condition and the actual processing. I am only attempting to make it a bit generic by introducing a function which returns a boolean instead of just passing a pre-computed boolean to `DoIf`. 

In general if the argument is to remove any convenience functions which actually makes the `Flow` read like a Flow, then my suggestions can be dropped. Please confirm if this understanding is correct, if yes then please feel free to close this issue.

**Comment by timebertt** [comment]
> In general if the argument is to remove any convenience functions [...]

No, that's not the case. My main concerns are readability and also the fact, that having a "flow" implementation in kubernetes controllers is a technical debt in the first place. Hence, I would like to avoid adding more "features" or "convenience" to a package that should not be used more extensively than it already is today.

**Comment by unmarshall** [comment]
> My main concerns are readability and also the fact, that having a "flow" implementation in kubernetes controllers is a technical debt in the first place


If you have a sequence of activities to be performed which are then represented as a compound activity comprising of sequential and concurrent steps having dependencies amongst them, then i find having a flow kind of frameworks useful as they have the following benefits:

1. They allow breaking down extra-large methods/functions (which i have seen quite a lot unfortunately) into smaller logically cohesive units.
2. Each of these steps are then very well defined and separated allowing proper unit testing.
3. Code readability and therefore understandability significantly improves as the flow is concisely defined in well-named steps with well-named functions. In a nutshell you can see the entire flow of a set of activities that needs to be done.
4. A `Graph` helps collect otherwise not-so-clearly related activities into a `Flow` thereby establishing pre/post conditions (trigger points), retry, timeout and back-off capabilities which can be associated to individual steps.
5. A `Flow` also clearly depicts error handling scenarios and an impact of an error in a single step on other following steps in a clear manner be it a collection of concurrent or sequential or any combination thereof.

I am curious to the reasons of why it is considered a technical debt. In the end i do not wish to increase the technical debt by using a framework in newer developments where it was not used before.

**Comment by timebertt** [comment]
> I am curious to the reasons of why it is considered a technical debt. In the end i do not wish to increase the technical debt by using a framework in newer developments where it was not used before.

Reconciliations in kubernetes controller should be fast (think milliseconds) and should generally not wait for anything. Instead of waiting they should requeue or enqueue for relevant watch events.
Instead of using a flow, controllers should always observe the entire state of the world and then decide what's the next thing to do in order to converge to the desired state.

**Comment by unmarshall** [comment]
yes that is well understood. So as long as you do not use functions like `RetryUtilTimeout` using a `Flow` is still fine IMHO as it does not cause any additional delays, just arranges the set of activities that one wishes to do as part of the reconciliation either in sequential or concurrent manner.

Today in DWD (existing code), we have a lot of retries. I agree in general that retry'ing from within a reconciliation loop is not recommended but in case of DWD things are a bit different. It is not a typical controller reconciliation loop, it just watches for changes in cluster resources and creates/updates/deletes probes which run as go-routines. These probes periodically probe the shoot control plane API server and take decisions on scaling of specific resources like KCM, MCM, CA. So having a retry in a probe is not the same as having a retry in the main reconciliation loop of the controller.
We were only proposing to use `Flow` from within the Probe and not directly in the reconciliation loop. 

If you do not want to add additional methods which provide retry semantics then can you at least allow the addition of `DoIfFn`? Ideally this is more generic than `DoIf` and eventually you can also replace `DoIf` with `DoIfFn` and remove `DoIf`

**Comment by timebertt** [comment]
Go ahead, I don't object. I just wanted to understand the motivation and describe additional considerations.

**Comment by unmarshall** [comment]
Closing this issue as `DoIfFn` also does not get lazily evaluated. Will just make the predicate as implementation detail of the `TaskFn`. For the remainder of the proposals i will not add convenience functions to `Flow` but i have now added utility functions to where it will be used. Therefore this issue is no longer needed and can be closed.
