### ISSUE TITLE
Unable to authenticate against grafana Ingresses

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5723]
/area monitoring
/kind bug

**What happened**:
Unable to authenticate against grafana ingresses.

**What you expected to happen**:
To be able to authenticate against grafana ingresses

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new Shoot

2. Navigate to `grafana-operators` or `grafana-users` host.

3. Authenticate with the username/password from the corresponding `observability-ingress-<hash>` or `observability-ingress-users-<hash>` Secret.

4. Make sure that the authentication attempt fails with `401 Unauthenticated`.

**Environment**:

- Gardener version: 09e7c0528ba4dafa09e5ff53c5ae2b773b864cab
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
Thanks for noticing this @ialidzhikov!

This was introduced as part of https://github.com/gardener/gardener/pull/5608/commits/3397cb7147a7b9f02fce81a0b85a10c688494100.
It seems the `.data.auth` value is double base64-encoded (called here: https://github.com/gardener/gardener/blob/09e7c0528ba4dafa09e5ff53c5ae2b773b864cab/pkg/utils/secrets/basic_auth.go#L145 and implemented here: https://github.com/gardener/gardener/blob/ebe812bbee4b4058671e08253890d736855f8241/pkg/utils/encoding.go#L136-L141).

Probably we should change https://github.com/gardener/gardener/blob/ebe812bbee4b4058671e08253890d736855f8241/pkg/utils/encoding.go#L140 to

```golang
	return []byte(credentials)
```

(needs to be verified)

**Comment by ialidzhikov** [comment]
Thank you! I am able to confirm that it now works with your suggestion. In short, looks like previously we needed https://github.com/gardener/gardener/blob/ebe812bbee4b4058671e08253890d736855f8241/pkg/utils/encoding.go#L140 because we passed the Secret value to the helm chart. With #5608 we switched to client-go calls and client-go under the hood takes care to base64 the Secret data values. This is my explanation how we ended with double base64 encoded value.

I noticed that the fix from https://github.com/gardener/gardener/pull/5724 for some reason is not applied to existing clusters. Logic for the Secret data generation is changed and now generates a different value but for some reason the new value is not updated to the existing Secret. For newly created Shoots I can see the Secret data is the correct one. Do you know if this is expected/what might be the problem?

**Comment by rfranzke** [comment]
Thanks for taking the time to verify this!
Yes, for existing shoots the secret needs to be deleted and regenerated, so this works as expected. However, it only affects clusters which were already reconciled with the master branch, so the bug/regression was not yet released.
