### ISSUE TITLE
GCM configuration for projects doesn't require concurrentSyncs to be set, deploys 0 workers

### ISSUE THREAD

**Issue by SimonKienzler** [gardener/gardener#5758]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:

When not setting `controllers.project.concurrentSyncs` in the `ControllerManagerConfiguration` (but any other `project` setting), this isn't caught by the validation step and results in 0 workers being deployed, so the `Project` resource isn't reconciled.

**What you expected to happen**:

Either a validation failure stating that `controllers.project.concurrentSyncs` is a required value, so the user can make a consciuous choice about the number of workers. The helm template e. g. already marks this as required.

Or, when not explicitly setting the `concurrentSyncs` value, just use the default value of `5`. Maybe a pointer value could be used in order to distinguish between a `nil` value and a `0` value.

**How to reproduce it (as minimally and precisely as possible)**:

Change the `ControllerManagerConfiguration` in the according section to something like this:

```yaml
controllers:
  project:
    staleGracePeriodDays: 20
```

in the `gardener-controller-manager-configmap` by hand.

**Anything else we need to know?**:

Should be changed around here:

https://github.com/gardener/gardener/blob/eec37223cb90475ec3e023136a7d5ba28ad48f0d/pkg/controllermanager/apis/config/v1alpha1/defaults.go#L78

This also affects other controllers with similiar settings.

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
Feel free to pick this up!
/help
