### ISSUE TITLE
Add support for HTTP LBs on GCP

### ISSUE THREAD

**Issue by harsimranmaan** [gardener/gardener#578]
While using Gardener with GCP, there is no support to add an [HTTPS LB](https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer). On GKE, it is possible to setup an ingress of class `gce` but on gardener, that annotation value is not supported for values other than `nginx`. Using nginx adds a TCP LB and not an HTTPS lb. 
HTTPS LB comes with features like out the box CDN support which make managing CDN simple and cost-effective. 

Supporting `kubernetes.io/ingress.class: "gce"` would resolve this.

**Comment by vlerenc** [comment]
I guess, this is about https://github.com/kubernetes/ingress-gce and I would assume you might be able to deploy it yourself, though I have not tried that. We have deployed nginx anyways only as default ingress controller and might pull it out/will pull it out eventually. We definitely don't want to be opinionated and offering nginx might even go too far (Gardener is an Open Source project and we, doing the backbone, select only general controllers/solutions if possible, that work across all infrastructures). However, we do our best to not "force" certain properties onto the clusters needlessly, so you can tweak it and install the components you like to use. By large, it would be impossible for us to offer all controllers that are out there for all the infrastructures. Our main concern is the cluster offering as such, not so much the additional software you install on top. We'd like to do more here, but would basically be a separate project on its own.

**Comment by harsimranmaan** [comment]
I followed the guide at https://github.com/kubernetes/ingress-gce/tree/master/examples/deployment to deploy on k8s 1.12.3 on Gardener but the GLBC container does not pass the livelinessProbe and crashes. I could not find anything valuable in the logs. Is there a way to debug this?

**Comment by vlerenc** [comment]
Sorry, we don't know. If the controller fails and the log doesn't help with the problem, then it's also hard for us, because we can't debug all controllers the people want to run in Gardener clusters. When you have cracked the problem and we can do something to improve, we are very open to consider, of course.

**Comment by harsimranmaan** [comment]
From further reading through the source, I am able to get to a state where the controller is being deployed but calls to GCP are failing as being unauthorized despite setting up correct? credentials. Would continue investigating this further. If I find a solution, I'll publish it here.
