### ISSUE TITLE
Use `--kubeconfig` flag for VPA components when deployed for shoot

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#5824]
**How to categorize this issue?**

/area open-source
/kind cleanup

**What would you like to be added**:
Now that we have upgraded the VPA components to `0.10` (#5716) we can switch them to use the `--kubeconfig` flag (for example https://github.com/kubernetes/autoscaler/blob/06ad568730252b9c7e6defdd71518a272069f11e/vertical-pod-autoscaler/pkg/admission-controller/main.go#L60 for the `vpa-admission-controller`).
Today, we are using a workaround when we deploy VPA for the shoots because the `--kubeconfig` flag was not available prior to `0.10` (ref https://github.com/kubernetes/autoscaler/pull/3769).

Concretely, we are overwriting the `KUBERNETES_SERVICE_*` environment variable and mount the CA certificate and token to `/var/run/secrets/kubernetes.io/serviceaccount` (the location where `client-go` expects to find the in-cluster configuration): https://github.com/gardener/gardener/blob/fa79a59d4611acd677e67c213d55907bd407eb48/pkg/operation/botanist/component/vpa/vpa.go#L403-L451

Instead, we should now simply use the `generic-token-kubeconfig` and pass the `--kubeconfig` flag to the components (like for all other components, e.g. https://github.com/gardener/gardener/blob/fa79a59d4611acd677e67c213d55907bd407eb48/pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager.go#L320 and https://github.com/gardener/gardener/blob/fa79a59d4611acd677e67c213d55907bd407eb48/pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager.go#L479

**Why is this needed**:
Get rid of custom code/workaround.

**Comment by rfranzke** [comment]
#5915 addresses the topic for `vpa-recommender` and `vpa-updater`. It is not possible for `vpa-admission-controller` due to https://github.com/kubernetes/autoscaler/issues/4844, so let's keep this issue closed for now until this is fixed and we can address it.

**Comment by shafeeqes** [comment]
https://github.com/kubernetes/autoscaler/issues/4844 is closed now. Let's wait for a release with the changes.
