### ISSUE TITLE
Unable to create K8s 1.17 Shoots

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5839]
/area quality
/kind bug
/kind regression

**What happened**:
Unable to create K8s 1.17 Shoots.

**What you expected to happen**:
To be able to create K8s 1.17 Shoots.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a K8s 1.17.17 Shoot

2. Make sure that the creation fails with:

```yaml
  lastErrors:
    - description: >-
        task "Waiting until the Kubernetes API server can connect to the Shoot
        workers" failed: retry failed with context deadline exceeded, last
        error: could not forward to vpn-shoot pod (timeout after 5 seconds):
        error forwarding ports: error upgrading connection: error dialing
        backend: dial tcp 10.250.5.46:10250: i/o timeout
      taskID: Waiting until the Kubernetes API server can connect to the Shoot workers
      lastUpdateTime: '2022-04-21T11:53:46Z'
```

The vpn-seed sidecar container fails to connect to the apiserver while fetch the vpn-shoot Service:
```
$ k -n shoot--foo--bar logs kube-apiserver-59b46dfc5b-h5d9w vpn-seed

[Thu Apr 21 11:55:39 UTC 2022]: No tunnel endpoint found
[Thu Apr 21 11:55:44 UTC 2022]: trying to identify the endpoint (load balancer name of vpn-shoot service) myself...
[Thu Apr 21 11:55:44 UTC 2022]: error: could not identify any endpoints
[Thu Apr 21 11:55:44 UTC 2022]: No tunnel endpoint found
[Thu Apr 21 11:55:49 UTC 2022]: trying to identify the endpoint (load balancer name of vpn-shoot service) myself...
[Thu Apr 21 11:55:49 UTC 2022]: error: could not identify any endpoints
[Thu Apr 21 11:55:49 UTC 2022]: No tunnel endpoint found
[Thu Apr 21 11:55:54 UTC 2022]: trying to identify the endpoint (load balancer name of vpn-shoot service) myself...
[Thu Apr 21 11:55:54 UTC 2022]: error: could not identify any endpoints
[Thu Apr 21 11:55:54 UTC 2022]: No tunnel endpoint found
```

The failing part is https://github.com/gardener/vpn/blob/4d6e7282c4e995b84b5099a6a24028f0d19ebfc3/seed/network-connection.sh#L56-L66.

```
/ # curl -vvv \
>         --connect-timeout 5 \
>         --max-time 5 \
>         --silent \
>         --cacert /srv/secrets/vpn-seed/ca.crt --cert /srv/secrets/vpn-seed/tls.crt --key /srv/secrets/vpn-seed/tls.key \
>         --header "Accept: application/json" \
>         --request GET \
>         "https://kube-apiserver/api/v1/namespaces/kube-system/services/vpn-shoot"
*   Trying 10.243.86.187:443...
* TCP_NODELAY set
* Connection timed out after 5001 milliseconds
* Closing connection 0
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: 61e391ecb37013c8fa0637136bb03ba9f4ddac91
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
What is the issue here, i.e. why is the `vpn-seed` unable to connect?

**Comment by acumino** [comment]
`kube-apiserver` logs are filled with 
```
I0421 11:47:31.790068       1 aggregator.go:229] Finished OpenAPI spec generation after 643.234728ms
I0421 11:47:32.911152       1 log.go:172] http: TLS handshake error from 127.0.0.1:54314: local error: tls: bad record MAC
E0421 11:47:34.287614       1 authentication.go:104] Unable to authenticate the request due to an error: x509: certificate
signed by unknown authority
E0421 11:47:34.996896       1 authentication.go:104] Unable to authenticate the request due to an error: x509: certificate
signed by unknown authority
E0421 11:47:36.150202       1 authentication.go:104] Unable to authenticate the request due to an error: x509: certificate
signed by unknown authority
I0421 11:47:37.964542       1 log.go:172] http: TLS handshake error from 127.0.0.1:54336: local error: tls: bad record MAC
E0421 11:47:37.994918       1 authentication.go:104] Unable to authenticate the request due to an error: x509: certificate
signed by unknown authority
```

**Comment by rfranzke** [comment]
Unfortunately, I will be OOO soon, so I can't try myself, but maybe it is because of https://github.com/gardener/gardener/blob/a64cf673641b14692c7a1656bf67302e8c154577/pkg/operation/botanist/component/kubeapiserver/secrets.go#L328 - can you try changing this to `secretsmanager.SignedByCA(v1beta1constants.SecretNameCACluster)`?
I see that the cluster CA is used in `vpn-shoot` when the `ReversedVPN` feature is disabled (https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/vpnshoot/vpnshoot.go#L157) but here we sign with the client CA which is a mismatch.

**Comment by acumino** [comment]
> Unfortunately, I will be OOO soon, so I can't try myself, but maybe it is because of
> 
> https://github.com/gardener/gardener/blob/a64cf673641b14692c7a1656bf67302e8c154577/pkg/operation/botanist/component/kubeapiserver/secrets.go#L328
> 
> - can you try changing this to `secretsmanager.SignedByCA(v1beta1constants.SecretNameCACluster)`?
> I see that the cluster CA is used in `vpn-shoot` when the `ReversedVPN` feature is disabled (https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/vpnshoot/vpnshoot.go#L157) but here we sign with the client CA which is a mismatch.

I will try. Thanks.

**Comment by acumino** [comment]
```
/ # curl -vvv \
>         --connect-timeout 5 \
>         --max-time 5 \
>         --silent \
>         --cacert /srv/secrets/vpn-seed/ca.crt --cert /srv/secrets/vpn-seed/tls.crt --key /srv/secrets/vpn-seed/tls.key \
>         --header "Accept: application/json" \
>         --request GET \
>         "https://127.0.0.1/api/v1/namespaces/kube-system/services/vpn-shoot"
```
Gives following error 
`Unable to get Local Issuer Certificate`

We need to use ca.crt here to mitigate the issue https://github.com/gardener/gardener/blob/28329fd8a93051f6c8cd92767cd5a981e52be589/pkg/operation/botanist/component/kubeapiserver/deployment.go#L741-L744

This seems to solve the issue describe above 

```
{
	Name:  "APISERVER_AUTH_MODE_CLIENT_CERT_CA",
	Value: volumeMountPathCA + "/" + secrets.DataKeyCertificateCA,
},
```
