### ISSUE TITLE
Project `lastActivityTimestamp` should not only consider `creationTimestamp` of objects

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#5858]
**How to categorize this issue?**

/area usability
/kind bug

**What happened**:
Today, the `Project` activity controller only considers the `creationTimestamp` of `Shoot`s (with #5821 also other objects are considered), see https://github.com/gardener/gardener/blob/e8999347e1367cdc9d108fd6b03446bd0a9040ad/pkg/controllermanager/controller/project/project_activity_control.go#L83-L85.
If a `Shoot` exists for a long time then the `Project` is still actively used, however the `lastActivityTimestamp` will never be updated accordingly.

**What you expected to happen**:
If there are still relevant resources in the `Project` then the `lastActivityTimestamp` should be set to the current time with each reconciliation.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a `Project` and a `Shoot`
2. Check that the `Project`'s `.status.lastActivityTimestamp` was set to the `creationTimestamp` of the `Shoot`
3. Restart the `gardener-controller-manager` to trigger a new reconciliation for the `Project` activity controller
4. See that the `.status.lastActivityTimestamp` is still the same

**Anything else we need to know?**:
The `Project` stale controller checks the `lastActivityTimestamp` here: https://github.com/gardener/gardener/blob/e8999347e1367cdc9d108fd6b03446bd0a9040ad/pkg/controllermanager/controller/project/project_stale_control.go#L113-L117
Hence, if a `Project` does not create new `Shoot`s for longer than the configured minimum lifetime, the `Project` could be considered as "stale". However, there is a "duplicate" check for existing resources: https://github.com/gardener/gardener/blob/e8999347e1367cdc9d108fd6b03446bd0a9040ad/pkg/controllermanager/controller/project/project_stale_control.go#L119-L134

Potentially this duplicated check should be removed so that we don't have checks for the relevant resources twice (once in the activity controller and once in the stale controller).

cc @oliver-goetz @kris94 

**Environment**:

- Gardener version: `master`

**Comment by rfranzke** [comment]
Potentially it makes sense to work on this only after #5821 got merged

**Comment by shafeeqes** [comment]
From https://github.com/gardener/gardener/blob/master/docs/concepts/controller-manager.md#stale-projects-reconciler,

" Projects are considered as "stale"/not actively used when all of the following conditions apply: The namespace associated with the Project does not have any...
* Shoot resources.
* Plant resources.
* BackupEntry resources.
* Secret resources that are referenced by a SecretBinding that is in use by a Shoot (not necessarily in the same namespace).
* Quota resources that are referenced by a SecretBinding that is in use by a Shoot (not necessarily in the same namespace).

The time period when the project was used for the last time (status.lastActivityTimestamp) is longer than the configured minimumLifetimeDays."


So even if the lastActivity is old enough, can we consider it stale if these resources exist in the namespace?
Then, Isn't this check still valid?
https://github.com/gardener/gardener/blob/e8999347e1367cdc9d108fd6b03446bd0a9040ad/pkg/controllermanager/controller/project/project_stale_control.go#L119-L134

**Comment by rfranzke** [comment]
> So even if the lastActivity is old enough, can we consider it stale if these resources exist in the namespace?
Then, Isn't this check still valid?

How can the `lastActivityTimestamp` be old enough when there are still resources in the namespace?

**Comment by shafeeqes** [comment]
When resources are created, but not updated for a long time?

**Comment by rfranzke** [comment]
Right, well, then we close this issue and keep everything as is?

**Comment by shafeeqes** [comment]
I think so, since the major concern of this issue is already addressed in #5821.

**Comment by rfranzke** [comment]
OK, sounds good
/close
