### ISSUE TITLE
[Flaky Test] Credentials rotation e2e test failing with `too many worker nodes are registered`

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#5895]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:

`E2E Test Suite: [It] Shoot Tests Create Shoot, Rotate CA and Delete Shoot`

**CI link**:

https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind/1521323003185467392
https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind/1519812618934554624
https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind/1519329201906257920
https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind/1518876991296638976

**Reason for failure**:

In all cases, the test seems to run into a timeout waiting for the shoot to be reconciled in step `Start CA rotation`:
```
    STEP: Start CA rotation 05/03/22 03:10:22.149
# roughly 10 minutes later
    {"level":"info","msg":"Shoot rotate-ca-gz76g not yet reconciled successfully (condition type EveryNodeReady is not true yet, had message Worker extension (shoot--local--rotate-ca-gz76g/rotate-ca-gz76g) reports failing health check: too many worker nodes are registered. Exceeding maximum desired machine count (2/1). with reason WorkerUnhealthyReport)","ts":"2022-05-03T03:19:52.470Z"}
    [AfterEach] Shoot Tests
```

`too many worker nodes are registered. Exceeding maximum desired machine count (2/1)` leads me to think that the old machine pod is stuck in `Terminating` state after machine rollout triggered by the CA rotation.
I think, I have also observed this once locally.

**Anything else we need to know**:

Interestingly enough, in the successful case termination seems to happen much faster and the timeout is not close to be reached.
It seems, the machine pod either terminates quickly or not at all.

**Comment by shafeeqes** [comment]
Another failure, but the error seems to be different.
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/5938/pull-gardener-e2e-kind/1524242997997211648#

**Comment by timebertt** [comment]
Another instance: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind/1526760693599047680
@plkokanov you are assigned to this issue, are you still working on it?

**Comment by plkokanov** [comment]
No I'm not working on it anymore, but I also got unassigned a couple of days ago, it just wasn't with the unassign command.

**Comment by timebertt** [comment]
Another instance: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind/1537273187778170880
