### ISSUE TITLE
Introduce subresource for binding `Shoot`s to `Seed`s

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#5913]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement

**What would you like to be added**:
Today, the `.spec.seedName` field of the `Shoot` resource can be changed via regular update requests. Especially in combination with an enabled `SeedChange` feature gate, end-users can now set `.spec.seedName=nil` which leaves the entire control plane resources orphaned in the seed cluster.

In the past, the `.spec.seedName` field was immutable, but now with the option to change it during `Shoot` lifetime, let's introduce a subresource `shoots/binding`. Only via this subresource it shall be possible to change the `.spec.seedName`. End-users would not get the RBAC permission for it, hence they wouldn't be allowed to change it.

I suggest following what Kubernetes does (they also have a subresource for binding `Pod`s to`Node`s) - https://gist.github.com/kelseyhightower/2349c9c645d32a3fcbe385082de74668 is a pretty good example for what we envision.

**Why is this needed**:
Prevent end-users from changing the seed (this should be done only be `gardener-scheduler` or operators).

**Comment by vlerenc** [comment]
Cosmetic: How about `shoots/scheduling` instead or `shoots/seed` if it's that specific?

**Comment by rfranzke** [comment]
No strong opinion, I was suggesting `binding` because that's how Kubernetes is calling it (https://github.com/kubernetes/kubernetes/blob/6605e526b05da23fee67cdbb59cc6df29ebfb6e5/pkg/registry/core/rest/storage_core.go#L288), and we are doing similar things with `Shoot`s/`Pod`s and `Seed`s/`Node`s
