### ISSUE TITLE
Support for a single worker pool with min=0

### ISSUE THREAD

**Issue by unmarshall** [gardener/gardener#5952]
**How to categorize this issue?**
/area control-plane
/kind discussion

**What happened**:
DWD only interacts with shoot control plane components apart from a `Cluster` resource. For writing integration tests for DWD we only need a seed with the control plane of a shoot under test. There is no need to spin up worker nodes. Currently there is a limitation being enforced wherein if there is a single worker pool created for the cluster, then `workers.minimum` cannot be 0 it has to be a minimum of 1. However, if more than 1 worker pool is there then barring 1, rest all of the worker pools can have `workers.minimum` set to 0.

**What you expected to happen**:
I wish to have an ability to only have a shoot control plane being provisioned and have the worker provisioning as optional. This could be achieved if the current constraint of having `workers.minimum=1` for a single worker pool  is relaxed and allows it to be 0. Then, using test machinery one could only provision a shoot control plane without provisioning a worker which not only takes time but also adds unnecessary cost as this worker will be quite useless from the perspective of the tests.

What were the reasons for having this constraint?

**Comment by timebertt** [comment]
If you are only concerned about testing, it is probably more sensible to simply use provider-local for e2e tests of dependency-watchdog.
You could take a look at https://github.com/gardener/gardener/blob/master/hack/test-e2e-local.sh, https://github.com/gardener/gardener-extension-shoot-oidc-service/blob/master/hack/test-e2e-provider-local.sh and https://github.com/gardener/ci-infra/blob/master/config/jobs/extension-shoot-oidc-service/extension-shoot-oidc-service-e2e-kind.yaml.

**Comment by unmarshall** [comment]
Currently testing is the scope. I wait for https://github.com/gardener/gardener/pull/5937 to be merged so that KIND cluster supports DWD prober. Once that is merged then it would definitely be sensible to use the KIND cluster instead of test machinery as DWD does not interact or need worker machines.
Thanks for the links - i think this was also presented in the last core weekly review meeting and i also made a note of it.

@vlerenc  also mentioned that vasu requested for "control plane as a service" feature, so i opened this issue to understand why the current constraint has been put and whether there are use cases where control-plan only would be useful.

**Comment by vlerenc** [comment]
@unmarshall This is the ticket that was opened back then: https://github.com/gardener/gardener/issues/1907

It was opened by @vpnachev, but I "think" @vasu1124 brought it up some time before, though I am not sure anymore.

**Comment by timebertt** [comment]
> Currently testing is the scope. I wait for #5937 to be merged so that KIND cluster supports DWD prober. Once that is merged then it would definitely be sensible to use the KIND cluster instead of test machinery as DWD does not interact or need worker machines. Thanks for the links - i think this was also presented in the last core weekly review meeting and i also made a note of it.

https://github.com/gardener/gardener/pull/5937 is merged now. So I think, we can
/close
this issue.

**Comment by afritzler** [comment]
@unmarshall if you are interested in running a Kubernetes control plane in your cluster you could use the following project from the @onmetal team: https://github.com/onmetal/matryoshka

It allows you to deploy the `kube-apiserver` and `kube-controller-manager` via CRs into your cluster. You can find the sample manifest here: https://github.com/onmetal/matryoshka/tree/main/config/samples

Together with the `cert-manager` and Gardener's [etcd-druid](https://github.com/gardener/etcd-druid) operator you can spin up relatively quickly a fully functional headless Kubernetes with automatic backup and restore (via etcd-druid) and certificate creation/rotation via the `cert-manager`.

/cc @adracus @vasu1124
