### ISSUE TITLE
Convert API packages to submodules

### ISSUE THREAD

**Issue by clebs** [gardener/gardener#5978]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement

**What would you like to be added**:

Make the API packages f gardener submodules for easier usage by clients. See example on the prometheus operator:
https://github.com/prometheus-operator/prometheus-operator/tree/main/pkg%2Fapis%2Fmonitoring

**Why is this needed**:

Currently when importing the gardener API packages to be able to use gardener, Go clients are transitively importing all the dependencies gardener uses in its internal implementation, which is not necessary at all.

Importing that amount of modules transitively makes it very hard for clients to get built and maintained. Additionally it makes security issues very hard to mitigate.

**Comment by timebertt** [comment]
Dedicated go modules in the same repo is painful as experience has shown. As stated in https://github.com/gardener/gardener/issues/2871#issuecomment-949526277, we would need a full sync-out mechanism like kubernetes to better deal with this.

However, since https://github.com/gardener/gardener/pull/5347 we have restricted the imports quite significantly for API packages, so importing them should not pull in any undesired dependencies.
Can you clarify which dependencies you are talking about?

**Comment by clebs** [comment]
Hi @timebertt,
thanks for the quick response! Currently I am importing gardener `1.46.2` here: https://github.com/kyma-project/hydroform/tree/main/provision. This is causing issues when transitively importing things like helm 2.16, yaml.v2, a very outdated version of k8s.io/client-go, etc...

I am able to replace them sometimes with the ones I need but it is not always possible. Additionally, even if possible, our security scans generate false positives because the replace directive is not properly understood by the tool.

I had a look at the other issue (sorry, did not find it on the tracker...) and I would be really interested in knowing why it is such a problem to make `apis` a submodule; I am intending to do the same for an upcoming operator we are preparing right now.

**Comment by tobiscr** [comment]
@timebertt and @rfranzke , thanks for your reply! But we would really like to challenge whether there is no chance to get this change in place. It's quite painful for us and we see risks, that it will cause collisions sooner or later and we get blocked in our deliveries. 

Any chance to bring this topic back on your agenda?

With Go 1.18 was also the support for modularisation improved (see [link](https://go.dev/blog/get-familiar-with-workspaces)).

**Comment by rfranzke** [comment]
It might be worth taking another look (especially at the new improvements with recent Go versions), but I doubt that we can change something short-term given that we are focusing on security-related topics these days (and the summer vacation period is just about to start).

**Comment by timebertt** [comment]
I recently got aware of the go workspaces feature as well, which might indeed reduce the pain of having multiple modules in the same repository.
But even if that eases the pain, I still think we need a fully-fledged sync-out mechanism like kubernetes as stated multiple times, see https://github.com/gardener/gardener/issues/2871#issuecomment-949526277.
We currently don't have this yet. However, this should be achievable by replicating config, prow jobs, etc. from k/k. 

@clebs @tobiscr are you interested in contributing this enhancement?
If so, feel free to `/assign` yourself to this issue.

**Comment by clebs** [comment]
Hi @timebertt, @rfranzke,

thanks for the response and looking into it again. I am very interested in learning more about the challenges this poses and why this sync-out is necessary.

I would also be happy to help with the topic when I can see the full picture.

**Comment by lautoma** [comment]
@timebertt or @rfranzke it would be great if you could meet with @clebs to explain your challenges and how he could contribute. Thanks!

**Comment by timebertt** [comment]
ref https://github.com/gardener/hvpa-controller/issues/92

**Comment by clebs** [comment]
Hi @timebertt,
thanks for the feedback. If I understand correctly, the issue is the ambiguous import. I also faced this and the problem was not solvable for some time in the past because the nested module support was not fully added until later.

Right now we are able to solve the problem by running `go mod tidy --compat=1.17`. Not sure if you tried this solution recently.
