### ISSUE TITLE
Improve error message about shoot hibernation admission

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#5981]
**How to categorize this issue?**

/area ops-productivity usability
/kind enhancement

**What would you like to be added**:
The error message forbidding shoot to be hibernated when hibernation is not allowed to be improved, ref: https://github.com/gardener/gardener/blob/64869baf1aa7cca708dcb174ba59b2549ecad216/plugin/pkg/shoot/validator/admission.go#L501

**Why is this needed**:
Sometimes the hibernation constraint have such `message` that is misleading when shoot update request is rejected, e.g.
```bash
$ kubectl patch shoots foo -p '{"spec": {"hibernation": {"enabled": true}}}'
Error from server (Forbidden): shoots.core.gardener.cloud "foo" is forbidden: Gardenlet stopped sending heartbeats.
```

Indeed gardenlet was down, but I started thinking in wrong direction - why gardener API server cares about the availability of gardenlet? It turn out that this error message is the message from the `HibernationPossible` constraint:

```bash
$ k get shoot foo -o yaml | yq  '.status.constraints[] | select(.type=="HibernationPossible")'
lastTransitionTime: "2022-05-12T13:41:47Z"
lastUpdateTime: "2022-05-12T13:41:47Z"
message: Gardenlet stopped sending heartbeats.
reason: StatusUnknown
status: Unknown
type: HibernationPossible
```

**Comment by timebertt** [comment]
Yep, good suggestion, that is confusing indeed.

Let's keep the current error message only for `constraint.Status == False` and add some more context for `constraint.Status == Unknown`.
