### ISSUE TITLE
CPM integration tests fail due to labels and data not being persisted for some secrets

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#5992]
**How to categorize this issue?**

/area control-plane-migration
/kind bug

**What happened**:
Control plane migration tests fail with the following errors:
```
2022-05-17 23:03:38 | In [AfterEach] at: /src/test/testmachinery/system/shoot_cp_migration/migrate_test.go:100
2022-05-17 23:03:38 | The Shoot CP Migration health checks failed with: the following secrets did not have their data or labels persisted during control plane migration: [observability-ingress]
```

**What you expected to happen**:
Tests to complete successfully

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot and wait for it to be reconciled. Get the `observability-ingress` secret from the shoot's control plane namespace, then immediately migrate it to a new seed. Compare the initial `observability-ingress` secret with the one deployed in the shoot's control plane namespace on the new seed

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.46.2

**Comment by ialidzhikov** [comment]
Can this issue be closed after https://github.com/gardener/gardener/pull/6011?

**Comment by plkokanov** [comment]
I guess. I wanted to wait until the tests pass the erroneous step before closing it though.

**Comment by ialidzhikov** [comment]
The previously failing `migrate-shoot` step is now successful (with `v1.48.0-dev-8f819ffab82898c65be19a4376aeec3b5627c3ba`).

![Screenshot 2022-05-27 at 9 16 41](https://user-images.githubusercontent.com/9372594/170641859-172164ed-fa63-4f78-86f9-bc88f614ae90.png)

/close
