### ISSUE TITLE
[GCP] Seed clusters' kubelets can't be scraped by Prometheus

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#60]
We directly scrape the `kubelets` for both seed and shoot clusters. On GCE the Token Review API is [disabled](https://github.com/kubernetes/kubernetes/issues/44330#issuecomment-294023219), breaking the kubelet seed scraping.

We have 2 options to mitigate this problem:

- generate a certificate for Prometheus using the CSR API
- use the api-server's proxy capabilities

Both have downsides.

**Comment by vlerenc** [comment]
@DockToFuture, @mliepold What's the status of this ticket?

**Comment by mliepold** [comment]
@mvladev Following the linked issue, it seems that the community prefers the 2nd option using the api-servers proxy cababilities. So we will test this option locally to see if it is feasible.

**Comment by rfranzke** [comment]
@mvladev, do you mean GKE or GCE? Is this relevant at all as we plan to shoot the Seeds itself?

**Comment by mvladev** [comment]
`GKE`

**Comment by rfranzke** [comment]
Ok, so answer to second question would be "no"?

**Comment by mvladev** [comment]
I would go with `api-server` proxy

**Comment by rfranzke** [comment]
So you say it's still relevant? Why?

**Comment by rfranzke** [comment]
Not relevant anymore because the Seed clusters are setup on GCE and not GKE.
