### ISSUE TITLE
☂️ Improve Gardener Development Productivity

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#6016]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement

**What would you like to be added**:

### 📖 Documentation

- [x] https://github.com/gardener/gardener/pull/6245

### 🧪 Testing

- Enable more e2e tests based on existing TestMachinery tests
  - [x] https://github.com/gardener/gardener/pull/6293
- Improve debugging experience for failing e2e tests
  - [x] https://github.com/gardener/gardener/pull/6088
  - [x] https://github.com/gardener/gardener/pull/6089
  - [x] dump container logs of e2e test even if test fails before `make test-e2e-local` ([example](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6059/pull-gardener-e2e-kind/1536257947749847040)): see https://github.com/gardener/gardener/pull/6089#issuecomment-1164029426 (done with https://github.com/gardener/gardener/pull/5987)
  - [x] https://github.com/gardener/gardener/pull/6589
  - [x] https://github.com/gardener/gardener/pull/6581
- Implement automated Gardener upgrade tests to catch more regressions between gardener versions
  - [x] https://github.com/gardener/gardener/issues/2692
- [x] https://github.com/gardener/gardener/issues/6281
- [x] allow executing tests with `pkg/envtest` (gardener envtest) against an existing gardener setup for debugging/deflaking: https://github.com/gardener/gardener/pull/6497
- [x] https://github.com/gardener/gardener/pull/6455
- [x] automate creation of release branch specific test jobs in prow: https://github.com/gardener/ci-infra/pull/407
- [x] https://github.com/gardener/gardener/pull/7431

### 👨🏼‍💻 Development Productivity

- [x] add verifier for consistent import aliases https://github.com/gardener/gardener/pull/7279
  - something like k/k's [`hack/verify-import-aliases.sh`](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-import-aliases.sh)
  - or enable `importas` golangci-lint linter (https://golangci-lint.run/usage/linters/#importas / https://github.com/julz/importas)
- [x] 🪝 https://github.com/gardener/gardener/issues/2754
- [x] ~Continuous deployment from `master` to DEV landscape~ (Abandoned/dropped from this umbrella issue since it would rather make sense to have an open-source landscape for continuous deployments and release validation. If desired/necessary in the future, we can track the tasks separately.)
- [x] No more development freeze during release validation; release from release branch
  - [x] https://github.com/gardener/cc-utils/pull/827
  - [x] https://github.com/gardener/cc-utils/pull/851
- [x] https://github.com/gardener/gardener/pull/6627
- [x] Improve automated PR reviewer assignment
  - [x] https://github.com/gardener/ci-infra/pull/327
  - [x] https://github.com/gardener/gardener/pull/6405
- [x] https://github.com/gardener/gardener/pull/7540
- [x] https://github.com/gardener/ci-infra/pull/561
- [x] Enforce import ordering: https://github.com/gardener/gardener/pull/7349
- [x] Enforce license headers: https://github.com/gardener/gardener/pull/7680
- [x] Split `make generate` into multiple rules (`make generate-mocks`, `make generate-api`) - potentially re-use the `WHAT` environment approach that also k/k uses: https://github.com/gardener/gardener/pull/8289
- [x] stop reading `/charts` from file system and use go embedded fs everywhere (including `images.yaml`)
  - https://github.com/gardener/gardener/pull/8237
  - https://github.com/gardener/gardener/pull/8243
  - https://github.com/gardener/gardener/pull/8250
- [x] Reduce the number of manual tasks for the release responsible
  - https://github.com/gardener/ci-infra/pull/776
  - https://github.com/gardener/ci-infra/pull/789

### 💻 `provider-local` / Local Setup

- [x] https://github.com/gardener/gardener/issues/6258
- [x] https://github.com/gardener/gardener/issues/6582
- [x] https://github.com/gardener/gardener/pull/6301
- Elimination of `provider-local`'s [limitations](https://github.com/gardener/gardener/blob/master/docs/extensions/provider-local.md#current-limitations):
  - Prerequisite for running `ManagedSeed` e2e tests:
    - [x] https://github.com/gardener/gardener/pull/6076
    - [x] ~~Support load balancers for shoot clusters~~: Not needed for now since there is no use-case.
  - Prerequisite for even more development use-cases:
    - [x] Support for fully reliable multi-node shoot clusters: https://github.com/gardener/gardener/pull/6166
  - Prerequisite for CPM Bad Case e2e tests:
    - [x] ~~Support for owner TXT `DNSRecord`s~~: Not needed since CPM bad case is planned to be abandoned.
- [x] https://github.com/gardener/gardener/issues/5548
- [x] Enhance DNS handling (drop `sudo` requirement, make custom CoreDNS server available in developer machine): https://github.com/gardener/gardener/pull/6997
- [x] Make it easy to register extensions (improve/refine docs for kind cluster with complete examples for extensions (provider, networking, OS, etc.)) https://github.com/gardener/gardener/pull/6678 (@oliver-goetz)
- [x] https://github.com/gardener/gardener/pull/7673
- [x] ~~Setup e2e tests for extensions based on gardener-on-kind and Prow (“manually” register needed Gardener resources and execute existing integration tests)~~ (abandoned/dropped from this umbrella issue since it's too large - consider tracking this separately)
- [x] https://github.com/gardener/gardener/pull/8075
  - [x] https://github.com/gardener/gardener/pull/8151
  - [x] https://github.com/gardener/gardener/pull/8194
- [x] https://github.com/gardener/gardener/issues/6062
- [x] https://github.com/gardener/gardener/pull/7755
- [x] https://github.com/gardener/gardener/issues/7284
- [x] https://github.com/gardener/gardener/pull/6554
- [x] https://github.com/gardener/gardener/pull/6781
- [x] https://github.com/gardener/gardener/pull/7659
- [x] https://github.com/gardener/gardener/pull/6591
- [x] ~~allow deploying existing images (`make gardener-deploy`?)~~ (not required anymore, because building images locally with KO is considered as fast enough)
- [x] https://github.com/gardener/gardener/pull/6730
- [x] https://github.com/gardener/gardener/issues/7116
- Support e2e tests running on GardenLinux 934.x (cgroupv2) nodes
  - [x] https://github.com/gardener/gardener/pull/7780
  - [x] https://github.com/gardener/gardener/pull/7797
  - [x] https://github.com/gardener/machine-controller-manager-provider-local/pull/16
  - [x] Reconfigure worker groups in prow cluster to run on GardenLinux 934.x

**Comment by timebertt** [comment]
/assign
for

> Add a unit/integration/e2e testing strategy and guideline

We just had a discussion about the testing strategy. I will finalize our discussion results and open a PR with the new document.
The testing developer guideline will follow once we've had the second part of the discussion.

**Comment by timebertt** [comment]
/unassign

> Add a unit/integration/e2e testing strategy and guideline

is done with https://github.com/gardener/gardener/pull/6245

**Comment by timebertt** [comment]
/assign @oliver-goetz 
for the tasks listed above with his name :)

**Comment by briantopping** [comment]
Would like to add #7284 and #7285 in here as appropriate but don't have credentials to do so 🤓

**Comment by rfranzke** [comment]
/unassign @oliver-goetz 
/assign @darmiel

for the "No more development freeze during release validation; release from release branch" task

**Comment by shafeeqes** [comment]
All tasks are completed. Thanks to everyone who contributed to this topic. 🎉 
/close
