### ISSUE TITLE
Shoot cannot be reconciled after CA Rotation was triggered if `ReversedVPN` is disabled

### ISSUE THREAD

**Issue by dimityrmirchev** [gardener/gardener#6042]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
I had `ReversedVPN` set to `false` and triggered CA rotation for a shoot cluster. The reconciliation failed with error:
```
description: |-
      task "Waiting until the Kubernetes API server can connect to the Shoot workers" failed: retry failed with context deadline exceeded, last error: could not forward to vpn-shoot pod (timeout after 5 seconds): error forwarding ports: error upgrading connection: error dialing backend: dial tcp 10.250.0.2:10250: i/o timeout

      -> Events:
      * service-controller reported 27m ago (x5 over 29m): Error syncing load balancer: failed to ensure load balancer: cannot EnsureLoadBalancer() with no hosts
      * service-controller reported 11m ago: There are no available nodes for LoadBalancer
```

The `vpn-seed` container in the `kube-apiserver` pod is logging the following:
```
TLS_ERROR: BIO read tls_read_plaintext error
TLS Error: TLS object -> incoming plaintext read error
TLS Error: TLS handshake failed
```

After restarting the gardenlet with `ReversedVPN: true` the shoot reconciles successfully.

**What you expected to happen**:
I expect that shoot reconciliation is successful.
**How to reproduce it (as minimally and precisely as possible)**:
1. Disable the `ReversedVPN` feature gate.
2. Start the `gardenlet`
3. Create a shoot
4. Trigger CA rotation by annotating the shoot with `gardener.cloud/operation=rotate-ca-start`

**Anything else we need to know?**:

**Environment**:

- Gardener version: `bf034088dee67e34d1dba329a161cff5ff7a33a1`
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
/assign

Thanks for reporting this @dimityrmirchev, however, I am unable to reproduce it following the steps you provided. After both `rotate-ca-start` and `rotate-ca-complete` everything is running fine. What am I missing (I tried with `provider-local`)?

**Comment by rfranzke** [comment]
Update: In a joint call with @dimityrmirchev we managed to reproduce it with `provider-gcp` (the difference with `provider-local` seems to be that the legacy VPN does not work "correctly" here; though, given that it's deprecated anyways it would probably be removed sooner or later).

We figured out what the problem is and @dimityrmirchev will open a PR with the fix. Thanks!
