### ISSUE TITLE
[Extensions lib] Pass clientConnection configuration to shoot client

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#6045]
**How to categorize this issue?**

/area performance
/kind enhancement

**What would you like to be added**:
Gardener's extensions library offers a standard health check registration which is used by provider extensions ([example](https://github.com/gardener/gardener-extension-provider-azure/blob/1f43bb5a28d2b67b22517a2cf60853675a20d1cf/pkg/controller/healthcheck/add.go#L62)).
Today, it's not possible to pass any information about how controller-runtime clients, which are used by health checks [ref](https://github.com/gardener/gardener/blob/bf034088dee67e34d1dba329a161cff5ff7a33a1/extensions/pkg/controller/healthcheck/healthcheck_actuator.go#L122), should be constructed. It should esp. be possible to pass options like `QPS` and `Burst`. 

**Why is this needed**:
To prevent client-side throttling issues during health check execution. Such a throttling can lead to a significant longer execution of the checks. We also saw cases where this led to a `context timeout` so that checks could not be finished at all.

**Comment by ialidzhikov** [comment]
/reopen
as we had to revert https://github.com/gardener/gardener/pull/6113
