### ISSUE TITLE
Using an external DNS Provider failed if UseDNSRecords-Feature-Flag is enabled

### ISSUE THREAD

**Issue by vabrams** [gardener/gardener#6052]
**How to categorize this issue?**
/area control-plane
/kind bug

**What happened**:
gardener-controller-manager reports a reconciliation error if the UseDNSRecords-Feature-Flag is enabled

`"level":"error","logger":"controller.controllerregistration.seed","msg":"Error reconciling request","name":"openstack","namespace":"","error":"need to install an extension controller for \"DNSRecord/cloudflare-dns\" but no appropriate ControllerRegistration found","stacktrace":"github.com/gardener/gardener/pkg/controllerutils.CreateWorker.func1.1\n\t/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:64\n ....`

**What you expected to happen**:
Any controller should implement the DNSRecord-Feature for external DNS

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster via garden-setup and specify a different DNS type
```
landscape:
  iaas:
  - type: openstack
  dns:
    type: cloudflare-dns
```

**Anything else we need to know?**:

**Environment**:

- Gardener version:
  v1.40.4

- Kubernetes version (use `kubectl version`):
  v1.21.10

- Cloud provider or hardware configuration:
  OpenStack-provider v1.24.2

- Others:
   external-dns-management v0.11.4

```
# kubectl get controllerregistrations.core.gardener.cloud dns-external provider-openstack
NAME                 RESOURCES                                                                                                                                                                                      
dns-external         DNSProvider/aws-route53, DNSProvider/alicloud-dns, DNSProvider/azure-dns, DNSProvider/google-clouddns, DNSProvider/openstack-designate, DNSProvider/cloudflare-dns, DNSProvider/infoblox-dns
provider-openstack   Infrastructure/openstack, ControlPlane/openstack, Worker/openstack, BackupBucket/openstack, BackupEntry/openstack, DNSRecord/openstack-designate
```

**Comment by rfranzke** [comment]
This is expected, I believe. To my knowledge, there is no extension yet implementing the `DNSRecord/cloudflare-dns` "API", so the `UseDNSRecord`s feature gate cannot be used. If you rely on such DNS provider type it would be advisable to contribute such extension (given that `DNSRecord` is the new standard and the feature gate will be eventually promoted and removed, i.e. it will not be able to disable it anymore).

**Comment by MartinWeindel** [comment]
You may try https://github.com/schrodit/gardener-extension-provider-dns-cloudflare

**Comment by rfranzke** [comment]
The question seems to be answered, so let's
/close
this issue for now. Feel free to `/reopen` if you see necessity.
