### ISSUE TITLE
Verify `maintenance.gardener.cloud/operation` annotation right away

### ISSUE THREAD

**Issue by oliver-goetz** [gardener/gardener#6058]
**How to categorize this issue?**

/area usability
/kind enhancement

**What would you like to be added**:
https://github.com/gardener/gardener/pull/6039 introduced `maintenance.gardener.cloud/operation` for shoots.
At the moment the annotation is validated before the operations are executed during the maintenance time window only. Thus, users will get notified about wrong annotations, typos etc. very late in the maintenance window.
A validation carried out at the creation of the annotation similar to [validation of shoot operation](https://github.com/gardener/gardener/blob/201673c1f8a356a63b21505ca9c7f6efe725bd48/pkg/apis/core/validation/shoot.go#L1707) would provide a direct validation of user input.

**Why is this needed**:
Improve usability

**Comment by rfranzke** [comment]
Small addition: We probably should validate `gardener.cloud/operation` on `Shoot`s as well
