### ISSUE TITLE
Expose Gardener Version

### ISSUE THREAD

**Issue by grolu** [gardener/gardener#611]
We have the requirement to show the Gardener version in the dashboard : gardener/dashboard#262

Currently, the version is set in the shoot spec during reconciliation, but there is no endpoint where the dashboard could fetch this version. Would it be possible to add this - otherwise we would need to parse the image tag in the deployment as a workaround.

**Comment by rfranzke** [comment]
Example output:

```
$ curl https://<gardener-apiserver-endpoint>/version
{
  "major": "0",
  "minor": "15",
  "gitVersion": "0.15.0-dev",
  "gitCommit": "69d057ba9f8fbf52c07280648fbfbaab31c099d2",
  "gitTreeState": "dirty",
  "buildDate": "2018-12-21T08:15:02+01:00",
  "goVersion": "go1.11.4",
  "compiler": "gc",
  "platform": "darwin/amd64"
}
```
