### ISSUE TITLE
Drop support for `alpha.csimigration.shoot.extensions.gardener.cloud/kubernetes-version`

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#6154]
**How to categorize this issue?**

/area storage control-plane
/kind cleanup

**What would you like to be added**:
https://github.com/gardener/gardener/pull/4202 and https://github.com/gardener/gardener-extension-provider-aws/pull/354 add possibility to overwrite the CSI migration version. Anyways, this was added back then due to existing issues during the migration but AFAIK it was never used or not used atm. 

**Why is this needed**:
We should rather drop this functionality as it is not something we would like to support and maintain as scenario.

**Comment by ialidzhikov** [comment]
I assume when we drop support fоr K8s 1.21 (provider-azure enables CSI migration starting K8s 1.21), we should be good to clean up the [csimigration controller](https://github.com/gardener/gardener/tree/v1.57.1/extensions/pkg/controller/csimigration). (@rfranzke, feel free to correct me if I am wrong).

If that's the case, then it  doesn't make much sense to first clean up the support for `alpha.csimigration.shoot.extensions.gardener.cloud/kubernetes-version` while the whole CSI migration contorller will be dropped in the future.

**Comment by rfranzke** [comment]
Sounds like a good plan @ialidzhikov!

**Comment by ialidzhikov** [comment]
Then let's close and do not invest into this task for now.

/close
