### ISSUE TITLE
API server probes sporadically fail with "tls: internal error"

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener#6157]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:

We see sporadic failures from blackbox exporter probing the kube-apiserver from both, seed and shoot side:

```
ts=2022-06-18T15:33:48.14775152Z caller=main.go:140 module=http_kubernetes_service target=https://kubernetes.default.svc.cluster.local/healthz level=error msg="Error for HTTP request" err="Get \"https://100.64.0.1/healthz\": remote error: tls: internal error"
ts=2022-06-18T15:33:48.147877825Z caller=main.go:347 module=http_kubernetes_service target=https://kubernetes.default.svc.cluster.local/healthz level=error msg="Probe failed" duration_seconds=0.506237025
```

Given the total amount of clusters this problem appears to be rare with probably less than 100 probes failing for this reason. 

**What you expected to happen**:

Probes should not fail with this error.

**How to reproduce it (as minimally and precisely as possible)**:

There is a list of incidents listed in our network channel.

**Anything else we need to know?**:

This is a new problem that popped up in the last couple of weeks. It must have been triggered by some change. As far as I can see this affects cluster running with multiple minor kubernetes versions.

A google search reveals lots of problems of that kind. The suspicion is that it might be related to certificate rotation, so this might not be an issue at all.

**Environment**:

- Gardener version: latest on live
- Kubernetes version (use `kubectl version`): n/a
- Cloud provider or hardware configuration: all
- Others:

**Comment by vlerenc** [comment]
@marwinski Is that a possible issue that may lead to the observed, but not necessarily perceived API server outages? They are phantom outages?

@istvanballok Wouldn't this be another (good) reason to finish the "meaningful availability" topic? In the end, API server availability is the most relevant SLI and we see (too) many issues with the seed/shoot probes we seem unable to get down. We found phantom reasons like DNS, now this. We need something we can trust and need to understand where we really stand.

**Comment by marwinski** [comment]
> @marwinski Is that a possible issue that may lead to the observed, but not necessarily perceived API server outages? They are phantom outages?

Yes, these are the outages shown in the report. Those are rare single failing requests so I would not necessary call this an outage. This said, there are too many failing requests - it is probably ok to see one failing request per week, not several per day.

This said, I remember that this issue alway hit the same clusters so it might be something application related. I do not consider this a network issue - this is an issue during the tls handshake.
