### ISSUE TITLE
"Logging" Stack Deprecated?

### ISSUE THREAD

**Issue by rufreakde** [gardener/gardener#6188]
https://github.com/gardener/gardener/blob/29031f9513f51caf28891a4b5a4c9c344aace570/docs/extensions/logging-and-monitoring.md?plain=1#L7

So I saw this Logging stack explanation but it seems that in the list of gates it is deprecated and even removed after 1.42.
Is this correct? If so could this guide be updated with a deprecation notice and also what are the general suggested alternatives then?

https://github.com/gardener/gardener/blob/master/docs/deployment/feature_gates.md
Logging | false | Removed | 1.41
-- | -- | -- | --

<br class="Apple-interchange-newline">

Best regards,
rufreakde

**Comment by rfranzke** [comment]
Only the feature gate was deprecated and removed, not the logging stack itself. It's still available.

**Comment by ialidzhikov** [comment]
No, it is not deprecated. Just changed the way how it is configured. Previously it was with a feature gate, after https://github.com/gardener/gardener/pull/5337 - with a configuration option in the gardenlet's component config.

**Comment by ialidzhikov** [comment]
Feel free to reach out [over Slack](https://kubernetes.slack.com/messages/gardener) if you have additional/follow-up questions.

/close

**Comment by rufreakde** [comment]
Ah okay got it could update the guide a little to emphasise that the gate is dependent on the version.
Thanks!
