### ISSUE TITLE
add support for tags/labels on shoots

### ISSUE THREAD

**Issue by alcasim** [gardener/gardener#623]
Hi,

I think it would be a nice feature to add support for tags/labels on all shoot resources. This will be really helpful on cost tracking on some cloud platforms.

I have some time to spare adding this feature for Azure, I'm happy to discuss about it

**Comment by bergerx** [comment]
I guess the path would be something like this:

```
Shoot CR --> MachineDeployment CR --> MachineSet CR --> Machine CR --> VM
--------     -----------------------------------------------------     ----
gardener                  machine-controller-manager                   iaas
```

So a good starting point is to check if machine-controller-manager supports this and create a matching issue there if needed.

**Comment by alcasim** [comment]
That's the path to follow to tag instances indeed. But those are not the only resources to be tagged (even more, in the Azure case it's not necessary to tag them in order to track costs). I planned to tag all elements created by the terraformer, that gives a valid first approach.  Then effort can be extended to the machine-controller manager.

**Comment by rfranzke** [comment]
Do you need arbitrary tags or is a cluster information on the resources enough? For example, in AWS we tag all the resources with the cluster name: https://github.com/gardener/gardener/blob/master/charts/seed-terraformer/charts/aws-infra/templates/_main.tf#L403-L407

**Comment by alcasim** [comment]
I need arbitrary tags, as we classify costs based on different criteria (per team, per shoot, per environment...). I (almost) have something which takes shoot's labels and place them as tags for Azure, just for the terraform infra charts. I will open a PR once I'm happy on how it works (probably I will extend that to AWS as well).

**Comment by rfranzke** [comment]
OK. How do you plan to tag the resources causing costs but are not created by Gardener but the CCM/KCM (load balancers, volumes, ...)?

**Comment by alcasim** [comment]
In the case of Azure it's quite easy: all resources created within a resource group are cost-tracked by the resource group itself. So when CCM or KCMs create something is done under the resource group, hence can be cost-tracked by that. In our use-case we need to tag the different resource groups to categorize the costs.

I cannot tell about AWS or other cloud providers, I will do an small research, as I want my changes to be aligned with whatever further changes are needed for tagging :)

**Comment by rfranzke** [comment]
Hm, I don't get it. I don't understand how you want to enable arbitrary tags on the shoot resource to be propagated to the IaaS resources in general. It's a special case in Azure that everything is grouped under the resource group which you can tag. Such a general solution you are having in mind should work for all cloud providers, and I don't see how we can achieve that for the mentioned resources not created by Gardener (load balancers, volumes, ...).

**Comment by alcasim** [comment]
Hey @rfranzke, I considered your feedback and I agree with you.
Unfortunately (and that is quite frustrating) Kubernetes does not tag any created resource. There are a PR and an issue stating that for PVs (and specifically for AWS):

- https://github.com/kubernetes/kubernetes/pull/49390
- https://github.com/kubernetes/kubernetes/issues/50898

In order to be consistent all resources should be tagged, not only any resource created by Gardener but also any resource created by Kubernetes. Then there is no point trying to add such support in Gardener if Kubernetes won't tag the resources.

The motivation for this issue (and my investigation on how to implement for the specific Azure case) was to have all infrastructure declared as code and not relying on manual tagging operation after shoot creation (any manual process is prone to failure/to be forgotten).

In the process I learned Gardener creates the infrastructure when a Shoot is created, but never reconciles again this infrastructure (unless Gardener is instructed to delete it), so the manual tag operation can be done, and the support for adding tags from the Shoot definition is not needed then. In the future, if you plan to add this infrastructure reconciliation into the Reconcile cycle perhaps this issue can be taken into account.

Said that, I agree on closing this issue (or lowering its priority). And thanks for your feedback on the comments :)

**Comment by rfranzke** [comment]
OK, thank you. I remember we were thinking about something similar back one year but postponed it as we would need to write additional controllers to tag resources created by Kubernetes. However, it's also more difficult generally, as the users could deploy any arbitrary custom controller into their clusters which again could create infrastructure resources we don't know about.

> In the process I learned Gardener creates the infrastructure when a Shoot is created, but never reconciles again this infrastructure (unless Gardener is instructed to delete it)

That's wrong, Gardener reconciles the infrastructure in the maintenance time window of the shoot. However, it depends on the Terraform implementation regarding whether manual tags would be deleted or not.

Let's close the issue for now until there is a reasonable way to achieve the wanted behaviour. :)
