### ISSUE TITLE
Add integration/e2e test for gardenlet certificate rotation

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#6263]
**How to categorize this issue?**

/area testing
/kind enhancement

**What would you like to be added**:

We currently don't test the gardenlet certificate rotation feature in CI.
We should add a test (optimally e2e) to verify that feature on PRs and on master.

**Why is this needed**:

Increasing test coverage and confidence.

**Comment by rfranzke** [comment]
Now that we have the `ManagedSeed` e2e tests, we could extend it with this case.
