### ISSUE TITLE
pending reserve-excess-capacity pods cause seed as notReady

### ISSUE THREAD

**Issue by shaoyongfeng** [gardener/gardener#6275]
**How to categorize this issue?**
/area ops-productivity
/kind bug

**What happened**:
When there is no enough capacity in seed cluster which enables excessCapacityReservation feature,  reserve-excess-capacity pod can't be scheduled and in pending state,  in this case,  the status of seed is notReady and all shoots created in this seed can't be reconciled anymore

**What you expected to happen**:
Status of reserve-excess-capacity shouldn't affect seed's status
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
I'm not sure whether this is indeed a bug or whether it's intended behavior. When you enable the excess capacity reservation then the desired state of the seed cluster is that the `reserve-excess-capacity` pods are deployed and running. If they are pending instead, the cluster should scale up within a few minutes and the seed should be come ready again. Newly created shoots might take a while until they become scheduled again, however this should be within a few minutes (typical duration for scale-up).

Excess capacity reservation does only work well with proper auto-scaling, hence it's the responsible of the operator to properly enable this for the seed cluster. If this cannot be guaranteed, it can also be disabled, see https://github.com/gardener/gardener/blob/master/docs/usage/seed_settings.md#reserve-excess-capacity.

**Comment by shaoyongfeng** [comment]
> I'm not sure whether this is indeed a bug or whether it's intended behavior. When you enable the excess capacity reservation then the desired state of the seed cluster is that the `reserve-excess-capacity` pods are deployed and running. If they are pending instead, the cluster should scale up within a few minutes and the seed should be come ready again. Newly created shoots might take a while until they become scheduled again, however this should be within a few minutes (typical duration for scale-up).
> 
> Excess capacity reservation does only work well with proper auto-scaling, hence it's the responsible of the operator to properly enable this for the seed cluster. If this cannot be guaranteed, it can also be disabled, see https://github.com/gardener/gardener/blob/master/docs/usage/seed_settings.md#reserve-excess-capacity.

My understanding is that the purpose of "reserve-excess-capacity" is to reserve some capacity from IaaS because IaaS is not so elastic sometimes.  In this way, when some important pods need to be scheduled, reserve-excess-capacity pods can be evicted and more important pods can be scheduled. Finally the whole cluster won't be affected by resource shortage from IaaS layer and it can continue to work as expected.  At this point of time, we may not be able to scale up cluster due to resource shortage of IaaS.  Then we can coordinate with hyperscaler to get more capacity later, but it's not so urgent anymore because all functional pods are up and running.    "reserve-excess-capacity" itself is not so important

but if "reserve-excess-capacity" itself will bring seed into NotReady state,  it loses its purpose.  If so, why do we need to reserve excess capacity?  we can also keep "important pods" as pending which will also make seed as NotReady and scale up cluster manually or automatically.  In this way, we don't even to cost extra money to reserve capacity.

**Comment by rfranzke** [comment]
Just saying that with `reserve-excess-capacity` disabled and fully utilized seed clusters, newly shoots would get scheduled but their creation would fail until the seed gets scaled up.
Now with `reverse-excess-capacity` enabled and fully utilized seed clusters, newly shoots won't get scheduled in the first place and have to wait until the seed gets scaled up (and becomes "ready" again for shoots).
You can probably find pro and con arguments for both behaviours 🤷🏻 

So I don't think that we necessarily have to change this to "fix" it for newly created shoots (they have to wait one way or the other), but I guess non-ready seeds also influence the reconciliation of already existing shoots, and this is probably something we would want to avoid. In this case, we would need to either move the `reserve-excess-capacity` resources into a dedicated `ManagedResource` and do not consider its health status when computing the seed's health, or we introduce a new annotation for `gardener-resource-manager` which makes it skipping health checks for resources with such annotation (similar to "ignore" annotation).
Opinions?

**Comment by shaoyongfeng** [comment]
second option seems more flexible.  Meanwhile, we can also setup a Prometheus  alert for reserve-excess-capacity pod, then ops will got informed when capacity is in shortage.

**Comment by shafeeqes** [comment]
I also think annotation would be better, removing this MR alone from health check feels like a change which is easy to miss later on, Using annotation would be more explicit. And do we want to annotate the MR by default, or only when it is causing problems?

**Comment by rfranzke** [comment]
We don't want to annotate the `ManagedResource` but rather the `DaemonSet/reserve-excess-capacity`. By default, yes.

**Comment by timebertt** [comment]
> we introduce a new annotation for `gardener-resource-manager` which makes it skipping health checks for resources with such annotation (similar to "ignore" annotation).

sounds good to me

**Comment by ialidzhikov** [comment]
I would rather vote to move the reserve-excess-capacity resources to a separate ManagedResource and to exclude this ManagedResource from the healthchecks (instead of introducing a new annotation and coding about it).

**Comment by shafeeqes** [comment]
This could be a nice-to-have feature in resource manager although we don't have any other use case right now. I have already made the changes, please take a look at the PR.
