### ISSUE TITLE
Improve control plane migration end-to-end tests

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#6281]
**How to categorize this issue?**

/area control-plane-migration
/area testing
/kind enhancement

**What would you like to be added**:

- [ ] Improve the control plane migration e2e test by:
  - [ ] Making the `Worker` migration and restoration testable. Currently the worker is deleted during the migrate phase and recreated during the restore phase which is not desired.
  - [ ] Making the `Shoot`'s `kube-apiserver` reachable both before and after control plane migration via its domain name from the host on which the control plane migration e2e test runs so that preservation of resources inside the shoot cluster can be tested directly.

**Why is this needed**:
Currently the end-to-end tests for control plane migration have a few limitations. Firstly, the migration and restoration of `Worker`s is not tested. Second, while running the tests in prow (and using skaffold to deploy all gardener components in the kind clusters that are used for `Seeds`), it is not possible to talk to the `kube-apiserver` of the `Shoot` which will be migrated.

The first limitation comes from the fact that for the local setup the `Shoot`'s node is backed by a `Pod` inside the `Shoot`'s control plane namespace. This `Pod` will get deleted once the `Shoot`'s namespace is destroyed from the source `Seed` as part of the migration phase. Afterwards, during the restore phase the `Shoot`'s `Node` and corresponding `Pod` need to be recreated.

The second limitation comes from the fact that the `provider-local` extension controllers are running inside the kind clusters, so they cannot write the domain name of the `Shoot`'s `kube-apiserver` and its IP address to the host's `/etc/hosts` file. This means that `/etc/hosts` must be edited by the script which triggers the tests. In Prow job containers, the `istio-ingressgateway` services used for SNI for both seeds are exposed on IP `0.0.0.0` but on different ports: `443` and `9443` (ref: [cluster1](https://github.com/gardener/gardener/blob/2de823d0a457beb9d680260243032c95fa47dc72/example/gardener-local/kind/cluster-skaffold.yaml#L7-L9), [cluster2](https://github.com/gardener/gardener/blob/2de823d0a457beb9d680260243032c95fa47dc72/example/gardener-local/kind2/cluster-skaffold.yaml#L7-L12)). Consequently, before migration is triggered the `Shoot`'s `kube-apiserver` will be reachable on 0.0.0.0:443, whereas after the migration phase finishes and during the restore phase it will be reachable on 0.0.0.0:9443. 

Resolving these limitations would bring the end-to-end tests for control plane migration closer to the actual scenario and would help us to identify problems sooner.

**Comment by rfranzke** [comment]
@plkokanov Do you still plan to work on this issue [ref](https://github.com/gardener/gardener/issues/6281#event-7948017621)?

**Comment by plkokanov** [comment]
@rfranzke I need to reevaluate this now that we've added https://github.com/gardener/gardener/pull/6678.
Perhaps the first task is no longer necessary. The second one, about making the api-server reachable, I can probably still work on. However, It would probably be good to first address this task `Enhance DNS handling (drop sudo requirement, make custom CoreDNS server available in developer machine):` from #6016

**Comment by rfranzke** [comment]
We discussed about improving the DNS handling with @ScheererJ. We will improve something as part of #6997, but that's probably all for the foreseeable future. It's not clear and not trivial to improve this further (making custom CoreDNS server available in developer machine means changing `/etc/resolv.conf` which is not much better than changing `/etc/hosts` and can yield to more different/weird issues in the long run).
