### ISSUE TITLE
Drop support for `use-as-seed` annotation

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#6305]
**How to categorize this issue?**

/area dev-productivity ops-productivity
/kind cleanup

**What would you like to be added**:

The `use-as-seed` annotation on shoots was replaced by a proper resource (`ManagedSeed`) a long time ago.
We should finally clean up the old annotation and the corresponding "shoot seed registration" controller.

Along the way, we should enforce that `Shoot` objects that are referenced by `ManagedSeed`s are configured to enable the shoot VPA feature.
Enabling the VPA in the seed spec instead of the shoot spec offers less flexibility and increases network transfer and cost.
Hence, there is no valid scenario for not using the shoot VPA feature for `ManagedSeed`s.

**Why is this needed**:

Get rid of unnecessary code.

**Comment by ialidzhikov** [comment]
> Along the way, we should enforce that `Shoot` objects that are referenced by `ManagedSeed`s are configured to enable the shoot VPA feature.
> Enabling the VPA in the seed spec instead of the shoot spec offers less flexibility and increases network transfer and cost.
> Hence, there is no valid scenario for not using the shoot VPA feature for `ManagedSeed`s.

@voelzmo @andrerun do you have any comments/objections against such enforcement?

**Comment by voelzmo** [comment]
Let my try to understand what the "enforcement" means. Is this something different than we're already doing for new Shoots, where we [default `VPA.enabled: true`](https://github.com/gardener/gardener/blob/2e3d605831d1628db914d24837d3bd385a246dff/plugin/pkg/shoot/vpa/admission.go#L66-L68)? Are you saying you would change this for existing clusters as well?

**Comment by timebertt** [comment]
The idea is to enforce, that you can only register `Shoots` as `ManagedSeeds` if the shoot VPA is enabled but the seed VPA is disabled, as it isn't sensible to do it any other way.
And yes, this should probably be enforced for existing Shoots that are registered as ManagedSeeds already.

**Comment by timebertt** [comment]
Is there anything left to do for this issue after https://github.com/gardener/gardener/pull/6388?

**Comment by ialidzhikov** [comment]
Nope.

/close
