### ISSUE TITLE
Add a sidecar to Operator/Owner Grafanas to discover dashboards

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener#6308]
**How to categorize this issue?**

/area monitoring
/kind enhancement

**What would you like to be added**:

Add a sidecar to Grafana to discover dashboards as described [here](https://github.com/gardener/gardener/blob/master/docs/proposals/19-migrating-to-prometheus-operator.md#grafana-sidecar).

- [ ] Refactor Grafana to a component (similar to https://github.com/gardener/gardener/pull/6210)
- [ ] Add a sidecar to Grafana
- [ ] Move common dashboards to the `monitoring` namespace
- [ ] Discover "special" dashboards in the shoot namespace
- [ ] Clean up the "old" dashboards

**Why is this needed**:

Part of GEP-19.

**Comment by rfranzke** [comment]
As part of this issue, it might make sense to refactor Grafana to a component (similar to #6210) before we even further extend the Helm charts (multiple times).

**Comment by wyb1** [comment]
> As part of this issue, it might make sense to refactor Grafana to a component

I will add it to the issue

**Comment by istvanballok** [comment]
- We use #5745 as an example to refactor Grafana (or even the whole monitoring stack) into a component.

/assign @istvanballok, @wyb1, @rickardsjp
