### ISSUE TITLE
Add integration/e2e test for `Plant` or drop it

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#6331]
**How to categorize this issue?**

/area dev-productivity
/kind technical-debt

**What would you like to be added**:

We should
- either add proper integration or e2e tests for the `Plant` resource and controller
- or drop them

**Why is this needed**:

The `Plant` resource and controller are currently untested in CI. There are testmachinery tests, but they can't prevent bugs and regressions from getting into master.
As nobody seems to be using the `Plant` resource, it's hard to know whether it's working properly.
It seems there is no real request for this feature, so we should get rid of the effort involved here, if we decide not to add proper tests.

**Comment by rfranzke** [comment]
/close
in favor of #6348
