### ISSUE TITLE
Prevent end-users from pinning `.spec.seedName` when creating `Shoot`s

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#6355]
**How to categorize this issue?**

/area robustness
/kind enhancement

**What would you like to be added**:
After #6018, it's still possible for end-users to specify `.spec.seedName` when they create new `Shoot` resources. We should prevent them from doing this.

**Why is this needed**:
This can easily lead to overload situations where end-users pin a single seed and create lots of clusters. It's better to leave this field empty so that `gardener-scheduler` (which has the best knowledge w.r.t. which seed is most suitable for running the shoot's control plane) can take the scheduling decision.

**Comment by shafeeqes** [comment]
Let's have a check in the admission plugins, whether the user trying to create the shoot with the `.spec.seedName` set is bound to a RBAC role with update permissions for `shoots/binding` subresource. 
This way operators can still create shoots the old way.
Should we have the check in the `ShootValidator` plugin or the `CustomVerbAuthorizer` plugin?

**Comment by timebertt** [comment]
> Should we have the check in the `ShootValidator` plugin or the `CustomVerbAuthorizer` plugin?

From my perspective, both options are fine. `ShootValidator` has already some `seedName` related checks, so it might be a good fit.
