### ISSUE TITLE
Adopt "tools" concept for extensions

### ISSUE THREAD

**Issue by acumino** [gardener/gardener#6396]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement

**What would you like to be added**:
Install required development tools to a local dir – on the fly and as needed. PR https://github.com/gardener/gardener/pull/4879, introduced `tools.mk` to install the required development dependencies on the fly. Extensions should also adopt these changes and should drop `install-requirement` script.

Adapt the following extensions to use the tools concept - 
  - [x] ~~kupid~~ [Can't be done as it needs old version of controller-gen tool]
  - [x] networking-calico https://github.com/gardener/gardener-extension-networking-calico/pull/200
  - [x] networking-cilium https://github.com/gardener/gardener-extension-networking-cilium/pull/114
  - [x] os-coreos https://github.com/gardener/gardener-extension-os-coreos/pull/48
  - [x] os-gardenlinux https://github.com/gardener/gardener-extension-os-gardenlinux/pull/66
  - [x] os-suse-chost https://github.com/gardener/gardener-extension-os-suse-chost/pull/72
  - [x] os-ubuntu https://github.com/gardener/gardener-extension-os-ubuntu/pull/68
  - [x] provider-alicloud https://github.com/gardener/gardener-extension-provider-alicloud/pull/516
  - [x] provider-aws https://github.com/gardener/gardener-extension-provider-aws/pull/583
  - [x] provider-azure
  - [x] provider-equinix-metal https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/224
  - [x] provider-gcp
  - [x] provider-openstack
  - [x] provider-vsphere https://github.com/gardener/gardener-extension-provider-vsphere/pull/278
  - [x] runtime-gvisor https://github.com/gardener/gardener-extension-runtime-gvisor/pull/52
  - [x] shoot-cert-service https://github.com/gardener/gardener-extension-shoot-cert-service/pull/129
  - [x] shoot-dns-service https://github.com/gardener/gardener-extension-shoot-dns-service/pull/148
  - [x] shoot-networking-filter https://github.com/gardener/gardener-extension-shoot-networking-filter/pull/28
  - [x] shoot-networking-problemdetector https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/pull/17
  - [x] shoot-oidc-service https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/53

**Comment by timebertt** [comment]
> kupid [Can't be done as it needs old version of controller-gen tool]

@acumino Why is that?
The controller-tools version is controlled via the project's `go.mod`. I expect that you can set the required version there.

**Comment by acumino** [comment]
> > kupid [Can't be done as it needs old version of controller-gen tool]
> 
> @acumino Why is that? The controller-tools version is controlled via the project's `go.mod`. I expect that you can set the required version there.

It uses `crd:trivialVersions=true` flag which is not there in new controller-gen tool. https://github.com/gardener/kupid/blob/db5a7ddd0e4133df1ecbf22dda24aa7188422f74/Makefile#L12

**Comment by timebertt** [comment]
And what about installing the old version of the tool, that still has the flag, i.e. v0.6.2 (ref https://github.com/gardener/kupid/blob/db5a7ddd0e4133df1ecbf22dda24aa7188422f74/Makefile#L13)?

**Comment by acumino** [comment]
> And what about installing the old version of the tool, that still has the flag, i.e. v0.6.2 (ref https://github.com/gardener/kupid/blob/db5a7ddd0e4133df1ecbf22dda24aa7188422f74/Makefile#L13)?

We use this rule in tools.mk https://github.com/gardener/gardener/blob/baf544c9a7e6126ee89785bbe059ef1d40e88566/hack/tools.mk#L94-L95
that means it will install the latest version of controller-gen tools. So we can't install the older version if we use tools.mk rule.

**Comment by timebertt** [comment]
The rule will install the version specified in `go.mod` 🤔

**Comment by acumino** [comment]
> The rule will install the version specified in `go.mod` 🤔

Yes, but in `go.mod` kupid specifies controller-tools version v0.8.0 but in the `make file` it uses v0.6.2. I am not sure if it is done intentionally. And do we really want `crd:trivialVersions=true` this flag.

**Comment by rfranzke** [comment]
All items in the list are completed.
/close
