### ISSUE TITLE
[GCP] Can we re-enable GCP multi-zone deployments?

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#64]
Some time back we have disabled deployments into [multiple availability zones for Google clusters](https://github.com/gardener/gardener/blob/72d4693ab5da13f9512e963bd5e8aa5772738035/pkg/apis/garden/validation/validation.go#L755-L757) because we saw issues with PVCs and volume attachments (kubernetes/issues#50115) in the GCE cloud provider.

Has the issue been resolved so that we can re-enable it again?

**Comment by rfranzke** [comment]
cc @DockToFuture @mliepold

**Comment by vlerenc** [comment]
Ping... @mliepold @DockToFuture

**Comment by mliepold** [comment]
The issue has been resolved in 1.9 and was even cherry picked into release 1.7 and 1.8. (see PR https://github.com/kubernetes/kubernetes/pull/52322). 
We will test it with the new gardener and activate multi-zone deployment if the test is successful.

**Comment by mliepold** [comment]
Multi-zone deployments for GCP have been enabled again and tested successfully for K8S 1.8.5+ and 1.9.
Pull request: https://github.com/gardener/gardener/pull/115
