### ISSUE TITLE
Gardenlet deployment using helm fails 

### ISSUE THREAD

**Issue by acumino** [gardener/gardener#6422]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
While deploying the Gardener v1.52.0 `gardenlet` deployment fails with the following error:
```
Error: kind PriorityClass with the name "gardener-system-critical" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
Error: UPGRADE FAILED: kind PriorityClass with the name "gardener-system-critical" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
```
 But the gardenlet images gets upgraded to the latest version. This removes the priority-class from managed resources and the priority class gets garbage collected. 
 So if one deploy the gardenelet again it will succeed without error.

**What you expected to happen**:
The gardenlet deployment should succeed without error.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.52.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
I see there is a mechanism in helm 3 for adopting existing resources if they are correctly labeled: https://github.com/helm/helm/pull/7649

However, leveraging this mechanism in gardenlet will get quite complicated.
Also, it will not help our internal case because we are still not using helm 3 (😞).

> But the gardenlet images gets upgraded to the latest version. This removes the priority-class from managed resources and the priority class gets garbage collected.
So if one deploy the gardenelet again it will succeed without error.

If that's true and it will succeed after one failure, I don't mind living with this bug, considering that workarounds/fixes will be highly complicated.
We could even edit the release notes to explain this to gardener operators.

**Comment by acumino** [comment]
My suggestion is to use the `gardenlet` priority class for v1.52 and let MR clean the old priority class `garden-system-critical`. Later In in v1.53, we can switch back again to  `garden-system-critical`. Because deploying 3-4 times on canary and live doesn't seem right to me.

**Comment by acumino** [comment]
> My suggestion is to use the `gardenlet` priority class for v1.52 and let MR clean the old priority class `garden-system-critical`. Later In in v1.53, we can switch back again to `garden-system-critical`. Because deploying 3-4 times on canary and live doesn't seem right to me.

Is this reasonable @timebertt @ialidzhikov?

**Comment by timebertt** [comment]
xref https://github.com/gardener/gardener/issues/5634

**Comment by timebertt** [comment]
Sounds good to me. This might be the simplest solution we can come up with
This also means we need to partially revert https://github.com/gardener/gardener/pull/6235 for now.

**Comment by ialidzhikov** [comment]
I couldn't follow all the details but if (partial) revert of the PR that introduces the issue (https://github.com/gardener/gardener/pull/6235) does the trick, then fine from my side. 👍

**Comment by acumino** [comment]
> I couldn't follow all the details but if (partial) revert of the PR that introduces the issue (#6235) does the trick, then fine from my side. 👍

#6430 partially reverts #6235.

**Comment by ialidzhikov** [comment]
Hm, I am not quite sure that this approach will work. I see that in https://github.com/gardener/gardener/pull/6257 components like istiod and gardener-resource-manager are adapted to use the `garden-system-critical`. With #6430 I don't see who creates this `garden-system-critical` PriorityClass. Or do I overlook something?

**Comment by acumino** [comment]
> Or do I overlook something?

No, I also just checked that #6430 is merged.

**Comment by ialidzhikov** [comment]
Will it work if we completely revert #6235? IIUC now https://github.com/gardener/gardener/pull/6430 is partial revert of #6235 (without the changes that deploy `gardener-system-critical` as part of the Seed bootstrap). And to me it seems that the issue is that in #6430 we don't deploy the `gardener-system-critical` PriorityClass.

**Comment by ialidzhikov** [comment]
As https://github.com/gardener/gardener/issues/6257 is meanwhile merged (and there are seed components that rely on the `gardener-system-critical` PriorityClass), with @acumino we rather tend to completely revert https://github.com/gardener/gardener/pull/6235. It can be followed up separately later on how to migrate the gardenlet Deployment to the new PriorityClass.

**Comment by ialidzhikov** [comment]
I had a call with @kris94 , he is also fine with the revert of https://github.com/gardener/gardener/pull/6235 and then cherry-picking it to v1.52.
Then we can follow a 2 release migration process for switching gardenlet back to the `gardener-system-critical` PriorityClass.

**Comment by acumino** [comment]
> I had a call with @kris94 , he is also fine with the revert of #6235 and then cherry-picking it to v1.52. Then we can follow a 2 release migration process for switching gardenlet back to the `gardener-system-critical` PriorityClass.

Since #6257 is merged not only `gradenlet` but everything which is using `gardener-system-critical` priority class needs to be switched to some different priority class as the first step and later in the second step we can clean that temporary priority class and let helm deploy the `gardener-system-critical` priority class.
