### ISSUE TITLE
ERR_INFRA_DEPENDENCIES wrongfully detected gardener internal error

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#6442]
**How to categorize this issue?**

/area ops-productivity quality usability
/kind bug

**What happened**:
`ERR_INFRA_DEPENDENCIES` wrongfully detect gardener internal error.
In details, a shoot reconciliation failed with
```
task "Deploying backup entry" failed: an error on the server ("Internal
  Server Error: \"/apis/core.gardener.cloud/v1beta1/namespaces/garden-foo/backupentries/shoot--foo--bar--7e508fce-7a85-4f11-9202-26518f2a493b\":
  Post \"https://virtual-garden-kube-apiserver:443/apis/authorization.k8s.io/v1/subjectaccessreviews?timeout=10s\":
  net/http: request canceled (Client.Timeout exceeded while awaiting headers)") has
  prevented the request from succeeding (patch backupentries.core.gardener.cloud shoot--foo--bar--7e508fce-7a85-4f11-9202-26518f2a493b)
```

`ERR_INFRA_DEPENDENCIES` is classified as a user non-retryable error but I don's see how a shoot owner can deal with this error.

**What you expected to happen**:
This internal to the gardener error to not be classified as `ERR_INFRA_DEPENDENCIES`

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.51.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by dguendisch** [comment]
Happened again with several clusters that sporadically faced an InternalServerError from openstack and immediately went into Failed state, hence required manual reconcilation.

<details><summary>Details</summary><p>

```
Your Action is required
This error is flagged as user error which indicates that no Gardener operator action is required. Please read the error message carefully and take action.
There is a problem with your secret shoot-operator-xxx:Infrastructure operation failed as unmanaged resources exist in your cloud provider account. Please delete all manually created resources related to this Shoot.
Worker extension (shoot--it--tm03u-aou/tm03u-aou) reports failing health check: machine "shoot--it--tm03u-aou-worker-1-z1-dc585-md592" failed: VM deletion failed due to - machine codes error: code = [Internal] message = [Internal Server Error]. Aborting operation. Initiate VM deletion.
```

</p></details>

**Comment by timebertt** [comment]
ref #5444

**Comment by rfranzke** [comment]
Thanks for reporting!
We talked about this one this morning, and we feel that we should rather close and not fix it right now. This doesn't seem something that was newly introduced and rather looks like a transient error. Instead, we rather wanted to spend the time on the proper solution (#5444) once the PSP migration story (#5250) is finished, cc @shafeeqes.
Kindly `/reopen` if you object and think this is of such importance that it cannot wait for #5444.

/close
