### ISSUE TITLE
ERR_INFRA_UNAUTHENTICATED wrongfully detected transient Azure API error

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#6453]
**How to categorize this issue?**

/area ops-productivity
/kind bug

**What happened**:
A shoot reconciliation failed with 
```
codes:
- ERR_INFRA_UNAUTHENTICATED
description: 'task "Waiting until shoot worker nodes have been reconciled" failed:
  Error while waiting for Worker shoot--foo--bar/bar to become ready:
  error during reconciliation: Error reconciling worker: Failed while waiting for
  all machine deployments to be ready: machine(s) failed: 1 error occurred: "shoot--foo--bar-worker-z3-7b7bd-4sz7h":
  Cloud provider message - machine codes error: code = [Internal] message = [marketplaceordering.MarketplaceAgreementsClient#Get:
  Failure responding to request: StatusCode=404 -- Original Error: autorest/azure:
  error response cannot be parsed: "The resource you are looking for has been removed,
  had its name changed, or is temporarily unavailable." error: invalid character ''T''
  looking for beginning of value]'
lastUpdateTime: '2022-08-05T08:00:02Z'
taskID: Waiting until shoot worker nodes have been reconciled
```

And this error is classified as `ERR_INFRA_UNAUTHENTICATED` just because of the presence of `invalid character` in the error message.

**What you expected to happen**:
Such errors to not be classified as `ERR_INFRA_UNAUTHENTICATED`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
#5444 

**Environment**:

- Gardener version: v1.51.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
Thanks for reporting!
We talked about this one this morning, and we feel that we should rather close and not fix it right now. This doesn't seem something that was newly introduced and rather looks like a transient error. Instead, we rather wanted to spend the time on the proper solution (#5444) once the PSP migration story (#5250) is finished, cc @shafeeqes.
Kindly `/reopen` if you object and think this is of such importance that it cannot wait for #5444.

/close
