### ISSUE TITLE
Switch back to the upstream ingress-default-backend image

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#6517]
**How to categorize this issue?**

/area open-source
/kind enhancement

**What would you like to be added**:
We switched back from `k8s.gcr.io/defaultbackend` to the https://github.com/gardener/ingress-default-backend because the upstream image is not multi-arch - ref https://github.com/kubernetes/ingress-gce/issues/1719.
We should switch back to the upstream image once it is multi-arch.

**Why is this needed**:
Less forks, more upstream image consumption.

**Comment by acumino** [comment]
Community has decided not to publish the image [ref](https://github.com/kubernetes/ingress-gce/issues/1719#issuecomment-1648501153).
/close
