### ISSUE TITLE
Shoots are not labelled for globally enabled extensions

### ISSUE THREAD

**Issue by MartinWeindel** [gardener/gardener#6528]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
Shoots are labelled for their extensions.
For example, if you add the extension of type `shoot-dns-service`, the shoot gets the label `extensions.extensions.gardener.cloud/shoot-dns-service: "true"`.
They same should be true for globally enabled extensions, but it does not.
As this label may be used to filter webhooks by an object selector, such webhooks are not executed anymore. 

**What you expected to happen**:
Shoots should have labels for globally enabled extensions.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot cluster on a landscape with an globally enabled extension. The shoot should be augmented with the label for this extension, but it does not.

**Anything else we need to know?**:
Related to this code: https://github.com/gardener/gardener/blob/367f160cab063463dfd06d9ab488334fccf3414a/plugin/pkg/global/extensionlabels/admission.go#L203-L230

**Environment**:

- Gardener version: v1.53.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
@MartinWeindel Thanks for reporting, nice issue description :)
