### ISSUE TITLE
Ensure Deletion of Logfiles older than Two weeks

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener#653]
In order to be DIPA compliant we need to ensure that logfiles older than 2 weeks are deleted.

### Implementation proposal

There are several ways on how the logging stack of Docker can be configured during cloud init. There may be an option to write to a new file every day and to rotate the log every day for up to fourteen days. In case there is no such option we may have to write a custom logger which provides this option.

### Definition of Done

There shall be a test that checkes that there are no logfiles older than 14 days. As staging is usually updated in shorter periods of time (where logs are being deleted) that test should be run on the canary landscape.

### Side conditions

We will be writing the logs to an external logging stack (EFK). This logging stack must be made compliant as well.

**Comment by ialidzhikov** [comment]
I will take this one.

**Comment by vlerenc** [comment]
Thanks for this ticket/taking it. Indeed we have two locations, we need to tweak the Docker log file handling and the ES log handling. I am not sure about Stackdriver for our Garden GKE clusters. I don't think we use that at all (@ThormaehlenFred, @mliepold), so there should be no issue with that (atm).

**Comment by mliepold** [comment]
The container log files of our Garden GKE clusters are not delivered to Stackdriver at the moment.
However some AuditLog, cluster operation and GCE resource information is logged there by default.

**Comment by vlerenc** [comment]
Is that a strict rule (14d) @marwinski? Sometimes, Gardener operators would like to have logs available for more than 14d in order to have enough time to follow issues and provide RCAs.

cc @ThormaehlenFred

**Comment by JordanJordanov** [comment]
DIPA requirements state we need to keep logs for 14 days. 
Due to personal data in the logs (incl. IP addresses) DPP requirements state we need to delete the logs after a reasonable period of time, which we decided to be 14 days.
