### ISSUE TITLE
`check-docforge` is failing in `ci-gardener-unit`

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#6539]
**How to categorize this issue?**

/area documentation
/kind bug

**What happened**:

`check-docforge` is always failing in `ci-gardener-unit`, e.g. https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-unit/1560512284504100864#1:build-log.txt%3A812-832:

```
> Check Docforge Manifest
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3569  100  3569    0     0   105k      0 --:--:-- --:--:-- --:--:--  105k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    73  100    73    0     0   3173      0 --:--:-- --:--:-- --:--:--  3173
REPO_PATH= /home/prow/go/src/github.com/gardener/gardener
REPO_NAME= gardener
MANIFEST_PATH= /home/prow/go/src/github.com/gardener/gardener/.docforge/manifest.yaml
USE_TOKEN= false
USE_CACHE= false
DIFF_DIRS= .docforge/;docs/
CONFIG_PATH= /tmp/tmp.y7jAEOkKXu/manifest-config
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
There is no diff in the checked directories so the script exits successfully
```

However, `check-docforge` doesn't set an error exit code indicating a failure, hence the job passes and no one actually noticed the issue.

**What you expected to happen**:

- `make check-docforge` to set a proper exit code indicating a failure
- `make check-docforge` to work in `ci-gardener-unit`

Alternatively, `make check-docforge` could be removed from `ci-gardener-unit`: https://github.com/gardener/ci-infra/blob/0b2ee875a76de0babccf4d6ad6e83fea71e612f5/config/jobs/gardener/gardener-unit-tests.yaml#L63

**Comment by timebertt** [comment]
@Kristian-ZH @Kostov6 can you take a look at this please?

**Comment by Kostov6** [comment]
can you tell me the version of git used?

**Comment by timebertt** [comment]
Here is the job manifest including the used image:
https://github.com/gardener/ci-infra/blob/master/config/jobs/gardener/gardener-unit-tests.yaml#L54

**Comment by Kostov6** [comment]
From my understanding the error is that origin/master does not exist. After local testing my biggest suspicion is that there is no origin remote but I'm not sure how to validate this. Can someone give me direction how to check if origin is added to the remotes?

**Comment by Kristian-ZH** [comment]
Is there a way to attach to a running/past job the way we could on Concourse via `fly hijack'?

**Comment by timebertt** [comment]
You can try out `mkpj.sh` and `pj-on-kind.sh` from https://github.com/gardener/ci-infra/tree/master/config.
It basically gives you the `Pod` spec as it would run on the prow cluster and then you can investigate in on a local kind cluster.
