### ISSUE TITLE
[Flaky Test] `CP Migration Test Suite` is flaky

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#6565]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
`CP Migration Test Suite - /src/test/testmachinery/system/shoot_cp_migration`

**CI link**:
Not applicable (internal test-machinery).

**Reason for failure**:

I noticed 2 flakes in the last days (the one is on gcp, the other one is on alicloud):
```
2022-08-18T14:52:53.859347117Z stdout F   In [AfterEach] at: /src/test/testmachinery/system/shoot_cp_migration/migrate_test.go:88
2022-08-18T14:52:53.859331672Z stdout F   The Shoot CP Migration health checks failed with: the following secrets did not have their data or labels persisted during control plane migration: [ca-provider-gcp-controlplane-d483fd48]
```

```
2022-08-22T15:02:35.54678121Z stdout F   In [AfterEach] at: /src/test/testmachinery/system/shoot_cp_migration/migrate_test.go:88
2022-08-22T15:02:35.546775973Z stdout F   The Shoot CP Migration health checks failed with: the following secrets did not have their data or labels persisted during control plane migration: [ca-provider-alicloud-controlplane-f36f9b25]
```

More flakes:
```
2022-08-23T15:01:48.560884288Z stdout F   In [AfterEach] at: /src/test/testmachinery/system/shoot_cp_migration/migrate_test.go:88
2022-08-23T15:01:48.56087846Z stdout F   The Shoot CP Migration health checks failed with: the following secrets did not have their data or labels persisted during control plane migration: [ca-provider-azure-controlplane-9e2c8c05]
```

**Anything else we need to know**:

**Environment**:

- Gardener version: 195189a61500b1010d9555c816755a91c0747e7c

**Comment by ialidzhikov** [comment]
cc @plkokanov

**Comment by ialidzhikov** [comment]
More verbose logging from a failed run:
```
Secret shoot--it--tmig2-6bq-hs-mgr/ca-provider-aws-controlplane-bdef740c did not have it's data persisted.
Secret shoot--it--tmig2-6bq-hs-mgr/ca-provider-aws-controlplane-bdef740c did not have it's labels persisted: labels before migration: map[checksum-of-config:6178420258531182942 issued-at-time:1662389362 last-rotation-initiation-time: managed-by:secrets-manager manager-identity:provider-aws-controlplane name:ca-provider-aws-controlplane persist:true valid-until-time:1978008562], labels after migration: map[checksum-of-config:6178420258531182942 issued-at-time:1662390520 last-rotation-initiation-time: managed-by:secrets-manager manager-identity:provider-aws-controlplane name:ca-provider-aws-controlplane persist:true valid-until-time:1978009720]
```

The secret name does not change but its data is regenerated.
We were discussing that the Secret can be regenerated during `restore` if is not present in the ShootState for some reason.
During `migrate` of a ControlPlane we delete the ControlPlane. Deletion of ControlPlane at the end calls `sm.Cleanup()`

https://github.com/gardener/gardener/blob/cffdb9fd10d598be614d90055ef1bf79d4e5a791/extensions/pkg/controller/controlplane/genericactuator/actuator.go#L533

which should also delete the Secrets. But the gardenlet's shootsecret controller does not remove Secrets from the ShootState when a Secret is deleted during `migrate` operation of a Shoot.

https://github.com/gardener/gardener/blob/b1e7f278b6d3bc781631fbbb3b3292c816355fe2/pkg/gardenlet/controller/shootsecret/reconciler.go#L142-L143

For now I am not able to explain the flakes or reproduce them.

**Comment by ialidzhikov** [comment]
I am now wondering whether the issue can be caused by https://github.com/kubernetes/kubernetes/issues/110625 (similar to https://github.com/gardener/gardener/issues/6441). In short the kube-apiserver does not always return all of the resources when `--label-selector` /`--field-selector` are used. Our Seeds are at 1.23.6, the corresponding backport for 1.23 is present in 1.23.9+.
I think it makes sense to update our Seeds to 1.23.9+ just to make sure that we are not hitting the above-mentioned issue in the context of this issue (or any other one). @dguendisch @BeckerMax WDYT?

**Comment by dguendisch** [comment]
Sure, I added an internal issue on the update, let's discuss the priority there.

**Comment by ialidzhikov** [comment]
Wrt https://github.com/gardener/gardener/issues/6565#issuecomment-1248269874 I am able to reproduce according to the steps in https://github.com/kubernetes/kubernetes/pull/110652#issue-1276119362 but I am not sure whether it can be reproduced with client-go/controller-runtime client. `--chunk-size` flag has client side implementation that relies on the `limit` and `continue` query params.
Anyways, let's see whether this issue still occurs in new runs of the test.

**Comment by ialidzhikov** [comment]
There is 1 failure from 2 days ago. The newest failures are due to https://github.com/gardener/gardener/issues/6703.

**Comment by ialidzhikov** [comment]
Meanwhile our Seeds were updated to 1.23.9. I now checked and was not able to see the particular error from this issue occurring for the past 10 days. Let's keep it open for a while to see whether it will occur again in the next days.

**Comment by ialidzhikov** [comment]
I now actually noticed a failure on other landscape from 2 days ago:
```
2022-10-05T15:57:55.202114102Z stdout F   Secret shoot--it--tm1m0-hgk-hs-mgr/ca-provider-openstack-controlplane-6a1a1e13 did not have it's labels persisted: labels before migration: map[checksum-of-config:14896576601499449788 issued-at-time:1664983816 last-rotation-initiation-time: managed-by:secrets-manager manager-identity:provider-openstack-controlplane name:ca-provider-openstack-controlplane persist:true valid-until-time:1980603016], labels after migration: map[checksum-of-config:14896576601499449788 issued-at-time:1664984997 last-rotation-initiation-time: managed-by:secrets-manager manager-identity:provider-openstack-controlplane name:ca-provider-openstack-controlplane persist:true valid-until-time:1980604197]
2022-10-05T15:57:55.202110499Z stdout F   Secret shoot--it--tm1m0-hgk-hs-mgr/ca-provider-openstack-controlplane-6a1a1e13 did not have it's data persisted.
```

**Comment by ialidzhikov** [comment]
In short, the issue occurs due to a transient error in the migrate flow after the ControlPlane Destroy. In the migrate flow we first Restore the ControlPlane, then we Destroy it. If a transient error occurs after the ControlPlane Destroy, in the next try we will Restore the ControlPlane which will created fresh new `ca-provider-{provider}-controlplane` Secret (because the existing ones were already deleted during Destroy) which will be updated/synced to the Shoot state by gardenlet.

Restore of ControlPlane calls Reconcile which generates all Secrets if they don't exist.

https://github.com/gardener/gardener/blob/cffdb9fd10d598be614d90055ef1bf79d4e5a791/extensions/pkg/controller/controlplane/genericactuator/actuator.go#L579

https://github.com/gardener/gardener/blob/cffdb9fd10d598be614d90055ef1bf79d4e5a791/extensions/pkg/controller/controlplane/genericactuator/actuator.go#L212-L217

Delete/Migrate of ControlPlane deletes all SecretManager Secrets:
https://github.com/gardener/gardener/blob/cffdb9fd10d598be614d90055ef1bf79d4e5a791/extensions/pkg/controller/controlplane/genericactuator/actuator.go#L533

**Steps to reproduce:**

1. Create a Shoot on Seed `foo`.

2. Save the `ca-provider-{provider}-controlplane` Secret to be able to compare it afterwards.

3. Simulate a transient error after https://github.com/gardener/gardener/blob/036fa069d610a2a62f7b819493df3bd19aa779a7/pkg/gardenlet/controller/shoot/shoot_control_migrate.go#L280:

   I used a webhook that forbids deleting the kube-apiserver Deployment.

4. Trigger CP migration to Seed `bar`.

5. Make sure that on every retry of the migrate flow the ControlPlane is redeployed and destroyed and the `ca-provider-{provider}-controlplane` Secrets are recreated.

6. Compare the `ca-provider-{provider}-controlplane` in the ShootState and the one you saved in step 2. and make sure they are different.

**Comment by rfranzke** [comment]
So it's an actual bug that we found here, nice summary @ialidzhikov, thanks. Do you have any ideas/suggestions what we can improve?

**Comment by plkokanov** [comment]
Before the introduction of the secrets manager we used to redeploy all secrets from the shoot state at the start of the migrate phase. Not sure if the same can be done now though - basically change this code:
https://github.com/gardener/gardener/blob/66b1975adf5d6656930d1273c150792028646ad5/pkg/operation/botanist/secrets.go#L59-L63
to also be executed during `Migrate` phase.

**Comment by rfranzke** [comment]
Maybe, but it feels a bit weird/sounds like a workaround. Can we rather prevent executing some of the tasks in the migrate flow when we already deleted the `ControlPlane` (same approach what we do in the deletion flow)? This way, we wouldn't even try to restore the `ControlPlane` resource again unnecessarily.

**Comment by plkokanov** [comment]
> same approach what we do in the deletion flow

We currently use the exact same approach and flags to determine if the `ControlPlane` resource needs to be redeployed.
So IIUC this issue can only happen if the migration flow errors after the `ControlPlane` is migrated, but before the `kube-apiserver` deployment is deleted. Generally, if we've already passed the step that migrates the `ControlPlane`, all `ManagedResources` and all extension resources that might depend on the `kube-apiserver` should also be migrated and deleted and there should be no reason to redeploy the `kube-apiserver` and restore the `ControlPlane`.
So perhaps we could improve the check for the migration flow and only redeploy the `ControlPlane` and the `kube-apiserver` if there are any `ManagedResources` or extension resources retrieved from [this list](https://github.com/gardener/gardener/blob/40b0bf10522e53c55ceaf1b361a4d016a94fe741/pkg/operation/shoot/shoot.go#L361-L370) inside the shoot's namespace.

**Comment by rfranzke** [comment]
> and only redeploy the ControlPlane and the kube-apiserver if there are any ManagedResources or extension resources retrieved from [this list](https://github.com/gardener/gardener/blob/40b0bf10522e53c55ceaf1b361a4d016a94fe741/pkg/operation/shoot/shoot.go#L361-L370) inside the shoot's namespace.

I don't think we want to make such assumptions. Extensions using `ManagedResource`s is just a convention, not a requirement and rather an implementation detail.
Can we rather not redeploy the `ControlPlane` if it is already deleted?

**Comment by plkokanov** [comment]
I found the issue that was causing this redeployment in the first place: https://github.com/gardener/gardener/issues/4484. Basically, [the `WakeUpKubeAPIServer`])(https://github.com/gardener/gardener/blob/40b0bf10522e53c55ceaf1b361a4d016a94fe741/pkg/gardenlet/controller/shoot/shoot_control_migrate.go#L229-L233) would cause problems for providers for which the webhook that mutates the `kube-apiserver` deployment relies on the `cloud-provider-config` secret (e.g. azure and alicloud), if the `ControlPlane` is gone. Both `RestoreControlPlane` and `WakeUpKubeAPIServer` steps are not executed if the `kube-apiserver` deployment does not exist, however we cannot delete the `ControlPlane` after deleting the `kube-apiserver` deployment, because then the deletion of `ManagedResources` that are created by the `ControlPlane` reconciliation would fail.

Another idea that sprang to mind is to not restore the `ControlPlane` and do not wake up the `kube-apiserver`, if it has already been woken up (meaning we would need to add a check if the replicas are > 0), although that's also a bit counterintuitive to what we generally do when deploying components.

**Comment by rfranzke** [comment]
As discussed in our meeting today, the only reason that the `ControlPlane` is deployed before the `kube-apiserver` was that we don't have CSI for all providers when the Kubernetes version is < `1.21`. Consequently, when we drop support for shoots < `1.21`, we can clean all this up (i.e., first deploy `kube-apiserver`, then deploy `ControlPlane`) and then these issues should disappear, am I right?

In this case, I would vote to not make it even more complicated now and wait for above mentioned cleanup. Instead, maybe we can improve the test assertions to accept re-generated secrets of the provider extensions so that the test does no longer flake. It shouldn't be critical if they are recomputed after a migration.

**Comment by plkokanov** [comment]
@rfranzke we could temporarily skip this assertion similar to what we did for resources inside the `Shoot` that are generated from `ManagedResources`: https://github.com/gardener/gardener/blob/1e01b2163c2383f3692d70e14f4f85072211b4e6/.test-defs/MigrateShoot.yaml#L20

Btw do we currently have any timeframe for dropping support for k8s `1.20`?

**Comment by rfranzke** [comment]
I think we can start with the removal after 1.63 got released, cc @dimitar-kostadinov @ialidzhikov.
Generally, we are in discussion about applying a general guideline for supporting only 3-4 Kubernetes versions at a time, but that's not yet fully clarified.

**Comment by rfranzke** [comment]
This issue can be tackled after #7405 has been fixed.
