### ISSUE TITLE
Problematic webhook remediator can conflict with 3rd party webhook reconciliation apps

### ISSUE THREAD

**Issue by oliver-goetz** [gardener/gardener#6566]
**How to categorize this issue?**

/area ops-productivity
/kind bug

**What happened**:
The problematic webhook remediato introduced with https://github.com/gardener/gardener/pull/6090 could have interdependencies with 3rd party applications reconciling webhooks resulting in a problematic outcome.
Assuming there is a third party application, which reconciles webhooks into an "undesired state" over and over again, even after it was remediated, there are several issues.
- The third party application and webhook remediator are continuously changing the `mutatingwebhookconfiguration` back-and-forth
  - This could be observed at the increasing number of generations of the `mutatingwebhookconfiguration` and in gardenlet logs
  - The annotation `gardener.cloud/warning` could be misleading for the cluster operator, because the changes announced by `The following modifications have been made:` are not always existing in the respective `mutatingwebhookconfiguration`
- It is hard for a cluster operator to solve the issue, because the link to [Kubernetes webhook best-practices](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#best-practices-and-warnings) mentioned in `gardener.cloud/warning` annotation is not very helpful. The webhook remediator (and the constraints check) checks for the concrete entries of [webhookConstraintMatchers](https://github.com/gardener/gardener/blob/195189a61500b1010d9555c816755a91c0747e7c/pkg/operation/botanist/matchers/matcher.go#L60-L176) only, but this is not mentioned anywhere.

**What you expected to happen**:
- Webhook Remediator should not battle with third party webhook reconciler applications
  - As we cannot control third party apps it might make sense to stop remediating webhooks after a certain number of retries and rely on displaying the `shoot constraints` in this case.
- It should be mentioned that rules have to match gardener `webhookConstraintMatchers` in order to solve the issue.
  - Alternatively the `webhookConstraintMatchers` could work more generically and consider things like custom labels too as long as they result in excluding the relevant objects 
- The default namespace label `kubernetes.io/metadata.name: kube-system` should be added to [kubeSystemLabels](https://github.com/gardener/gardener/blob/195189a61500b1010d9555c816755a91c0747e7c/pkg/operation/botanist/matchers/matcher.go#L50-L53) as this label looks like a common way to create namespace selectors.
- `gardener.cloud/warning` annotation should not be misleading

**How to reproduce it (as minimally and precisely as possible)**:
Enable webhook remediator by setting `.controllers.shootCare.webhookRemediatorEnabled=true` in the gardenlet's configuration file.

Install an application which reconciles webhook into a gardener cluster.
This is an example using [kyverno](https://kyverno.io/) with a sample policy which causes a remediation of `mutatingwebhookconfiguration` `kyverno-resource-mutating-webhook-cfg`
```
kubectl apply -f https://raw.githubusercontent.com/kyverno/kyverno/release-1.7/config/release/install.yaml
kubectl apply -f https://raw.githubusercontent.com/kyverno/policies/main/other/add-imagepullsecrets/add-imagepullsecrets.yaml
```
Check annotations, content and generations of conflicting `mutatingwebhookconfiguration`.
```
kubectl get mutatingwebhookconfigurations kyverno-resource-mutating-webhook-cfg -o yaml
```

**Environment**:

- Gardener version: v1.54.0-dev
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
Well, exactly this situation was the reason why we had not implemented the auto-remediation earlier. I have mixed feelings about putting more complexity into it right now to cover such cases (unless they occur at high rate; though I would expect this to rather be an exception since not many webhooks are automatically reconciled by controllers).

> As we cannot control third party apps it might make sense to stop remediating webhooks after a certain number of retries and rely on displaying the shoot constraints in this case.


> gardener.cloud/warning annotation should not be misleading

Yes, we could probably store information about how often we have already remediated this webhook in a given timeframe as annotations on the webhooks and stop, eventually. In this case, the warning annotation could be rephrased accordingly.

> The default namespace label kubernetes.io/metadata.name: kube-system should be added to [kubeSystemLabels](https://github.com/gardener/gardener/blob/195189a61500b1010d9555c816755a91c0747e7c/pkg/operation/botanist/matchers/matcher.go#L50-L53) as this label looks like a common way to create namespace selectors.

Sounds reasonable 👍🏻 

> It should be mentioned that rules have to match gardener webhookConstraintMatchers in order to solve the issue.

Where? I don't think we have documented them anywhere. The intent was that the warning annotation contains the needed information for users to resolve the issues. Why isn't this good enough?

> Alternatively the webhookConstraintMatchers could work more generically and consider things like custom labels too as long as they result in excluding the relevant objects

Sounds even more complex.

**Comment by oliver-goetz** [comment]
> > As we cannot control third party apps it might make sense to stop remediating webhooks after a certain number of retries and rely on displaying the shoot constraints in this case.
> 
> > gardener.cloud/warning annotation should not be misleading
> 
> Yes, we could probably store information about how often we have already remediated this webhook in a given timeframe as annotations on the webhooks and stop, eventually. In this case, the warning annotation could be rephrased accordingly.

That's what I have in my mind too.
 
> > It should be mentioned that rules have to match gardener webhookConstraintMatchers in order to solve the issue.
> 
> Where? I don't think we have documented them anywhere. The intent was that the warning annotation contains the needed information for users to resolve the issues. Why isn't this good enough?

After reading [this paragraph](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#avoiding-operating-on-the-kube-system-namespace) a potential solution could be adding a custom label like `my.webhook.com/disable: true` to `kube-system` namespace and create a corresponding matcher for it.
This would prevent the webhook from running in `kube-system` namespace, but does not fit to the `webhookConstraintMatchers` and the webhook will still be remediated.
When I faced this issue, I was wondering why the webhook was still remediated after I added `kube-system` namespace to an existing `kubernetes.io/metadata.name` matcher in the webhook configuration.

Adding one sentence like `Please apply the proposed changes to your webhook configuration to prevent future remediations` could be enough.

> > Alternatively the webhookConstraintMatchers could work more generically and consider things like custom labels too as long as they result in excluding the relevant objects
> 
> Sounds even more complex.

Agree, I just added it for sake of completeness 😄

**Comment by ialidzhikov** [comment]
We discussed that it would be useful to add a metric that keeps track of how often a webhook for Shoot is remediated. We need to check how to add this metrics - if it requires storing values in a ConfigMap, then we rather think that it is getting too complex and we kind of agree to live with the current state.
