### ISSUE TITLE
Duplication in documentation

### ISSUE THREAD

**Issue by rodcloutier** [gardener/gardener#6602]
**How to categorize this issue?**
/area documentation
/kind enhancement

**What would you like to be added**:

There seems to be two documentation page that document the same process, at least have the same name, but in different manners. 

* Development: https://gardener.cloud/docs/gardener/development/getting_started_locally/
* Deployment: https://gardener.cloud/docs/gardener/deployment/getting_started_locally/

**Why is this needed**:

We should unify the documentation to have a single source of truth or make the distinction between the same process more obvious.

**Comment by timebertt** [comment]
This is on purpose, actually. 
The second guide is a general getting started for when you want to get started with trying out gardener.
The first guide however is targeted at developers.

There are big overlaps, but also important differences in the setup (e.g., running gardener components as pods in the cluster or as processes on the host machine).
We want to strive towards a single skaffold-based setup for both current variants as part of #6016.
However, as long as we have both, we can't deduplicate the documentation.
/close
