### ISSUE TITLE
[Flaky Test] CloudProfile Controller Integration Test Suite

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#6607]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
`CloudProfile Controller Integration Test Suite`

**CI link**:
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6604/pull-gardener-integration/1564895635423891456

**Reason for failure**:

```
Failed after 0.210s.
  Expected success, but got an error:
      <*errors.StatusError | 0xc003f06640>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "cloudprofiles.core.gardener.cloud \"cloudprofile-controller-test-2tt[59](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6604/pull-gardener-integration/1564895635423891456#1:build-log.txt%3A59)\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "cloudprofile-controller-test-2tt59",
                  Group: "core.gardener.cloud",
                  Kind: "cloudprofiles",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
      cloudprofiles.core.gardener.cloud "cloudprofile-controller-test-2tt59" not found
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/cloudprofile/cloudprofile_test.go:151
```

**Anything else we need to know**:

**Comment by shafeeqes** [comment]
Another occurence https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6570/pull-gardener-integration/1565631458125549568

**Comment by acumino** [comment]
```
   STEP: Create CloudProfile 09/02/22 09:24:53.147
    {"level":"info","ts":"2022-09-02T09:24:53.151Z","msg":"Adding finalizer","controller":"cloudprofile","controllerGroup":"core.gardener.cloud","controllerKind":"CloudProfile","cloudProfile":{"name":"cloudprofile-controller-test-rvr4r"},"namespace":"","name":"cloudprofile-controller-test-rvr4r","reconcileID":"1137059d-31e2-41e0-8472-039d2d808221"}
    {"level":"info","ts":"2022-09-02T09:24:53.152Z","logger":"cloudprofile-controller-test","msg":"Created CloudProfile for test","cloudProfile":{"name":"cloudprofile-controller-test-rvr4r"}}
    STEP: Create Shoot 09/02/22 09:24:53.152
    {"level":"info","ts":"2022-09-02T09:24:53.162Z","logger":"KubeAPIWarningLogger","msg":"you should consider disabling the static token kubeconfig, see https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md for details"}
    {"level":"info","ts":"2022-09-02T09:24:53.162Z","logger":"cloudprofile-controller-test","msg":"Created shoot for test","shoot":{"namespace":"cloudprofile-controller-test-qbcjf","name":"cloudprofile-controller-test-4dbxc"}}
    STEP: Ensure finalizer got added 09/02/22 09:24:53.162
    STEP: Delete CloudProfile 09/02/22 09:24:53.165
    STEP: Ensure CloudProfile is not released 09/02/22 09:24:53.169
    {"level":"info","ts":"2022-09-02T09:24:53.170Z","msg":"No Shoots are referencing the CloudProfile, deletion accepted","controller":"cloudprofile","controllerGroup":"core.gardener.cloud","controllerKind":"CloudProfile","cloudProfile":{"name":"cloudprofile-controller-test-rvr4r"},"namespace":"","name":"cloudprofile-controller-test-rvr4r","reconcileID":"7103b98c-97ce-4d92-865d-614252c874a3"}
    {"level":"info","ts":"2022-09-02T09:24:53.170Z","msg":"Removing finalizer","controller":"cloudprofile","controllerGroup":"core.gardener.cloud","controllerKind":"CloudProfile","cloudProfile":{"name":"cloudprofile-controller-test-rvr4r"},"namespace":"","name":"cloudprofile-controller-test-rvr4r","reconcileID":"7103b98c-97ce-4d92-865d-614252c874a3"}
    {"level":"debug","ts":"2022-09-02T09:24:53.182Z","msg":"Object is gone, stop reconciling","controller":"cloudprofile","controllerGroup":"core.gardener.cloud","controllerKind":"CloudProfile","cloudProfile":{"name":"cloudprofile-controller-test-rvr4r"},"namespace":"","name":"cloudprofile-controller-test-rvr4r","reconcileID":"b905280e-b062-479f-9411-70[59](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6570/pull-gardener-integration/1565631458125549568#1:build-log.txt%3A59)cfe33430"}
    STEP: Delete Shoot 09/02/22 09:24:53.377
    STEP: Delete CloudProfile 09/02/22 09:24:53.384
```

From the logs, I guess the cloud profile is being deleted before even the shoot gets persisted. 
Shoots get created at `09/02/22 09:24:53.152`
```
STEP: Create Shoot at 09/02/22 09:24:53.152
    {"level":"info","ts":"2022-09-02T09:24:53.162Z","logger":"KubeAPIWarningLogger","msg":"you should consider disabling the static token kubeconfig, see https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md for details"}
```
and meanwhile, the cloud profile is deleted at `2022-09-02T09:24:53.170Z`
```
    {"level":"info","ts":"2022-09-02T09:24:53.170Z","msg":"No Shoots are referencing the CloudProfile, deletion accepted","controller":"cloudprofile","controllerGroup":"core.gardener.cloud","controllerKind":"CloudProfile","cloudProfile":{"name":"cloudprofile-controller-test-rvr4r"},"namespace":"","name":"cloudprofile-controller-test-rvr4r","reconcileID":"7103b98c-97ce-4d92-865d-614252c874a3"}
```
Probably adding eventually call after https://github.com/gardener/gardener/blob/8a3036e718172f41390527a402ae18b8860f89be/test/integration/controllermanager/cloudprofile/cloudprofile_test.go#L103 should resolve it.

I was not able to produce the flake locally so can't confirm if the changes which I suggested will solve the issue.

**Comment by rfranzke** [comment]
Thanks for checking @acumino!

However, I don't think that adding `Eventually` to this line will fix it. The shoot is actually persisted (otherwise the `Create` call would have failed), but I assume that the manager cache is stale and has not yet observed it. Hence, when the `CloudProfile` is being deleted it will just release it immediately.

Probably we need something like https://github.com/gardener/gardener/blob/de54e290557356c16a266f960a07ed1fd77010e9/test/integration/controllermanager/secretbinding/secretbinding_test.go#L116-L119 before deleting the `CloudProfile`?

**Comment by ary1992** [comment]
> Thanks for checking @acumino!
> 
> However, I don't think that adding `Eventually` to this line will fix it. The shoot is actually persisted (otherwise the `Create` call would have failed), but I assume that the manager cache is stale and has not yet observed it. Hence, when the `CloudProfile` is being deleted it will just release it immediately.
> 
> Probably we need something like
> 
> https://github.com/gardener/gardener/blob/de54e290557356c16a266f960a07ed1fd77010e9/test/integration/controllermanager/secretbinding/secretbinding_test.go#L116-L119
> 
> before deleting the `CloudProfile`?

Similar issue was there with `ExposureClass` integration test as well.

**Comment by acumino** [comment]
> Probably adding eventually call after

Here I was suggesting the same thing that you suggested i.e adding a get call wrapped in eventually.

**Comment by rfranzke** [comment]
Ah, got it now. Cool :) Yeah, then let's do this and get this fixed. Thanks again!

**Comment by rfranzke** [comment]
There is a similar flake for the `Quota` controller, see https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6625/pull-gardener-integration/1567521678953549824.
I'm opening a PR now.
/assign
