### ISSUE TITLE
[Flaky Test] E2E Test: Gardenlet Kubeconfig Rotation Tests

### ISSUE THREAD

**Issue by shafeeqes** [gardener/gardener#6618]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
https://github.com/gardener/gardener/blob/833e5f89b48079922d39ac43f60a3d853e802f43/test/e2e/managedseed/create_rotate_delete.go#L58

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6570/pull-gardener-e2e-kind/1565631458054246400

**Reason for failure**:
```
 Expected success, but got an error:
      <*errors.errorString | 0xc000156750>: {
          s: "kubeconfig secret has not yet been renewed, timeBeforeRotation: 2022-09-02 09:46:40.027848693 +0000 UTC, newClientCertificateIssuedAt: 2022-09-02 09:46:40 +0000 UTC",
      }
      kubeconfig secret has not yet been renewed, timeBeforeRotation: 2022-09-02 09:46:40.027848693 +0000 UTC, newClientCertificateIssuedAt: 2022-09-02 09:46:40 +0000 UTC
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/e2e/managedseed/create_rotate_delete.go:398
```

**Anything else we need to know**:
Introduced with https://github.com/gardener/gardener/pull/6568

**Comment by timebertt** [comment]
Two more occurrences:
- https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind/1565790237840379904
- https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind/1566273427218632704

**Comment by acumino** [comment]
More occurences:
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6632/pull-gardener-e2e-kind/1567049874501799936
