### ISSUE TITLE
Provide Fork Bomb Protection for Clusters

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener#663]
In a cluster that allows untrusted code execution in pods from multiple tenants (e.g. a CI/CD system) tenants should be protected from fork bombs (see https://en.wikipedia.org/wiki/Fork_bomb). By default cluster nodes in Kubernetes with docker as the container runtime are not protected against this kind of denial-of-service attack.

## Implementation Proposal

There are two generally two ways to implement this requirements:

1. There is an alpha feature in the kubelet
2. A behavioural detection can react on a high number of processes in a pod

### 1. kubelet

alpha feature: add option ```--pod-max-pids``` to the kubelet and enable ```SupportPodPidsLimit=true``` in the ```--feature-gates=```parameter.

We can set this parameter to 100 as a default (should be high enough for every container) and control this by an annotation ```alpha.shoot.garden.sapcloud.io/kubelet-pod-pid-limit: 100```.  This annotation shall be set by default but cluster owners shall be able to change / remove it. 

### 2. Behavioural Approach

In a cluster that allows untrusted code execution in pods from multiple tenants (e.g. a CI/CD system) tenants should be protected from fork bombs (see https://en.wikipedia.org/wiki/Fork_bomb). By default cluster nodes in Kubernetes with docker as the container runtime are not protected against this kind of denial-of-service attack.

Implementation Proposal
There are two generally two ways to implement this requirements:

There is an alpha feature in the kubelet
A behavioural detection can react on a high number of processes in a pod
1. kubelet configuration
alpha feature: add option --pod-max-pids to the kubelet and enable SupportPodPidsLimit=true in the --feature-gates=parameter.

We can set this parameter to 100 as a default (should be high enough for every container) and control this by an annotation `alpha.shoot.garden.sapcloud.io/kubelet-pod-pid-limit: 100`. This annotation shall be set by default but cluster owners shall be able to change / remove it (would require a rolling update of all nodes and might be a problem).

2. Behavioural Approach
A relatively simple program can used the mechanism described in https://www.howtoforge.com/tutorial/trigger-commands-on-file-or-directory-changes-with-incron/ to learn of the start of a new process. This information can be used to detect the number of processes per namespace and potentially react accordingly (e.g. kill pod).

(well this would not be part of the Gardener but a different component)

Definition of Done
 Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
 Unit tests are provided: Have you written automated unit tests?
 Integration tests are provided: Have you written automated integration tests? This should include a test that get a pod killed due to too many processes.
 Minimum API exposure: If you have added/changed public API, was it really necessary/is it minimal?
 Operations guide: Have you updated the operations guide about ops-relevant changes?
 User documentation: Have you updated the READMEs/docs/how-tos about user-relevant changes?

**Comment by i300543** [comment]
Hello,
we at WebIDE are using gardener as our infrastructure provider, and also struggling with protection of our pods against malicious content execution (fork bomb etc)
Is there a timeline when this suggestion could be accepted ?

Thanks

**Comment by marwinski** [comment]
Hi @rfranzke , can you do this in the Gardener team or do you know anybody who could take this?

**Comment by rfranzke** [comment]
@marwinski as you know we are currently focusing on extensibility, but @brunoklein99 volunteered to look into this one

**Comment by marwinski** [comment]
Great @brunoklein99. Let me know if you need anything. For the time being option one should be fine.

**Comment by brunoklein99** [comment]
Instead of adding the parameter as an annotation, wouldn't it be more appropriate to instead add it as a property of [spec.kubernetes.kubelet](https://github.com/gardener/gardener/blob/master/example/90-shoot-local.yaml#L73) which is already (only `featureGates`) being [passed to the chart renderer](https://github.com/gardener/gardener/blob/master/pkg/operation/hybridbotanist/cloud_config.go#L113-L116)?

**Comment by marwinski** [comment]
OK for me as long as @rfranzke agrees. This is an alpha feature and I am not sure the feature gates are meant for exactly that purpose.

**Comment by brunoklein99** [comment]
Agreed. I meant adding a sibling to `featureGates`.

**Comment by rfranzke** [comment]
As long as it is alpha I would not add it to our versioned spec - just start with the annotation.
So, IMHO, in order to enable it in a shoot,

1. the feature gate must be enabled
1. the new annotation specifying the pid-limit must be set.

> This annotation shall be set by default but cluster owners shall be able to change / remove it (would require a rolling update of all nodes and might be a problem).

This I wouldn't do either. Everybody can enable it who wants it. once it is beta/stable we can enable it by default, but not as long as it's alpha.

**Comment by Henrike42** [comment]
How can a cluster owner set the annotation specifying the pid-limit at the moment? I have tried, but the reconcile simply removes it. Is it possible to "secure" our live clusters?

**Comment by brunoklein99** [comment]
Hi, Henrike.
The actual implementation for this hasn't been released yet.
As for why the annotation is being removed, make sure the annotation has a string value. e.g. `alpha.shoot.garden.sapcloud.io/kubelet-pod-pid-limit: "100"`

**Comment by usherfu** [comment]
@brunoklein99 

Thanks for working on this feature. Our stakeholder WebIDE is also interested in this feature. Do you maybe have a rough estimation when this will be available? :-). Thanks.

**Comment by brunoklein99** [comment]
Pretty soon, within next couple weeks probably.

**Comment by marwinski** [comment]
Thanks @brunoklein99 - this is really useful.

**Comment by Henrike42** [comment]
Regarding, the reconcile removal of the annotation: alpha.shoot.garden.sapcloud.io/kubelet-pod-pid-limit: "100" 
I did this like typed above, with a string value. It's still removed.

**Comment by rfranzke** [comment]
@Henrike42 you probably tried to set it via the Dashboard, right? AFAIK it does not support setting these kinds of annotations, is that correct @holgerkoser @petersutter @grolu ?

**Comment by petersutter** [comment]
yes this is filtered out by the dashboard https://github.com/gardener/dashboard/blob/master/backend/lib/services/shoots.js#L63-L77

**Comment by holgerkoser** [comment]
@rfranzke Yes. Currently the dashboard does not allow to modify annotations which match `*.garden.sapcloud.io/*` except  
* 'shoot.garden.sapcloud.io/ignore'
* 'garden.sapcloud.io/purpose'
* 'shoot.garden.sapcloud.io/operation'

The reason is only usability to protect the dashboard user from changing accidentally shoot metadata. We could remove these filters or add others annotations to the list of exceptions. What do you think?

**Comment by rfranzke** [comment]
Not sure anymore what was the reason to add it in the first place - technically, users can anyway modify it by using `kubectl`. So probably it's the best to just remove this restriction instead of maintaining a 'whitelist' for allowed fields?!

**Comment by Henrike42** [comment]
At the moment it doesn't seem possible for a cluster owner to secure a Gardener cluster against the Fork bomb. If I am wrong, can you please provide the corresponding kubectl command and/or describe the necessary actions via the Gardener dashboard?
If I am right, is it possible for the Gardener team to secure our live Gardener shoot clusters? At the moment we have three of them?

**Comment by i300543** [comment]
There is a workaround you could apply in the image(pod) level:
define system user to be used in your dockerfile defining your container, and add the ulimit command into bashrc

**Comment by Henrike42** [comment]
The container uses a Docker image which is constructed from scratch. I put an etc/security/limits.conf file into it, which restricts the number of processes to 2 for all users. However, I can execute Node.js code successfully, which spawns more than 2 child processes.

**Comment by i300543** [comment]
modifying limits.conf file will not work.
this is what we have done in our dockerfile:
#  Create system user
RUN mkdir -p /home/exec && \
    groupadd -g 4000 exec && \
    useradd -u 4001 -g group -s /bin/bash -d /home/user exec && \
    chown -R 4001:3000 /home/exec && \
    chmod 770 -R /home/exec
#impose hard limit on number of processes for users when running in bash
RUN echo $'if [ $(whoami) = "exec" ]; then\n \
	plimit=5000\n \
	else\n \
	plimit=500\n \
	fi\n \
	ulimit -Su $plimit && ulimit -Hu $plimit\n' >> /etc/bash.bashrc
USER exec
ENV HOME=/home/exec
WORKDIR /home/exec

however our only goal was protection against fork bomb not limiting user to 2 processes
here we give 'exec' user soft + hard limit of 5000 processes, and all other users limit of 500 processes.
quick check verified that the container is no longer killed by dropping fork bomb in it's exec bash

**Comment by rfranzke** [comment]
@brunoklein99 the feature gets graduated to beta in 1.14 (https://github.com/kubernetes/kubernetes/pull/72076), so let's not go the "annotation"-way but add it to the shoot spec (`.spec.kubernetes.kubelet.podMaxPids`). That means, for 1.13 clusters we have to add the feature gate automatically if `.spec.kubernetes.kubelet.podMaxPids` is specified, with 1.14 it's enabled by default anyways

**Comment by Henrike42** [comment]
Our goal is also to provide protection against the fork bomb, but before testing a fork bomb. I'd like to test if limits for number of processes work at all. 
I have tried to adapt the solution proposal, so far it's not working. 
Please note, our runtime docker image is built from scratch. It only contains the Node.js executable plus its dependencies and certificates so far. 
What I did now is to add an /etc/bash.bashrc file with the content as described above.
Still I can run Node.js code which spawns more child processes as configured in /etc/bash.bashrc.
My questions:
* is this approach working with a docker image built from scratch containing described /etc/bash.bashrc?
* is this approach working in regards to process creation via Node.js (`require('child_process').spawn`)?

**Comment by i300543** [comment]
I"m sorry the bash solution will not work for nodejs application.
It also contains a flaw as i discovered, because all users running on the same node will share this limitation, and as such its not really a per container limitation in the end.

As such we are stuck until the annotation is supported by gardener
If there are updates related to the dates and times when this is available, please let us know

**Comment by usherfu** [comment]
> @brunoklein99 the feature gets graduated to beta in 1.14 ([kubernetes/kubernetes#72076](https://github.com/kubernetes/kubernetes/pull/72076)), so let's not go the "annotation"-way but add it to the shoot spec (`.spec.kubernetes.kubelet.podMaxPids`). That means, for 1.13 clusters we have to add the feature gate automatically if `.spec.kubernetes.kubelet.podMaxPids` is specified, with 1.14 it's enabled by default anyways

Hi @rfranzke 
Do we have a timeline of shoot spec ".spec.kubernetes.kubelet.podMaxPids" since the feature graduated to beta in1.14 ?

Thanks
Tieyan

**Comment by brunoklein99** [comment]
I have already implemented. Just haven't written the tests yet. Should be
out soon.

**Comment by usherfu** [comment]
@rfranzke @brunoklein99 
Want to avoid any confusion, the implementation from @brunoklein99 is the shoot spec ".spec.kubernetes.kubelet.podMaxPids" as suggsted by @rfranzke , correct?  Thanks for putting the effort!

**Comment by brunoklein99** [comment]
That is correct. :)

**Comment by usherfu** [comment]
Thanks!:-)

**Comment by rfranzke** [comment]
@brunoklein99 mentioned that he is currently busy with other tasks and cannot finish his PR soon.
Based on his work I have created #853 that allows the configuration of the pod pid limit.

**Comment by usherfu** [comment]
@rfranzke Thanks!  We were just discussing with our devx stakeholder:-).
