### ISSUE TITLE
[Flaky Test] ShootValidator Integration Test Suite

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#6642]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
One of the `DeferCleanup` calls from the suite setup is failing:
https://github.com/gardener/gardener/blob/8f2b58bf8d16b1ee3079f68cdc10b66e9dee7918/test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_suite_test.go#L330-L333

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6619/pull-gardener-integration/1567450360757358592

**Reason for failure**:
```
[DeferCleanup (Suite)] [FAILED] [0.024 seconds]
[DeferCleanup (Suite)] 
/home/prow/go/src/github.com/gardener/gardener/test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_suite_test.go:330
  Begin Captured GinkgoWriter Output >>
    STEP: deleting Seed 09/07/22 09:52:23.443
  << End Captured GinkgoWriter Output
  Expected success, but got an error:
      <*errors.StatusError | 0xc001fe1720>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "seeds.core.gardener.cloud \"shootvalidator-test-57nh4\" is forbidden: cannot delete seed shootvalidator-test-57nh4 since it is still used by shoot(s)",
              Reason: "Forbidden",
              Details: {
                  Name: "shootvalidator-test-57nh4",
                  Group: "core.gardener.cloud",
                  Kind: "seeds",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: [40](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6619/pull-gardener-integration/1567450360757358592#1:build-log.txt%3A40)3,
          },
      }
      seeds.core.gardener.cloud "shootvalidator-test-57nh4" is forbidden: cannot delete seed shootvalidator-test-[57](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6619/pull-gardener-integration/1567450360757358592#1:build-log.txt%3A57)nh4 since it is still used by shoot(s)
  In [DeferCleanup (Suite)] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_suite_test.go:332
```

**Anything else we need to know**:

**Comment by shafeeqes** [comment]
```
• [SLOW TEST] [5.025 seconds]
ShootValidator tests User without RBAC for shoots/binding should not be able to create a shoot with .spec.seedName
/home/prow/go/src/github.com/gardener/gardener/test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_test.go:102
```
This test shouldn't be creating Shoots at all. 👀 
https://github.com/gardener/gardener/blob/ba7cb8c4e6dc8fc376a32084ba403959a8edb43d/test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_test.go#L106-L111

**Comment by rfranzke** [comment]
@shafeeqes https://github.com/gardener/gardener/blob/8f2b58bf8d16b1ee3079f68cdc10b66e9dee7918/test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_test.go#L102-L112 creates a `Shoot` but doesn't seem to delete it?

**Comment by shafeeqes** [comment]
Running this against an existing Gardener cluster gives this error:
```
 Unexpected error:
      <*errors.errorString | 0xc000618da0>: {
          s: "no API server authentication is configured yet.  The API server defaults one when Start is called, did you mean to use that?",
      }
      no API server authentication is configured yet.  The API server defaults one when Start is called, did you mean to use that?
  occurred
  In [BeforeEach] at: /Users/i545724/go/src/github.com/gardener/gardener/test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_test.go:125
```
which comes from here:
https://github.com/gardener/gardener/blob/bf9dcf5704d2bb53273f1807c6e2e73dd17a9fd1/vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/plane.go#L234-L237

Will check how to add this to the kube-apiserver.

**Comment by rfranzke** [comment]
> Running this against an existing Gardener cluster gives this error:
> 
> ```
>  Unexpected error:
>       <*errors.errorString | 0xc000618da0>: {
>           s: "no API server authentication is configured yet.  The API server defaults one when Start is called, did you mean to use that?",
>       }
>       no API server authentication is configured yet.  The API server defaults one when Start is called, did you mean to use that?
>   occurred
>   In [BeforeEach] at: /Users/i545724/go/src/github.com/gardener/gardener/test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_test.go:125
> ```
> 
> which comes from here:
> 
> https://github.com/gardener/gardener/blob/bf9dcf5704d2bb53273f1807c6e2e73dd17a9fd1/vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/plane.go#L234-L237
> 
> Will check how to add this to the kube-apiserver.

https://github.com/gardener/gardener/blob/3ca159190b08fd667535e01c460b5372209234a2/test/integration/controllermanager/project/project/project_test.go#L461-L471 might be of help :)

**Comment by shafeeqes** [comment]
> > Running this against an existing Gardener cluster gives this error:
> > ```
> >  Unexpected error:
> >       <*errors.errorString | 0xc000618da0>: {
> >           s: "no API server authentication is configured yet.  The API server defaults one when Start is called, did you mean to use that?",
> >       }
> >       no API server authentication is configured yet.  The API server defaults one when Start is called, did you mean to use that?
> >   occurred
> >   In [BeforeEach] at: /Users/i545724/go/src/github.com/gardener/gardener/test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_test.go:125
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which comes from here:
> > https://github.com/gardener/gardener/blob/bf9dcf5704d2bb53273f1807c6e2e73dd17a9fd1/vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/plane.go#L234-L237
> > 
> > Will check how to add this to the kube-apiserver.
> 
> https://github.com/gardener/gardener/blob/3ca159190b08fd667535e01c460b5372209234a2/test/integration/controllermanager/project/project/project_test.go#L461-L471
> 
> might be of help :)

Thanks a lot! This worked.
However, I was unable to reproduce the flake.
```
9m45s: 1215 runs so far, 0 failures
9m50s: 1220 runs so far, 0 failures
9m55s: 1229 runs so far, 0 failures
```

**Comment by shafeeqes** [comment]
Meanwhile another occurence: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration/1568366665064779776

**Comment by shafeeqes** [comment]
I tried using the local-garden setup as well.
No luck there too.
```
20m5s: 4094 runs so far, 0 failures
20m10s: 4106 runs so far, 0 failures
```
In kind,
it fails with a different error:
```
  Timed out after 10.005s.
  Expected
      <*errors.StatusError | 0xc000000c80>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "Post \"https://127.0.0.1:65006/apis/authorization.k8s.io/v1/subjectaccessreviews?timeout=10s\": stream error: stream ID 2881; INTERNAL_ERROR; received from peer",
              Reason: "",
              Details: nil,
              Code: 500,
          },
      }
  to be Forbidden error
```

**Comment by rfranzke** [comment]
@shafeeqes It happened again: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6733/pull-gardener-integration/1578270033082060800

**Comment by shafeeqes** [comment]
I tried again, but had no success in reproducing this,
```
10m25s: 2378 runs so far, 0 failures
10m30s: 2391 runs so far, 0 failures
10m35s: 2406 runs so far, 0 failures
```
We wait for deletion of shoots in all tests which creates shoots, 
eg,
https://github.com/gardener/gardener/blob/d1d365fdbcdab52680aca6d82626e15b747fe752/test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_test.go#L139-L141
Yet, this flakes.
What I can think of is, we can disable `SeedValidator` admission plugin in the tests as well, since it is not related to the test.
WDYT?

**Comment by rfranzke** [comment]
> What I can think of is, we can disable SeedValidator admission plugin in the tests as well, since it is not related to the test.
WDYT?

Sounds reasonable

**Comment by shafeeqes** [comment]
Okay, then I will make the change.
