### ISSUE TITLE
`make gardener-down` fails at deletion of `garden` `Project`

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#6656]
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What happened**:
Calling `make gardener-down` fails with the following error:
```
$ make gardener-down 
hack/tools/bin/kubectl delete seed local --ignore-not-found --wait --timeout 5m
seed.core.gardener.cloud "local" deleted
hack/tools/bin/kubectl delete seed local2 --ignore-not-found --wait --timeout 5m
hack/tools/bin/skaffold delete -m provider-local,gardenlet
Cleaning up...
release "gardener-extension-provider-local-registration" uninstalled
release "gardener-gardenlet" uninstalled
hack/tools/bin/kubectl delete validatingwebhookconfiguration/validate-namespace-deletion --ignore-not-found
validatingwebhookconfiguration.admissionregistration.k8s.io "validate-namespace-deletion" deleted
hack/tools/bin/kubectl annotate project local confirmation.gardener.cloud/deletion=true
project.core.gardener.cloud/local annotated
hack/tools/bin/skaffold delete -m local-env
Cleaning up...
 - secret "bootstrap-token-07401c" deleted
 - namespace "garden-local" deleted
 - secret "backup-local" deleted
 - secret "local" deleted
 - cloudprofile.core.gardener.cloud "local" deleted
 - controllerdeployment.core.gardener.cloud "networking-calico" deleted
 - controllerregistration.core.gardener.cloud "networking-calico" deleted
 - project.core.gardener.cloud "local" deleted
 - secretbinding.core.gardener.cloud "local" deleted
 - secretbinding.core.gardener.cloud "local" deleted
 - secret "seed-local" deleted
 - Error from server (Forbidden): error when deleting "STDIN": projects.core.gardener.cloud "garden" is forbidden: must have a "confirmation.gardener.cloud/deletion" annotation to delete
kubectl delete: exit status 1
make: *** [gardener-down] Error 1
```

**What you expected to happen**:
`make gardener-down to complete successfully`

**How to reproduce it (as minimally and precisely as possible)**:
1. `make kind-up`
2. `make gardener-up`
3. `make gardener-down`

**Anything else we need to know?**:
The `garden` `Project` was added to the `kustomize` configuration here: https://github.com/gardener/gardener/blob/master/example/provider-local/garden/base/project.yaml with #6293

Perhaps we could add `make gardener-down` to our e2e tests, maybe as a last step in the [ci-e2e-kind.sh](https://github.com/gardener/gardener/blob/master/hack/ci-e2e-kind.sh) script to prevent future errors.

**Environment**:

- Gardener version: 1da39002ccd90e8b3dc08763dcf41708e48d907f
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: 
- Others:

**Comment by rfranzke** [comment]
Can we just add the confirmation annotation to https://github.com/gardener/gardener/blob/master/example/provider-local/garden/base/project.yaml?

> Perhaps we could add make gardener-down to our e2e tests, maybe as a last step in the [ci-e2e-kind.sh](https://github.com/gardener/gardener/blob/master/hack/ci-e2e-kind.sh) script to prevent future errors.

Yes, sounds good, do you want to open a PR?

**Comment by plkokanov** [comment]
> Yes, sounds good, do you want to open a PR? 

Yep sure I'll do it on Monday morning, though.

/assign @plkokanov
