### ISSUE TITLE
[Flaky Test] Shoot Maintenance controller tests

### ISSUE THREAD

**Issue by shafeeqes** [gardener/gardener#6659]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
  Worker Pool Kubernetes version maintenance tests
  /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/shoot/maintenance/maintenance_test.go:417
    [It] Kubernetes version should be updated: force update patch version
    /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/shoot/maintenance/maintenance_test.go:442
...
 Expected
      <string>: 0.0.1
  to equal
      <string>: 0.0.5
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/shoot/maintenance/maintenance_test.go:454
```
and 
```
  Machine image maintenance tests
  /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/shoot/maintenance/maintenance_test.go:322
    [It] Shoot machine image must be updated in maintenance time: AutoUpdate.MachineImageVersion == false && expirationDate applies
    /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/shoot/maintenance/maintenance_test.go:348
...
  Expected success, but got an error:
      <*errors.errorString | 0xc0014f1810>: {
          s: "Assertion in callback at /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/shoot/maintenance/maintenance_test.go:356 failed:\nExpected\n    <v1beta1.ShootMachineImage>: {\n        Name: \"foo-image\",\n        ProviderConfig: nil,\n        Version: \"0.0.1-beta\",\n    }\nto equal\n    <v1beta1.ShootMachineImage>: {Name: \"foo-image\", ProviderConfig: nil, Version: \"1.1.1\"}",
      }
      Assertion in callback at /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/shoot/maintenance/maintenance_test.go:356 failed:
      Expected
          <v1beta1.ShootMachineImage>: {
              Name: "foo-image",
              ProviderConfig: nil,
              Version: "0.0.1-beta",
          }
      to equal
          <v1beta1.ShootMachineImage>: {Name: "foo-image", ProviderConfig: nil, Version: "1.1.1"}
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/shoot/maintenance/maintenance_test.go:358
```
**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6638/pull-gardener-integration/1568990366986670080

**Reason for failure**:
Mentioned above.

**Anything else we need to know**:

**Comment by rfranzke** [comment]
Happened again: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6645/pull-gardener-integration/1569224037224157184

**Comment by ialidzhikov** [comment]
I tried to reproduce the failures locally against my remote garden setup but had no success with the try:
```
$ stress -p 32 ./test/integration/controllermanager/shoot/maintenance/maintenance.test -ginkgo.progress
...
22m50s: 510 runs so far, 0 failures
22m55s: 511 runs so far, 0 failures
23m0s: 512 runs so far, 0 failures
23m5s: 515 runs so far, 0 failures
```

**Comment by ialidzhikov** [comment]
I was able to reproduce the failures when I ran the stress test against the local garden setup.

---

I think the reason for the failures is that for example the test is updating the CloudProfile (sets a version to expire) but the CloudProfile fetched by the maintenance controller is a stale one that does not contain the most recent update.
I think the reason for such failures to happen now is https://github.com/gardener/gardener/pull/6620. 
Before https://github.com/gardener/gardener/pull/6620 the controller was using `testClient` from the test which is a direct client (that reads *and* writes directly from/to the server) created by `client.New(...)`.

https://github.com/gardener/gardener/blob/3999f826f18883b52a1bc0bf58c86edb4ef1c0af/test/integration/controllermanager/shoot/maintenance/maintenance_test.go#L513

https://github.com/gardener/gardener/blob/3999f826f18883b52a1bc0bf58c86edb4ef1c0af/test/integration/controllermanager/shoot/maintenance/maintenance_suite_test.go#L81-L82

After #6620 the controller is added with manager's Client which is not a direct one.

https://github.com/gardener/gardener/blob/4d84c5fdf389a6b54f64f8eabb112b33c25b5b1b/pkg/controllermanager/controller/shoot/maintenance/add.go#L34-L36

**Comment by ialidzhikov** [comment]
One approach to deflake would be to run the controller with direct client as before:

```diff
--- a/test/integration/controllermanager/shoot/maintenance/maintenance_suite_test.go
+++ b/test/integration/controllermanager/shoot/maintenance/maintenance_suite_test.go
@@ -110,6 +110,7 @@ var _ = BeforeSuite(func() {

        By("registering controller")
        Expect((&maintenance.Reconciler{
+               Client: testClient,
                Config: config.ShootMaintenanceControllerConfiguration{
                        ConcurrentSyncs: pointer.Int(5),
                },
```

This approach is not consistent with the other controller-manager integration tests that don't need to run with a direct client (at least I don't know of similar flakes reported for them).

Alternatively, everywhere we patch the CloudProfile we could add "waits" the corresponding CloudProfile update to be observed by the `mgrClient`. Example

https://github.com/gardener/gardener/blob/3ca159190b08fd667535e01c460b5372209234a2/test/integration/controllermanager/project/project/project_test.go#L249-L253

@rfranzke @timebertt @ary1992  do you have a suggestion? Maybe the 2nd approach is what we did recently to deflake some tests. One could say that we put "waits" to make the manager's cache happy but in ideal world the manager/reconciler is supposed to be a "black box" that does not need such "help" from outside.

**Comment by rfranzke** [comment]
In reality, the manager has a cached client, so I think we should keep following this approach and not inject the `testClient`. 

> One could say that we put "waits" to make the manager's cache happy but in ideal world the manager/reconciler is supposed to be a "black box" that does not need such "help" from outside.

I understand what you mean, but I'm not sure whether this is an argument against it. In the tests, we are having quite low sync periods and fast, frequent reconciliations, so we have to make sure that we do not make assertions too early. Can you try this approach for now and see whether this helps deflaking it?

**Comment by ialidzhikov** [comment]
Sure, I will give a try tomorrow.
