### ISSUE TITLE
Containerd monitoring script - remove/fix?  Bad side effects + no clear advantage

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#6666]
**How to categorize this issue?**

/area os
/area robustness
/kind bug

**What happened**:

The [containerd monitoring script](https://github.com/gardener/gardener/blob/6445844bf0dbf166bf79b4b416e202617a596a31/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/templates/scripts/health-monitor.tpl.sh) sends a SIGTERM to a restarting containerd daemon process triggering a potential containerd bug leading to loss of shim process and user processes. The containerd daemon can only be recovered after manual intervention.
This was reported by a Stakeholder.

**Problem**: the command `timeout 60 ctr c list` returns as soon as `ctr` returns with exit code 1. This depends on a ctr internal timeout which is much smaller than 60 seconds.

This in turn can lead to the monitoring script failing on a containerd restart (e.g when a stakeholder re-configures the containerd config) and sending a SIGTERM to containerd. Containerd's signal handler catches the signal. 

**Hypothesis**: Containerd is terminated due to handling a SIGTERM during startup (systemd status `activating`) reconnection to shim processes. 

It is unclear why the shim processes are terminated (that should never happen). I will link the containerd issue here once the Stakeholder has created it.

EDIT: problem was identified and is described in a comment below.

**What you expected to happen**:

Containerd monitoring script retries `ctr c list` for 60s until it sends a signal to containerd. This avoids sending SIGTERMS too early.
- also relevant for CPU/memory contention scenarios when containerd might be slow to react to RPC calls. We do not want to run into a potential restart loop.

Additionally, we should not send SIGTERMS during startup i.e before the systemd unit `active` status.

I could also see the monitoring script getting removed 
- the containerd systemd service is configured with auto-restart in case the containerd process terminates
- no clear evidence that a process restart brings any benefit when it is unable to respond to RPC calls in time. 
- I would rather argue the containerd monitor is actively harmful
  - restarting a process under resource contention causes all it's memory pages to be flushed. Demand-paging large amounts of pages during memory contention can be a performance problem. Having to fill the page cache again can be a performance problem (containerd page cache size can be in the tens of Gi)
  - possible exposure to bugs - such as we see with this issue.

**How to reproduce it (as minimally and precisely as possible)**:

- run the monitoring service i.e command `watch timeout 60 ctr list`
- restart containerd
- ctr list will fail once the containerd socket is gone, returns exit code 1.
```
ctr: failed to dial "/run/containerd/containerd.sock": context deadline exceeded
```
- the containerd monitor script sends a SIGTERM to containerd
- containerd restarts and hangs during reconnection to the (gone) containerd shims

Note that containerd-shim processes have been terminated + the respective user processes are either gone (probably SIGPIPE) or re-parented to init. 
```
65535       4579  0.0  0.0    996     4 ?        Ss   06:04   0:00 /pause
65535       4698  0.0  0.0    996     4 ?        Ss   06:04   0:00 /pause
65535       4714  0.0  0.0    996     4 ?        Ss   06:04   0:00 /pause
65535       4726  0.0  0.0    996     4 ?        Ss   06:04   0:00 /pause
65535       4728  0.0  0.0    996     4 ?        Ss   06:04   0:00 /pause
nobody      4753  0.0  0.0    996     4 ?        Ss   06:04   0:00 /pause
root        4859  0.0  0.2 1178356 32068 ?       Ssl  06:04   0:04 /gce-pd-csi-driver --endpoint=unix:/csi/csi.sock --run-controller-service=false --logtostderr --v=5
root        5035  0.0  0.1 708012 18408 ?        Ssl  06:04   0:01 /apiserver-proxy-sidecar --ip-address=10.243.14.218 --setup-iptables=false --interface=lo
root        5073  0.5  0.5 809256 77400 ?        Ssl  06:04   2:11 cilium-operator --config-dir=/tmp/cilium/config-map --debug=false
nobody      5111  0.0  0.1 717892 26676 ?        Ssl  06:04   0:13 /bin/node_exporter --web.listen-address=:16909 --path.procfs=/host/proc --path.sysfs=/host/sys --path.rootfs=/host --log.level=error --collector.disable-defaults --collector.conn
root
```

To be more thoroughly tested: can this inconsistent state of containerd only be reproduced when the containerd-monitor sends a SIGTERM during startup? In essence, are manual restarts with inactive monitoring script fine?

**Anything else we need to know?**:

I will link the containerd bug issue once it got created.

**Environment**:

- GL 576.11.0 running containerd 1.5.11

**Comment by syurevich** [comment]
[containerd bug issue](https://github.com/containerd/containerd/issues/7394).

**Comment by danielfoehrKn** [comment]
Stakeholder reported

> we finally found the culprit. It’s the pkill command in the containerd-monitor script [1]:
  pkill containerd
 
> It sends SIGTERM to all processes whose program name contains the string “containerd”, i.e. containerd itself and containerd-shim-runc-v2 in our case.
 
> But there’s also a problem with containerd that we will report. When a shim dies while containerd is running, containerd runs a clean-up procedure that removes the respective containers from its database. But when a shim dies when containerd is not running, it retries forever reconnecting to the shim when it starts up instead of giving up and performing the clean-up procedure.

Hence, the script either needs to be removed or updated to exactly match only the containerd daemon process name (e.g via `pkill -x`)
