### ISSUE TITLE
[Flaky Test] ExtensionsCheck Integration Test Suite

### ISSUE THREAD

**Issue by acumino** [gardener/gardener#6679]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
• [FAILED] [5.302 seconds]
Seed ExtensionsCheck controller tests
/home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go:29
  when one ControllerInstallation becomes not valid
  /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go:152
    [It] should set ExtensionsReady to Progressing and eventually to False when condition threshold expires
    /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go:125

```

**CI link**: 
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6585/pull-gardener-integration/1570059944915374080

**Reason for failure**:

**Anything else we need to know**:

**Comment by rfranzke** [comment]
I believe that #6585 which caused this flake was not rebased on `master` and particularly did not include #6636. Here, we made sure that these suites should not flake anymore. Let's wait a bit more, but I hope that we can close this issue without the necessity to do anything.

**Comment by ialidzhikov** [comment]
From @oliver-goetz:
> For PR tests prow is checking out the current master, applies the PR changes and performs the tests ([see first lines of a git checkout log](https://storage.googleapis.com/gardener-prow/pr-logs/pull/gardener_gardener/6371/pull-gardener-e2e-kind/1552204706921582592/clone-log.txt)).
Thus, when the changes are merged the next PR test run should use the fixes.

My understanding is that prow does a rebase before running the tests.

**Comment by oliver-goetz** [comment]
You can see in [clone-log.txt](https://storage.googleapis.com/gardener-prow/pr-logs/pull/gardener_gardener/6585/pull-gardener-integration/1570059944915374080/clone-log.txt) of the test @acumino mentioned, that prow used commit `3749db49b33e32e2d73c63213f0ea8c94dfba18e` and applied the PR changes on top of it.
At this point #6636 was already included.

**Comment by rfranzke** [comment]
Well, that's unfortunate then :) 

Here is another similar failure from the `BackupBucketsCheck` test suite which is very similar to the `ExtensionsCheck` suite:
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6667/pull-gardener-integration/1570323685837901824

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6681/pull-gardener-integration/1570666193080029184

**Comment by rfranzke** [comment]
@plkokanov There is a new flake: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6705/pull-gardener-integration/1572124710328602624

/reopen
