### ISSUE TITLE
Add a new `WithClock(...)` function to the `ConditionBuilder` interface and deprecate `WithNowFunc(...)`

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#6689]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement

**What would you like to be added**:
Add new function that can be used to pass a `clock.Clock` interface to the [`ConditionBuilder`](https://github.com/gardener/gardener/blob/176bf4aa05a4087f69d13fbd9ac9fc105ef4a4ff/pkg/apis/core/v1beta1/helper/condition_builder.go#L26-L35) interface. 
Enhance the current `ConditionBuilder` implementations (e.g. the `defaultConditionBuilder`'s [`Build()`](https://github.com/gardener/gardener/blob/176bf4aa05a4087f69d13fbd9ac9fc105ef4a4ff/pkg/apis/core/v1beta1/helper/condition_builder.go#L105-L146) function) so that they use a `clock.Clock` interface internally when building conditions and assigning the `condition.lastTransitionTime` and `condition.lastUpdateTime`.
Deprecate the [`WithNowFunc(...)`](https://github.com/gardener/gardener/blob/176bf4aa05a4087f69d13fbd9ac9fc105ef4a4ff/pkg/apis/core/v1beta1/helper/condition_builder.go#L33) from the `ConditionBuilder` interface.

**Why is this needed**:
We have started using the `clock.Clock` interface in our reconcilers so it makes sense to reuse it directly when maintaining conditions of resources with the `ConditionBuilder` interface. This should also help when writing tests and make it easier to correctly configure/test expected timestamps. The [`UpdatedConditionBuilder(...)`](https://github.com/gardener/gardener/blob/176bf4aa05a4087f69d13fbd9ac9fc105ef4a4ff/pkg/apis/core/v1beta1/helper/helper.go#L74-L88) function should also be modified to accept a `clock.Clock` interface and pass it onto the `ConditionBuilder`.
Currently, the following code has to be added to make sure that the conditions are created with expected timestamps, in tests:
https://github.com/gardener/gardener/blob/176bf4aa05a4087f69d13fbd9ac9fc105ef4a4ff/test/integration/controllermanager/seed/extensionscheck/extensionscheck_suite_test.go#L121-L126

Additionally, the `WithNowFunc(...)` is not properly documented. According to the go comment it should only be used in tests, but it is used in other places as well.

**Comment by oliver-goetz** [comment]
@plkokanov: ~~Could we delete `WithNowFunction(..)` directly instead of deprecating it?~~
Otherwise, it would not be clear which function was used and there could be some weird combinations like `conditionBuilder.WithClock(realClock).WithNowFunc(fakeNow)`.

I'll simply build it that the last change matters 😄
