### ISSUE TITLE
Changing Log Level of vpn-shoot, calico-node, node-exporter

### ISSUE THREAD

**Issue by zoyapronyakova** [gardener/gardener#671]
Dear gardener colleagues, 

I am part of SAP Web IDE team and i am working on logs analysis in our platform.
Currently,  vpn-shoot, calico-node, node-exporter log levels are set to **info**, which basically floods our logs with irrelevant information.
I understood that those components are part of gardener deployment.
How can i set this components log level to error automatically?  (I mean, **not** by setting it manually in Config Map for each cluster)

Thank you,
Zoya
DI Cloud Exp DevX | SAP Labs Israel

**Comment by marwinski** [comment]
We can certainly reduce the log level for calico, we don't really need info here (@DockToFuture can you please take over). As for vpn-shoot this should normally not create a lot of messages - the number of messages is merely an indication of a problem. So far we mostly saw it on AWS (which we believe is due to the AWS load balancers) but I just saw that also on Azure. We do need to investigate. Is it ok if we leave it at that level for now?

**Comment by zoyapronyakova** [comment]
@marwinski  thanks for your fast response. Good news!
Could you please provide timelines for both
- switching calico and node-exporter log levels
- vpn-shoot logs investigation
By timelines, I mean when the fix is provided and when it is available in Canary landscape?

In addition, attaching here some of vpn-shoot info logs we are getting, maybe it could help:
-- Tue Jan 22 10:50:37 2019 vpn-seed/100.96.3.1:60935 peer info: IV_PLAT=linux
-- Tue Jan 22 10:50:37 2019 vpn-seed/100.96.3.1:60935 peer info: IV_COMP_STUB=1
-- Tue Jan 22 10:24:00 2019 vpn-seed/100.96.5.1:41264 peer info: IV_PROTO=2
-- Tue Jan 22 10:50:37 2019 vpn-seed/100.96.3.1:60935 peer info: IV_VER=2.4.4
and so on...

Thanks

**Comment by marwinski** [comment]
Excessive logs in the vpn-shoot pod are caused by the blackbox exporter opening a connection to the vpn endpoint every 5 seconds. This is not necessary as there is already a test for the VPN in the seed cluster. @dkistner can you please check and disable that test. Thanks.

**Comment by dkistner** [comment]
The blackbox exporter (running co-deployed with Prometheus in the Seed) is executing the `vpn-connection` check every **15** seconds. 
 https://github.com/gardener/gardener/blob/master/charts/seed-monitoring/charts/prometheus/templates/config.yaml#L442 
But on top of this Prometheus will use the vpn connection to scrape several components (node-exporter, kube-proxy etc...) running on the Shoot nodes. Maybe we have therefore an average of 5 seconds for opening connections?

**Comment by zoyapronyakova** [comment]
@marwinski do you know when we can expect log level change of the the calico and other components?
I need to provide estimations when to eliminate log flooding.

**Comment by zoyapronyakova** [comment]
Thanks a lot for your help! Number of calico-node INFO messages has bee significantly reduced 
31.01 - 1,031,208
03.02 - 0!

**Comment by rfranzke** [comment]
Can this one be closed?

**Comment by zoyapronyakova** [comment]
yes :)
