### ISSUE TITLE
Webhook remediator feature too aggressive

### ISSUE THREAD

**Issue by dimakow** [gardener/gardener#6726]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
With https://github.com/gardener/gardener/pull/6090 Gardener has introduced a webhook remediator feature which should trigger once users are using Webhook which are too costly. Unfortunately, the current implementation will also remediate Webhook definitions which are simply lacking a "timeoutSeconds" property. 

```
func mustRemediateTimeoutSeconds(timeoutSeconds *int32) bool {
	return timeoutSeconds == nil || *timeoutSeconds > WebhookMaximumTimeoutSecondsNotProblematic
}
```
https://github.com/gardener/gardener/pull/6090/files#diff-baa858cea1e1a35989cd4be79657eefdceb915139fb4380a2fbc38bfc622ad06

Usually, such Webhook definitions would then get the default timeoutSeconds of 10s by API-Server which would be fine. Now using Webhook definition will mark shoots as "problematic" even if they are actually not problematic.

**What you expected to happen**:
No warning/interaction by Gardener components if no harming behavior is followed.

**How to reproduce it (as minimally and precisely as possible)**:
Use a Webhook without timeoutSeconds property

**Anything else we need to know?**:

**Environment**: all

- Gardener version: landscape-canary-garden 0.584.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: all
- Others:

**Comment by hua82556281** [comment]
I also concern this issue. We have some webhook configurations in our cluster. As I observed most of them didn't specify timeoutSeconds and use default value 10s. But they are evaluated as problematic.  Is there any simple ways to remove the Warning currently . Or I only can remove the annotation gardener.cloud/warning in them one by one.

**Comment by rfranzke** [comment]
> I also concern this issue. We have some webhook configurations in our cluster. As I observed most of them didn't specify timeoutSeconds and use default value 10s. But they are evaluated as problematic. Is there any simple ways to remove the Warning currently . Or I only can remove the annotation gardener.cloud/warning in them one by one.

The easiest option is to explicitly set the `timeoutSeconds`. Alternatively, you can label the webhook with `remediation.webhook.shoot.gardener.cloud/exclude=true`, however please remember to remove it again once this issue is fixed.
