### ISSUE TITLE
[Flaky Test] `make gardener-down` is flaky

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#6769]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:

`make gardener-down` in `*-gardener-e2e-kind` is flaky. Sometimes, `helm uninstall` fails with:

```
hack/tools/bin/skaffold delete -m etcd,controlplane
Cleaning up...
 - namespace "garden" deleted
 - secret "etcd-tls" deleted
 - service "etcd" deleted
 - service "etcd-client" deleted
 - statefulset.apps "etcd" deleted
Error: uninstallation completed with 1 error(s): uninstall: Failed to purge the release: release: not found
```

**CI link**:

https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6754/pull-gardener-e2e-kind/1577253184139694080#1:build-log.txt%3A1569-1604

**Reason for failure**:

Maybe helm is racing with the namespace deletion.

**Anything else we need to know**:

Visible since https://github.com/gardener/gardener/pull/6664

**Comment by oliver-goetz** [comment]
/close
Today, I checked like 40 different e2e tests and I was not able to find any other occurrence of this issue.
Please reopen, if it happens again.
