### ISSUE TITLE
Unready calico-node Pod is not reflected in the Shoot status

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#6775]
**How to categorize this issue?**

/area control-plane quality
/kind bug

**What happened**:
For a Shoot calico-node Pod is unhealthy since longtime:
```
$ k -n kube-system get po -l k8s-app=calico-node
NAME                READY   STATUS    RESTARTS   AGE
calico-node-rgd9p   0/1     Running   0          6d10h
calico-node-w9zmf   1/1     Running   0          7d

$ k -n kube-system describe po calico-node-rgd9p

Events:
  Type     Reason     Age                      From     Message
  ----     ------     ----                     ----     -------
  Warning  Unhealthy  77s (x63115 over 6d10h)  kubelet  (combined from similar events): Readiness probe failed: 2022-10-05 08:59:22.390 [INFO][1946539] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 10.180.13.235

$ k -n kube-system get ds calico-node
NAME          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
calico-node   2         2         1       1            1           kubernetes.io/os=linux   7d
```

```
$ k -n kube-system get ds calico-node -o yaml

status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 1
  numberUnavailable: 1
  observedGeneration: 2
  updatedNumberScheduled: 1
```

Looks lie GRM threats this that the DaemonSet is Progressing:
```
$ k -n shoot--foo--bar get mr extension-networking-calico-config
NAME                                 CLASS   APPLIED   HEALTHY   PROGRESSING   AGE
extension-networking-calico-config           True      True      True          7d
```

And this issue is not reflected in any way in the Shoot status.

**What you expected to happen**:
The issue to be reflected in the Shoot status.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.56.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
I am able to reproduce the issue. In short, with https://github.com/gardener/gardener/pull/5628 during a rolling update of a DaemonSet we tolerate `maxUnavailable` replicas to be unavailable to prevent failing the health check always during a rolling update. The issue is that rolling update of DaemonSet can get stuck (ref https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#daemonset-rolling-update-is-stuck) - it could happen for example if the new Pod is unhealthy. In such case the rollout of the DaemonSet doesn't progress. `resource-manager` continues to tolerate  `maxUnavailable` unavailable replicas - that's why the unhealthy replica is not reflected in the ManagedResource status.

I am not sure how to accomplish the following requirements at the same time:
1) tolerate `maxUnavailable` replicas to be unavailable during a rolling update
2) and fail the health check when the DaemonSet rollout is stuck due to unhealthy replica

Any suggestion?

**Comment by rfranzke** [comment]
I don't think it's possible to achieve both at the same time. A way out could be to incorporate the `Progressing` condition of `ManagedResource`s into the health status conditions of the `Shoot`. When e.g. a `DaemonSet` rollout is `Progressing` for too long then the `Shoot` condition will eventually transition to `False`, hence the error would become "visible". OTOH, this might again lead to some false negative health checks that #5628 tried to fix.

**Comment by ialidzhikov** [comment]
> I don't think it's possible to achieve both at the same time.

Agree.

There are some open questions/challenges. If we start reflecting "MR not progressing" to the Shoot status, then the Shoot condition will be false for more  

> A way out could be to incorporate the `Progressing` condition of `ManagedResource`s into the health status conditions of the `Shoot`. When e.g. a `DaemonSet` rollout is `Progressing` for too long then the `Shoot` condition will eventually transition to `False`, hence the error would become "visible". OTOH, this might again lead to some false negative health checks that #5628 tried to fix.

As you said, if we start reflecting "MR not progressing" to the Shoot conditions, then a Shoot condition will be "false" appr. right away for long-running (> 30min) calico-node rolling updates.

If you mean introducing a "toleration" somewhere in the shoot-care-controller for `DaemonSets` that are `Progressing` for more than 1h for example:
- we have to read the ManagedResource's Progressing condition's message to understand if it is a DaemonSet that is causing the Progressing condition to be true
- I am not sure if theoretically Deployments/StatefulSets with relatively high replica count can get in such Progressing=true,Healthy=true state.

**Comment by rfranzke** [comment]
Yeah, such toleration approach sounds promising from UX PoV, i.e. when there are `ManagedResource`s with are `Progressing=true` and `Healthy=true` then let's keep the shoot condition at status `Progressing` the entire time and don't transition it to `False` after the grace period. Only when something is indeed unhealthy for too long then we should transition it to `False`.

However, I'm not sure how easy it is to implement this.

**Comment by rfranzke** [comment]
/unassign @ialidzhikov 
for now in favor of some other tasks

**Comment by acumino** [comment]
MangedResources created by extensions are not considered in PR https://github.com/gardener/gardener/pull/7241.
/reopen

**Comment by acumino** [comment]
There are two ways to fix this issue for MR created by extensions:
- Simple Way:  A label can be added to MR created by extensions something like origin:gardener-extensions and this label can be used in label selector [here](https://github.com/gardener/gardener/blob/a38354a6c3a0ae734d243553d14bed26c2fcbd0d/pkg/operation/care/health.go#L402).
- More technical/correct way: Enhance [this](https://github.com/gardener/gardener/blob/a38354a6c3a0ae734d243553d14bed26c2fcbd0d/pkg/utils/kubernetes/health/managedresource.go#L27) function so it also checks progressing condition of MR. Currently progressing condition of MR is not considered in extension health check if MR is healthy.

Any thoughts, which one is better option?

**Comment by rfranzke** [comment]
From dev perspective/complexity PoV, I think it makes sense to make `gardenlet` consider all `ManagedResource`s in the shoot namespace with `.spec.class!=seed` to be shoot system components. Then it could simply check all of them and we don't need to "replicate" its behaviour to all extensions.

As a consequence, the extensions health check controller does no longer need to check them in addition, hence we could remove all such statements from all extensions: https://github.com/gardener/gardener/blob/2f34cb1422985253aa47eb761bb759d6ae4823e3/pkg/provider-local/controller/healthcheck/add.go#L83-L86

**Comment by acumino** [comment]
> From dev perspective/complexity PoV, I think it makes sense to make `gardenlet` consider all `ManagedResource`s in the shoot namespace with `.spec.class!=seed` to be shoot system components. Then it could simply check all of them and we don't need to "replicate" its behaviour to all extensions.
> 
> As a consequence, the extensions health check controller does no longer need to check them in addition, hence we could remove all such statements from all extensions:
> 
> https://github.com/gardener/gardener/blob/2f34cb1422985253aa47eb761bb759d6ae4823e3/pkg/provider-local/controller/healthcheck/add.go#L83-L86

Sounds Good. Should I go ahead with this approach?

**Comment by rfranzke** [comment]
Let's wait a bit more to give others a chance to provide feedback as well (at least @oliver-goetz mentioned that he wanted to look into this issue).

**Comment by oliver-goetz** [comment]
In general this would help to decrease the effort on the extension side adding their managed resources to the health check. 
However, I have two questions:

Why considering ManagedResources with `.spec.class!=seed` only? 
There are extensions which have a seed and a shoot component like `extension-shoot-cert-service-seed` and `extension-shoot-cert-service-shoot` or `extension-shoot-dns-service-seed` and `extension-shoot-dns-service-shoot`. Does it make sense to include only the shoot part of these extensions to the system components health check? 

Are these latest proposed changes related to this issue?
The calico extension already [defines a health check](https://github.com/gardener/gardener-extension-networking-calico/blob/1b38213dee16cc51ee06891ef5b085ecaa102593/pkg/healthcheck/add.go#L52-L56) for its managed resource. Thus, isn't it solved already by PR https://github.com/gardener/gardener/pull/7241?

**Comment by rfranzke** [comment]
> Why considering ManagedResources with `.spec.class!=seed` only? [...] Does it make sense to include only the shoot part of these extensions to the system components health check?

Yes, it does. `ManagedResource`s with `class=seed` only contain resources deployed to the seed cluster - this is not considered a "shoot system component". We could consider those things for the `ControlPlaneHealthy` condition, but this is a separate discussion (potentially in the light of the `Consider using ManagedResources for deploying shoot control plane components instead of directly applying the resources with the client` task tracked in https://github.com/gardener/gardener/issues/6016).

> Are these latest proposed changes related to this issue? The calico extension already [defines a health check](https://github.com/gardener/gardener-extension-networking-calico/blob/1b38213dee16cc51ee06891ef5b085ecaa102593/pkg/healthcheck/add.go#L52-L56) for its managed resource. Thus, isn't it solved already by PR #7241?

Not sure whether I get this, can you explain again?

**Comment by oliver-goetz** [comment]
> > Why considering ManagedResources with `.spec.class!=seed` only? [...] Does it make sense to include only the shoot part of these extensions to the system components health check?
> 
> Yes, it does. `ManagedResource`s with `class=seed` only contain resources deployed to the seed cluster - this is not considered a "shoot system component". We could consider those things for the `ControlPlaneHealthy` condition, but this is a separate discussion (potentially in the light of the `Consider using ManagedResources for deploying shoot control plane components instead of directly applying the resources with the client` task tracked in #6016).
> 
Good to know, thanks 👍 

> > Are these latest proposed changes related to this issue? The calico extension already [defines a health check](https://github.com/gardener/gardener-extension-networking-calico/blob/1b38213dee16cc51ee06891ef5b085ecaa102593/pkg/healthcheck/add.go#L52-L56) for its managed resource. Thus, isn't it solved already by PR #7241?
> 
> Not sure whether I get this, can you explain again?

I thought that the `HealthChecker` which was changed in #7241 was used in extensions too, so that it would be a matter of revendoring the extension to the latest Gardener release to solve this issue. But I now think, that this is not the case 😅

**Comment by ialidzhikov** [comment]
Wrt to the idea shared in https://github.com/gardener/gardener/issues/6775#issuecomment-1408406519:
- I feel that 1. (Simple Way) approach is actually the harder way. You will have to loop over each extension add the origin=gardener-extensions label; you will have to adapt the central check in gardener to consider this label; finally you will have to remove the existing health checks for managed resources in the extensions. While the second approach would need only adaptation in the health check func that is used by the extensions. And this change has to be vendored in the extensions. The challenging part there should be to make the progressing threshold configurable but it should be possible to do it via flag.
- I feel that 2. approach is more consistent. If we pick 1. approach, then it would be strange that gardenlet takes care to health check all MR in the Shoot control plane (incl the ones from the extensions) but leaves to the extension to health check the stuffs that the extensions deploy without a MR (it still has to health check its Deployments that are deployed with chartApplier).
- On the other side, doing the MR healthchecks via gardenlet would drop some code duplication - currently there are different funcs for healthchecking ManagedResources - ones used by gardnelet, others used by the extensions.

No strong opinion from my side, but maybe the 2. approach would be easier to go?

**Comment by rfranzke** [comment]
@ialidzhikov I don't think the second approach is simpler since this configuration value has to be exposed (and set, ideally consistently) for each and every extension.

Generally, this health checking has reached a certain complexity, and we have the chance to simplify things a little bit now. Consequently, I still vote for pursuing https://github.com/gardener/gardener/issues/6775#issuecomment-1408510744.

> On the other side, doing the MR healthchecks via gardenlet would drop some code duplication - currently there are different funcs for healthchecking ManagedResources - ones used by gardnelet, others used by the extensions.

I agree, for the time being it looks weird. However, in #6016 we track this task:

>  Consider using `ManagedResource`s for deploying shoot control plane components instead of directly applying the resources with the client

When we implement this, we can follow the same approach as proposed for the system components now (which would again simplify things).

**Comment by acumino** [comment]
Current Logic - 
Extension objects have a list of conditions in status like this 
```
- lastTransitionTime: "2023-02-03T10:42:41Z"
    lastUpdateTime: "2023-02-07T07:04:25Z"
    message: All health checks successful
    reason: HealthCheckSuccessful
    status: "True"
    type: SystemComponentsHealthy
```
where it states what type of shoot condition it contributes to. Which is decided in extensions like [this](https://github.com/gardener/gardener-extension-provider-aws/blob/36cf165d206843b182be5344451e26623efaef14/pkg/controller/healthcheck/add.go#L89-L92).

And while checking the health of `SystemComponentsHealthy` in `Gardener`, we list the extension object and check that whatever condition it is supposed to contribute is healthy or not.
So if we start handling all the MR's in `Shoot` namespace in `Seed`, health check in Gardner, it will drop overall complexity but the extension will lose control over the MRs health check, that if they want to skip it or something else.
Also, health checks will get distributed over the extension and gardener and will not be consistent as some things will be checked in the gardener and some items will be checked in extensions.

**Comment by rfranzke** [comment]
> So if we start handling all the MR's in `Shoot` namespace in `Seed`, health check in Gardner, it will drop overall complexity but the extension will lose control over the MRs health check, that if they want to skip it or something else.

Sounds like an acceptable compromise. I am not aware of a scenario where an extension deploys a `ManagedResource` for which no health check should be done.
Also, they still can contribute to the shoot conditions via this mechanism. The only thing is that everything that is a `ManagedResource` contributes automatically without any special code needed in extension.

> Also, health checks will get distributed over the extension and gardener and will not be consistent as some things will be checked in the gardener and some items will be checked in extensions.

Example? They are, naturally, already distributed today. Overall, I think it's more intuitive to assume that `ManagedResource`s are automatically checked (that's also what you assumed in your first implementation 😉) while still allowing the option to contribute with more sophisticated checks if needed.

**Comment by acumino** [comment]
> I think it's more intuitive to assume that ManagedResources are automatically checked (that's also what you assumed in your first implementation 😉)

Yes 🥲. 
Checking all MR health in the gardener is more easy and intuitive. Any thoughts @ialidzhikov ?

**Comment by acumino** [comment]
Extensions can drop ManagedResource health check when `gardener/gardener`>=`v1.65.0` is revendored

---
### Provider Extensions
- [x] Revendor g/g in [extension-provider-openstack](https://github.com/gardener/gardener-extension-provider-openstack) and drop ManagedResource health check. -> https://github.com/gardener/gardener-extension-provider-openstack/pull/564
- [x] Revendor g/g in [extension-provider-equinix-metal](https://github.com/gardener/gardener-extension-provider-equinix-metal) and drop ManagedResource health check. -> https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/244
- [x] Revendor g/g in [extension-provider-vsphere](https://github.com/gardener/gardener-extension-provider-vsphere) and drop ManagedResource health check. -> https://github.com/gardener/gardener-extension-provider-vsphere/pull/379
- [x] Revendor g/g in [extension-provider-aws](https://github.com/gardener/gardener-extension-provider-aws) and drop ManagedResource health check. -> https://github.com/gardener/gardener-extension-provider-aws/pull/695
- [x] Revendor g/g in [extension-provider-gcp](https://github.com/gardener/gardener-extension-provider-gcp) and drop ManagedResource health check. -> https://github.com/gardener/gardener-extension-provider-gcp/pull/551
- [x] Revendor g/g in [extension-provider-azure](https://github.com/gardener/gardener-extension-provider-azure) and drop ManagedResource health check. -> https://github.com/gardener/gardener-extension-provider-azure/pull/630
- [x] Revendor g/g in [extension-provider-alicloud](https://github.com/gardener/gardener-extension-provider-alicloud) and drop ManagedResource health check. -> https://github.com/gardener/gardener-extension-provider-alicloud/pull/565
---
### Networking Extensions
- [x] Revendor g/g in [extension-networking-cilium](https://github.com/gardener/gardener-extension-networking-cilium) and drop ManagedResource health check. -> https://github.com/gardener/gardener-extension-networking-cilium/pull/158
- [x] Revendor g/g in [extension-networking-calico](https://github.com/gardener/gardener-extension-networking-calico) and drop ManagedResource health check. -> https://github.com/gardener/gardener-extension-networking-calico/pull/245
- [x] Revendor g/g in [extension-shoot-networking-filter](https://github.com/gardener/gardener-extension-shoot-networking-filter) and drop ManagedResource health check. ->https://github.com/gardener/gardener-extension-shoot-networking-filter/pull/56
- [x] Revendor g/g in [extension-shoot-networking-problem-detector](https://github.com/gardener/gardener-extension-shoot-networking-problemdetector) and drop ManagedResource health check. -> https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/pull/60
---
### Others
- [x] Revendor g/g in [extension-shoot-dns-service](https://github.com/gardener/gardener-extension-shoot-dns-service) and drop ManagedResource health check. -> https://github.com/gardener/gardener-extension-shoot-dns-service/pull/194
- [x] Revendor g/g in [extension-shoot-cert-service](https://github.com/gardener/gardener-extension-shoot-cert-service) and drop ManagedResource health check. -> https://github.com/gardener/gardener-extension-shoot-cert-service/pull/148
- [x] Revendor g/g in [extension-shoot-oidc-service](https://github.com/gardener/gardener-extension-shoot-oidc-service) and drop ManagedResource health check. -> https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/93
- [x] Revendor g/g in [extension-runtime-gvisor](https://github.com/gardener/gardener-extension-runtime-gvisor) and drop ManagedResource health check. -> https://github.com/gardener/gardener-extension-runtime-gvisor/pull/75
- [x] Revendor g/g in [extension-registry-cache](https://github.com/gardener/gardener-extension-registry-cache) and drop ManagedResource health check. -> https://github.com/gardener/gardener-extension-registry-cache/pull/12

**Comment by shafeeqes** [comment]
/close
All the tasks are completed.

**Comment by shafeeqes** [comment]
The old conditions are not cleaned up in the extensions. After upgrading to a new version of the extension, where the healthcheck for condition `SystemComponentsHealthy` is removed, the controlplane extension have status:
```
status:
  conditions:
  - lastTransitionTime: "2023-03-17T00:47:05Z"
    lastUpdateTime: "2023-03-17T00:47:05Z"
    message: All health checks successful
    reason: HealthCheckSuccessful
    status: "True"
    type: ControlPlaneHealthy
  - lastTransitionTime: "2023-03-16T10:56:07Z"
    lastUpdateTime: "2023-03-16T10:58:07Z"
    message: '1) managed resource "extension-controlplane-shoot-webhooks" in namespace
      "shoot--ns--name" is unhealthy: observed generation of managed resource
      shoot--ns--name/extension-controlplane-shoot-webhooks outdated (0/1).
      2) managed resource "extension-controlplane-shoot" in namespace "shoot--ns--name"
      is unhealthy: observed generation of managed resource shoot--ns--name/extension-controlplane-shoot
      outdated (0/1). 3) managed resource "extension-controlplane-storageclasses"
      in namespace "shoot--ns--name" is unhealthy: observed generation
      of managed resource shoot--ns--name/extension-controlplane-storageclasses
      outdated (0/1).'
    reason: HealthCheckUnsuccessful
    status: "False"
    type: SystemComponentsHealthy
``` 
even though the MR is healthy.
```
❯ k get mr extension-controlplane-storageclasses
NAME                                    CLASS   APPLIED   HEALTHY   PROGRESSING   AGE
extension-controlplane-storageclasses           True      True      False         19h
```
We should clean up these conditions.
/reopen

**Comment by shafeeqes** [comment]
Extensions should add `ShootSystemComponentsHealthy` in `conditionTypesToRemove` when `gardener/gardener` `v1.65.3` or `v1.66.1` is vendored.

---
### Provider Extensions
- [x] provider-alicloud -> https://github.com/gardener/gardener-extension-provider-alicloud/pull/588
- [x] provider-aws -> https://github.com/gardener/gardener-extension-provider-aws/pull/724
- [x] provider-azure -> https://github.com/gardener/gardener-extension-provider-azure/pull/650
- [x] provider-equinix-metal -> https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/250
- [x] provider-gcp -> https://github.com/gardener/gardener-extension-provider-gcp/pull/575
- [x] provider-openstack -> https://github.com/gardener/gardener-extension-provider-openstack/pull/590
- [x] provider-vsphere -> https://github.com/gardener/gardener-extension-provider-vsphere/pull/385
---
### Networking Extensions
- [x] networking-calico -> https://github.com/gardener/gardener-extension-networking-calico/pull/252
- [x] networking-cilium -> https://github.com/gardener/gardener-extension-networking-cilium/pull/170
- [x] shoot-networking-filter -> https://github.com/gardener/gardener-extension-shoot-networking-filter/pull/60
- [x] shoot-networking-problem-detector -> https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/pull/64
---
### Others
- [x] shoot-cert-service -> https://github.com/gardener/gardener-extension-shoot-cert-service/pull/154
- [x] shoot-dns-service -> https://github.com/gardener/gardener-extension-shoot-dns-service/pull/201
- [x] shoot-oidc-service -> https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/101
- [x] runtime-gvisor -> https://github.com/gardener/gardener-extension-runtime-gvisor/pull/79
- [x] registry-cache -> https://github.com/gardener/gardener-extension-registry-cache/pull/16

**Comment by shafeeqes** [comment]
/close
All tasks are completed.
