### ISSUE TITLE
Allow Shoot TLS certificates with more than 64 characters

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#679]
Gardener offers a certificate service for Shoot cluster Ingress domains. Unfortunately, a `Common Name (CN)` field of a certificate is **limited to 64 characters** but at the same time required by Let's Encrypt (https://community.letsencrypt.org/t/ssl-for-a-63-character-max-number-of-characters-domain-name-s/36387/17), i.e. it's not possible to leave out `CN` and fill out `Subject Alternative Name` (SAN) instead. Domains in `SAN` aren't subjected to this character limitation.

Furthermore, a standard Ingress domain of a Shoot cluster can easily exceed 64 characters since it's built up by `<xyz>.ingress.<shootName>.<projectName>.<externalDefaultDomain>`, so the certificate service cannot be used in such cases.

I suggest the following to circumvent this restriction:
1. Calculate a single and unique domain for a Shoot cluster:
`<hash(shootName & projectName)>.<externalDefaultDomain>`
2. Use domain from 1. in `CN`.
3. Add any other Shoot Ingress domain to `SAN`.
4. Request certificate.

Any feedback is appreciated!

**Comment by marwinski** [comment]
I like this idea but doesn't it require changes to the certificate manager?

**Comment by timuthy** [comment]
It will require changes to `Gardener` or the `Certificate Service Extension` which will do the domain calculation as well as `Cert-Broker` which will enrich the replicated Ingress by this domain. Changes to `Cert-Manager` won't be required.

**Comment by timuthy** [comment]
**Update:**
Along with our plans towards extensibility we want to extend our Shoot specification by a field `.spec.dns.ingressDomain`.

- A selected ingress domain must be a subdomain of `externalDefaultDomain`. In case of a custom Shoot domain, any domain is accepted since Gardener doesn't know how the hostedZone is related to the domain.
- A selected ingress domain is checked against existing Shoot resources to verify its uniqueness.

This is an alternative approach to what is explained in the description but gives a Shoot owner the possibility to choose a shorter ingress domain himself.

Please note, that this change won't affect the scope of manageable certificates. That is, certificates will still only be offered for domains which are under the control of Gardener, i.e. `externalDefaultDomain`.

**Comment by rfranzke** [comment]
After a discussion we went away from the idea of having `.spec.dns.ingressDomain`, see #731.
To fix the problem here (64 char limit), we decided to generate a second wildcard ingress domain (not configurable) for every shoot that has enabled the nginx-ingress addon.

Based on the "internal domain" configured in the garden cluster we will compute a random value, and create a DNS record pointing to the nginx-ingress load balancer.

For example, with internal domain `internal.my-domain.com`, the shoot `my-shoot` in project `my-project` could get the following additional ingress domain:

`*.98an23y3.internal.my-domain.com`.

This domain will be generated by the admission controller and put into the `.spec.addons.nginx-ingress.wildcardDNSRecords.additonal`:

```yaml
apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  name: johndoe-aws
  namespace: garden-dev
spec:
  ...
  addons:
    nginx-ingress:
      enabled: true
      loadBalancerSourceRanges: []
      wildcardDNSRecords:
        standard: ingress.johndoe-aws.garden-dev.example.com
        second: 98an23y3.internal.my-domain.com
```

**Comment by timuthy** [comment]
@rfranzke what do you think about having:
```
...
  wildcardDNSRecords:
  - ingress.johndoe-aws.garden-dev.example.com
  - 98an23y3.internal.my-domain.com
```

So admission could look like the following:

```
count := 0
for dns := range wildcardDNSRecords {
  if ! shootDomainSuffix(dns) && modified(dns) {
    reject("Domain is not a Shoot domain.")
  } else {
    count++
  }
}

if count > 1 {
  reject("Too many DNS records for Shoot domain.")
}
```

Imho, this means a little more effort in the code but a cleaner API since both Ingress records work the same way.

**Comment by rfranzke** [comment]
👍 much better, thank you

**Comment by timuthy** [comment]
Any efforts of bringing this to Gardener are stopped. We'll rather go with the approach of having a dedicated DNS service for shoot clusters in the future.
