### ISSUE TITLE
unable to downscale unused nodes

### ISSUE THREAD

**Issue by freegroup** [gardener/gardener#68]
unused nodes stays forever.

```
failed to mark the node as toBeDeleted/unschedulable: nodes "ip-10-250-27-69.ec2.internal" is forbidden: User "system:serviceaccount:kube-system:addons-cluster-autoscaler" cannot update nodes at the cluster scope
```

<img width="633" alt="bildschirmfoto 2018-01-26 um 12 51 35" src="https://user-images.githubusercontent.com/1155039/35438769-24cbe686-0298-11e8-8d1c-95d5159f34d4.png">

**Comment by rfranzke** [comment]
Hi, thanks for reporting.

This issue has already been fixed: https://github.com/gardener/gardener/blob/master/charts/shoot-addons/charts/cluster-autoscaler/templates/clusterrole.yaml#L33-L44

**Comment by freegroup** [comment]
Hi Rafael,

Is this already deployed and available for new clusters?
