### ISSUE TITLE
Please provide missing custom override mechanism for node-local-dns

### ISSUE THREAD

**Issue by cbarbian-sap** [gardener/gardener#6852]
**How to categorize this issue?**

/area control-plane
/kind enhancement

**What would you like to be added**:

For the 'normal' cluster coredns service Gardener offers a possibility to inject custom servers and custom overrides for the main server, see https://github.com/gardener/gardener/blob/master/docs/usage/custom-dns-config.md ...

Please add the same or a similar functionality for the node-local-dns.
At least the overrides part would be useful/required, the custom servers thing maybe does not make much sense in this context, not sure.

**Why is this needed**:

With node-local-dns enabled, the 'normal' cluster coredns service is no longer answering all DNS lookup requests originating from the cluster, but only queries for '.cluster.local'. This causes functional defects, for example when `rewrite` rules for non-cluster.local addresses are defined via override in the `coredns-custom` configmap.

**Comment by ScheererJ** [comment]
https://github.com/gardener/gardener/pull/6856 documents the status quo.
