### ISSUE TITLE
Gardenlet in local gardener fails to create seed due to IP CIDR conflicts

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#6872]
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What happened**:
Following this guide https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally.md, it failed on step `make gardener-up` as no seed was created. In fact, gardenlet is crashing with this error message
```
panic: failed during bootstrapping: incorrect node network specified in seed configuration (cluster node="192.168.16.2" vs. config="172.18.0.0/16")
```

**What you expected to happen**:
To be able to create local gardener environment

**How to reproduce it (as minimally and precisely as possible)**:
Follow the guide from https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally.md

**Anything else we need to know?**:
It is still working, if I checkout `v1.57.0` tag.

**Environment**:

- Gardener version: afa6db45466a5f1c171a3848ef0f86168464d92c
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
The problem is that the node CIDR is hard-coded at several places (https://github.com/gardener/gardener/search?q=%22172.18.0.0%2F16%22). This specific CIDR seems to only be the correct one for Macs.

**Comment by vpnachev** [comment]
@dimityrmirchev suggested that this is related to the `kind` docker network which changed its CIDR in newer versions of kind and needs to be re-created, but this is did not work for me as it still uses the `192.168.16.0/20` CIDR.
