### ISSUE TITLE
Validation Webhook for worker groups

### ISSUE THREAD

**Issue by mandelsoft** [gardener/gardener#6881]
**How to categorize this issue?**
 /area control-plane
/kind impediment

**What happened**:

A worker group has configured multiple times the same zone. Fixing this by deleting the additional occurrences is prevented
by the UI as well as by the validation webhook.

But, because it has been created earlier, the creation must have been accepted by the webhook, which leads to reconcilation problems for the worker group.

**What you expected to happen**:

It is not possible to configure such erroneous worker group configuration.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: canary
- Cloud provider or hardware configuration: AWS

**Comment by rfranzke** [comment]
> A worker group has configured multiple times the same zone. 

Yes, generally this is not forbidden. It is in the responsibility of the user to properly configure the network layout of their IaaS layer as well as the worker pools. Gardener does not make any assumptions.

> Fixing this by deleting the additional occurrences is prevented by the UI as well as by the validation webhook.

Yes, deleting existing zones is not permitted (and will not be for now).

>  which leads to reconcilation problems for the worker group.

Can you share more information? Which "problems" occur during reconciliation? Can you share logs?
