### ISSUE TITLE
Extension regularly report an outdated health status in Canary landscape

### ISSUE THREAD

**Issue by mandelsoft** [gardener/gardener#6883]
**How to categorize this issue?**

/area control-plane
/kind question

**What happened**:

Several times a day a lot of shoots are reported with problems, because extensions report an outdated health status.
This happend for all extensions, but in most of the cases only the cert or dns extension is reported on the dashboard.

The problem state persists for up to 10 minutes for more than 100 shoots in canary.  Then it disappears again.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: canary
- Cloud provider or hardware configuration: in most cases on AWS eu-central-1, but also seen on Azure

**Comment by rfranzke** [comment]
What do you think should be the next step to analyse this? I don't see any information in this issue (no logs of extensions, no gardenlet logs, nothing at all). Can you provide them, please?
