### ISSUE TITLE
Consider removing `SeedTemplate` field from ManagedSeed

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#6898]
**How to categorize this issue?**

/area scalability
/kind cleanup

**What would you like to be added**:
The field `SeedTemplate` in the ManagedSeed-API is used to register the `seed` object via the ManagedSeed-Controller rather than the Gardenlet.

```
	// SeedTemplate is a template for a Seed object, that should be used to register a given cluster as a Seed.
	// Either SeedTemplate or Gardenlet must be specified. When Seed is specified, the ManagedSeed controller will not deploy a gardenlet into the cluster
	// and an existing gardenlet reconciling the new Seed is required.
```

At the same time, the Gardenlet-Config **requires** the `config.seedConfig` to be set, i.e. it is anyway registering or updating the `seed` object when it starts.

The two concepts are conflicting and we should only follow one approach. Since Gardenlet mimics the behavior of Kubelet WRT node registration, it's preferred to get rid of the mentioned ManagedSeed use-case and to remove the `ManagedSeed.SeedTemplate` field completely.

**Comment by rfranzke** [comment]
@timuthy wants to work on this, thanks!
/assign @timuthy
