### ISSUE TITLE
[Flaky Test] Extensions Controller BackupBucket Integration Test Suite

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#6904]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
`BackupBucket should successfully create and delete a BackupBucket (respecting operation annotation)`

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6902/pull-gardener-integration/1585137129640431616#1:build-log.txt%3A131-219

**Reason for failure**:
The test never observes the BackupBucket object to transition to `status.lastOperation.state=Error` but instead sees `Processing`.
This could be caused by the exponential backoff (the requested error causes the controller to retry).

**Anything else we need to know**:

**Comment by timebertt** [comment]
ref https://github.com/gardener/gardener/pull/6902

**Comment by rfranzke** [comment]
@timuthy FYI https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7086/pull-gardener-integration/1597201262674186240

**Comment by timuthy** [comment]
Wow, it even ran into the 5 mins timeout 😮 I'll have another look if and how this is related to the slower rate limiter. Thanks for letting me know 👍

**Comment by timuthy** [comment]
We set the test timeout to `5m` but this is the overall timeout which is why I think it is not related to the BackupBucket controller. The strike happened more or less by coincidence because the global timeout was exceeded. Does that make sense? Should we increase the timeout to `10m` as we have more and more integration tests?

**Comment by timebertt** [comment]
Are you referring to this line? https://github.com/gardener/gardener/blob/d856aa25803701ccdf540569fd8639f4ae94890c/hack/test-integration.sh#L45

The `-timeout` flag of `go test` specifies a "per-suite" timeout, not an overall timeout of the integration test:
```
go help testflag
...
	-timeout d
	    If a test binary runs longer than duration d, panic.
	    If d is 0, the timeout is disabled.
	    The default is 10 minutes (10m).
```

I'm afraid, that the test run rather failed because the individual test took too long, but not because of the overall number of integration tests.

**Comment by timuthy** [comment]
Okay, thanks for double checking 👍. I played around with this value yesterday and it seemed like it's not applying per suite for some reason.

I ran it again locally and even after 10 minutes of stress testing, the integration tests passed. Unfortunately, the test output doesn't show any valuable information either about the `Extensions Controller BackupBucket Integration Test Suite`. Only the stacktrace shows that the test waited for the `BackupBucket` to become ready but apart from that there are no log entries or similar.

It seems like with `-timeout` the buffered output in `GinkgoWriter` can't be dumped. WDYT using `-ginkgo.timeout=5m` instead? I tried it out locally, it printed out the expected logs after the timeout had happened.

**Comment by timebertt** [comment]
Yes, that sounds good. Let's use `-ginkgo.timeout` instead of `-timeout` to get a nicer output 👍 
I'm not sure if this will break the test cache though. If I remember correctly, go considers test invocations with additional arguments as "non-cacheable".

**Comment by shafeeqes** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7180/pull-gardener-integration/1602180030815801344
