### ISSUE TITLE
kube-controller-manager: unknown flag: --cluster-signing-kube-apiserver-client-cert-file

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#6906]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
After https://github.com/gardener/gardener/pull/6784 `kube-controller-manager` for a Shoot with K8s 1.18.20 fails with:
```
$ k -n shoot--foo--bar kube-controller-manager-5fd48598d5-mtmdk
Error: unknown flag: --cluster-signing-kube-apiserver-client-cert-file
```

It seems that the corresponding flag is not present in v1.18.20. The `--cluster-signing-kube-apiserver-client-cert-file` flag is added starting K8s 1.19 with https://github.com/kubernetes/kubernetes/pull/90822.

**What you expected to happen**:
gardenlet to do not configure kube-controller-manager with an invalid flag.

**How to reproduce it (as minimally and precisely as possible)**:
Create a v1.18.20 Shoot and verify the above error.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.58.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
The issue will be tackled with https://github.com/gardener/gardener/issues/6911.

**Comment by rfranzke** [comment]
Shall we close this in favor of #6911?

**Comment by ialidzhikov** [comment]
/close
as the issue will be tackled with https://github.com/gardener/gardener/issues/6911
