### ISSUE TITLE
`make check-apidiff` is silently panicking

### ISSUE THREAD

**Issue by oliver-goetz** [gardener/gardener#6917]
**How to categorize this issue?**

/area TODO
/kind bug

**What happened**:
`make check-apidiff` is silently panicking in each PR: [ref](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6915/pull-gardener-apidiff/1585770153394573312), [ref](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6916/pull-gardener-apidiff/1585762892211294208), [ref](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6915/pull-gardener-apidiff/1585703311900676096), [ref](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6749/pull-gardener-apidiff/1585656505607131136), [ref](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6914/pull-gardener-apidiff/1585651636599001088)

**What you expected to happen**:
`make check-apidiff` not panicking.

**How to reproduce it (as minimally and precisely as possible)**:
Run `make check-apidiff` locally or in a PR.

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by acumino** [comment]
we need to upgrade new go-apidiff release with this PR https://github.com/joelanford/go-apidiff/pull/19 in.
