### ISSUE TITLE
[Flaky Test] ShootState Extensions Controller Integration Test Suite

### ISSUE THREAD

**Issue by acumino** [gardener/gardener#6923]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:

```
ShootState Extensions controller tests
/home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/shootstate/extensions/extensions_test.go:33
  when reconciliation should be performed
  /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/shootstate/extensions/extensions_test.go:113
    [It] should update the resources
    /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/shootstate/extensions/extensions_test.go:131
```

and 

```
ShootState Extensions controller tests
/home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/shootstate/extensions/extensions_test.go:33
  when reconciliation should be performed
  /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/shootstate/extensions/extensions_test.go:113
    [It] should remove the state when deletion timestamp is set
    /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/shootstate/extensions/extensions_test.go:234
```
**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6912/pull-gardener-integration/1585932846114017280
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6912/pull-gardener-integration/1585935334800101376

**Reason for failure**:

**Anything else we need to know**:

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6919/pull-gardener-integration/1586987487371202560

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6871/pull-gardener-integration/1583427715539668992

**Comment by shafeeqes** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration/1587184101889150976

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6953/pull-gardener-integration/1588432675562065920

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6955/pull-gardener-integration/1589884252810383360

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6942/pull-gardener-integration/1589903601944236032

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6955/pull-gardener-integration/1589904549689167872

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6967/pull-gardener-integration/1589919843140767744

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6971/pull-gardener-integration/1589966613707231232

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-59/1589966808553623552

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration/1590265201867886592

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6967/pull-gardener-integration/1590369680780955648

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-59/1590389774017892352

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6839/pull-gardener-integration/1590642637797330944

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6994/pull-gardener-integration-release-v1-59/1590977273563975680

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6998/pull-gardener-integration/1591003340601298944

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6973/pull-gardener-integration/1591052708461154304

**Comment by acumino** [comment]
Another one - https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6993/pull-gardener-integration/1591064788916506624

**Comment by shafeeqes** [comment]
Another one - https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6973/pull-gardener-integration/1591052708461154304

**Comment by rfranzke** [comment]
A new one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7154/pull-gardener-integration/1600059754376335360
/reopen
