### ISSUE TITLE
[Flaky Test] Project Activity controller tests

### ISSUE THREAD

**Issue by shafeeqes** [gardener/gardener#6928]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
Project Activity controller tests
/home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/project/activity/activity_test.go:33
  when object is Secret
  /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/project/activity/activity_test.go:221
    [It] should update the lastActivityTimestamp in the Project status
```
**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6837/pull-gardener-integration/1586977319220678656

**Reason for failure**:
```
    <*errors.errorString | 0xc003358620>: {
          s: "Assertion in callback at /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/project/activity/activity_test.go:269 failed:\nExpected\n    <*v1.Time | 0x0>: nil\nnot to be nil",
      }
      Assertion in callback at /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/project/activity/activity_test.go:269 failed:
      Expected
          <*v1.Time | 0x0>: nil
      not to be nil
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/project/activity/activity_test.go:89
```

**Anything else we need to know**:

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6945/pull-gardener-integration-release/1588057792680300544

**Comment by shafeeqes** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6948/pull-gardener-integration/1588109381390569472

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6951/pull-gardener-integration/1588145125026959360

**Comment by axel7born** [comment]
An other one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6942/pull-gardener-integration/1588417128011141120

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-57/1589845759593811968

**Comment by shafeeqes** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6926/pull-gardener-integration/1589945678304382976

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-57/1589966556819886080

This time, the `Project` controller itself

```
• [FAILED] [5.269 seconds]
Project controller tests
/home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/project/project/project_test.go:38
  [It] should not release the project as long as it still contains shoots
  /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/project/project/project_test.go:1[63](https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-57/1589966556819886080#1:build-log.txt%3A63)
  Begin Captured GinkgoWriter Output >>
    STEP: Create Project 11/08/22 13:04:40.958
    {"level":"info","ts":"2022-11-08T13:04:40.961Z","msg":"Reconciling project","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"c310c20b-7ca4-47f3-935a-f79c18886118"}
    {"level":"info","ts":"2022-11-08T13:04:40.961Z","msg":"Adding finalizer","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"c310c20b-7ca4-47f3-935a-f79c18886118"}
    {"level":"info","ts":"2022-11-08T13:04:40.961Z","logger":"project-controller-test","msg":"Created Project","project":{"name":"test-da802"}}
    STEP: Wait for Project to be reconciled 11/08/22 13:04:40.961
    {"level":"info","ts":"2022-11-08T13:04:40.970Z","msg":"Creating Namespace for Project","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"c310c20b-7ca4-47f3-935a-f79c18886118","namespaceName":"garden-test-da802"}
    {"level":"debug","ts":"2022-11-08T13:04:40.974Z","logger":"events","msg":"Successfully reconciled namespace \"garden-test-da802\" for project","type":"Normal","object":{"kind":"Project","name":"test-da802","uid":"553f0e87-d7ae-49d3-9206-c548ab16881c","apiVersion":"core.gardener.cloud/v1beta1","resourceVersion":"246"},"reason":"NamespaceReconcileSuccessful"}
    STEP: Create Shoot 11/08/22 13:04:41.17
    {"level":"info","ts":"2022-11-08T13:04:41.177Z","logger":"KubeAPIWarningLogger","msg":"you should consider disabling the static token kubeconfig, see https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md for details"}
    {"level":"info","ts":"2022-11-08T13:04:41.177Z","logger":"project-controller-test","msg":"Created Shoot for test","shoot":{"namespace":"garden-test-da802","name":"test-z5tls"}}
    STEP: Delete Project 11/08/22 13:04:41.178
    {"level":"info","ts":"2022-11-08T13:04:41.181Z","msg":"Deleting project","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"d7d40347-fc55-489e-9684-52a6c6d47148"}
    {"level":"info","ts":"2022-11-08T13:04:41.181Z","msg":"Deleting Project Namespace","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"d7d40347-fc55-489e-9684-52a6c6d47148","namespaceName":"garden-test-da802"}
    STEP: Wait for Project to be reconciled 11/08/22 13:04:41.181
    {"level":"debug","ts":"2022-11-08T13:04:41.186Z","msg":"Finalizing Namespace","controller":"namespacefinalizer","controllerGroup":"","controllerKind":"Namespace","Namespace":{"name":"garden-test-da802"},"namespace":"","name":"garden-test-da802","reconcileID":"63dae98d-7fdd-4913-8a5b-75e98217e59c"}
    {"level":"debug","ts":"2022-11-08T13:04:41.186Z","logger":"events","msg":"Successfully marked project namespace \"garden-test-da802\" for deletion","type":"Normal","object":{"kind":"Project","name":"test-da802","uid":"553f0e87-d7ae-49d3-9206-c548ab16881c","apiVersion":"core.gardener.cloud/v1beta1","resourceVersion":"263"},"reason":"NamespaceMarkedForDeletion"}
    {"level":"debug","ts":"2022-11-08T13:04:41.197Z","msg":"Object is gone, stop reconciling","controller":"namespacefinalizer","controllerGroup":"","controllerKind":"Namespace","Namespace":{"name":"garden-test-da802"},"namespace":"","name":"garden-test-da802","reconcileID":"cdd84930-61cb-4110-907b-503fd84e31b2"}
    {"level":"info","ts":"2022-11-08T13:04:41.197Z","msg":"Deleting project","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"cf8b[64](https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-57/1589966556819886080#1:build-log.txt%3A64)97-be3d-4605-bb24-ab2d4d188213"}
    {"level":"info","ts":"2022-11-08T13:04:41.197Z","msg":"Removing finalizer","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"cf8b6497-be3d-4605-bb24-ab2d4d188213","namespaceName":"garden-test-da802"}
    {"level":"debug","ts":"2022-11-08T13:04:41.202Z","msg":"Object is gone, stop reconciling","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"deb2c13b-7161-4a7d-922d-55b6b378d807"}
    STEP: Cleanup Shoot 11/08/22 13:04:46.184
    STEP: Delete Project 11/08/22 13:04:46.218
    STEP: Wait for Project to be gone 11/08/22 13:04:46.225
  << End Captured GinkgoWriter Output
  Timed out after 5.002s.
  Expected success, but got an error:
      <*errors.errorString | 0xc00261[74](https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-57/1589966556819886080#1:build-log.txt%3A74)20>: {
          s: "Assertion in callback at /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/project/project/project_test.go:144 failed:\nExpected success, but got an error:\n    <*errors.StatusError | 0xc003193540>: {\n        ErrStatus: {\n            TypeMeta: {Kind: \"\", APIVersion: \"\"},\n            ListMeta: {\n                SelfLink: \"\",\n                ResourceVersion: \"\",\n                Continue: \"\",\n                RemainingItemCount: nil,\n            },\n            Status: \"Failure\",\n            Message: \"projects.core.gardener.cloud \\\"test-da[80](https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-57/1589966556819886080#1:build-log.txt%3A80)2\\\" not found\",\n            Reason: \"NotFound\",\n            Details: {\n                Name: \"test-da802\",\n                Group: \"core.gardener.cloud\",\n                Kind: \"projects\",\n                UID: \"\",\n                Causes: nil,\n                RetryAfterSeconds: 0,\n            },\n            Code: 404,\n        },\n    }\n    projects.core.gardener.cloud \"test-da802\" not found",
      }
      Assertion in callback at /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/project/project/project_test.go:144 failed:
      Expected success, but got an error:
          <*errors.StatusError | 0xc0031[93](https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-57/1589966556819886080#1:build-log.txt%3A93)540>: {
              ErrStatus: {
                  TypeMeta: {Kind: "", APIVersion: ""},
                  ListMeta: {
                      SelfLink: "",
                      ResourceVersion: "",
                      Continue: "",
                      RemainingItemCount: nil,
                  },
                  Status: "Failure",
                  Message: "projects.core.gardener.cloud \"test-da802\" not found",
                  Reason: "NotFound",
                  Details: {
                      Name: "test-da802",
                      Group: "core.gardener.cloud",
                      Kind: "projects",
                      UID: "",
                      Causes: nil,
                      RetryAfterSeconds: 0,
                  },
                  Code: 404,
              },
          }
          projects.core.gardener.cloud "test-da802" not found
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/project/project/project_test.go:147
```

**Comment by shafeeqes** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6837/pull-gardener-integration/1589992038886019072

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6979/pull-gardener-integration/1590368042737471488

**Comment by rfranzke** [comment]
> Another one: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-57/1589966556819886080
> 
> This time, the `Project` controller itself
> 
> ```
> • [FAILED] [5.269 seconds]
> Project controller tests
> /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/project/project/project_test.go:38
>   [It] should not release the project as long as it still contains shoots
>   /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/project/project/project_test.go:1[63](https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-57/1589966556819886080#1:build-log.txt%3A63)
>   Begin Captured GinkgoWriter Output >>
>     STEP: Create Project 11/08/22 13:04:40.958
>     {"level":"info","ts":"2022-11-08T13:04:40.961Z","msg":"Reconciling project","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"c310c20b-7ca4-47f3-935a-f79c18886118"}
>     {"level":"info","ts":"2022-11-08T13:04:40.961Z","msg":"Adding finalizer","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"c310c20b-7ca4-47f3-935a-f79c18886118"}
>     {"level":"info","ts":"2022-11-08T13:04:40.961Z","logger":"project-controller-test","msg":"Created Project","project":{"name":"test-da802"}}
>     STEP: Wait for Project to be reconciled 11/08/22 13:04:40.961
>     {"level":"info","ts":"2022-11-08T13:04:40.970Z","msg":"Creating Namespace for Project","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"c310c20b-7ca4-47f3-935a-f79c18886118","namespaceName":"garden-test-da802"}
>     {"level":"debug","ts":"2022-11-08T13:04:40.974Z","logger":"events","msg":"Successfully reconciled namespace \"garden-test-da802\" for project","type":"Normal","object":{"kind":"Project","name":"test-da802","uid":"553f0e87-d7ae-49d3-9206-c548ab16881c","apiVersion":"core.gardener.cloud/v1beta1","resourceVersion":"246"},"reason":"NamespaceReconcileSuccessful"}
>     STEP: Create Shoot 11/08/22 13:04:41.17
>     {"level":"info","ts":"2022-11-08T13:04:41.177Z","logger":"KubeAPIWarningLogger","msg":"you should consider disabling the static token kubeconfig, see https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md for details"}
>     {"level":"info","ts":"2022-11-08T13:04:41.177Z","logger":"project-controller-test","msg":"Created Shoot for test","shoot":{"namespace":"garden-test-da802","name":"test-z5tls"}}
>     STEP: Delete Project 11/08/22 13:04:41.178
>     {"level":"info","ts":"2022-11-08T13:04:41.181Z","msg":"Deleting project","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"d7d40347-fc55-489e-9684-52a6c6d47148"}
>     {"level":"info","ts":"2022-11-08T13:04:41.181Z","msg":"Deleting Project Namespace","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"d7d40347-fc55-489e-9684-52a6c6d47148","namespaceName":"garden-test-da802"}
>     STEP: Wait for Project to be reconciled 11/08/22 13:04:41.181
>     {"level":"debug","ts":"2022-11-08T13:04:41.186Z","msg":"Finalizing Namespace","controller":"namespacefinalizer","controllerGroup":"","controllerKind":"Namespace","Namespace":{"name":"garden-test-da802"},"namespace":"","name":"garden-test-da802","reconcileID":"63dae98d-7fdd-4913-8a5b-75e98217e59c"}
>     {"level":"debug","ts":"2022-11-08T13:04:41.186Z","logger":"events","msg":"Successfully marked project namespace \"garden-test-da802\" for deletion","type":"Normal","object":{"kind":"Project","name":"test-da802","uid":"553f0e87-d7ae-49d3-9206-c548ab16881c","apiVersion":"core.gardener.cloud/v1beta1","resourceVersion":"263"},"reason":"NamespaceMarkedForDeletion"}
>     {"level":"debug","ts":"2022-11-08T13:04:41.197Z","msg":"Object is gone, stop reconciling","controller":"namespacefinalizer","controllerGroup":"","controllerKind":"Namespace","Namespace":{"name":"garden-test-da802"},"namespace":"","name":"garden-test-da802","reconcileID":"cdd84930-61cb-4110-907b-503fd84e31b2"}
>     {"level":"info","ts":"2022-11-08T13:04:41.197Z","msg":"Deleting project","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"cf8b[64](https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-57/1589966556819886080#1:build-log.txt%3A64)97-be3d-4605-bb24-ab2d4d188213"}
>     {"level":"info","ts":"2022-11-08T13:04:41.197Z","msg":"Removing finalizer","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"cf8b6497-be3d-4605-bb24-ab2d4d188213","namespaceName":"garden-test-da802"}
>     {"level":"debug","ts":"2022-11-08T13:04:41.202Z","msg":"Object is gone, stop reconciling","controller":"project","controllerGroup":"core.gardener.cloud","controllerKind":"Project","Project":{"name":"test-da802"},"namespace":"","name":"test-da802","reconcileID":"deb2c13b-7161-4a7d-922d-55b6b378d807"}
>     STEP: Cleanup Shoot 11/08/22 13:04:46.184
>     STEP: Delete Project 11/08/22 13:04:46.218
>     STEP: Wait for Project to be gone 11/08/22 13:04:46.225
>   << End Captured GinkgoWriter Output
>   Timed out after 5.002s.
>   Expected success, but got an error:
>       <*errors.errorString | 0xc00261[74](https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-57/1589966556819886080#1:build-log.txt%3A74)20>: {
>           s: "Assertion in callback at /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/project/project/project_test.go:144 failed:\nExpected success, but got an error:\n    <*errors.StatusError | 0xc003193540>: {\n        ErrStatus: {\n            TypeMeta: {Kind: \"\", APIVersion: \"\"},\n            ListMeta: {\n                SelfLink: \"\",\n                ResourceVersion: \"\",\n                Continue: \"\",\n                RemainingItemCount: nil,\n            },\n            Status: \"Failure\",\n            Message: \"projects.core.gardener.cloud \\\"test-da[80](https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-57/1589966556819886080#1:build-log.txt%3A80)2\\\" not found\",\n            Reason: \"NotFound\",\n            Details: {\n                Name: \"test-da802\",\n                Group: \"core.gardener.cloud\",\n                Kind: \"projects\",\n                UID: \"\",\n                Causes: nil,\n                RetryAfterSeconds: 0,\n            },\n            Code: 404,\n        },\n    }\n    projects.core.gardener.cloud \"test-da802\" not found",
>       }
>       Assertion in callback at /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/project/project/project_test.go:144 failed:
>       Expected success, but got an error:
>           <*errors.StatusError | 0xc0031[93](https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-57/1589966556819886080#1:build-log.txt%3A93)540>: {
>               ErrStatus: {
>                   TypeMeta: {Kind: "", APIVersion: ""},
>                   ListMeta: {
>                       SelfLink: "",
>                       ResourceVersion: "",
>                       Continue: "",
>                       RemainingItemCount: nil,
>                   },
>                   Status: "Failure",
>                   Message: "projects.core.gardener.cloud \"test-da802\" not found",
>                   Reason: "NotFound",
>                   Details: {
>                       Name: "test-da802",
>                       Group: "core.gardener.cloud",
>                       Kind: "projects",
>                       UID: "",
>                       Causes: nil,
>                       RetryAfterSeconds: 0,
>                   },
>                   Code: 404,
>               },
>           }
>           projects.core.gardener.cloud "test-da802" not found
>   In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/project/project/project_test.go:147
> ```

Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6977/pull-gardener-integration/1590596853710196736

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6967/pull-gardener-integration/1590632744210141184

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration/1590869511567839232

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/batch/pull-gardener-integration/1590958004495192064

**Comment by oliver-goetz** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6991/pull-gardener-integration/1592077703593332736

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7062/pull-gardener-integration/1595762629912039424

/reopen

**Comment by oliver-goetz** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6678/pull-gardener-integration/1595830864925691904

Removing the `Ordered` directive in https://github.com/gardener/gardener/pull/7043 might be the reason for this.

**Comment by oliver-goetz** [comment]
I did not see @shafeeqes comment: https://github.com/gardener/gardener/pull/7020#issuecomment-1320188359
Thus, my statement from the previous comment is wrong 😅

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-60/1596052914634231808

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-61/1599609152022253568
