### ISSUE TITLE
[Flaky Test] Seed Controller Integration Test Suite

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#6933]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
Seed controller tests
/home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:38
  when seed namespace exists
  /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:95
    when internal domain secret exists
    /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:129
      when global monitoring secret exists
      /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:166
        [It] should properly maintain the Bootstrapped condition
        /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:190
```

**CI link**:
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6873/pull-gardener-integration/1586620335078248448

**Reason for failure**:
```
Timed out after 5.003s.
  Expected
      <[]v1beta1.Condition | len:1, cap:1>: [
          {
              Type: "Bootstrapped",
              Status: "False",
              LastTransitionTime: {
                  Time: 2022-10-30T07:27:58Z,
              },
              LastUpdateTime: {
                  Time: 2022-10-30T07:27:58Z,
              },
              Reason: "GardenSecretsError",
              Message: "need an internal domain secret but found none",
              Codes: nil,
          },
      ]
  to contain element matching
      <*matchers.AndMatcher | 0xc004a11d10>: {
          Matchers: [
              <*gstruct.FieldsMatcher | 0xc004a11c80>{
                  Fields: {
                      "Type": <*matchers.EqualMatcher | 0xc002e01510>{
                          Expected: <v1beta1.ConditionType>"Bootstrapped",
                      },
                  },
                  IgnoreExtras: true,
                  IgnoreMissing: false,
                  failures: nil,
              },
              <*gstruct.FieldsMatcher | 0xc004a11ce0>{
                  Fields: {
                      "Status": <*matchers.EqualMatcher | 0xc002e01530>{
                          Expected: <v1beta1.ConditionStatus>"Progressing",
                      },
                  },
                  IgnoreExtras: true,
                  IgnoreMissing: false,
                  failures: [
                      <*errors.NestedError | 0xc0025a3440>{
                          Path: ".Status",
                          Err: <*errors.errorString | 0xc003[166](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6873/pull-gardener-integration/1586620335078248448#1:build-log.txt%3A166)770>{
                              s: "Expected\n    <v1beta1.ConditionStatus>: False\nto equal\n    <v1beta1.ConditionStatus>: Progressing",
                          },
                      },
                  ],
              },
          ],
          firstFailedMatcher: <*gstruct.FieldsMatcher | 0xc004a11ce0>{
              Fields: {
                  "Status": <*matchers.EqualMatcher | 0xc002e01530>{
                      Expected: <v1beta1.ConditionStatus>"Progressing",
                  },
              },
              IgnoreExtras: true,
              IgnoreMissing: false,
              failures: [
                  <*errors.NestedError | 0xc0025a3440>{
                      Path: ".Status",
                      Err: <*errors.errorString | 0xc003166770>{
                          s: "Expected\n    <v1beta1.ConditionStatus>: False\nto equal\n    <v1beta1.ConditionStatus>: Progressing",
                      },
                  },
              ],
          },
      }
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:[201](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6873/pull-gardener-integration/1586620335078248448#1:build-log.txt%3A201)
```

**Comment by shafeeqes** [comment]
Another test:
```
• [FAILED] [10.197 seconds]
Seed controller tests
/home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:42
  when seed namespace exists
  /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:106
    when internal domain secret exists
    /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:140
      when global monitoring secret exists
      /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:177
        when seed cluster is garden cluster at the same time
        /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:354
          [It] should not manage components managed by gardener-operator
```
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7055/pull-gardener-integration/1595094201236721664

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7048/pull-gardener-integration/1595432196343074816

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration/1595581470750019584

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7062/pull-gardener-integration/1595693472789041152

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7067/pull-gardener-integration/1595690595425193984

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration/1595702350595493888

**Comment by shafeeqes** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7080/pull-gardener-integration/1596078462827761664

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration-release-v1-59/1596068517638049792

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7086/pull-gardener-integration/1597203594749153280

**Comment by timuthy** [comment]
Same suite but different test: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7119/pull-gardener-integration/1597955763936956416

```
Seed Controller Integration Test Suite: [It] Seed controller tests when seed namespace exists when internal domain secret exists when global monitoring secret exists when seed cluster is garden cluster at the same time should not manage components managed by gardener-operator
```

/cc @rfranzke

**Comment by shafeeqes** [comment]
> Same suite but different test: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7086/pull-gardener-integration/1597203594749153280
> 
> ```
> Seed Controller Integration Test Suite: [It] Seed controller tests when seed namespace exists when internal domain secret exists when global monitoring secret exists when seed cluster is garden cluster at the same time should not manage components managed by gardener-operator
> ```
> 
> /cc @rfranzke

Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7044/pull-gardener-integration/1598233026121175040

@timuthy, You probably pasted the wrong CI link.

**Comment by rfranzke** [comment]
Another occurrence in `master`: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7144/pull-gardener-integration/1599720790868103168
/reopen

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7152/pull-gardener-integration/1599806025207123968

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7154/pull-gardener-integration/1600059754376335360

**Comment by shafeeqes** [comment]
Another occurence: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7180/pull-gardener-integration/1602282101380485120

**Comment by acumino** [comment]
> Another occurence: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7180/pull-gardener-integration/1602282101380485120

This is what I mentioned in my PR, sometimes secret reconciliation needs extra time. I will increase the time out.

**Comment by shafeeqes** [comment]
```
• [SLOW TEST] [5.019 seconds]
Seed controller tests when seed namespace does not exist should not maintain the Bootstrapped condition
/home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:104
```
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7281/pull-gardener-integration/1610856889669652480
