### ISSUE TITLE
Do not execute irrelevant checks on certain pull requests

### ISSUE THREAD

**Issue by dimityrmirchev** [gardener/gardener#6936]
**How to categorize this issue?**

/area quality cost
/kind enhancement

**What would you like to be added**:
There are certain PRs that modify only documentation related files. There is no need to run all test suites in such cases. We can save time and computing resources by skipping the irrelevant suites in such cases. See [this](https://github.com/gardener/gardener/pull/6935) PR for example.

cc @oliver-goetz 

**Why is this needed**:
Save time and computing resources.

**Comment by oliver-goetz** [comment]
Last time I checked, there have been only very few PRs (like 3 in a quarter) which changed docs only.
If we will exclude certain files from several tests, we cannot not enforce these tests via github branch protection anymore. We should not do this for this low number of PRs.

**Comment by dimityrmirchev** [comment]
Thanks for the explanation! Feel free to close the issue if you think it is irrelevant for the time being.

**Comment by oliver-goetz** [comment]
/close
Please see [this comment ](https://github.com/gardener/gardener/issues/6936#issuecomment-1299921707)for an explanation.

**Comment by ialidzhikov** [comment]
Fixed by https://github.com/gardener/ci-infra/pull/4425
