### ISSUE TITLE
SchemaError of ProviderConfig

### ISSUE THREAD

**Issue by MSSedusch** [gardener/gardener#694]
I am trying to set up a local dev environment on Windows. I first tried with Docker for Windows and the Kubernetes version of it but it seems to be too old. I switched to minikube today and updated my local repo with the latest upstream version.

make dev-setup and make start-api are working fine from WSL but when I try to create an internal domain that is required for make start, I get the following error:

kubectl apply -f .\domain.yaml
error: SchemaError(com.github.gardener.gardener.pkg.apis.core.v1alpha1.ProviderConfig): invalid object doesn't have additional properties

The internal domain itself does not reference anything like that. Any idea why this might be failing?

Thanks

**Comment by dguendisch** [comment]
"invalid object doesn't have additional properties" is most likely caused by an outdated `kubectl`, just update it to a recent one.

**Comment by MSSedusch** [comment]
Thanks! That worked
