### ISSUE TITLE
Creation of cluster in OpenStack will fail if there is key pair with the same name

### ISSUE THREAD

**Issue by StenlyTU** [gardener/gardener#695]
Cluster in OpenStack cannot be created If in the customer account, key pair with the same name as the shoot already exist: `shoot--<project>--<shoot>`

Expected behavior:
The key pair need to be modified or deleted/recreated

**Comment by rfranzke** [comment]
We will not modify or delete existing keys. That's expected behaviour that the creation fails and an error is shown to the end-user. The existing key might be used for other critical workload.
