### ISSUE TITLE
Make MCM Timeouts Configurable 

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener#696]
Currently we are having hardcoded timeouts for the MCM[0]. Would be a good idea to have that configurable (per infrastructure).

[0] https://github.com/gardener/gardener/blob/master/charts/seed-controlplane/charts/machine-controller-manager/templates/deployment.yaml#L42-L48

**Comment by rfranzke** [comment]
See GEP-1 (#308), that will be possible with extensibility in the future. Every provider will manage its own MCM deployment (because it needs to deploy the provider-specific MCM sidecar).
We won't invest into that with the current status.
Closing this then, OK?

**Comment by afritzler** [comment]
Fine with me! Thx!
