### ISSUE TITLE
Gardener Logging stack could not properly detect whether the journald logs in /var/log/journal or /run/log/journal

### ISSUE THREAD

**Issue by vlvasilev** [gardener/gardener#6965]
**How to categorize this issue?**

/area logging
/kind bug

**What happened**:
People often complain that the `systemd` logs from SUSE machines are missing.
The `/var/lib/promtail/scripts/set_active_journal_file.sh` script as part from the `promtail` systemd service decides where on the filesystem - either from `/run/log/journal` or from `/var/log/journal` - promtail should parse the system logs. If the `/var/log/journal` exists it is preferred over  `/run/log/journal`. And, although the `/var/log/journal` dir exists then `systemd` logs are stored under `/run/log/journal`.

According to the @D060239 [investigation](https://github.tools.sap/kubernetes-live/issues-live/issues/2021#issuecomment-1487992)  the `/var/log/journal` at early boot time  existed, but was not mounted r/w, so the directory check on `/var/log/journal` during the boot process made by `journald` failed. Thus the `journald` logs to `/run/log/journal` and `promtail` looks fo those logs in /var/log/journal`.

**What you expected to happen**:
Gardener should correctly identify the logging directory for `systemd-journald` and not rely on a directory existence check.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
As a first step, let's try to duplicate the `promtail's` `journald` configuration in order to try to scrape `systemd` logs both from `/var/log/journal` and `/run/log/journal`.
**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by nickytd** [comment]
Reading through `promtail` configuration  https://grafana.com/docs/loki/latest/clients/promtail/configuration/#journal it says 
```
# Path to a directory to read entries from. Defaults to system
# paths (/var/log/journal and /run/log/journal) when empty.
```
It seems that if empty the `promtail` potentially will resolve to the correct location. Or just my hopes are too high :)
