### ISSUE TITLE
base64 on macOS doesn't recognize the w0 flag

### ISSUE THREAD

**Issue by dmahmalatsap** [gardener/gardener#7019]
While setting up a local cluster of Gardener using KinD, there was a failure at this line:
https://github.com/gardener/gardener/blob/28be93bd2860e6c8de087c5c112200be68f43150/hack/local-development/start-gardenlet#L50

Since the `base64` binary that comes with macOS doesn't support the `-w0` flag (`-b 0` is the equivalent on macOS and is already set as default behaviour), the command fails.
I got the line to work by removing `-w0` entirely, but also by adding the `-i` flag to tell it to read from the file specified in argument. The command wouldn't run without `-i`.

Maybe a check to see whether `base64 -w0` exists should be made in the script and fall back to something else if it doesn't.

**Comment by ialidzhikov** [comment]
AFAIK, `-w0` should work on macOS when GNU core utils are used. See https://github.com/gardener/gardener/blob/v1.59.1/docs/development/local_setup.md#macos-only-install-gnu-core-utilities.

**Comment by dmahmalatsap** [comment]
Works as intended then !
Once I applied the changes to my `PATH` var, the correct binaries were being used and everything compiles fine.
Thank you @ialidzhikov, closing the issue.
