### ISSUE TITLE
SKIP button in kubernetes dashboard is missing

### ISSUE THREAD

**Issue by bergerx** [gardener/gardener#703]
The SKIP button in the Kubernetes Dashboard is no more there: 
![image](https://user-images.githubusercontent.com/45531/52091985-1c3fef00-25ae-11e9-8fec-3d709a82152c.png)

We believe its because of https://github.com/kubernetes/dashboard/issues/2672

Related comment from @rfranzke in https://github.com/gardener/gardener/issues/398#issuecomment-425369182 on 28 Sep 2018:
> We hvae disabled the login in the kubernetes dashboard as it does not work properly for kubeconfigs with client certificates which we generate. You don't have to login, please just use "Skip".

Is there any other way than using the basic auth? Maybe we can add the `--enable-skip-login` flag to the Kubernetes Dashboard.

**Comment by rfranzke** [comment]
Due to security concerns we won't reintroduce the SKIP button. We have removed it for good reasons, see #555.
The Kubernetes dashboard only supports Basic Auth and JWT Token authentication, nothing else and out of our control.
