### ISSUE TITLE
Invalid Azure load balancer idle connection timeout

### ISSUE THREAD

**Issue by urabenst** [gardener/gardener#707]
Since Kubernetes 1.12 it is possible to adapt the Azure load balancer idle connection timeout for services. It is currently set to 60 minutes which unfortunately is an invalid value:

`Warning  CreatingLoadBalancerFailed  4m (x9 over 19m)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service shoot--dev--urshoot/kube-apiserver: idle timeoutvalue must be a whole number representing minutes between 4 and 30` (from `kubectl describe service kube-apiserver -n shoot--dev--urshoot`)

Hence, I currently can't create shoot clusters on Azure, since the load balancer doesn't receive an external IP. Can we simply reduce the value to 30 minutes?

**Comment by rfranzke** [comment]
Great!, thank's for finding that! We have not yet run Azure seeds in v1.12, that's why we didn't face the issue ourselves yet.
