### ISSUE TITLE
Unify and improve shoot system components handling

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#7104]
**How to categorize this issue?**

/area robustness
/area usability
/kind enhancement

**What would you like to be added**:
Whenever users specify a worker pool with `shoot.spec.provider.pools[].systemComponents.allow: true`, related components should be scheduled onto these nodes even when custom and additional taints are specified.

Gardener will need https://github.com/gardener/gardener/issues/7103 in order to accomplish this task. Custom taints are read from the shoot spec and added to the webhook's configuration. It'll then wait until GRM is rolled out before the taints are added to the worker nodes.

In addition, it adds the required node selector to the webhook config as well. This is will make it easier for extension developers because they don't need to care about putting the selectors to their components, the webhook will take over this job.

**Why is this needed**:
Today, users can specify their worker pools to allow system component but can lock them out at the same time by adding custom taints to the nodes. System components should run on these nodes, even if misconfigured.

**Comment by timebertt** [comment]
What is tracked in this issue in addition to https://github.com/gardener/gardener/issues/7103?

**Comment by timuthy** [comment]
Let's continue with #7103 which now contains both aspects.
/close
