### ISSUE TITLE
DNS uniqueness validation blocks shoot deletion

### ISSUE THREAD

**Issue by dguendisch** [gardener/gardener#7130]
**How to categorize this issue?**
/area ops-productivity
/kind bug

**What happened**:
https://github.com/gardener/gardener/pull/7086 removed the DNS uniqueness validation for `DELETE` operations to be able to get rid of shoots that were tried to be created with non-unique DNS domains.
However we have still shoots in place for which we cannot add the annotation `confirmation.gardener.cloud/deletion: "true"` before trying to execute the `DELETE` operation.

**What you expected to happen**:
Shoots failing the DNS uniqueness validation should be able to be deleted which requires to annotate them with `confirmation.gardener.cloud/deletion: "true"`, hence the DNS uniqueness validation should be skipped for this annotation as well.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create two shoots with non-unique DNS names
2. Try to annotate one of them with `confirmation.gardener.cloud/deletion: "true"`

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by shafeeqes** [comment]
/assign
Do we have to check for this annotation update particularly, or we just skip the check if spec hasn't changed between old and new Shoot?

**Comment by rfranzke** [comment]
> or we just skip the check if spec hasn't changed between old and new Shoot?

This sounds reasonable 👍🏻
