### ISSUE TITLE
`BackupEntry` sometimes does not get migrated to the destination `Seed` during control plane migration.

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#7139]
**How to categorize this issue?**

/area control-plane-migration
/kind bug

**What happened**:
During the migrate step of control plane migration, the `.spec.seedName` of the `Shoot`'s `BackupEntry` is changed to point to the `Seed` to which the `Shoot`'s control plane is being migrated: https://github.com/gardener/gardener/blob/9f13d07f23ebe459b4d2309281bf688ade7648ee/pkg/gardenlet/controller/shoot/shoot_control_migrate.go#L349-L358

However, for hibernated `Shoot`s it seems that sometimes the `.spec.seedName` is not properly changed before the restoration phase begins and it fails with the following error:
```
task "Deploying source backup entry" failed: admission webhook "seed-restriction.gardener.cloud" denied the request: specification of source BackupEntry must equal specification of original BackupEntry shoot--it--tmf89-5vg-hs-mgr--f38c4921-1b70-4e83-a18f-c7e8a382cd7f
```
More specifically, the error happens because the special source `BackupEntry` that is deployed during the restoration phase  is deployed with its `spec.seedName` equal to the destination `Seed`, and therefore differs with the `spec.seedName` in the original `BackupEntry`.

**What you expected to happen**:
The `spec.seedName` of the `BackupEntry` to be updated properly and migration to finish without problems.

**How to reproduce it (as minimally and precisely as possible)**:
I still do not know what the steps are to reproduce this issue, as it occurs very rarely. However, I have noticed that it is happening to hibernated `Shoot`s

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.60.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by plkokanov** [comment]
This could potentially be caused by the forceful shoot migration controller: https://github.com/gardener/gardener/blob/master/pkg/gardenlet/controller/shoot/migration/reconciler.go which forces the restoration phase to begin without waiting for the migration phase to finish. I'll investigate further.

/assign

**Comment by plkokanov** [comment]
It seems that it is indeed the shoot migration controller that is responsible for this. There are a few cases that it might force the restoration phase before migration phase has finished (basically triggering "bad case control plane migration") when we would not want it to:

1. During the migration phase, if a `Shoot` is hibernated it can happen that some components cannot be woken up and can be stuck in `Pending` state or `ContainerCreation` state.
2. The destination seed might not be ready, which will interrupt the migration phase here: https://github.com/gardener/gardener/blob/c27f04381ed66237c747caa159c2a3cc17fbefdb/pkg/gardenlet/controller/shoot/shoot/reconciler.go#L164-L166
If the destination `Seed` does not become ready before the [`Shoot` migration controller grace period](https://github.com/gardener/gardener/blob/c27f04381ed66237c747caa159c2a3cc17fbefdb/example/20-componentconfig-gardenlet.yaml#L86) has expired, the shoot migration controller will forcefully start the restoration phase on the destination `Seed`.

In both of those cases and probably other similar ones, we actually would not want the shoot to be forcefully migrated and instead have an operator to resolve the issues so that normal control plane migration can take place. If the shoot is forcefully migrated, there will be an orphaned control plane namespace in the source shoot left over. This can cause problems now that we are also removing the owner checks.

I'm thinking about removing the shoot migration controller (and backupentry migration controller) as they probably do more harm then help, now that we are also removing the owner checks. /cc @timebertt and @rfranzke as you might also have an opinion on this.

**Comment by rfranzke** [comment]
I am not into the details, but I indeed don't see any reason to keep this code for longer if we anyways planned to drop it eventually. The force restoration is behind an alpha feature gate, so it should be fine to just drop everything now before it causes even more harm.

**Comment by timebertt** [comment]
+1
