### ISSUE TITLE
Prevent deleting gardener APIServices in non-local environment during local setup

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7142]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement

**What would you like to be added**:
Every now and then people execute `make dev-setup` against non-local environment and break the corresponding environment for example by deleting the APIServices.
We should check how to prevent that:
- check if the `hack/local-development/dev-setup-register-gardener` script can be enhanced to do not delete the APIServices? Do update/apply of dev-setup APIServices break the remote ones?
- add deletion protection for the gardener APIServices?
- other?

**Why is this needed**:
Prevent breaking a running non-local environment by someone who targets this env in his local setup.

**Comment by nschad** [comment]
I don't see how this could happen to anyone

</irony>
