### ISSUE TITLE
Add vertical pod autoscaler into seed.

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener#715]
Prometheus has had trouble in the past with scaling. The vertical pod autoscaler can alleviate some of these issues. I propose adding the VPA behind a feature gate. The VPA consists of 3 components:
* vpa-admission-controller
* vpa-recommender
* vpa-updater

These components would run in the garden namespace of the seed. Along with these components a VPA CRD will be created. Then it will be possible to create a VPA object. The VPA has a pod selector and will make recommendations based on that pods usage. 

Any suggestions/ideas for integrating this into the gardener? @rfranzke @adracus @dkistner

**Comment by rfranzke** [comment]
Are you aligned with @amshuman-kr @georgekuruvillak @swapnilgm that are working on VPA for etcd?
