### ISSUE TITLE
[GRM] ManagedResource deletion flow to ignore "garbagecollectable" resources only if they are secret or configmap

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#7156]
**How to categorize this issue?**

/area usability 
/kind bug

**What happened**:
I had deleted a managed resource and its deletion was successful, though almost all referenced resource were orphaned and never deleted. The reason is that the deletion flow of ManagedResource ignores any resource that has the metadata classifying it as garbagecollectable (not only secrets and configmaps), ref:
https://github.com/gardener/gardener/blob/0d37c8a33483d8e497a0f79dc70f38a0aeecfd57/pkg/resourcemanager/controller/managedresource/reconciler.go#L699-L703

On the other side, the garbage collector cleans-up only secrets and configmaps, refs:
https://github.com/gardener/gardener/blob/0d37c8a33483d8e497a0f79dc70f38a0aeecfd57/pkg/resourcemanager/controller/garbagecollector/reconciler.go#L69-L70 and https://github.com/gardener/gardener/blob/0d37c8a33483d8e497a0f79dc70f38a0aeecfd57/pkg/resourcemanager/controller/garbagecollector/reconciler.go#L148-L155

**What you expected to happen**:
GRM to not leak "garbagecollectable" resources like Deployments, VPAs, PDBs, etc.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a managed resource that deploys a PDB labeled with `resources.gardener.cloud/garbage-collectable-reference=true`. 
2. Delete the MR
3. Make sure that the PDB is never deleted.

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
Just to get the full picture: In which scenario would you add this label to anything other than Secret/ConfigMap?

**Comment by vpnachev** [comment]
It was a mistake on my side to put the label on other resources, but it would be nice the GRM to consider the label only if it is applied to secrets and configmaps.
