### ISSUE TITLE
Unable to create internal LoadBalancer on GKE

### ISSUE THREAD

**Issue by freegroup** [gardener/gardener#716]
Hi,
 
Unfortunately I’m unable to create an internal LoadBalancer on GKE. The reason for this
Seems to be the missing feature to name a subnet in the Service-Resource.
 
https://github.com/kubernetes/kubernetes/issues/60665
 
As mention in the ticket, it is possible to fix it by add some parameters to the kube-controller.
Did we have this already?
 
This feature is heavy required for a kind of cluster federation without expose some 
critical endpoints to the internet.
 
It seems that there is no annotation available for this purpose
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce_annotations.go
 
I this case a the configuration of the kube-controller is required.

 
 ```
$> k describe service external-kubedns-udp -n kube-system
Name:                     external-kubedns-udp
Namespace:                kube-system
Labels:                   <none>
Annotations:              cloud.google.com/load-balancer-subnet: shoot--cpet--mesh-gcp-nodes
                          cloud.google.com/load-balancer-type: Internal
                          kubectl.kubernetes.io/last-applied-configuration:
                            {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.google.com/load-balancer-subnet":"shoot--cpet--mesh-gcp-nodes","clou...
Selector:                 k8s-app=kube-dns
Type:                     LoadBalancer
IP:                       100.95.110.160
IP:                       10.127.0.3
Port:                     dns  53/UDP
TargetPort:               8053/UDP
NodePort:                 dns  32399/UDP
Endpoints:                100.64.0.6:8053
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                      Age   From                Message
  ----     ------                      ----  ----                -------
  Normal   EnsuringLoadBalancer        36s   service-controller  Ensuring load balancer
  Warning  CreatingLoadBalancerFailed  1s    service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service kube-system/external-kubedns-udp: googleapi: Error 400: Invalid value for field 'resource.subnetwork': ''. Network interface must specify a subnet if the network resource is in custom subnet mode., invalid
SAP-Laptop:kube-https d023280$ (shoot--cpet--mesh-gcp)
```

**Comment by rfranzke** [comment]
@marwinski @DockToFuture @zanetworker 
What would be the side effects when we would add `subnetwork` to the GCE cloud provider config?

**Comment by DockToFuture** [comment]
So far we have no side effects, when enabling internal loadbalancers on gcp. We could use our existing node-subnet: ```subnetwork-name="shoot--<namespace>--<name>-nodes"``` to take the ips from that range for the ilbs if no seperate ip-range is required.

**Comment by freegroup** [comment]
I just saw that it is not possible to share an internal LB across different regions.
https://issuetracker.google.com/issues/111021512

Internal LB is still a good feature for some use cases....but I paste the ticket to inform other user that
this feature has some limitations.

**Comment by DockToFuture** [comment]
Yes they are bound to their regions and we absolutely should enable them, @zanetworker @marwinski shall we use the node subnet or create a separate one. WDYT?

**Comment by rfranzke** [comment]
What would be the rationale behind creating a separate one?

**Comment by zanetworker** [comment]
@DockToFuture maybe we can divide up the node subnet into two smaller subnets namely -> nodes and LBs, WDYT?

**Comment by DockToFuture** [comment]
Sounds good, I will create a PR.

**Comment by vlerenc** [comment]
Thanks all!
