### ISSUE TITLE
Drop `nginx-ingress` load balancer in favor of `Istio`

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#7232]
**How to categorize this issue?**

/area dev-productivity networking
/kind enhancement

**What would you like to be added**:
The gardenlet's seed controller can deploy `nginx-ingress` as `Ingress` controller into the `garden` namespace. This is used to expose the observability components (Prometheus, Grafana, Loki, Alertmanager). However, we already deploy `Istio` as well into the seeds to expose the shoot API servers.

Let's drop `nginx-ingress` load balancer and use `Istio` instead for exposing the `nginx-ingress` instead.

**Why is this needed**:
Less public endpoints to maintain.

**Comment by shafeeqes** [comment]
nginx-ingress controller has many features based on annotations, [ref](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/), which are not present in Istio, or at least I couldn't find any documentation pointing to it.
We can use the Istio resources (gateway, virtualservices, destinationrules etc.) for the monitoring components as well.
It'd be better if we do the switch in steps, like switching shoot components first, then seed, and then finally dropping the nginx controller.
I and @acumino will jointly work on this.
/assign @acumino 
/cc @ScheererJ

**Comment by ScheererJ** [comment]
Using a solution purely based on kubernetes `Ingress` would have been simpler, but it turns out that `Ingress` is not a first class citizen in the istio environment. This is why we changed to targeting native istio components.

**Comment by rfranzke** [comment]
FYI @petersutter

**Comment by acumino** [comment]
Did some digging with @shafeeqes, posting the summary here:
Using ingress is not preferred by the community. In this https://github.com/istio/istio/issues/42985 issue, while trying to manage more than 3 ingress objects Istio starts having issues.
Also, it is suggested here https://github.com/istio/istio/issues/42985#issuecomment-1403842819 that support for Ingress is not really good and Gateway/Virtual-Service should be preferred.

Here are the things that are needed, to expose observability components:
- For each service, a `Gateway`, `Virtual-Service`, and `DestinationRule` Istio resources are required to be created in the `Shoot` namespace in `Seed`.
- For enabling `tls` for each service a `tls` secret needs to be present in `istio-ingress` namespace. 
- Network policies are required to allow communication between istio-ingressgateway and that service.
- We can use a common DNSRecord `*.oberservabiity.<seed-name>.seed.example.com` for observability components of all shoots in the seed.

This will give a running service without the authentication enabled. 
To enable authentication `RequestAuthentication` and `AuthorizationPolicy` Istio resources are required per service in the shoot namespace in the seed. Istio supports `JWT` based authentication with a custom authentication provider or any OpenID Connect providers.

Any feedback is welcome.

**Comment by ScheererJ** [comment]
@acumino Did you use an existing port on istio or added a new one? The reason for asking is that in the past monitoring resources where exposed via a default port (443). However, the default https port is already in use and configured for the SNI kube-apiserver access. I am not sure if we can easily configure istio to do both on the same port.
WDYT?

**Comment by shafeeqes** [comment]
We actually tried with a different port `8421` (just a random one) for testing.

**Comment by rfranzke** [comment]
TBH, this all sounds very complicated from the user's perspective (`gardenlet`) compared to what happens today (`Ingress` from `nginx-ingress` vs. `Gateway`, `VirtualService`, `DestinationRule` and TLS secrets scattered in some namespaces.

Also, what would be the strategy to move away from the basic auth credentials towards the JWT token/OIDC-based auth?

Generally, my personal impression is that it would be easier to not move to `Istio`.

**Comment by donistz** [comment]
>move away from the basic auth credentials towards the JWT token/OIDC-based auth

@shafeeqes and @acumino  Such "move" will require also a solution for permissions management. When there is basic auth credentials are anonymous and can be shared with limited list with users (like with the current implementation - they are shared with the project members who have permissions to see the secrets) while with JWT token/OIDC you need to ensure that only the members of the project will be able to see/edit the data and not the entire list of users known by the trusted provider.

**Comment by oliver-goetz** [comment]
I share @rfranzke opinion. Considering all the given circumstances, moving from `nginx` to `Istio` would introduce more complexity than it reduces.

**Comment by rfranzke** [comment]
We agreed to not continue working on this item since the complexity it brings is not worth the value.
/close

**Comment by rfranzke** [comment]
This is still something we want to pursue eventually when there is capacity, so let's
/reopen
the issue. It makes sense to get rid of `nginx-ingress` and only have one ingress controller in garden and seed clusters.

**Comment by rfranzke** [comment]
/assign @ScheererJ 

Note: When this issue gets closed, we can probably also close https://github.com/gardener/gardener/issues/6517 and archive https://github.com/gardener/ingress-default-backend.

**Comment by ScheererJ** [comment]
Current plan with regards to dropping `nginx-ingress` controller in favor of `Istio` after further analysis:
- Drop usage of `Ingress` and move to `Istio` resources (`Gateway`, `VirtualService` and `DestinationRule`), mostly due to `Ingress` not being first class citizen in the `Istio` community, e.g. https://github.com/istio/istio/issues/42985
- Move TLS termination to observability components similar to how `kube-apiserver` is handled via `Istio`
  - This implies that the currently used basic authentication is also moved to the individual observability components

**Comment by ScheererJ** [comment]
After analysis of PR #8621 and further discussion, it was decided to NOT drop `nginx-ingress`, but to drop its loadbalancer. This means that
- `nginx-ingress` should be exposed via `istio`.
- The observability components will continue to use `ingress` resources.
- The `kube-apiserver` ingress should be replaced via direct `istio` exposure.

The main reasons for moving away from the previous approach are the following:
- Observability credentials would be exposed via `VirtualService` resources, which can be a problem in case custom resources are not encrypted in `etcd`. The alternative option of an external authorisation service would increase complexity.
- The `istio` solution was deemed more complex than the `ingress` solution as it requires multiple custom resources.
