### ISSUE TITLE
Enable the use of flexvolumes

### ISSUE THREAD

**Issue by thomasdraebing** [gardener/gardener#725]
Hi,

currently it is not possible to use Rook [1], because the directory configured in the kubelet to store flexvolume drivers is not writable (by default: `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/`). The documentation of Rook suggests to use `/var/lib/kubelet/volumeplugins` as an alternative [2]. Configuring this path for the Rook operator, allowed Rook to create the flexvolume drivers correctly, but since the Kubelet was not configured accordingly, the volumes were not provisioned to the requesting pods.

This issue appeared, when I tried to use Rook to provision Ceph-volumes on a shoot cluster running on AWS.

This could be solved, by adding/changing the following parameter in the Kubelet configuration: `--volume-plugin-dir=/var/lib/kubelet/volumeplugins`.

Best Regards,
Thomas

[1] https://rook.io/
[2] https://rook.io/docs/rook/v0.9/flexvolume.html#platform-specific-flexvolume-path

**Comment by thomasdraebing** [comment]
@georgekuruvillak As discussed I created this issue following our discussion via email.

**Comment by thomasdraebing** [comment]
Is there any progress on this issue?
If you could give me some pointers on where parameters for the kubelet are added in the Gardener source-code, I would also give it a try.

**Comment by rfranzke** [comment]
No progress yet.
https://github.com/gardener/gardener/pull/853/files is a perfect example for what needs to be done (new parameter that allows to configure the path, and actual transportation of the configuration to the kubelet).

**Comment by rfranzke** [comment]
@thomasdraebing do you still plan to implement this/need this? If not, shall we close the ticket?

**Comment by thomasdraebing** [comment]
We are currently not needing this anymore and I am too busy with other things right now to implement it, so please go ahead and close this ticket.
