### ISSUE TITLE
[Flaky Test] E2E Gardener Test Suite

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#7266]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
The Create, Hibernate, Wake up and Delete Shoot e2e test failed when checking that no `Pod`s exist in the shoot control plane namespace:

```
E2E Gardener Test Suite: [It] Shoot Tests Create, Hibernate, Wake up and Delete Shoot [Shoot, default] expand_less | 11m31s
-- | --
{Expected     <bool>: true to be false failed /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/create_and_delete_hibernated.go:59 github.com/gardener/gardener/test/e2e/gardener/shoot.verifyNoPodsRunning({0x24149c8, 0xc00044ec60}, 0xc0006bfc80) 	/home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/create_and_delete_hibernated.go:59 +0x217 github.com/gardener/gardener/test/e2e/gardener/shoot.glob..func4.1() 	/home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/create_hibernate_wakeup_delete.go:43 +0x16f}
```

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7204/pull-gardener-e2e-kind/1605927500741873664

**Comment by rfranzke** [comment]
Two ideas from our sync:
- improve error message to list the pods that are still existing
- maybe some pods were in `Terminating` state and took too long for getting removed

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7326/pull-gardener-e2e-kind/1614869969550446592

**Comment by rfranzke** [comment]
/close
Let's reopen it in case we see it again with more information for debugging.
