### ISSUE TITLE
`BackupEntry` issues with credential rotation

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#7276]
**How to categorize this issue?**

/area control-plane
/area security
/kind bug

**What happened**:
The backup credentials for a seed cluster were rotated but after the old account was deactivated, some shoots faced issues because the `etcd-backup-restore` side-car still used the expired account.

```
time="2022-12-29T15:10:12Z" level=error msg="Failed initialization: error while initializing: unable to get snapshots from store: Get \"https://www.googleapis.com/storage/v1/b/xyz/o?alt=json&delimiter=&pageToken=&prefix=foo%2Fetcd-main&prettyPrint=false&projection=full&versions=false\": oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"Invalid JWT Signature.\"}" actor=backup-restore-server
```

Situation:
- All shoot clusters were already reconciled successfully after the old account was deactivated.
- The `BackupEntry` secrets in the seed already received that updated account information.
- The `etcd-backup` secret in the shoot control plane namespaces still had the **old account information**.

There are some optimizations in https://github.com/gardener/gardener/blob/387a2cca9683ec2ffdaa3cb0e6c67f46613d343a/pkg/gardenlet/controller/backupentry/backupentry/reconciler.go#L130 which let the controller skip the reconciliation of the `BackupEntry` resource in the seed.
Presumably, after the secret was synced [here](https://github.com/gardener/gardener/blob/387a2cca9683ec2ffdaa3cb0e6c67f46613d343a/pkg/gardenlet/controller/backupentry/backupentry/reconciler.go#L168), Gardenlet was restarted and since then [this condition](https://github.com/gardener/gardener/blob/387a2cca9683ec2ffdaa3cb0e6c67f46613d343a/pkg/gardenlet/controller/backupentry/backupentry/reconciler.go#L163) has led to exiting the reconciliation prematurely. 

**What you expected to happen**:
`etcd-main` not to have any issues after backup credentials rotation.

**Environment**:

- Gardener version: `v1.62.0`

**Comment by timuthy** [comment]
/cc @shafeeqes @plkokanov
Do we really need the optimizations to not reconcile the `BackupEntry` resource in the seed or can we easily drop them to circumvent the mentioned issue?

**Comment by shafeeqes** [comment]
If we don't do this optimization, and reconcile the extension `BackupEntry` every single time, this will cause an endless loop since we now have a watch for this extension status change, and the status change from `Processing` to `Succeeded` will invoke our reconciler.
What I can immediately think of is using a timestamp annotation in the seed secret on modification and if the lastUpdate time of the extension is older than this, we reconcile it. 
Open for better ideas.

**Comment by timuthy** [comment]
Thanks for explaining @shafeeqes. Well then yes, the timestamp approach should work. Alternatively, the `BackupEntry` resources needed to report the last seen generation of the referenced secret.
