### ISSUE TITLE
Restructure healthcheck ports to enable `skaffold debug`

### ISSUE THREAD

**Issue by briantopping** [gardener/gardener#7284]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement

**What would you like to be added**:
Debugging in Delve via Skaffold is actually pretty close to working. Skaffold runs debuggers via support containers, which include additional executable and configuration material for specific language environments (golang, JVM, etc). In the case of Golang (maybe others), Skaffold rewrites the deployment descriptor for the target container so the target container is launched as a sidecar to the Delve support container. An critical aspect of this rewriting ports exposed by the target/sidecar.

It is apparently a common pattern that healthcheck resources are a path on an existing container HTTP port instead of separate ports. When this is true, the ports don't need to be explicitly handled. The ports are rewired and the path stays the same. The healthcheck pattern inside Gardener configures additional ports in a lookaside configuration. Skaffold isn't able to parse this deeply and when the container is started, the configured healthcheck fails, shutting down the container. 

**Why is this needed**:
Fixing this will allow the Gardener stack to be debugged in the IDE with a single command.

/assign briantopping

**Comment by oliver-goetz** [comment]
@briantopping: I'm wondering whether this is still an issue with skaffold v2.2.0, because I did not face problems with killed pods when enabling debugging in #7755.

**Comment by rfranzke** [comment]
Probably not in the light of #7755, so perhaps we can close this issue?

**Comment by briantopping** [comment]
Yes that's fine. Oliver was asking me about this the other day, I ended up with COVID last week and this week has been catch up. 

I'm pretty agnostic to the solution since I didn't invest in one here. 😀
