### ISSUE TITLE
Configure extension providers for Skaffold

### ISSUE THREAD

**Issue by briantopping** [gardener/gardener#7285]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement

**What would you like to be added**:
In the last year, Skaffold has been extensively supported to encapsulate the developer build/deploy cycle for lightweight local runs. #7284 will enable debugging of these configurations, allowing the full Gardener stack to be debuggable from within an IDE that supports Delve. This is easily managed via the Google Cloud Code IDE extensions.

The last piece of this is to create configurations for each extension provider in their respective repositories. Create a `skaffold.yaml` in each provider repository that chains to the g/g Skaffold configuration, allowing evaluators and developers to more quickly bootstrap and debug a local deployment. 

Work has been started on this in #7247 so that the extension providers can use the `kind-up.sh` script in g/g. Once that's released in 2213a, work in the vSphere extension can be propagated to the other extensions. 

**Why is this needed**:
When complete, a user will be able to download an extension provider repository, add credentials and bootstrap a running environment with a few command line commands, or maybe only `make kind-up gardener-up`. This will significantly lower the barrier to entry for new users and evaluators. 

/assign

**Comment by timuthy** [comment]
Isn't this closely related to https://github.com/gardener/gardener/pull/6678 which tackled the requirement rather in `gardener/gardener` instead of adjusting the extensions.

**Comment by briantopping** [comment]
Yes it is. I wasn’t aware of that effort and solved it separately. I think it might be worth considering both methods, but for now just want to help that effort by contributing the fix for debugging containers with Delve.

**Comment by timuthy** [comment]
Thanks @briantopping, sounds good 🙂 
We talked with @oliver-goetz that it would also be nice to extend the current setup by supporting multiple seeds and thus multiple providers at the same time. Maybe you can also support here whenever you have capacity or maybe have a good idea how to bring the pieces together.

**Comment by briantopping** [comment]
Absolutely! It may be that both approaches are valuable if they don't require significant additional maintenance. I see now how the multiple seeds scenario is difficult with the extension-centric launch setup I have been building. On the other hand, it is much simpler for an evaluator of a specific extension to run the seed they are specifically interested in when all the chart specifics are already worked out in `~/example`. I am wondering if there is a good way to normalize the charts across providers so they can be used transparently in both deployment scenarios. 

Improving the onboarding experience is something we've all been after for a long time, this is super exciting to be a part of it.
