### ISSUE TITLE
[Flaky Test] Shoot Migration Controller Integration Test Suite

### ISSUE THREAD

**Issue by acumino** [gardener/gardener#7286]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
• [FAILED] [5.052 seconds]
Shoot migration controller tests
/home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/shoot/migration/migration_test.go:32
  [It] should update the Shoot status to force the restoration if grace period is elapsed
  /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/shoot/migration/migration_test.go:153
```

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7267/pull-gardener-integration/1610653410267238400

**Reason for failure**:

**Anything else we need to know**:

**Comment by rfranzke** [comment]
Does it make sense to invest into this one? @plkokanov IIUC your plan is to remove these migration controllers for `BackupEntry` and `Shoot` anyways, or?

**Comment by plkokanov** [comment]
Yes the plan was to remove those controllers as we observed that they can do harm. And anyway the addition of the `shoot.gardener.cloud/force-restore` annotation should only be done manually now. So let's remove the controllers instead of fixing the flakes.
