### ISSUE TITLE
Clean up technical debt in defaulting code and unit tests

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#7312]
**How to categorize this issue?**

/area dev-productivity
/kind technical-debt

**What would you like to be ~~added~~ cleaned up**:

As a follow-up to https://github.com/gardener/gardener/pull/7288#discussion_r1065777461, we should clean up the following technical debt in our defaulting code and unit tests:

- extract defaulting code and unit tests into dedicated files (like the dedicated `types_*.go` files)
- testing the overall defaulting function instead of testing defaulting functions for individual sections
- refactoring the defaulting code to `SetDefaults_*` functions (as they are supposed to be structured) instead of defaulting everything in the top-level defaulting function

I performed the changes for the `v1beta1.Project` defaulting as an example: https://github.com/gardener/gardener/compare/master...timebertt:gardener:tech-debt-defaults-project
These steps would need to be performed for all API groups, versions, and kinds.

**Why is this needed**:

Code and unit tests of our API defaulting are inconsistently structured. Hence, adding new defaulting logic is not as straightforward as it should be.
Cleaning up technical debt in this area will ease maintenance and addition of new features, and ensure we are testing the right thing in our unit tests to prevent regressions.

**Steps**:

- [x] `authentication.gardener.cloud` API group https://github.com/gardener/gardener/pull/8701
- [x] `core.gardener.cloud` API group
  - [x] https://github.com/gardener/gardener/pull/7357
  - [x] https://github.com/gardener/gardener/pull/8696
- [x] `seedmanagement.gardener.cloud` API group https://github.com/gardener/gardener/pull/9033
- [x] `settings.gardener.cloud` API group https://github.com/gardener/gardener/pull/8764
- [x] `admissioncontroller.config.gardener.cloud` API group https://github.com/gardener/gardener/pull/8916
- [x] `controllermanager.config.gardener.cloud` API group https://github.com/gardener/gardener/pull/8978
- [x] `resourcemanager.config.gardener.cloud` API group https://github.com/gardener/gardener/pull/8953
- [x] `gardenlet.config.gardener.cloud` API group https://github.com/gardener/gardener/pull/8985
- [x] `scheduler.config.gardener.cloud` API group https://github.com/gardener/gardener/pull/8832
- [x] `operator.config.gardener.cloud` API group https://github.com/gardener/gardener/pull/9001.
- [x] Document the followed conventions https://github.com/gardener/gardener/pull/9122

**Comment by timebertt** [comment]
Tackling https://github.com/gardener/gardener/issues/7358 first would reduce the effort of this work stream a bit.

**Comment by rfranzke** [comment]
Does anybody plan to continue with this issue?

**Comment by timebertt** [comment]
I still have this on my list. With very low priority though.
If anybody else wants to pick this up, feel free to do so and comment here beforehand :)

**Comment by rfranzke** [comment]
Thanks for all the PRs! So, only documentation is missing, right @ary1992 @Kostov6? Who will take this? :)

**Comment by ary1992** [comment]
> Thanks for all the PRs! So, only documentation is missing, right @ary1992 @Kostov6? Who will take this? :)

I am on it

**Comment by shafeeqes** [comment]
All tasks are completed.
/close
