### ISSUE TITLE
[Flaky Test] E2E Operator Suite

### ISSUE THREAD

**Issue by acumino** [gardener/gardener#7334]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
Garden Tests [Garden, default]
/home/prow/go/src/github.com/gardener/gardener/test/e2e/operator/garden/create_rotate_delete.go:32
  [It] Create Garden, Rotate Credentials and Delete Garden [credentials-rotation]
  /home/prow/go/src/github.com/gardener/gardener/test/e2e/operator/garden/create_rotate_delete.go:38
```

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7332/pull-gardener-e2e-kind-operator/1614993857328451584

**Reason for failure**:

**Anything else we need to know**:

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7336/pull-gardener-e2e-kind-operator/1615160527934197760

Note that the flakes seem to have appeared after #7225, i.e. after ETCD runs in HA mode. cc @shreyas-s-rao @abdasgupta @ishan16696

**Comment by rfranzke** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7336/pull-gardener-e2e-kind-operator/1615248036244492288

**Comment by timuthy** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7397/pull-gardener-e2e-kind-operator/1618910353347842048

**Comment by ialidzhikov** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7428/pull-gardener-e2e-kind-operator/1621049866824192000

**Comment by acumino** [comment]
Another one: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7399/pull-gardener-e2e-kind-operator/1622932423517933568
