### ISSUE TITLE
Drop `core/v1alpha1` API version

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#7358]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement

**What would you like to be ~~added~~ removed**:

The `core/v1alpha1` API version.

**Why is this needed**:

Most types and code is duplicated between `core/v1alpha1` and `core/v1beta`, not consistently though.
Having two versions of the main API group increases the effort for introducing new API fields/validation/defaulting.
Maintaining both versions seems like a worthless effort, given that the API versions don't drift and there has been more than enough time to upgrade clients to `v1beta1`.

**Comment by rfranzke** [comment]
@ary1992 expressed interest in working on this one as soon as capacity allows.

**Comment by timebertt** [comment]
We probably need to promote the `ShootState` and `ExposureClass` resources to `v1beta1` as a first step as they are only available in `v1alpha1`, currently.

**Comment by ary1992** [comment]
I will be working on promoting the `ShootState` and `ExposureClass` resource to v1beta1.
/assign

**Comment by rfranzke** [comment]
We will wait for the release of `v1.68` and drop the `core.gardener.cloud/v1alpha1` API beginning with `v1.69`.

**Comment by rfranzke** [comment]
@ary1992 I think we can go ahead and continue with this story.
