### ISSUE TITLE
Webhook remediator not removing annotation automatically

### ISSUE THREAD

**Issue by dimakow** [gardener/gardener#7371]
**How to categorize this issue?**

/area control-plane
"/kind" identifiers:     enhancement

**What would you like to be added**:
The [webhook remediator](https://github.com/gardener/gardener/blob/2868508f994821c68fc37289aa97b49d43b856dc/pkg/operation/care/webhook_remediation.go) currently adds an annotation to a webhook once a webhook definition is found which has no timeout set. The annotation reminds the customer of Gardener to remove the annotation when he has followed the best practises mentioned. This pattern of manually removing annotations does not scale and is also from security perspective not recommendable. Instead, the webhook remediator should follow the reconcile pattern and remove the annotation if the trigger condition is not existing anymore.

**Why is this needed**:

Scalability and security reasons

**Comment by ary1992** [comment]
The main motivation towards adding the annotation to webhook was to first remediate the webhook and mention the remediaitions as an annotation to inform the end users regarding the problematic webhook, its remediation steps and best practice associated with the webhook. It was expected from user to fix the configuration from there side and remove the annotation after the fix.
- Removing the annotation means, user will not be aware of the changes made to the webhook and hence might miss to make the configuration changes on there side. Which can again lead to same problematic webhook at later point of time.
- If we proceed with the annotation, then what should be the apt time to remove the annotation by reconciler? Should it be removed in the next phase of reconciliation when the webhook was remediated by gardener itself and now the webhook is no longer problematic? In this scenario how we will be sure that the correct configuration was also adapted on the user side.

**Comment by rfranzke** [comment]
@ary1992 I think your reply is a bit confusing - the gist of it is

> In this scenario how we will be sure that the correct configuration was also adapted on the user side.

When looking at the webhook configurations in the cluster, we cannot know whether a "no-longer-problematic-webhook" was fixed by the end-user, or whether it was just remediated by our code. This was also the reason why automatic removal of the annotation was not implemented and expected from the user instead.

@dimakow Thoughts?

**Comment by dimakow** [comment]
Hi @ary1992  @rfranzke ,

thanks for the explanation. I guess that we need to discuss this further. You want the user to edit some annotation which Gardener is setting because you would like to enforce a certain value. While I understand the reason behind the enforcement (safeguard controlplane), I think this can and should be done actually in two steps.

1. Add an annotation if no timeout is set on a webhook - this gives customers time to adjust their external artifacts and would also allow for an automatic removal of the annotation
2. At a certain point, have a ValidationWebhook reject Webhooks without a timeout set

Your thoughts @rfranzke ?

**Comment by rfranzke** [comment]
We discussed this approach before implementing today's webhook remediation solution. Unfortunately, you cannot have webhooks for webhooks [1] [2]. Hence, it wasn't possible to implement it this way.

As a consequence, this mean that your "step 2" must be translated to

> 2. At a certain point, have ~~ValidationWebhook reject~~ a controller which remediates Webhooks without a timeout set

This is exactly what we do today and brings us back to square one. 

[1] https://github.com/kubernetes/apiserver/blob/d50444613bc690d073d21c10702fb767746ef832/pkg/admission/plugin/webhook/generic/webhook.go#L222-L224
[2] https://github.com/kubernetes/apiserver/blob/19d202d87cbe4bc94c7ffe6857b1c379373963da/pkg/admission/plugin/webhook/predicates/rules/rules.go#L119-L129

**Comment by rfranzke** [comment]
Any more thoughts/comments/suggestions? Otherwise, I'd propose to close this issue.

**Comment by dimakow** [comment]
Hi Rafael,

what speaks against simply indicating on the cluster status that a problematic webhook is found and needs attention?

Regards, Dirk

**Comment by rfranzke** [comment]
The ignorance of the users, I guess :) We were reporting about "problematic webhooks" for a long time via `.status.constraints` in the `Shoot`s, but not many people cared about it. Still, these things often led to ops effort, especially at scale with a lot of clusters. This finally made us implement the automatic webhook remediation.

**Comment by vlerenc** [comment]
Given @rfranzke explanation that we cannot know whether the "original" web hook was fixed, is that actually/really an issue for you guys after you have updated your stencils/templates? "Run a script" and you are done, because if your stencils/templates are changed, it won't pop up again?

**Comment by rfranzke** [comment]
I guess there is not much to add/do here, let's
/close
this issue for now.
