### ISSUE TITLE
Show available/unavailable/updated replicas for the istio-ingressgateway and istiod Deployment

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7387]
**How to categorize this issue?**

/area monitoring
/area networking
/area ops-productivity
/kind enhancement

**What would you like to be added**:
The Shoot control plane monitoring has useful dashboards that show StatefulSet/Deployment/DaemonSet available/unavailable/update replicas. The corresponding dashboards that do this are `Kubernetes Deployments`, `Kubernetes StatetefulSets`, `Kubernetes DaemonSets`.

Example for such panel that shows etcd-main StatefulSet:
![Screenshot 2023-01-23 at 17 44 29](https://user-images.githubusercontent.com/9372594/214247339-2cf36d2d-3317-4ba2-8a12-caeaec4f6698.png)

Having such panel allows operators to easily identify downtimes in the respective components.
This issue requests similar panels to be added for the istio-ingressgateway and istiod Deployments. Currently an operator needs to  query prometheus to check this data.

**Why is this needed**:
See above.

**Comment by Sallyan** [comment]
/close 
As the pr merged
