### ISSUE TITLE
☂️ Drop support for Shoots with K8s < 1.22

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7405]
**How to categorize this issue?**

/kind cleanup

**What would you like to be added**:
After 2023-02-28 we can drop support for Shoots with K8s < 1.22. See https://github.com/gardener/gardener/blob/v1.63.0/docs/usage/supported_k8s_versions.md#support-timeline.

Gardener:
- [x] https://github.com/gardener/gardener:  
  - [x] Use `--kubeconfig` flag for VPA admission controller too, once v1.21 Shoots are no longer supported. And VPA version v0.12.0 is default.  -> https://github.com/gardener/gardener/pull/8087
  - [x] Deploy `extensions.gardener.cloud/v1alpha1.ControlPlane` after `kube-apiserver` (not before) -> https://github.com/gardener/gardener/pull/8162
  - [x] Drop everything related to CSI migration -> https://github.com/gardener/gardener/pull/8087

Extensions:
- Drop non-CSI related code (webhooks, etc.)
- [x] `provider-alicloud`: https://github.com/gardener/gardener-extension-provider-alicloud/pull/623
- [x] `provider-aws`: https://github.com/gardener/gardener-extension-provider-aws/pull/771
- [x] `provider-gcp`: https://github.com/gardener/gardener-extension-provider-gcp/pull/628
- [x] `provider-azure`: https://github.com/gardener/gardener-extension-provider-azure/pull/708
- [x] `provider-openstack`: https://github.com/gardener/gardener-extension-provider-openstack/pull/648
- [x] `provider-vsphere`: https://github.com/gardener/gardener-extension-provider-vsphere/pull/448
- [x] `provider-equinix-metal`: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/278
- [x] `networking-calico`: https://github.com/gardener/gardener-extension-networking-calico/pull/263, https://github.com/gardener/gardener-extension-networking-calico/pull/278
- [x] `networking-cilium`: https://github.com/gardener/gardener-extension-networking-cilium/pull/194
- [x] `extension-shoot-dns-service`: https://github.com/gardener/gardener-extension-shoot-dns-service/pull/218
- [x] `extension-shoot-cert-service`: https://github.com/gardener/gardener-extension-shoot-cert-service/pull/169
- [x] `extension-shoot-lakom-service`: https://github.com/gardener/gardener-extension-shoot-lakom-service/pull/22, https://github.com/gardener/gardener-extension-shoot-lakom-service/pull/23
- [x] `extension-shoot-oidc-service`: https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/115
- [x] `extension-shoot-networking-filter`: https://github.com/gardener/gardener-extension-shoot-networking-filter/pull/71
- [x] `extension-shoot-networking-problemdetector`: https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/pull/76
- [x] `os-gardenlinux`: https://github.com/gardener/gardener-extension-os-gardenlinux/pull/113
- [x] `os-suse-chost`: https://github.com/gardener/gardener-extension-os-suse-chost/pull/95
- [x] `os-ubuntu`: https://github.com/gardener/gardener-extension-os-ubuntu/pull/82
- [x] `os-coreos`: https://github.com/gardener/gardener-extension-os-coreos/pull/64
- [x] `runtime-gvisor`: https://github.com/gardener/gardener-extension-runtime-gvisor/pull/84
- [x] `registry-cache`: https://github.com/gardener/gardener-extension-registry-cache/pull/20
- ...

K8s test infra:
- [x] https://github.com/kubernetes/test-infra: https://github.com/kubernetes/test-infra/pull/29938

**Why is this needed**:
Drop support for quite old K8s versions.

**Comment by shafeeqes** [comment]
/assign
for `gardener/gardener` changes

**Comment by shafeeqes** [comment]
All the tasks are completed.
/close
