### ISSUE TITLE
[gardener-local] [mac] Error while `make kind-ha-multi-zone-up` trying to add IPv6 address to lo0

### ISSUE THREAD

**Issue by seshachalam-yv** [gardener/gardener#7430]
**How to categorize this issue?**

  /area testing
/kind bug test

**What happened**:
Error occurred while `make kind-ha-multi-zone-up` using the script [./hack/kind-up.sh](https://github.com/gardener/gardener/blob/master/hack/kind-up.sh#L57-L64)  is trying to add an IPv6 address to the loopback device lo0 in mac OS.

``` bash
> make kind-ha-multi-zone-up

Checking loopback device lo0...
IP address 127.0.0.10 already assigned to lo0.
IP address 127.0.0.11 already assigned to lo0.
IP address 127.0.0.12 already assigned to lo0.
Adding IP address ::10 to lo0...
Executing: /usr/bin/sudo /sbin/ifconfig lo0 inet6 add ::10
ifconfig: ioctl (SIOCAIFADDR): Invalid argument
Usage: ip addr show [ dev STRING ]
       ip addr { add | del } PREFIX dev STRING
make: *** [kind-ha-multi-zone-up] Error 255
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
Introduced with https://github.com/gardener/gardener/pull/7388 3 days ago. @timebertt , can you check?
