### ISSUE TITLE
[provider-local] pod `registry_registry-docker-ipv6` in `CrashLoopBackOff`

### ISSUE THREAD

**Issue by seshachalam-yv** [gardener/gardener#7444]
**How to categorize this issue?**

/area testing robustness
/kind bug test

**What happened**:

- In `provider-local` kind setup, always pod `registry_registry-docker-ipv6` in `CrashLoopBackOff.
- From [logs](https://storage.googleapis.com/gardener-prow/pr-logs/pull/gardener_gardener/7434/pull-gardener-e2e-kind-ha-multi-zone/1622101357408292864/artifacts/gardener-local-ha-multi-zone-control-plane/pods/registry_registry-docker-ipv6-5c8cb66b76-b67s7_c3a059a0-c0a6-4aed-be48-06a06abf4a48/registry/12.log) I can see network is unreachable error.
```
2023-02-05T15:04:28.396056945Z stderr F panic: Get "https://registry.ipv6.docker.com/v2/": dial tcp [2600:1f18:2148:bc00:8334:ca86:c3d6:a507]:443: connect: network is unreachable
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
cc @breuerfelix @timebertt - could you please have a look (see also #7434) 👀

**Comment by timebertt** [comment]
I think https://github.com/gardener/gardener/pull/7434#issuecomment-1418667778 is unrelated to this issue.
It rather seems like the mirror configuration in the shoot (changed with https://github.com/gardener/gardener/pull/7316) doesn't work, otherwise the node wouldn't try to pull the image from `localhost`.
cc @danielfoehrKn
