### ISSUE TITLE
Add Oracle as a Gardener Extension

### ISSUE THREAD

**Issue by tibeer** [gardener/gardener#7445]
**How to categorize this issue?**
/area open-source
/kind question

**What would you like to be added**:
Are there any plans to add Oracle as a Gardener Extension? If I had the skills to write go-code I would contribute, but unfortunately I lack a lot of experience there.

**Why is this needed**:
Partly out of curiosity, partly because I run some of my VMs on Oracle as they offer one permanent free arm-based VM. Would be nice to be able to orchestrate Kubernetes on this with Gardener.

**Comment by FHeine** [comment]
Hi @tibeer, thank you for your interest in using Gardener outside of the current scope. Unfortunately, there are no plans to enable OCI as an additional Gardener infrastructure extension. Such a request has never been received from any of the active community members so far and hence, is not planned at all.

**Comment by tibeer** [comment]
Fine for me :) Closing the issue.
