### ISSUE TITLE
`peerUrlTls` removed from etcd CR when shoot hibernated

### ISSUE THREAD

**Issue by aaronfern** [gardener/gardener#7497]
**How to categorize this issue?**

/area control-plane high-availability
/kind bug

**What happened**:
We noticed an issue that `etcd.Spec.Etcd.PeerUrlTls` was removed from the ETCD CR when shoot is hibernated and is re added when the shoot is then woken up. 
This causes an issue that when a shoot is marked for deletion while hibernated, etcd is scaled up without adding `etcd.Spec.Etcd.PeerUrlTls` and etcd members throw up the following error
```
2023-02-15 14:20:31.492960 W | rafthttp: health check for peer dda1e1b5de5194a3 could not connect: tls: first record does not look like a TLS handshake
```

**What you expected to happen**:
`etcd.Spec.Etcd.PeerUrlTls` to always be present in the ETCD CR

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an HA shoot with failure tolerance `zone`
2. Hibernate the shoot
3. Mark the shoot for deletion while the shoot is hibernated

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.64.0
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
Related code: https://github.com/gardener/gardener/blob/e74cc7cc70de5a78bc2f0268a8178c283f8f69f8/pkg/operation/botanist/component/etcd/etcd.go#L463-L478

**Comment by aaronfern** [comment]
Also noticed that the peer secrets for etcd are being deleted when the shoot is hibernated. This is not the case for client secrets, which remain when a shoot is hibernated

**Comment by rfranzke** [comment]
> Also noticed that the peer secrets for etcd are being deleted when the shoot is hibernated. This is not the case for client secrets, which remain when a shoot is hibernated

Related code: https://github.com/gardener/gardener/blob/e74cc7cc70de5a78bc2f0268a8178c283f8f69f8/pkg/operation/botanist/component/etcd/etcd.go#L924-L928 and ff.

**Comment by timuthy** [comment]
Thanks @rfranzke and @aaronfern 🙂 
The code misses to check if the peerTLS is already set and should not unset it if that's the case. Do you want to work on a fix @aaronfern?

**Comment by aaronfern** [comment]
Yes, I'd like to work on a fix for this 🙂

**Comment by BeckerMax** [comment]
Until we have this fix: Is there a workaround to resolve this situation for an existing cluster?

**Comment by BeckerMax** [comment]
@aaronfern And would it be fine to als create a hotfix once we have the fix? Thanks!
