### ISSUE TITLE
Drop `WaitUntilObjectReadyWithHealthFunction ` function in `BackupEntry` reconciler

### ISSUE THREAD

**Issue by ary1992** [gardener/gardener#7517]
**How to categorize this issue?**

/area dev-productivity scalability
/kind enhancement

**What would you like to be added**:
Drop `WaitUntilObjectReadyWithHealthFunction ` function in `BackupEntry` reconciler in favour of watch to eliminate higher timeouts.

https://github.com/gardener/gardener/blob/8fada8291d23d9dbc23a4be715afe35bc9995bf1/pkg/gardenlet/controller/backupentry/backupentry/reconciler.go#L600-L613
**Why is this needed**:

**Comment by rfranzke** [comment]
/remove-lifecycle stale
cc @ary1992
