### ISSUE TITLE
Drop deprecated `.spec.dns.ingressDomain` from `SeedSpec`

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#7519]
**How to categorize this issue?**

/area dev-productivity
/kind cleanup

**What would you like to be added**:
With https://github.com/gardener/gardener/pull/3131, the `.spec.dns.ingressDomain` field was deprecated more than two years ago in favor of `.spec.dns.provider` and `.spec.ingress`. However, the field was never removed. Let's clean it up now.

**Why is this needed**:
Removal of technical debt.

**Comment by shafeeqes** [comment]
/assign
Should this also be done in two parts for the usages and API?

**Comment by rfranzke** [comment]
@shafeeqes I think this makes sense, yes.

**Comment by shafeeqes** [comment]
/close
All tasks are completed.
