### ISSUE TITLE
Run existing `default` `shoot` E2E tests as part of HA single/multi zone Prow jobs

### ISSUE THREAD

**Issue by seshachalam-yv** [gardener/gardener#7525]
**How to categorize this issue?**

/area control-plane high-availability robustness testing 
/kind enhancement test

**What is the request**:
The request is to add the existing E2E shoot tests labeled as (`default` && `shoot`) to `single/multi-zone` E2E testing Prow jobs:
  - [Create and Delete Unprivileged Shoot `[Shoot, default, unprivileged]`](https://github.com/gardener/gardener/blob/master/test/e2e/gardener/shoot/create_and_delete_unprivileged.go#L57)
  - [Create, Update, Delete `[Shoot, default, simple]`](https://github.com/gardener/gardener/blob/master/test/e2e/gardener/shoot/create_update_delete.go#L55)
  - [Create, Hibernate, Wake up and Delete Shoot `[Shoot, default]`](https://github.com/gardener/gardener/blob/master/test/e2e/gardener/shoot/create_hibernate_wakeup_delete.go#L32)
  - [Create Shoot, Rotate Credentials and Delete Shoot `[Shoot, default, credentials-rotation]`](https://github.com/gardener/gardener/blob/master/test/e2e/gardener/shoot/create_rotate_delete.go#L36)

**Why is this needed**:
- An issue was recently observed where hibernated shoots were getting stuck during deletion, as reported in GitHub issue #7497. Currently, the test case for this issue runs only as part of the Prow job `pull-gardener-e2e-kind `, and it is not included in `pull-gardener-e2e-kind-ha-multi-zone` and `pull-gardener-e2e-kind-ha-multi-zone`. 

- **To prevent similar issues in the future**, I propose to run all shoot tests labeled as (`default` && `shoot`) as part of `pull-gardener-e2e-kind-ha-multi-zone` and `pull-gardener-e2e-kind-ha-multi-zone`. 

cc: @rfranzke @timuthy @aaronfern

**Comment by Sallyan** [comment]
Prow job `pull-gardener-e2e-kind` run all the tests labeled with `default`, it has 14

<img width="1104" alt="Screenshot 2023-07-11 at 09 50 40" src="https://github.com/gardener/gardener/assets/50126000/0fc53150-47dd-45da-b998-3c950503306e">

Prow job `pull-gardener-e2e-kind-ha-multi-zone` and `pull-gardener-e2e-kind-ha-single-zone/`  run the tests with label `--label-filter "simple || (high-availability && upgrade-to-node)"`

If update `single/multi-zone` E2E jobs label to `--label-filter "(default && shoot) || (high-availability && upgrade-to-node)"` , it will add the following tests: 
- Shoot with invalid DNS configuration Create and Delete Failed Shoot [Shoot, default]
- Workerless Shoot Create and Delete Hibernated Shoot [Shoot, default, workerless, hibernated]
- Shoot with workers Create and Delete Hibernated Shoot [Shoot, default, hibernated]
- Create and Delete Unprivileged Shoot [Shoot, default, unprivileged]
- Workerless Shoot Create, Update, Delete [Shoot, default, workerless, simple]
- Workerless Shoot Create, Hibernate, Wake up and Delete Shoot [Shoot, default, workerless]
- Create Shoot, Rotate Credentials and Delete Shoot [Shoot, default, workerless, credentials-rotation]
- Shoot with workers Create, Update, Delete [Shoot, default, simple]
- Shoot with workers Create, Hibernate, Wake up and Delete Shoot [Shoot, default]
- Shoot with workers Create Shoot, Rotate Credentials and Delete Shoot [Shoot, default, credentials-rotation]

**Comment by Sallyan** [comment]
@seshachalam-yv  @rfranzke @timuthy 
Would we only add the listed four tests or can i go ahead to add all shoot tests labeled `default && shoot` ?

**Comment by seshachalam-yv** [comment]
The motivation behind this issue stems from a problem we observed where hibernated shoots were getting stuck during deletion, as detailed in this issue description. 

To catch similar issues more effectively in the future, I've proposed to run all shoot tests labeled as `default && shoot`. Initially, this meant adding only four specific tests. However, with the recent introduction of workerless shoots, the scope of the `default && shoot` label has broadened significantly, now encompassing a wider set of tests that include both workerless and worker shoots.

This comprehensive approach could enhance our testing coverage, helping us discover and address potential bugs more effectively.

@rfranzke, I'd love to hear your thoughts on a couple of things:
- Should we include the workerless tests in our expanded coverage?
- I believe the following two tests may not be necessary, as they're already covered in `pull-gardener-e2e-kind`. Could you confirm this?
   - `Shoot with invalid DNS configuration Create and Delete Failed Shoot [Shoot, default]` 
   - `Create Shoot, Rotate Credentials and Delete Shoot [Shoot, default, workerless, credentials-rotation]`

**Comment by rfranzke** [comment]
> Should we include the workerless tests in our expanded coverage?

What is the benefit? There is nothing specific to HA In this scenario, is it?

> I believe the following two tests may not be necessary, as they're already covered in pull-gardener-e2e-kind. Could you confirm this?

I agree.

**Comment by seshachalam-yv** [comment]
> What is the benefit? There is nothing specific to HA In this scenario, is it?

Yes, there is no specific benefit.

Then we can stick with four tests listed in issue description.

**Comment by Sallyan** [comment]
/close 
As the pr already merged.
