### ISSUE TITLE
Core documentation for KubeletConfig evictionHard and evictionSoft with misleading memory defaults

### ISSUE THREAD

**Issue by CGilde** [gardener/gardener#7527]
Documentation issue at https://gardener.cloud/docs/gardener/api-reference/core/

evictionHard
KubeletConfigEviction	(Optional)
EvictionHard describes a set of eviction thresholds (e.g. memory.available<1Gi) that if met would trigger a Pod eviction. **Default: memory.available: “100Mi/1Gi/5%”** nodefs.available: “5%” nodefs.inodesFree: “5%” imagefs.available: “5%” imagefs.inodesFree: “5%”

The "**Default: memory.available: “100Mi/1Gi/5%”**" is misleading, what is the "1Gi/5%" part about? 

Isn't it just "100Mi" ?

Same with EvictionSoft

**Comment by danielfoehrKn** [comment]
Hi, 
The eviction thresholds are defaulted taking the machine type into consideration. For eviction hard:
- Machine type cannot be found in the cloud profile -> 100 Mi
- Machine type can be found -> 5%
- Machine type has > 8 Gi capacity -> 1 Gi

See [here](https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go#L528-L540)

**Comment by rfranzke** [comment]
I guess there is not much else to do here, please correct me if I'm wrong/reopen if necessary.
/close
