### ISSUE TITLE
Clean up the multitenancy fluent-bit filters

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7580]
**How to categorize this issue?**

/area logging
/kind cleanup

**What would you like to be added**:
After https://github.com/gardener/gardener/pull/7523, the user tenant in loki is removed. Hence, we no longer need the corresponding multitenancy fluent-bit filters ([ref](https://github.com/gardener/gardener/blob/579c2ba781a2803bf4cd5b9d5b73de28136e21c4/pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go#L589-L611)). @vlvasilev shared that even the latest version of the fluent-bit plugin has the handling for the plugin removed.

Gardener
  - [x] Seed reconciler ([ref](https://github.com/gardener/gardener/blob/579c2ba781a2803bf4cd5b9d5b73de28136e21c4/pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go#L589-L611)): https://github.com/gardener/gardener/pull/7670

Extensions:
  - [x] gardener-extension-provider-aws ([ref](https://github.com/gardener/gardener-extension-provider-aws/blob/84af99fb6b2754230dd3bb50e54e8f782eefd0f7/charts/gardener-extension-provider-aws/templates/configmap-logging.yaml#L45-L55), [ref](https://github.com/gardener/gardener-extension-provider-aws/blob/76c2402beba460fa56d217a5cbc50dfea5bba9c4/charts/gardener-extension-provider-aws/templates/clusterfilters-logging.yaml#L93-L109)): https://github.com/gardener/gardener-extension-provider-aws/pull/765
  - [x] gardener-extension-provider-gcp ([ref](https://github.com/gardener/gardener-extension-provider-gcp/blob/4b7a8d01d19c46a93fed86ef59de7c2a85d7c38e/charts/gardener-extension-provider-gcp/templates/configmap-logging.yaml#L45-L55), [ref](https://github.com/gardener/gardener-extension-provider-gcp/blob/23a7913aeb772b96f81742a46b2ca9c58e815035/charts/gardener-extension-provider-gcp/templates/clusterfilters-logging.yaml#L77-L93)): https://github.com/gardener/gardener-extension-provider-gcp/pull/616
- [x] gardener-extension-provider-azure: https://github.com/gardener/gardener-extension-provider-azure/pull/700
- [x] gardener-extension-provider-openstack: https://github.com/gardener/gardener-extension-provider-openstack/pull/639
- [x] gardener-extension-provider-alicloud: https://github.com/gardener/gardener-extension-provider-alicloud/pull/610
- [x] gardener-extension-provider-equinix-metal: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/271
- [x] gardener-extension-provider-vsphere: https://github.com/gardener/gardener-extension-provider-vsphere/pull/432

**Why is this needed**:
A follow-up clean up related to the user tenant cleanup.

**Comment by vlvasilev** [comment]
ref: https://github.com/gardener/gardener-extension-provider-aws/pull/765
ref: https://github.com/gardener/gardener-extension-provider-gcp/pull/616
ref: https://github.com/gardener/gardener-extension-provider-azure/pull/700
ref: https://github.com/gardener/gardener-extension-provider-openstack/pull/639
ref: https://github.com/gardener/gardener-extension-provider-alicloud/pull/610
ref: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/271
ref: https://github.com/gardener/gardener-extension-provider-vsphere/pull/432

**Comment by ialidzhikov** [comment]
/close
as all sub-tasks are now resolved
