### ISSUE TITLE
Deprecate and remove node-local-dns annotations which already have a Shoot spec field replacement

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7581]
**How to categorize this issue?**

/area networking
/kind cleanup

**What would you like to be added**:
This issue proposes deprecation and removal of the following annotations:
- `alpha.featuregates.shoot.gardener.cloud/node-local-dns` - it is possible to enable/disable the node-local-dns from the Shoot spec (`.spec.systemComponents.nodeLocalDNS.enabled`)
- `alpha.featuregates.shoot.gardener.cloud/node-local-dns-force-tcp-to-cluster-dns` - the corresponding Shoot spec field is `.spec.systemComponents.nodeLocalDNSforceTCPToClusterDNS`
- `alpha.featuregates.shoot.gardener.cloud/node-local-dns-force-tcp-to-upstream-dns` - the corresponding Shoot spec field is `.spec.systemComponents.nodeLocalDNSforceTCPToUpstreamDNS`

We have to first deprecate these annotations. We can use [API warnings](https://kubernetes.io/blog/2020/09/03/warnings/) to let the Shoot owners know that these annotations are deprecated.

> Switching on node-local-dns via shoot specification will roll the nodes even if node-local-dns was enabled beforehand via annotation.

**Why is this needed**:
To have a cleaner API.

**Comment by rfranzke** [comment]
FYI @ScheererJ @DockToFuture @axel7born
