### ISSUE TITLE
Use cache for `ShootState`s in Gardenlet

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#7593]
**How to categorize this issue?**

/area performance
/area robustness
/area cost
/area control-plane-migration
/area scalability
/kind enhancement

**What would you like to be added**:
Gardenlet to use cached `ShootState` objects for its controllers.

For this, we can follow Kubelet's approach to list-watch individual `ConfigMap`s and `Secret`s ([ref](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-ResourceChangeDetectionStrategy)):

- Initiate a list-watch (leads to caching) when object is requested
- Track a `lastAccessTime` whenever the object is requested from cache
- Define a `maxIdleTime` (here 5 * sync period)
- Close watch whenever `lastAccessTime + maxIdleTime < now`

See [Watch Based Manager](https://github.com/kubernetes/kubernetes/blob/v1.26.0/pkg/kubelet/util/manager/watch_based_manager.go) for implementation details.

**Why is this needed**:
Due to security reasons, the cache [is disabled](https://github.com/gardener/gardener/blob/2a6641a3fec2fcdb9481484a31186745910a9fbe/cmd/gardenlet/app/app.go#L290) for `ShootState`s. This is mostly because the [Seed Authorizer](https://github.com/gardener/gardener/tree/master/pkg/admissioncontroller/webhook/auth/seed) doesn't have access to any list options which makes it impossible to ensure that only objects related to the Gardenlet's seed are "list-watched".

In the last months we observed this has become a performance and stability issue, esp. in landscapes with many shoots. `ShootState` objects are comparably bigger in size and whenever Gardenlet(s) restart, they put Gardener Apiservers under pressure with many `GET` calls being involved, mainly originating from the [shootstate secret controller](https://github.com/gardener/gardener/tree/master/pkg/gardenlet/controller/shootstate/secret).

**Related tasks**:

- Consider using the single object cache also for `Secret`s outside of the seed-specific namespace
- Consider optimizing sent `PATCH` requests for `ShootState`s in case there is no change

**Comment by rfranzke** [comment]
/assign @timuthy @rfranzke 
We would like to take a closer look together on Thursday.
