### ISSUE TITLE
Switch default KCM `--node-monitor-grace-period` to `40s`

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#7688]
**What would you like to be added**:

While introducing DWD, we set KCM's `--node-monitor-grace-period` to `120s`, but this is very long and way beyond KCM's default of `40s`. We should go back to that default, for seeds and shoots. See also https://github.com/gardener/dependency-watchdog/issues/79.

**Why is this needed**:

We saw during "zone outage simulations" that recovery happens very slowly. It takes `2m` for KCM to put a node into `Unknown` state and only then things move forward like endpoint and loadbalancer deregistration. Notable is especially our Istio ingress gateway/the API server that appears available for 2m before it gets updated even though it's dead for the entire time.

**Comment by timuthy** [comment]
Should we change the default setting to 40s with Kubernetes v1.27?
cc @ary1992

**Comment by acumino** [comment]
Completed in https://github.com/gardener/gardener/pull/7883
/close
