### ISSUE TITLE
Set topology spread constraint `minDomains` to number of zones

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#7690]
**What would you like to be added**:

When the scheduler doesn't see a zone (e.g. during a zone outage or because of worker pool scale to zero), TSCs will be interpreted "wrongly", if [`minDomains`](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition) is not set. I believe we should amend https://github.com/gardener/gardener/blob/master/docs/development/high-availability.md and start setting `minDomains` based on the number of zones for seed and shoot components alike.

**Why is this needed**:

We saw during "rolling zone outage simulations" with clusters with only 2 zones that e.g. `coredns` gets scheduled to the second zone while the first zone is struck and that DNS fails then completely once the second zone is struck (long after the first zone recovered). That is just an example and it shows that our TSCs don't work as expected, if the scheduler lacks "the full picture"/zone topology information.

**Comment by rfranzke** [comment]
The effect of the `minDomains` is controlled by the `MinDomainsInPodTopologySpread` feature gate which is still disabled by default (even though it graduated to beta).

However, it seems that the `minDomains` field can still be set by clients and will just be dropped before persisted to ETCD: https://github.com/kubernetes/kubernetes/blob/d2be69ac11346d2a0fab8c3c168c4255db99c56f/pkg/api/pod/util.go#L617-L625

Hence, we should be fine always setting the field. Whether it takes effect is out of Gardeners control (the feature gate must be enabled for the seed cluster by the human operator, or a high-enough Kubernetes version must be used where the feature gate is enabled by default).
