### ISSUE TITLE
Access Gardener cluster for Shoot cluster creation/management without token expiration of service account

### ISSUE THREAD

**Issue by turtlechips** [gardener/gardener#7706]
**How to categorize this issue?**
/kind enhancement

**What would you like to be added**:
Ability to access Gardener cluster to create/manage Shoot Cluster through Automation tools (GitOps/Jenkins) without token expiration of service account.

**Why is this needed**:
We are currently using a service account to help managing Shoot Clusters in Gardener through Automation tools.
The service user token expires/rotates every so often and that means we need to update the token into our Automation tools.

**Comment by donistz** [comment]
Hello @turtlechips, The service account tokens validity for accessing the Gardener API depends on the Kubernetes API configuration/rotation implemented/enforced by your Gardener service operator for the service. If you want to find more details about the validity of the tokens and why such validity has been enforced for the Gardener service that you use, you have to get in contact with your Gardener service provider.
