### ISSUE TITLE
Unable to Deploy Gardener on Kubernetes

### ISSUE THREAD

**Issue by arnabnandy1706** [gardener/gardener#771]
Hello All,

I am deploying the gardener on top of Kubernetes Cluster running on-premise. 

I am using the helm chart provided here, but the **gardener-apiserver** goes into **CrashLoopBackOff** state.

When I checked the logs for the pod I get below the error.

`Error: unable to load server certificate: tls: failed to find any PEM data in certificate input`

Please help me.

Thanks in advance.

Regards,
Arnab

**Comment by rfranzke** [comment]
Have you specified the needed certificates [for etcd](https://github.com/gardener/gardener/blob/master/charts/gardener/values.yaml#L21-L33) and [the gardener-apiserver](https://github.com/gardener/gardener/blob/master/charts/gardener/values.yaml#L37-L49)?

**Comment by arnabnandy1706** [comment]
No I have not. 

I followed below the link to install. 

https://github.com/gardener/gardener/blob/master/docs/deployment/kubernetes.md

How to provide the certificate?

Thanks
Arnab

**Comment by arnabnandy1706** [comment]
@rfranzke  any suggestion on above question?

**Comment by timuthy** [comment]
[For etcd](https://github.com/gardener/gardener/blob/master/charts/gardener/values.yaml#L21-L33) you need to provide `ca.crt / client.crt / client.key` that lets the `Gardener-Apiserver` connect to an etcd instance.

For instance, if you want to use the same etcd that your `Kube-Apiserver` is connected to, you can refer to the `command parameters` of your `Kube-Apiserver Pod`.

[The Gardener-Apiserver](https://github.com/gardener/gardener/blob/master/charts/gardener/values.yaml#L37-L49) also needs a `ca.crt / client.crt / client.key` triplet to start. These files are supposed to be created and provided by yourself (e.g. create a CA + signed client cert via `openssl`).

**Comment by arnabnandy1706** [comment]
@timuthy Thanks for the help.

After I have generated the certificates and keys I have provided in the **values.yaml** file.

But now in the **apiserver** log I am getting below the error.

`F0228 10:56:01.216559       1 storage_decorator.go:57] Unable to create storage backend: config (&{ /registry/garden.sapcloud.io [https://10.211.203.83:2379]    false 0xc0005067e0 <nil> 5m0s 1m0s}), err (context deadline exceeded)`

**Comment by arnabnandy1706** [comment]
Below is the values.yaml file.

[values.txt](https://github.com/gardener/gardener/files/2914684/values.txt)

**Comment by timuthy** [comment]
Looks like a connection issue to your etcd form Gardner-Apiserver. Have you checked that the IP is correct, `etcd Pod` is running, `Service` is configured correctly, `Endpoint` object is available ...?

**Comment by arnabnandy1706** [comment]
But ETCD pod is up and running:
`etcd-k8-master.domain                      1/1     Running   3          10d`

Kubernetes Service:
`Name:              kubernetes`
`Namespace:         default`
`Labels:            component=apiserver`
`                   provider=kubernetes`
`Annotations:       <none>`
`Selector:          <none>`
`Type:              ClusterIP`
`IP:                10.96.0.1`
`Port:              https  443/TCP`
`TargetPort:        6443/TCP`
`Endpoints:         **<masterip>**:6443`
`Session Affinity:  None`
`Events:            <none>`

**Comment by timuthy** [comment]
I rather meant a `Service` for etcd.

Anyways, the point is if your etcd instance is really reachable via `
https://10.211.203.83:2379` and `
ca.crt / client.crt / client.key` you provided.

If you intend to use the same etcd instance your `Kube-Apiserver` uses, please double check these  settings with the ones passed to `Gardener-Apiserver`. If `10.211.203.83:2379` is really your endpoint for etcd, you could `exec` the following inside the `Gardener-Apiserver Pod` to check the connection:
`curl -vk --cert /etc/gardener-apiserver/srv/etcd-client.crt --key /etc/gardener-apiserver/srv/etcd-client.key https://10.211.203.83:2379/v2/keys`

**Comment by vasu1124** [comment]
@arnabnandy1706 can you take a look at what @afritzler did on GKE with https://github.com/afritzler/virtual-gardener-gke and maybe re-use/adopt to your on-premise situation?

**Comment by rfranzke** [comment]
Can this issue be closed?

**Comment by timuthy** [comment]
Please reopen if required.
