### ISSUE TITLE
Expose kubelet option `memorySwap.swapBehavior` in shoot.yaml

### ISSUE THREAD

**Issue by NorbertAtSAP** [gardener/gardener#7745]
**How to categorize this issue?**

/area control-plane
/area cost
/kind enhancement

**What would you like to be added**:

Please make the parameter `memorySwap.swapBehavior` from the kubelet configuration accessible in the `shoot.yaml`as `kubelet.memorySwap.swapBehavior`, so that Gardener users can continue to use swap.

**Why is this needed**:

With Kubernetes release 1.22, it has become possible to enable swap for nodes as an alpha feature (see [feature description](https://kubernetes.io/docs/concepts/architecture/nodes/#swap-memory). This is an important cost factor for many applications, see [use cases in the KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2400-node-swap#motivation).

The kubelet configuration in the `shoot.yaml` already exposes the parameters required to enable swap: `kubelet.featureGates.NodeSwap: true` and `kubelet.failSwapOn: false`. With cgroups v1, this was sufficient to enable swap, but according to the feature description, with cgroups v2, swap will only be available to kubernetes workloads if the parameter `memorySwap.swapBehavior` in the kubelet config is also set to `UnlimitedSwap`.

Relevant quotes from the [feature description](https://kubernetes.io/docs/concepts/architecture/nodes/#swap-memory):
> "If configuration for `memorySwap` is not specified and the feature gate is enabled, by default the kubelet will apply the same behaviour as the `LimitedSwap` setting."
> "The behaviour of the `LimitedSwap` setting depends if the node is running with v1 or v2 of control groups (also known as "cgroups"):"
> "cgroupsv1: Kubernetes workloads can use any combination of memory and swap, up to the pod's memory limit, if set."
> "cgroupsv2: Kubernetes workloads cannot use swap memory."

**Comment by danielfoehrKn** [comment]
A word of caution: this will enable each container cgroup to use unlimited swap (up to the maximum amount available on the host system) for its anonymous memory. That is different behavior from cgroupsv1 where swap + memory usage is limited by the memory limit on the cgroup. One process with a memory leak/heavy anon memory usage alone can demand all swap.
That might cause Gardener operators a lot of headaches.

I am not saying there is no valid use case for it, just that it's a setting where the user must know exactly what they are doing. The KEP also states important improvements that are supposed to come for beta graduation such as limiting swap usage on the pod level, as well as system-reserved swap.

**Comment by NorbertAtSAP** [comment]
Yes, completely agreed. The full potential will only unfold when the KEP reaches its beta goals, and it is not yet quite clear when that is expected to happen.
But even with the somewhat risky "any pod may eat up all swap space" scenario, just being able to enable swap at all can make a huge difference in cost. In our target scenario we have the following boundary conditions:
- app usually grows, up to 8 GB, never shrinks
- actual working set is much smaller (usually less than half)
- app is sensitive about disruptions, so we use request == limit to avoid OOM kills
- in occasional spikes, the app may need up to 12 GB (virtual memory, not working set)
- without swap, we are forced to actually spend 12 GB, with swap we get away with less than 8 GB
- performance penalty resulting from swap tolerable so far (happens rarely)

So we would very much appreciate if you could continue to enable the Gardener user to accept that risk.
