### ISSUE TITLE
monitoring: Make sure grafana dashboards are valid JSON files

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7761]
**How to categorize this issue?**

/area monitoring
/area dev-productivity
/kind enhancement

**What would you like to be added**:
In https://github.com/gardener/gardener/issues/7747#issuecomment-1497391411 we noticed that a grafana dashboard has invalid JSON. We should add a check to `make verify` that check that these dashboard files are valid JSON documents.

**Why is this needed**:
To prevent introducing invalid grafana dashboard JSON.

**Comment by Sallyan** [comment]
To valid grafana dashboard JSON, firstly we should check for any syntax errors to verify it's a valid json. Then check the specific properties like title cannot be empty, uid cannot be duplicate etc. 
Can use JSON validator or JSON linter tools analyze JSON files for syntax errors, missing commas, or other common mistakes. 
Find a tool to lint Grafana dashboards, https://github.com/grafana/dashboard-linter. This tool is a work in progress and has some checks we dont need. I think we probably reuse this linter and define the rules.
