### ISSUE TITLE
Extreme TCP buffer settings

### ISSUE THREAD

**Issue by DanielYWoo** [gardener/gardener#7768]
**How to categorize this issue?**
/area networking
/area scalability
/kind bug

**What happened**:
The TCP buffer is 12KB in most linux systems, and we sometimes increase them to 64KB or even 128KB for better performance. But I think we have a typo here which makes them 12MB by default. Out performance test shows all most all of our applications run OOM.
https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go#L100-L101

**What you expected to happen**:
Make it between 64KB to 128KB.

**How to reproduce it (as minimally and precisely as possible)**:
run sysctl to grep the two settings

**Anything else we need to know?**:
N/A

**Environment**:
N/A

- Gardener version: all versions
- Kubernetes version (use `kubectl version`): v1.24.10
- Cloud provider or hardware configuration: Azure
- Others: N/A

**Comment by timuthy** [comment]
@gardener/gardener-core-networking-maintainers any thoughts?

**Comment by ScheererJ** [comment]
@DanielYWoo While the default buffer size certainly is fairly large we have not seen issues related to that so far. Could you please share more details concerning your context/scenario where you experience these issues? What are the characteristics of your performance tests?

**Comment by ScheererJ** [comment]
Similar previous issue: https://github.com/gardener/gardener/issues/6067

**Comment by DanielYWoo** [comment]
@ScheererJ For example, the Hana JDBC Driver allocates two buffers for sending and receiving based on the kernel parameters. With 12MB settings, a connection could consume 24MB memory. In our case, in a typical deployment each pod connects to 50+ databases, suppose each connection pool keeps 20 connections, that's 1K connections in total which consumes 24GB of memory just for TCP buffers.
12MB is way too large. 12KB ~ 128KB is good enough for most cases.

**Comment by ScheererJ** [comment]
@DanielYWoo Thanks for sharing the additional details.

After some discussion, we will most likely make this configurable at some point in the future.

However, if you need an immediate solution please use a daemonset with host network to set your preferred value. Please note that this might need to be reapplied every now and then as the default value is applied every time the operating system configuration changes.
