### ISSUE TITLE
gardener-apiserver: `deletecollection` does not work for ShootStates and leaks all ShootState names

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7776]
**How to categorize this issue?**

/area quality
/area security
/kind bug

**What happened**:

We see cases where KCM cannot delete namespaces with error:
```
I0412 11:39:51.097247       1 namespaced_resources_deleter.go:336] namespace controller - deleteCollection unexpected error - namespace: garden-bar, gvr: core.gardener.cloud/v1beta1, Resource=shootstates, error: shootstates.core.gardener.cloud "Unknown" is forbidden: 5 errors occurred:
	* shootstates.core.gardener.cloud "aws-local-baz" not found
	* shootstates.core.gardener.cloud "aws-local-bazz" not found
	* shootstates.core.gardener.cloud "aws-local" not found
	* shootstates.core.gardener.cloud "aws-local-ha" not found
	* shootstates.core.gardener.cloud "aws-local-bar" is forbidden: must have a "confirmation.gardener.cloud/deletion" annotation to delete
```

This happens when there is a ShootState in a leaked namespace without the `confirmation.gardener.cloud/deletion` annotation. 

Indeed, I am able to reproduce - see https://gist.github.com/ialidzhikov/18de9d7b875cc8693bc57e412662a19d.

The above `main.go` fails with:
```
% go run main.go --garden-kubeconfig=$KUBECONFIG
panic: shootstates.core.gardener.cloud "Unknown" is forbidden: 5 errors occurred:
	* shootstates.core.gardener.cloud "aws-local" not found
	* shootstates.core.gardener.cloud "aws-local-bazz" not found
	* shootstates.core.gardener.cloud "aws-local-bar" not found
	* shootstates.core.gardener.cloud "aws-local-ha" not found
	* shootstates.core.gardener.cloud "aws-local-baz" is forbidden: must have a "confirmation.gardener.cloud/deletion" annotation to delete



goroutine 1 [running]:
main.main()
	/example/main.go:49 +0x1b1
exit status 2
```

The `main.go` is trying to deletecollection in the `garden-baz` Namespace.

**What you expected to happen**:
`deletecollection` to work for ShootStates.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:
N/A

**Environment**:

- Gardener version: v1.68.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
What do you suggest to implement here? We do have the deletion confirmation protection on purpose, so allowing `deletecollection` operation somewhat contradicts to this approach. Do you propose to drop the protection?

**Comment by ialidzhikov** [comment]
I am not sure whether it is related to the deletion confirmation. Let me put some more detailed steps to reproduce:

1. Create Namespaces
```
% k create ns garden-foo
% k create ns garden-bar
% k create ns garden-baz
% k create ns garden-bazz
```

2. Create a ShootState in each Namespace. I put the ShootState name to be the Namespace suffix (foo, bar, baz, bazz). Create the ShootStates with the deletion confirmation annotation added:
```yaml
  annotations:
    confirmation.gardener.cloud/deletion: "true"
```

My setup looks like:
```
% k get shootstates -A
NAMESPACE        NAME           GARDENER DATA   EXTENSION STATES   AGE
garden-bar       bar            15              2                  32s
garden-baz       baz            15              2                  27s
garden-bazz      bazz           15              2                  18s
garden-foo       foo            15              2                  43s
```

3. Run `deletecollection` for ShootStates in `garden-baz` Namespace (Run the above `main.go`).

It fails with:
```
panic: shootstates.core.gardener.cloud "Unknown" is forbidden: 5 errors occurred:
	* shootstates.core.gardener.cloud "bazz" not found
	* shootstates.core.gardener.cloud "foo" not found
	* shootstates.core.gardener.cloud "bar" not found
```

---

1. I would expect `deletecollection` to work when all ShootStates in a Namespace have the confirmation annotation. As demonstrated above, it does not.
2. I don't understand why the returned error contains error of types `shootstates.core.gardener.cloud "<name>" not found` while these ShootStates exist in completely other namespaces than the one we use for the deletecolection (`garden-baz`).

**Comment by rfranzke** [comment]
Thanks for the additional explanation, this makes sense then! Let's indeed fix this and make `deletecollection` work when all `ShootState`s have the deletion confirmation annotation.
