### ISSUE TITLE
Gardener refused to create correctly configured cluster (CIDR calculation problem)

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener#7779]
**How to categorize this issue?**

/area regression
/kind bug

**What happened**:

When I try to create a cluster with 128 nodes I get the following error:

```
The Shoot "gcp-fgl" is invalid: spec.provider.workers: Invalid value: 128: worker configuration incorrect. The podCIDRs in `spec.networking.pod` can only support a maximum of 64 nodes. The total number of worker pool nodes should be less than 64
```

The pod CIDR is configured to be `10.243.128.0/17` and there is no `nodeCIDRMaskSize` value set in the shoot config which means that the default should be taken (`/24`). This should allow a cluster to be created with 128 nodes (the bug is that it does not).

Explicitly setting the `nodeCIDRMaskSize` to `/24` resolves the problem.

This means that currently almost no seed cluster could be created in our development environment with the currently generated specs - they would all run into that problem because most of them or all are configured in a way described above.

**What you expected to happen**:

Cluster should be created.

**How to reproduce it (as minimally and precisely as possible)**:

I have a shoot spec available but you can take any shoot spec from the development environment that serves as a shooted seed (e.g. `gcp` does the trick).

**Anything else we need to know?**:

**Environment**:

**Comment by shafeeqes** [comment]
Can you please post your full shoot yaml?
From the defaulting logic here, https://github.com/gardener/gardener/blob/e48872933e3039438d971786798ded799181e202/pkg/apis/core/v1beta1/defaults.go#L390-L413

if `kubelet.maxPods` is 180, (assuming gcp), then default `nodeCIDRMaskSize` calculated is only 23 (For a quick check, you can alter `MaxPods=180` this test: https://github.com/gardener/gardener/blob/1e9b2c1a4e5ec47d29b250eaf99a35dad05f525d/pkg/apis/core/v1beta1/defaults_test.go#L260-L268). Then the error message is correct. If the `maxPods` is not mentioned, then it's defaulted to 110, in that case, the `nodeCIDRMaskSize` is defaulted to 24. If you mention `kubeControllerManager.NodeCIDRMaskSize` as 24, explicitly, then it works as expected too.

**Comment by rfranzke** [comment]
cc @danielfoehrKn

**Comment by marwinski** [comment]
Sent shoot spec via separate email. 

> if kubelet.maxPods is 180, (assuming gcp), then default nodeCIDRMaskSize calculated is only 23 (For a quick check, you can alter MaxPods=180 this test:

I would assume that with maxPods set to 180 the nodeCIDRMaskSize should be 24 !?

**Comment by shafeeqes** [comment]
> I would assume that with maxPods set to 180 the nodeCIDRMaskSize should be 24 !?

For any value > 128, it's 23.

**Comment by marwinski** [comment]
> For any value > 128, it's 23.

Did that change and why - you only need a /24 to cater for 128 pods? This said, none of our seeds in our development environment could be created anymore because they don't have `nodeCIDRMaskSize` configured - we just don't see it because those clusters already exist. Can we get back the old behavior.

**Comment by shafeeqes** [comment]
> > For any value > 128, it's 23.
> 
> Did that change and why - you only need a /24 to cater for 128 pods? This said, none of our seeds in our development environment could be created anymore because they don't have `nodeCIDRMaskSize` configured - we just don't see it because those clusters already exist. Can we get back the old behavior.
```
 	// by having approximately twice as many available IP addresses as possible Pods, Kubernetes is able to mitigate IP address reuse as Pods are added to and removed from a node. 
 	nodeCidrRange := int32(32 - int(math.Ceil(math.Log2(float64(maxPods*2))))) 
```
This is the reasoning mentioned.
> because they don't have nodeCIDRMaskSize configured 

Can't we just configure them then rather than changing the validation, which I think is working just fine?
Isn't it rather the defaulting which is limiting here?
