### ISSUE TITLE
`make start-gardenlet SEED_NAME=local` sometimes cannot bootstrap Seed

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7816]
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What happened**:
While following https://github.com/gardener/gardener/blob/master/docs/development/getting_started_locally.md we hit the following issue - we start gardenlet (`make start-gardenlet SEED_NAME=local`) but for some reason gardenlet cannot/doesn't add the Seed controller in 2minutes.
I ~2minutes gardenlet logs:
```
2023-04-20T17:29:07.977+0300	ERROR	error received after stop sequence was engaged	{"error": "failed adding controllers to manager: failed adding ManagedSeed controller: can't accept new runnable as stop procedure is already engaged"}
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1
	/Users/i331370/SAPDevelop/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go:555
```

It failed here
https://github.com/gardener/gardener/blob/5abed1bfedd6f2188e5dcec9af161d1b5c286236/pkg/gardenlet/controller/add.go#L124-L130

and the code that adds the Seed controller is few lines below:
https://github.com/gardener/gardener/blob/5abed1bfedd6f2188e5dcec9af161d1b5c286236/pkg/gardenlet/controller/add.go#L139-L141

So far, we were not able to understand why gardenlet cannot add the Seed controller (and others).
The issue is not always reproducible. Sometimes it succeeds adding the Seed controller, the Seed gets reconciled, etc.
But in other cases, gardenlet only spams about missing Seed CRDs and exits without success in 2minutes.

**What you expected to happen**:
`make start-gardenlet SEED_NAME=local` to work always.
 
**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: 9e72057c48b8525a362bcce7d1e618cbf93f3c24
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
We won't fix this since we plan to drop all local setup options other than `make kind-up gardener-up` (and the same for extensions, respectively) as part of #6016, cc @oliver-goetz.
/close
