### ISSUE TITLE
Change the way `containerd` uses custom configuration

### ISSUE THREAD

**Issue by Kostov6** [gardener/gardener#7838]
**How to categorize this issue?**

/area quality
/kind enhancement

**What would you like to be added**:
Remove the import of `conf.d` folder that is added [here](https://github.com/gardener/gardener/blob/454ad5ba2d67e99bbd4d0ce278b8fef838cb6ff6/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/templates/scripts/init.tpl.sh#L14-L30)
```bash 
head -n 1 /etc/containerd/config.toml
# Output:
# imports = ["/etc/containerd/conf.d/*.toml"]
```
This causes overwrite of configuration added in `/etc/containerd/config.toml` like [sandbox_image](https://github.com/gardener/gardener/blob/454ad5ba2d67e99bbd4d0ce278b8fef838cb6ff6/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/templates/scripts/init.tpl.sh#L10-L12)
```bash
grep -F -A 2 '[plugins."io.containerd.grpc.v1.cri"]' /etc/containerd/config.toml
# Output:
# [plugins."io.containerd.grpc.v1.cri"]
#   # use fixed sandbox image
#   sandbox_image = "registry.k8s.io/pause:3.7"
containerd config dump | grep sandbox_image
# Output:
# sandbox_image = "registry.k8s.io/pause:3.7"

# Now adding foo.toml

cat /etc/containerd/conf.d/foo.toml
# Output:
# [plugins."io.containerd.grpc.v1.cri".containerd]
#   discard_unpacked_layers = false
containerd config dump | grep sandbox_image
# Output:
# sandbox_image = "registry.k8s.io/pause:3.6"
```

**Why is this needed**:
Same issue has been hit [here](https://github.com/gardener/gardener/pull/7316)
The registry-cache extension that is under developement needs to change `containerd` configuration. If someone uses the import functionality and has enabled registry-cache for his shoots he will overwrite the registry-cache configuration and this will make the extension useless in those cases

[This PR](https://github.com/gardener/gardener/pull/7837) proposes the removal of the import functionality and proposes changes of the documentation for how to create custom `containerd` configuration 

It seems in 2.0 of containerd merging will happen rather than overriding but if we extrapolate the time between minor releases from https://containerd.io/releases/ it seems 2.0 will come at least after a year

**Comment by timebertt** [comment]
There is a new configuration option in [containerd 1.5](https://github.com/containerd/containerd/releases/tag/v1.5.0) (released in May 2021), which looks like a good replacement of the current containerd config imports and would simply the registry cache extension:
https://github.com/containerd/containerd/blob/main/docs/hosts.md
Also see https://kind.sigs.k8s.io/docs/user/local-registry/ for an example usage in kind.

I would try to rather use this configuration option instead of suggesting users and extensions to patch the main configuration file.

**Comment by ialidzhikov** [comment]
We are already aware of the new way of configuring containerd registries. See the updated details in https://github.com/gardener/gardener-extension-registry-cache/issues/3.

**Comment by timebertt** [comment]
Great. I would vote for keeping the `conf.d` import nevertheless and simply use the new host config dir as an additional mechanism.
I.e., I would vote for closing https://github.com/gardener/gardener/pull/7837
