### ISSUE TITLE
Missing secret audit-secret should not block reconciliation

### ISSUE THREAD

**Issue by lenhard** [gardener/gardener#7846]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:

- Some clusters that were marked for deletion could not be deleted because of infrastructure dependencies.
- During the deletion process, the associated `audit-secret` got deleted as well.
- At some point the infrastructure dependencies got resolved
- The clusters are now in a broken state with `lastOperation`:
```
description: 'Flow "Shoot cluster deletion" encountered task errors: [task "Deploying
  referenced resources" failed: retry failed with context deadline exceeded, last
  error: object not found {Secret audit-secret-539-9e-haas v1}]'
lastUpdateTime: '2023-04-25T22:46:01Z'
progress: 13
state: Failed
type: Delete
```
It is not possible anymore to trigger reconciliation for these shoots because of the error.
- I was told by @rfranzke to simply create an empty secret with the referenced name to enable the flow to continue.

If no actual secret is needed to continue here, then why does the controller fail at all? It could simply ignore the missing secret and continue without manual interaction.

**What you expected to happen**:

I expect that it is possible to trigger reconciliation for a shoot in this state.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`): 1.24.10
- Cloud provider or hardware configuration: Azure
- Others:

**Comment by rfranzke** [comment]
> If no actual secret is needed to continue here, then why does the controller fail at all? It could simply ignore the missing secret and continue without manual interaction.

Gardener cannot know whether the secret is needed for deletion or not since it is related to an extension. Hence, it has to redeploy them to cover all cases in general. 
The actual fix would be to protect such referenced secrets with a finalizer as long as there are still `Shoot`s referencing them. We already do this for other references. Will work on it.
