### ISSUE TITLE
CA not returned by api server during tls handshake

### ISSUE THREAD

**Issue by tareksha** [gardener/gardener#7905]
/area control-plane
/area security
/kind bug

**What happened**:

AWS requires the certificate authority to be present in the certificate chain that is returned by the jwt issuer. This way it can be verified against the thumbprint that is configured on the AWS side.

I am trying to configure AWS IRSA to trust the service account tokens in my gardener shoot. The api server in gardener shoots does not return a certificate chain that includes the CA - it only returns the server certificate.
Since the CA is not returned by that shoot's api server , authentication against AWS IRSA fails with error like this:
> InvalidIdentityToken: OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint

_mroe info from my side:_

AWS IAM stores only a hash (thumbprint) of the jwt issuer's certificate in the oidc trust configuration. As stated by AWS support personnel, this trust mechanism does not support verifying CAs not returned explicitly by the jwt issuer endpoint.

**What you expected to happen**:

api-server to return a certificate chain that contains the CA

**How to reproduce it (as minimally and precisely as possible)**:

Configure IRSA for gardener shoot
1. enable anonymous auth
2. give anonymous rbac for jwt discovery
3. in aws iam, put thumbprint of the CA (not api server cert) in oidc provider config
4. configure pod with irsa (role arn in env, projected token with correct audience)
5. aws auth fails due to mismatched jwt issuer cert

**Anything else we need to know?**:

I'm not sure but kubernetes api-server does seem to support returning a CA via `--tls-cert-file`. official doc:
> File containing the default x509 Certificate for HTTPS. (CA cert, if any, concatenated after server cert).

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

**Environment**:

- Gardener version: 1.68.2
- Kubernetes version (use `kubectl version`): 1.25.8
- Cloud provider or hardware configuration: aws
- Others:

**Comment by tareksha** [comment]
This is how it works right now:
1. Gardener issues a private CA for each shoot and signes api server certs with it. The shoot's kubeconfig includes the CA.
2. Standard k8s clients use kubeconfig and have the CA at hand so things work for them: they simply verify that the returned kapi certificate is signed by the CA from kubeconfig.
3. AWS IAM does not have the CA at hand. it only stores a certificate thumbprint. When it receives the top cert from api server it can't trust it directly because it is not signed by a public CA so it has two options:
    1. hash the received cert and compare with known thumbprint
    2. if a cert chain is received, walk the chain until one of the CAs (possibly intermediate) matches the known thumbprint. the chain walk itself is the standard secure method - each cert/CA in the chain is verified to be signed by the next one.

The problem is that AWS IAM does not store full CA, only a thumbprint. It can't check that the returned kapi certificate is signed with private CA of some sort. The CA itself must appear in the returned chain to be matched with the known thumbprint, in addition to verifying that it actually signed the kapi certificate through standard chain verification.

Returning a certificate chain is also a standard feature of kubernetes api servers per the documentation of `--tls-cert-file` cli argument.

@rfranzke 
@dimityrmirchev

**Comment by dimityrmirchev** [comment]
I think that this is implementable if we extend the `CertificateSecretConfig` with a similar to the [SkipPublishingCACertificate](https://github.com/gardener/gardener/blob/ec6f410d180868fded06122f53be16ed9892353f/pkg/utils/secrets/certificate.go#LL76C8-L76C8)  flag (`PublishCertificateChain` or something like this). Then we may pass the whole chain to the `kube-apiserver`. This can be configurable (or maybe not and we do this always 🤔 ). I am not sure if there are any downsides of doing this, i.e. serving the whole chain.

**Comment by rfranzke** [comment]
I don't think we should implement this since this eliminates the client's possibility to validate the server's authenticity.

**Comment by dimityrmirchev** [comment]
> this eliminates the client's possibility to validate the server's authenticity.

Maybe I am missing something but how exactly? You can still validate the server certificate by using the CA that you have acquired in a secure manner 🤔 Take `gardener.cloud` or `prow.gardener.cloud` for example. They return the whole certificate chain.

```bash
openssl s_client -servername gardener.cloud -showcerts -connect gardener.cloud:443
```

**Comment by tareksha** [comment]
> I don't think we should implement this since this eliminates the client's possibility to validate the server's authenticity.

@rfranzke I'm not sure what you mean by this. the certificate chain itself is checked by the clients and certificates inside it can't violate the standard certificate verification flow, including signing relationships between them.

this setup is common for https servers in the internet.

**Comment by vlerenc** [comment]
> Maybe I am missing something but how exactly? You can still validate the server certificate by using the CA that you have acquired in a secure manner 🤔 Take gardener.cloud or prow.gardener.cloud for example. They return the whole certificate chain.

But isn't this about AWS and AWS trusting it?

> this setup is common for https servers in the internet

For something signed by root CAs, sure. For self-signed certs it sounds pretty wrong. Have you more information.

Bottom line: Until we understand that this is safe, we will implement nothing. Please do some research and share information and background, so that we can assess this request.

**Comment by vlerenc** [comment]
P.S.: I used AWS IRSA some years back and had no problems giving it the required thumbnail. So, I have some difficulties understanding your difficulties. Can you share those as well, because I remember zero issues - it worked quite nicely.

**Comment by tareksha** [comment]
Hi @vlerenc,

IRSA does work but only using the thumbprint of the server certificate. Putting the thumbprint of the shoot's CA does not work because AWS only verifies the correctness of the certificate (or chain) that is presented by the api server and then, if it is not signed by a public CA, it tries to match its thumbprint with a list of user-provided thumbprints.

This is problematic for production systems because the api server certificate is not stable like the CA. It changes due to many reasons: k8s patches, landscape changes, or even some gardener-specific changes (e.g. the recent sni change). Each time this happens the system loses connectivity to aws services - an outage.

> For something signed by root CAs, sure. For self-signed certs it sounds pretty wrong. Have you more information.

Can you please elaborate on why is it wrong? A certificate is not sensitive info and it is publishable by definition, in contrary to the private key which is held internally by gardener.

Quoting to RFC 5246: certificate_list: This is a sequence (chain) of certificates.  The sender's certificate MUST come first in the list.  Each following certificate MUST directly certify the one preceding it.  Because certificate validation requires that root keys be distributed independently, the self-signed certificate that specifies the root certificate authority MAY be omitted from the chain, under the assumption that the remote end must already possess it in order to validate it in any case.

Since AWS IAM does not support uploading a private CA, returning it in the chain in gardener shoot api servers and putting its thumbprint in AWS IAM still keeps everything fully secure and compliant.

**Comment by vlerenc** [comment]
You might be interested in: https://github.com/gardener/gardener/issues/1413

> Can you please elaborate on why is it wrong? A certificate is not sensitive info and it is publishable by definition, in contrary to the private key which is held internally by gardener.

Will regular libraries fail to verify the server cert if the CA cert is in the chain, but not on the verifying machine @dimityrmirchev? If we do that as you suggested, the locally installed/known "root CAs" still apply and if the CA is not explicitly made available, the verification will still fail, correct?

> Quoting to RFC 5246: certificate_list: This is a sequence (chain) of certificates. The sender's certificate MUST come first in the list. Each following certificate MUST directly certify the one preceding it. Because certificate validation requires that root keys be distributed independently, the self-signed certificate that specifies the root certificate authority MAY be omitted from the chain, under the assumption that the remote end must already possess it in order to validate it in any case.

Yes, may be omitted. Since it is a custom CA, we omit it. We didn't want people to get "ideas" and take the CA out of the chain to use it to verify the request, which would be dumb, I guess.

> Since AWS IAM does not support uploading a private CA, returning it in the chain in gardener shoot api servers and putting its thumbprint in AWS IAM still keeps everything fully secure and compliant.

Yes, that's the exactly crux as it seems.

**Comment by vlerenc** [comment]
> https://www.rfc-editor.org/rfc/rfc5246#section-7.4.2

I am not expert enough to fully understand what this means.

My basic question: In a chain, obviously each preceding cert is verified by the next CA cert (must have signed the previous), but that also means, that it's used for the verification (clearly). In our case, it would end after the custom CA. So are libraries then ignoring it for cert verification and instead looking for a pre-distributed CA cert or not? If they ignore it, fine. If not, it's a security issue, right?

> MAY be omitted from the chain, under the assumption that the remote end must already possess it in order to validate it in any case.
      
This sentence sounds like it would be used for verification, if not omitted and that would be unsafe/a security issue, if true.

That's at least my interpretation of the sentence (omit if you have it locally implies: if contained in the chain, it's used for verification).

Can you find that out please @tareksha ?

**Comment by vlerenc** [comment]
When I think about this, it actually should always try to find the root CA locally and ignore the last CA in the chain, otherwise an attacker that presents a full chain would have already won and bypass the local root CAs and that cannot be true, I guess.

Then again, the browser case is different. A browser MUST follow to one of its root CAs, because it's written this way. Client libraries that validate certs... I don't know. I hope/assume, it's the same and if they see the CA, they want to verify by what it was signed - or it matches one of the installed ones. If it doesn't match and they don't have the signer, the verification should fail and we would be good.

I am not an expert and would like some confirmation of the same before we do such a thing.

**Comment by tareksha** [comment]
hi @vlerenc,

The server can't just put any CA cert A and claim that it signed cert B. The client checks the structure of both certificates according to TLS spec (checksums, metadata, ...). This is exactly the same method that the client uses for verifying that a server certificate is signed by a CA that is not presented in the chain but exists in the client-side trust store. Checking certificates on the client side is one the foundations of TLS.

> MAY be omitted from the chain, under the assumption that the remote end must already possess it in order to validate it in any case.

This sentence actually means the cert chain can omit the last part (root CA) and the client will continue the verification flow by searching its trust store for a CA that signed the chain. This is how a gardener kubeconfig actually works: the CA is provided separately via `certificate-authority-data` in kubeconfig, the client adds `certificate-authority-data` to its trust store and verifies that it signed the certificate presented by the shoot's api-server. This fact is easy to check - replace the CA in kubeconfig with anything else (even valid CA) and kubectl will start failing with errors like this:

> Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")

And the last part here: if the server presents a full chain that includes root CA then that root CA can't be just anything. the client verifies that it matches one of the CAs in its trust store.

**Comment by vlerenc** [comment]
@tareksha I haven't said any of that. Of course, it's not about the server adding just any CA (that's not even an attack). Of course, `kubectl` will fail if you change the CA in the `kubeconfig`. Etc.

@dimityrmirchev is out-of-office, but we will try the scenario manually (with the CA in the chain) and see how everything responds with and without pre-distributed CA.

**Comment by dimityrmirchev** [comment]
I did some patches to my local setup (`provider-local` based) in order to make the `kube-apiserver` return the whole certificate chain. From my testing it looks like that tools/libraries will fail the verification process (as expected) if the CA is not passed to them explicitly (or the CA is installed on the host) even if the CA is returned by the server as part of the certificate chain. See samples below.

### openssl

``` bash
 $ openssl s_client -servername api.local.local.internal.local.gardener.cloud -showcerts -connect api.local.local.internal.local.gardener.cloud:443
```
<details>
  <summary>Output</summary>

  ```logs
    CONNECTED(00000003)
    depth=1 CN = ca
    verify error:num=19:self signed certificate in certificate chain
    verify return:0
    write W BLOCK
    ---
    Certificate chain
    0 s:/CN=kube-apiserver
    i:/CN=ca
    -----BEGIN CERTIFICATE-----
    MIIEuzCCA6OgAwIBAgIQJA2llTjgCAPgPAD82X63ETANBgkqhkiG9w0BAQsFADAN
    MQswCQYDVQQDEwJjYTAeFw0yMzA1MTgwOTE1MjJaFw0zMzA1MTgwOTE1MjJaMBkx
    FzAVBgNVBAMTDmt1YmUtYXBpc2VydmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
    MIIBCgKCAQEApzYjvtsgQ3aVuIEM6Hm7YXr7s8jPW6LBekdnDbuuD8sXMl2m9mcR
    dTlf+XNXuUqFa6bCGlhQUnj07PaWWJ/D8NKBGV63SA0rzakh9YEkIP0iYY2W20qN
    kF8C1UgWCENkhXdZH6+Yb2wMFSRy3Xjru/ONFw12iAey8dUSWmZFanUI8X1iIgEt
    a2UuyzlLTug6dB2WmE5nn3NULS1HmUmBGPNuWcNkXdD7tPcxcBDbgCfUIoFPLa0g
    leZAVtHwvX+NrBKDpVoY6m6KTY2/6q/xucgAsgo/reIyXORgnIURiUoUn192y9da
    kzH3M6v8YynI/ztYgSKDWvGd4/R0XXikjwIDAQABo4ICCTCCAgUwDgYDVR0PAQH/
    BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHwYDVR0j
    BBgwFoAU0Td3tEURuJNvwUeg9Po8vxCMVa0wggGtBgNVHREEggGkMIIBoIIOa3Vi
    ZS1hcGlzZXJ2ZXKCImt1YmUtYXBpc2VydmVyLnNob290LS1sb2NhbC0tbG9jYWyC
    Jmt1YmUtYXBpc2VydmVyLnNob290LS1sb2NhbC0tbG9jYWwuc3ZjgjRrdWJlLWFw
    aXNlcnZlci5zaG9vdC0tbG9jYWwtLWxvY2FsLnN2Yy5jbHVzdGVyLmxvY2Fsggpr
    dWJlcm5ldGVzghJrdWJlcm5ldGVzLmRlZmF1bHSCFmt1YmVybmV0ZXMuZGVmYXVs
    dC5zdmOCJGt1YmVybmV0ZXMuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbIItYXBp
    LmxvY2FsLmxvY2FsLmludGVybmFsLmxvY2FsLmdhcmRlbmVyLmNsb3VkghNzaG9v
    dC0tbG9jYWwtLWxvY2Fsgilsb2NhbC5sb2NhbC5leHRlcm5hbC5sb2NhbC5nYXJk
    ZW5lci5jbG91ZIItYXBpLmxvY2FsLmxvY2FsLmV4dGVybmFsLmxvY2FsLmdhcmRl
    bmVyLmNsb3VkhwQKBAABhwR/AAABhwQKBAABMA0GCSqGSIb3DQEBCwUAA4IBAQCA
    D55dMvd6vD8fH9wwZ3oyVxrokCSOIFzYjJ49C3QjLE04ID0HSNeAipHM/EvcamIB
    DFJ2nWnDrTldBuR5sRRTkTti1WfiFR2Kf4pJICF8xXY07PqX6+ww7vUSYfOCvzu+
    RLZSZou0tFta7zlqkhXq6MUofn6QolcEru6ab56Uj7BPladv5e21g+x6lUXAdDX4
    w2wBsFNdknuTBy/v5QTmmnMyR1l/gCrAin0uL3+muGOhHioQtBLS8IuJnVOpBB1U
    /ooO5rdgtY7Vo3YJFFy4Nh8lCXKpfnPNQGGtDEjE83dYInLeXExMqbN3f9bRdsV/
    iIisF1EVRqO9ullbxRkq
    -----END CERTIFICATE-----
    1 s:/CN=ca
    i:/CN=ca
    -----BEGIN CERTIFICATE-----
    MIIC5zCCAc+gAwIBAgIRALl2grWPIlnCXjH4rw55CVAwDQYJKoZIhvcNAQELBQAw
    DTELMAkGA1UEAxMCY2EwHhcNMjMwNTE4MDkxNDM3WhcNMzMwNTE4MDkxNDM3WjAN
    MQswCQYDVQQDEwJjYTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKIN
    y351Mbz8b4mvlBACeNCa8mopLbauw/cdBJFAzMhoDK71TcAP8Y0SlZUC8Qt0vGux
    Jma/aM4w0pB8YSfFJwdbEANBLgyAqk+aJkIcwXTU6JIh9PKA/HkHy6nVFefFtEpx
    7QPOQjd8rdPtY5hpBc3NTbzNUbQudgUwfgIB2p1AY4z+ODlnX4iWaMlb3UKPj7hc
    Dri2OCWOboY936kOUIChB6pFFpQfVXYnIbeCboMWsctKriudbU8ppMyX9WW4yek1
    pa+axxD5+mSZ7KcRVVvxFUtTR7yc8VoRp1MaO6zrKsnpAKEmV30btsUc6LpKqnJ3
    H0sceAzuORRfeqqM/SsCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgGmMA8GA1UdEwEB
    /wQFMAMBAf8wHQYDVR0OBBYEFNE3d7RFEbiTb8FHoPT6PL8QjFWtMA0GCSqGSIb3
    DQEBCwUAA4IBAQBxnfolXctFr033JNts5sYqxUoekE2lKKnKG+bmJXlpRGV8cXXA
    uMb5OktHZ+WQYOqIluYscrryD6pI1AAaC0aEo1jHkn6/h7vovFaFgVUsB8+Pj8EQ
    1pEy0bA5FaDZaBU/URomOokDDMpozvH8OPgfqEBIQ5yMvR0V3x7U+DXpjL4i0xw4
    vyC7YpQ5oVECuk9hLikhwhIcdg6uhN0zIUQqubRtTjBfjTQJBVopG16YNRXtrV9b
    ZWOFuXin4oQ1k/vjv+ODimS6SykLq3NtLnZDGtIzc03+iKKr1YiBrfswf8VFoLsF
    WWduQrm/tMDJw/TcincjwqVdtBC6mZ0ymYbS
    -----END CERTIFICATE-----
    ---
    Server certificate
    subject=/CN=kube-apiserver
    issuer=/CN=ca
    ---
    No client certificate CA names sent
    Server Temp Key: ECDH, X25519, 253 bits
    ---
    SSL handshake has read 2642 bytes and written 435 bytes
    ---
    New, TLSv1/SSLv3, Cipher is AEAD-AES128-GCM-SHA256
    Server public key is 2048 bit
    Secure Renegotiation IS NOT supported
    Compression: NONE
    Expansion: NONE
    No ALPN negotiated
    SSL-Session:
        Protocol  : TLSv1.3
        Cipher    : AEAD-AES128-GCM-SHA256
        Session-ID:
        Session-ID-ctx:
        Master-Key:
        Start Time: 1684402280
        Timeout   : 7200 (sec)
        Verify return code: 19 (self signed certificate in certificate chain)
    ---
  ```
</details>

Of course passing the CA removes the verification error.

``` bash
 $ openssl s_client -CAfile ca.crt -servername api.local.local.internal.local.gardener.cloud -showcerts -connect api.local.local.internal.local.gardener.cloud:443
```

<details>
  <summary>Output</summary>

  ```logs
    CONNECTED(00000003)
    depth=1 CN = ca
    verify return:1
    depth=0 CN = kube-apiserver
    verify return:1
    write W BLOCK
    ---
    Certificate chain
    0 s:/CN=kube-apiserver
    i:/CN=ca
    -----BEGIN CERTIFICATE-----
    MIIEuzCCA6OgAwIBAgIQJA2llTjgCAPgPAD82X63ETANBgkqhkiG9w0BAQsFADAN
    MQswCQYDVQQDEwJjYTAeFw0yMzA1MTgwOTE1MjJaFw0zMzA1MTgwOTE1MjJaMBkx
    FzAVBgNVBAMTDmt1YmUtYXBpc2VydmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
    MIIBCgKCAQEApzYjvtsgQ3aVuIEM6Hm7YXr7s8jPW6LBekdnDbuuD8sXMl2m9mcR
    dTlf+XNXuUqFa6bCGlhQUnj07PaWWJ/D8NKBGV63SA0rzakh9YEkIP0iYY2W20qN
    kF8C1UgWCENkhXdZH6+Yb2wMFSRy3Xjru/ONFw12iAey8dUSWmZFanUI8X1iIgEt
    a2UuyzlLTug6dB2WmE5nn3NULS1HmUmBGPNuWcNkXdD7tPcxcBDbgCfUIoFPLa0g
    leZAVtHwvX+NrBKDpVoY6m6KTY2/6q/xucgAsgo/reIyXORgnIURiUoUn192y9da
    kzH3M6v8YynI/ztYgSKDWvGd4/R0XXikjwIDAQABo4ICCTCCAgUwDgYDVR0PAQH/
    BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHwYDVR0j
    BBgwFoAU0Td3tEURuJNvwUeg9Po8vxCMVa0wggGtBgNVHREEggGkMIIBoIIOa3Vi
    ZS1hcGlzZXJ2ZXKCImt1YmUtYXBpc2VydmVyLnNob290LS1sb2NhbC0tbG9jYWyC
    Jmt1YmUtYXBpc2VydmVyLnNob290LS1sb2NhbC0tbG9jYWwuc3ZjgjRrdWJlLWFw
    aXNlcnZlci5zaG9vdC0tbG9jYWwtLWxvY2FsLnN2Yy5jbHVzdGVyLmxvY2Fsggpr
    dWJlcm5ldGVzghJrdWJlcm5ldGVzLmRlZmF1bHSCFmt1YmVybmV0ZXMuZGVmYXVs
    dC5zdmOCJGt1YmVybmV0ZXMuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbIItYXBp
    LmxvY2FsLmxvY2FsLmludGVybmFsLmxvY2FsLmdhcmRlbmVyLmNsb3VkghNzaG9v
    dC0tbG9jYWwtLWxvY2Fsgilsb2NhbC5sb2NhbC5leHRlcm5hbC5sb2NhbC5nYXJk
    ZW5lci5jbG91ZIItYXBpLmxvY2FsLmxvY2FsLmV4dGVybmFsLmxvY2FsLmdhcmRl
    bmVyLmNsb3VkhwQKBAABhwR/AAABhwQKBAABMA0GCSqGSIb3DQEBCwUAA4IBAQCA
    D55dMvd6vD8fH9wwZ3oyVxrokCSOIFzYjJ49C3QjLE04ID0HSNeAipHM/EvcamIB
    DFJ2nWnDrTldBuR5sRRTkTti1WfiFR2Kf4pJICF8xXY07PqX6+ww7vUSYfOCvzu+
    RLZSZou0tFta7zlqkhXq6MUofn6QolcEru6ab56Uj7BPladv5e21g+x6lUXAdDX4
    w2wBsFNdknuTBy/v5QTmmnMyR1l/gCrAin0uL3+muGOhHioQtBLS8IuJnVOpBB1U
    /ooO5rdgtY7Vo3YJFFy4Nh8lCXKpfnPNQGGtDEjE83dYInLeXExMqbN3f9bRdsV/
    iIisF1EVRqO9ullbxRkq
    -----END CERTIFICATE-----
    1 s:/CN=ca
    i:/CN=ca
    -----BEGIN CERTIFICATE-----
    MIIC5zCCAc+gAwIBAgIRALl2grWPIlnCXjH4rw55CVAwDQYJKoZIhvcNAQELBQAw
    DTELMAkGA1UEAxMCY2EwHhcNMjMwNTE4MDkxNDM3WhcNMzMwNTE4MDkxNDM3WjAN
    MQswCQYDVQQDEwJjYTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKIN
    y351Mbz8b4mvlBACeNCa8mopLbauw/cdBJFAzMhoDK71TcAP8Y0SlZUC8Qt0vGux
    Jma/aM4w0pB8YSfFJwdbEANBLgyAqk+aJkIcwXTU6JIh9PKA/HkHy6nVFefFtEpx
    7QPOQjd8rdPtY5hpBc3NTbzNUbQudgUwfgIB2p1AY4z+ODlnX4iWaMlb3UKPj7hc
    Dri2OCWOboY936kOUIChB6pFFpQfVXYnIbeCboMWsctKriudbU8ppMyX9WW4yek1
    pa+axxD5+mSZ7KcRVVvxFUtTR7yc8VoRp1MaO6zrKsnpAKEmV30btsUc6LpKqnJ3
    H0sceAzuORRfeqqM/SsCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgGmMA8GA1UdEwEB
    /wQFMAMBAf8wHQYDVR0OBBYEFNE3d7RFEbiTb8FHoPT6PL8QjFWtMA0GCSqGSIb3
    DQEBCwUAA4IBAQBxnfolXctFr033JNts5sYqxUoekE2lKKnKG+bmJXlpRGV8cXXA
    uMb5OktHZ+WQYOqIluYscrryD6pI1AAaC0aEo1jHkn6/h7vovFaFgVUsB8+Pj8EQ
    1pEy0bA5FaDZaBU/URomOokDDMpozvH8OPgfqEBIQ5yMvR0V3x7U+DXpjL4i0xw4
    vyC7YpQ5oVECuk9hLikhwhIcdg6uhN0zIUQqubRtTjBfjTQJBVopG16YNRXtrV9b
    ZWOFuXin4oQ1k/vjv+ODimS6SykLq3NtLnZDGtIzc03+iKKr1YiBrfswf8VFoLsF
    WWduQrm/tMDJw/TcincjwqVdtBC6mZ0ymYbS
    -----END CERTIFICATE-----
    ---
    Server certificate
    subject=/CN=kube-apiserver
    issuer=/CN=ca
    ---
    No client certificate CA names sent
    Server Temp Key: ECDH, X25519, 253 bits
    ---
    SSL handshake has read 2642 bytes and written 435 bytes
    ---
    New, TLSv1/SSLv3, Cipher is AEAD-AES128-GCM-SHA256
    Server public key is 2048 bit
    Secure Renegotiation IS NOT supported
    Compression: NONE
    Expansion: NONE
    No ALPN negotiated
    SSL-Session:
        Protocol  : TLSv1.3
        Cipher    : AEAD-AES128-GCM-SHA256
        Session-ID:
        Session-ID-ctx:
        Master-Key:
        Start Time: 1684402919
        Timeout   : 7200 (sec)
        Verify return code: 0 (ok)
    ---
  ```

</details>

### curl

<details>
  <summary>Samples</summary>
  Without provided CA.

  ```logs
    $ curl https://api.local.local.internal.local.gardener.cloud
    curl: (60) SSL certificate problem: self signed certificate in certificate chain
    More details here: https://curl.se/docs/sslcerts.html

    curl failed to verify the legitimacy of the server and therefore could not
    establish a secure connection to it. To learn more about this situation and
    how to fix it, please visit the web page mentioned above.
  ```

  With provided CA.

  ```logs
    $ curl  --cacert ca.crt https://api.local.local.internal.local.gardener.cloud
    {
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "Unauthorized",
    "reason": "Unauthorized",
    "code": 401
    }
  ```
</details>

### go

<details>
  <summary>Code sample</summary>

  ```go
    package main

    import (
      "context"
      "crypto/tls"
      "crypto/x509"
      "fmt"
      "net/http"
      "time"
    )

    var castring = `
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
    `

    func main() {
      // error check skipped for brevity
      req, _ := http.NewRequestWithContext(context.Background(), "GET", "https://api.local.local.internal.local.gardener.cloud", nil)
      _, err := http.DefaultClient.Do(req) // using the default client will fail
      if err != nil {
        fmt.Println(err)
      }

      pool := x509.NewCertPool()
      pool.AppendCertsFromPEM([]byte(castring))
      tlsConfig := &tls.Config{
        RootCAs: pool,
      }
      c := &http.Client{
        Transport: &http.Transport{
          TLSClientConfig: tlsConfig,
        },
        Timeout: time.Second * 3,
      }
      _, err = c.Do(req)
      if err != nil {
        fmt.Println("we will not see this since the request succeeded")
      }
    }

  ```
</details>

<details>
  <summary>Output</summary>

  ```bash
    $ go run test.go 
    Get "https://api.local.local.internal.local.gardener.cloud": tls: failed to verify certificate: x509: “kube-apiserver” certificate is not standards compliant
  ```

</details>

### python

<details>
  <summary>Code sample</summary>

  ```python
  import requests

  try:
      r = requests.get('https://api.local.local.internal.local.gardener.cloud')
  except Exception as e: 
      print(e)

  ```
</details>

<details>
  <summary>Output</summary>

  ```bash
    $ python3.10 ./test.py 
    HTTPSConnectionPool(host='api.local.local.internal.local.gardener.cloud', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
  ```

</details>

**Comment by tareksha** [comment]
thanks a lot for the detailed report @dimityrmirchev !
@rfranzke @vlerenc how do you suggest we proceed from here?

**Comment by vlerenc** [comment]
Thank you @dimityrmirchev.

**Comment by rfranzke** [comment]
Thanks for the analysis @dimityrmirchev. We had a chat and now plan to unconditionally add the signing CA certificate to the server certificate for `kube-apiserver` for all shoots (no configuration option needed in the `Shoot` spec).

**Comment by tareksha** [comment]
great news, thanks @rfranzke. which gardener release is expected to include this change?

**Comment by rfranzke** [comment]
[`1.72`](https://github.com/gardener/gardener/blob/master/docs/development/process.md#release-responsible-plan) earliest. PR opened: https://github.com/gardener/gardener/pull/7961

**Comment by tareksha** [comment]
excellent! thanks a lot for the co-operation colleagues :)
