### ISSUE TITLE
PeerURL is not TLS enabled for non-HA shoots

### ISSUE THREAD

**Issue by ishan16696** [gardener/gardener#7924]
/area high-availability
/kind bug

**What happened**:
It has been observed that etcd's peerURL is not TLS enabled for non-HA shoots.
```
+------------------+---------+-------------+------------------------------------------------------------------+-------------------------------------------------------------------+------------+
|        ID        | STATUS  |    NAME     |                            PEER ADDRS                            |                           CLIENT ADDRS                            | IS LEARNER |
+------------------+---------+-------------+------------------------------------------------------------------+-------------------------------------------------------------------+------------+
| 47d2a75f6e2eaf35 | started | etcd-main-0 | http://etcd-main-0.etcd-main-peer.shoot--i539698--tests.svc:2380 | https://etcd-main-0.etcd-main-peer.shoot--i539698--tests.svc:2379 |      false |
+------------------+---------+-------------+------------------------------------------------------------------+-------------------------------------------------------------------+------------+
```

Previously peerURL TLS was enabled if `existingEtcd.Spec.Etcd.PeerUrlTLS != nil` but in this PR https://github.com/gardener/gardener/pull/7554 condition to enable peerURL TLS changed to only if shoots is HA.

**Why it is noticed now**:
With backup-restore `v0.24.0` we made some changes like `if scale-up case is detected try until you add a learner`: https://github.com/gardener/etcd-backup-restore/blob/v0.24.0/pkg/initializer/initializer.go#L67-L77
And druid adds a annotation of scale-up as `.spec.replicas` is not set to `3` 

**Why it is not noticed on any of landscapes**:
With backup-restore `v0.23.0` or before we were not `adding a learner untill succeed`: https://github.com/gardener/etcd-backup-restore/blob/v0.23.0/pkg/initializer/initializer.go#L63-L68

**What you expected to happen**:
PeerURL should be TLS enabled for non-HA shoots as well, so that while migrating from non-HA to HA, there won't be any restart of etcd's zeroth pod to update peerURL from `http` to `https`.

**How to reproduce it (as minimally and precisely as possible)**:
1. create a non-HA shoot
2. checked the etcd's member list:
```
bash-5.1# etcdctl --cert=/var/etcd/ssl/client/client/tls.crt --key=/var/etcd/ssl/client/client/tls.key --cacert=/var/etcd/ssl/client/ca/bundle.crt --endpoints=https://etcd-main-local:2379 member list -w table
```

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timuthy** [comment]
> Previously peerURL TLS was enabled if existingEtcd.Spec.Etcd.PeerUrlTLS != nil

**Comment by timuthy** [comment]
> Previously peerURL TLS was enabled if existingEtcd.Spec.Etcd.PeerUrlTLS != nil

**Comment by timuthy** [comment]
> Previously peerURL TLS was enabled if existingEtcd.Spec.Etcd.PeerUrlTLS != nil

`PeerTLS` has never been enabled for non-HA shoots. If we had enabled it, all `etcd`s of all control-planes would have been recreated. That's what we wanted and still want to prevent.

**Comment by ishan16696** [comment]
Hi @timuthy ,
I don't remember what was decided, I saw this line: https://github.com/gardener/gardener/pull/7554/files#diff-edb9775351eb76aaf28e8baca372b1ecbb9278348d59e531c23594fa3b84c089L261 had been removed in this PR: https://github.com/gardener/gardener/pull/7554
>If we had enabled it, all etcds of all control-planes would have been recreated. That's what we wanted and still want to prevent.

what's the point of this when old non-HA shoot will move to HA, then there will be a etcd statefulset recreation, so eventually there will be a downtime.

**Comment by timuthy** [comment]
The referred line has to be seen in context to the implementation before this change. Again, `PeerURLTLS` has never been enabled for non-HA shoots and I don't see a reason to do so right now, only because Druid can't handle this use-case.

**Comment by ishan16696** [comment]
I'm almost 100% sure that for new non-HA shoots peerURL was TLS enabled. I have saw it myself while testing quorom loss recovery playbook and while working on this PR: https://github.com/gardener/etcd-backup-restore/pull/564 
But I'm not sure about old non-HA shoots what was decided as I was not involved in this feature handling.
Also, In this comment: https://github.com/gardener/etcd-druid/pull/421#discussion_r972920686
@unmarshall  mentioned
```
With https://github.com/gardener/gardener/pull/6533 even single member etcd will have peer URL TLS enabled
```

**Comment by timuthy** [comment]
The [comment you refer to](https://github.com/gardener/etcd-druid/pull/421#discussion_r972920686) was written on Sep16, 2022. This was before the [related PR](https://github.com/gardener/gardener/pull/6533) was merged. Since then there have been updates to the PR which changed the plan mentioned by @unmarshall

![image](https://github.com/gardener/gardener/assets/40451181/20f455e4-6efc-4d59-a449-abe9d48c5384)

> I'm almost 100% sure that for new non-HA shoots peerURL was TLS enabled.

I'm open to be proven wrong, please based on **released code** not on outdated comments or memories.

**Comment by ishan16696** [comment]
> I'm open to be proven wrong, please based on released code not on outdated comments or memories.

Please refer to this condition: https://github.com/gardener/gardener/pull/7554/files#diff-edb9775351eb76aaf28e8baca372b1ecbb9278348d59e531c23594fa3b84c089L261

```go
peerTLSAlreadyEnabled := existingEtcd != nil && existingEtcd.Spec.Etcd.PeerUrlTLS != nil
```
it calculates `peerTLSAlreadyEnabled` boolean based on PeerUrlTLS passed to etcd spec or not.
it was not done on the basis of `.spec.replicas` (HA or non-HA)

As I mentioned I was not involved this feature and I also don't have much insight on this.
If people involved in this discussion haven’t responded it yet although I have opened the issue 24 hours ago, then I see no point of having argument of whether it was enabled or not.
I'm closing this issue feel free to open it if somebody feels otherwise
/close
