### ISSUE TITLE
GCM reference protection controller is not (un)setting the finalizer on the referenced resources or does it too late

### ISSUE THREAD

**Issue by mimiteto** [gardener/gardener#7955]
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
* User added a cm
* User was creating a shoot with auditlog policy enabled ([like this](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_auditpolicy.md))
* User was able to remove their auditlog policy configmap and their shoot failed to create

**What you expected to happen**:
User not to be able to break their shoot during deployment.

**How to reproduce it (as minimally and precisely as possible)**:
* create a configmap ([here, but change the namespace](https://github.com/gardener/gardener/blob/master/example/95-configmap-custom-audit-policy.yaml))
* Create a shoot with the spec from [doc](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_auditpolicy.md) added
* Delete the cm with `kubectl delete cm auditlog`
* Edit out the finalizer from that cm (`kubectl patch configmap auditlog --type json --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'`)
* configmap is deleted and cluster fails to create

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.70.2
- Kubernetes version (use `kubectl version`):  v1.26.2 (doesn't really matter ) 
- Cloud provider or hardware configuration: Any
- Others:

**Comment by vpnachev** [comment]
Just faced another occurrance of this issue, but this time it was not the audit policy configmap but a secret mounted via `shoot.spec.resources`. Checking also the audit events shows that the reference protection finalizer of the referenced secret was never set by GCM. There is also no log from GCM that it even attempted to set it. 


Running local gardener version v1.70.2, I also fail to see GCM to set the protection finalizer. Also the seed authorizer does not build the relation and disallows requests from gardenlet to read the configmap. 

Here are the steps I've executed:
1. `make kind-up`
2. `make gardener-up`
3. `kubectl -n garden-local create configmap foo`
4. `kubectl create -f example/provider-local/shoot.yaml` and wait the creation to be completed. 
5. `kubectl -n garden-local edit shoot local` and set
```yaml
spec:
  resources:
    - name: foo
      resourceRef:
        kind: ConfigMap
        name: foo
        apiVersion: v1
```


After some time:
1. Check the reference protection finalizer has not been set on the configmap (open watch with `k -n garden-local get cm foo -o yaml -w`) 
2. Check the last operation of the shoot is failing with error like  
```
task "Deploying referenced resources" failed: retry failed with context deadline exceeded, last error: configmaps "foo" is forbidden: User "gardener.cloud:system:seed:local" cannot get resource "configmaps" in API group "" in the namespace "garden-local": no relationship found between seed 'local' and this object
```
3. Check gardener-admission-controller logs to see that it fails to find the relationship between the resources
```
{"level":"info","ts":"2023-05-23T12:56:56.823Z","logger":"webhook.seedauthorizer","msg":"Denying authorization because no relationship is found between seed and object","seedName":"local","attributes":"authorizer.AttributesRecord{User:(*user.DefaultInfo)(0xc000b27c00), Verb:\"get\", Namespace:\"garden-local\", APIGroup:\"\", APIVersion:\"v1\", Resource:\"configmaps\", Subresource:\"\", Name:\"foo\", ResourceRequest:true, Path:\"\"}"}
```
4. Check the GCM logs to ensure there is no attempt from GCM to protect the referenced resource.
5. Change shoot.spec.resources[0].name value to `foo2` and ensure steps 1-4 are all still failing.


/title GCM reference protection controller is not setting the finalizer on the referenced resources or does it too late

**Comment by vpnachev** [comment]
/retitle GCM reference protection controller is not (un)setting the finalizer on the referenced resources or does it too late

**Comment by acumino** [comment]
> Here are the steps I've executed:
> 
> 1. `make kind-up`
> 2. `make gardener-up`
> 3. `kubectl -n garden-local create configmap foo`
> 4. `kubectl create -f example/provider-local/shoot.yaml` and wait the creation to be completed.
> 5. `kubectl -n garden-local edit shoot local` and set

~~ConfigMap is not supported to be referenced, only secret is supported as of now [ref](https://github.com/gardener/gardener/blob/4507f53471f8f982e1351af499a5ed2804ee65d4/pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_shoot.go#L139-L145).~~

ConfigMap need to be added here - 
https://github.com/gardener/gardener/blob/4507f53471f8f982e1351af499a5ed2804ee65d4/pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_shoot.go#L139-L145

**Comment by acumino** [comment]
> * create a configmap ([here, but change the namespace](https://github.com/gardener/gardener/blob/master/example/95-configmap-custom-audit-policy.yaml))
> * Create a shoot with the spec from [doc](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_auditpolicy.md) added
> * Delete the cm with `kubectl delete cm auditlog`
> * Edit out the finalizer from that cm (`kubectl patch configmap auditlog --type json --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'`)
>  configmap is deleted and cluster fails to create

The finalizer is there to prevent secret deletion, I don't think there is a good way to stop users to remove the finalizer.
/cc @rfranzke
