### ISSUE TITLE
gardener-controller-manager cannot read secrets "gardener"

### ISSUE THREAD

**Issue by Ntr0** [gardener/gardener#799]
I setup a gardener control plane in kubernetes, following the tutorials. I installed the gardener controlplane into namespace "garden", and added a namespace for the seed cluster "garden-dev". I tried then to deploy a seed and a shoot cluster, but all I get is that the gardener-controller-manager complains that the "gardener" secret cannot be retrieved.

time="2019-03-07T08:52:38Z" level=error msg="Could not initialize Shoot client for garbage collection of shoot garden-dev/johndoe-openstack: secrets \"gardener\" not found" shoot=garden-dev/johndoe-openstack

First the secret was only deployed to garden-dev, but to be sure I also deployed it to the garden namespace.

Would be glad if I could get some hints how to proceed.

**Comment by rfranzke** [comment]
Hi @Ntr0, this message is just coming from the health check, you can ignore it for now. More interesting is the `status` of the `Shoot` resource you created. Can you please share that?

**Comment by Ntr0** [comment]
Thanks for the hint. The error was misleading indeed. So the shoot resource complains that several extension controllers are missing. As the examples contained only aws related information I skipped this. So I need to figure out how to deploy the extension controllers for openstack.

**Comment by rfranzke** [comment]
OK. Currently, we only have operating system config extensions, you can apply https://github.com/gardener/gardener-extensions/blob/0.4.0/controllers/os-coreos/example/controller-registration.yaml to your garden cluster and try again

**Comment by Ntr0** [comment]
Thanks for your help. That solved my issue.
