### ISSUE TITLE
Investigate GKE

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#8]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:44 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/15_

----

Check out https://cloud.google.com/container-engine. What would be necessary to do in order to remotely provision/manage/operate/access those clusters (instead of our native ones on that IaaS) and what would be the limitations? Please report results here.

:information_source: Migrated from Jira issue [KUBE-89](https://jtrack.removed/browse/KUBE-89)

**Comment by vlerenc** [comment]
Won't do.
