### ISSUE TITLE
OS image - maintenance controller strategy

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#8013]
**How to categorize this issue?**

/area quality
/kind enhancement

### **What would you like to be added**:

Align the OS and Kubernetes version maintenance.

To cope with versioning differences (though have to be valid SemVer) of OS images, introduce strategies `autoUpdateStrategy: {major, minor, patch}` that can be set on a `MachineImage`.
- `patch`: update to the latest patch version of the current minor version. When using an `expired version`: force update to the latest patch of the current minor. If already on the latest patch version, then force update to the <s>consecutive</s> next higher (as defined in the cloud profile) minor. <s>This is the same behavior as for Kubernetes versions</s> .
- `minor` update to the latest minor and patch version. When using an `expired version`: force update to the latest minor and patch of the current major. If already on the latest minor and patch of the current major, then update to the <s>consecutive</s> next higher (as defined in the cloud profile) major version 
- `major` always update to the overall latest version. This is the current behavior for OS image versions. Force updates will fail, as the latest version in the CloudpProfile for that image is expired (EOL scenario). 

Strategy independent rules
- always first try to update to the latest patch version of the same minor (essentially the auto-update for strategy `patch`).
- auto update prefers supported versions over deprecated versions. If there is a lower supported version and a higher deprecated version, auto update will pick the supported version. If all qualifying versions are deprecated, update to the latest deprecated.
- auto update never updates to expired versions
- force update prefers to update to not-expired versions. If all qualifying versions are expired, update to the latest expired version. This potentially causes consecutive force updates.
- force updates for machine images can skip minor versions (strategy: patch) or major versions (strategy: minor) if the next minor/major version has no qualifying versions (see post in comments).
- force updates for K8s versions cannot skip minor versions (will fail).
 
When is either an **auto** update or a **force** update triggered:
- Auto update:
    - auto-update is enabled and the machine/K8s version is not the latest version according to the strategy (latest version in major for strategy `minor`, latest patch version for strategy `patch` (same for k8s versions), or latest overall version for strategy `major`). 
    - auto-update is disabled, the version is either expired or does not exist (legacy). If the auto-update for expired versions fails, triggers a force update. This is the case when the auto-update cannot find a qualifying version because the machine/K8s version is already the latest version according to the machine image strategy.
- Force update: the version is expired and is the highest version according to the machine image strategy (k8s: latest patch version of minor). 

The `autoUpdateStrategy: minor` is helpful to adequately handle an OS such as [Gardenlinux](https://github.com/gardenlinux/gardenlinux/releases), that only updates major and minor versions (`934.7`, `934.8`, `1148.0`).

Example `CloudProfile`

```
machineImages:
  - name: gardenlinux
     autoUpdateStrategy: minor
     versions:
     - version: 934.8.0
     - version: 934.7.0
  - name: suse-chost
     autoUpdateStrategy: patch
     versions:
    - version: 15.3.20220818 
    - version: 15.3.20221118

```
**Why is this needed**:

The maintenance in the GCM for Kubernetes and OS image versions is different today.  For Kubernetes versions, the following logic is implemented:
- deprecated version + auto-update -> update to the latest supported version of the same minor.
- expired versions -> force update to the latest patch version of the consecutive minor version 

For OS image versions:
- deprecated version + auto-update -> update to the overall latest supported version
- expired version -> update to the overall latest supported version

The K8s version policy recognizes that Kubernetes versions are safe to be upgraded across patch versions, but not safe to be upgraded across minor/major versions (e,g 1.22.0 --> 1.24.0 is not possible). On the other hand, the OS image versions policy assumes that an update to the latest OS version is always safe - even across minor and major versions. But that is not the case. There can be significant differences from OS version to OS version. Examples:
- cgroupsv2 superseding cgroupsv1. Some stakeholder workloads require cgroupsv1 (e.g some older JVM versions that don't understand cggroupsv1)
- Introduction of secure boot
- Removal of docker from OS images. 

Why using the `preview` classification is not enough to ensure safe OS-version upgrades
- Given two OS versions `534.0.0` and `976.0.0`. `976.0.0` has an incompatible change from `534.0.0`.  A critical security vulnerability in one of the packages in `534.0.0` is discovered. Stakeholders are still using `534.0.0` and would break upon an update to `976.0.0`. We can simply introduce a version `534.0.1` and all Shoots with auto-update enabled are updated without having to use a `976.X.X` version.

Hence, a Gardener operator needs more control over the OS image version maintenance - similar to how it's possible for Kubernetes versions today.

**Comment by danielfoehrKn** [comment]
The above "minor" and "patch" strategy for machine image updates does not work for force updates of  GL versions such as from `934.X.X` to `1148.X.X`. This is because `1148` is not consecutive (n+1). 
- Kubernetes versions require a force update to the next minor (n+1), 
- Machine image versions are fine to update to the next higher minor/major version as defined in the CloudProfile.

Hence those approaches require a distinct approach unlike initially described above.

**Comment by rfranzke** [comment]
Sounds reasonable, but what does 

> those approaches require a distinct approach unlike initially described above.

mean?

**Comment by danielfoehrKn** [comment]
Initially, I mentioned that the Kubernetes version upgrade and machine image version upgrade using the strategy: "patch"  use the same logic. Just stating the obvious that this is no longer the case (hence potentially requiring different code paths, ..). Sorry for the confusion.

**Comment by danielfoehrKn** [comment]
Maybe someone has an input for me here: what shall the policy be, when 
- the shoot uses an image with strategy: "patch"
- the shoot's worker requires force update
- the next higher minor version maintained in the cloudprofile does not contain any qualifying version (all are in preview, expired versions are upgraded to if necessary)
- there is an even higher minor version that contains qualifying versions

For example when Shoot uses `suse-chost` with version `15.3.0`
```
machineImages:
  - name: suse-chost
     autoUpdateStrategy: patch
     versions:
    - version: 15.3.0
       expirationDate: <inThePast>
    - version: 15.4.1 # all in preview for minor
       classification: preview
    - version: 15.5.0
       classification: supported
```

What should be done in this case
1) Fail force-update complaining that there are no qualifying versions in the next higher minor version
2) Skip next higher minor version and directly update to `15.5.0`

Currently, my approach is 2) as I did not want to fail a force update if at all possible (so that image version can be removed from the landscape).

**Comment by rfranzke** [comment]
I would also vote for 2) for now.

**Comment by timebertt** [comment]
+1 for option 2

**Comment by danielfoehrKn** [comment]
Noting another edge case here (will add to the documentation): in the example above, if there is another expired non-preview version `15.4.0`, we'll update to this version instead of skipping over the minor. This will cause another consecutive force update in the next maintenance window. This is similar to the maintenance of K8s versions. 

Follows the rule: update to the next minor if there are qualifying versions available for that minor. Qualifying versions for a force update are all but preview versions.

**Comment by danielfoehrKn** [comment]
Another thing that I just noticed: the maintenance controller allows updates to expired k8s and machine image versions, but that's rejected by the APIServers admission plugin, [here](https://github.com/gardener/gardener/blob/73eb7d2be194bbd769b334266a3a998074ada675/plugin/pkg/shoot/validator/admission.go#L1222) for Kubernetes versions and [here](https://github.com/gardener/gardener/blob/73eb7d2be194bbd769b334266a3a998074ada675/plugin/pkg/shoot/validator/admission.go#L1509) for machine images.

The maintenance controllers' behaviour is also consistent with the documentation:

> Please note that multiple consecutive minor version upgrades are possible. This can occur if the Shoot is updated to a version that in turn is also expired. In this case, the version is again upgraded in the next maintenance time. Depending on the circumstances described above, it can happen that the cluster receives multiple consecutive minor Kubernetes version updates!

I still think it makes sense to allow using an expired machine image or kubernetes version, it will just be upgraded in the next maintenance cycle. Otherwise, we cannot upgrade "through" a minor/major version that has only expired versions (EDIT: that's very relevant for Kubernetes versions which need to be consecutive).

Example: 
```
  - name: suse-chost
     versions:
    - version: 15.5.0
    - version: 15.4.1 # all expired for minor
      expirationDate: <inThePast>
    - version: 15.2.0 # --> cannot be updated
      classification: supported
``` 

I would therefore adjust the admission plugins accordingly to allow the usage of expired versions during Shoot updates (but not on creation).
