### ISSUE TITLE
CoreOS systemd-journal memory issue

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#804]
It seems the latest CoreOS Container Linux version we use has a memory issue in systemd-journal. In some cases it's using 6Gi on the node, bringing it under severe memory pressure. We expect a fix by CoreOS soon.

**Comment by vpnachev** [comment]
Let me drop a link to the PR #796 , where the issue was discussed, too.

**Comment by vpnachev** [comment]
This issue should be closed by #811 .
