### ISSUE TITLE
GRM's system-components-config webhook should not add the `ToBeDeletedByClusterAutoscaler` toleration (maintained by the cluster-autoscaler)

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#8154]
**How to categorize this issue?**

/area ops-productivity
/kind bug

**What happened**:
With @rishabh-11 we found the following issue:
Key logs from the event logger:
```
2023-06-22 03:38:39	{"_entry":"Scale-down: removing node shoot--foo--bar-worker-opt-z3-56ccb-k9rzq, utilization: {0.00859322033898305 0.0032986741384152035 0 cpu 0.00859322033898305}, pods to reschedule: vpn-shoot-0","count":1,"firstTimestamp":"2023-06-22T03:38:39Z","lastTimestamp":"2023-06-22T03:38:39Z","namespace":"kube-system","object":"ConfigMap/cluster-autoscaler-status","origin":"shoot","reason":"ScaleDown","source":"cluster-autoscaler","type":"Normal"}
2023-06-22 03:38:39	{"_entry":"deleting pod for node scale down","count":1,"firstTimestamp":"2023-06-22T03:38:39Z","lastTimestamp":"2023-06-22T03:38:39Z","namespace":"kube-system","object":"Pod/vpn-shoot-0","origin":"shoot","reason":"ScaleDown","source":"cluster-autoscaler","type":"Normal"}

2023-06-22 03:39:11	{"_entry":"Successfully assigned kube-system/vpn-shoot-0 to shoot--foo--bar-worker-opt-z3-56ccb-k9rzq","eventTime":"2023-06-22T03:39:11.984938Z","namespace":"kube-system","object":"Pod/vpn-shoot-0","origin":"shoot","reason":"Scheduled","type":"Normal"}
```

You can see that the kube-system/vpn-shoot-0 Pod was successfully evicted. But the issue is that then it got scheduled to the same Node.
This is a cluster with the following cluster-autoscaler config:
```yaml
spec:
  kubernetes:
    clusterAutoscaler:
      maxGracefulTerminationSeconds: 129600 # 36h
```

We see that currently the vpn-shoot-0 Pod (and my other gardener Pods) tolerate the cluster-autoscaler taints:
```yaml
% k -n kube-system get po vpn-shoot-0 -o yaml | yq '.spec.tolerations'
- effect: PreferNoSchedule
  key: DeletionCandidateOfClusterAutoscaler
  operator: Equal
  value: "1687320358"
- effect: NoSchedule
  key: ToBeDeletedByClusterAutoscaler
  operator: Equal
  value: "1687448378"
- effect: PreferNoSchedule
  key: DeletionCandidateOfClusterAutoscaler
  operator: Equal
  value: "1687404718"
- effect: NoSchedule
  key: ToBeDeletedByClusterAutoscaler
  operator: Equal
  value: "1687448388"
- effect: NoExecute
  key: node.kubernetes.io/not-ready
  operator: Exists
  tolerationSeconds: 60
- effect: NoExecute
  key: node.kubernetes.io/unreachable
  operator: Exists
  tolerationSeconds: 60
```

You can see that the vpn-shoot-0 is tolerating the ToBeDeletedByClusterAutoscaler taint. Hence, such evicted Pod can be scheduled on a Node that is being scaled down by cluster-autoscaler. The component causing the troubles is the GRM's system-components-config webhook (introduced with https://github.com/gardener/gardener/pull/7204).

In the corresponding webhook in gardener-resource-manager we have to make sure that the cluster-autoscaler taint(s) are not messed up because it breaks cluster-autoscaler handling.

Because of this, cluster-autoscaler enters in https://github.com/gardener/autoscaler/blob/c127763a4529d7d07961102856afe0ba8781f8ee/cluster-autoscaler/core/scaledown/actuation/drain.go#L133-L155 and waits for `maxGracefulTerminationSeconds` (36h) in this case until it drains the Node.

**What you expected to happen**:
GRM's system-components-config webhook should not add the `ToBeDeletedByClusterAutoscaler` taint. It simply breaks cluster-autoscaler's internal drain/eviction for Node scale down.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.73.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timuthy** [comment]
Should be as easy as enhancing the Kubernetes reserved taints logic ([ref](https://github.com/gardener/gardener/blob/17ff592e734131ef746560641bdcdec3bcfce0f1/pkg/resourcemanager/webhook/systemcomponentsconfig/handler.go#L120)). Is this already an assignment for yourself @ialidzhikov?

**Comment by FullyScaled** [comment]
Thank you again for providing a fix for this.

I assume that this fix will not be shipped directly to the live landscape. Can you give an estimation when it reaches the live landscape as we are currently discussing other mitigation options to prevent increased costs over the next weeks until the fix reaches live landscape.

**Comment by ialidzhikov** [comment]
From OSS project perspective, I can only share that we can include it in the upcoming minor release (v1.74.0).
In the OSS project we avoid discussing internal topics like landscapes, ETA, etc. Let's discuss this internally.
