### ISSUE TITLE
Contradicting Statements in the SecretManager Documentation

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#8183]
**How to categorize this issue?**

/area documentation
/kind bug

**What happened**:
I am reading https://github.com/gardener/gardener/blob/v1.73.1/docs/development/secrets_management.md#certificate-signing and find contradicting the following statements 

> server certificate are signed by the old CA (if it exists). This is to ensure a smooth exchange of certificate during a CA rotation
> ...
> **Always Sign Server Certificates with Current CA**

Same contradiction is available also for the client certificates. 

**What you expected to happen**:
Straight forward non-contradicting statements in the documentation

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timuthy** [comment]
Since the documentation doesn't seem to be obviously contradicting in the extract mentioned in this issue, it would be helpful to get your input via a pull request that proposes the particular doc change leading to a better understanding.

**Comment by vpnachev** [comment]
I would love to open a PR instead of an issue, but to me is not quite clear which CA must sign the server certificate.
And this is exactly what contradicts currently in the documentation, it is firstly explained that the server certificate must be signed by the old CA, and then with bold font exactly the opposite is stated - the server certificate to be signed by the current(new) CA.

**Comment by timebertt** [comment]
`Always Sign Server Certificates with Current CA` is a header that starts a new subsection explaining how to do the opposite to the general rule (signing server certificates with the old CA). The first sentence explains, when this is possible:

> In case you control all clients and update them at the same time as the server, it is possible to make the secrets manager generate even server certificates with the new/current CA

**Comment by vpnachev** [comment]
I opened #8207 trying to clarify this exception.
