### ISSUE TITLE
Possibility to leak secret `extension-controlplane-shoot` and prevent shoot deletion

### ISSUE THREAD

**Issue by Kostov6** [gardener/gardener#8190]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
https://github.com/gardener/gardener/blob/445ba3d395704755bb2a0c5719d1a0ec47f1023d/pkg/resourcemanager/controller/secret/reconciler.go#L81-L86
On shoot deletion if a slowdown happens when removing finalizer of secret `extension-controlplane-shoot`
shoot might fail to get deleted. That's because shoot's GRM can get terminated before the removal of GRM's finalizer for secret `extension-controlplane-shoot`. Secret can remain with a remaining GRM finalizer that prevents it's deletion and therefore interrupts shoot deletion

From a gardenlet logs for the corresponding Shoot:
```
2023-06-20 14:23:30	{"log":{"controller":"shoot","flow":"Shoot cluster deletion","level":"info","msg":"Succeeded","name":"bar","namespace":"garden-foo","object":{"name":"bar","namespace":"garden-foo"},"operation":"delete","reconcileID":"11727ea7-7808-4f12-bbf4-d64ee28e9fa1","task":"Destroying shoot control plane","ts":"2023-06-20T14:23:30.759Z"}}

2023-06-20 14:23:32	{"log":{"controller":"shoot","flow":"Shoot cluster deletion","level":"info","msg":"Succeeded","name":"bar","namespace":"garden-foo","object":{"name":"bar","namespace":"garden-foo"},"operation":"delete","reconcileID":"11727ea7-7808-4f12-bbf4-d64ee28e9fa1","task":"Destroying gardener-resource-manager","ts":"2023-06-20T14:23:32.672Z"}}
```

We can see that GRM has around 2 seconds to remove `extension-controlplane-shoot` Secrets's finalizer before GRM gets deleted.

In the geneticactuator we have:
https://github.com/gardener/gardener/blob/5abed1bfedd6f2188e5dcec9af161d1b5c286236/extensions/pkg/controller/controlplane/genericactuator/actuator.go#L479-L493

It waits the ManagedResource to be deleted, but it doesn't wait the Secret to be deleted.

**What you expected to happen**:
Shoot to be deleted successfully

**How to reproduce it (as minimally and precisely as possible)**:
In the local setup we can reproduce the issue by putting `time.Sleep(10 * time.Second)` for this `extension-controlplane-shoot` Secret before the finalizer release:
https://github.com/gardener/gardener/blob/dff43d99d2128c99f6d09116145ee48aebfd97f4/pkg/resourcemanager/controller/secret/reconciler.go#L83-L85

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.73.1
- Kubernetes version (use `kubectl version`):

**Comment by rfranzke** [comment]
I've also seen this, thanks for reporting @Kostov6! Probably we should make `managedresources.WaitUntilDeleted` also wait for the `Secret` to be gone?

**Comment by Kostov6** [comment]
After a discussion with @ialidzhikov and @rfranzke 3 approaches were proposed

1. Remove MR secret finalizer
- Pros:
    - simplest solution
    - biggest utility of finalizers is when a given resource is required for a proper deletion of another resource. Here this is not the case because GRM stores what it created in the `status` of the `ManagedResource`, so it doesn't rely on the secret for cleanup
    - Any delete of MR is correct
- Cons:
    - no safety net if secret is deleted by mistake (ops/bug)
2. Use owner reference
- Pros:
   - utilizes KCM
   - no explicit need to delete/wait for secrets
- Cons:
   - should only be deleted with foreground cascading deletion  
   - possibility to leak secret if KCM is down?
3. Use labels 
- Pros: 
   - feels most self-explanatory?
   - secrets will get deletion timestamp independently of KCM 
 - Cons:
    - It's unnatural that we don't remove the label when the Secret is no longer referenced
    - We need to use the utility Delete/Wait functions because we need to delete/wait for the secrets too

**Comment by ialidzhikov** [comment]
In a discussion this morning, we agreed to pick option 1 (drop finalizers from the ManagedResource Secrets).

**Comment by ialidzhikov** [comment]
I think we were keeping it open to clean up the TODO introduced with https://github.com/gardener/gardener/pull/8912.

/remove-lifecycle rotten
