### ISSUE TITLE
Add `component` field for the shoot status `conditions`

### ISSUE THREAD

**Issue by bd3lage** [gardener/gardener#8191]
**How to categorize this issue?**

/area monitoring
/kind enhancement

**What would you like to be added**:

The [shoot_status](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_status.md) conditions have the following fields :

| Field name           | Description                                                                                                        |
| -------------------- | ------------------------------------------------------------------------------------------------------------------ |
| `type`               | Name of the condition.                                                                                             |
| `status`             | Indicates whether the condition is applicable, with possible values `True`, `False`, `Unknown` or `Progressing`.  |
| `lastTransitionTime` | Timestamp for when the condition last transitioned from one status to another.                                     |
| `lastUpdateTime`     | Timestamp for when the condition was updated. Usually changes when `reason` or `message` in condition is updated.  |
| `reason`             | Machine-readable, UpperCamelCase text indicating the reason for the condition's last transition.                   |
| `message`            | Human-readable message indicating details about the last status transition.                                        |
| `codes`              | Well-defined error codes in case the condition reports a problem.                                                  |

We would like to add an extra `component` field for the following `conditions` :
- `ControlPlaneHealthy` - [kube-apiserver, lakom, GCM, MCM, vpn-seed-server...]
- `ObservabilityComponentsHealthy` [plutono, vali]
- `SystemComponentsHealthy` [coredns, calico-node, calico-typha-deploy, vpn-shoot...]

**Why is this needed**:

By clearly stating which component(s) is not healthy, it'll help to craft more granular alerts and automate the discovery of patterns.

**Comment by rfranzke** [comment]
I'm not sure if the conditions are the right place to report this - today, we exit early after we found the first unhealthy component and just turn the `status` into `False`. Generally, conditions are also used for other resources and their evaluations were the `components` field wouldn't make much sense. For alerts, we probably should leverage metrics and alertmanager?

**Comment by bd3lage** [comment]
Using alertmanager is actually the goal.
Parsing the `message` field to extract component name with Prometheus query is going to be too costly.

**Comment by rfranzke** [comment]
I don't think we will do this, so let's
/close
this as "won't-fix".
