### ISSUE TITLE
Shoot creation validation to disallow setting gardener's own finalizers

### ISSUE THREAD

**Issue by dguendisch** [gardener/gardener#8208]
**How to categorize this issue?**

/area robustness
/kind enhancement

**What would you like to be added**:
Sometimes users (blindly) copy existing shoot resources and use these to create new shoots. We have seen cases where they created a shoot and had defined `.metadata.finalizers: ["gardener","gardener.cloud/reference-protection"]`. The particular shoot however had wrong CIDR ranges, therefore never got scheduled to a seed and upon deleting this shoot, it failed to be deleted because of these manually added finalizers.

A validation that blocks the creation of shoot resources that contain "well-known" gardener finalizers should be rejected immediately so that users are immediately realizing what they did wrong and can immediately correct such mistakes. 

**Why is this needed**:
Sometimes users (blindly) copy existing shoot resources and use these to create new shoots thereby negatively interfering with a shoot's lifecycle.

**Comment by shafeeqes** [comment]
I checked the code, and if `gardener` finalizer is not present, the `gardener.cloud/reference-protection` finalizer will be removed by the reference controller in GCM. See https://github.com/gardener/gardener/blob/27b76d8d825461b9edc75c2d4472829e309af05e/pkg/controllermanager/controller/shoot/reference/add.go#L67-L69
So we need to forbid only `gardener`.
