### ISSUE TITLE
It is not possible to deploy cloud profiles with expired Kubernetes and operating system versions

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener#8229]
**How to categorize this issue?**

/area TODO
/kind bug

**What happened**:

When adding additional infrastructure (in my case VMware vSphere) I often see failures when deploying cloud profiles due to expired operating system and Kubernetes versions. From my point of view this is not a feature but a bug.

To mitigate this I added some coding to filter out expired versions when generating the cloud profile. While this mitigates the deployment failures for initial deployment it is problematic later on and I will remove that code again. The problem is that an expired version must remain in the cloud profile until all clusters / operating systems are upgraded to non-expired versions (at least I do assume that this is the case). My "fix" would however remove the version from the cloud profile although there might still be instances deployed.

Of course, the landscape setup (whatever it might look like) could check whether this is an initial deployment of a cloud profile (remote expired versions) or an update (don't remove them) but this adds another level of complexity. I would therefore appreciate if one could deploy cloud profiles with expired versions (up to 4 weeks would probably be a good compromise).

In contrast to the large cloud providers where one cloud profile is required for each of them, there is one cloud profile required for each vSphere cluster.

**What you expected to happen**:

Cloud profiles with expired versions can be deployed. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timuthy** [comment]
@danielfoehrKn IIRC you worked on the expiration topic. Was there a specific reason to not allow creating `CloudProfile`s with expired versions?

**Comment by danielfoehrKn** [comment]
That's a check to disallow invalid versions to be added. They are invalid as they cannot be used by any Shoot, hence it does not make sense to introduce such versions. The whole purpose of expiring versions is to eventually get rid of them (after Shoots are force upgraded) - hence it does not make sense to add new expired versions.

To me, it seems expired versions should be removed in a post-processing step from the CloudProfile before deployed to Gardener

@marwinski  is convenience the only reason for wanting to be able to add expired versions?

**Comment by timuthy** [comment]
I think it's valid to silently drop expired versions when the CloudProfile is **created**, mainly for convenience because I assume that devs usually copy the profile from some landscape and paste it to their dev environment.

Would you agree @marwinski?

**Comment by danielfoehrKn** [comment]
Good idea, instead of creating expired versions, we could also simply silently drop them on creation.
