### ISSUE TITLE
Forced updates of expired Kubernetes versions might fail because requirements are not met

### ISSUE THREAD

**Issue by oliver-goetz** [gardener/gardener#8271]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement

**What would you like to be added**:
Shoot maintenance controller enforces update of expired Kubernetes versions. However, this can fail for an update of a minor version if not all requirements are met. 

Upgrading Kubernetes `v1.26->v1.27` is already covered by #8114 which disables static token kubeconfig in this case.
However, there are upgrade paths which are not covered yet
- [x] `v1.22->v1.23`:  `v1.23` [requires containerd CRI](https://github.com/gardener/gardener/blob/master/docs/usage/docker-shim-removal.md), `docker` is not supported anymore:
  https://github.com/gardener/gardener/pull/8272
- [x] `v1.24->v1.25`: `PodSecurityPolicy` needs to be deactivated before the update and all `PodSecurityPolicy` resources have to be deleted, because this API is not served anymore in `v1.25` ([ref](https://github.com/gardener/gardener/blob/master/docs/usage/pod-security.md)): https://github.com/gardener/gardener/pull/8281
  - ~~Deleting `PodSecurityPolicy` resources affects the content of the cluster and not only its specification.
  Thus, there is an open question. Should `maintenance-controller` stop if it finds `PodSecurityPolicies` in the shoot or should it delete them?~~
  We deactivate the admission controller only while keeping the resources.
- [x] `v1.26->v1.27`:  Maximum workers of each worker group have to be greater or equal to its number of zones: https://github.com/gardener/gardener/pull/8281

**Why is this needed**:
Improving ops-productivity

**Comment by rfranzke** [comment]
There is also https://github.com/gardener/gardener/blob/15339f30da15e91f8892d406e7f9eb3ca6bfa129/pkg/apis/core/validation/shoot.go#L1843-L1849

**Comment by rfranzke** [comment]
> * Deleting `PodSecurityPolicy` resources affects the content of the cluster and not only its specification.
>   Thus, there is an open question. Should `maintenance-controller` stop if it finds `PodSecurityPolicies` in the shoot or should it delete them?

Well, changing the CRI from `docker` to `containerd` might also affect "the content" of the cluster. Also, there might be hibernated clusters that require a force-upgrade, so we cannot talk to their API servers. For simplicity reasons, I would probably ignore the PSPs and simply go ahead and disable the plugin. The consequence out of this is that the PSPs will remain in ETCD for the remaining lifetime of the cluster.
The "complete" solution would require way more effort (waking up the shoot, waiting for it, and all of this might fail or not even work (invalid IaaS credentials), so the force-upgrade may get stuck again and we are back at square one).

**Comment by rfranzke** [comment]
All tasks have been completed.
/close
