### ISSUE TITLE
Integrate reserve-excess-capacity extension logic into gardenlet 

### ISSUE THREAD

**Issue by adenitiu** [gardener/gardener#8307]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement

**What would you like to be added**:
Currently there is the extension https://github.com/gardener/reserve-excess-capacity and the gardenlet https://github.com/gardener/gardener/blob/master/docs/usage/seed_settings.md#reserve-excess-capacity logic available. The issue here is opened to address the possibility to merge the extension in the gardenlet logic and hence remove superfluous maintenance/deployment of another extension.

**Why is this needed**:
The logic in both setups above enables one to schedule reserve access capacity dummy pods in a dedicated worker-pool.
The extension is running for etcd worker pool and the gardenlet currently only handles the cpu worker pools.

**Comment by rfranzke** [comment]
We discussed that it's possible to augment https://github.com/gardener/gardener/blob/f6f65020aa32dc69913892144edaae2c53dedac6/example/50-seed.yaml#L62-L63 by allowing specifying additional node selectors and maybe overwrite the resource requirements to realize this. Then `gardenlet's` `Seed` controller would simply deploy multiple of the `reserve-excess-capacity` `DaemonSet`s based on on the configured list in above mentioned structure.
