### ISSUE TITLE
Multiple audit log sinks

### ISSUE THREAD

**Issue by pbochynski** [gardener/gardener#8313]
**How to categorize this issue?**

/area audit-logging
/kind enhancement

**What would you like to be added**:
Possibility to define 2 (or more) audit log backends with independent audit policies.

**Why is this needed**:
We (SAP BTP Kyma Runtime) operate a gardener cluster for our customers. We install several managed components and we would like to keep audit logs related to those components. Our customers deploy their own Kubernetes extensions and also want to access their audit logs. Writing all the records to our log backend causes scalability issues (we cannot control how many logs come from customers' policies). Writing all the logs to the customer's audit log backend is also not an option as we have to ask a customer for the audit log.

**Comment by rfranzke** [comment]
@vpnachev @dimityrmirchev Please correct me if I'm wrong, but I think the upstream `kube-apiserver` only supports the specification of exactly one audit webhook, correct? Is there anything we can do at this point? Apart from that, `gardener/gardener` itself does not set any configuration for audit webhooks for `Shoot`s, so this repository is anyways the wrong place?

**Comment by dimityrmirchev** [comment]
> I think the upstream kube-apiserver only supports the specification of exactly one audit webhook, correct? 

Yes, this is correct. Also a single audit policy is supported.

Multiple backends with multiple audit policies sounds like
- feature that may be implemented in k8s itself
- **OR** a single audit backend that receives all k8s logs and then filters/forwards them to the correct backend depending on some configuration

Either way, I also think that this issue does not concern g/g.

**Comment by rfranzke** [comment]
Thanks @dimityrmirchev, then let's
/close
this issue accordingly.
