### ISSUE TITLE
[Evaluate] Explore the possibility of combining HPA and VPA for efficient scalability of API Server 

### ISSUE THREAD

**Issue by PadmaB** [gardener/gardener#834]
# Story

- Explore the possibility of combining both HPA and VPA to efficiently scale API Server

# Proposal
- To be detailed

# Acceptance Criteria
- Based on the outcome of the evaluation adopt the proposal to control plane component API Server and to other relevant components

**Comment by PadmaB** [comment]
With #890 memory metrics is also included to scale kube-apiserver.
However, this issue #834 is to explore the possibility of using both HPA and VPA for better scalability of components like kube-apiserver

**Comment by vlerenc** [comment]
That's with Gaurav, right? Assigning it to him then. I hope that's OK. Maybe we should later move this ticket to this independent/new component.

**Comment by rfranzke** [comment]
Closing as HVPA got integrated as of #1421
