### ISSUE TITLE
Upgrade `k8s.io/*` to `v0.28`, `sigs.k8s.io/controller-runtime` to `v0.16`

### ISSUE THREAD

**Issue by shafeeqes** [gardener/gardener#8382]
**How to categorize this issue?**

/area open-source dev-productivity
/kind enhancement

**What would you like to be added**:

We should upgrade to the latest versions of our go upstream dependencies:
- `sigs.k8s.io/controller-runtime@v0.16.0`: https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.16.0
- `k8s.io/*@v0.28.0`: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md
-  `sigs.k8s.io/controller-tools@v0.13.0`:  https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.13.0

## Important changes / Action items

Here is a list of a few upstream changes to look out for when vendoring g/g, k/* and c-r in any of our repos (e.g. extensions). Please consider the release notes of [controller-runtime@v0.16](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.16.0) and upwards as well for a more complete list and more details.

### ⚠️ breaking / most notable changes 
- Following fields are changed under manager Options :
  - `MetricsBindAddress` is removed from manager options in favor of `Metrics` struct. https://github.com/kubernetes-sigs/controller-runtime/pull/2407
  - `Namespace`  is removed from manager options in favor of `cache.DefaultNamespaces`. https://github.com/kubernetes-sigs/controller-runtime/pull/2421
  - Deprecated fields `Port`, `Host`, `CertDir`, `TLSOpts`, `ClientDisableCacheFor`, `Namespace` and `DryRunClient` are removed. https://github.com/kubernetes-sigs/controller-runtime/pull/2422
- <strike>Drop resource lock `LeaderElectionResourceLock` as the only possible value is lease. </strike> Will remove once it is removed from `LeaderElectionConfiguration`
- [x] Projects which use k8s.io/code-generator and invoke generate-groups or generate-internal-groups.sh have a new, simpler script (kube_codegen.sh) they can use. The old scripts are deprecated but remain intact. (https://github.com/kubernetes/kubernetes/pull/117262) (@ary1992)
  - https://github.com/gardener/gardener/pull/8851
- ~~Use new code-generator script (kube_codegen.sh). Currently the script has few issues https://github.com/kubernetes/kubernetes/issues/121247 due to which it cannot be used in our code-base.~~
- [x] The new `cache.Options.Namespace` (replacement for the deprecated MultiNamespacedCacheBuilder) behaves differently when requesting an object in a namespace that is not included in the cache: it simply returns a usual `NotFound` error. Adapt our `FallbackClient` accordingly. https://github.com/gardener/gardener/pull/8447
- <strike> Adapt the new [restmapper](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/client/apiutil/restmapper.go) implementation.
  - https://github.com/kubernetes-sigs/controller-runtime/pull/2571</strike>, tackled by https://github.com/gardener/gardener/issues/9047

### ℹ️ other changes / good to know / for information only:
- ...

**Comment by shafeeqes** [comment]
To be tackled after https://github.com/gardener/gardener/issues/7991

**Comment by ary1992** [comment]
There were few changes done in the new code-generator which breaks our code generation:
- In new new `kube-codegen.sh` script, `code-gen` is called only on `type.go` file [refer](https://github.com/kubernetes/code-generator/blob/e4611069dfb4b0c04c7751afae1b9fef64828964/kube_codegen.sh#L539C1-L545C1). But our apis files are named as `type_<api>.go`. Hence fix is needed to also include file with names as `types_*.go`.
There is already an open [PR](https://github.com/kubernetes/kubernetes/pull/119981).
- We are using [`--extra-peer-dirs`](https://github.com/gardener/gardener/blob/f0172b75a7343c9400bb9ea3835643526010bf07/hack/update-codegen.sh#L257) at few places for `conversion-gen`. New `kube-codegen.sh` doesnot allow the flag anymore. Opened an issue upstream regarding this [refer](https://github.com/kubernetes/kubernetes/issues/120803)

**Comment by ary1992** [comment]
Issues related to `gen_client` function which is breaking us is tracked in the following upstream issue https://github.com/kubernetes/kubernetes/issues/121247

**Comment by ary1992** [comment]
As the code-generator no longs generates client, informers and listers for internal packages, we need to drop using internal clients ,lister and informers. Following PR adapts the changes https://github.com/gardener/gardener/pull/8851

**Comment by rfranzke** [comment]
@ary1992 Could you please update the issue description such that it's visible which takes are still open/what needs to be done? Or do you think it makes more sense to close this one and open a dedicated issue for the left-overs?

**Comment by ary1992** [comment]
> Issues related to `gen_client` function which is breaking us is tracked in the following upstream issue [kubernetes/kubernetes#121247](https://github.com/kubernetes/kubernetes/issues/121247)

The issue is fixed with PR https://github.com/kubernetes/kubernetes/pull/121411 and will be shipped with K8s `v1.30`

**Comment by acumino** [comment]
/close
All tasks completed.
