### ISSUE TITLE
Shoot Autoscaling

### ISSUE THREAD

**Issue by ira-gordin-sap** [gardener/gardener#8412]
Documentation issue at https://gardener.cloud/docs/gardener/usage/shoot_autoscaling/:
In Vertical Pod Auto-Scaling section: https://gardener.cloud/docs/gardener/usage/shoot_autoscaling/#vertical-pod-auto-scaling there is a link to [vertical-pod-autoscaler component](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler), but actually gardener forked this repo and has its own in https://github.com/gardener/autoscaler.

**Comment by rfranzke** [comment]
Gardener does not use VPA from its fork, see https://github.com/gardener/gardener/blob/bc94ce9bd342f3c18f206018edeca7278fcb4cfc/imagevector/images.yaml#L551-L590. We only consume `cluster-autoscaler` from the fork. Hence, the link is correct.

/close

**Comment by ira-gordin-sap** [comment]
> Gardener does not use VPA from its fork, see
> 
> https://github.com/gardener/gardener/blob/bc94ce9bd342f3c18f206018edeca7278fcb4cfc/imagevector/images.yaml#L551-L590
> 
> . We only consume `cluster-autoscaler` from the fork. Hence, the link is correct.
> /close

@rfranzke great reference, thanks!
What is calico-node-vertical-autoscaler deployment which uses registry_k8s_io/cpa/cpvpa@sha256:5c67cd124f9f1c00c6dd39b7aefa41e651c2f8303ddeb8f4ee491715d3938080 image in shoot clusters? k8s version is 1.25.11, gardenlinux version is 934.9.0.
I can't find it in the images.yaml.

**Comment by shafeeqes** [comment]
It should be https://github.com/gardener/gardener-extension-networking-calico/blob/cba69b7b5490f698af04f3d34dff5f590b6c4c8a/charts/images.yaml#L71

**Comment by shafeeqes** [comment]
>  What is calico-node-vertical-autoscaler deployment which uses registry_k8s_io/cpa/cpvpa@sha256:5c67cd124f9f1c00c6dd39b7aefa41e651c2f8303ddeb8f4ee491715d3938080 image in shoot clusters? k8s version is 1.25.11, gardenlinux version is 934.9.0. I can't find it in the images.yaml.

It should be from https://github.com/gardener/gardener-extension-networking-calico/blob/cba69b7b5490f698af04f3d34dff5f590b6c4c8a/charts/images.yaml#L71-L74
