### ISSUE TITLE
[GEP-22] Eliminate the `Worker` State Reconciler

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#8488]
**How to categorize this issue?**

/area control-plane-migration
/kind enhancement

**What would you like to be added**:
On our landscapes we hit a case where gardenlet was no longer able to update the Worker resource because we hit the etcd's default request limit of 1.5MiB:
```
task "Configuring shoot worker pools" failed: retry failed with context deadline exceeded, last error: etcdserver: request is too large
```

https://github.com/gardener/gardener/pull/8482 was a band-aid fix to mitigate the issue in short-term.

For long-term, @rfranzke shared that there is already the following TODO https://github.com/gardener/gardener/blob/7fbf64f49acec19cbd8398c8121830705db5388e/extensions/pkg/controller/worker/state_reconciler.go#L41-L42 which depends on this TODO (https://github.com/gardener/gardener/blob/7fbf64f49acec19cbd8398c8121830705db5388e/pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go#L179-L180)

@rfranzke shared:
> The idea is to not update the `.status.state` in the Worker field at all - gardenlet just fetches the machine state during migration phase and populates it directly to the ShootState (without the detour of first populating it to the Worker).

It is debatable whether this will permanently fix the problem or move it from the Worker resource to the ShootState resource. Still, it will be a nice improvement as CPM is a rare operation and the Shoot reconciliation won't be bothered by similar issue.

See also https://github.com/gardener/gardener/blob/e0ca8e718b56697de2e873d4383796f0b8b0dc82/docs/proposals/22-improved-usage-of-shootstate-api.md#eliminating-the-worker-state-reconciler

**Why is this needed**:
See above.

**Comment by rfranzke** [comment]
> It is debatable whether this will permanently fix the problem or move it from the Worker resource to the ShootState resource. Still, it will be a nice improvement as CPM is a rare operation and the Shoot reconciliation won't be bothered by similar issue.

This is somewhat true, of course, but I think it's not as bad as before:
- Today, the `Worker` resource does not only contain all `Machine`-related resources in its `.status.state`, but also all the worker pool configurations in the `.spec.pools` (which contribute to the overall size of the object).
- If really needed, we can increase the request size limit for the virtual garden via `gardener-operator`, while we are reluctant to do so for shoot clusters in general.
- Having shoots with so many worker pools can be considered "exotic", so chances to hit this frequently should be rather low.
