### ISSUE TITLE
Enable multiple chained auto-scaler expanders

### ISSUE THREAD

**Issue by dongyingbo** [gardener/gardener#8502]
**How to categorize this issue?**

/area auto-scaling
/kind enhancement

**What would you like to be added**:
Enable multiple chained auto-scaler expanders like "priority,least-waste"

**Why is this needed**:
**Problem**
In [SAP auto-scaler document](https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/FAQ.md#what-are-expanders:~:text=binpacking-,expander,random,-ignore%2Ddaemonsets%2Dutilization) it says,
```
From 1.23.0 onwards, multiple expanders may be passed, i.e. .cluster-autoscaler --expander=priority,least-waste
```
But after setting shoot/spec/kubernates/clusterautoscaler/expander to "priority.least-waste", I got error message,
```
 The Shoot "i545007-orc" is invalid: spec.kubernetes.clusterAutoscaler.expander: Unsupported value: "priority,least-waste": supported values: "least-waste", "most-pods", "priority", "random"
```
**Why**
Gardener make least-waste as default expander of auto-scaler. When switching to priority expander, we need to give different worker groups different priorities. And it will be done groups by groups because they are owned by different teams.
But it means for groups without explicitly priority yet will use AC's default random expander which is unexpected.

**Comment by rfranzke** [comment]
cc @rishabh-11 @himanshu-kun @elankath

**Comment by himanshu-kun** [comment]
We have an issue to track this request on `g/autoscaler` https://github.com/gardener/autoscaler/issues/128 (created there for better management)
We will discuss internally to decide its priority and get back to you.

**Comment by rfranzke** [comment]
Then let's
/close
this issue in favor of the one linked by @himanshu-kun. Thank you :)
