### ISSUE TITLE
OS update triggers a restart of all kubelets on old/existing nodes

### ISSUE THREAD

**Issue by dguendisch** [gardener/gardener#8512]
**How to categorize this issue?**

/area robustness
/kind bug

**What happened**:
Triggering an OS update immediately leads to all existing/old nodes restarting their kubelets because:
- the resp. cloud-config contains an OS version label introduced with https://github.com/gardener/gardener/pull/8295
- this label is placed in the systemd unit file of the kubelet service
- the resp. cloud-config-downloader service on old nodes sees that the cloud-config has changed and applies it (it logs `Seen newer cloud config or cloud config downloader version or hyperkube image"`)
- as a consequence, kubelets are restarted

Due to the infamous https://github.com/kubernetes/kubernetes/issues/100277, all readiness probes are put to false (until kubelet has re-executed the readiness probes).
Hence when a customer has some distributed/replicated workload with proper readiness probe definitions and prober PDBs, he might still see unexpected disruptions (and thus potentially downtimes) although the node rolling flow (together with replicated workload and PDBs) should be able to guard against this (and did so before https://github.com/gardener/gardener/pull/8295 was added).

@rfranzke suggested that this scenario should be kept in mind for the upcoming node-agent (i.e. to not add additional development to the soon outdated cloud-config-downloader service).

@MrBatschner: https://github.com/gardener/gardener/pull/8295 obviously regressed the till then available OS upgrades. Is https://github.com/gardener/gardener/pull/8295 something that can be reverted until there is proper support for this scenario (e.g. having different cloud-configs for old vs. new nodes) in the upcoming node-agent?

**What you expected to happen**:
Node rolling upgrades to not trigger sudden restarts of all old/existing node's kubelets.

**How to reproduce it (as minimally and precisely as possible)**:
- Create some cluster, dump the secret `cloud-config-<worker-pool>-<hash>` (in `kube-system` namespace)
- Update the worker pool to some other OS version
- Dump again the above secret and diff both, one will have (GL example): `--node-labels=worker.gardener.cloud/image-version=934.9.0` the other one will have `--node-labels=worker.gardener.cloud/image-version=934.10.0`
- Observe that kubelets now restart on the old nodes

**Comment by MrBatschner** [comment]
> @MrBatschner: https://github.com/gardener/gardener/pull/8295 obviously regressed the till then available OS upgrades. Is https://github.com/gardener/gardener/pull/8295 something that can be reverted until there is proper support for this scenario (e.g. having different cloud-configs for old vs. new nodes) in the upcoming node-agent?

The reason for #8295 was to offer a way for users to select on certain node operating systems which is especially useful when it comes to driver deployments for e.g. GPUs in machine learning environments. You could consider it a convenience feature though - especially if it breaks other, more important promises we make in regards to stability. Therefore, yes, it can be reverted until we find a solution to the problem.

**Comment by dguendisch** [comment]
Then I would suggest to revert the change for now as it degrades the OS upgrade flow and only introduce it again once there is a proper mean to ship worker/OS specific cloud-configs (most likely with the upcoming node-agent).
