### ISSUE TITLE
Unmanaged DNS doesn't respect service IP of shoot api server

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener#852]
Currently the unmanaged DNS only works if you provide the domain of the cluster in the shoot spec. In order to make #827 work, we need to create nip.io based kube-api urls dynamically - the same way we do it for "real" DNS entries.

**Comment by vpnachev** [comment]
With #1617 the DNS can be disabled and DNS domain is not required in favor of simple IP addresses.
@afritzler can we close this issue now?

**Comment by afritzler** [comment]
Will do so. Thanks for following up.
