### ISSUE TITLE
Fix debugging in Skaffold targets

### ISSUE THREAD

**Issue by briantopping** [gardener/gardener#8522]
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What happened**:
In #8418, there is a divergence of opinion on how to resolve a failure of `make gardener-debug`. There should be no disagreement that this target should work, and there is some disagreement regarding simultaneous debugging of multiple containers. Without the ability to target arbitrary multiple containers, it is impractical to create a generic IDE integration that does not require tribal knowledge to be successful.

With this resolution, the contention in #8418 should be more easily resolved.

**What you expected to happen**:
`make gardener-debug` will launch and emit Delve sockets for each container built and deployed by the configuration(s) in use, with any desired set of container targets supported in `skaffold.yaml` et al.

**How to reproduce it (as minimally and precisely as possible)**:
```
make kind-up gardener-debug
```

Some kind of blocking unit test should be created to ensure continued availability. 

**Anything else we need to know?**:
`make kind-up gardener-up` works.

cc: @ScheererJ @oliver-goetz @marwinski

**Comment by oliver-goetz** [comment]
Did you try to run `make kind-up gardener-up gardener-debug`? 
This is one command to bring up the local setup and then starts all debuggable components in debug mode. It works for me.

**Comment by briantopping** [comment]
@oliver-goetz Probably something to do with number of cores and machine speed. What is the spec of your machine?
