### ISSUE TITLE
[Cleanup] Managed resource package is making unnecessary calls causing transient errors

### ISSUE THREAD

**Issue by dimityrmirchev** [gardener/gardener#8549]
**How to categorize this issue?**

/area quality
/kind cleanup

Together with @rfranzke we had a private discussion about the logic residing in the managed resource builder package and more concretely we discussed the [mr.Reconcile](https://github.com/gardener/gardener/blob/fbbd16a1aefdc4aaac295162fa4a692cd1d4b7de/pkg/utils/managedresources/builder/managedresources.go#L121) function. It is not ideal that we currently patch the referenced secrets to make them garbage collectable. This results in transient errors when reconciling a managed resource because some client's caches may not be populated with the newly created secret. See [an example log from a test run](https://gcsweb.gardener.cloud/gcs/gardener-prow/pr-logs/pull/gardener_gardener/8509/pull-gardener-e2e-kind-operator/1704409810713186304/artifacts/gardener-operator-local/gardener-operator-local-worker/pods/garden_gardener-operator-775bcf7488-g2pg4_5eb8618d-6a8c-4ac5-8ca1-9805461264fa/gardener-operator/0.log) and search for "marking new secrets as garbage collectable". Ideally we would not see such errors.

We can remove this piece of code (the one that marks the secrets as garbage collectable) if we ensure that:
 - old secrets are deleted/marked for garbage collection
 - it is ensured that all extensions now work with the immutable secrets approach

A [quick search](https://sourcegraph.com/search?q=context:global+repo:github.com/gardener+-file:vendor+WithSecretRef&patternType=standard&sm=1&groupBy=repo) shows that only a couple of extensions are using the `WithSecretRef` function which is one of the fewer possible ways to use managed resources with a mutable secrets, i.e. you create a mutable secret and then reference it via the said function.

Initlially the plan was not to modify any extension code. This would mean that every extension should be released with vendored g/g >= [v1.77](https://github.com/gardener/gardener/releases/tag/v1.77.0) and managed resources should be reconciled at least once.

Another more involved (and probably safer) approach would be to include migration step in extensions's code. This approach may also unblock the removal of the discussed code since the cleanup will happen explicitly.
1. Deploy managed resource with immutable secrets
2. Clean the old secret (temporary step which can be removed anytime by the extension owner after a (few) release(s))

@timuthy @shafeeqes since you reviewed https://github.com/gardener/gardener/pull/8116 do you have any inputs on this?

**Comment by timuthy** [comment]
Thanks @dimityrmirchev and @rfranzke for the analysis.

I wonder if we can still keep the logic that patches the "old" secrets (see [here](https://github.com/gardener/gardener/blob/307d9f77d3edd2314b09ab5cb1a2ca0b0e5feefd/pkg/utils/managedresources/builder/managedresources.go#L163-L166))? The operation should be safe since those secrets have already existed for a longer time, i.e. no stale cache issues.

**Comment by rfranzke** [comment]
@timuthy For how long do you want to keep this? I'm fine with not dropping it immediately since we don't see any issues with it (only with the new secrets), but we should define when we drop this since this is migration coding that we probably don't want to carry with us indefinitely :)

**Comment by timuthy** [comment]
I didn't really see this as (classical) migration code so far because there is no guaranteed migration (according to the many discussions we had in the past). It doesn't concern to keep this piece of code since it runs efficiently. However, I'm also not blocking the decision to remove it and leave "orphaned" secrets for some clusters if you have a strong preference to do so.

**Comment by rfranzke** [comment]
What is the difference compared to other changes where we change functionality/behaviour that affects dependencies/extensions? I can't think of many cases where we have guaranteed migrations. Often, we notify dependencies via release notes that something changed and they should adapt to it, and after some time (3-6 releases), we drop the old behaviour. If they don't adapt, we can't help/guarantee.

**Comment by timuthy** [comment]
It was more about clusters in an error state for which we'd miss the migration. As I said, I'm fine if we decide to disregard this case or if we keep https://github.com/gardener/gardener/blob/307d9f77d3edd2314b09ab5cb1a2ca0b0e5feefd/pkg/utils/managedresources/builder/managedresources.go#L163-L166.

**Comment by dimityrmirchev** [comment]
I like the idea of @timuthy to keep https://github.com/gardener/gardener/blob/307d9f77d3edd2314b09ab5cb1a2ca0b0e5feefd/pkg/utils/managedresources/builder/managedresources.go#L163-L166. To me this seems like the more pragmatic approach because it:
 - guarantees that if somebody changes the name of a mr secret then the old one will be GCed
 - is usually a noop since clients already have cached this secret and the secret has the GC label in which case we do not send a patch request

I can also open PRs for extensions that do not use yet immutable secrets and then we can remove the other 2 patch requests. @rfranzke can you agree with such approach?

**Comment by rfranzke** [comment]
Sure, sounds great 👍🏻
