### ISSUE TITLE
Cluster Deletion with Four-Eyes-Principle

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#8566]
**How to categorize this issue?**
/area ops-productivity
/kind discussion

**What would you like to be added**:
While discussing with @donistz that despite our delete annotation, people sometimes shoot themselves in the foot, we wondered whether it would be possible to improve/secure the deletion flow further.

The basic idea: The person (subject) who sets the annotation should not be the same person (subject) that deletes it.

Notes:
- This should be configurable per project and/or shoot resource, so people can decide that at project level or when creating the shoot (immutable at shoot resource level), whether the four-eyes-principle is required for later deletion.
- This should apply primarily to humans and there must be still a way to a fully automated deletion via technical robots/service accounts

Could we please have a discussion, how we could achieve such a thing?

**Alternative**:
What might already help is to introduce another annotation that completely prevents the shoot cluster deletion if set. Something like a lock annotation on that shoot cluster that must be removed first prior to deletion. It would also trigger a separate UI flow, so that accidental deletion becomes less likely, though the four-eyes principle would still be preferable. However, locking is probably a lot easier to implement.

Other, additional or flanking, additions or alternatives include:
- Delayed deletion, i.e. give the people means to specify for a cluster (at any point in time) how much the deletion should be delayed, should it ever be triggered. For productive clusters, people could set that to `72h` or whatever time they deem appropriate. If a cluster was scheduled for deletion, people would then have time to react and should have the means to abort the deletion.
- Active notification, especially in combination with above, could further help. Specified people or, by default, project owner/members and/or the cluster owner could be notified about the impending deletion. That may help to detect an accidental deletion and abort the scheduled deletion on time.

**Why is this needed**:
So that it becomes harder for one individual to accidentally delete clusters.

**Comment by adenitiu** [comment]
Another situation occurred. When we asked the user how did he trigger deletion, he mentioned it was done via CLI.

**Comment by HappyTobi** [comment]
An other concept / idea of preventing clusters from accidental delete could be a  "lock" mechanism.
Example of a "lock" concept that azure is using:
[Azure resource lock](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/lock-resources?tabs=json)

At azure you can deploy a dedicated “lock" to secure a "resource".
To delete a "resource" that is "locked" is still possible, but you first have to remove the "lock" before you can remove the "resource" itself.

With that pattern you have possibility to select "clusters" that should be secured from accidental deletion.
Because it's an optional thing, you can still remove your dev, test clusters without any additional step.

**Comment by rfranzke** [comment]
We propose to extend the `Project` resource as follows:

1. New `.spec.dualApprovalForDeletion` field which can only be mutated by the project owner:
   ```yaml
   spec:
     dualApprovalForDeletion:
       shootSelector:
         matchLabels: {}
       includeServiceAccounts: true
   ```
2. For all shoots matched by the respective selector, the subject confirming the deletion (i.e., setting the confirmation annotation) must be different from the subject sending the DELETE request.
3. A new admission plugin in `gardener-apiserver` validates this and stores the subject who confirmed the deletion in an annotation on the `Shoot` which can only be removed (together with the confirmation annotation (i.e., if they change their mind)) but never changed.
4. If `includeServiceAccounts` is false, `ServiceAccount`s are excluded, i.e., the same `ServiceAccount` subject can confirm+delete a `Shoot`.

**Comment by vlerenc** [comment]
I love it. Great!

**Comment by vlerenc** [comment]
I love it ❤️. Great 🚀!

@HappyTobi In comparison to "locking", we worried people will automate it, so 4-👀 "dual-approval" seemed more safe. As this happened to you or your colleagues, what are your thoughts?
