### ISSUE TITLE
Replace Terraform DNS with DNS Provider

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#86]
@mandelsoft has shown usage of the [DNS provider](https://github.com/kubernetes-incubator/external-dns) in our sister project [Kubify](https://github.com/gardener/kubify). Can we switch over to it for our DNS entries like the shoot API server? That would reduce the dependency to Terraform further, which we want to eliminate completely eventually (because of the poor error handling and other reasons).

**Comment by rfranzke** [comment]
Once the [pull request](https://github.com/kubernetes-incubator/external-dns/pull/455) from @mandelsoft is merged we can do it.

**Comment by rfranzke** [comment]
Just had a quick discussion with @mandelsoft as it looks like his PR is going to be merged soon.

We would have to deploy one `external-dns` centrally in all seeds (which would manage the (internal) DNS records for the `kube-apiserver`s of all shoots with our credentials/hosted zone), and we would have to deploy another `external-dns` next to each control plane (which would manage the ingress DNS record for the `nginx-ingress-controller` of the respective shoot (either with our credentials/hosted zone or those provided by the user)). However, we also create a DNS record based on the shoots `.spec.dns.domain` value pointing to the internal DNS record. The `external-dns` component can only manage DNS records per annotations on `Service` or `Ingress` objects. Thus, how would we create this record?

Do we really want to integrate that component?

**Comment by vlerenc** [comment]
Hmm... not sure whether multiple annotations would work at the API service LB service (https://github.com/kubernetes-incubator/external-dns/blob/master/docs/faq.md#how-do-i-specify-dns-name-for-my-kubernetes-objects), but no, we don't have to implement it. We all thought it may be a good idea to get rid of TF stuff. If we believe, it's not worth the effort, we don't do it.

**Comment by rfranzke** [comment]
Well, the way it works fits into how Gardener does things, but I'm afraid we have to enhance it here and there to make it usable for us (e.g., the multiple DNS name thing if that's not yet possible). Somebody (probably @mandelsoft) would have to take this. We would have to bring in our changes upstream (we don't want forks, however, it's quite slow as @mandelsoft's initial PR is still not merged). I'd need to take a deeper look to get an opinion whether it's worth the effort or not, but (regarding this ticket/issue) it's not only about integrating the component, but also enhancing it to fit properly.

**Comment by fsniper** [comment]
Hello, 

I think this work is a good idea to move forward with. Currently, gardener should be extended for using any dns service you want to use it for. (eg. https://github.com/gardener/gardener/commit/06b01dad1fda3d043042aa7da632b3c1e260746e#diff-33d2a8cacfcd2dda84699a11862f3ab0). 

For our requirements we need to use Azure Dns Zones. If gardener were leveraging external-dns this would be a trivial process.

**Comment by rfranzke** [comment]
With the extension concept we have in mind I guess we won't using the external DNS (as it does anyway not provide all the features we need currently, and as it seems hard to contribute to it (@mandelsoft's PR from February is still open).
