### ISSUE TITLE
Enable `kube-controller-manager` controllers based on activated APIs

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#8654]
**How to categorize this issue?**

/area control-plane
/kind enhancement

**What would you like to be added**:
The list of enabled `kube-controller-manager` controllers should depend on APIs activated via `.spec.kubernetes.kubeAPIServer.runtimeConfig`.

_Example_:
- Enabled API for workerless shoot:
```
kubeAPIServer:
  runtimeConfig:
    apps/v1: true
```
- Controllers to be enabled: _replicaset_, _deployment_, _controllerrevision_, _statefulset_

While it's primarily important that these controllers are enabled, the logic can of course also be reversed: If particular APIs are disabled, the related controllers can be disabled as well.

_Alternative_: Always enable a full set for workerless shoots (`*,-nodeipam,-nodelifecycle,-persistentvolume-binder,-attachdetach,-persistentvolume-expander,-cloud-node-lifecycle,-ttl`). This might cause noise in KCM logs but reduces maintenance effort on our side.

**Why is this needed**:
User can enabled/disable various APIs in their shoots but don't get a matching `kube-controller-manager` deployment. If `apps/v1` is enabled for workerless shoots, the cluster is left w/o further functionality since no actor would manage `deployment -> replicaset -> pod`.

**Comment by timuthy** [comment]
Thanks for volunteering @shafeeqes 👏

**Comment by vlerenc** [comment]
Awesome, thank you! We stumbled across this problem today in context of connecting bare metal nodes manually to a workerless shoot (rather: sole control plane). With this, it's possible to get all functionality of a real cluster with our managed control plane, but without fake worker pools that a regular shoot would require to have.

In hindsight, we should have called this feature not workerless shoot, but something like managed control plane (as a service). As we now know, people can either just use the control plane (then both names are OK) or use it and amend it with custom nodes (and then the name workerless shoot is no longer as fitting as with the first use case).

**Comment by vlerenc** [comment]
Never mind, it's not working. Besides the topic here, to make a workerless shoot cluster work with custom nodes requires a lot more as @ScheererJ pointed out and actually https://github.com/gardener/gardener/issues/7635 hints at, e.g. DNS, VPN, etc. all don't get deployed either.

For the moment, if one doesn't want to duplicate all of that (and probably more), a regular shoot with an unused worker pool is better, but it's a pity. To cover this use case (control plane as a service plus manually added custom nodes), we need to invest a bit more/it's not for free.
