### ISSUE TITLE
Deploying Gardener Locally :  Build Err

### ISSUE THREAD

**Issue by RAVSECIO** [gardener/gardener#8661]
Unexpected error running "go build": exit status 1
pkg/utils/managedresources/registry.go:18:2: cannot find package "." in:
/gardener/vendor/cmp

2:~/gardener$ make gardener-debug SKAFFOLD_MODULE=gardenlet
hack/tools/bin/skaffold debug
Generating tags...
 - eu.gcr.io/gardener-project/gardener/gardenlet -> localhost:5001/eu_gcr_io_gardener-project_gardener_gardenlet:v1.73.0-394-g7827cf4ab
 - eu.gcr.io/gardener-project/gardener/resource-manager -> localhost:5001/eu_gcr_io_gardener-project_gardener_resource-manager:v1.73.0-394-g7827cf4ab
Starting build...
Found [kind-gardener-local] context, using local docker daemon.
Building 2 artifacts in parallel
Building [eu.gcr.io/gardener-project/gardener/gardenlet]...
Target platforms: [linux/amd64]
Using base cgr.dev/chainguard/static:latest@sha256:ef5add7fd46cf1ce7d33d6de517833ac5c7e749db9b15249f9c472a772f3af27 for github.com/gardener/gardener/cmd/gardener-resource-manager
Using base cgr.dev/chainguard/static:latest@sha256:ef5add7fd46cf1ce7d33d6de517833ac5c7e749db9b15249f9c472a772f3af27 for github.com/gardener/gardener/cmd/gardenlet
Using build config eu.gcr.io/gardener-project/gardener/resource-manager for github.com/gardener/gardener/cmd/gardener-resource-manager
Building github.com/gardener/gardener/cmd/gardener-resource-manager for linux/amd64
Using build config eu.gcr.io/gardener-project/gardener/gardenlet for github.com/gardener/gardener/cmd/gardenlet
Building github.com/gardener/gardener/cmd/gardenlet for linux/amd64
Unexpected error running "go build": exit status 1
pkg/utils/checksums.go:19:2: cannot find package "." in:
	/home/ubuntu/gardener/vendor/slices
Unexpected error running "go build": signal: killed
Build [eu.gcr.io/gardener-project/gardener/gardenlet] was canceled

Building [eu.gcr.io/gardener-project/gardener/resource-manager]...
Target platforms: [linux/amd64]
Build [eu.gcr.io/gardener-project/gardener/resource-manager] failed: could not build and publish ko image "eu.gcr.io/gardener-project/gardener/resource-manager": failed to publish ko image: error building "ko://github.com/gardener/gardener/cmd/gardener-resource-manager": build: go build: exit status 1

Pruning images...
build [eu.gcr.io/gardener-project/gardener/resource-manager] failed: could not build and publish ko image "eu.gcr.io/gardener-project/gardener/resource-manager": failed to publish ko image: error building "ko://github.com/gardener/gardener/cmd/gardener-resource-manager": build: go build: exit status 1
make: *** [Makefile:345: gardener-debug] Error 1

**Comment by shafeeqes** [comment]
You have to upgrade go to 1.21. The slices package is only present starting 1.21.

**Comment by acumino** [comment]
Which version of `GO` are you using?
If it is not 1.21, please update it and try again.

**Comment by acumino** [comment]
Which version of `GO` are you using?
If it is not 1.21, please update it and try again.
