### ISSUE TITLE
Source `etcd` backup directory for a `Shoot` is not deleted after a successful control plane migration

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#8730]
**How to categorize this issue?**

/area control-plane-migration
/kind bug

**What happened**:
After performing a control plane migration we noticed that the backup folder and the data of the shoot's `BackupEntry` in the source seed's backup bucket does not get deleted.

**What you expected to happen**:
The `BackupEntry`'s folder and data in the source seed to be deleted after it has been successfully copied to the destination seed's backup bucket.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup two seeds in your local development environment
2. Create a shoot cluster
3. Migrate the shoot cluster's control plane from its original seed to the second seed in your local setup
4. Observe that the directory for the backup of the shoot's BackupEntry still exists in the backup bucket of the source cluster located at `dev/local-backupbuckets/<source-seed-backup-bucket-id>`

**Anything else we need to know?**:
During the restore phase of control plane migration a new source `core.BackupEntry` is created with the data of the original shoot's `core.BackupEntry` and a `source-` prefix added to its name. It is reconciled and a corresponding `extensions.BackupEntry` is created in the seed cluster.  After the backup of the shoot's etcd is copied via an `EtcdCopyBackupsTask` resource, the `core.BackupEntry` with the `source-` prefix is deleted. This also deletes the `extensions.BackupEntry` from the seed cluster, which should clean up the shoot's backup directory in the source seed. However, this does not seem to happen.

This issue is not limited only to the local setup and seems to happen with other provider extensions as well.

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by plkokanov** [comment]
I noticed an issue while doing some tests today on azure clusters where the `source` BackpEntry did not get deleted after a successful control plane migration. It was instead stuck in an `Error` state with the following:
```
Error deleting BackupEntry: secret garden/entry-source-shoot--<project>--<shoot-name>--<uuid>
      doesn''t have a subscription ID'
```

CPM finishes successfully because there is no check whether the source `BackupEntry` actually gets deleted successfully after the `etcd` backups are copied and the `etcd` statefulsets are created:
https://github.com/gardener/gardener/blob/bb4e628270195aae6d698f7bf325268d9d5e8553/pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go#L274-L279

**Comment by plkokanov** [comment]
For the azure issue above: It seems that the secrets we use for backupentries on azure seeds have the following format in their data field (1):
```
data:
  storageAccount: <account>
  storageKey: <key>
```

Instead of (2)
```
data:
  clientID: <client-id>
  clientSecret: <client-secret>
  subscriptionID: <subscription-id>
  tenantID: <tenant-id>
  ```

This is because when gardenlet deploys the `backupentry` secrets as part of the `backupentry` reconciliation, it checks the corresponding `backupbucket` whether it has a `status.generatedSecretRef` or not. If it has a `status.generatedSecretRef`, it will use that when deploying the `backupentry` secret in the `garden` namespace in the seed. That secret has the structure displayed above in (1).
If `status.generatedSecretRef` is not found, the `spec.secretRef` is used instead. That secret has the data structure displayed in (2),

The provider-azure extension expects a data structure in the form of (2) when creating a client to connect to the azure proivder and thus returns the `secret garden/entry-source-shoot--<project>--<shoot-name>--<uuid> doesn''t have a subscription ID' error: https://github.com/gardener/gardener-extension-provider-azure/blob/4d071a46acb65ab554cb173dd52a7a986b9e527b/pkg/internal/auth.go#L60-L95

/cc @kon-angelo 

This should also be affecting normal cluster deletions and not be limited to CPM.

---

This is not the only cause of the original issue but only a part of it. The first step towards solving it would be to add a step which checks if the source etcd backup entry is deleted successfully after etcd backups are copied and the etcd pods are started.

**Comment by Kostov6** [comment]
The source `extension.BackupEntry` should clean up the backup directory and the problem comes from the `source-` prefix in `path` 
```
{...,"msg":"Deleting directory","controller":"backupentry",
"object":{"name":"source-shoot--local--local--fdbf251c-edf7-4cd9-89ac-b796d17401a7"},"namespace":"",
...
"path":"/dev/local-backupbuckets/ebf7cc21-174b-4d96-94a5-252dfa9e38af/source-shoot--local--local--fdbf251c-edf7-4cd9-89ac-b796d17401a7"}
```

**Comment by Kostov6** [comment]
For other `gardener-extension-provider-.*`
- [ ] https://github.com/gardener/gardener-extension-provider-aws/blob/master/pkg/controller/backupentry/actuator.go#L53
- [ ] https://github.com/gardener/gardener-extension-provider-gcp/blob/master/pkg/controller/backupentry/actuator.go#L52
- [ ] https://github.com/gardener/gardener-extension-provider-azure/blob/master/pkg/controller/backupentry/actuator.go#L56
- [ ] https://github.com/gardener/gardener-extension-provider-openstack/blob/master/pkg/controller/backupentry/actuator.go#L54
- [ ] https://github.com/gardener/gardener-extension-provider-alicloud/blob/4d329383031ac6f7238e2f86d52dd7959a37bac6/pkg/controller/backupentry/actuator.go#L54

**Comment by Kostov6** [comment]
What do you think about changing the genericactuator instead like this?
``` go
// Delete deletes the BackupEntry.
func (a *actuator) Delete(ctx context.Context, log logr.Logger, be *extensionsv1alpha1.BackupEntry) error {
	if err := a.deleteEtcdBackupSecret(ctx, be.Name); err != nil {
		return err
	}
	be.Name = strings.TrimPrefix(be.Name,"source-")
	return a.backupEntryDelegate.Delete(ctx, log, be)
}
```

**Comment by plkokanov** [comment]
> What do you think about changing the genericactuator instead like this?
> 
> ```go
> // Delete deletes the BackupEntry.
> func (a *actuator) Delete(ctx context.Context, log logr.Logger, be *extensionsv1alpha1.BackupEntry) error {
> 	if err := a.deleteEtcdBackupSecret(ctx, be.Name); err != nil {
> 		return err
> 	}
> 	be.Name = strings.TrimPrefix(be.Name,"source-")
> 	return a.backupEntryDelegate.Delete(ctx, log, be)
> }
> ```

Changing the name here is a problem because the `BackupEntry` object is passed via reference, menaing that it will also be changed for the calling code. That same object is still used in the calling code and it will be used with a modified name here: https://github.com/gardener/gardener/blob/eda15abf13f9917403f1b77776b19e3d40b39f06/extensions/pkg/controller/backupentry/reconciler.go#L221-L243

You could do it by copying the object first.
One one hand it's easier to just make the change in the generic actuator, on the other we can't guarantee how exactly this `BackupEntry` object is used inside the `Delete()` function of the delegate (esp. for other provider extensions), so changing the name might not be safe and be a breaking change.

**Comment by ialidzhikov** [comment]
@plkokanov created an issue to provider-azure for the findings described in https://github.com/gardener/gardener/issues/8730#issuecomment-1946025063: https://github.com/gardener/gardener-extension-provider-azure/issues/793. Thanks!
