### ISSUE TITLE
Node leases never get cleaned up

### ISSUE THREAD

**Issue by unmarshall** [gardener/gardener#8749]
**How to categorize this issue?**
/area control-plane

/kind cleanup
/kind bug

**What happened**:
kubelet creates a node lease for every node in the `kube-node-lease` namespace. We have noticed that across shoot clusters, node leases are never cleaned up and pile up.
Example:
Take aws-ha (dev landscape) seed as an example
Total number of nodes: 9
Total number of node leases: 388

For leases which do not have any node, their `OwnerReference` is absent but their `holderIdentity` still has the node name.
There is a related upstream issue https://github.com/kubernetes/kubernetes/issues/119660 

**What you expected to happen**:
Node leases should be eventually cleaned up after their parent nodes are no longer available. A potential enhancement to garbage collection is required.

**How to reproduce it (as minimally and precisely as possible)**:
Just look at any shoot cluster.

**Comment by ialidzhikov** [comment]
According to the github issues, this seems to be fixed in K8s 1.29 with https://github.com/kubernetes/kubernetes/pull/119661.
Do you suggest implementing a workaround/clean in Gardener for the affected versions?

**Comment by unmarshall** [comment]
>Do you suggest implementing a workaround/clean in Gardener for the affected versions?

The judgement on if and when to fix the issue is left to the gardener core team. One option is to wait for the fix in 1.29 if the leak is not a concern. I am not sure if this fix will be back-ported to earlier k8s versions.

**Comment by timuthy** [comment]
It could be a low hanging fruit removing the orphaned `Lease`s via the shoot's [garbage collection](https://github.com/gardener/gardener/blob/master/pkg/gardenlet/controller/shoot/care/garbage_collection.go). IIUC, even the fix in 1.29 will not clean up already orphaned objects.
