### ISSUE TITLE
Enable deleting a project without deleting its namespace

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/gardener#879]
For the garden-setup project, I'd like to create a `garden` project linked to the `garden` namespace, in order to be able to use the `shoot.garden.sapcloud.io/use-as-seed` annotation and have the seed created automatically. 

However, since deleting a project will also delete the corresponding namespace, this causes trouble when trying to remove the project again, as the Gardener itself is within the `garden` namespace. 

Unfortunately, it seems impossible to undo the step of turning a namespace into a project namespace. 
It would be nice to have an annotation (or something else) that changes the project deletion behaviour, so that instead of deleting the namespace, the Gardener will instead undo anything it did to the namespace when it was associated with the project (e.g. deleting `ownerReference`, etc.) and leave it in the state it was in before the project was created.

**Comment by petersutter** [comment]
workaround:
- delete ownerRef on namespace and project related annotations and labels on the namespace.
- remove finalizer on project and set `confirmation.garden.sapcloud.io/deletion` annotation
- delete project
- cleanup other resources created for the project (clusterroles + bindings)
