### ISSUE TITLE
Certificate Rotation

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener#88]
# Story

As a provider we need to ensure that all certificates that are used in a Kubernetes cluste are valid and  are kept secure.

# Implementation Proposal

One way to ensure the validity of certificates is to update them on every cluster update. This also means that certificates don't need to be valid for an extensive period of time but can expire after a couple of months (requiring frequent cluster updates). 

# Acceptance Criteria
[ ] A document/wiki describing the certificate strategy
[ ] An implementation of the above

**Comment by vlerenc** [comment]
This is a massive undertaking, but not yet spec'ed. Also, it states it's a story, which would not be fitting. We speak of many months of work here. If it's a story, it would not meet the formal requirements either (no DoD).

**Comment by rfranzke** [comment]
Closing for the reasons commented by @vlerenc.
