### ISSUE TITLE
Use PDBs with `unhealthyPodEvictionPolicy`

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#8821]
**How to categorize this issue?**

/area robustness
/area high-availability
/kind enhancement

**What would you like to be added**:
Since Kubernetes 1.27 (`PDBUnhealthyPodEvictionPolicy` defaulted to `true`) PDBs offer a [Unhealthy Pod Eviction Policy](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#unhealthy-pod-eviction-policy).
It should be considered using `unhealthyPodEvictionPolicy: AlwaysAllow` for (some) Gardener managed components.

**Why is this needed**:
The default behavior for PDBs (also before 1.27) considers running pods (`.status.phase="Running"`) as potential candidates violating against a PDB. This becomes a problem if a pod of a single replica deployment is in `Running` but not `Ready` state and has a matching PDB with `maxUnavailable: 1` as endorsed by Gardener ([ref](https://github.com/gardener/gardener/blob/master/docs/development/high-availability.md#convenient-application-of-these-rules)).

For example, we saw `kube-controller-manager` pods being not `Ready` and thus blocked node roll-outs on seeds since the defined PDB was violated.
The [Shoot HA Best Practices](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_high_availability_best_practices.md) documentation as well advertises advantages using `AlwaysAllow` in case of a zone outage.

**Comment by timuthy** [comment]
cc @vlerenc

**Comment by vlerenc** [comment]
Nice, thanks @timuthy for bringing this up!

**Comment by voelzmo** [comment]
We had this frozen in our backlog for a while, waiting for our Seeds to update to 1.27 – are you going to make this change before that happens?

**Comment by timuthy** [comment]
Gardener contains support for Kubernetes `1.24.x` ([ref](https://github.com/gardener/gardener/blob/master/docs/usage/supported_k8s_versions.md)) and it will probably take ~1 year to have `1.27.x` as the least supported version. If we want to benefit from `unhealthyPodEvictionPolicy: always` we'll have to check the runtime version and set it if possible.

Side note: The PDB API change was introduced with `1.26.x`. So even if the feature gate is disabled, we can set `unhealthyPodEvictionPolicy` unconditionally as soon as the least supported version is `1.26.x`.
