### ISSUE TITLE
Shoot worker pools can be updated to reference expired OS versions

### ISSUE THREAD

**Issue by MrBatschner** [gardener/gardener#8824]
**How to categorize this issue?**

/area os
/kind bug

**What happened**:

Creating a new Shoot with an expired OS version for its worker pools is impossible and will be caught by the admission controller. However, an existing Shoot can be updated with a new/modified worker pool that references an expired OS version.

**What you expected to happen**:

Updating a Shoot with an expired OS version should be impossible (at least for end-users and their automation).

**How to reproduce it (as minimally and precisely as possible)**:

Create a Shoot. Once the Shoot is up and running, update the Shoot manifest and add another worker pool that references an expired OS version (that is still present in the CloudProfile).

**Anything else we need to know?**:

Probably caused by the `a.GetOperation() == admission.Update` check in https://github.com/gardener/gardener/blob/f05b0d1c0442966cbe9186d5d97ca18be607aa70/plugin/pkg/shoot/validator/admission.go#L1508-L1511

**Environment**:

- Gardener version: v1.83.1
- Kubernetes version (use `kubectl version`): irrelevant

**Comment by acumino** [comment]
/cc @danielfoehrKn
Update to an expired version was added in PR https://github.com/gardener/gardener/pull/8275.
