### ISSUE TITLE
Expose egress IPs of a shoot

### ISSUE THREAD

**Issue by kon-angelo** [gardener/gardener#8837]
**How to categorize this issue?**

/area control-plane
/kind enhancement

**What would you like to be added**:

Provide a way to express and expose egress IPs of shoots inside extension resources in the seed. 

**Why is this needed**:

Egress IPs can be used for a variety of purposes including building ACL extensions like https://github.com/stackitcloud/gardener-extension-acl. Additionally, shoots that communicate with external systems that rely on allowlist could also make use of this feature (assuming that this gets exposed to the end-user in a later phase). We will use the acl extension as a case study for the current status.

Currently the acl extension only supports provider Openstack. It does so by reading the IP field of the provider's [infrastructureStatus](https://github.com/gardener/gardener-extension-provider-openstack/blob/8753a00f7dadf4427627dcc992a4dd7836f6cbbb/pkg/apis/openstack/v1alpha1/types_infrastructure.go#L108). For extensions that want to provide similar capabilities for all infra providers there are 2 major drawbacks to this approach currently:
- it requires the extension to expose such a field explicitly (which only Openstack and GCP partially support)
- it requires specific knowledge about the provider status - meaning that you need to import and consume the "openstack"-specific api packages and subsequently do the same for all other infra providers (assuming the previous point is resolved).

Proposed changes: 

## API field
Instead we can opt to make a more generalised API that is easier to consume by extensions. We propose the a field like:
```go
EgressCIDRs []string `json:"egressCIDRs,omitempty"`
```
As many providers support defining IPs and IP ranges in the form of CIDRs e.g. [azure](https://github.com/Azure/azure-sdk-for-go/blob/4661007ca1fd68b2e31f3502d4282904014fd731/sdk/resourcemanager/network/armnetwork/models.go#L9725), a generic string slice should be sufficient. IP family can be resolved by the `net.ParseCIDR` package so an explicit mention should not be necessary.

## Provider egress CIDR calculation:
Let's take a look at the current providers for how we can get the egress IPs of the shoot:

- AWS: 
   - the IP depends on the NAT Gateways of each zone ([ref](https://github.com/gardener/gardener-extension-provider-aws/blob/master/docs/usage/usage.md#infrastructureconfig)) - Static
- Openstack: 
   - the IP is that of the floating IP of the router - Static
- Azure: 
   - the IP is static if you use NAT Gateways (either use your own or provider-azure will create a public IP for you) - Static.
   - if you are not using NAT Gateways, the egress IP currently is a random one chosen from the list of frontendIPs of the LB. That means that it depends on the number of k8s LB services in the cluster - Dynamic.
- GCP:
   - the IP is static if the user provides his own IP - Static.
   - by default gardener-managed CloudNATs use "automatic" ip allocation. That means that depending on the scaling of the cluster, new IPs maybe added or removed - Dynamic.

## API resource 
The new `EgressCIDRs` field needs to reside in a resource that is readily accessible in the seed. The primary candidate would be the [InfrastructureStatus](https://github.com/gardener/gardener/blob/72ce85574d37e3a8ffcf2b082aca643f87059ed8/pkg/apis/extensions/v1alpha1/types_infrastructure.go#L91). 

By the time the infrastructure reconciles for **most** providers we have a good idea of the egress IPs, but as explained in certain scenarios the egress CIDR may be dynamic. 
This means that if we only populate the field during infrastructure reconciliation, we will not be able to support the dynamic scenarios as they may change outside the infra reconciliation. We can overcome this with a polling controller that is able calculate the correct CIDRs at any given time (mod requeue time). 

Regarding where the new field should be placed (one of the following):
- keep it with the infrastructureStatus
- move it in a separate resource e.g. `egressCIDRSlice`

Regarding its use (one of the following):
- only handle the static IP cases. Dynamic scenarios can be validated against if necessary (e.g. using the acl extension with a dynamic egress cidr). In this case we can directly produce the list after each infrastructure reconciliation.
- Add an additional controller/actuator that deals with populating the new field - either bundled with the provider extension or completely external - like the polling controller mentioned above.

The field should remain optional and the provider extensions can choose not to use it.

Regarding next implementation steps:
- At the very least we can start with handling the static IP cases and later extend it if there is need or is requested. The only difficulty for consumers like the ACL extension, will be handling the validation, as the validation requires specific provider knowledge to discern the dynamic cases mentioned above.

**Comment by rfranzke** [comment]
Thanks for the summary. I would also start with the static IP scenario only for now, and forbid the dynamic scenarios via validation. The respective code could still be put into the provider extensions (they could forbid using the `acl` extension when the dynamic scenario is configured) - I wouldn't move this into the ACL extension.
