### ISSUE TITLE
[Feature] Expose VPA recommendations as Prometheus metrics

### ISSUE THREAD

**Issue by PadmaB** [gardener/gardener#885]
# Story
As an operator, I would like to expose the recommendations from VPA as prometheus metrics

# Motivation
Run the VPA in the "Off" mode and observe its recommendations for a certain period of time and compare with the actual resource usage before actually applying those recommendations.
However, at the moment there is no way to expose the recommendations as prometheus metrics - will be convenient to have an exporter which does this job

# Acceptance Criteria
- [ ] To be able to view the recommendations from VPA as Prometheus Metrics and be able to create grafana dashboards for the same

**Comment by vlerenc** [comment]
That's with George, right? Assigning it to him then. I hope that's OK.
