### ISSUE TITLE
[GRM] Resource manager does not remove manually applied finalizers

### ISSUE THREAD

**Issue by dimityrmirchev** [gardener/gardener#8864]
**How to categorize this issue?**

/area robustness
/kind bug

**What happened**:
I created a managed resource that got successfully reconciled. I added a single finalizer to a deployment managed by the said MR. The finalizer was not removed.

**What you expected to happen**:
Since the applied objects are annotated with 
```
    resources.gardener.cloud/description: |-
      DO NOT EDIT - This resource is managed by gardener-resource-manager.
      Any modifications are discarded and the resource is returned to the original state.
```
I expect that the finalizer is removed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I am not 100% sure if this is a bug or not but at first thought is seems logical that the finalizers are also overwritten.

In a real world scenario we had a cluster being stuck in deletion because some of its system components (deployed via managed resources by Gardener) had a finalizer that was wrongfully added to them in the past.

**Comment by Kostov6** [comment]
This seems to be expected behaviour: https://github.com/gardener/gardener/pull/8584
