### ISSUE TITLE
Some networkpolices are missing within shoot-namespace

### ISSUE THREAD

**Issue by nitrocb** [gardener/gardener#8879]
**How to categorize this issue?**

/area control-plane
/area networking
/area security
/kind bug

**What happened**:

During shoot-creation, some networkpolicies within the shoot-namespace are missing:

- policy for allowing requests to cluster DNS (allow-to-dns)
- policy for allowing requests to private networks (allow-to-private-networks)

Those policies are present in the garden namespace (named like shown in the parantheses).
But they are missing in the shoot namespace.

Apparently this leads to different problems:

- Pods can not do DNS resolution
- Pods can not reach private networks outside of the cluster

When manually adding those policies (basically copying them from garden namespace), everything works fine.

**What you expected to happen**:

Those policies should be created automatically by gardener during shoot creation.

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy garden-cluster using gardener-operator
- Deploy Gardenlet into the same cluster, defining it as seed
- Create a shoot-cluster

**Anything else we need to know?**:

- The garden-cluster has been built using gardener operator.
- Gardenlet has been deployed into the garden-cluster, defining it also as the seed cluster.
- We are using a vSphere Tanzu cluster as base-cluster.

**Environment**:

- Gardener version: 
v1.80.7
- Kubernetes version (use `kubectl version`): 
v1.24.9+vmware.1
- Cloud provider or hardware configuration:
vSphere provider

**Comment by acumino** [comment]
@nitrocb Can you share the `OperatorConfiguration` yaml? Are you setting `operatorConfiguration.controllers.networkPolicy.concurrentSyncs` to > 0? Looking at the code I don't find any reason why the required networkpolicies should not get created. We rely on labels to create `netpol` in namespace and if ns 
 has `gardener.cloud/role: shoot`(Which is the case for ns created for shoot) the above netpols will get created.

**Comment by nitrocb** [comment]
@acumino Thanks for your answer!
my OperatorConfiguration basicly looks like this:


```
image:
  repository: <REDACTED>/eu.gcr.io/gardener-project/gardener/operator
  tag: v1.84.0
imageVectorOverwrite: |
  images:
    <REDACTED>
componentImageVectorOverwrites: |
  components:
  - name: etcd-druid
    imageVectorOverwrite: |
      images:
        <REDACTED>
```

So everything is on defaults except for the image locations.

I just tested the following:
I manually created a namespace with label `gardener.cloud/role: shoot`.
Within this namespace the `netpols` `allow-to-private-networks` and `allow-to-dns` get created by the operator successfully.

Then I created another shoot-cluster and in that controlplane-namespace, these `netpols` are again missing...
Here is the shoot manifest for that shoot:
[shoot-netpoltest.txt](https://github.com/gardener/gardener/files/13579512/shoot-netpoltest.txt)
Is there some setting for the shoot, which might prevent the creation of certain `netpols`?

I also recognized this log from the operator-pod:

`{"level":"error","ts":"2023-12-06T10:01:23.441Z","msg":"Reconciler error","controller":"networkpolicy","namespace":"","name":"shoot--test--netpoltest","reconcileID":"373f25e5-3823-4b27-b91f-f430f95d97ef","error":"failed to reconcile NetworkPolicy shoot--test--netpoltest/allow-to-private-networks: no kind is registered for the type v1alpha1.Cluster in scheme \"pkg/runtime/scheme.go:100\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}`

That would explain the missing "allow-to-private-networks" `netpol`, even if I do not understand what is happening there.

But there is no sign of the allow-to-dns `netpol` in the shoot-namespace either and due to the operator logfile, this is not even reconciled:

```
$ k logs gardener-operator-8879ff76b-fr7tc |grep allow-to-dns |grep "shoot--test--netpoltest"
$
```

Can you make any sense of this?

Thanks in advance!

**Comment by rfranzke** [comment]
@acumino Maybe we have to add the `extensions.gardener.cloud/v1alpha1` scheme to https://github.com/gardener/gardener/blob/fc80be941edf1381b7c792b27883614c47580c45/pkg/operator/client/scheme.go#L57-L66 to make this work

**Comment by acumino** [comment]
This is related to https://github.com/gardener/gardener/issues/8881 issue.

**Comment by acumino** [comment]
> @acumino Maybe we have to add the `extensions.gardener.cloud/v1alpha1` scheme to
> 
> https://github.com/gardener/gardener/blob/fc80be941edf1381b7c792b27883614c47580c45/pkg/operator/client/scheme.go#L57-L66
> 
> to make this work

Yes, I was guessing the same, but have not checked it.

**Comment by nitrocb** [comment]
Removed the rotten lifecycle, as this issue is still present.
Will try to find some time to try this fix:
https://github.com/gardener/gardener/issues/8879#issuecomment-1842592558
