### ISSUE TITLE
Extension CRDs are not deployed into seed-cluster automatically during gardenlet deployment

### ISSUE THREAD

**Issue by nitrocb** [gardener/gardener#8881]
**How to categorize this issue?**

/kind bug

**What happened**:

When deploying gardenlet into the garden-cluster, thus defining it as the initial seed, the extension CRDs are not deployed into the cluster.
But gardenlet is complaining about those missing CRDs (BackupBucket, BackupEntry, Bastion) and fails, because the appropriate controllers do not start correctly.

Here is the complete gardenlet log for consideration:
[gardenlet_log.txt](https://github.com/gardener/gardener/files/13510215/gardenlet_log.txt)

When I deploy the extension CRDs myself, then everything is working fine.

**What you expected to happen**:

The extension CRDs should be deployed automatically into the seed cluster.

**How to reproduce it (as minimally and precisely as possible)**:

- create a garden cluster using gardener operator
- deploy gardenlet into the same base cluster, defining it as the initial seed

**Anything else we need to know?**:

- garden-cluster has been built using gardener-operator
- garden-cluster and seed run on the same base-cluster
- base-cluster is a VMware tanzu cluster

**Environment**:

- Gardener version:
v1.84.0
- Kubernetes version (use `kubectl version`):
v1.24.9+vmware.1
- Cloud provider or hardware configuration:
vSphere provider

**Comment by acumino** [comment]
@nitrocb I tried the same setup and CRDs are getting deployed automatically. The log which you have shared, it's not complete(Enough), I don't see any log from the seed controller.
Can you provide more logs?

**Comment by nitrocb** [comment]
@acumino the seed controller runs in the gardener controller manager right?
I would need some time to do another test and gather these logs. I will provide them asap!

**Comment by nitrocb** [comment]
Here is the logfile of the gardener-controller-manager when deploying the gardenlet into the garden-cluster:
[gardener-controller-manager.txt](https://github.com/gardener/gardener/files/13671381/gardener-controller-manager.txt)
Unfortunately I do not see any obvious hints here. The gardenlet just stops reporting the seed status.

**Comment by acumino** [comment]
> @acumino the seed controller runs in the gardener controller manager right? I would need some time to do another test and gather these logs. I will provide them asap!

Seed controller in gardenlet, can you post gardenlet logs?

**Comment by nitrocb** [comment]
Ok, I just realized, that there should be a seed controller running in the gardenlet.
So here is also a log from the gardenlet , where I manually added the CRDs:

[gardenlet_after_manual_CRD_deployment.txt](https://github.com/gardener/gardener/files/13671662/gardenlet_after_manual_CRD_deployment.txt)

You can see there, that the seed controller is started and acting normal.
But in the logfile from the gardenlet, where the CRDs are not deployed yet, the seed controller is not started as it seems, but I am not sure why.

**Comment by acumino** [comment]
> Ok, I just realized, that there should be a seed controller running in the gardenlet. So here is also a log from the gardenlet , where I manually added the CRDs:
> 
> [gardenlet_after_manual_CRD_deployment.txt](https://github.com/gardener/gardener/files/13671662/gardenlet_after_manual_CRD_deployment.txt)
> 
> You can see there, that the seed controller is started and acting normal. But in the logfile from the gardenlet, where the CRDs are not deployed yet, the seed controller is not started as it seems, but I am not sure why.

Can you post logs without manually deploying CRDs? As I mentioned when i tested CRDs were deployed automatically

**Comment by acumino** [comment]
What is the seed status?

**Comment by nitrocb** [comment]
Here is the seed status:

```
Status:
  Conditions:
    Last Transition Time:  2023-12-14T09:22:25Z
    Last Update Time:      2023-12-14T09:22:27Z
    Message:               Some extensions are not valid: map[provider-dns-infoblox-str24:The condition has been initialized but its semantic check has not been performed yet. provider-vsphere-qkx29:The condition has been initialized but its semantic check has not been performed yet.]
    Reason:                NotAllExtensionsValid
    Status:                False
    Type:                  ExtensionsReady
    Last Transition Time:  2023-12-14T09:22:35Z
    Last Update Time:      2023-12-14T09:22:35Z
    Message:               Gardenlet stopped posting seed status.
    Reason:                SeedStatusUnknown
    Status:                Unknown
    Type:                  GardenletReady
Events:                    <none>
```

**Comment by acumino** [comment]
As you can see from the seed status your extensions are not ready, therefore reconciliation is not proceeding.

**Comment by nitrocb** [comment]
Yes, thats correct and that was also my first investigation. But the managedresources for the extensions do not even get deployed, which should be done by the gardenlet. So it makes sense to me that the extensions are not ready.

As soon as I deploy the extension CRDs manually and restart the gardenlet, the extensions and everything else gets deployed without a problem. So I would not suspect a problem with the extensions here.

I am not familiar with the insights of this process, but it seems to me, that the seed controller would be startet after the controllers for the CRDs, but the CRD controller failures are preventing the progress to the seed controller start. Not sure if that makes sense.

**Comment by nitrocb** [comment]
The thing also is, that if I create a managedseed, the gardenlet there is also able to deploy the extension CRDs without a problem and the seed creation is flawlessly. It is only not working in my setup when deploying the gardenlet directly into the garden-cluster.

**Comment by acumino** [comment]
Error seems to be related to cluster-identity. can you post seed status by doing `kubectl get seed <seed-name> -oyaml`

**Comment by nitrocb** [comment]
Here is the complete seed yaml:

```
apiVersion: core.gardener.cloud/v1beta1
kind: Seed
metadata:
  creationTimestamp: "2023-12-14T09:22:25Z"
  finalizers:
  - core.gardener.cloud/controllerregistration
  generation: 1
  labels:
    dnsrecord.extensions.gardener.cloud/infoblox-dns: "true"
    gardener.cloud/role: seed
    provider.extensions.gardener.cloud/vsphere: "true"
  name: soil-local
  resourceVersion: "5872"
  uid: addb42e7-81e3-45eb-a658-889e026d98d4
spec:
  dns:
    provider:
      secretRef:
        name: internal-domain-soil
        namespace: garden
      type: infoblox-dns
  ingress:
    controller:
      kind: nginx
    domain: <REDACTED>
  networks:
    ipFamilies:
    - IPv4
    nodes: <REDACTED>
    pods: <REDACTED>
    services: <REDACTED>
    shootDefaults:
      pods: <REDACTED>
      services: <REDACTED>
  provider:
    providerConfig:
      svStorageClass: <REDACTED>
    region: <REDACTED>
    type: vsphere
  settings:
    dependencyWatchdog:
      prober:
        enabled: true
      weeder:
        enabled: true
    excessCapacityReservation:
      configs:
      - resources:
          cpu: "2"
          memory: 6Gi
    scheduling:
      visible: true
    topologyAwareRouting:
      enabled: false
    verticalPodAutoscaler:
      enabled: false
status:
  conditions:
  - lastTransitionTime: "2023-12-14T09:22:25Z"
    lastUpdateTime: "2023-12-14T09:22:27Z"
    message: 'Some extensions are not valid: map[provider-dns-infoblox-str24:The condition
      has been initialized but its semantic check has not been performed yet. provider-vsphere-qkx29:The
      condition has been initialized but its semantic check has not been performed
      yet.]'
    reason: NotAllExtensionsValid
    status: "False"
    type: ExtensionsReady
  - lastTransitionTime: "2023-12-14T09:22:35Z"
    lastUpdateTime: "2023-12-14T09:22:35Z"
    message: Gardenlet stopped posting seed status.
    reason: SeedStatusUnknown
    status: Unknown
    type: GardenletReady
```

**Comment by acumino** [comment]
Can we continue the discussion on slack?

**Comment by nitrocb** [comment]
alright, sent you a PN on slack ;-)

**Comment by nitrocb** [comment]
I am back with new insights:

I found that the problem with the CRDs not being created is somehow connected with the k8s version of the seed cluster.
When I use k8s version below 1.27, then this problem occurs. This is even occuring with ManagedSeeds, where the target shoot cluster is on 1.26 for example.

As soon as I use a k8s cluster with version 1.27, it is working fine.
Could it be, that the gardenlet somehow requires k8s 1.27 at a minimum?

**Comment by acumino** [comment]
After checking the gardenlet logs I reached the following conclusion - 
- The issue is not related to Kubernetes version.
- You are trying to deploy seed without VPA enabled.

Fix should be, either deploy Seed with VPA enabled or manually deploy the VPA CRD in the cluster as VPA CRD is a must requirement, [ref](https://github.com/gardener/gardener/blob/96335a6487944f05322ac8f182f46c1e738ee2ff/pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go#L178-L183).
