### ISSUE TITLE
Protect Privileged Container from Access

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener#89]
# Story

As provider of Garden cluster I want the possibility to provide my customers with clusters that do not allow privileged containers. Today certain containers are privileged such as the Calico container where clusters users can log on. This should be prohibited.

# Accptance criteria

[ ] Access to privileged pods in the shoot cluster is not possible anymore

**Comment by mvladev** [comment]
@marwinski there are 2 different scenarios: Disable `attach` and `exec` with [DenyEscalatingExec](https://kubernetes.io/docs/admin/admission-controllers/#denyescalatingexec) and [PodSecurityPolicy](https://kubernetes.io/docs/concepts/policy/pod-security-policy/). Are you referring to both of them or a single one?

**Comment by vlerenc** [comment]
Why do we have this requirement? It doesn't fit the situation we have today. Can we please close it or can you please formulate the big picture and corresponding epic first? As it stands right now (and for the coming months), there is only (cluster-)admin access and then there is nothing to be restricted. Even if you disable privileged containers in the API server configuration, which we actually allow to configure, there are other loopholes, e.g. hostPath mounts of Docker. I doubt you can make the users cluster-admins, but limit what they can do. At least it would be helpful to see the full plan laid out somewhere before we engage in effort.

Formally: The story description mixes story with motivation. In this story you do not want to disable privileged containers, but the access to them. The first sentence speaks about the first topic, which is a prerequisite whereas the second part of the loophole via already privileged containers. Also, DoD is missing, which is formal requirement to offer some transparency and traceability in quality measures that will help ease our program management.

**Comment by vlerenc** [comment]
Closing as we hand out cluster admin creds. Cluster admins may still choose to add more users and restrict access with RBAC/PSPs.
