### ISSUE TITLE
Make seed prometheus configurations extendable 

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#8924]
**How to categorize this issue?**

/area monitoring
/kind enhancement

**What would you like to be added**:
Make seed prometheus configurations extendable. Other seed level observability components like the alertmanager also needs to be extendable. 

**Why is this needed**:
There are components running in the seed clusters that expose metrics, however the seed prometheus is statically configured with restricted targets to scrape, for example https://github.com/gardener/gardener/blob/53e08c3d5c8ff6dc77f4dd361f833f931c10c129/pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/config.yaml#L14-L40 
It would be nice this prometheus instance configuration to be extendable so that 3rd party extensions deployed in other namespaces, e.g. kube-system, to be also scraped, for example this is a prerequisite for https://github.com/gardener/gardener-extension-shoot-lakom-service/issues/55.

**Comment by rfranzke** [comment]
This should be supported meanwhile: https://github.com/gardener/gardener/blob/master/docs/extensions/logging-and-monitoring.md#seed-prometheus
/close
