### ISSUE TITLE
What's the default value of forceTCPToUpstreamDNS and forceTCPToClusterDNS

### ISSUE THREAD

**Issue by chengshifan** [gardener/gardener#8928]
forceTCPToClusterDNSbool | (Optional)ForceTCPToClusterDNS indicates whether the connection from the node local DNS to the cluster DNS (Core DNS) will be forced to TCP or not. Default, if unspecified, is to enforce TCP.
-- | --
forceTCPToUpstreamDNSbool | (Optional)ForceTCPToUpstreamDNS indicates whether the connection from the node local DNS to the upstream DNS (infrastructure DNS) will be forced to TCP or not. Default, if unspecified, is to enforce TCP.

How to understand *Default, if unspecified, is to enforce TCP.* ?

Is it true or false when default ?

**Comment by ScheererJ** [comment]
If the attribute is unspecified the code handles it as if the value `true` would have been set. However, the attribute is not defaulted in the sense that it will show up in the shoot specification unless set explicitly.

/close

**Comment by chengshifan** [comment]
Thanks @ScheererJ for your information
