### ISSUE TITLE
[Node Agent] Support patching `containerd` config file

### ISSUE THREAD

**Issue by dimityrmirchev** [gardener/gardener#8929]
**How to categorize this issue?**

/area quality os
/kind enhancement

This proposal was inspired by a discussion with @ialidzhikov. Thanks!

**What would you like to be added**:
`kind` supports patching of the `containerd` configuration. We make use of this feature in our local setup https://github.com/gardener/gardener/blob/b83a3a0932698ebf267462dff30f3e31c8f912ac/example/gardener-local/kind/cluster/templates/cluster.yaml#L34-L37

I propose that we extend the `OperatingSystemConfig` with a similar API so that the `node-agent` can apply these patches to the `containerd` configuration and restart `containerd` if needed. Here is [the kind implementation](https://github.com/kubernetes-sigs/kind/blob/fa9c89d2832ed643ce46eeafdc1ada469252e064/pkg/cluster/internal/create/actions/config/config.go#L118-L148).

**Why is this needed**:
The current import functionality is not robust enough to be used in certain scenarios. See https://github.com/gardener/gardener/issues/7838

Extensions that need to modify the `containerd` configuration usually deploy a daemonset which makes use of some error prone and limited scripting in order to apply changes to the config file. It would be nice if such extensions can simply modify the OSC with a webhook requesting the changes they need.

Some examples of such scripting:
- [Gvisor](https://github.com/gardener/gardener-extension-runtime-gvisor/blob/25339b3804805e5e3ed2fade9031f0dbbe4c23cd/charts/internal/gvisor-installation/templates/configmap-containerd.yaml#L8-L72)
- [Kata](https://github.com/23technologies/gardener-extension-runtime-kata/blob/c8e90cbd39db04fc7413e94354ba1fc7da05f32f/charts/internal/kata-deploy/scripts/process-config.py#L7-L16)

**Comment by ialidzhikov** [comment]
@timuthy , I think we can close this as https://github.com/gardener/gardener/pull/10167 is merged, right?
