### ISSUE TITLE
[Gardenlet] Sync shoot service account discovery metadata into Garden cluster

### ISSUE THREAD

**Issue by dimityrmirchev** [gardener/gardener#8937]
**How to categorize this issue?**

/area security
/kind enhancement

This proposal was insiped after several discussions on the topic "Bring your own OIDC compatible provider in the Garden cluster".

Kubernetes clusters can act as an OIDC compatible provider in a sense that they serve OIDC discovery documents. These documents if publicly accessible can be used by other systems to establish trust to such clusters by fetching the public key of the private key that is used to sign service account tokens. These public keys can be then used by external systems to verify that a service account token is issued by a particular cluster and then grant access to the bearer of that token. As example of such integration we can use Google's [Workload Indentity Federation](https://cloud.google.com/iam/docs/workload-identity-federation-with-kubernetes#kubernetes_1) with a K8S Cluster.

By default Gardener creates clusters which expose such documents directly through the `kube-apiserver`. This has several drawbacks:
 - The `kube-apiserver` is protected and unless you have annonymous authentication on then the endpoint requires authn.
 - The certificate used to serve the documents is not signed by a trusted CA.

Gardener also provides means for users to tweak such config and overcome these drawbacks by using the following [shoot configurations](https://github.com/gardener/gardener/blob/580324da9af4ec47955d9e216569d09053c5d008/example/90-shoot.yaml#L201-L204). Once the issuer of a shoot is changed the user can take over that domain and expose the OIDC metadata documents to the public. This poses another challenge since it requires additional involvement. Some users use istio/nginx igress to do so, others make use of projects like [service-account-issuer-discovery](https://github.com/gardener/service-account-issuer-discovery), or combination of both.

I propose that we start thinking in the direction of taking ownership of a shoot's issuer. Ideally a central place which can serve all shoots OIDC discovery documents. AFAIK Google is already exposing such information for GKE clusters. URIs look something like https://container.googleapis.com/v1/projects/PROJECT/locations/LOCATION/clusters/NAME/.well-known/openid-configuration. See https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters.well-known/getOpenid-configuration. Mind that on Google side the documentation states "This API is not yet intended for general use, and is not available for all clusters."

What are the benefits?
 - Users will get out of the box solution which can serve their shoot's OIDC discovery documents. Even for clusters which reside in isolated environments, i.e. are protected by firewalls, have limited access to the outside etc.
 - The Garden cluster can be easily configured to trust shoot clusters by using [Structured Authentication](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3331-structured-authentication-configuration) or [OIDC Webhook Authenticator](https://github.com/gardener/oidc-webhook-authenticator) without giving regular users access to error prone trust configurations. It would also keep the control in Gardener's hands, i.e. user and groups prefixes will be configured so that overlaping and impersonation is not possible and when a shoot is deleted the trust can be immediatelly broken.
 - Users will be able to configure workloads in their clusters to directly communicate with the Gardener API, without transporting credentials to that cluster beforehand.

What needs to be done?
 - Gardenlet should start synchronizing OIDC metadata information for all (or just selected) shoots in the Garden cluster. This can be done in a configmap/secret or some CR in a dedicated namespace. Credential rotation should also be accounted for. Even this step alone will provide with the ability to configure "offline" trust via `openidconnect` CRs (see [example](https://github.com/gardener/oidc-webhook-authenticator/blob/dbe80607f6df11cb3a68ff74d7a2d6bb8be738a8/apis/authentication/v1alpha1/openidconnect_types.go#L134)).
 - Shoots should have an immutable trigger that means "manage my issuer". This should be available for new shoots and shoots that do not make use of custom [serviceaccount issuer configs](https://github.com/gardener/gardener/blob/580324da9af4ec47955d9e216569d09053c5d008/example/90-shoot.yaml#L201-L204).
 - A publicly exposed component should be taught to serve the metadata information for all (or selected number) of shoots.

Related requests:
- https://github.com/gardener/gardener/issues/8859

**Comment by vlerenc** [comment]
@dimityrmirchev Do you maybe have another link/docs where Google gives more details on GKE and this information? The page you referenced says:
> This API is not yet intended for general use, and is not available for all clusters.
I would be interested to know:
a.) What does Google mean with "not yet intended for general use"?
b.) For which clusters is that feature available and for which is it not?

**Comment by dimityrmirchev** [comment]
> I would be interested to know:
a.) What does Google mean with "not yet intended for general use"?
b.) For which clusters is that feature available and for which is it not?

Sadly, I did not find any other documents about this feature in Google docs. I might open a question directly to their support. I also did some experimenting with AKS and EKS.

In AKS it is possible to enable this feature which changes the issuer of a cluster and then this gets served on a central endpoint. Here is [the documentation](https://learn.microsoft.com/en-us/azure/aks/use-oidc-issuer) for this feature. They even warn that if enabled this cannot be changed back to disabled state.

For EKS I created a cluster and it seems that they already have this ON by default. I did not find any way to disable/influence it.

<img width="1091" alt="image" src="https://github.com/gardener/gardener/assets/28221091/38ca14a3-03da-4cfe-bfcb-52ec5b6fe71f">

**Comment by dimityrmirchev** [comment]
I also got back from GCP support. They reached out to their their internal product specialist team and I got informed that the API mentioned in https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters.well-known/getOpenid-configuration is available for general use and also for all clusters. I guess that their documentation is outdated.

**Comment by vlerenc** [comment]
Excellent.

**Comment by georgi-lozev** [comment]
We are one of those using the [service-account-issuer-discovery](https://github.com/gardener/service-account-issuer-discovery) and we'll appreciate if we get the out of the box solution from Gardener.

Looking forward to this enhancement.

**Comment by uwefreidank** [comment]
> We are one of those using the [service-account-issuer-discovery](https://github.com/gardener/service-account-issuer-discovery) and we'll appreciate if we get the out of the box solution from Gardener.
> 
> Looking forward to this enhancement.

Same from our side. Would be very helpful, if we can enable the service-account-issuer-discovery via shoot spec.

**Comment by dimityrmirchev** [comment]
The functionalities are mostly implemented by https://github.com/gardener/gardener/issues/9157

> The Garden cluster can be easily configured to trust shoot clusters by using [Structured Authentication](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3331-structured-authentication-configuration) or [OIDC Webhook Authenticator](https://github.com/gardener/oidc-webhook-authenticator) without giving regular users access to error prone trust configurations. It would also keep the control in Gardener's hands, i.e. user and groups prefixes will be configured so that overlaping and impersonation is not possible and when a shoot is deleted the trust can be immediatelly broken.


This part can be achieved but is not automated as of now and is probably out of the scope of this issue, so we can close it for now.

/close
