### ISSUE TITLE
Switch to `etcd-druid-api`

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener#8941]
**How to categorize this issue?**
/area dev-productivity
/kind enhancement

**What would you like to be added**:

Are there any plans in switching the `etcd-druid` dependency to `etcd-druid-api`?

**Comment by timuthy** [comment]
As discussed via chat there are mainly two prerequisites missing to switch to `etcd-druid-api`:
- Release of `https://github.com/gardener/etcd-druid-api`
- Drop [validation dependency](https://github.com/gardener/gardener/blob/cdad185a27b39b2f35b8ae4d921273d65ae164ae/pkg/resourcemanager/webhook/extensionvalidation/handler.go#L165C3-L179) via https://github.com/gardener/etcd-druid/issues/409.

**Comment by unmarshall** [comment]
We are planning to switch to the new API repo in 2 phases:

1. Current version of API is `v1alpha1` which will continue to be there in the new github project. etcd-druid will consume this version currently. Once that is done then we can start to also adapt g/g to consume the API repo directly thus removing the current cyclic dependency between the two repos.
2. We have started work on creating `v1beta1` of the API which has a LOT of breaking changes. This will be require some additional support like api conversion-webhook to enable support for both versions for some time. I am expecting a tentative timeline of first quarter for that.

**Comment by afritzler** [comment]
Thanks @unmarshall for the update.

**Comment by afritzler** [comment]
I guess we can then close/freeze this issue for now.

**Comment by timuthy** [comment]
/close
We will revisit this topic once the said prerequisites are solved.
