### ISSUE TITLE
Reconcile Failed on openstack 

### ISSUE THREAD

**Issue by mervynzhang** [gardener/gardener#8942]
Hi gardener team,

We have a canary shoot on openstack (ccloud). One node stop working and we delete it on openstack. 

gardener keep reporting even this node is already gone.

```
Reconcile Failed
Worker extension (shoot--**/**-nonprod) reports failing health check: machine "shoot--***-c32m384-v100g3-z1-67ff4-ql6p9" failed: Machine shoot--***-c32m384-v100g3-z1-67ff4-ql6p9 is not healthy since 10m0s minutes. Changing status to failed. 
```
A new node has been created on openstack, but gardener just ignore it and keep reporting above error.

**Comment by timuthy** [comment]
Please open an issue in your internal landscape ticket system to analyze the problem with your shoot.
/close
