### ISSUE TITLE
[Flaky Test] Seed Tests Renew gardenlet kubeconfig

### ISSUE THREAD

**Issue by acumino** [gardener/gardener#8954]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
Seed Tests Renew gardenlet kubeconfig [It] should renew the gardenlet garden kubeconfig when triggered by annotation
```
 [FAILED] in [It] - /home/prow/go/src/github.com/gardener/gardener/test/utils/rotation/gardenlet_kubeconfig.go:121 @ 12/05/23 11:14:42.037
  < Exit [It] should renew the gardenlet garden kubeconfig when triggered by annotation @ 12/05/23 11:14:42.037 (5m26.823s)
  << Timeline
  [FAILED] Timed out after 300.000s.
  Expected success, but got an error:
      <*errors.errorString | 0xc00097bb70>: 
      kubeconfig secret has not yet been renewed, timeBeforeRotation: 2023-12-05 11:09:15.213976419 +0000 UTC, newClientCertificateIssuedAt: 2023-12-05 10:55:37 +0000 UTC
      {
          s: "kubeconfig secret has not yet been renewed, timeBeforeRotation: 2023-12-05 11:09:15.213976419 +0000 UTC, newClientCertificateIssuedAt: 2023-12-05 10:55:37 +0000 UTC",
      }
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/utils/rotation/gardenlet_kubeconfig.go:121 @ 12/05/23 11:14:42.037
```

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8869/pull-gardener-e2e-kind/1731988540067155968
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8906/pull-gardener-e2e-kind/1732023885148196864
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8897/pull-gardener-e2e-kind/1732238516160565248
https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind/1732244661927415808

**Reason for failure**:

**Anything else we need to know**:
In all the case which is mentioned, the selected seed is `e2e-managedseed`.
/cc @oliver-goetz

**Comment by shafeeqes** [comment]
More occurrences:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/9025/pull-gardener-e2e-kind/1745291920587886592
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/9019/pull-gardener-e2e-kind/1745036135509266432
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8877/pull-gardener-e2e-kind/1745034813175238656
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/9017/pull-gardener-e2e-kind/1744811345166995456
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/9013/pull-gardener-e2e-kind/1744787429602103296
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8999/pull-gardener-e2e-kind/1744784164562931712
