### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by NHingerl** [gardener/gardener#8971]
Documentation issue at https://gardener.cloud/docs/gardener/concepts/architecture/

Your document has the name "Architecture", but the first (h2) headline is "What is Kubernetes?" (and it has no h1 headline). When I open a file called "Architecture", I thought I'll learn about Gardener's architecture, not about K8s in general. 

At a first glance, the following two sections also don't seem to be related to architecture. 

I have to scroll down to https://gardener.cloud/docs/gardener/concepts/architecture/#overview-architecture-diagram until I finally see what I thought I'd find on the "Architecture" page. 
But then again, this and the following diagrams don't have much explanation. I suspect that architecture explanation might be hidden somewhere in "Setting The Scene - Components and Procedure", but it's not immediately clear. 

I'd suggest changing the document title to "Architecture" (as h1 headline) and editing the descriptions so they're more clearly related to the architecture diagram.

**Comment by n-boshnakov** [comment]
> > When I open a file called "Architecture", I thought I'll learn about Gardener's architecture, not about K8s in general.
> 
> The thing is, in order to make the (rather complex) architecture of Gardener easier understandable/consumable, we have to first explain/reiterate on a few concepts of Kubernetes (because that's what people typically already know) and compare them to what we have built with Gardener. That's why we start with "What is Kubernetes?" first.
> 
> > But then again, this and the following diagrams don't have much explanation. I suspect that architecture explanation might be hidden somewhere in "Setting The Scene - Components and Procedure", but it's not immediately clear.
> 
> Fair enough, I agree that this page doesn't explain much. I'd definitely be happy about seeing more content there (maybe @n-boshnakov can help here?).

Of course, I'd be glad to help. We can set up a sync and discuss what content you'd like added and how to go about it.

**Comment by NHingerl** [comment]
@n-boshnakov 😆  just now I realize I'm creating work for you here. 
Do you think this is something that could be improved? If yes, could we un-stale the issue? 
Otherwise, if this won't be fixed, it could be closed with "won't fix" or any matching status.

**Comment by n-boshnakov** [comment]
> @n-boshnakov 😆 just now I realize I'm creating work for you here. Do you think this is something that could be improved? If yes, could we un-stale the issue? Otherwise, if this won't be fixed, it could be closed with "won't fix" or any matching status.

I had a sync with Rafael Franzke on the issue, and he said that there is currently no capacity to tackle the documentation update. Therefore, we will be closing the issue for the moment.
