### ISSUE TITLE
Shoot-specific `EnvoyFilter` Remains in Old Ingress Namespace when Upgrading `Shoot` to Zone-HA

### ISSUE THREAD

**Issue by SimonKienzler** [gardener/gardener#8982]
**How to categorize this issue?**

/area networking
/kind bug

**What happened**:

A Shoot runs on a zonal-HA Seed, but is itself not highly available. This means it uses an ingress namespace like `istio-ingress--az-1`, i.e. a "zonal" ingress namespace for the zone its control plane is in. When converting this `Shoot` to Zone-HA (`controlPlane.highAvailability.failureTolerance.type: zone`), its ingress namespace changes (to `istio-ingress`). With this change, a Shoot -specific `EnvoyFilter` is created in the `istio-ingress` namespace. In our environment, we're observing that the shoot-specific `EnvoyFilter` in the previous (non-HA) ingress namespace remains after converting the `Shoot` to HA. This is not bad per se (no traffic is routed via this ingress anymore for the Shoot in question), but it seems like something that should be removed to fully complete the switch.

**What you expected to happen**:

After the conversion of the `Shoot` to zonal HA, I expect the non-HA ingress namespace (for the single zone the `Shoot`s control plane used to be in) to have no leftovers from this particular `Shoot`.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy a non-HA `Shoot` on an HA `Seed`, so that it uses a zonal ingress namespace (let's say `istio-ingress--az-1` for clarity).
2. Confirm that Gardener has created an `Envoyfilter` object in that ingress namespace, called `shoot-<projectID>-<shootName>`.
4. Upgrade the `Shoot` to zone-HA by setting `controlPlane.highAvailability.failureTolerance.type: zone` and wait for the `Shoot` to be converted.
5. Observe the newly created `EnvoyFilter` object in the HA ingress namespace (`istio-ingress`) with the same name as in the old namespace (`shoot-<projectID>-<shootName>`).
6. In the old ingress namespace `istio-ingress--az-1`, the `shoot-<projectID>-<shootName>` `EnvoyFilter` still exists (unnecessarily).

**Anything else we need to know?**:

This issue has been opened based on [this slack thread](https://gardener-cloud.slack.com/archives/C047S4N9NTV/p1702906700265569).

**Environment**:

- Gardener version: current (`v1.86.0`)
- Cloud provider or hardware configuration: OpenStack

**Comment by timuthy** [comment]
Such a cleanup would come out of the box if we used a `ManagedResource`, also in the light of https://github.com/gardener/gardener/issues/8241.
