### ISSUE TITLE
Provision via ACS

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#9]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:44 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/16_

----

# Stories
* As provider I want to provision Kubernetes via ACS, so that we dont have to provision Kubernetes ourselves on Azure (when SAP or customers need to run it side-by-side) and benefit from a probably more competitive solution than whatever we can do (in terms of full management and pricing).

# Motivation
Do not engage in Kubernetes provisioning when there are competitive native solutions, especially when customers already run on that infrastructure and use/manage/operate the same native solutions.

# Acceptance Criteria
- [ ] ACS Kubernetes cluster can be created via the Gardener and offers about the same functionality as what we have on AWS (to be clarified)

:information_source: Migrated from Jira issue [KUBE-83](https://jtrack.removed/browse/KUBE-83)

**Comment by vlerenc** [comment]
Dropped out of scope.
