### ISSUE TITLE
Shoot resource status.lastOperation.description can get too large (easily reach resource size limit)

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#9039]
**What happened**:
We have seen, e.g. when people fail to update their credentials, that the error message repeats in `status.lastOperation.description`, e.g. for each node separately (observed by @mliepold @kon-angelo), driving the size of the `shoot` resource beyond the permitted limit, breaking further automated updates that do not strip the status first.

**What you expected to happen**:
It seems reasonable to prevent status updates from blowing up the resource in this way and either do not repeat the same message (may or may not be easy to achieve or at least truncate the field if it gets "too" large). @kon-angelo suggested:
> It should be handled for all extensions and most of their code reside in the form of libraries in gardener/gardener.

**How to reproduce it (as minimally and precisely as possible)**:
Please contact the above mentioned colleagues.

**Comment by vlerenc** [comment]
I added the label `enhancement` rather than `bug`, but this behaviour may feel to the affected people more like a bug, because they a.) rarely know what the error messages means and b.) don't know what to do then. This is what we have observed.

**Comment by timuthy** [comment]
Yep, makes sense 👍

**Comment by timuthy** [comment]
We could combine this enhancement with a relaxed validation for `last-applied-configuration` and `managed-fields` fields, as discussed as while ago.

**Comment by timuthy** [comment]
@LucaBernstein would you like to take this?
