### ISSUE TITLE
Upgrade `k8s.io/*` to `v0.29`, `sigs.k8s.io/controller-runtime` to `v0.17`

### ISSUE THREAD

**Issue by acumino** [gardener/gardener#9047]
**How to categorize this issue?**

/area open-source dev-productivity
/kind enhancement

**What would you like to be added**:

We should upgrade to the latest versions of our go upstream dependencies:
- `sigs.k8s.io/controller-runtime@v0.17.0`: https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.17.0
- `k8s.io/*@v0.29.0`

## Important changes / Action items
- [x] Adapt the new [restmapper](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/client/apiutil/restmapper.go) implementation.
https://github.com/kubernetes-sigs/controller-runtime/pull/2571. Follow up of https://github.com/gardener/gardener/issues/8382.
- [x] Replace `ResourceRequirements` struct with `VolumeResourceRequirements` for use with volumes: https://github.com/kubernetes/kubernetes/pull/118653
- [x] Fake client now sets TypeMeta only for unstructured objects: https://github.com/kubernetes-sigs/controller-runtime/pull/2633

Here is a list of a few upstream changes to look out for when vendoring g/g, k/* and c-r in any of our repos (e.g. extensions). Please consider the release notes of [controller-runtime@v0.17](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.17.0) and upwards as well for a complete list and more details.

### ⚠️ breaking / most notable changes 
- Removing informers from cache.Cache is now possible: https://github.com/kubernetes-sigs/controller-runtime/pull/2285
- client.MatchingFields now supports multiple indexes: https://github.com/kubernetes-sigs/controller-runtime/pull/2512

### ℹ️ other changes / good to know / for information only:
- ...

**Comment by shafeeqes** [comment]
Will wait until #8989 is merged to tackle this issue since the PodSecurity API is removed with v0.29.0 and so on..

**Comment by shafeeqes** [comment]
/close
All tasks are completed
