### ISSUE TITLE
Improve sync between `Cluster` object and `Shoot` information

### ISSUE THREAD

**Issue by nschad** [gardener/gardener#9078]
**How to categorize this issue?**
/area ops-productivity
/kind enhancement

We have noticed in our gardener version (v1.75 to be fair) that it takes quite some time for some information, after shoot creation, like the `AdvertisedAddresses` to be populated into the `Cluster` object of the shoot.

**What would you like to be added**:

Faster sync for information that are pre-known before creation or immediately known after creation.

**Why is this needed**:

* Reduce load on virtual-garden for extensions.
* Avoids some "fake" error state for extensions that can not yet fetch the information.

**Comment by rfranzke** [comment]
We were actually thinking of eliminating the `extensions.gardener.cloud/v1alpha1.Cluster` object completely and let extensions directly talk to the virtual garden, now that #8001 is possible. While we haven't fully agreed on really pursuing this goal, it's probably still questionable whether to invest into your request. I would advise to read the information directly from the `Shoot` object in the virtual garden for now.
