### ISSUE TITLE
Local development setup doesn't work with external dns provider

### ISSUE THREAD

**Issue by pablochacin** [gardener/gardener#910]
After introducing the external DNS Provider, the local setup fails to create a shoot.

The Controller reflects the following error message:
```
Could not initialize a new operation: unable to figure out which secret should be used for dns
```

**Comment by ialidzhikov** [comment]
@mvladev , @rfranzke , do you have any suggestions here? Do we need to introduce for the local provider a dummy `DNSProvider` of type `unmanaged` that will create the nip.io `DNSEntries` and update their status to Ready?

**Comment by rfranzke** [comment]
If provider=unmanaged we should not check whether there is a DNS extension, we don't need a dummy provider.

**Comment by vpnachev** [comment]
I am running locally a fix for that. Just need some time to test it and I will open a PR.
