### ISSUE TITLE
Provider local scenario cannot start with calico 3.27.2

### ISSUE THREAD

**Issue by nickytd** [gardener/gardener#9261]
/area testing
/kind bug 

**What happened**:
`make kind-up` timeouts with
```
Error: FelixConfiguration 'default' not found or patch failed after 600 attempts.
```
The root cause is that `calico-node` cannot start with following error
`calico-node: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory`

There is an issue reported in the upstream project
https://github.com/projectcalico/calico/issues/8541

**Environment**:
arm64 Darwin
- Gardener version:
v1.90.0-dev

**Comment by plkokanov** [comment]
We could revert this change https://github.com/gardener/gardener/pull/9241 and potentially only update calico to 3.27.0 or 3.27.1 (if the problem does not appear there as well)
