### ISSUE TITLE
Silence Monitoring Alerts for Integration/Conformance/E2E Tests

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#938]
What can we do to silence monitoring alerts for integration/conformance/e2e tests?

cc: @wyb1 @dkistner @dguendisch @schrodit @OlegLoewen

**Comment by OlegLoewen** [comment]
Short update:
monitoring/alerting team will introduce a new label handling. If a cluster contains the corresponding label, alerting will be ignored. Output qualification team will ingest this label into all test clusters.

**Comment by wyb1** [comment]
We plan on introducing a new annotation for shoot clusters `garden.sapcloud.io/ignore-alerts`. If this annotation is `true` then the central alertmanager will not send any alerts for this shoot and the shoot specific alertmanager will not be deployed. We will also add an external label for the prometheus config `ignoreAlerts`. This will only be true if the annotation `garden.sapcloud.io/ignore-alerts` is set to true. All alerts from an "ignored" shoot will have this `ignoreAlerts` label and the alertmanager will know not to send any alerts for this cluster.

**Comment by vlerenc** [comment]
Thank you!
