### ISSUE TITLE
make gardener-up issue

### ISSUE THREAD

**Issue by miteshjpatel** [gardener/gardener#9469]
**How to categorize this issue?**

Hello I am new to Gardener and need some help starting gardener on my Ubuntu server. 

/area TODO
/kind bug

**What happened**: Ran command gardener-up it ran successfully 
Ran command skaffold run --tail I see following error

sudo skaffold run --tail
WARN[0000] failed to detect active kubernetes cluster node platform. Specify the correct build platform in the `skaffold.yaml` file or using the `--platform` flag  subtask=-1 task=DevLoop
Generating tags...
 - europe-docker.pkg.dev/gardener-project/releases/gardener/apiserver -> europe-docker.pkg.dev/gardener-project/releases/gardener/apiserver:latest
 - europe-docker.pkg.dev/gardener-project/releases/gardener/controller-manager -> europe-docker.pkg.dev/gardener-project/releases/gardener/controller-manager:latest
 - europe-docker.pkg.dev/gardener-project/releases/gardener/scheduler -> europe-docker.pkg.dev/gardener-project/releases/gardener/scheduler:latest
 - europe-docker.pkg.dev/gardener-project/releases/gardener/admission-controller -> europe-docker.pkg.dev/gardener-project/releases/gardener/admission-controller:latest
 - europe-docker.pkg.dev/gardener-project/releases/gardener/extensions/provider-local -> europe-docker.pkg.dev/gardener-project/releases/gardener/extensions/provider-local:latest
 - europe-docker.pkg.dev/gardener-project/releases/gardener/gardenlet -> europe-docker.pkg.dev/gardener-project/releases/gardener/gardenlet:latest
 - europe-docker.pkg.dev/gardener-project/releases/gardener/resource-manager -> europe-docker.pkg.dev/gardener-project/releases/gardener/resource-manager:latest
 - europe-docker.pkg.dev/gardener-project/releases/gardener/node-agent -> europe-docker.pkg.dev/gardener-project/releases/gardener/node-agent:latest
Some taggers failed. Rerun with -vdebug for errors.
Checking cache...
 - europe-docker.pkg.dev/gardener-project/releases/gardener/apiserver: Found Remotely
 - europe-docker.pkg.dev/gardener-project/releases/gardener/controller-manager: Found Remotely
 - europe-docker.pkg.dev/gardener-project/releases/gardener/scheduler: Found Remotely
 - europe-docker.pkg.dev/gardener-project/releases/gardener/admission-controller: Found Remotely
 - europe-docker.pkg.dev/gardener-project/releases/gardener/extensions/provider-local: Not found. Building
 - europe-docker.pkg.dev/gardener-project/releases/gardener/gardenlet: Found Remotely
 - europe-docker.pkg.dev/gardener-project/releases/gardener/resource-manager: Found Remotely
 - europe-docker.pkg.dev/gardener-project/releases/gardener/node-agent: Found Remotely
Starting build...
Building [europe-docker.pkg.dev/gardener-project/releases/gardener/extensions/provider-local]...
Using base cgr.dev/chainguard/static:latest@sha256:45346401d4619bb419d412e9f6cf6723e2a914219c4adc21c699d7616cfe9c69 for github.com/gardener/gardener/cmd/gardener-extension-provider-local
Using build config europe-docker.pkg.dev/gardener-project/releases/gardener/extensions/provider-local for github.com/gardener/gardener/cmd/gardener-extension-provider-local
Building github.com/gardener/gardener/cmd/gardener-extension-provider-local for linux/amd64
Unexpected error running "go build": exit status 2
invalid value "<no value>" for flag -ldflags: missing =<value> in <pattern>=<value>
usage: go build [-o output] [build flags] [packages]
Run 'go help build' for details.
build [europe-docker.pkg.dev/gardener-project/releases/gardener/extensions/provider-local] failed: could not build and publish ko image "europe-docker.pkg.dev/gardener-project/releases/gardener/extensions/provider-local": failed to publish ko image: error building "ko://github.com/gardener/gardener/cmd/gardener-extension-provider-local": build: go build: exit status 2

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.92.0-dev
- Kubernetes version (use `kubectl version`): v1.92.0-dev
- Cloud provider or hardware configuration:
- Others:

**Comment by acumino** [comment]
I am assuming you followed [this](https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally.md) guide, seems you have missed the step to run [make kind-up](https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally.md#setting-up-the-kind-cluster-garden-and-seed) before running `make gardener-up`.

**Comment by jaythamke** [comment]
As mentioned by @acumino , please follow the instructions from [getting_started_locally.md](https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally.md). The local run guide uses Skaffold so you do not have to explicitly use Skaffold utility.
Please make sure to allocate more resources (CPU > 8 and Memory > 16) to your VM/Ubuntu server (non-docker desktop env).

Use following command to get the current resources used by docker daemon on your server.
```bash
$ docker system info -f 'CPU: {{.NCPU}}, TOTAL MEMORY: {{.MemTotal}} Bytes'
```
