### ISSUE TITLE
Add e2e tests for DWD in g/g

### ISSUE THREAD

**Issue by rishabh-11** [gardener/gardener#9535]
**How to categorize this issue?**

/area performance
/area quality
/kind test
/priority 3

**What would you like to be added**:
We need to add e2e tests in g/g for DWD.

**Why is this needed**:

The current problem that we have is for DWD to work as expected, there are specific changes done in g/g (See https://github.com/gardener/gardener/pull/9072 and https://github.com/gardener/gardener/pull/9339). The problem is any change made in DWD might require a change in g/g as well (like in the case of https://github.com/gardener/dependency-watchdog/pull/106 we needed to adapt g/g to give node access permissions for DWD service account, which we forgot to do before making a DWD release). If we had e2e tests for DWD in g/g this problem will not happen as it will be caught before the new version of DWD is merged in g/g.

**Comment by acumino** [comment]
Wouldn't it be better to add the test in DWD instead, extensions that need to test functionality specific to the extension add e2e tests in their own repo. You can check one such example [here](https://github.com/gardener/gardener-extension-registry-cache/tree/main/test/e2e).
