### ISSUE TITLE
Reduce Control Plane Requests

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#9562]
**What do you suggest to change**:
- KAPI
  - [x] Reduce KAPI HVPA `minAllowed` for memory (there isn't one for CPU anyway) from `400M` down to `200M`: https://github.com/gardener/gardener/pull/9654
  - [x] Change KAPI HVPA maximum number of replicas and set them from 4 to 3 to better match HA clusters in 3 zones (we believe we do not need 4, if under VPA anyway, so let's get rid of that odd number): https://github.com/gardener/gardener/pull/9605
  - [x] Quick-fix vertical scaling after KAPIs reach 4 (3 if the above gets implemented) replicas and then going below (can then only happen for non-HA clusters), effectively freezing the vertical scaling (wasting resources from then onwards).
  - [x] [Replace HVPA with HPA and VPA on CPU and metrics](https://github.com/gardener/gardener/pull/9678) (both on both):
    - Dropped: ~~Temporary solution: https://sap-ti.slack.com/archives/C017KSLTF4H/p1713531512758829~~
    - Accepted: Actual solution: https://gist.github.tools.sap/D043832/2051e639cf77d878f188234125c915f6
    - On Hold: ~~Amending solution: [GEP-23](https://github.com/gardener/gardener/blob/master/docs/proposals/23-autoscaling-kube-apiserver-via-independent-hpa-and-vpa.md) tracked [here](https://github.tools.sap/kubernetes/autoscaling-backlog/issues/15)~~
  - [x] Promote the `VPAAndHPAForAPIServer` feature gate
    - [x] Promote to beta: https://github.com/gardener/gardener/pull/10207
    - [x] Promote to GA: https://github.com/gardener/gardener/pull/10599
    - [x] Remove the feature gate. Clean up the related code after the feature gate removal: https://github.com/gardener/gardener/pull/10853
- KCM:
  - [x] Reduce KCM HVPA `minAllowed` for memory (there isn't one for CPU anyway) from `100M` down to `50M`: https://github.com/gardener/gardener/pull/9654

**Why is this needed**:
Primarily KAPIs but also other components waste too many resources. It would be great to address these problems, especially for KAPIs until [GEP-23](https://github.com/gardener/gardener/blob/master/docs/proposals/23-autoscaling-kube-apiserver-via-independent-hpa-and-vpa.md) lands.

**Comment by ialidzhikov** [comment]
/close
as all subtasks are resolved now
