### ISSUE TITLE
CCM on Alicloud does not expose metrics via HTTPS for Kubernetes version 1.13+

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener#963]
Prometheus is firing the false positive alert `CloudControllerManagerDown` for all Alicloud shoot clusters with kubernetes version 1.13+. This is because the CCM on Alicloud does not support exposing its metrics via HTTPS. Prometheus tries scraping via HTTPS and gets an HTTP response causing an error. Prometheus then thinks that the CCM is down because it got no metrics and an error.

**Comment by jia-jerry** [comment]
Thank you for supporting Alicloud clusters. This is because ccm is implemented by Alicloud https://github.com/kubernetes/cloud-provider-alibaba-cloud. It is based on earlier version of Kube lib. Can we change prometheus scape settings?

**Comment by wyb1** [comment]
We could change the scrape settings in Prometheus but that would be an infrastructure specific change. What do you think @rfranzke?

**Comment by rfranzke** [comment]
I guess that's fine ATM. We will anyway need an extensibility concept for monitoring/logging as well.
