### ISSUE TITLE
Add VPA Policy Configuration per Component

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener#969]
**What would you like to be added**:
Currently the Gardener decides what VPA policy to use when deploying the CP components. It would be great to allow the Gardener administrator to set the VPA policy per component in the Gardener configuration configmap.

**Why is this needed**:
This will allow the Gardener administrator to have a fine grained controller on how VPA is used in the landscape.

**Comment by rfranzke** [comment]
@afritzler Can you elaborate more about concrete use-cases?
@wyb1 Do you think it makes sense to implement this?

**Comment by afritzler** [comment]
Gosh that is an old one. I think we can close this one again. Can't remember what the exact problem was.
