### ISSUE TITLE
Expose Gardener Metrics/Dashboard in (our) Kubify Clusters

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#97]
While @afritzler has integrated a monitoring stack into https://github.com/gardener/kubify, @dkistner has exposed a metrics endpoint in the Gardener and created a dashboard for it.

How can we bring both together now, via configuration in one of our Kubify-created clusters/landscapes?

**Comment by afritzler** [comment]
1. Do we need a custom scrape configuration for prometheus? 
2. Custom dashboards need to be uploaded manually at the moment into Grafana :( I have this on our todo list to integrate an automatic upload of non standard dashboards. (same is true for non standard prometheus scape config and alerting rules)

**Comment by dkistner** [comment]
We have introduced a generic scrape job for pods called ''kubernetes-pods-by-annotation'' in Prometheus on kubify clusters. But this job will only scrape pods with proper annotations in the ``kube-system`` namespace [see here](https://github.com/gardener/kubify/blob/master/modules/seed/addons/monitoring/templates/prometheus-config.yaml#L177). 

We could also extend the job to watch on other namespaces. But then we have to annotate the Gardner deployment accordingly. But the problem with custom dashboards and also prometheus alert configs and altermanager rules still remains.

**Comment by vlerenc** [comment]
Well, can it be scripted? We have the landscape setup/[`plow` script](https://github.wdf.sap.corp/kubernetes-dev/landscape-dev-garden/blob/master/plow) (for now, but something similar will remain). Then we wouldn't mind "some additional steps" until we find better suited ways.

**Comment by dkistner** [comment]
Sure, we could update the configmaps, which contains the configurations for Prometheus and Grafana,  within the script, by appending the dashboard definition and the scrape config.

We have an update mechanism available, which applies the changes on those configmaps automatically to Grafana and Prometheus.

**Comment by vlerenc** [comment]
Good, then that's another topic to add to the landscape setup (cc @rfranzke, who is at present keeping track of the open issues for the landscape setup).

**Comment by vlerenc** [comment]
Closing as duplicate.
