### ISSUE TITLE
Shorten name of ingress controller when ingress controller addon enabled - limiting shoot cluster name to only 13 characters currently

### ISSUE THREAD

**Issue by dnlvanco** [gardener/gardener#9895]
**How to categorize this issue?**

/area usability
/kind enhancement

**What would you like to be added**:

DESCRIPTION:
If the ingress controller addon is enabled by the customer for the shoot,
the nginx ingress controller is created with a helm release name nginx-ingress-controller.
The resulting service name on the OnMetal side will look like this:
`shoot--<projectname>--<shootname>-addons-nginx-ingress-controller-<hash>`
This name however cannot be longer that 63 characters, otherwise the ingress won't be functional.
This leaves 13 characters for the customer for the project name + shoot name.
There are multiple ways how to solve this:

-       Change the generation of the service name 
-       Shorten the ingress name

**Why is this needed**:

In real production customers really like to have longer shoot cluster names than 13 characters, where they can use few characters to specify environment stage and few characters purpose of cluster etc. Current limit is really annoying. This could help increase customer experience a lot.

**Comment by ialidzhikov** [comment]
> The resulting service name on the OnMetal side will look like this:
> `shoot--<projectname>--<shootname>-addons-nginx-ingress-controller-<hash>`

The Service of the nginx-ingress addon should be `addons-nginx-ingress-controller`.
I don't know from where the `shoot--<projectname>--<shootname>-addons-nginx-ingress-controller-<hash>` Service comes from. Can you check on your side? Or is this the LB name in the underlying infrastructure?
The corresponding source code:
https://github.com/gardener/gardener/blob/452b244a15382906aaf6de73356a9d98f159f0fd/pkg/component/networking/nginxingress/nginxingress.go#L801-L813


> In real production customers really like to have longer shoot cluster names than 13 characters, where they can use few characters to specify environment stage and few characters purpose of cluster etc. Current limit is really annoying. This could help increase customer experience a lot.

The nginx-addon is deprecated and not recommended for productive usage. You cannot enable the addon for Shoots with `.spec.purpose=production`. The addon still exists to make testing of Ingress resources easy for evaluation clusters.

The deprecation message from the Gardener dashboard about the nginx-ingress addon:
> The default ingress controller has a static configuration and a conservative size, which cannot be changed. For production clusters, we recommend installing an alternative ingress controller of your choice, which you can freely configure, program, and scale according to your production needs.
