### ISSUE TITLE
[CPE] Optimize rolling update of Nodes with more volumes

### ISSUE THREAD

**Issue by PadmaB** [gardener/gardener#993]
# Improvement
Optimize the time taken for the rolling update of Nodes with higher number of Volumes attached. The nodes in the SEED clusters have an average of 10+ volumes per Node

Tests across cloud providers show that GCP and OpenStack are better than AWS and Azure in the attach and detach operations. AWS performs better than GCP during attach while GCP outperforms heavily during detach

**Impact**

- ETCD downtime could be longer during rolling updates of the SEED clusters
- Also applicable for the workloads of the stakeholders in the SHOOT clusters

# Approach
Improvements in the CSI wouldn't suffice and a more generic approach will be required. Also the solution is not restricted to the control plane components alone - the workloads on the Shoot clusters could face similar impact depending on the number of volumes attached to their Nodes

**Short-term**
MCM could serialize the eviction of pods with volumes, maybe via a drain controller

**Comment by vlerenc** [comment]
Maybe it could have 2 queues, one that works in parallel and deals with all pods that have no PVs and one that works serially and one-by-one evicts pods with PVs. Maybe it is sufficient to wait for the pod to be evicted and the PV to be successfully detached before the next one is processed, but maybe the controller would have to wait for the attach to complete, too. That however would be ugly / a very ugly dependency as there is no guarantee that this will even work (pod scheduling or attach may be blocked by unrelated reasons). Hopefully, waiting for the detach operation to complete puts a sufficient brake on the "flow of pods" that it will lead to quasi-serialised attach operations (we put a brake on the pods that leave a node, so the inflow of pods on the other/new nodes will be slowed down).

**Comment by rfranzke** [comment]
Closing as respective improvements were implemented in the g/machine-controller-manager.
