### ISSUE TITLE
Garden control plane: Specify preemption priority class for extension admission controllers

### ISSUE THREAD

**Issue by andrerun** [gardener/gardener#9936]
**How to categorize this issue?**
/area control-plane
/kind enhancement

**What would you like to be added**:
The following is in the context of the garden control plane: Currently extension admission controllers do not specify preemption priority class and run with priority=0. Ideally, we'd like to avoid the extra latency and potential timeout faults resulting from admission controller preemption.

**Why is this needed**:
Reduce the frequency of webhook latency spikes caused by admission controller preemption.

**Comment by timuthy** [comment]
Could you elaborate what you'd like to see being added by `gardener/gardener` @andrerun, a new priority class? 
There is already https://github.com/gardener/gardener/blob/master/docs/development/priority-classes.md#priorityclasses-for-garden-control-plane-components, e.g. `gardener-garden-system-400` sounds reasonable?!

**Comment by andrerun** [comment]
I think the existing classes would work well.

I agree with you that `gardener-garden-system-400` sounds like the reasonable choice. The other class where I see an admission controller is `gardener-garden-system-300`, which we apparently use for VPA's admission controller. To me, 400 seems the reasonable default, with 300 being a possible choice for admission controllers which are less time-sensitive.

**Comment by timuthy** [comment]
Any suggestion what we should do with this issue @andrerun? Admission controller charts need to be adjusted to allow the value of `priorityClass`, but do you want to track the status of each one here or should be close it and you just adjust the extensions one by one ... ?

**Comment by andrerun** [comment]
For simplicity, I'd say: keep just this issue, and then the implementer(s) can decide. I won't be doing the actual implementation. I'm filing the issue as someone who stumbled upon it, not as a first step of a specific plan to fix it.
