### ISSUE TITLE
vpa-admission-controller: Add observability and alerting

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#9954]
**How to categorize this issue?**

/area auto-scaling
/kind enhancement

**What would you like to be added**:
- [x] Configure prometheus to scrape the vpa-admission-controller metrics: https://github.com/gardener/gardener/pull/10033
- [x] Add plutono dashboards based on the metrics: https://github.com/gardener/gardener/pull/10741
- [x] ~~Add alerts~~

**Why is this needed**:
In a recent VPA related outage (ref https://github.com/kubernetes/autoscaler/issues/6884), we noticed that we are missing observability for the vpa-admission-controller component. For example:
- we don't have a panel showing the response times of the component
- we don't have alerts if the vpa-admission-controller response time > 10s (the webhook's timeout).

**Comment by voelzmo** [comment]
Given we contextified the admission-controller, such that response times >10s shouldn't be catastrophic anymore, I'm nor sure if we still need the alerting. @ialidzhikov WDYT?

**Comment by ialidzhikov** [comment]
@voelzmo , shouldn't we let https://github.com/gardener/gardener/pull/10741 close this issue? Sorry that I didn't manage to check it so far.

> Given we contextified the admission-controller, such that response times >10s shouldn't be catastrophic anymore, I'm nor sure if we still need the alerting. @ialidzhikov WDYT?

Agree, if we don't have good ideas for alerts let's don't add any for now.

**Comment by ialidzhikov** [comment]
/close
as the subtasks are completed
