### ISSUE TITLE
`Reversed VPN OpenVPN Server (HA)` and `Reversed VPN Envoy Proxy` dashboards show no data

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#9958]
**How to categorize this issue?**

/area monitoring
/kind bug

**What happened**:
![Screenshot 2024-06-11 at 17 17 34](https://github.com/gardener/gardener/assets/9372594/139921b0-4778-4f44-a9f7-cf1085a177d5)

![Screenshot 2024-06-11 at 17 18 18](https://github.com/gardener/gardener/assets/9372594/a42e1a28-7464-44d8-894d-3e7338614090)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an HA cluster
2. Make sure that the `Reversed VPN OpenVPN Server (HA)` dashboards don't show any data

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.96.3
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by oliver-goetz** [comment]
/close
#10035 fixes the issue.
