### ISSUE TITLE
SSH Key Pair Rotation for Worker Nodes Fails to Update `authorized_keys`

### ISSUE THREAD

**Issue by petersutter** [gardener/gardener#9966]
**How to categorize this issue?**

/area security
/kind bug

**What happened**:
When triggering the SSH Key Pair rotation for Worker Nodes once, the file `/home/gardener/.ssh/authorized_keys` on the node only contains the old SSH key (which can now be found in Secret `<shootname>.ssh-keypair.old`). The new SSH key in `<shootname>.ssh-keypair` is not added to the `authorized_keys` list. When rotating again, you are not able to access the node anymore via SSH (as the initial SSH key is still in the file but not anymore accessible via the `.ssh-keypair` secrets).

**What you expected to happen**:
The new SSH key should be added to the `authorized_keys` file on the node during the first rotation, ensuring continued SSH access.

**How to reproduce it (as minimally and precisely as possible)**:
1. Trigger SSH Key Pair rotation for Worker Nodes.
2. Check the `/home/gardener/.ssh/authorized_keys` file on the node.
3. Observe that only the old SSH key is present.
4. Rotate the SSH Key Pair again.
5. Attempt to access the node via SSH and observe the failure.

**Anything else we need to know?**:
N/A

**Environment**:
- Gardener version: v1.96.3
- Kubernetes version (use `kubectl version`): 1.29.3
- Cloud provider or hardware configuration: `aws`
- Others: N/A

**Comment by dongyingbo** [comment]
Any plan to fix it please?
Thanks
