### ISSUE TITLE
Use only one IDP for monitoring and logging

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#999]
# Use one IDP for monitoring and logging

## Problem

At the moment operators can access logging and monitoring components which are exposed via Ingress and Basic Authentication:

```console
   +------+
   | USER |
   +--+---+
      |
      | Basic Auth
      |
      v
 +----+----+
 |  Nginx  |
 | Ingress |
 +----+----+
      |
      |
      |
      v
+-----+------+
| Prometheus |
+------------+
```

Basic Authentication is plagued by has many issues, not limited to, password-sharing, need for revocation when user is removed from the `Project`, subject to brute force attacks, impossible to enforce Multi-factor authentication and more.

A more elegant solution can be deployed, using Authentication and Authorization proxies which validate requests agains the Gardener IDP (dex in most cases) and the Gardener K8S API Server.

### Goals

- Have only one identity authentication source for monitoring and logging components.
- Remove basic authentication for those components.
- Enforce authorization via `SubjectAccessReview` against the Garden cluster.

### Non-goals

- Network connectivity Garden cluster -> Seed cluster components is out of scope.

### Authentication

End-users accessing the dashboard authenticate via OAuth and the Dashboard is connected to OpenID Connect provider such as Dex.

We want to use the same mechanism to authenticate users. Because Prometheus and other components don't support OIDC configurations we are forced to use proxies.
There are several implementations for this and [OAuth Proxy](https://github.com/pusher/oauth2_proxy) can be used as an example.

The flow goes like this (with some steps skipped for simpicity):

1. User enters `https://prometheus.myshoot.seed-one.gardener.cloud` in browser.
1. The request goes via Nginx to the the `OAuth Proxy`.
1. Because there is no session cookie, `OAuth Proxy` redirects user to Dex at `https://dex.gardener.cloud`.
1. User authenticates succesfuly and its redirected back to `https://prometheus.myshoot.seed-one.gardener.cloud/oauth2/callback` where the access token is exchanged for ID token.
1. Session cookie is set in user's browser, which expires after some time.
1. User is redirected back to `https://prometheus.myshoot.seed-one.gardener.cloud`
1. `OAuth Proxy` proxies the connection to `Prometheus` container. `Prometheus` only listens on `localhost`.

```console
                                          +------+
                                          | USER |
                                          +--+---+
                                             |
                                             |
                                             |
                                             v
                                        +----+----+
                                        |  Nginx  |
                                        | Ingress |
                                        +----+----+
                                             |
                                    +----------------------------+
              1. Redirect Browser   |        |    Prometheus Pod |
+-----------+     + Authenticate    |        v                   |
|           |                       |   +----+--------+          |
|           +<--------------------------+ OAuth Proxy |          |
|    Dex    |                       |   |             |          |
|           +-------------------------->+             |          |
|           |                       |   +------+------+          |
+-----------+  2. Receive ID token  |          |                 |
                                    |          | 3. Proxy        |
                                    |          v                 |
                                    |   +------+-----+           |
                                    |   | Prometheus |           |
                                    |   +------------+           |
                                    |                            |
                                    +----------------------------+
```

In order for this flow to work two configurations are needed.

- New OAuth client must be added in Dex (or any OIDC provider) with redirect URL pointing to the oauth2 callback endpoint of `OAuth Proxy` - `https://prometheus.myshoot.seed-one.gardener.cloud/oauth2/callback`
- `client_id` and `client_secret` from said client must be configured on `OAuth Proxy` and `OIDC issuer URL` (`https://dex.gardener.cloud`) must be added.

> Note: As the authentication step can be done the same way for all Shoot clusters in a Seed, the OAuthProxy component can be deployed as a stand-alone deployment.

### Authorization

Now that we have successfuly authenticated our user, authorization must be executed. The ID token from Dex only provides us with some basic identity information:

```json
{
  "iss": "https://dex.gardener.cloud",
  "sub": "CiQwOGE4Njg0Yi1kYjg4LTRiNzMtOTBhOS0zY2QxNjYxZjU0NjYSBWxvY2Fs",
  "aud": "seed-one-oauth",
  "exp": 1557571686,
  "iat": 1557485286,
  "at_hash": "rFl80YaYUdGkinXtW_Cq7A",
  "email": "user@example.com",
  "email_verified": true,
  "name": "user"
}
```

as the source of truth for Authorization is the K8S APIServer, then a `SelfSubjectAccessReview` call [must be make](https://kubernetes.io/docs/reference/access-authn-authz/authorization/#checking-api-access) like:

```console
kubectl create -f - -o yaml << EOF

apiVersion: authorization.k8s.io/v1
kind: SelfSubjectAccessReview
spec:
  resourceAttributes:
    group: garden.sapcloud.io
    resource: shoots
    verb: update
    namespace: my-project-namespace
    resourceName: my-shoot
EOF
```

There is already a project which does that - [RBAC Proxy](https://github.com/brancz/kube-rbac-proxy).

With it installed and configured to talk against the K8S API server in the Gardener cluster the flow is:

1. User enters `https://prometheus.myshoot.seed-one.gardener.cloud` in browser.
1. The request goes via Nginx to the the `OAuth Proxy`.
1. Because there is no session cookie, `OAuth Proxy` redirects user to Dex at `https://dex.gardener.cloud`.
1. User authenticates succesfuly and its redirected back to `https://prometheus.myshoot.seed-one.gardener.cloud/oauth2/callback` where the access token is exchanged for ID token.
1. Session cookie is set in user's browser, which expires after some time.
1. User is redirected back to `https://prometheus.myshoot.seed-one.gardener.cloud`
1. `OAuth Proxy` proxies the connection to `RBAC Proxy` (which listens only on `localhost`) container and sends the ID token via `Authorization: Bearer` Header.
1. `RBAC proxy` receives the request and does a `SubjectAccessReview` request against the K8S API in the Gardener cluster which succeeds.
1. `RBAC proxy` then caches the authz descision and passes the connection to `Prometheus`.

```console
                                                        +------+
                                                        | USER |
                                                        +--+---+
                                                           |
                                                           |
                                                           |
                                                           v
                                                      +----+----+
                                                      |  Nginx  |
                                                      | Ingress |
                                                      +----+----+
                                                           |
                                                  +----------------------------+
                            1. Redirect Browser   |        |    Prometheus Pod |
              +-----------+     + Authenticate    |        v                   |
              |           |                       |   +----+--------+          |
              |           +<--------------------------+ OAuth Proxy |          |
              |    Dex    |                       |   |             |          |
              |           +-------------------------->+             |          |
              |           |                       |   +------+------+          |
              +-----+-----+  2. Receive ID token  |          |                 |
                    ^                             |          | 3. Proxy        |
                    |                             |          |   + ID token    |
                    |                             |          |                 |
                    |                             |          v                 |
              +-----+-----+                       |   +------+-------+         |
Uses Dex as   |           |4. SubjectAccessReview |   |              |         |
OIDC provider | K8S  API  |                       |   |  RBAC Proxy  |         |
              |  Server   +<--------------------------+              |         |
              |           |                       |   +------+-------+         |
              |           |                       |          |                 |
              +-----------+                       |          | 5. Proxy        |
                                                  |          |                 |
                                                  |          v                 |
                                                  |   +------+-----+           |
                                                  |   | Prometheus |           |
                                                  |   +------------+           |
                                                  |                            |
                                                  +----------------------------+

```

## Alternatives

Alternative solutions for Authorization might include using Istio's [ServiceRole and RoleBinding](https://istio.io/docs/tasks/security/rbac-groups/), but this requires to have a controller which reconsiles K8S `ClusterRole` + `Role` to  istio's `ServiceRole` and `ClusterRoleBinding` + `RoleBinding` to istio's `ServiceRoleBinding`.

**Comment by SayakMukhopadhyay** [comment]
Is this issue being worked upon? I was planning to solve the same issue in my cluster and was interested in contributing.

**Comment by mvladev** [comment]
@SayakMukhopadhyay I'm not working on it at the moment. Any contributions are welcomed.

**Comment by SayakMukhopadhyay** [comment]
I have managed to put the `garden-grafana` and `garden-prometheus` behind a OAuth proxy instead of Basic Auth. I have used `oauth2-proxy` and connected with the existing dex service and have got a nice flow going. Right now, the OAuth works in the ingress level so people with access to Gardener dashboard will have access to Grafana/Prometheus too.

I am willing to contribute to this issue but my current solution does not have the architecture proposed above. Still I think its a good starting point. I would like to discuss the architecture in here or in Slack, whichever is preferred.

**Comment by ThormaehlenFred** [comment]
Hello @mvladev , does this issue still exist?

**Comment by mvladev** [comment]
Yes, it's not fixed.

**Comment by timebertt** [comment]
I don't think anyone is working on this right now, so
/unassign mvladev ThormaehlenFred marwinski 

However, there are some ideas floating around and brainstorming meetings happening (cc @istvanballok @wyb1)
/touch

**Comment by rfranzke** [comment]
Follow-up issue: https://github.com/gardener/gardener/issues/8416
