### ISSUE TITLE
[development] Check Imports ignores all source files effectively checking nothing

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#9992]
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What happened**:
Check Imports ignores all source files effectively checking nothing.
Logs of the `make check` shows that the `import-boss` ignores all configured directories https://github.com/gardener/gardener/blob/85ad75bd203577ccf5e67f415a77d261d79ca49f/Makefile#L152

```bash
...
> Check Imports
W0617 16:12:45.018087   70042 parse.go:247] Ignoring directory github.com/gardener/gardener/cmd: No files for pkg "github.com/gardener/gardener/cmd"
W0617 16:12:48.919020   70042 parse.go:247] Ignoring directory github.com/gardener/gardener/extensions: No files for pkg "github.com/gardener/gardener/extensions"
W0617 16:12:48.945522   70042 parse.go:247] Ignoring directory github.com/gardener/gardener/pkg: No files for pkg "github.com/gardener/gardener/pkg"
W0617 16:12:49.108970   70042 parse.go:247] Ignoring directory github.com/gardener/gardener/plugin: No files for pkg "github.com/gardener/gardener/plugin"
W0617 16:12:49.114224   70042 parse.go:247] Ignoring directory github.com/gardener/gardener/test: No files for pkg "github.com/gardener/gardener/test"
W0617 16:12:49.270422   70042 parse.go:247] Ignoring directory github.com/gardener/gardener/third_party: No files for pkg "github.com/gardener/gardener/third_party"
...
```  

**What you expected to happen**:
Import check to not ignore the source files of gardener. 

**How to reproduce it (as minimally and precisely as possible)**:
Run `make check`. 

**Anything else we need to know?**:
I guess it is somehow related to the virtual go path or prefixing the configured dirs with the module name https://github.com/gardener/gardener/blob/85ad75bd203577ccf5e67f415a77d261d79ca49f/hack/check-imports.sh#L33

**Environment**:

- Gardener version: 85ad75bd203577ccf5e67f415a77d261d79ca49f
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by vpnachev** [comment]
Looks like the check-imports was already ignoring the files before the removal of the vendor folder. 
At least when I run `make check` from 328f202a312de139bb9ae80378c3641c254850c3, I see the same logs 

```
> Check Imports
W0617 16:34:35.800349    6058 parse.go:247] Ignoring directory github.com/gardener/gardener/cmd: No files for pkg "github.com/gardener/gardener/cmd"
W0617 16:34:41.614182    6058 parse.go:247] Ignoring directory github.com/gardener/gardener/extensions: No files for pkg "github.com/gardener/gardener/extensions"
W0617 16:34:41.634248    6058 parse.go:247] Ignoring directory github.com/gardener/gardener/pkg: No files for pkg "github.com/gardener/gardener/pkg"
W0617 16:34:41.833862    6058 parse.go:247] Ignoring directory github.com/gardener/gardener/plugin: No files for pkg "github.com/gardener/gardener/plugin"
W0617 16:34:41.846382    6058 parse.go:247] Ignoring directory github.com/gardener/gardener/test: No files for pkg "github.com/gardener/gardener/test"
W0617 16:34:42.030385    6058 parse.go:247] Ignoring directory github.com/gardener/gardener/third_party: No files for pkg "github.com/gardener/gardener/third_party"
```

**Comment by oliver-goetz** [comment]
The output is misleading, but `import-boss` seems to work.
When you comment an `allowedPrefix` in an `.import-restrictions` file (e.g. [here](https://github.com/gardener/gardener/blob/master/pkg/operator/.import-restrictions)), the step fails.

**Comment by vpnachev** [comment]
Thanks for looking into it, if I find some time, I will try to report the issue to k8s community with minimal reproducible scenario. 

/close
